package http

import (
	"bytes"
	"encoding/json"
	"errors"
	"io"
	"net/http"
	"os"
	"strings"

	"github.com/sainteye/clawdline/internal/adapters/projectfiles"
	"github.com/sainteye/clawdline/internal/adapters/store"
)

// projectFilesRoute takes only a current place id and a file id generated by
// that place's inventory. No client-supplied filesystem path is opened.
func (s *Server) projectFilesRoute(w http.ResponseWriter, r *http.Request, placeID, fileID string) {
	if r.URL.RawQuery != "" {
		writeRefusal(w, 400, "bad_request", "Project files take no query fields.")
		return
	}
	if fileID == "" && r.Method != http.MethodGet || fileID != "" && r.Method != http.MethodGet && r.Method != http.MethodPut {
		writeRefusal(w, 405, "method_not_allowed", "Read with GET or save one file with PUT.")
		return
	}
	project, found := s.workV2Project(r.Context(), placeID)
	if !found {
		writeRefusal(w, 404, "project_not_found", "Choose a Project that this machine currently lists.")
		return
	}
	home, err := os.UserHomeDir()
	if err != nil {
		writeRefusal(w, 503, "home_unavailable", "This machine's home directory is unavailable.")
		return
	}
	if r.Method == http.MethodGet {
		if r.ContentLength > 0 {
			writeRefusal(w, 400, "bad_request", "A Project file read takes no body.")
			return
		}
		if fileID == "" {
			list, err := projectfiles.List(project.Path, home)
			if err != nil {
				writeProjectFileRefusal(w, err)
				return
			}
			writeJSON(w, list)
			return
		}
		content, err := projectfiles.Read(project.Path, home, fileID)
		if err != nil {
			writeProjectFileRefusal(w, err)
			return
		}
		writeJSON(w, content)
		return
	}
	if !maySend(r) {
		writeRefusal(w, 403, "forbidden", "This device may read Project files but cannot save them.")
		return
	}
	key := strings.TrimSpace(r.Header.Get("Idempotency-Key"))
	if key == "" {
		writeRefusal(w, 400, "bad_request", "Saving a file needs an Idempotency-Key.")
		return
	}
	body, err := io.ReadAll(io.LimitReader(r.Body, projectfiles.MaxWriteBytes+1))
	if err != nil {
		writeRefusal(w, 400, "bad_request", "The file update could not be read.")
		return
	}
	if len(body) > projectfiles.MaxWriteBytes {
		writeRefusal(w, 413, "body_too_large", "The file update is too large.")
		return
	}
	var input struct {
		ExpectedVersion string `json:"expected_version"`
		Content         string `json:"content"`
	}
	dec := json.NewDecoder(bytes.NewReader(body))
	dec.DisallowUnknownFields()
	if err := dec.Decode(&input); err != nil || dec.Decode(new(any)) != io.EOF || input.ExpectedVersion == "" {
		writeRefusal(w, 400, "bad_request", "Supply the expected version and text content.")
		return
	}
	// Include the body in the receipt digest. A reused key with different text
	// must not replay a successful write of the previous text.
	receipt := store.ReceiptKey{Scope: scopePlaces, Actor: accessOf(r).verdict.Device, Key: key}
	s.receipted(w, r, receipt, requestDigest([]byte(r.Method), []byte(routePath(r)), body),
		func(status int) bool { return status != http.StatusTooManyRequests },
		func(w http.ResponseWriter) {
			content, err := projectfiles.Save(project.Path, home, fileID, input.ExpectedVersion, input.Content)
			if err != nil {
				writeProjectFileRefusal(w, err)
				return
			}
			writeJSON(w, content)
		})
}

func writeProjectFileRefusal(w http.ResponseWriter, err error) {
	if errors.Is(err, os.ErrPermission) {
		writeRefusal(w, 403, "file_permission", "This file cannot be read or saved with this machine's permissions.")
		return
	}
	status, code, detail := projectfiles.Refusal(err)
	writeRefusal(w, status, code, detail)
}
