export var els = {};
["counts", "conn", "conn-label", "filter", "rows", "list-empty", "list-scroll", "ptr", "ptr-label",
 "app", "pane-detail", "back", "detail-focus", "detail-mark", "detail-name", "detail-sub", "tx", "tx-scroll",
 "session-actions", "session-actions-main", "session-actions-git", "session-actions-back",
 "session-focus", "session-info", "session-git-more", "session-git", "session-commit", "session-push", "session-end",
 "detail-actions-title",
 "action-confirm", "action-confirm-sheet", "action-confirm-title", "action-confirm-say",
 "action-confirm-cancel", "action-confirm-go",
 "tx-refresh", "tx-refresh-label", "tx-focus", "tx-focus-label", "live", "stale-shut",
 "git-panel", "git-title", "git-refresh", "git-close", "git-body",
 "shell-panel", "shell-title", "shell-stop", "shell-close", "shell-body",
 "composer", "msg", "send", "why", "waiting", "agents", "skill-menu", "stale", "stale-say", "stale-go",
 "detail-head", "agent-head", "agent-back", "agent-back-label", "agent-name", "agent-sub",
 "status-line", "status-line-open", "status-line-files", "status-line-deploy", "status-line-limits", "keys", "toast", "brand", "brand-mark",
 "settings", "settings-sheet", "settings-title", "settings-notify-title", "settings-notify-say",
 "settings-notify-go", "settings-notify-test", "settings-notify-said", "settings-version",
 "settings-close", "settings-order", "settings-order-title", "settings-order-say",
 "settings-order-label", "settings-assistant-icons", "settings-assistant-icons-title",
 "settings-assistant-icons-say", "settings-assistant-icons-marks", "settings-assistant-icons-label",
 "info", "info-sheet", "info-title", "info-say", "info-body", "info-said", "info-refresh", "info-close",
 "start-go", "start", "start-sheet", "start-title", "start-say", "start-with", "start-filter",
 "start-resume", "start-list",
 "start-said", "start-close", "starting", "starting-spin", "starting-say", "starting-close",
 "voice-go", "command", "command-sheet", "command-title", "command-say",
 "command-voice", "command-text", "command-mic", "command-draft", "command-with", "command-model",
 "command-list", "command-instructions", "command-said", "command-cancel", "command-go",
 "schedule-new", "schedule-form", "schedule-sheet", "schedule-form-title", "schedule-form-say",
 "schedule-title-label", "schedule-title", "schedule-at-label", "schedule-at",
 "schedule-days-label", "schedule-days", "schedule-where-label", "schedule-with",
 "schedule-picked", "schedule-places", "schedule-with-label",
 "schedule-first-label", "schedule-instructions",
 "schedule-more", "schedule-more-label", "schedule-close-label", "schedule-close",
 "schedule-flags", "schedule-catch-label", "schedule-catch",
 "schedule-timeout-label", "schedule-timeout", "schedule-model-label", "schedule-model",
 "schedule-said", "schedule-cancel", "schedule-go", "schedule-delete",
 "schedule-rows",
 "schedule-delete-confirm", "schedule-delete-confirm-sheet", "schedule-delete-confirm-title",
 "schedule-delete-confirm-say", "schedule-delete-confirm-cancel", "schedule-delete-confirm-go",
 "notify", "notify-go", "notify-go-label", "notify-say", "shots", "attach", "pick", "mic", "voice",
 "door", "door-mark", "door-name", "door-ask", "door-to-password", "door-digits", "door-confirm",
 "door-restart", "door-left", "door-password", "door-pw-name", "door-pw-go", "door-to-pair", "door-say"
].forEach(function (id) { els[id] = document.getElementById(id); });
