import Foundation

runCloudAccountRegressionModeIfRequested()
runCoordinatorRegistrationWorkerIfRequested()
configureTestIsolation()
runIsolationProcessProbesIfRequested()

runTestIsolationTests()
print("Clawdline tests")
runScheduledDispatchTests()
runSnippetStoreTests()
runMascotTests()
runTranscriptTests()
runMarkdownTests()
runProjectDocumentsTests()
runDevStackTests()
runHookTests()
runSessionLaunchTests()
runPlannerTests()
runPeerMessageTests()
runCodexSessionTests()
runConversationTests()
runOrchestratorDispatchTests()
runOrchestratorLandingTests()
runOrchestratorLandingQueueTests()
runOrchestratorLifecycleTests()
runOrchestratorCoordinationTests()
runSessionCloseAndQuotaTests()
runSessionRegistryTests()
runBackgroundAndStorageTests()
runOrchestratorRecoveryTests()
runCoordinatorTests()
runOrchestratorCompletionTests()
runUsageLedgerTests()
runUsagePortfolioAndLifecycleTests()
runSessionWatchTests()
runReadingFreshnessTests()
runTmuxCoexistenceTests()
runOrchestratorStoreTests()
runOrchestratorRegistryTests()
runOrchestratorDraftTests()
runCloudTestsAndFinish()
dispatchMain()
