import Foundation

// Sealed from Tests/main.swift at f32071e5, then extended only by approved feature receipts.
// Runtime validation is deliberately check-neutral: the manifest tracks current order while
// test.sh separately owns the current exact completion count.
let expectedOrderedTestGroupTitles: [String] = [
    "the test binary isolates push state even when it is launched directly",
    "the test binary isolates the drop cache even when it is launched directly",
    "schedule files are strict and carry an ordinary task template",
    "schedule fire arithmetic crosses midnight and filters days",
    "catch-up, active-task and close-tab policies are explicit",
    "no occurrence from before a schedule was made is an occurrence it missed",
    "an edit does not fire the occurrence it has just invented",
    "bad schedule files are isolated and the routes use orchestrator envelopes",
    "the settings schedule switch changes only enabled",
    "schedule records become valid and warning rows for settings",
    "a schedule made over HTTP is one the parser above would have accepted",
    "the minute timer and the answer the write route gave agree with each other",
    "one schedule can be read in full, and the write route is behind the write gate",
    "a schedule that was written says whether anything on this Mac will run it",
    "a schedule can be changed and taken away, and an edit is not a way past the parser",
    "changing and removing a schedule pass the same three gates as making one",
    "shipped packs decode and validate",
    "validation rejects malformed packs",
    "the slash menu discovers the skills Claude Code keeps on disk",
    "the slash menu reads the exact skills a Codex session started with",
    "the prompt names the assistant on the other end",
    "routine sampling interpolates and steps",
    "non-looping routines clamp at the end",
    "palette colours parse",
    "hex colours",
    "closed eyes fill with the right colour",
    "display size is independent of grid resolution",
    "hotkey specs parse",
    "iTerm session labels drop the job name and the status glyph",
    "ps output picks out real assistant processes",
    "assistant process scans distinguish absence from failure",
    "safe close consumes a fresh exact-tty observation and fails closed",
    "incomplete session inventories merge but complete ones replace",
    "ps output picks out Codex, shim and all",
    "the Codex subcommands that are not sessions are refused",
    "a Codex session may run its own app server",
    "tmux pane listing parses",
    "a hung tmux subprocess times out and is cleaned up",
    "ending a session waits for the process before it takes the tab",
    "TERM and KILL rungs stay bound to one process identity",
    "the sacrificial safe-close lifecycle never signals a replacement process",
    "ansi: plain text is left alone",
    "ansi: colours",
    "ansi: everything that is not colour is dropped",
    "ansi: bold",
    "transcript parsing",
    "versioned Clawdline notices",
    "versioned Clawdline session messages",
    "session image artifacts are owned, bounded and expire explicitly",
    "native session images render live thumbnails and explicit expiry",
    "session image artifact HTTP retrieval is typed and authenticated",
    "version 2 file-wait and handoff notices",
    "orchestrator notices preserve the model-readable completion contract",
    "both completion notices still carry the untouched-claims reminder",
    "file-wait and handoff deliveries type only the versioned envelope",
    "the Web transcript has an inert Clawdline card",
    "transcript tool summaries",
    "transcript titles",
    "transcript project directory",
    "a hook session id is an identity boundary",
    "a task marker is the fallback transcript identity",
    "transcript ownership repairs only identities it disproves",
    "transcript rendering",
    "markdown: no syntax reaches the screen",
    "markdown: headings",
    "markdown: emphasis",
    "markdown: code",
    "markdown: tables and code blocks",
    "markdown: lists",
    "markdown: links",
    "markdown: quotes and rules",
    "folding runs of tool calls",
    "the words dictation is told to expect",
    "whisper as an optional engine",
    "how long a process has been running",
    "dictating next to a dropped image",
    "nothing you typed yourself stays faded",
    "knowing when somebody has stopped talking",
    "knowing when somebody has finished, not just paused",
    "words that are not settled yet are not fully there",
    "which versions this was run against",
    "an image goes over as an image, not as a path",
    "remote images survive the terminal handoff",
    "giving the pasteboard back",
    "editing the config while the app is running",
    "paths somebody wrote in a config file",
    "the languages the interface speaks",
    "every Session work-state string crosses the typed localization contract",
    "the code-block copy button's words cross the typed localization contract",
    "dictation starts where the caret is",
    "dictation across a pause",
    "files and images dropped on the bar",
    "a dropped file is a picture on screen and a path on the wire",
    "the documented example files",
    "the project's mark and colour",
    "which project a session is in",
    "the line that says what it is doing",
    "what a session is doing, from its screen",
    "the transcript behind the README pictures",
    "newest first",
    "the transcript pane's text view",
    "devstack: a project describes its stack",
    "devstack: a file with nothing but a name still works",
    "devstack: tier 0 declares ports and nothing else",
    "devstack: garbage is refused, not guessed at",
    "devstack: the fingerprint follows the bytes",
    "devstack: the state document",
    "devstack: a state document missing its verdict still lights the dot",
    "devstack: the line worth showing out of a process's dying words",
    "devstack: which broken process the row names",
    "devstack: commands substitute rather than concatenate",
    "devstack: the documented example files",
    "stack logs: unwrapping the supervisor's envelope",
    "stack logs: the pipe a line came down, kept for the post-mortem",
    "stack logs: severity comes from the text, not the pipe",
    "stack logs: the three shapes a logs command can hand back",
    "stack logs: the timestamp every line starts with",
    "devstack: port probing",
    "the label a tab shows, without the animation on the front",
    "the machinery Claude Code injects into your turns",
    "a slash command is the one piece of that machinery somebody typed",
    "the remote server refuses the right cross-origin requests",
    "a tool result is what a command printed, not how it wanted to be coloured",
    "hooks: reading a note",
    "hooks: what a note is allowed to change",
    "hooks: editing somebody else's settings file",
    "hooks: the script itself",
    "quickURL",
    "registeredConnection",
    "complaint",
    "redacted",
    "backoff",
    "arguments",
    "TunnelMode",
    "the tunnel refuses, and every reason is a pure function of its inputs",
    "state hook: a reading is not an event",
    "a long turn keeps enough time to announce its finish",
    "state hook: the words a hook reads",
    "state hook: what a hook is told",
    "push notifications identify the session and its project",
    "a notification goes to whoever is actually blocked",
    "a fan-out is one sentence, whatever it cost",
    "smart notifications describe the completed work, not its machinery",
    "a headless assistant runs in one directory, not a new one per call",
    "a burst of finishes becomes one push, not one each",
    "smart notification health is visible where the switch is",
    "a push payload keeps the beginning of a sentence that does not fit",
    "push-service receipts distinguish acceptance from refusal",
    "a project mark small enough to be a URL",
    "state hook: finding the program",
    "a hook written as #!/usr/bin/env node has to be able to find node",
    "pairing tells a client apart from a sentence",
    "the cloudflared config we write, rather than the one that was already there",
    "which language to answer a browser in",
    "a cache stamp has to see through a symlink",
    "telling two devices with the same name apart",
    "a top-level state from the wrong vocabulary",
    "a browser token is adopted before its credential leaves the address bar",
    "the expensive remote reads take exactly one bounded side door",
    "the slow-reading gate agrees with dispatch",
    "the usage analytics gate accepts both documented read credentials",
    "usage analytics saturation is isolated from ordinary remote readings",
    "transcript backpressure is typed and independent",
    "the slow-reading depth is paired on every exit",
    "terminal writes cannot hold the remote server queue",
    "key and end terminal mutations leave health and SSE turns responsive",
    "a project folder says which directory it is, and is not taken at its word",
    "the line a new tab is given, before anything types it",
    "which terminal a session is started in, and when none of them will do",
    "the list of places, tidied",
    "the folder budget is spent on plausible places before scratch",
    "starting a session is behind the write gate, like everything else that runs code",
    "place history routes preserve their assistant from path to operation",
    "the page is given the words it draws the start sheet with",
    "restart maintenance drains the real terminal broker",
    "the planner is shown a numbered list and never a way to write a path",
    "a time and a set of days survive the trip out of a model, or do not",
    "a number the planner wrote is mapped back to a place, and nothing else is",
    "what a model printed becomes a draft, or does not",
    "how sure the planner was decides whether the page asks",
    "a draft says whether the sentence asked for a session now or one that repeats",
    "the sentence POST /v1/intents plans from, before it costs a model turn",
    "a deploy is news only when it stops running",
    "answering a menu or cycling permissions stays a closed key allowlist",
    "the key route is gated like every other write",
    "the session-title route is a bounded authenticated write",
    "a recording arrives as base64 and is refused before it costs a second of CPU",
    "Git porcelain and numstat become the web status payload",
    "every word the page can draw is a word the page is sent",
    "health and hello carry the same fields their shared handler reads",
    "ending a session is the one route that destroys something",
    "a numbered list somebody typed is not a menu",
    "rows with the session's own output under them are scrollback, not a dialog",
    "a menu read as options a finger can hit",
    "a picker drawn without numbers",
    "an unnumbered picker is answered by walking the highlight, not by typing a digit",
    "a multi-select's button is walked to with Tab, because its last row eats anything else",
    "the Submit a multi-select puts under its rows is a row of its own",
    "a multi-select's box is a fact about the row, not two characters in front of it",
    "a checkbox inside a description is text, not the header above the question",
    "the words under an option come from the transcript, which has all of them",
    "the question above a visual menu",
    "a menu row no keystroke can reach is shown and not offered",
    "what a background agent left on disk",
    "what a background agent is doing right now",
    "following an agent to its own transcript",
    "T1 queued peer envelopes become attributed peer entries",
    "T2 delivered meta peer rows use their structured origin",
    "T3 one enqueue and delivery receipt keeps the delivery",
    "T4 delayed delivery still replaces its enqueue receipt",
    "T5 distinct deliveries of the same text remain distinct",
    "T6 an enqueue receipt survives without a delivery row",
    "T7 peer envelope boundaries reject lookalikes and preserve Markdown",
    "T8 peer envelope attributes decode entities in the safe order",
    "T9 a peer turn disproves ownership just like a user turn",
    "T10 peer entries serialize their role and omit an empty source",
    "T11 a newer repeated enqueue survives an older delivery",
    "T12 one transcript carries both a peer message and a Clawdline notice",
    "T13 peer de-duplication leaves notices alone",
    "T14 an envelope quoted inside the other envelope stays what it arrived as",
    "T15 a Clawdline notice does not disprove transcript ownership",
    "T16 the two envelopes are mutually exclusive, so the order they are tried in is unobservable",
    "Codex's live line is the one with a clock in it",
    "Codex's dialogs are read by what is under them, not by the margin",
    "a rollout says where its session is working",
    "the rollout a Codex process is holding open",
    "a new Codex process never borrows an existing conversation",
    "a rollout reads as the same entries a transcript does",
    "a Codex session can be named from its first request",
    "an unnamed Claude conversation gets a durable model fallback",
    "a Codex npm shim starts with Finder's cold PATH",
    "a canonical Codex npm shim resolves to its native vendor executable",
    "the fields of a rollout, one at a time",
    "a person-named session title outranks every automatic label",
    "a session's name never comes from its terminal's tab title",
    "a name is read from what proves identity, and from nothing else",
    "a name survives its source going quiet",
    "a remembered name belongs to a conversation, not to a tab",
    "session titles are normalized, persisted and bounded",
    "renaming never changes the terminal label used to locate transcripts",
    "a person's session title belongs to the conversation, not to the tab",
    "the newest of a local name and a terminal /rename wins",
    "a config write that did not happen is not reported as saved",
    "clearing a title takes the Codex name off Clawdline's surfaces too",
    "resuming a known conversation carries its title onto the new terminal",
    "a rename is not typed into a session that is showing a menu",
    "session-title downstream synchronization never interrupts Claude",
    "which assistant a process name stands for",
    "assistant product marks load at row size",
    "the line a new tab is given names the assistant",
    "a conversation id is a UUID or it is nothing",
    "the line that picks a conversation back up",
    "Codex threads become conversations that can be picked back up",
    "what has already been said in a place",
    "an agent's turn is not the opening of a conversation",
    "what is not a conversation somebody had",
    "the first turn is found however far in it sits",
    "a rename is found wherever it was made",
    "a task.json is read before a terminal is opened for it",
    "the assistant-quota dispatch gate names the override and the age the same way "
    + "workspace_busy already does",
    "a model name is a name, not a fragment of a command line",
    "a new tab is not handed the identity of whatever launched the terminal",
    "a child row resolves only to its current parent session",
    "a public session id and task root use one process-bound identity",
    "a task keeps its per-dispatch Codex reasoning effort",
    "how far a child may go is this Mac's answer, not the asking session's",
    "the directory a child is given reach over is a path, not a fragment of one",
    "a task id is the name of a directory, so it may not be a path",
    "a worktree is named by repository and task, without accepting a path as a ref",
    "worktree cleanup chooses data preservation before disk reclamation",
    "worktree task records, briefings and shared-tree coordination stay distinct",
    "workspace overlap is a path-component relationship",
    "workspace overlap follows the whole dispatch tree",
    "declared write claims are reserved across dispatch trees",
    "a released claim key no longer counts as held",
    "the claims/release route frees paths early, guards terminal tasks, and is idempotent",
    "release compares ancestor and descendant paths like arbitration does, validates paths, "
      + "and refuses a queued task",
    "the claims/release HTTP route is orchestrator-token gated",
    "landing records enforce the root-owned state machine and keep idempotent receipts",
    "landing verification survives a disposed worktree but refuses a repository mismatch",
    "landing routes accept a matching task or machine credential and list pending obligations",
    "pending landing ownership is one fail-closed observation across list and Bearings",
    "published coordinator inventory is a direct fail-closed read",
    "cleanup retains pending landing obligations beyond the ordinary registry cap",
    "work visibility decides from git, not from anybody's memory",
    "session work state is a closed broker projection, never an idle guess",
    "a session's own declaration is bounded, typed, and can never mint a check",
    "closeability is four states, and doubt about the evidence outranks the list",
    "every broker blocker has a record that produces it, and a closure that clears it",
    "a closure attestation is bound to one process and one turn, and survives a restart",
    "the close route asks to be proven only when a client says so",
    "the closure route is closed at its edges",
    "session completion receipts are bound to the current process, not a reusable terminal",
    "a root session can report one delivered turn without becoming a child task",
    "only broker-verified target landing evidence can produce the double check",
    "the in-flight list answers what a worktree hides",
    "a session can say what it is doing without stopping to write a report",
    "a sandboxed child's progress arrives as a file, the way its result does",
    "terminal notices remind a root about unrecorded claimed work exactly where needed",
    "the terminal claims audit tells touched from untouched from gone",
    "finalize runs the claims audit and writes it into the record",
    "a directory-shaped claim is judged by recursively walking its subtree, not its own mtime",
    "claims refusals do not spend the dispatch rate budget",
    "serialized operations are acquired atomically and globally",
    "a serialized waiter survives a store round trip without a plaintext secret",
    "a queued serialized task reports its blockers and cancels immediately",
    "a queued task scans and types workspace warnings only when promoted",
    "startup pumps a recoverable serialized waiter exactly once",
    "every terminal outcome really pumps the next serialized waiter",
    "a task secret is kept as a hash and compared as one",
    "what a child's turn cost, at the prices this app knows",
    "token accounting reads only a transcript proved for its task",
    "orchestrator task states only move forward",
    "an orchestrated Claude child keeps its process identity",
    "an orchestrated child's cwd",
    "an orchestrated Claude child prefers registry identity",
    "an orchestrated child only inherits identity from this spawn",
    "an orchestrated child is briefed only at a real composer",
    "briefing delivery is verified and retries are bounded",
    "the one line a child is given",
    "a child briefing carries the whole of what a child needs, and none of what it must not",
    "a child is the bottom of the tree, and no setting can put a level under it",
    "a codex child is briefed with channels it can actually reach",
    "the graph and this Mac's own rules reach every child's briefing",
    "root assignments are a closed durable fourth primitive",
    "a handoff envelope is validated without reading its letter",
    "handoff envelopes survive restart and terminal ones are swept as one unit",
    "handoff registration opens once and shares the dispatch brake",
    "coordination waits are durable broker relationships",
    "coordination wait routes keep their credential and ownership boundaries",
    "session whoami is a machine-only exact-conversation bridge",
    "the session index a wait needs is the dispatch credential's own door",
    "session-message relay has a machine-only, idempotent door",
    "the wait session index says what a wait must name, and nothing off the screen",
    "attached follow-up tasks are single-flight broker work in a standing session",
    "a file-wait notice is not typed into a session that is showing a picker",
    "A3 owner visibility: a session row says when peers are parked on it",
    "A3 owner visibility: the page draws the same two sides as the Mac",
    "handing off is the other thing a paired device may not do",
    "a handoff request is parsed before the shared switch, and no further",
    "dispatching is the one thing a paired device may not do",
    "finishing a task takes that task's secret and nothing else",
    "the agent-notification preference defaults on, including for old config files",
    "smart notifications are an explicit quota-spending preference",
    "an agent notification is narrow, scarce and audited",
    "loading an unavailable stored transcript preserves an unrefuted identity",
    "closing a root session takes the work it dispatched with it",
    "what a linger running out decides, one instant at a time",
    "safe-close activity keeps capture failure distinct from idle",
    "linger expiry and explicit root close share one closing admission",
    "the automatic close runs closeStep against an inventory it took itself",
    "a beat with several lingering children takes one terminal walk, not one each",
    "terminal intervention type follows the returned failure, not unrelated global state",
    "a linger survives the restart that lands in the middle of it",
    "the Session info card is read off the files, and says unknown rather than 0%",
    "an assistant's quota reads as one of four values, and ages by its own rule",
    "the machine-level providers read the same file shapes /info already reads, "
    + "and the route answers with what they found",
    "resetsAt names the tightest live window rather than the earliest of any of them, and "
    + "Codex's credits rule only trusts a depleted record that is actually the newer one",
    "the dispatch gate actually reads the quota it computed, rather than only its helpers",
    "the models a session can be moved to, and the word that moves each",
    "Claude Code permission modes come from the screen and cycle in wire order",
    "the model a `/model` names, before the reply that proves it",
    "session registry: reading a file a session wrote about itself",
    "session registry: telling one process from the next one to get its number",
    "session registry: what a file is allowed to change",
    "session registry: a conversation that has moved to the background",
    "session registry: finding the session a parked tab moved into",
    "session registry: which files get read, and when a change is worth a look",
    "waiting for a subprocess does not run anything else on this thread",
    "a background command is over when its own output says so",
    "a file left behind by an interrupted command is not a command still running",
    "nothing is signalled until it is known whose process it is",
    "the list of background sessions is a list of jobs, not a question",
    "the Mac's schedule form collects fields and never checks them twice",
    "the Mac's schedule form and the file it wrote agree about what it says",
    "a save keeps the task fields no form has a control for",
    "owned storage evaluation is three-valued and fail-closed",
    "owned storage ledger records proof durably and never claims a failed append",
    "the Claude live-session source distinguishes empty from unreadable",
    "pending landing storage survives task-directory cleanup",
    "task-owned work is reclaimed on the terminal-state schedule",
    "the beat reclaims what a terminal task still owes",
    "every terminal path keeps the reclaim contract at its real filesystem boundary",
    "an isolated checkout's build output is reclaimed on its own deadline",
    "cleanup documentation describes the API and runtime contract, not registry spelling",
    "an attached follow-up goes through dispatch, and survives its own single-flight check",
    "a result's verification is read even when the summary and artifacts are already known",
    "Clawdline answers a menu only on a tab it opened itself",
    "dispatch answers an immediate tab refusal; the later pump finalizes its refusal",
    "a tab that never opened is retried from its own task file, twice and no further",
    "a dispatch that never said what it writes is warned, and one that said nothing is not",
    "an attached briefing is delivered work, not a tab still trying to open",
    "a task that has posted progress is not a tab that never opened",
    "owned storage is visible through the read-only orchestrator route",
    "child briefings put heavyweight temporary work in owned task storage",
    "verification reports are optional, bounded metadata rather than a success gate",
    "restart executor reconciliation uses exact durable identity evidence",
    "a briefed task refreshes identity before its inventory receipt is judged",
    "restart maintenance transition is durable and idempotent",
    "restart maintenance HTTP is machine-only, closed, idempotent and abortable",
    "restart reconciliation is bounded, fail-closed on corruption, and rolls back atomically",
    "durable task results settle while terminal admission is paused",
    "a coordinator is explicitly registered, durable, singleton and process-bound",
    "registration availability is a closed word derived from the durable store",
    "an offline coordinator can be rebound without changing its durable identity",
    "clock rollback cannot lower a rebound binding's freshness barrier",
    "coordinator cache observes another process's atomic creation",
    "coordinator registration is a real cross-process singleton",
    "Bearings is a closed deterministic projection without transcript data",
    "Bearings takes one coherent Orchestrator snapshot for every session fact",
    "coordinator routes require the machine token and expose no implicit takeover",
    "the reconnect route is closed, machine-only and refuses online takeover",
    "the production route preserves scan evidence across cache reads and app generations",
    "Clawdfather succession keeps every handoff and rebind boundary durable",
    "task completion ingress and delivery are durable protocol facts",
    "owned child dispatch and detached automation use different doors",
    "completion transport failure injection is typed and bounded",
    "the three ways a completion fails to arrive are each typed and each visible",
    "grandchild completion delivery is bound to the parent's exact process tuple",
    "the wait for a completion notice has an upper bound, and something re-arms it",
    "finalize saves before send, retries one notice after restart, and ACK stops it",
    "ACK save failure rolls back only its delivery transition",
    "completion HTTP schemas are closed and machine-authenticated",
    "both shipped skills teach the durable completion contract",
    "both shipped skills trigger on cross-session reports",
    "the protocol page carries the durable completion contract",
    "legacy completion reconciliation is bounded and preserves polling compatibility",
    "Coordinator evidence rejects physical ingress and follows only proved rebind aliases",
    "a settings tab taller than the screen is capped, and the overflow goes to the scroller",
    "the ledger reads every usage spelling and decides the shape by arithmetic",
    "re-reading a source never double-counts, and a boundary cuts a segment",
    "a source that cannot be read is a state, and nothing renders it as zero",
    "a cost is copied where it exists and never invented where it does not",
    "usage analytics keeps quantity semantics and privacy in one closed contract",
    "usage analytics validates filters and paginates a changing ledger stably",
    "usage analytics uses one requested timezone for day grouping and trend",
    "usage portfolio ranks canonical projects and keeps every unavailable dimension honest",
    "legacy managed-worktree Projects migrate through auditable append-only evidence",
    "usage portfolio accepts exactly one Feature head and leaves proposals or conflicts unknown",
    "a 60k-row SQLite-to-DTO usage query stays bounded and measured",
    "the SQLite analytics bound belongs to the complete matching query",
    "usage exports are spreadsheet-safe and JSON-lossless",
    "usage analytics routes keep authentication, validation and privacy aligned",
    "the shipped page contains the accessible Usage Project Portfolio",
    "the ledger agrees with the registry and the route, row by row on one task id",
    "a sealed row is corrected rather than rewritten",
    "each kind of work is counted exactly once, and the routes answer for the range",
    "finalize files a task in the ledger without being told anybody heard about it",
    "a row with one part unknown keeps its unknown through every reader",
    "a session the store had to name for itself says so on the wire",
    "a source that went backwards re-anchors instead of quietly under-counting",
    "a row marked twice keeps both marks, and both reach every reader",
    "a store written under version 1 is upgraded in place, and never orphaned",
    "the backfill files work that happened, and re-importing it changes nothing",
    "a correction is written once, however many times the evidence is re-read",
    "which reading of input won is a stored fact, not one to be re-derived",
    "the watcher decides when to read, and what a session leaves behind when it goes",
    "every main-queue crossing is a named production call site, in the source on disk",
    "every direct SessionWatch nudge call site is inventoried across production source",
    "one published Session inventory owns process evidence and bounded subprocess cleanup",
    "whoami revalidates real Claude and Codex files across fresh process passes",
    "a reading with live sessions in it reaches the ledger, both ways",
    "a manual session refresh has coherent evidence and bounded backpressure",
    "what a terminal's spend is filed under, and what the backfill hands over",
    "a warm reading is answered without asking the Mac again",
    "a stale reading goes out first and the refresh happens behind it",
    "a refused refresh ages the reading it could not replace",
    "one expensive read serves every request that arrived without one",
    "past serveFor a reading stops being an answer",
    "a request waiting on a refresh that fails is answered, not refused",
    "keys do not read each other's readings",
    "the trace separates waiting from working",
    "percentiles answer for an empty lane instead of crashing",
]

func validateExecutedTestGroupManifest() {
    if !focusedTestGroups.isEmpty { return }
    guard executedTestGroupTitles == expectedOrderedTestGroupTitles else {
        let mismatch = zip(executedTestGroupTitles, expectedOrderedTestGroupTitles)
            .enumerated().first { $0.element.0 != $0.element.1 }?.offset
        failures.append(
            "ordered test group manifest changed — executed \(executedTestGroupTitles.count), " +
            "expected \(expectedOrderedTestGroupTitles.count), first mismatch " +
            "\(mismatch.map(String.init) ?? "at the shorter list boundary")"
        )
        return
    }
}
