import Foundation

struct Korean: Copy {
    let placeholder = "Claude Code에 메시지…"

    let hintSend = "보내기"
    let hintNewline = "줄바꿈"
    let hintSwitch = "전환"
    let hintList = "목록"
    let hintMascot = "마스코트"
    let hintOutput = "출력"
    let hintFullscreen = "전체 화면"
    let hintKeys = "단축키"
    let hintTextSize = "글자 크기"
    let hintOrder = "역순"
    let hintVoice = "받아쓰기"
    func voiceListening(onDevice: Bool) -> String {
        onDevice ? "이 Mac에서 듣는 중 — 다시 누르면 중지"
                 : "듣는 중 — 이 언어는 이 Mac이 아니라 Apple이 인식합니다"
    }
    let voiceNoPermission = "받아쓰기에는 마이크와 음성 인식 권한이 필요합니다"
    let voiceUnavailable = "지금은 받아쓰기를 사용할 수 없습니다"
    func voiceTranscribing(seconds: Double) -> String {
        String(format: "Whisper가 다시 듣는 중… %.1f초", seconds)
    }
    let whisperMissing = "Whisper가 설치되어 있지 않습니다 — docs/whisper.md 참고"
    let whisperNothingHeard = "아무것도 들리지 않았습니다"
    func dictationStatus(_ status: Whisper.Status) -> String {
        switch status {
        case .ready(let model): return "받아쓰기: Apple 다음 Whisper (\(model))"
        case .noBinary: return "받아쓰기: Apple만 — whisper-cli 없음"
        case .noModel: return "받아쓰기: Apple만 — whisper-cli는 있고 모델이 없음"
        }
    }
    func voiceListeningWhisper() -> String { "듣는 중 — 멈추면 Whisper가 한 번 더 봅니다" }

    let scanning = "찾는 중…"
    let noSession = "Claude Code 세션을 찾지 못했습니다"
    let nothingToSend = "보낼 곳이 없습니다 — 먼저 터미널에서 Claude Code를 실행하세요"
    let sendFailed = "보내지 못했습니다"
    let itermSilent = "iTerm2가 응답하지 않았습니다"
    let scriptMissing = "iterm.js가 없습니다 — 앱 번들이 손상되었을 수 있습니다"
    let cannotList = "iTerm2 세션을 읽지 못했습니다"
    let noOutput = "이 세션에서 아직 읽을 것이 없습니다."
    func outputSize(_ pt: Int) -> String { "출력 글자 크기 \(pt)pt — ⌘J로 보기" }
    func foldedTools(_ count: Int) -> String { "\(count)단계" }
    func outputOrder(newestFirst: Bool) -> String {
        newestFirst ? "최신순" : "오래된순"
    }
    func backlogNow(_ count: Int) -> String { "현재 \(count)" }
    func dropped(_ count: Int) -> String {
        count == 1 ? "경로를 넣었습니다 — Claude Code가 읽습니다" : "경로 \(count)개를 넣었습니다"
    }
    func stackConfirm(_ command: String) -> String { "다시 누르면 실행합니다: \(command)" }
    let hintStacks = "서버"
    func stackTip(up: Int, total: Int) -> String { "서버 \(total)개 중 \(up)개 실행 중 — ⌘S로 목록 보기" }
    let stackTipUnknown = "이 프로젝트에는 서버가 있지만 status 명령이 아직 신뢰되지 않았습니다 — ⌘S"
    let stackUntrusted = "미승인"
    let stackExit = "종료 코드"
    let stackActionStart = "시작"
    let stackActionRestart = "재시작"
    let stackActionStop = "중지"
    let stackActionLogs = "로그"
    let stackLogAll = "전체"
    let stackLogBack = "대화 기록"
    let stackActionAllow = "허용"
    let stackActionAgain = "다시 누르기"
    func sessionTip(index: Int, total: Int) -> String { "\(total)개 중 \(index)번째 세션 — ⌘K로 전환" }
    let sessionWaiting = "답변 대기 중"
    let sessionAgents = "백그라운드에 {n}개"
    let islandDone = "완료"
    let islandAllSessions = "모든 세션…"
    func statusWaiting(_ labels: [String]) -> String {
        labels.count == 1 ? "\(labels[0]) 세션이 답변을 기다립니다"
                          : "\(labels.count)개 세션이 답변을 기다립니다"
    }
    func statusWorking(_ count: Int) -> String { "\(count)개 실행 중" }

    let settingsTitle = "Clawdline 설정"
    let settingsGeneral = "일반"
    let settingsBar = "막대"
    let settingsReading = "읽기"
    let settingsVoice = "받아쓰기"
    let settingsHotkey = "단축키"
    let settingsRecording = "키를 누르세요…"
    let settingsScope = "작동하는 곳"
    let settingsScopeGlobal = "모든 앱에서"
    let settingsScopeHint = "비워 두면 어디서나 동작합니다. 그래서 마지막 하나를 빼면 위의 스위치가 켜지고, 그 스위치를 다시 끄면 목록이 돌아옵니다. 설정 파일에는 번들 ID로 남고, 손으로 고친 목록도 그대로 동작합니다."
    let settingsScopeAdd = "앱 추가…"
    let settingsScopeChoose = "앱 고르기…"
    let settingsScopeRunning = "지금 열려 있는 앱"
    let settingsScopeRemove = "빼기"
    let settingsLanguage = "언어"
    let settingsReopen = "막대가 터미널을 따라 나왔다 들어가기"
    let settingsReopenHint = "터미널에서 다른 곳으로 넘어가면 막대는 들어가고, 터미널로 돌아오면 막대도 돌아옵니다. 다 썼다는 뜻이 되는 것은 Esc입니다."
    let settingsFollow = "막대가 겨냥한 것을 터미널에도 띄우기"
    let settingsFollowHint = "그 세션의 탭을 선택합니다. 터미널을 맨 앞으로 가져오지는 않습니다. 그랬다가는 Tab을 누를 때마다 지금 입력하던 칸에서 키보드가 빠져나가기 때문입니다."
    let settingsCodexAutoName = "새 Codex 세션 자동 이름 지정"
    let settingsCodexAutoNameHint = "이름 없는 세션마다 작은 Codex Luna turn을 한 번 실행합니다. 첫 요청을 사용하고 Codex 사용량을 소모하며, 직접 정한 이름은 바꾸지 않습니다."
    let settingsNotch = "노치에 살기"
    let settingsNotchHint = "카메라 하우징에 사는 캐릭터. 끄면 끝 — 아무것도 그리지 않고 창도 만들지 않습니다."
    let settingsPosition = "화면에서의 높이"
    let settingsWidth = "너비"
    let settingsOpacity = "카드 불투명도"
    let settingsShow = "표시"
    let settingsPaneHeight = "패널 높이"
    let settingsTextSize = "글자 크기"
    let settingsPaneFont = "패널 글꼴"
    let settingsBlur = "뒤쪽 흐림"
    let settingsNewestFirst = "최신 항목 먼저"
    let settingsEngine = "인식기"
    let settingsSettle = "이만큼 쉬면 문장이 끝남"
    let settingsStop = "이만큼 조용하면 세션 종료"
    let settingsAuto = "자동"
    let settingsTranscript = "트랜스크립트"
    let settingsTerminal = "터미널"
    let settingsOff = "끔"
    let settingsHooks = "Claude Code 훅"
    let settingsHooksHint = "설치해 두면 한 차례가 시작되거나 끝나거나 답을 기다리는 순간을 Claude Code가 곧바로 알려 줍니다. Clawdline이 다음에 확인할 때까지 기다리지 않습니다. 상태를 읽는 곳은 여전히 화면이고, 여기서 정해지는 것은 얼마나 빨리인지뿐입니다."
    let settingsHooksInstall = "설치"
    let settingsHooksRemove = "제거"
    let settingsHooksOff = "설치 안 됨 — 상태는 모두 화면에서 읽습니다"
    let settingsHooksOn = "설치됨 — 아직 알려 온 세션이 없습니다"
    let settingsHooksLive = "설치됨. 세션이 알려 오고 있습니다"
    let settingsStateHook = "세션 상태가 바뀔 때"
    let settingsStateHookHint = "세션이 일을 시작하거나, 끝내거나, 무언가를 물어볼 때마다 Clawdline이 이것을 실행합니다. 당신의 프로그램을, 자세한 내용은 환경 변수에 담아서. 여기가 아니라 설정 파일에 적는 이유는 이것이 명령줄이 아니라 argv 목록이기 때문입니다. 공백이 든 경로는 끝까지 하나의 경로로 남아야 합니다."
    let settingsRemote = "원격"
    let settingsRemoteServe = "브라우저나 휴대폰에서 세션을 볼 수 있게 하기"
    let settingsRemoteHint = "꺼져 있으면 이 Mac 바깥에서는 아무것도 닿지 않습니다. 켜면 세션 목록이 127.0.0.1에 올라갑니다. 여기 브라우저에도, 터널 너머의 휴대폰에도, 스크립트에도. 그렇게 넘어가는 것이 저장소 이름과 브랜치, 작업 제목이라서 당신이 말하기 전까지는 꺼진 채로 있습니다."
    let settingsRemoteDevices = "페어링된 기기"
    let settingsRemoteNoDevices = "아직 없음 — 이 Mac 밖에서는 아무것도 읽을 수 없습니다"
    let settingsRemoteRevokeAll = "모두 연결 해제"
    let settingsRemoteOpen = "브라우저에서 열기"
    let pairingIgnore = "무시"
    func pairingAsks(_ device: String) -> String { "\(device)에서 이 Mac과 페어링을 요청합니다" }
    func pairingCode(_ code: String) -> String {
        """
        그 기기에 이 코드를 입력하세요:

        \(code)

        2분 동안만 유효합니다. 방금 요청한 적이 없다면 무시해도 됩니다. 이 코드 없이는 \
        요청한 쪽이 끝낼 수 없습니다.
        """
    }
    let settingsTunnel = "어디서든 이 Mac에 닿기"
    let settingsTunnelQuick = "자동 생성된 주소"
    let settingsTunnelNamed = "내 도메인"
    let settingsTunnelHostname = "호스트 이름"
    let settingsTunnelHint = "cloudflared를 통해 이 Mac에서 바깥으로 연결을 겁니다. 포트 포워딩도 없고, 네트워크에서 듣고 있는 것도 없습니다. 기기가 하나 페어링될 때까지는 시작하지 않습니다. 터널 너머에 있는 것이 이 Mac의 모든 저장소 이름과 모든 작업 제목이기 때문입니다."
    let settingsRemoteWrite = "페어링된 기기가 세션에 쓸 수 있게 하기"
    let settingsRemoteWriteHint = "꺼져 있으면 페어링된 기기는 읽기만 할 수 있습니다. 켜면 세션에 텍스트를 보내고 새 세션을 시작할 수도 있습니다. 그것은 이 Mac에서 코드를 실행한다는 뜻입니다. Claude Code가 하는 일이 바로 그것이기 때문입니다. 위쪽과는 다른 결정이라 스위치도 따로 두었습니다."
    let settingsRemotePhone = "휴대폰 페어링…"
    let settingsRemotePhoneHint = "스캔할 코드를 보여줍니다. 그 코드는 자기 키를 따로 갖고 있어서, 사진으로 찍히더라도 남는 것은 이 목록에 보이고 언제든 지울 수 있는 기기 하나뿐입니다. 이 Mac 자신의 키가 아닙니다."
    let pairingScanTitle = "휴대폰으로 이것을 스캔하세요"
    let pushWaiting = "이 답을 기다리는 중"
    let pushTest = "테스트 알림입니다. 필요한 것은 다 연결되어 있습니다."
    let pushFinished = "의 긴 작업이 끝났습니다"
    let pushDeployOk = "의 배포가 성공했습니다"
    let pushDeployFail = "의 배포가 실패했습니다"
    let settingsPushFinish = "긴 작업이 끝나면 알리기"
    let settingsPushFinishHint = "2분이 넘는 작업만입니다."
    let settingsPushDeploy = "배포가 끝나면 알리기"
    let settingsPushDeployHint = "성공도 실패도 알립니다."
    let settingsOrchestrator = "다른 세션에 일 맡기기"
    let settingsOrchestratorEnabled = "세션이 다른 세션에 일을 넘길 수 있게"
    let settingsOrchestratorEnabledHint = "clawdline 스킬을 가진 세션이 새 탭을 열고 지시를 입력한 뒤, 끝나면 알림을 받습니다. 꺼두면 모든 요청을 거절합니다. 이미 돌고 있는 것은 멈추지 않습니다."
    let settingsOrchestratorMax = "동시에 돌릴 자식 세션"
    let settingsOrchestratorMaxHint = "기본값은 세 개. 하나하나가 어시스턴트가 들어 있는 터미널 탭입니다."
    let settingsOrchestratorNotify = "요청한 세션에 알리기"
    let settingsOrchestratorNotifyHint = "일이 끝나면 그 세션에 한 줄을 입력합니다."
    let settingsOrchestratorClose = "자식 세션이 보고하면"
    let settingsOrchestratorCloseHint = "보고한 뒤에 그 탭을 닫습니다. 시간이 다 된 것은 읽어 볼 수 있게 남겨 둡니다."
    let settingsOrchestratorCloseNow = "탭을 바로 닫기"
    let settingsOrchestratorCloseLinger = "3분 뒤에 닫기"
    let settingsOrchestratorCloseKeep = "닫지 않고 두기"
    func childAnnounce(_ title: String) -> String { "Clawdline이 맡긴 일을 받았습니다: \(title) — 지금 시작합니다." }
    func settingsSeconds(_ value: Double) -> String { String(format: "%.1f초", value) }

    let webConnLive = "실시간"
    let webConnConnecting = "연결 중"
    let webConnRetrying = "{n}초 후 재시도"
    let webConnOffline = "오프라인"
    let webConnLocked = "페어링 안 됨"
    let webConnTipLive = "앱에서 실시간으로 받는 중"
    let webConnTipLocked = "이 브라우저는 아직 Mac과 페어링되지 않았습니다"
    let webConnTipDown = "연결되지 않음 — 눌러서 지금 시도"

    let webCountWorking = "{n}개 실행 중"
    let webCountWaiting = "{n}개 대기 중"
    let webCountUnreadable = "{n}개 읽을 수 없음"
    let webCountQuietOne = "세션 {n}개, 모두 조용함"
    let webCountQuietMany = "세션 {n}개, 모두 조용함"
    let webCountNone = "세션 없음"

    let webFilterPlaceholder = "작업, 프로젝트, tty로 거르기"
    let webFilterLabel = "세션 거르기"
    let webListLabel = "Claude Code 세션"
    let webPull = "당겨서 새로고침"
    let webPullRelease = "놓으면 새로고침"
    let webPullBusy = "새로고침 중…"
    let webEmptyFilterTitle = "“{q}”에 맞는 것이 없습니다"
    let webEmptyFilterHint = "Esc를 누르면 지워집니다"
    let webEmptyLockedTitle = "이 기기는 페어링되지 않았습니다"
    let webEmptyLockedHint = "앱이 401을 돌려주었습니다 — Mac의 Clawdline에서 페어링하세요"
    let webEmptyNoneHint = "터미널에서 하나 시작하면 여기 나타납니다"
    let webEmptyWaitTitle = "앱을 기다리는 중"
    let webEmptyWaitHint = "아직 아무것도 들어오지 않았습니다"
    let webStateUnreadable = "화면을 읽지 못함"
    let webStateWorking = "실행 중"

    let webBack = "세션"
    let webBackLabel = "세션 목록으로 돌아가기"
    let webNoSessionOpen = "열린 세션 없음"
    let webOrderTip = "트랜스크립트 뒤집기 (r)"
    let webShowOnMac = "Mac에 띄우기"
    let webShowOnMacTip = "이 세션의 터미널을 Mac 맨 앞으로 가져옵니다"
    let webShowOnMacOff = "서버가 write: false라고 답합니다 — 아직 아무것도 보낼 수 없습니다"
    let webShowOnMacAsked = "Mac에 앞으로 가져오라고 했습니다"
    let webSessionActions = "세션 작업"
    let webSessionGit = "Git 변경 사항"
    let webGitTitle = "Git 변경 사항"
    let webGitClean = "작업 트리에 변경 사항 없음"
    let webGitNotRepo = "Git 저장소가 아님"
    let webGitFailed = "Git 변경 사항을 읽을 수 없음"
    let webGitRefresh = "새로고침"
    let webGitClose = "닫기"
    let webGitStaged = "스테이징됨"
    let webGitUnstaged = "스테이징되지 않음"
    let webGitUntracked = "추적되지 않음"
    let webGitConflict = "충돌"
    let webEndSession = "세션 닫기"
    let webConfirmActionTitle = "{action}을 실행할까요?"
    let webConfirmActionSay = "현재 세션에 {action}을 보냅니다."
    let webConfirmEndTitle = "이 세션을 닫을까요?"
    let webConfirmEndSay = "어시스턴트를 종료한 뒤 터미널 탭을 닫습니다."
    let webCancel = "취소"
    let webConfirm = "확인"
    let webPickSession = "왼쪽에서 세션을 고르세요."
    let webReading = "읽는 중…"
    let webLoading = "불러오는 중…"
    let webTranscriptFailed = "트랜스크립트를 읽지 못했습니다"
    let webWhoYou = "나"
    let webWhoTool = "도구"
    let webSteps = "{n}단계"
    let webJustNow = "방금"
    let webMinutesAgo = "{n}분 전"

    let webSend = "보내기"
    let webAttach = "사진 첨부"
    let webRemoveShot = "{name} 빼기"
    let webWriteOpen = "쓰려면 세션을 여세요."
    let webWriteOff = "*보내기가 꺼져 있습니다* — 서버가 `write: false`라고 답합니다. 칸은 이어져 있고, 그쪽이 바뀌면 스스로 켜집니다."
    let webShotsOnlyPictures = "메시지에 함께 보낼 수 있는 것은 사진뿐입니다"
    let webShotsTooMany = "한 메시지에 담을 수 있는 사진은 {n}장까지입니다"
    let webShotTooBig = "이 사진은 줄여도 보내기엔 너무 큽니다"
    let webShotsTooBig = "이 사진들은 함께 보내기엔 너무 큽니다"
    let webShotUnreadable = "이 사진을 읽지 못했습니다"
    let webShotNeedsSession = "사진을 보내려면 세션을 여세요"

    let webHintMove = "이동"
    let webHintOpen = "열기"
    let webHintFilter = "거르기"
    let webHintPane = "패널"

    let webKeysLabel = "키보드 단축키"
    let webKeysTitle = "키보드"
    let webKeysMove = "목록을 오르내리기 — `j`와 `k`도 같습니다"
    let webKeysOpen = "고른 세션 열기"
    let webKeysFilter = "목록 거르기"
    let webKeysEscape = "거른 것을 지우고, 그다음 뒤로"
    let webKeysList = "세션 목록으로 포커스"
    let webKeysPane = "트랜스크립트 보이기·숨기기"
    let webKeysEnds = "트랜스크립트의 맨 위나 맨 아래"
    let webKeysReverse = "트랜스크립트 순서 뒤집기"
    let webKeysThis = "이 카드"
    let webKeysFoot = "입력란에 친 것은 입력란에 남습니다 — 쓰는 동안 단축키는 물러나 있습니다."

    let webDoorLabel = "이 브라우저 페어링"
    let webDoorAskLede = "이 브라우저는 아직 들어오지 못했습니다."
    let webDoorAskFine = "페어링을 요청하면 여섯 자리 코드가 *Mac에* 뜹니다 — 이 페이지로 오는 답에는 일부러 넣지 않았습니다. 그 앞에 있는 사람만 끝낼 수 있고, 그것이 번거로움이 아니라 이 방식의 핵심입니다."
    let webDoorName = "이 기기의 이름"
    let webDoorAsk = "페어링 요청"
    let webDoorToPassword = "대신 비밀번호로 로그인"
    let webDoorCodeLede = "Mac을 보세요."
    let webDoorCodeFine = "Clawdline이 여섯 자리를 보여 줍니다. 남은 시간 {left}. 여기에 입력하세요."
    let webDoorTwoMinutes = "2분"
    let webDoorDigit = "{n}번째 자리"
    let webDoorConfirm = "이 기기 페어링"
    let webDoorRestart = "다시 시작"
    let webDoorPasswordLede = "비밀번호로 로그인합니다."
    let webDoorPasswordFine = "Mac의 Clawdline에서 설정 → 원격에 정해 둔 그것입니다. 정해 둔 적이 없다면 페어링이 들어오는 길입니다."
    let webDoorPassword = "비밀번호"
    let webDoorPasswordGo = "로그인"
    let webDoorToPair = "대신 페어링 코드 쓰기"
    let webDoorAsking = "Mac에 묻는 중…"
    let webDoorAskFailed = "Mac에 묻지 못했습니다."
    let webDoorRateLimited = "한 번 요청할 때마다 Mac에 알림이 뜨기 때문에 10분에 세 번까지입니다."
    let webDoorSixDigits = "여섯 자리입니다."
    let webDoorChecking = "확인 중…"
    let webDoorFinished = "이 페어링은 끝났습니다 — 다섯 번 틀렸습니다. Mac 앞에 있을 때 다시 요청하세요."
    let webDoorWrongCode = "그 코드가 아닙니다."
    let webDoorNeedPassword = "비밀번호부터."
    let webDoorWrongPassword = "그 비밀번호가 아닙니다."
    let webDoorExpired = "그 코드는 만료되었습니다. 다시 요청하면 새 코드가 Mac에 뜹니다."
    let webDoorPaired = "페어링 완료 — 이 브라우저는 들어왔습니다"

    let webOffline = "Clawdline에 닿지 못했습니다. Mac에서 아직 돌고 있나요?"
    let webNotJSON = "서버가 JSON이 아닌 것을 보냈습니다"
    let webRequestFailed = "요청 실패"

    let webNotifyGo = "알려 주세요"
    let webNotifyAsking = "묻는 중…"
    let webNotifyStop = "그만"
    let webNotifyStopping = "끄는 중…"
    let webNotifyOff = "세션이 답을 기다릴 때"
    let webNotifyOn = "이 기기는 등록되어 있습니다. 무엇을 알릴지는 Mac에서 정합니다."
    let webNotifyBlocked = "이 사이트의 알림이 막혀 있습니다. 그 스위치는 여기가 아니라 브라우저 자체 설정에 있습니다."
    let webNotifyUnsupported = "이 브라우저는 알림을 띄울 수 없습니다."
    let webNotifyHomeScreen = "clawdline을 홈 화면에 추가하고 거기서 여세요 — iOS는 거기 있는 앱에만 알림을 보냅니다."
    let webNotifyOnFailed = "알림을 켜지 못했습니다"
    let webNotifyOffFailed = "알림을 끄지 못했습니다"

    let webSettings = "설정"
    let webSettingsNotify = "알림"
    let webSettingsAssistantIcons = "어시스턴트 아이콘"
    let webSettingsAssistantIconsSay = "대화에서 Claude 또는 Codex 이름 앞에 아이콘을 표시합니다."
    let webSettingsAssistantIconsShow = "아이콘 표시"
    let webSettingsVersion = "버전 {v}"
    let webClose = "닫기"
    let webNotifySheetOff = "세션이 기다려도 이 기기에는 알리지 않습니다."
    let webNotifyTest = "테스트 보내기"
    let webNotifyTestSent = "보냈습니다 — 곧 이 기기에 도착할 것입니다."
    let webNotifyTestNone = "Mac에 이 기기의 등록이 없습니다. 알림을 껐다 켜면 이 브라우저가 새로 등록합니다."
    let webNotifyTestFailed = "테스트 알림을 보내지 못했습니다"
    let webSending = "보내는 중…"
    let webSendTip = "Return으로 보내기 · Shift-Return으로 줄바꿈"
    let webStart = "세션 시작"
    let webStartLabel = "프로젝트에서 세션 시작"
    let webStartPick = "어디서 시작할까요?"
    let webStartWith = "무엇으로 시작할까요?"
    let webStartEmpty = "아직 시작할 곳이 없습니다. Mac에서 Claude Code를 한 번 돌리면 여기에 나타납니다."
    let webStartFilter = "프로젝트 거르기"
    let webStarting = "탭을 여는 중…"
    let webStartWaiting = "시작했습니다. 나타나기를 기다리는 중…"
    let webStartSlow = "탭은 열렸지만 세션이 아직 알려 오지 않았습니다. Mac을 한번 보세요."
    let webStartFailed = "이것은 시작하지 못했습니다."
    let webStartGone = "그 프로젝트는 이제 Mac에 없습니다."
    let webStartTerminalClosed = "{app} 앱이 Mac에서 돌고 있지 않습니다. 거기서 연 뒤에 다시 해 보세요."
    let webStartTerminalUnsupported = "여기서는 {app} 안에서 세션을 시작할 수 없습니다. 그 안에서 tmux를 돌리면 됩니다."
    let webStartOff = "세션 시작이 꺼져 있습니다. Mac의 설정 → 원격에서 켤 수 있습니다."
    let webLinks = "링크"
    let webLinksTip = "이 프로젝트를 열 수 있는 곳"
    let webLinksPick = "이 프로젝트에 주소가 있는 것은 이게 전부입니다."
    let webLinksEmpty = "이 프로젝트에는 주소가 있는 것이 없습니다 — 사이트도, 배포도, 돌고 있는 서버도 없습니다."
    let webLinksFailed = "이 프로젝트의 링크를 읽지 못했습니다."
    let webLinksLocal = "Mac 자신의 네트워크에서만 닿습니다. 여기서는 열리지 않습니다."
    let webLinksFile = "Mac에 있는 파일입니다. 거기서 열리지, 이 브라우저에서 열리지 않습니다."
    let webLinksCopy = "경로 복사"
    let webLinksCopied = "복사했습니다."
    let webLinksCopyFailed = "이 브라우저가 페이지의 복사를 막았습니다."
    let webLinkOk = "정상"
    let webLinkFail = "오류"
    let webLinkDown = "꺼짐"
    let webLinkRunning = "진행 중"
    let webSessionInfo = "세션 정보"
    let webInfoTitle = "이 세션에 대하여"
    let webInfoSession = "이 세션"
    let webInfoAssistant = "어시스턴트"
    let webInfoModel = "모델"
    let webInfoSessionId = "세션 ID"
    let webInfoDirectory = "디렉터리"
    let webInfoRunningFor = "실행 시간"
    let webInfoUsage = "토큰 사용량"
    let webInfoInput = "입력"
    let webInfoOutput = "출력"
    let webInfoCacheRead = "캐시 읽기"
    let webInfoCacheWrite = "캐시 쓰기"
    let webInfoTotal = "합계"
    let webInfoCost = "예상 비용"
    let webInfoNoUsage = "이 세션의 기록을 아직 찾지 못했습니다."
    let webInfoLimits = "플랜 한도"
    let webInfoLimitHit = "한도 도달"
    let webInfoResets = "{when} 초기화"
    let webInfoUnknown = "알 수 없음"
    let webInfoFiles = "파일"
    let webInfoBranch = "브랜치"
    let webInfoStaged = "스테이징됨"
    let webInfoUnstaged = "변경됨"
    let webInfoUntracked = "추적 안 됨"
    let webInfoConflict = "충돌"
    let webInfoClean = "커밋하지 않은 것이 없습니다."
    let webInfoNotRepo = "git 저장소가 아닙니다."
    let webInfoDeploy = "마지막 배포"
    let webInfoNoDeploy = "이 프로젝트에는 배포 기록이 없습니다."
    let webInfoFailed = "이 세션의 정보를 읽지 못했습니다."
    let webInfoRefresh = "새로고침"
    let webInfoTokens = "토큰"
    let webInfoSwitchModel = "모델 바꾸기"
    let webInfoModelOther = "다른 모델…"
    let webInfoModelSent = "/model {model}을 보냈습니다. 다음 답변 뒤에 카드에 반영됩니다."
    let webInfoModelBusy = "세션이 쉬고 있을 때만 바꿀 수 있습니다."
    let webInfoLimitsClaude = "Claude Code는 한도를 다 쓴 뒤에야 기록하므로, 그 전에는 알 수 없습니다."
    let webInfoCopied = "세션 id를 복사했습니다."
    let webInfoAsOf = "{when} 기준"
    let webInfoWhyUnknown = "왜 알 수 없는지, 숫자를 받아오는 방법"
    let webSettingsOrder = "트랜스크립트"
    let webSettingsOrderSay = "트랜스크립트를 어느 쪽 끝부터 읽기 시작할지. 모든 세션에 적용되고, 키보드에서는 `r`이 같은 일을 합니다."
    let webAskLabel = "물었습니다"
    let webAskAny = "몇 개든 고를 수 있습니다"
    let webWaitingTitle = "이 세션이 답을 기다리고 있습니다"
    let webWaitingSay = "Claude Code가 Mac에 메뉴를 띄우고 있습니다. Clawdline은 아직 여기서 메뉴를 읽지 못해서, 고를 것들은 그 화면에만 있습니다."
    let webWaitingSend = "*여기서 보내도 답이 메뉴에 입력되지 않습니다* — 메뉴에서 지금 선택되어 있는 항목을 그대로 확정할 뿐이고, 그건 대개 뜻한 것이 아닙니다. 이건 Mac에서 답하세요."
    let webMenuSay = "답을 누르면 그대로 세션으로 갑니다."
    let webMenuHighlighted = "선택됨"
    let webMenuSent = "답을 보냈습니다."
    let webAgents = "백그라운드 에이전트"
    let webAgentsCount = "{n}개 실행 중"
    let webAgentDone = "완료"
    let webAgentFailed = "실패"
    let agentRunning = "실행 중"
    let agentTools = "도구 {n}회"
    let agentEmpty = "이 에이전트는 아직 아무것도 남기지 않았습니다."
    let agentBack = "세션"
    let webAgentOpen = "이 에이전트가 한 일 보기"
    let webTaskRoot = "부모"
    let webTaskChild = "자식"
    let webTaskTasks = "작업"
    let webTaskDone = "완료"
    let webTaskFailed = "실패"
    let webTaskRunning = "실행 중"
    let webStale = "Mac에서 Clawdline을 다시 빌드했습니다. 이 페이지는 그 전 것입니다."
    let webStaleGo = "새로고침"

    let menuOpen = "입력창 열기"
    let menuReveal = "대상 탭으로 이동"
    let menuMascot = "마스코트"
    let menuLogin = "로그인 시 실행"
    let menuEditConfig = "설정…"
    let menuReload = "설정 다시 읽기"
    let menuQuit = "Clawdline 종료"
    let menuNoTarget = "(아직 찾지 못함)"

    func hotkeyFailedTitle(_ combo: String) -> String { "\(combo)를 등록하지 못했습니다" }
    func hotkeyFailedBody(_ configPath: String) -> String {
        """
        다른 앱이 이미 쓰고 있을 가능성이 큽니다 — Spotlight, 입력기 전환, \
        BetterTouchTool 등.

        다른 키를 고르세요: \(configPath)의 "hotkey"를 편집한 뒤 \
        메뉴 막대에서 "설정 다시 읽기"를 선택합니다.

        그때까지도 메뉴 막대의 ✳로 입력창을 열 수 있습니다.
        """
    }
    let loginFailed = "로그인 시 실행을 설정하지 못했습니다"
}
