import Foundation

/// The reference translation. Copy this file to add a language.
struct English: Copy {
    let placeholder = "Message Claude Code…"

    let hintSend = "send"
    let hintNewline = "new line"
    let hintSwitch = "switch"
    let hintList = "list"
    let hintMascot = "mascot"
    let hintOutput = "output"
    let hintFullscreen = "full screen"
    let hintKeys = "keys"
    let hintTextSize = "text size"
    let hintOrder = "reverse"
    let hintVoice = "dictate"
    func voiceListening(onDevice: Bool) -> String {
        onDevice ? "Listening on this Mac — press again to stop"
                 : "Listening — this language is transcribed by Apple, not on this Mac"
    }
    let voiceNoPermission = "Dictation needs microphone and speech access"
    let voiceUnavailable = "Dictation is not available right now"
    func voiceTranscribing(seconds: Double) -> String {
        String(format: "Whisper is reading it back… %.1fs", seconds)
    }
    let whisperMissing = "Whisper is not installed — see docs/whisper.md"
    let whisperNothingHeard = "Heard nothing"
    func dictationStatus(_ status: Whisper.Status) -> String {
        switch status {
        case .ready(let model): return "Dictation: Apple, then Whisper (\(model))"
        case .noBinary: return "Dictation: Apple only — no whisper-cli"
        case .noModel: return "Dictation: Apple only — whisper-cli is there, no model"
        }
    }
    func voiceListeningWhisper() -> String { "Listening — Whisper takes another look when you stop" }

    let scanning = "Scanning…"
    let noSession = "No Claude Code session found"
    let nothingToSend = "Nothing to send to — start Claude Code in a terminal first"
    let sendFailed = "Could not send"
    let itermSilent = "iTerm2 did not respond"
    let itermBusy = "iTerm2 is waiting on a dialog — answer it on the Mac"
    let scriptMissing = "iterm.js is missing — broken app bundle?"
    let cannotList = "Could not read iTerm2 sessions"
    let noOutput = "Nothing to read from this session yet."
    let imageExpired = "Image expired"
    let imagePreview = "Image preview"
    let imageClose = "Close preview"
    func outputSize(_ pt: Int) -> String { "Output text \(pt)pt — ⌘J to see it" }
    func foldedTools(_ count: Int) -> String { "\(count) steps" }
    func outputOrder(newestFirst: Bool) -> String {
        newestFirst ? "Newest first" : "Oldest first"
    }
    func backlogNow(_ count: Int) -> String { "now \(count)" }
    func dropped(_ count: Int) -> String {
        count == 1 ? "Added the path — Claude Code reads it" : "Added \(count) paths"
    }
    func stackConfirm(_ command: String) -> String { "Press again to run:  \(command)" }
    let hintStacks = "servers"
    func stackTip(up: Int, total: Int) -> String { "\(up) of \(total) servers up — ⌘S for the list" }
    let stackTipUnknown = "This project has servers; its status command is not trusted yet — ⌘S"
    let stackUntrusted = "not trusted yet"
    let stackExit = "exit"
    let stackActionStart = "start"
    let stackActionRestart = "restart"
    let stackActionStop = "stop"
    let stackActionLogs = "log"
    let stackLogAll = "all"
    let stackLogBack = "transcript"
    let stackActionAllow = "allow"
    let stackActionAgain = "press again"
    func sessionTip(index: Int, total: Int) -> String { "Session \(index) of \(total) — ⌘K to switch" }
    let sessionWaiting = "waiting for you"
    let sessionAgents = "{n} in the background"
    let sessionShellOne = "1 shell running"
    let sessionShellMany = "{n} shells running"
    let sessionWaitedOnByOne = "1 waiting on you"
    let sessionWaitedOnByMany = "{n} waiting on you"
    let islandDone = "done"
    let islandAllSessions = "All sessions…"
    func statusWaiting(_ labels: [String]) -> String {
        labels.count == 1 ? "\(labels[0]) is waiting for you"
                          : "\(labels.count) sessions are waiting for you"
    }
    func statusWorking(_ count: Int) -> String { "\(count) running" }

    let settingsTitle = "Clawdline Settings"
    let settingsGeneral = "General"
    let settingsBar = "The bar"
    let settingsReading = "Reading"
    let settingsVoice = "Dictation"
    let settingsHotkey = "Hotkey"
    let settingsRecording = "Press keys…"
    let settingsScope = "Fires in"
    let settingsScopeGlobal = "In every app"
    let settingsScopeHint = "Empty means everywhere, so taking the last one out turns the switch above on — and turning that back off puts the list back. The config file keeps these as bundle ids, and a hand-edited list still works."
    let settingsScopeAdd = "Add an app…"
    let settingsScopeChoose = "Choose an app…"
    let settingsScopeRunning = "Open right now"
    let settingsScopeRemove = "Remove"
    let settingsLanguage = "Language"
    let settingsReopen = "The bar comes and goes with the terminal"
    let settingsReopenHint = "Switching away from the terminal puts the bar away, and switching back to it brings the bar back. Esc is what means finished with it."
    let settingsFollow = "The terminal shows whatever the bar is aimed at"
    let settingsFollowHint = "It selects that session's tab. It does not bring the terminal to the front — otherwise every press of Tab would take the keyboard out of the box you are typing into."
    let settingsCodexAutoName = "Name new sessions"
    let settingsCodexAutoNameHint = "Runs one small Codex Luna turn for each unnamed session. It uses the first request, spends Codex usage, and never replaces a name you chose."
    let settingsNotch = "Live in the notch"
    let settingsNotchHint = "A character in the camera housing. Off is off — nothing is drawn and no window is made."
    let settingsPosition = "Height on screen"
    let settingsWidth = "Width"
    let settingsOpacity = "Card opacity"
    let settingsShow = "Show"
    let settingsPaneHeight = "Pane height"
    let settingsTextSize = "Text size"
    let settingsPaneFont = "Pane font"
    let settingsBlur = "Blur behind"
    let settingsNewestFirst = "Newest first"
    let settingsEngine = "Recogniser"
    let settingsSettle = "A pause ends a sentence"
    let settingsStop = "A silence ends the session"
    let settingsAuto = "Auto"
    let settingsTranscript = "Transcript"
    let settingsTerminal = "Terminal"
    let settingsOff = "Off"
    let settingsHooks = "Claude Code hooks"
    let settingsHooksHint = "With these installed, Claude Code says the moment a turn starts, ends or needs an answer, instead of Clawdline finding out at its next look. The screen is still where every reading comes from; this only decides how soon one is taken."
    let settingsHooksInstall = "Install"
    let settingsHooksRemove = "Remove"
    let settingsHooksOff = "Not installed — readings come from the screen alone"
    let settingsHooksOn = "Installed — no session has reported yet"
    let settingsHooksLive = "Installed, and sessions are reporting"
    let settingsStateHook = "When a session changes state"
    let settingsStateHookHint = "Whenever a session starts working, finishes, or asks you something, Clawdline runs this: your own program, with the details in its environment. It is set in the config file rather than here because it is an argument list and not a command line — a path with a space in it has to stay one path."
    let settingsRemote = "Remote"
    let settingsRemoteServe = "Let a browser or your phone see your sessions"
    let settingsRemoteHint = "Off, and nothing outside this Mac can reach anything. On, and the session list is served on 127.0.0.1 — for a browser here, for a phone through a tunnel, for a script. What that hands over is repository names, branches and task titles, which is why it stays off until you say otherwise."
    let settingsRemoteDevices = "Paired devices"
    let settingsRemoteNoDevices = "None yet — nothing outside this Mac can read anything"
    let settingsRemoteRevokeAll = "Disconnect everything"
    let settingsRemoteOpen = "Open in a browser"
    let pairingIgnore = "Ignore"
    func pairingAsks(_ device: String) -> String { "\(device) wants to pair with this Mac" }
    func pairingCode(_ code: String) -> String {
        """
        Type this code into it:

        \(code)

        It is good for two minutes. If you did not just ask for this, ignore it — whoever asked \
        cannot finish without this code.
        """
    }
    let settingsTunnel = "Reach this Mac from anywhere"
    let settingsTunnelQuick = "A generated address"
    let settingsTunnelNamed = "My own domain"
    let settingsTunnelHostname = "Hostname"
    let settingsTunnelHint = "Opens an outbound connection through cloudflared — no port forwarding, nothing listening on your network. It will not start until a device is paired, because what is behind it is every repository name and task title on this Mac."
    let settingsRemoteWrite = "Let a paired device write into a session"
    let settingsRemoteWriteHint = "Off, and a paired device can only read. On, and it can send text into a session and start new ones — which runs code on this Mac, because that is what Claude Code does. A different decision from the one above, so it is a different switch."
    let settingsRemotePhone = "Pair a phone…"
    let settingsRemotePhoneHint = "Shows a code to scan. It carries a key of its own, so a photograph of it is a device you can see in this list and take away again — not this Mac's own key."
    let pairingScanTitle = "Scan this with the phone"
    let pushWaiting = "is waiting for an answer"
    let pushTest = "A test notification. Everything is wired up."
    let pushFinished = "finished a long run"
    let pushDeployOk = "deploy succeeded"
    let pushDeployFail = "deploy failed"
    func pushChildWaiting(minutes: Int?) -> String {
        guard let minutes else { return "has a child session waiting" }
        return "has a child session waiting — \(minutes) min left"
    }
    func pushBatchDone(done: Int, failed: Int) -> String {
        let all = done == 1 ? "finished 1 task" : "finished \(done) tasks"
        return failed == 0 ? all : "\(all), \(failed) failed"
    }
    let settingsPushFinish = "Notify when a long turn finishes"
    let settingsPushFinishHint = "Only for turns over two minutes."
    let settingsSmartNotifications = "Smart notifications"
    let settingsSmartNotificationsHint = "Use Haiku to say what the finished work did. Falls back to the ordinary notice."
    func pushCoalesced(count: Int) -> String { "\(count) jobs finished together" }
    let settingsSmartHealthIdle = "No smart notification has been attempted yet."
    func settingsSmartHealth(attempts: Int, successes: Int) -> String {
        "\(successes) of \(attempts) smart notifications carried a model sentence."
    }
    func settingsSmartHealthFailure(reason: String, time: String) -> String {
        "Last fallback at \(time): \(reason)."
    }
    func settingsSmartTimeout(seconds: Int) -> String {
        "Claude ran past the \(seconds)-second deadline and was cut off"
    }
    let settingsSmartQueueFull = "more finishes arrived than the queue holds"
    let settingsSmartModelFailed = "Claude returned nothing usable"
    let settingsSmartNoSource = "there was nothing to summarize"
    let settingsSmartMissing = "no claude executable was found"
    let settingsPushDeploy = "Notify when a deploy ends"
    let settingsPushDeployHint = "Both success and failure."
    let settingsAgentNotify = "Let agents send their own notifications"
    let settingsAgentNotifyNote = "Controls only content an agent proactively sends; finish, deploy and other notifications are unchanged."
    let settingsOrchestrator = "Agent tasks"
    let settingsOrchestratorEnabled = "Let a session hand work to another"
    let settingsOrchestratorEnabledHint = "A session holding the clawdline skill can open a tab, brief the assistant in it and be told when the work is done. Off, and every dispatch is refused — nothing already running is stopped."
    let settingsOrchestratorMax = "Child sessions at once"
    let settingsOrchestratorMaxHint = "Five by default, and per session rather than per Mac. Each one is a terminal tab with an assistant working in it."
    let settingsOrchestratorPermission = "How far a child may go"
    let settingsOrchestratorPermissionHint = "Nobody is watching a child's tab, so one that stops for approval stops until it times out — and a dispatched session's whole job is running commands and writing files, so anything short of the last stop stops it somewhere. A task may ask for less than this; never for more."
    let settingsOrchestratorPermissionAsk = "Ask before every step"
    let settingsOrchestratorPermissionEdits = "Write files without asking"
    let settingsOrchestratorPermissionFull = "Never ask"
    let settingsOrchestratorNotify = "Tell the session that asked"
    let settingsOrchestratorNotifyHint = "One line typed back into it when its task ends."
    let settingsOrchestratorClose = "When a child reports"
    let settingsOrchestratorCloseHint = "Its tab is closed after it reports — one that timed out is left for you to read."
    let settingsOrchestratorCloseNow = "Close the tab right away"
    let settingsOrchestratorCloseLinger = "Close it after three minutes"
    let settingsOrchestratorCloseKeep = "Leave it open"
    let settingsOrchestratorPolicy = "How work is handed out"
    let settingsOrchestratorPolicyHint = "Rules Clawdline reads on every dispatch and copies into the briefing of every child that may dispatch in turn. Which assistant, which model, what shape the graph should be. Empty means no house rules."
    let settingsOrchestratorPolicyEdit = "Edit the rules"
    func settingsOrchestratorPolicyOn(_ lines: Int) -> String { return "In force — \(lines) lines" }
    let settingsOrchestratorPolicyOff = "No house rules — every dispatch is the dispatcher's own call"
    let settingsSchedules = "Schedules"
    let settingsSchedulesEmpty = "No schedules yet. New schedule below makes the first one."
    let settingsScheduleNew = "New schedule"
    let settingsScheduleEdit = "Edit"
    let settingsScheduleSave = "Save"
    let settingsScheduleDelete = "Delete"
    let settingsScheduleRun = "Run now"
    let settingsScheduleReveal = "Reveal in Finder"
    let settingsSchedulesFolder = "Open schedules folder"
    let settingsScheduleNext = "Next"
    let settingsScheduleLast = "Last"
    let settingsScheduleNever = "Not run yet"
    let settingsScheduleStarted = "Run started."
    let settingsScheduleActive = "The previous task from this schedule is still active."
    let webScheduleMissed = "Last missed"
    let webScheduleNoNext = "No next run is scheduled."
    func childAnnounce(_ title: String) -> String { "Clawdline task received: \(title) — starting now." }
    func settingsSeconds(_ value: Double) -> String { String(format: "%.1f s", value) }

    let webConnLive = "live"
    let webConnConnecting = "connecting"
    let webConnRetrying = "retrying in {n}s"
    let webConnOffline = "offline"
    let webConnLocked = "not paired"
    let webConnTipLive = "Streaming from the app"
    let webConnTipLocked = "This browser has not been paired with the Mac"
    let webConnTipDown = "Not connected — click to try now"

    let webCountWorking = "{n} working"
    let webCountWaiting = "{n} waiting"
    let webCountUnreadable = "{n} unreadable"
    let webCountQuietOne = "{n} session, all quiet"
    let webCountQuietMany = "{n} sessions, all quiet"
    let webCountNone = "no sessions"

    let webFilterPlaceholder = "Filter by task, project or tty"
    let webFilterLabel = "Filter sessions"
    let webListLabel = "Claude Code sessions"
    let webPull = "Pull to refresh"
    let webPullRelease = "Release to refresh"
    let webPullBusy = "Refreshing…"
    let webEmptyFilterTitle = "Nothing matches “{q}”"
    let webEmptyFilterHint = "Esc clears the filter"
    let webEmptyLockedTitle = "This device is not paired"
    let webEmptyLockedHint = "The app answered 401 — pair it from Clawdline on the Mac"
    let webEmptyNoneHint = "Start one in a terminal and it appears here"
    let webEmptyWaitTitle = "Waiting for the app"
    let webEmptyWaitHint = "Nothing has arrived on the stream yet"
    let webStateUnreadable = "screen could not be read"
    let webStateWorking = "working"
    let webTerminalLive = "Terminal live preview"
    let sessionWorkReady = "can take new work"
    let sessionWorkUnknown = "status unknown"
    let sessionWorkHolding = "moving on its own"
    let sessionWorkOwed = "a decision is owed"
    let sessionWorkSelfStated = "self-reported"
    let sessionWorkMilestone = "Delivered; awaiting approval"
    let sessionWorkComplete = "Reviewed and approved"
    let closeabilitySafe = "Safe to close"
    let closeabilityBlocked = "{n} obligations remain"
    let closeabilityBlockedOne = "1 obligation remains"
    let closeabilityBlockedMany = "{n} obligations remain"
    let closeabilityNeedsAttestation = "Waiting for session attestation"
    let closeabilityUnknown = "Closeability unknown"
    let closeabilityWhy = "Not closeable because"
    let closeabilityMoverSelf = "this session moves it"
    let closeabilityMoverPerson = "you move it"
    let closeabilityMoverSession = "another session moves it"
    let closeabilityMoverBroker = "a fresh reading moves it"
    let closeabilityNotProven = "The broker could not prove this session is safe to close."
    let closeabilityAttestationExplanation = "This does not mean unfinished work was found. The checks Clawdline can perform are clear, but this session has not yet confirmed whether it left local changes, undelivered work, or work outside Clawdline. Review the session before closing it."
    let closeabilityTechnicalDetails = "Technical details"

    let webBack = "Sessions"
    let webBackLabel = "Back to the session list"
    let webNoSessionOpen = "No session open"
    let webOrderTip = "Reverse the transcript (r)"
    let webShowOnMac = "Show on Mac"
    let webShowOnMacTip = "Bring this session's terminal to the front on the Mac"
    let webShowOnMacOff = "The server reports write: false — nothing can be sent yet"
    let webShowOnMacAsked = "Asked the Mac to bring it forward"
    let webSessionActions = "Session actions"
    let webSessionGit = "Git changes"
    let webGitTitle = "Git changes"
    let webGitClean = "Working tree clean"
    let webGitNotRepo = "Not a Git repository"
    let webGitFailed = "Could not read Git changes"
    let webGitRefresh = "Refresh"
    let webGitClose = "Close"
    let webGitStaged = "Staged"
    let webGitUnstaged = "Unstaged"
    let webGitUntracked = "Untracked"
    let webGitConflict = "Conflict"
    let webEndSession = "Close session"
    let webConfirmActionTitle = "Run {action}?"
    let webConfirmActionSay = "This sends {action} to the current session."
    let webConfirmEndTitle = "Close this session?"
    let webConfirmEndSay = "The assistant will quit, then its terminal tab will close."
    let webConfirmEndLoses = "Closing also ends:"
    let webClawdfatherCreateLabel = "Name the new session Clawdfather"
    let webClawdfatherIs = "This session is {name}"
    let webClawdfatherRegisterAsk = "Please register this new session as this Mac's Clawdfather, the machine coordinator. Your terminal-neutral session id is {id}. Read the coordinator record using the orchestrator token at ~/.config/clawdline/orchestrator-token. If and only if no coordinator is configured, follow the registration branch of “Becoming Clawdfather” in docs/orchestrator.md. If any coordinator is already configured, including one that is offline, do not replace it. Then report what happened."
    let webClawdfatherRegisterSent = "The new session was asked to become Clawdfather"
    let webClawdfatherRegisterLate = "The new session did not become ready in time to name it Clawdfather."
    let webClawdfatherRegisterBlocked = "This Mac's coordinator record cannot be read, so it is left exactly as it is."
    let webCoordSectionObserve = "Observe"
    let webCoordSectionCoordinate = "Coordinate"
    let webCoordSectionPresence = "Presence"
    let webCoordSectionAdmin = "Administration"
    let webCoordCmdStatusReport = "Status report"
    let webCoordCmdStatusReportSay = "Read Clawdfather's current status and active obligations."
    let webCoordCmdSinceAway = "Since you were away"
    let webCoordCmdSinceAwaySay = "Read the changes and decisions recorded since your last return point."
    let webCoordCmdDuplicates = "Duplicates, conflicts & ownership"
    let webCoordCmdDuplicatesSay = "Inspect duplicate work, conflicting claims and current ownership."
    let webCoordCmdLandingClosure = "Landing closure"
    let webCoordCmdLandingClosureSay = "Read the reviewed deliveries that still wait for root-owned landing."
    let webCoordCmdCoordinateWork = "Coordinate work"
    let webCoordCmdCoordinateWorkSay = "Draft coordination steps across the work already in flight."
    let webCoordCmdDispatch = "Dispatch independent work"
    let webCoordCmdDispatchSay = "Preview a dispatch that would start an independent child session."
    let webCoordCmdAsk = "Ask Clawdfather"
    let webCoordCmdAskSay = "Draft a question for Clawdfather's judgement."
    let webCoordCmdQuietWatch = "Quiet watch"
    let webCoordCmdQuietWatchSay = "Draft a quiet monitoring request without raising a human-waiting alert."
    let webCoordCmdScope = "Scope & permissions"
    let webCoordCmdScopeSay = "Read Clawdfather's current scope and granted permissions."
    let webCoordCmdStop = "Stop Clawdfather"
    let webCoordCmdStopSay = "Preview stopping Clawdfather."
    let webCoordCmdReconnect = "Reconnect Clawdfather"
    let webCoordCmdReconnectSay = "Preview reconnecting Clawdfather."
    let webCoordCmdDeepAudit = "Deep status audit"
    let webCoordCmdDeepAuditSay = "Ask Clawdfather to audit live work, deliveries and decisions across relevant sessions."
    let webCoordTokenExpected = "Expected Token effort: {effort}"
    let webCoordTokenLow = "Low"
    let webCoordTokenMedium = "Medium"
    let webCoordTokenHigh = "High"
    let webCoordTokenUnknown = "Unknown"
    let webCoordAuditPreview = "High-token, multi-session request. Nothing has been sent yet. Confirm to send the complete audit instruction to this exact Clawdfather Session. This first slice is agent-driven and has no persistent broker run record."
    let webCoordAuditWhyOffline = "Clawdfather is offline, so an audit request cannot be sent."
    let webCoordAuditWhyDisconnected = "This browser is offline, so an audit request cannot be sent."
    let webCoordAuditWhyNoWrite = "This browser does not currently have send/write capability."
    let webCoordAuditSending = "Sending request…"
    let webCoordAuditSent = "Audit request sent. This receipt does not mean the audit has finished."
    let webCoordAuditFailed = "Audit request was not sent ({code}): {message}"
    let webCoordEffectRead = "Read only"
    let webCoordEffectAdvisory = "Advisory"
    let webCoordEffectSpawns = "Starts session"
    let webCoordEffectMutation = "Changes state"
    let webCoordStateAvailable = "Available"
    let webCoordStateDraft = "Draft"
    let webCoordStateUnavailable = "Unavailable"
    let webCoordStatePreview = "Preview"
    let webCoordStateDisabled = "Disabled"
    let webCoordOnline = "{name} online"
    let webCoordOffline = "{name} offline"
    let webCoordControlsTitle = "{name} controls"
    let webCoordOpenControls = "Open {name} controls"
    let webCoordEmpty = "No supported Clawdfather commands were advertised."
    let webCoordDisabledFallback = "Disabled by Clawdfather."
    let webCoordPreviewTitle = "Clawdfather command"
    let webCoordPreviewNone = "No command selected; nothing has been sent."
    let webCoordPreviewMutation = "Preview only — nothing has been sent. Confirmation stays unavailable until the Clawdfather command API is connected."
    let webCoordPreviewDraft = "Offline draft only — nothing has been sent or presented as Clawdfather judgement."
    let webCoordPreviewSpawn = "Preview only — no session has been started."
    let webCoordPreviewContract = "Only this command's contract is shown; nothing has been sent."
    let webCoordWhyNoCommandRoute = "No route carries a command from this panel into a session yet, so nothing can be sent."
    let webCoordWhyNoReturnLedger = "This Mac does not record a return point yet, so there is nothing to read one against."
    let webCoordWhyDeviceCannotSpawn = "A paired device can never start a session — that separation is deliberate, and this button will not cross it."
    let webCoordWhyMachineTokenOnly = "Reconnecting needs the Mac's own orchestrator token, which a paired device deliberately does not hold."
    let webCoordReadFailed = "Could not read Clawdfather's bearings."
    let webCoordActiveTasks = "{n} tasks in flight"
    let webCoordPendingLandings = "{n} deliveries awaiting landing"
    let webCoordOpenWaits = "{n} open file waits"
    let webCoordCountUnknown = "{n} unknown"
    let webCoordStaleSessions = "The Mac's session picture is stale; these numbers may be old."
    let webCoordUnknown = "Unknown"
    let webCoordWaitingList = "Waiting on someone"
    let webCoordBlockingList = "Holding files others wait on"
    let webCoordAllQuiet = "Nothing is blocked, contested or waiting for an owner."
    let webCoordNoLandings = "Nothing delivered is waiting to land."
    let webCoordUnregistered = "No Clawdfather is registered on this Mac."
    let webCoordScopeLine = "{name} coordinates this Mac — machine scope."
    let webCoordScopeDevice = "From this panel Clawdfather can only be read. Sending work, starting sessions and changing machine state need the Mac's own credentials, and stay disabled here."
    let webClosing = "Closing…"
    let webCancel = "Cancel"
    let webConfirm = "Confirm"
    let webReviewBeforeClosing = "Review session"
    let webConfirmEndAnyway = "Close anyway"
    let webPickSession = "Pick a session on the left."
    let webReading = "Reading…"
    let webLoading = "Loading…"
    let webTranscriptFailed = "Could not read the transcript"
    let webWhoYou = "you"
    let webWhoTool = "tool"
    let webNoticeTask = "task"
    let webNoticeCompleted = "Task completed"
    let webNoticeFailed = "Task failed"
    let webNoticeTimedOut = "Task timed out"
    let webNoticeCancelled = "Task cancelled"
    let webNoticeCouldNotStart = "Task could not start"
    let webNoticeFinished = "Task finished"
    let webNoticeWorkspaceOverlap = "Workspace overlap"
    let webNoticeNoSiblings = "No sibling work is still running."
    let webNoticeOneSibling = "{n} sibling task is still running."
    let webNoticeManySiblings = "{n} sibling tasks are still running."
    let webNoticeClaimsReleased = "Claims were released; the child tab may still write."
    let webNoticeFileWaitRequested = "File wait requested"
    let webNoticeFileWaitReleased = "File wait released"
    let webNoticeHandoffPickedUp = "Handoff picked up"
    let webNoticeHandoffNeedsDelivery = "Handoff needs manual delivery"
    let webNoticeRecheckGit = "Re-check HEAD, status and diff before integrating."
    let webPending = "Waiting for the Mac…"
    let webAttachedImage = "{n} image attached"
    let webAttachedImages = "{n} images attached"
    let webSteps = "{n} steps"
    let webJustNow = "just now"
    let webMinutesAgo = "{n}m ago"
    let webCodeCopy = "Copy this code"
    let webCodeCopied = "Code copied."
    let webCodeCopyFailed = "Could not copy — select the text instead."

    let webSend = "Send"
    let webAttach = "Attach a picture"
    let webRemoveShot = "Remove {name}"
    let webWriteOpen = "Open a session to write to it."
    let webWriteOff = "*Sending is off* — the server reports `write: false`. The box is wired; it switches itself on when that changes."
    let webShotsOnlyPictures = "Only pictures can go with a message"
    let webShotsTooMany = "{n} pictures is the most one message can carry"
    let webShotTooBig = "That picture is too big to send, even shrunk"
    let webShotsTooBig = "Those pictures are too big to send together"
    let webShotUnreadable = "That picture could not be read"
    let webShotNeedsSession = "Open a session to send a picture to it"

    let webVoiceStart = "Dictate a message"
    let webVoiceStop = "Stop and transcribe"
    let webVoiceDone = "Done"
    let webVoiceListening = "Listening… {t}"
    let webVoiceReading = "Transcribing on the Mac… {n}s"
    let webVoiceSlow = "The first one after this Mac reboots loads the model first — about twelve seconds."
    let webVoiceLimit = "Recording stopped at {n} minutes, which is as long as one goes. Transcribing what there is."
    let webVoiceEmpty = "Nothing was heard in that."
    let webVoiceTooShort = "That was too short to hear."
    let webVoiceDenied = "The microphone was refused. Turn it back on in this browser's settings for this site."
    let webVoiceNoMic = "No microphone was found on this device."
    let webVoiceInUse = "The microphone is busy — something else on this device has it."
    let webVoiceInsecure = "A microphone needs https, and this page is not on it. The tunnel provides one; a plain address on the local network does not."
    let webVoiceUnsupported = "This browser cannot record audio."
    let webVoiceBusy = "One of these is being transcribed and another is waiting. Try again in a moment."
    let webVoiceNoBinary = "Whisper is not installed on the Mac, so there is nothing there to transcribe with."
    let webVoiceNoModel = "Whisper is on the Mac but has no model to read with. One ggml file in `~/.cache/whisper` is all it wants."
    let webVoiceFailed = "That could not be transcribed."

    let webHintMove = "move"
    let webHintOpen = "open"
    let webHintFilter = "filter"
    let webHintPane = "pane"

    let webKeysLabel = "Keyboard shortcuts"
    let webKeysTitle = "Keyboard"
    let webKeysMove = "Move through the list — `j` and `k` do the same"
    let webKeysOpen = "Open the selected session"
    let webKeysFilter = "Filter the list"
    let webKeysEscape = "Clear the filter, then step back"
    let webKeysList = "Focus the session list"
    let webKeysPane = "Show or hide the transcript"
    let webKeysEnds = "Top or bottom of the transcript"
    let webKeysReverse = "Reverse the transcript order"
    let webKeysThis = "This card"
    let webKeysFoot = "Anything typed into a text box stays in the text box — the shortcuts stand down while you write."

    let webDoorLabel = "Pair this browser"
    let webDoorAskLede = "This browser has not been let in yet."
    let webDoorAskFine = "Ask to pair and a six-digit code appears *on the Mac* — it is deliberately not in the reply to this page. Only somebody at that machine can finish this, and that is the point rather than the hurdle."
    let webDoorName = "Call this device"
    let webDoorAsk = "Ask to pair"
    let webDoorToPassword = "Sign in with a password instead"
    let webDoorCodeLede = "Look at the Mac."
    let webDoorCodeFine = "Clawdline is showing six digits for {left}. Type them here."
    let webDoorTwoMinutes = "two minutes"
    let webDoorDigit = "Digit {n}"
    let webDoorConfirm = "Pair this device"
    let webDoorRestart = "Start again"
    let webDoorPasswordLede = "Sign in with the password."
    let webDoorPasswordFine = "The one set in Clawdline on the Mac, under Settings → Remote. If none has been set, pairing is the way in."
    let webDoorPassword = "Password"
    let webDoorPasswordGo = "Sign in"
    let webDoorToPair = "Use a pairing code instead"
    let webDoorAsking = "Asking the Mac…"
    let webDoorAskFailed = "Could not ask the Mac."
    let webDoorRateLimited = "Each request puts an alert on the Mac, so there are only three every ten minutes."
    let webDoorSixDigits = "Six digits."
    let webDoorChecking = "Checking…"
    let webDoorFinished = "That pairing is finished — five wrong codes. Ask again when you are at the Mac."
    let webDoorWrongCode = "That code is not right."
    let webDoorNeedPassword = "The password, first."
    let webDoorWrongPassword = "That is not the password."
    let webDoorExpired = "That code has expired. Ask again and a fresh one appears on the Mac."
    let webDoorPaired = "Paired — this browser is in"

    let webOffline = "Could not reach Clawdline. Is it still running on the Mac?"
    let webNotJSON = "The server sent something that is not JSON"
    let webRequestFailed = "Request failed"

    let webNotifyGo = "Notify me"
    let webNotifyAsking = "Asking…"
    let webNotifyStop = "Stop"
    let webNotifyStopping = "Stopping…"
    let webNotifyOff = "when a session is waiting for an answer"
    let webNotifyOn = "This device is subscribed. What it gets told about is set on the Mac."
    let webNotifyBlocked = "Notifications are blocked for this site. That switch is in the browser's own settings, not here."
    let webNotifyUnsupported = "This browser cannot show notifications."
    let webNotifyHomeScreen = "Add clawdline to your home screen and open it from there — iOS only sends notifications to an app that lives there."
    let webNotifyOnFailed = "Could not turn notifications on"
    let webNotifyOffFailed = "Could not turn notifications off"

    let webSettings = "Settings"
    let webSettingsNotify = "Notifications"
    let webSettingsAssistantIcons = "Assistant icons"
    let webSettingsAssistantIconsSay = "Show the Claude or Codex mark before its name in the conversation."
    let webSettingsAssistantIconsShow = "Show icons"
    let webSettingsVersion = "Version {v}"
    let webClose = "Close"
    let webNotifySheetOff = "This device is not told when a session is waiting."
    let webNotifyTest = "Send a test"
    let webNotifyTestSent = "Sent — it should arrive on this device in a moment."
    let webNotifyTestNone = "The Mac has no subscription for this device. Turn notifications off and on again, and this browser will register a fresh one."
    let webNotifyTestFailed = "Could not send a test notification"
    let webSending = "Sending…"
    let webSendTip = "Return sends · Shift-Return starts a line"
    let webStart = "Start a session"
    let webStartLabel = "Start a session in a project"
    let webStartPick = "Where should it start?"
    let webStartWith = "Start with"
    let webStartEmpty = "Nowhere to start yet. Run Claude Code on the Mac once and it will be here."
    let webStartFilter = "Filter projects"
    let webStarting = "Opening a tab\u{2026}"
    let webStartWaiting = "Started. Waiting for it to appear\u{2026}"
    let webStartSlow = "The tab is open, but the session has not reported in. Have a look at the Mac."
    let webStartFailed = "That could not be started."
    let webStartGone = "That project is not on the Mac any more."
    let webStartTerminalClosed = "{app} is not running on the Mac. Open it there and try again."
    let webStartTerminalUnsupported = "A session cannot be started in {app} from here. Run tmux in it and this works."
    let webStartOff = "Starting a session is switched off. Settings \u{2192} Remote on the Mac turns it on."
    let webResumeWith = "Pick up an earlier one"
    let webResumePick = "Which conversation?"
    let webResumeFilter = "Filter conversations"
    let webResumeEmpty = "Nothing has been recorded in that project yet."
    let webResumeLive = "open now"
    let webResumeBack = "Another project"
    let webResumeGone = "That conversation is not on the Mac any more."
    let webResumeClaudeOnly = "Only Claude Code keeps conversations that can be picked back up."
    let webResuming = "Picking it back up\u{2026}"
    let webResumeCapped = "Older ones than these are not on this list."
    let webCommand = "Say what to start"
    let webCommandLabel = "Start a session by saying what to do"
    let webCommandSay = "Nothing is sent until you press Start below."
    let webCommandHeard = "What should it do?"
    let webCommandThinking = "Thinking…"
    let webCommandDraft = "Draft"
    let webCommandWhere = "Where"
    let webCommandWith = "With"
    let webCommandModel = "Model"
    let webCommandFirst = "First message"
    let webCommandGo = "Start"
    let webCommandUnsure = "Not sure which project — pick one below."
    let webCommandFailed = "Could not turn that into a draft."
    let webCommandNoPlanner = "This Mac has no Claude Code to turn that into a draft."
    let webCommandBusy = "Already turning one sentence into a draft — try again in a moment."
    let webCommandEmpty = "Heard nothing"
    let webScheduleNew = "New schedule"
    let webScheduleEdit = "Edit schedule"
    let webScheduleNewSay = "Nothing is scheduled until you press Create below."
    let webScheduleTitle = "Title"
    let webScheduleAt = "At"
    let webScheduleOn = "On"
    let webScheduleWhere = "Where"
    let webScheduleWith = "With"
    let webScheduleFirst = "First message"
    let webScheduleMore = "More"
    let webScheduleModel = "Model"
    let webScheduleWhenDone = "Close the tab when it finishes"
    let webScheduleCloseSuccess = "If it worked"
    let webScheduleCloseAlways = "Always"
    let webScheduleCloseNever = "Leave it open"
    let webScheduleEnabled = "Enabled"
    let webScheduleDisabled = "Disabled"
    let webScheduleNotify = "Tell me if it fails"
    let webScheduleCatchUp = "If it was missed, catch up within (hours)"
    let webScheduleTimeout = "Give up if it is not done in (minutes)"
    let webScheduleCreate = "Create"
    let webScheduleCreated = "Schedule created."
    let webScheduleDispatchOff = "The schedule is created and valid, but dispatch is off — nothing will run it. Settings \u{2192} Remote on the Mac turns it on."
    let webScheduleFailed = "Could not create the schedule."
    let webScheduleSave = "Save"
    let webScheduleSaved = "Schedule saved."
    let webScheduleDelete = "Delete"
    let webScheduleDeleteAsk = "Delete {title}? There is no undo."
    let webScheduleDeleted = "Schedule deleted."
    let webScheduleNeedsTime = "Didn't catch a time — set one."
    let webScheduleNeedsPlace = "Didn't catch which project — pick one."
    let webScheduleDaily = "Daily"
    let webScheduleSun = "Sun"
    let webScheduleMon = "Mon"
    let webScheduleTue = "Tue"
    let webScheduleWed = "Wed"
    let webScheduleThu = "Thu"
    let webScheduleFri = "Fri"
    let webScheduleSat = "Sat"
    let webLinks = "Links"
    let webLinksTip = "Where this project can be opened"
    let webLinksPick = "Everything this project has an address for."
    let webLinksEmpty = "This project has nothing with an address \u{2014} no site, no deploy, and no dev stack running."
    let webLinksFailed = "Could not read this project's links."
    let webLinksLocal = "On the Mac's own network only. It will not open from here."
    let webLinksFile = "A file on the Mac. It opens there, not in this browser."
    let webLinksCopy = "Copy path"
    let webLinksCopied = "Copied."
    let webLinksCopyFailed = "This browser would not let the page copy that."
    let webLinkOk = "ok"
    let webLinkFail = "failing"
    let webLinkDown = "down"
    let webLinkRunning = "running"
    let webSessionInfo = "Session info"
    let webInfoTitle = "About this session"
    let webInfoEditTitle = "Edit session title"
    let webInfoCopyTitle = "Copy this name"
    let webInfoTitleSaved = "Title saved."
    let webInfoTitleLocal = "Title saved in Clawdline; the downstream name was not changed."
    let webInfoTitleQueued = "Title saved in Clawdline; the Codex update is queued."
    let webInfoTitleNotDurable = "Title is showing here, but this Mac could not write it to disk; it will be gone after a restart."
    let webInfoTitleCloud = "Session titles can only be changed on the Mac itself, not over the cloud connection."
    let webInfoSession = "This session"
    let webInfoAssistant = "Assistant"
    let webInfoModel = "Model"
    let webInfoSessionId = "Session id"
    let webInfoDirectory = "Directory"
    let webInfoRunningFor = "Running for"
    let webInfoStatus = "Status"
    let webInfoWorkStatusMeaning = "This is the session's work status. One check means delivered and awaiting approval; two checks mean reviewed and approved."
    let webInfoCloseabilityMeaning = "The key shows whether this session can be closed safely. It is independent of delivery status."
    let webInfoUsage = "Token use"
    let webInfoInput = "Input"
    let webInfoOutput = "Output"
    let webInfoCacheRead = "Cache read"
    let webInfoCacheWrite = "Cache write"
    let webInfoTotal = "Total"
    let webInfoCost = "Estimated cost"
    let webInfoNoUsage = "No transcript found for this session yet."
    let webInfoLimits = "Plan limits"
    let webInfoLimitHit = "limit reached"
    let webInfoResets = "resets {when}"
    let webInfoUnknown = "unknown"
    let webInfoFiles = "Files"
    let webInfoBranch = "Branch"
    let webInfoStaged = "Staged"
    let webInfoUnstaged = "Changed"
    let webInfoUntracked = "Untracked"
    let webInfoConflict = "Conflicts"
    let webInfoClean = "Nothing uncommitted."
    let webInfoNotRepo = "Not a git repository."
    let webInfoDeploy = "Last deploy"
    let webInfoNoDeploy = "No deploy recorded for this project."
    let webInfoFailed = "Could not read this session's info."
    let webInfoBusy = "The Mac is busy reading other sessions — try again in a moment."
    let webInfoRefresh = "Refresh"
    let webInfoTokens = "tokens"
    let webInfoSwitchModel = "Switch model"
    let webInfoModelOther = "another model…"
    let webInfoModelSent = "Sent /model {model}. Confirming…"
    let webInfoModelBusy = "Switching waits until the session is idle."
    let webInfoSwitchPermission = "Switch permission mode"
    let webInfoPermissionAuto = "Auto"
    let webInfoPermissionManual = "Manual"
    let webInfoPermissionAcceptEdits = "Accept edits"
    let webInfoPermissionPlan = "Plan"
    let webInfoPermissionUnreadable = "Could not read the current mode."
    let webInfoPermissionSent = "Switched to {mode}. Confirming…"
    let webInfoPermissionBusy = "A permission mode change is being sent."
    let webInfoLimitsClaude = "Claude Code only writes a window down once it is spent, so nothing is known until then."
    let webInfoCopied = "Session id copied."
    let webInfoAsOf = "as of {when}"
    let webInfoWhyUnknown = "Why this is unknown, and how to get the numbers"
    let webSettingsOrder = "Transcript"
    let webSettingsOrderSay = "Which end of a transcript to start reading from. It applies to every session, and `r` does the same from a keyboard."
    let webAskLabel = "asked"
    let webAskAny = "Any number of these"
    let webWaitingTitle = "This session is waiting for an answer"
    let webWaitingSay = "Claude Code is showing a menu on the Mac. Clawdline cannot read a menu from here yet, so the choices are only on that screen."
    let webWaitingSend = "*Sending from here will not type your answer into the menu.* It confirms whichever option the menu has highlighted \u{2014} which is rarely the one you meant. Answer this one on the Mac."
    let webMenuSay = "Tap an answer and it goes straight to the session."
    let webMenuHighlighted = "highlighted"
    let webMenuSent = "Answer sent."
    let webAgents = "Background agents"
    let webAgentsCount = "{n} running"
    let webAgentDone = "done"
    let webAgentFailed = "failed"
    let webShells = "Background shells"
    let webShellTitle = "Background shell"
    let webShellOpen = "See what this command is printing"
    let webShellRunning = "still running"
    let webShellEnded = "finished"
    let webShellQuiet = "Nothing printed yet."
    let webShellFailed = "Could not read this command's output."
    let webShellClose = "Close"
    let webShellStop = "Stop"
    let webShellStopTitle = "Stop this command?"
    let webShellStopSay = "{command} is still running. It is asked to stop, and killed five seconds later if it does not. Nothing it has already done is undone."
    let webShellStopped = "Asked it to stop."
    let webShellStopFailed = "Could not stop it."
    let agentRunning = "running"
    let agentTools = "{n} tools"
    let agentEmpty = "This agent has not written anything down yet."
    let agentBack = "Session"
    let webAgentOpen = "See what this agent did"
    let webTaskRoot = "Root"
    let webTaskChild = "Child"
    let webTaskTasks = "Tasks"
    let webTaskDone = "done"
    let webTaskFailed = "failed"
    let webTaskRunning = "running"
    let webStale = "Clawdline has been rebuilt on the Mac. This page is the older one."
    let webStaleGo = "Reload"

    let menuOpen = "Open prompt bar"
    let menuReveal = "Jump to target tab"
    let menuMascot = "Mascot"
    let menuLogin = "Launch at login"
    let menuEditConfig = "Settings…"
    let menuReload = "Reload config"
    let menuQuit = "Quit Clawdline"
    let menuNoTarget = "(not detected yet)"

    func hotkeyFailedTitle(_ combo: String) -> String { "Could not register \(combo)" }
    func hotkeyFailedBody(_ configPath: String) -> String {
        """
        Another app has probably taken it — Spotlight, an input-method switcher, \
        BetterTouchTool, and so on.

        Pick a different one: edit "hotkey" in \(configPath), then choose \
        "Reload config" from the menu bar.

        Until then, the ✳ in the menu bar still opens the prompt bar.
        """
    }
    let loginFailed = "Could not set launch at login"
}
