import Foundation

struct Russian: Copy {
    let placeholder = "Сообщение для Claude Code…"

    let hintSend = "отправить"
    let hintNewline = "новая строка"
    let hintSwitch = "переключить"
    let hintList = "список"
    let hintMascot = "маскот"
    let hintOutput = "вывод"
    let hintFullscreen = "во весь экран"
    let hintKeys = "клавиши"
    let hintTextSize = "размер"
    let hintOrder = "обратный порядок"
    let hintVoice = "диктовка"
    func voiceListening(onDevice: Bool) -> String {
        onDevice ? "Слушает на этом Mac — нажмите ещё раз, чтобы остановить"
                 : "Слушает — этот язык распознаёт Apple, а не этот Mac"
    }
    let voiceNoPermission = "Диктовке нужен доступ к микрофону и распознаванию речи"
    let voiceUnavailable = "Диктовка сейчас недоступна"
    func voiceTranscribing(seconds: Double) -> String {
        String(format: "Whisper перечитывает… %.1f с", seconds)
    }
    let whisperMissing = "Whisper не установлен — см. docs/whisper.md"
    let whisperNothingHeard = "Ничего не услышал"
    func dictationStatus(_ status: Whisper.Status) -> String {
        switch status {
        case .ready(let model): return "Диктовка: Apple, затем Whisper (\(model))"
        case .noBinary: return "Диктовка: только Apple — нет whisper-cli"
        case .noModel: return "Диктовка: только Apple — whisper-cli есть, модели нет"
        }
    }
    func voiceListeningWhisper() -> String {
        "Слушает — когда вы закончите, Whisper перечитает"
    }

    let scanning = "Поиск…"
    let noSession = "Сессия Claude Code не найдена"
    let nothingToSend = "Некуда отправлять — сначала запустите Claude Code в терминале"
    let sendFailed = "Не удалось отправить"
    let itermSilent = "iTerm2 не ответил"
    let itermBusy = "iTerm2 ждёт ответа на диалог — закройте его на Mac"
    let scriptMissing = "Нет iterm.js — повреждённый бандл приложения?"
    let cannotList = "Не удалось прочитать сессии iTerm2"
    let noOutput = "В этой сессии пока нечего читать."
    let imageExpired = "Срок действия изображения истёк"
    let imagePreview = "Предпросмотр изображения"
    let imageClose = "Закрыть предпросмотр"
    let imageTooLarge = "Слишком большое для отправки ({mb} МБ)"
    let imageUnavailable = "Изображение не получено"
    func outputSize(_ pt: Int) -> String { "Размер текста вывода \(pt) pt — ⌘J, чтобы посмотреть" }
    func foldedTools(_ count: Int) -> String { "шагов: \(count)" }
    func outputOrder(newestFirst: Bool) -> String {
        newestFirst ? "Сначала новые" : "Сначала старые"
    }
    func backlogNow(_ count: Int) -> String { "сейчас \(count)" }
    func dropped(_ count: Int) -> String {
        count == 1 ? "Путь добавлен — Claude Code его прочитает" : "Добавлено путей: \(count)"
    }
    func stackConfirm(_ command: String) -> String { "Нажмите ещё раз, чтобы выполнить:  \(command)" }
    let hintStacks = "серверы"
    func stackTip(up: Int, total: Int) -> String { "Запущено \(up) из \(total) серверов — ⌘S для списка" }
    let stackTipUnknown = "У проекта есть серверы, но его команда состояния ещё не доверена — ⌘S"
    let stackUntrusted = "не доверено"
    let stackExit = "код выхода"
    let stackActionStart = "запустить"
    let stackActionRestart = "перезапуск"
    let stackActionStop = "остановить"
    let stackActionLogs = "журнал"
    let stackLogAll = "все"
    let stackLogBack = "расшифровка"
    let stackActionAllow = "разрешить"
    let stackActionAgain = "ещё раз"
    func sessionTip(index: Int, total: Int) -> String { "Сессия \(index) из \(total) — ⌘K для переключения" }
    let sessionWaiting = "ждёт вашего ответа"
    let sessionAgents = "{n} в фоне"
    let sessionShellOne = "1 shell работает"
    let sessionShellMany = "{n} shell работают"
    let sessionWaitedOnByOne = "1 ждёт вас"
    let sessionWaitedOnByMany = "{n} ждут вас"
    let islandDone = "готово"
    let islandAllSessions = "Все сессии…"
    func statusWaiting(_ labels: [String]) -> String {
        labels.count == 1 ? "\(labels[0]) ждёт вашего ответа"
                          : "\(labels.count) сессий ждут вашего ответа"
    }
    func statusWorking(_ count: Int) -> String { "\(count) выполняется" }

    let settingsTitle = "Настройки Clawdline"
    let settingsGeneral = "Основные"
    let settingsBar = "Строка"
    let settingsReading = "Чтение"
    let settingsVoice = "Диктовка"
    let settingsHotkey = "Сочетание клавиш"
    let settingsRecording = "Нажмите клавиши…"
    let settingsScope = "Работает в"
    let settingsScopeGlobal = "Во всех приложениях"
    let settingsScopeHint = "Пусто — значит везде, поэтому если убрать последнее, включится переключатель выше, а если выключить его обратно, список вернётся. В файле настроек это bundle id, и список, поправленный вручную, тоже работает."
    let settingsSessionTerminal = "Новые сессии открываются в"
    let settingsSessionTerminalHint = "Это не то же самое, где срабатывает сочетание клавиш. «Авто» — iTerm2, когда он открыт, и tmux, когда нет; iTerm2 просит именно iTerm2, поэтому работающий рядом сервер tmux ответом не считается, а закрытый iTerm2 — это отказ; tmux кладёт сессию в сервер tmux, даже если iTerm2 запущен. Действует со следующей сессии, перезапуск не нужен."
    let settingsScopeAdd = "Добавить приложение…"
    let settingsScopeChoose = "Выбрать приложение…"
    let settingsScopeRunning = "Открыты прямо сейчас"
    let settingsScopeRemove = "Убрать"
    let settingsLanguage = "Язык"
    let settingsReopen = "Строка приходит и уходит вместе с терминалом"
    let settingsReopenHint = "Ушли из терминала — строка убирается, вернулись в него — строка возвращается. А Esc означает, что вы с ней закончили."
    let settingsFollow = "Терминал показывает то, на что нацелена строка"
    let settingsFollowHint = "Выбирает вкладку этой сессии. Терминал на передний план не выводится: иначе каждое нажатие Tab уводило бы клавиатуру из поля, в котором вы печатаете."
    let settingsCodexAutoName = "Называть новые сессии"
    let settingsCodexAutoNameHint = "Для каждой сессии без имени запускается один небольшой ход выбранного помощника. Он использует первый запрос, расходует лимит этого помощника и не заменяет выбранное вами имя."
    let settingsNotch = "Жить в вырезе"
    let settingsNotchHint = "Персонаж в корпусе камеры. Выключено — значит выключено: ничего не рисуется и окно не создаётся."
    let settingsPosition = "Высота на экране"
    let settingsWidth = "Ширина"
    let settingsOpacity = "Непрозрачность карточки"
    let settingsShow = "Показывать"
    let settingsPaneHeight = "Высота панели"
    let settingsTextSize = "Размер текста"
    let settingsPaneFont = "Шрифт панели"
    let settingsBlur = "Размытие позади"
    let settingsNewestFirst = "Сначала новые"
    let settingsEngine = "Распознаватель"
    let settingsSettle = "Пауза завершает фразу"
    let settingsStop = "Тишина завершает сессию"
    let settingsAuto = "Авто"
    let settingsTranscript = "Расшифровка"
    let settingsTerminal = "Терминал"
    let settingsOff = "Выкл"
    let settingsHooks = "Хуки Claude Code"
    let settingsHooksHint = "Когда они установлены, Claude Code сам сообщает момент, когда ход начался, закончился или ждёт ответа, — вместо того чтобы Clawdline узнал об этом при следующем опросе. Читается всё по-прежнему с экрана; здесь решается только, насколько быстро."
    let settingsHooksInstall = "Установить"
    let settingsHooksRemove = "Убрать"
    let settingsHooksOff = "Не установлены — состояние читается только с экрана"
    let settingsHooksOn = "Установлены — ни одна сессия ещё не отозвалась"
    let settingsHooksLive = "Установлены, сессии отзываются"
    let settingsStateHook = "Когда сессия меняет состояние"
    let settingsStateHookHint = "Каждый раз, когда сессия берётся за работу, заканчивает или о чём-то вас спрашивает, Clawdline запускает это: вашу собственную программу, с подробностями в её окружении. Задаётся в файле настроек, а не здесь, потому что это argv, а не командная строка — путь с пробелом должен остаться одним путём."
    let settingsRemote = "Удалённый доступ"
    let settingsRemoteServe = "Разрешить браузеру или телефону видеть ваши сессии"
    let settingsRemoteHint = "Выключено — снаружи этого Mac ничто ни до чего не дотянется. Включено — список сессий отдаётся на 127.0.0.1: браузеру здесь, телефону через туннель, скрипту. Отдаются при этом имена репозиториев, ветки и названия задач, поэтому оно так и стоит выключенным, пока вы не скажете иначе."
    let settingsRemoteDevices = "Сопряжённые устройства"
    let settingsRemoteNoDevices = "Пока ни одного — за пределами этого Mac ничего прочитать нельзя"
    let settingsRemoteRevokeAll = "Отключить всё"
    let settingsRemoteOpen = "Открыть в браузере"
    let pairingIgnore = "Игнорировать"
    func pairingAsks(_ device: String) -> String { "\(device) хочет создать пару с этим Mac" }
    func pairingCode(_ code: String) -> String {
        """
        Введите этот код на нём:

        \(code)

        Он действует две минуты. Если вы только что этого не запрашивали — не обращайте \
        внимания: без этого кода тот, кто запросил, ничего не завершит.
        """
    }
    let settingsTunnel = "Дотянуться до этого Mac откуда угодно"
    let settingsTunnelQuick = "Сгенерированный адрес"
    let settingsTunnelNamed = "Мой собственный домен"
    let settingsTunnelHostname = "Имя хоста"
    let settingsTunnelHint = "Открывает исходящее соединение через cloudflared — никакого проброса портов, ничего слушающего в вашей сети. Не запустится, пока не сопряжено хотя бы одно устройство: за туннелем — имя каждого репозитория и название каждой задачи на этом Mac."
    let settingsRemoteWrite = "Разрешить сопряжённому устройству писать в сессию"
    let settingsRemoteWriteHint = "Выключено — сопряжённое устройство может только читать. Включено — оно может отправлять текст в сессию и запускать новые, а это выполняет код на этом Mac, потому что Claude Code именно этим и занимается. Решение здесь другое, чем выше, поэтому и переключатель отдельный."
    let settingsRemotePhone = "Сопрячь телефон…"
    let settingsRemotePhoneHint = "Показывает код для сканирования. У кода собственный ключ: снимок этого кода — это устройство, которое видно в списке выше и которое можно отключить, а не ключ самого этого Mac."
    let pairingScanTitle = "Наведите на это телефон"
    let pushWaiting = "ждёт ответа"
    let pushTest = "Тестовое уведомление. Всё подключено."
    let pushDelivered = "сдал работу и ждёт вас"
    let pushDeployOk = "деплой прошёл успешно"
    let pushDeployFail = "деплой не удался"
    func pushChildWaiting(minutes: Int?) -> String {
        guard let minutes else { return "дочерняя сессия ждёт ответа" }
        return "дочерняя сессия ждёт ответа — осталось \(minutes) мин"
    }
    func pushBatchDone(done: Int, failed: Int) -> String {
        let all = "задач завершено: \(done)"
        return failed == 0 ? all : "\(all), с ошибкой: \(failed)"
    }
    let settingsPushDelivery = "Сообщать, когда сессия сообщает о сдаче работы"
    let settingsPushDeliveryHint = "Один раз на сообщение; повтор того же молчит."
    let settingsPushFanout = "Сообщать, когда закончится пачка задач"
    let settingsPushFanoutHint = "Одно уведомление на всю пачку, с числом ошибок."
    let settingsSmartNotifications = "Умные уведомления"
    let settingsSmartNotificationsHint = "Haiku одним предложением опишет результат. При ошибке придёт обычное уведомление."
    func pushCoalesced(count: Int) -> String { "Завершено сразу: \(count)" }
    let settingsSmartHealthIdle = "Умные уведомления ещё не пробовались."
    func settingsSmartHealth(attempts: Int, successes: Int) -> String {
        "Из \(attempts) попыток \(successes) доставили фразу модели."
    }
    func settingsSmartHealthFailure(reason: String, time: String) -> String {
        "Последний откат в \(time): \(reason)."
    }
    func settingsSmartTimeout(seconds: Int) -> String {
        "Claude превысил лимит в \(seconds) с и был остановлен"
    }
    let settingsSmartQueueFull = "завершений больше, чем вмещает очередь"
    let settingsSmartModelFailed = "Claude не вернул ничего пригодного"
    let settingsSmartNoSource = "нечего было резюмировать"
    let settingsSmartMissing = "исполняемый файл claude не найден"
    let settingsPushDeploy = "Сообщать, когда закончится деплой"
    let settingsPushDeployHint = "И об успехе, и об ошибке."
    let settingsAgentNotify = "Разрешить агентам отправлять свои уведомления"
    let settingsAgentNotifyNote = "Управляет только содержимым, которое агент отправляет сам; уведомления о завершении, деплое и остальные не меняются."
    let settingsOrchestrator = "Работа для другой сессии"
    let settingsOrchestratorEnabled = "Разрешить сессии передавать работу другой"
    let settingsOrchestratorEnabledHint = "Сессия со скиллом clawdline может открыть вкладку, впечатать в неё задание и узнать, когда работа сделана. Выключено — каждая заявка отклоняется; то, что уже работает, не останавливается."
    let settingsOrchestratorMax = "Дочерних сессий сразу"
    let settingsOrchestratorMaxHint = "По умолчанию пять, и счёт идёт на сессию, а не на весь Mac. Каждая — вкладка терминала, в которой работает ассистент."
    let settingsOrchestratorPermission = "Насколько далеко дочерняя идёт сама"
    let settingsOrchestratorPermissionHint = "На вкладку дочерней сессии никто не смотрит, поэтому та, что остановилась ради подтверждения, стоит до истечения времени — а работа отправленной сессии целиком состоит из запуска команд и записи файлов, так что всё, кроме последнего пункта, где-нибудь её остановит. Задача может попросить меньше этого, но не больше."
    let settingsOrchestratorPermissionAsk = "Спрашивать на каждом шаге"
    let settingsOrchestratorPermissionEdits = "Писать файлы без вопросов"
    let settingsOrchestratorPermissionFull = "Не спрашивать"
    let settingsOrchestratorNotify = "Сообщать той сессии, которая попросила"
    let settingsOrchestratorNotifyHint = "Одна строка, впечатанная в неё, когда задача заканчивается."
    let settingsOrchestratorClose = "Когда дочерняя сессия отчитается"
    let settingsOrchestratorCloseHint = "Её вкладка закрывается после отчёта; та, что не уложилась в срок, остаётся открытой — чтобы вы её прочитали."
    let settingsOrchestratorCloseNow = "Закрывать вкладку сразу"
    let settingsOrchestratorCloseLinger = "Закрывать через три минуты"
    let settingsOrchestratorCloseKeep = "Оставлять открытой"
    let settingsOrchestratorPolicy = "Как раздаётся работа"
    let settingsOrchestratorPolicyHint = "Правила, которые Clawdline читает при каждой отправке и переносит в инструкцию каждой дочерней сессии, которой можно отправлять дальше: какой ассистент, какая модель, какой формы должен быть граф. Пусто — правил нет."
    let settingsOrchestratorPolicyEdit = "Изменить правила"
    func settingsOrchestratorPolicyOn(_ lines: Int) -> String { return "Действуют — строк: \(lines)" }
    let settingsOrchestratorPolicyOff = "Правил нет — каждый раз решает тот, кто отправляет"
    let settingsSchedules = "Расписания"
    let settingsSchedulesEmpty = "Расписаний пока нет. Кнопка «Новое расписание» ниже создаёт первое."
    let settingsScheduleNew = "Новое расписание"
    let settingsScheduleEdit = "Изменить"
    let settingsScheduleSave = "Сохранить"
    let settingsScheduleDelete = "Удалить"
    let settingsScheduleRun = "Запустить"
    let settingsScheduleReveal = "Показать в Finder"
    let settingsSchedulesFolder = "Открыть папку schedules"
    let settingsScheduleNext = "Следующий"
    let settingsScheduleLast = "Последний"
    let settingsScheduleNever = "Ещё не запускалось"
    let settingsScheduleStarted = "Запуск начат."
    let settingsScheduleActive = "Предыдущая задача этого расписания ещё выполняется."
    let webScheduleMissed = "Последний пропуск"
    let webScheduleNoNext = "Следующий запуск не запланирован."
    func childAnnounce(_ title: String) -> String { "Задача от Clawdline принята: \(title) — приступаю." }
    func settingsSeconds(_ value: Double) -> String { String(format: "%.1f с", value) }

    let webConnLive = "на связи"
    let webConnConnecting = "подключение"
    let webConnRetrying = "повтор через {n} с"
    let webConnOffline = "нет связи"
    let webConnLocked = "нет пары"
    let webConnTipLive = "Поток из приложения"
    let webConnTipLocked = "Этот браузер не сопряжён с этим Mac"
    let webConnTipDown = "Нет связи — нажмите, чтобы попробовать"

    let webCountWorking = "в работе: {n}"
    let webCountWaiting = "в ожидании: {n}"
    let webCountUnreadable = "нечитаемых: {n}"
    let webCountQuietOne = "{n} сессия, всё тихо"
    let webCountQuietMany = "сессий: {n}, всё тихо"
    let webCountNone = "нет сессий"

    let webFilterPlaceholder = "Фильтр по задаче, проекту или tty"
    let webFilterLabel = "Фильтр сессий"
    let webListLabel = "Сессии Claude Code"
    let webPull = "Потяните, чтобы обновить"
    let webPullRelease = "Отпустите, чтобы обновить"
    let webPullBusy = "Обновление…"
    let webEmptyFilterTitle = "Ничего не подходит под «{q}»"
    let webEmptyFilterHint = "Esc очищает фильтр"
    let webEmptyLockedTitle = "Это устройство не сопряжено"
    let webEmptyLockedHint = "Приложение ответило 401 — создайте пару в Clawdline на Mac"
    let webEmptyNoneHint = "Запустите её в терминале, и она появится здесь"
    let webEmptyWaitTitle = "Ждём приложение"
    let webEmptyWaitHint = "В потоке пока ничего не появилось"
    let webStateUnreadable = "экран не прочитать"
    let webStateWorking = "в работе"
    let sessionWorkReady = "может взять новую работу"
    let sessionWorkUnknown = "статус неизвестен"
    let sessionWorkHolding = "движется само"
    let sessionWorkOwed = "за вами решение"
    let sessionWorkSelfStated = "по самоотчёту"
    let sessionWorkMilestone = "Этап сдан; проверка или вливание могут оставаться"
    let sessionWorkComplete = "Подтверждённое брокером вливание в целевую ветку"
    let closeabilitySafe = "Можно безопасно закрыть"
    let closeabilityBlocked = "Осталось обязательств: {n}"
    let closeabilityBlockedOne = "Осталось 1 обязательство"
    let closeabilityBlockedMany = "Осталось обязательств: {n}"
    let closeabilityNeedsAttestation = "Ждём подтверждения от самой сессии"
    let closeabilityUnknown = "Можно ли закрыть — неизвестно"
    let closeabilityWhy = "Закрыть нельзя, потому что"
    let closeabilityMoverSelf = "это двигает сама сессия"
    let closeabilityMoverPerson = "это двигаете вы"
    let closeabilityMoverSession = "это двигает другая сессия"
    let closeabilityMoverBroker = "нужно свежее чтение"
    let closeabilityNotProven = "Брокер не смог доказать, что эту сессию можно безопасно закрыть."
    let closeabilityAttestationExplanation = "Это не означает, что найдена незавершённая работа. Проверки, доступные Clawdline, пройдены, но сессия ещё не подтвердила, остались ли локальные изменения, несданная работа или работа вне Clawdline. Проверьте сессию перед закрытием."
    let closeabilityTechnicalDetails = "Технические подробности"

    let webBack = "Сессии"
    let webBackLabel = "Назад к списку сессий"
    let webMenu = "Меню"
    let webPages = "Страницы"
    let webSessions = "Сессии"
    let webUsage = "Расход"
    let webNoSessionOpen = "Сессия не открыта"
    let webOrderTip = "Перевернуть расшифровку (r)"
    let webShowOnMac = "Показать на Mac"
    let webShowOnMacTip = "Вывести терминал этой сессии на передний план на Mac"
    let webShowOnMacOff = "Сервер сообщает write: false — отправить пока ничего нельзя"
    let webShowOnMacAsked = "Mac попросили вывести её вперёд"
    let webSessionActions = "Действия с сессией"
    let webSessionGit = "Изменения Git"
    let webScreenTitle = "Экран"
    let webScreenLive = "в реальном времени"
    let webScreenOnDemand = "по запросу"
    let webScreenGone = "Не удалось прочитать этот экран"
    let webGitTitle = "Изменения Git"
    let webGitClean = "Рабочее дерево не изменено"
    let webGitNotRepo = "Это не репозиторий Git"
    let webGitFailed = "Не удалось прочитать изменения Git"
    let webGitRefresh = "Обновить"
    let webGitClose = "Закрыть"
    let webGitStaged = "Добавлено в индекс"
    let webGitUnstaged = "Не добавлено в индекс"
    let webGitUntracked = "Не отслеживается"
    let webGitConflict = "Конфликт"
    let webEndSession = "Закрыть сессию"
    let webConfirmActionTitle = "Выполнить {action}?"
    let webConfirmActionSay = "Команда {action} будет отправлена в текущую сессию."
    let webConfirmEndTitle = "Закрыть эту сессию?"
    let webConfirmEndSay = "Ассистент завершит работу, затем закроется вкладка терминала."
    let webConfirmEndLoses = "Закрытие также завершит:"
    let webClawdfatherCreateLabel = "Назвать новую сессию Clawdfather"
    let webClawdfatherIs = "Эта сессия — {name}"
    let webClawdfatherRegisterAsk = "Зарегистрируй эту новую сессию как Clawdfather этого Mac — координатора машины. Твой terminal-neutral id сессии — {id}. Прочитай запись координатора с токеном оркестратора из ~/.config/clawdline/orchestrator-token. Только если ни один координатор не настроен, выполни часть про регистрацию из «Becoming Clawdfather» в docs/orchestrator.md. Если координатор уже настроен, даже офлайн, не заменяй его. Потом расскажи, что вышло."
    let webClawdfatherRegisterSent = "Новую сессию попросили стать Clawdfather"
    let webClawdfatherRegisterLate = "Новая сессия не успела подготовиться, чтобы стать Clawdfather."
    let webClawdfatherRegisterBlocked = "Запись координатора на этом Mac не читается, поэтому её оставили как есть."
    let webCoordSectionObserve = "Наблюдение"
    let webCoordSectionCoordinate = "Координация"
    let webCoordSectionPresence = "Присутствие"
    let webCoordSectionAdmin = "Администрирование"
    let webCoordCmdStatusReport = "Отчёт о состоянии"
    let webCoordCmdStatusReportSay = "Прочитать текущее состояние Clawdfather и его действующие обязанности."
    let webCoordCmdSinceAway = "Пока вас не было"
    let webCoordCmdSinceAwaySay = "Прочитать изменения и решения, записанные с вашей последней точки возврата."
    let webCoordCmdDuplicates = "Дубли, конфликты и владение"
    let webCoordCmdDuplicatesSay = "Просмотреть дублирующуюся работу, конфликтующие заявки и текущее владение."
    let webCoordCmdLandingClosure = "Закрытие поставок"
    let webCoordCmdLandingClosureSay = "Прочитать проверенные поставки, всё ещё ожидающие интеграции корневой сессией."
    let webCoordCmdCoordinateWork = "Координировать работу"
    let webCoordCmdCoordinateWorkSay = "Набросать шаги координации по уже идущей работе."
    let webCoordCmdDispatch = "Поручить независимую работу"
    let webCoordCmdDispatchSay = "Предпросмотр поручения, которое запустило бы независимую дочернюю сессию."
    let webCoordCmdAsk = "Спросить Clawdfather"
    let webCoordCmdAskSay = "Набросать вопрос на суждение Clawdfather."
    let webCoordCmdQuietWatch = "Тихое наблюдение"
    let webCoordCmdQuietWatchSay = "Набросать запрос тихого наблюдения без сигнала ожидания."
    let webCoordCmdScope = "Область и права"
    let webCoordCmdScopeSay = "Прочитать текущую область Clawdfather и предоставленные права."
    let webCoordCmdStop = "Остановить Clawdfather"
    let webCoordCmdStopSay = "Предпросмотр остановки Clawdfather."
    let webCoordCmdReconnect = "Переподключить Clawdfather"
    let webCoordCmdReconnectSay = "Предпросмотр переподключения Clawdfather."
    let webCoordCmdDeepAudit = "Глубокий аудит состояния"
    let webCoordCmdDeepAuditSay = "Попросить Clawdfather проверить работу, поставки и решения во всех связанных Session."
    let webCoordTokenExpected = "Ожидаемая нагрузка Token: {effort}"
    let webCoordTokenLow = "Низкая"
    let webCoordTokenMedium = "Средняя"
    let webCoordTokenHigh = "Высокая"
    let webCoordTokenUnknown = "Неизвестна"
    let webCoordAuditPreview = "Многосессионный запрос с высокой нагрузкой Token. Пока ничего не отправлено. Подтвердите отправку полной инструкции именно в эту Session Clawdfather. Первая версия выполняется агентом и не имеет постоянной записи run в broker."
    let webCoordAuditWhyOffline = "Clawdfather не в сети, поэтому запрос аудита отправить нельзя."
    let webCoordAuditWhyDisconnected = "Этот браузер не в сети, поэтому запрос аудита отправить нельзя."
    let webCoordAuditWhyNoWrite = "У этого браузера сейчас нет права на отправку/запись."
    let webCoordAuditSending = "Запрос отправляется…"
    let webCoordAuditSent = "Запрос аудита отправлен. Эта квитанция не означает, что аудит завершён."
    let webCoordAuditFailed = "Запрос аудита не отправлен ({code}): {message}"
    let webCoordEffectRead = "Только чтение"
    let webCoordEffectAdvisory = "Совещательное"
    let webCoordEffectSpawns = "Запускает сессию"
    let webCoordEffectMutation = "Меняет состояние"
    let webCoordStateAvailable = "Доступно"
    let webCoordStateDraft = "Черновик"
    let webCoordStateUnavailable = "Недоступно"
    let webCoordStatePreview = "Предпросмотр"
    let webCoordStateDisabled = "Отключено"
    let webCoordOnline = "{name} в сети"
    let webCoordOffline = "{name} не в сети"
    let webCoordControlsTitle = "Управление {name}"
    let webCoordOpenControls = "Открыть управление {name}"
    let webCoordEmpty = "Не объявлено ни одной поддерживаемой команды Clawdfather."
    let webCoordDisabledFallback = "Отключено Clawdfather."
    let webCoordPreviewTitle = "Команда Clawdfather"
    let webCoordPreviewNone = "Команда не выбрана; ничего не отправлено."
    let webCoordPreviewMutation = "Только предпросмотр — ничего не отправлено. Подтверждение остаётся недоступным, пока API команд Clawdfather не подключён."
    let webCoordPreviewDraft = "Только офлайн-черновик — ничего не отправлено и не выдано за суждение Clawdfather."
    let webCoordPreviewSpawn = "Только предпросмотр — ни одна сессия не запущена."
    let webCoordPreviewContract = "Показан только контракт этой команды; ничего не отправлено."
    let webCoordWhyNoCommandRoute = "Пока ни один маршрут не несёт команду из этой панели в сессию, поэтому отправить ничего нельзя."
    let webCoordWhyNoReturnLedger = "Этот Mac ещё не записывает точку возврата, поэтому читать не от чего."
    let webCoordWhyDeviceCannotSpawn = "Сопряжённое устройство никогда не может запустить сессию — это разделение сделано намеренно, и эта кнопка его не пересечёт."
    let webCoordWhyMachineTokenOnly = "Для переподключения нужен токен оркестратора самого Mac, которого у сопряжённого устройства намеренно нет."
    let webCoordReadFailed = "Не удалось прочитать сводку Clawdfather."
    let webCoordActiveTasks = "{n} задач в работе"
    let webCoordPendingLandings = "{n} поставок ждут интеграции"
    let webCoordOpenWaits = "{n} открытых ожиданий файлов"
    let webCoordCountUnknown = "{n} неизвестно"
    let webCoordStaleSessions = "Картина сессий на Mac устарела; эти числа могут быть старыми."
    let webCoordUnknown = "Неизвестно"
    let webCoordWaitingList = "Ждут кого-то"
    let webCoordBlockingList = "Держат файлы, которых ждут другие"
    let webCoordAllQuiet = "Ничего не заблокировано, не оспаривается и не осталось без владельца."
    let webCoordNoLandings = "Ни одна поставка не ждёт интеграции."
    let webCoordUnregistered = "На этом Mac не зарегистрирован Clawdfather."
    let webCoordScopeLine = "{name} координирует этот Mac — область: машина."
    let webCoordScopeDevice = "Из этой панели Clawdfather можно только читать. Отправка работы, запуск сессий и изменение состояния машины требуют учётных данных самого Mac и остаются здесь отключёнными."
    let webClosing = "Закрытие…"
    let webCancel = "Отмена"
    let webConfirm = "Подтвердить"
    let webReviewBeforeClosing = "Проверить сессию"
    let webConfirmEndAnyway = "Всё равно закрыть"
    let webPickSession = "Выберите сессию слева."
    let webReading = "Читаем…"
    let webLoading = "Загрузка…"
    let webTranscriptFailed = "Не удалось прочитать расшифровку"
    let webWhoYou = "вы"
    let webWhoTool = "инструмент"
    let webNoticeTask = "задача"
    let webNoticeCompleted = "Задача завершена"
    let webNoticeFailed = "Задача завершилась с ошибкой"
    let webNoticeTimedOut = "Время задачи истекло"
    let webNoticeCancelled = "Задача отменена"
    let webNoticeCouldNotStart = "Не удалось запустить задачу"
    let webNoticeFinished = "Задача завершена"
    let webNoticeWorkspaceOverlap = "Пересечение рабочих областей"
    let webNoticeNoSiblings = "Другие одноуровневые задачи не выполняются."
    let webNoticeOneSibling = "Выполняется ещё {n} одноуровневая задача."
    let webNoticeManySiblings = "Выполняются одноуровневые задачи: {n}."
    let webNoticeClaimsReleased = "Бронирование путей снято; дочерняя вкладка всё ещё может записывать данные."
    let webNoticeFileWaitRequested = "Запрошено ожидание файлов"
    let webNoticeFileWaitReleased = "Ожидание файлов снято"
    let webNoticeHandoffPickedUp = "Передача принята"
    let webNoticeHandoffNeedsDelivery = "Передачу нужно доставить вручную"
    let webNoticeRecheckGit = "Перед интеграцией снова проверьте HEAD, status и diff."
    let webPending = "Ждём Mac…"
    let webAttachedImage = "Прикреплено изображение: {n}"
    let webAttachedImages = "Прикреплено изображений: {n}"
    let webSteps = "шагов: {n}"
    let webJustNow = "только что"
    let webMinutesAgo = "{n} мин назад"
    let webCodeCopy = "Скопировать этот код"
    let webCodeCopied = "Код скопирован."
    let webCodeCopyFailed = "Не удалось скопировать — выделите текст."

    let webSend = "Отправить"
    let webAttach = "Прикрепить картинку"
    let webRemoveShot = "Убрать {name}"
    let webWriteOpen = "Откройте сессию, чтобы в неё писать."
    let webWriteOff = "*Отправка выключена* — сервер сообщает `write: false`. Поле подключено; оно включится само, когда это изменится."
    let webShotsOnlyPictures = "С сообщением могут уйти только картинки"
    let webShotsTooMany = "Больше {n} картинок одно сообщение не унесёт"
    let webShotTooBig = "Эта картинка слишком велика для отправки, даже уменьшенная"
    let webShotsTooBig = "Эти картинки слишком велики, чтобы уйти вместе"
    let webShotUnreadable = "Эту картинку не удалось прочитать"
    let webShotNeedsSession = "Откройте сессию, чтобы отправить в неё картинку"

    let webVoiceStart = "Продиктовать сообщение"
    let webVoiceStop = "Остановить и расшифровать"
    let webVoiceDone = "Готово"
    let webVoiceListening = "Слушаем… {t}"
    let webVoiceReading = "Расшифровываем на Mac… {n} с"
    let webVoiceSlow = "Первая после перезагрузки этого Mac сначала грузит модель — секунд двенадцать."
    let webVoiceLimit = "Запись остановилась на {n} минутах — дольше одна не идёт. Расшифровываем то, что есть."
    let webVoiceEmpty = "Там ничего не услышали."
    let webVoiceTooShort = "Это было слишком коротко, чтобы что-то расслышать."
    let webVoiceDenied = "Микрофон отклонён. Включите его обратно в настройках этого браузера для этого сайта."
    let webVoiceNoMic = "На этом устройстве микрофон не найден."
    let webVoiceInUse = "Микрофон занят — им владеет что-то другое на этом устройстве."
    let webVoiceInsecure = "Микрофону нужен https, а эта страница не по нему. Туннель его даёт; обычный адрес в локальной сети — нет."
    let webVoiceUnsupported = "Этот браузер не умеет записывать звук."
    let webVoiceBusy = "Одну сейчас расшифровывают, другая ждёт. Попробуйте через минуту."
    let webVoiceNoBinary = "На Mac нет Whisper, так что там нечем это расшифровать."
    let webVoiceNoModel = "Whisper на Mac есть, а модели для чтения нет. Ему хватит одного файла ggml в `~/.cache/whisper`."
    let webVoiceFailed = "Это не удалось расшифровать."

    let webHintMove = "листать"
    let webHintOpen = "открыть"
    let webHintFilter = "фильтр"
    let webHintPane = "панель"

    let webKeysLabel = "Сочетания клавиш"
    let webKeysTitle = "Клавиатура"
    let webKeysMove = "Двигаться по списку — `j` и `k` делают то же"
    let webKeysOpen = "Открыть выбранную сессию"
    let webKeysFilter = "Отфильтровать список"
    let webKeysEscape = "Очистить фильтр, потом шаг назад"
    let webKeysList = "Перейти к списку сессий"
    let webKeysPane = "Показать или скрыть расшифровку"
    let webKeysEnds = "Начало или конец расшифровки"
    let webKeysReverse = "Перевернуть порядок расшифровки"
    let webKeysThis = "Эта карточка"
    let webKeysFoot = "Всё, что набрано в текстовом поле, в поле и остаётся — пока вы пишете, сочетания не срабатывают."

    let webDoorLabel = "Сопрячь этот браузер"
    let webDoorAskLede = "Этот браузер сюда ещё не впустили."
    let webDoorAskFine = "Запросите пару — и шестизначный код появится *на Mac*, а не в ответе этой странице: так задумано. Довести дело до конца может только тот, кто сидит за той машиной, и в этом весь смысл, а не помеха."
    let webDoorName = "Назовите это устройство"
    let webDoorAsk = "Запросить пару"
    let webDoorToPassword = "Войти по паролю"
    let webDoorCodeLede = "Посмотрите на Mac."
    let webDoorCodeFine = "Clawdline показывает шесть цифр ещё {left}. Введите их здесь."
    let webDoorTwoMinutes = "две минуты"
    let webDoorDigit = "Цифра {n}"
    let webDoorConfirm = "Сопрячь это устройство"
    let webDoorRestart = "Начать заново"
    let webDoorPasswordLede = "Войдите по паролю."
    let webDoorPasswordFine = "Это тот пароль, что задан в Clawdline на Mac, в Настройках → Удалённый доступ. Если он не задан, внутрь ведёт только пара."
    let webDoorPassword = "Пароль"
    let webDoorPasswordGo = "Войти"
    let webDoorToPair = "Ввести код сопряжения"
    let webDoorAsking = "Спрашиваем Mac…"
    let webDoorAskFailed = "Не удалось спросить Mac."
    let webDoorRateLimited = "Каждый запрос выводит уведомление на Mac, поэтому их всего три за десять минут."
    let webDoorSixDigits = "Шесть цифр."
    let webDoorChecking = "Проверяем…"
    let webDoorFinished = "Эта пара закрыта — пять неверных кодов. Запросите заново, когда будете за Mac."
    let webDoorWrongCode = "Этот код неверный."
    let webDoorNeedPassword = "Сначала пароль."
    let webDoorWrongPassword = "Это не тот пароль."
    let webDoorExpired = "Этот код истёк. Запросите заново — на Mac появится новый."
    let webDoorPaired = "Пара создана — браузер внутри"

    let webOffline = "Не удалось достучаться до Clawdline. Он ещё запущен на Mac?"
    let webNotJSON = "Сервер прислал что-то, что не JSON"
    let webRequestFailed = "Запрос не удался"

    let webNotifyGo = "Сообщать мне"
    let webNotifyAsking = "Спрашиваем…"
    let webNotifyStop = "Отключить"
    let webNotifyStopping = "Отключаем…"
    let webNotifyOff = "когда сессия ждёт ответа"
    let webNotifyOn = "Это устройство подписано. О чём ему сообщать, задаётся на Mac."
    let webNotifyBlocked = "Уведомления для этого сайта заблокированы. Этот переключатель — в настройках самого браузера, не здесь."
    let webNotifyUnsupported = "Этот браузер не умеет показывать уведомления."
    let webNotifyHomeScreen = "Добавьте clawdline на домашний экран и открывайте оттуда — iOS шлёт уведомления только приложению, которое там живёт."
    let webNotifyOnFailed = "Не удалось включить уведомления"
    let webNotifyOffFailed = "Не удалось выключить уведомления"

    let webSettings = "Настройки"
    let webSettingsNotify = "Уведомления"
    let webSettingsAssistantIcons = "Значки ассистентов"
    let webSettingsAssistantIconsSay = "Показывать значок Claude или Codex перед его именем в диалоге."
    let webSettingsAssistantIconsShow = "Показывать значки"
    let webSettingsVersion = "Версия {v}"
    let webClose = "Закрыть"
    let webNotifySheetOff = "Этому устройству не сообщают, когда сессия ждёт."
    let webNotifyTest = "Отправить тест"
    let webNotifyTestSent = "Отправлено — вот-вот придёт на это устройство."
    let webNotifyTestNone = "На Mac нет подписки для этого устройства. Выключите и снова включите уведомления — браузер зарегистрирует новую."
    let webNotifyTestFailed = "Не удалось отправить тестовое уведомление"
    let webSending = "Отправка…"
    let webSendTip = "Return отправляет · Shift-Return переносит строку"
    let webStart = "Начать сессию"
    let webStartLabel = "Начать сессию в проекте"
    let webStartPick = "Где её начать?"
    let webStartWith = "Чем её начать?"
    let webStartEmpty = "Пока негде начинать. Запустите Claude Code на Mac один раз — и проект появится здесь."
    let webStartFilter = "Фильтр проектов"
    let webStarting = "Открываем вкладку…"
    let webStartWaiting = "Запущена. Вот-вот появится…"
    let webStartSlow = "Вкладка открыта, но сессия не отозвалась. Загляните на Mac."
    let webStartFailed = "Запустить это не удалось."
    let webStartGone = "Этого проекта на Mac больше нет."
    let webStartTerminalClosed = "На Mac не запущен {app}. Откройте его там и попробуйте снова."
    let webStartTerminalUnsupported = "В настройках новые сессии открываются в tmux, а на этом Mac нет tmux. Установите его там или выберите другой терминал в настройках."
    let webStartDetached = "Сессия запустилась в сервере tmux, к которому никто не подключён. Введите на Mac {command}, чтобы её увидеть."
    let webStartOff = "Запуск сессий выключен. Включается на Mac, в Настройках → Удалённый доступ."
    let webResumeWith = "Продолжить прежний"
    let webResumePick = "Какой разговор?"
    let webResumeFilter = "Отфильтровать разговоры"
    let webResumeEmpty = "В этом проекте пока ничего не записано."
    let webResumeLive = "открыт"
    let webResumeBack = "Другой проект"
    let webResumeGone = "Этого разговора больше нет на Mac."
    let webResumeClaudeOnly = "Только Claude Code хранит разговоры, которые можно продолжить."
    let webResuming = "Продолжаем…"
    let webResumeCapped = "Более старых в этом списке нет."
    let webCommand = "Скажите, что начать"
    let webCommandLabel = "Начать сессию, сказав, что она должна сделать"
    let webCommandSay = "Ничего не отправляется, пока вы не нажмёте «Начать» внизу."
    let webCommandHeard = "Что нужно сделать?"
    let webCommandThinking = "Думаем…"
    let webCommandDraft = "Черновик"
    let webCommandWhere = "Где"
    let webCommandWith = "Чем"
    let webCommandModel = "Модель"
    let webCommandFirst = "Первое сообщение"
    let webCommandGo = "Начать"
    let webCommandUnsure = "Не понятно, какой проект — выберите один ниже."
    let webCommandFailed = "Не удалось превратить это в черновик."
    let webCommandNoPlanner = "На этом Mac нет Claude Code, чтобы превратить это в черновик."
    let webCommandBusy = "Одна фраза уже превращается в черновик — попробуйте ещё раз через минуту."
    let webCommandEmpty = "Ничего не услышал"
    let webScheduleNew = "Новое расписание"
    let webScheduleEdit = "Изменить расписание"
    let webScheduleNewSay = "Ничего не запланировано, пока вы не нажмёте «Создать» внизу."
    let webScheduleTitle = "Название"
    let webScheduleAt = "Время"
    let webScheduleOn = "Дни"
    let webScheduleWhere = "Где"
    let webScheduleWith = "Чем"
    let webScheduleFirst = "Первое сообщение"
    let webScheduleMore = "Ещё"
    let webScheduleModel = "Модель"
    let webScheduleWhenDone = "Закрывать вкладку по завершении"
    let webScheduleCloseSuccess = "Если получилось"
    let webScheduleCloseAlways = "Всегда"
    let webScheduleCloseNever = "Оставлять открытой"
    let webScheduleEnabled = "Включено"
    let webScheduleDisabled = "Отключено"
    let webScheduleNotify = "Сообщать мне при сбое"
    let webScheduleCatchUp = "Если пропущено, наверстать в течение (часов)"
    let webScheduleTimeout = "Сдаться, если не уложится за (минут)"
    let webScheduleCreate = "Создать"
    let webScheduleCreated = "Расписание создано."
    let webScheduleDispatchOff = "Расписание создано и действительно, но отправка выключена — никто его не запустит. Включается на Mac, в Настройках → Удалённый доступ."
    let webScheduleFailed = "Не удалось создать расписание."
    let webScheduleSave = "Сохранить"
    let webScheduleSaved = "Расписание сохранено."
    let webScheduleDelete = "Удалить"
    let webScheduleDeleteAsk = "Удалить {title}? Это нельзя отменить."
    let webScheduleDeleted = "Расписание удалено."
    let webScheduleNeedsTime = "Время не расслышано — укажите его."
    let webScheduleNeedsPlace = "Не понятно, какой проект — выберите один."
    let webScheduleDaily = "Ежедневно"
    let webScheduleSun = "Вс"
    let webScheduleMon = "Пн"
    let webScheduleTue = "Вт"
    let webScheduleWed = "Ср"
    let webScheduleThu = "Чт"
    let webScheduleFri = "Пт"
    let webScheduleSat = "Сб"
    let webLinks = "Ссылки"
    let webLinksTip = "Где этот проект можно открыть"
    let webLinksPick = "Всё, у чего в этом проекте есть адрес."
    let webLinksEmpty = "В этом проекте нет ничего с адресом — ни сайта, ни деплоя, ни запущенных серверов."
    let webLinksFailed = "Не удалось прочитать ссылки этого проекта."
    let webLinksLocal = "Только в собственной сети Mac. Отсюда не откроется."
    let webLinksFile = "Файл на Mac. Открывается он там, а не в этом браузере."
    let webLinksCopy = "Скопировать путь"
    let webLinksCopied = "Скопировано."
    let webLinksCopyFailed = "Этот браузер не дал странице это скопировать."
    let webLinkOk = "в норме"
    let webLinkFail = "ошибка"
    let webLinkDown = "выключен"
    let webLinkRunning = "идёт"
    let webSessionInfo = "О сессии"
    let webInfoTitle = "Об этой сессии"
    let webInfoEditTitle = "Изменить название сессии"
    let webInfoCopyTitle = "Скопировать это имя"
    let webInfoTitleSaved = "Название сохранено."
    let webInfoTitleLocal = "Название сохранено в Clawdline; нижестоящее имя не изменено."
    let webInfoTitleQueued = "Название сохранено в Clawdline; обновление Codex в очереди."
    let webInfoTitleNotDurable = "Название применено, но этот Mac не смог записать его на диск; после перезапуска оно исчезнет."
    let webInfoTitleCloud = "Названия сессий меняются только на самом Mac, а не через облачное подключение."
    let webInfoSession = "Эта сессия"
    let webInfoAssistant = "Ассистент"
    let webInfoModel = "Модель"
    let webInfoSessionId = "ID сессии"
    let webInfoDirectory = "Каталог"
    let webInfoRunningFor = "Работает уже"
    let webInfoStatus = "Статус"
    let webInfoWorkStatusMeaning = "Это рабочий статус сессии. Одна галочка означает, что результат сдан и ждёт подтверждения; две — что он проверен и принят."
    let webInfoCloseabilityMeaning = "Ключ показывает, можно ли безопасно закрыть сессию. Это не зависит от статуса сдачи."
    let webInfoUsage = "Расход токенов"
    let webInfoInput = "Ввод"
    let webInfoOutput = "Вывод"
    let webInfoCacheRead = "Чтение из кэша"
    let webInfoCacheWrite = "Запись в кэш"
    let webInfoTotal = "Всего"
    let webInfoCost = "Примерная стоимость"
    let webInfoNoUsage = "Транскрипт этой сессии пока не найден."
    let webInfoLimits = "Лимиты тарифа"
    let webInfoLimitHit = "лимит исчерпан"
    let webInfoResets = "сброс {when}"
    let webInfoUnknown = "неизвестно"
    let webInfoFiles = "Файлы"
    let webInfoBranch = "Ветка"
    let webInfoStaged = "В индексе"
    let webInfoUnstaged = "Изменены"
    let webInfoUntracked = "Не отслеживаются"
    let webInfoConflict = "Конфликты"
    let webInfoClean = "Незакоммиченного нет."
    let webInfoNotRepo = "Это не git-репозиторий."
    let webInfoDeploy = "Последний деплой"
    let webInfoNoDeploy = "У этого проекта нет записей о деплое."
    let webInfoFailed = "Не удалось прочитать сведения об этой сессии."
    let webInfoBusy = "Mac сейчас занят чтением других сессий. Попробуйте через минуту."
    let webInfoRefresh = "Обновить"
    let webInfoTokens = "токенов"
    let webInfoSwitchModel = "Сменить модель"
    let webInfoModelOther = "другая модель…"
    let webInfoModelSent = "Отправлено /model {model}. Проверяем…"
    let webInfoModelBusy = "Смена ждёт, пока сессия не освободится."
    let webInfoSwitchPermission = "Сменить режим разрешений"
    let webInfoPermissionAuto = "Автоматический"
    let webInfoPermissionManual = "Ручной"
    let webInfoPermissionAcceptEdits = "Принимать изменения"
    let webInfoPermissionPlan = "Планирование"
    let webInfoPermissionUnreadable = "Не удалось прочитать текущий режим."
    let webInfoPermissionSent = "Включён режим «{mode}». Проверяем…"
    let webInfoPermissionBusy = "Режим разрешений переключается."
    let webInfoLimitsClaude = "Claude Code записывает окно только когда оно исчерпано; до тех пор ничего не известно."
    let webInfoCopied = "Id сессии скопирован."
    let webInfoAsOf = "на {when}"
    let webInfoWhyUnknown = "Почему неизвестно, и как получить цифры"
    let webSettingsOrder = "Расшифровка"
    let webSettingsOrderSay = "С какого конца начинать читать расшифровку. Это касается каждой сессии, а с клавиатуры то же самое делает `r`."
    let webAskLabel = "спросил"
    let webAskAny = "Сколько угодно из этих"
    let webWaitingTitle = "Эта сессия ждёт ответа"
    let webWaitingSay = "Claude Code показывает меню на Mac. Clawdline пока не умеет читать меню отсюда, так что варианты есть только на том экране."
    let webWaitingSend = "*Отправка отсюда не впечатает ваш ответ в меню* — она подтвердит тот пункт, который в меню сейчас подсвечен, а это редко тот, что вы имели в виду. На этот вопрос ответьте на Mac."
    let webMenuSay = "Нажмите на ответ — он уйдёт прямо в сессию."
    let webMenuHighlighted = "выделен"
    let webMenuSent = "Ответ отправлен."
    let webAgents = "Фоновые агенты"
    let webAgentsCount = "{n} работают"
    let webAgentDone = "готово"
    let webAgentFailed = "не удалось"
    let webShells = "Фоновые shell"
    let webShellTitle = "Фоновый shell"
    let webShellOpen = "Посмотреть, что печатает эта команда"
    let webShellRunning = "ещё работает"
    let webShellEnded = "завершена"
    let webShellQuiet = "Пока ничего не напечатано."
    let webShellFailed = "Не удалось прочитать вывод этой команды."
    let webShellClose = "Закрыть"
    let webShellStop = "Остановить"
    let webShellStopTitle = "Остановить эту команду?"
    let webShellStopSay = "{command} ещё работает. Ей будет предложено остановиться, а через пять секунд она будет убита, если этого не сделает. Уже сделанное не отменяется."
    let webShellStopped = "Запрошена остановка."
    let webShellStopFailed = "Не удалось остановить."
    let agentRunning = "работает"
    let agentTools = "инструментов: {n}"
    let agentEmpty = "Этот агент пока ничего не записал."
    let agentBack = "Сессия"
    let webAgentOpen = "Посмотреть, что сделал этот агент"
    let webTaskRoot = "Главная"
    let webTaskChild = "Дочерняя"
    let webTaskTasks = "Задачи"
    let webTaskDone = "готово"
    let webTaskFailed = "не удалось"
    let webTaskRunning = "работает"
    let webStale = "Clawdline на Mac пересобрали. Эта страница осталась от прежней сборки."
    let webStaleGo = "Перезагрузить"

    // The Projects page, and the worktrees under one Project that finished a Feature.
    let webProjects = "Проекты"
    let webProjectsLede = "Каталоги, в которых ассистент действительно запускался и которые ещё существуют."
    let webProjectsEmpty = "На этом Mac пока не записан ни один каталог проекта."
    let webProjectsUnavailable = "Это соединение не может читать проекты. Откройте собственный адрес приложения в сети этого Mac."
    let webProjectsLoading = "Читаем список проектов этого Mac…"
    let webProjectOpenLabel = "Открыть {name}"
    let webProjectReading = "Соединяем строки журнала этого проекта…"
    let webProjectDelivered = "Сделано, но не влито"
    let webProjectDeliveredSay = "Здесь Feature доведена до конца, и ни одна запись о слиянии не говорит, что работа дошла до ветки. Она сделана; её просто никто не влил."
    let webProjectDeliveredNone = "Здесь ничего не ждёт: у каждой завершённой Feature этого проекта есть запись о слиянии."
    let webProjectLanded = "Влито"
    let webProjectLandedSay = "Root записал, что поставка дошла до целевой ветки."
    let webProjectActive = "Ещё выполняется"
    let webProjectActiveSay = "Задача из этого worktree прямо сейчас жива в реестре."
    let webProjectAbandoned = "Брошено"
    let webProjectAbandonedSay = "Здесь ничего не завершилось успехом и ничего больше не выполняется."
    let webProjectUnknownOutcome = "Неизвестно"
    let webProjectUnknownSay = "Ни одна сохранённая строка не несла состояния задачи, поэтому догадок нет ни в одну сторону."
    let webProjectBranch = "Ветка, по соглашению"
    let webProjectRuns = "Работа агента"
    let webProjectSeen = "Наблюдалось"
    let webProjectNoWorktrees = "Ни один worktree этого проекта не завершил ни одной Feature."
    let webProjectExcluded = "Ещё {n} worktree этого проекта не завершили ни одной Feature — они посчитаны, но не перечислены."
    let webProjectUnattributed = "Worktree без проекта"
    let webProjectUnattributedSay = "{n} worktree не принадлежат ни одному проекту: они записаны до появления канонических ключей проекта, поэтому их собственный ключ — путь рабочей копии. Посчитаны здесь, а не отброшены молча."
    let webProjectRead = "Прочитано строк: {rows} · из них {project} по этому проекту · {worktree} в worktree · {feature} с Feature"
    let webProjectTruncated = "Частично: сканирование упёрлось в предел по строкам, поэтому всё выше — нижняя граница, а не итог."
    let webProjectNotFound = "В журнале ничто не соответствует этому проекту. Под ним ещё ничего не записано."
    let webProjectAmbiguous = "Это имя носит больше одного проекта, поэтому чтение отклонено, а не отвечено за один из них."
    let webProjectBusy = "Читатель журнала занят. На сессии это не влияет — попробуйте ещё раз чуть позже."
    let webProjectFailed = "Не удалось прочитать worktree этого проекта."

    let menuApplication = "Clawdline"
    let menuWindow = "Окно"
    let menuHelp = "Справка"
    let menuClose = "Закрыть окно"
    let menuHome = "Главная / Центр настройки"
    let menuHelpDocumentation = "Документация Clawdline"
    func menuAbout(_ app: String) -> String { "О программе \(app)" }
    let menuServices = "Службы"
    func menuHide(_ app: String) -> String { "Скрыть \(app)" }
    let menuHideOthers = "Скрыть остальные"
    let menuShowAll = "Показать все"
    let menuMinimize = "Свернуть"
    let homeTitle = "Главная Clawdline"
    let homeWelcome = "Выберите цель подключения. Настройка показывает реальные подтверждения, а не только изменённый переключатель."
    let homePurpose = "Что вы хотите подключить?"
    let homeLocalTitle = "Локальный браузер"
    let homeLocalSummary = "Читайте Clawdline в браузере на этом Mac. Управление остаётся выключенным до явного включения в Настройках."
    let homeCloudPreviewTitle = "Предпросмотр Clawdline Cloud"
    let homeCloudPreviewSummary = "Используйте размещённый предпросмотр после подтверждения живого соединения."
    let homeCloudflareTitle = "Мой URL Cloudflare"
    let homeCloudflareSummary = "Используйте свой хост Cloudflare после подтверждения публичного HTTPS-пути."
    let homeUnavailable = "В этой сборке ещё не готово; успешное соединение не заявляется."
    let setupDetected = "Обнаруженное состояние"
    let setupNextAction = "Следующий шаг"
    let setupExpected = "Ожидаемый результат"
    let setupRecovery = "Восстановление"
    let setupLocalServerOff = "Сервер обратной петли выключен."
    let setupLocalChecking = "Проверяется настоящий endpoint /v1/health…"
    let setupLocalConfigurationFailed = "Не удалось сохранить настройку локального браузера; ничего не изменено."
    let setupLocalHealthTransport = "Endpoint здоровья недоступен. Проверьте порт и другие программы."
    let setupLocalHealthTimedOut = "Истекло время ожидания endpoint здоровья. Проверьте порт и повторите."
    func setupLocalHealthHTTP(_ status: Int) -> String { "Endpoint здоровья вернул HTTP \(status), а не исправный ответ." }
    let setupLocalHealthUnhealthy = "Endpoint ответил, но сообщил ok: false."
    let setupLocalHealthInvalid = "Endpoint не вернул допустимый ответ здоровья. Проверьте занятость порта."
    let setupLocalReady = "Endpoint состояния готов. Учётных данных браузера ещё нет."
    let setupLocalWaiting = "Браузер открыт; ожидается аутентификация именно этого устройства."
    let setupLocalConnected = "Подключено. Это устройство браузера связалось с Clawdline."
    let setupLocalEnable = "Включить локальный браузер"
    let setupLocalRetry = "Проверить снова"
    let setupLocalOpen = "Открыть браузер только для чтения"
    let setupLocalOpenAgain = "Открыть браузер снова"
    let setupFinish = "Готово"
    let setupLocalExpected = "Браузер только для чтения открывается и проходит проверку даже без активных сеансов."
    let setupLocalRecovery = "Если процесс остановился, оставьте окно открытым и проверьте снова. Сервер и порт указаны в Настройках."
    let setupNoRecovery = "Восстановление не требуется; этот маршрут доказан."
    let setupLocalReadOnlyAction = "Это действие сохраняет доступ только для чтения и оставляет управление выключенным."
    let setupReadOnly = "Только чтение · управление выключено"
    let setupLocalDeviceName = "Браузер центра настройки"
    func setupTunnelFacts(_ mode: String, _ tunnel: String, _ hostname: String, _ status: String) -> String { "Режим: \(mode)\nТуннель: \(tunnel)\nХост QR: \(hostname)\nСостояние: \(status)" }
    let setupTunnelModeOff = "Выключен"
    let setupTunnelModeQuick = "Быстрый"
    let setupTunnelModeNamed = "Именованный"
    let setupTunnelQuickName = "Быстрый туннель Cloudflare"
    let setupNone = "Нет"
    let setupControlChosen = "Чтение + управление · явно включено в Настройках"
    let setupTunnelMissing = "cloudflared не установлен."
    let setupTunnelOff = "Туннель выключен; QR для телефона недоступен."
    let setupTunnelStarting = "cloudflared запускается; QR пока недоступен."
    func setupTunnelReady(_ url: String) -> String { "Доступен по \(url). Учётных данных телефона ещё нет." }
    func setupTunnelWaiting(_ url: String) -> String { "QR ведёт на \(url). Ожидание именно этого телефона." }
    func setupTunnelConnected(_ url: String) -> String { "Подключено через \(url). Этот телефон сообщил lastSeen." }
    let setupTunnelExpected = "В QR попадает только URL работающего туннеля; настройку завершает лишь lastSeen нелокального устройства, созданного этим QR."
    let setupTunnelRecovery = "Откройте удалённые настройки. Установите cloudflared, если его нет; иначе следуйте указанной причине, держите туннель включённым и сканируйте снова."
    let setupOpenRemoteSettings = "Открыть удалённые настройки"
    let setupCheckTunnel = "Проверить туннель снова"
    let setupShowPhoneQR = "Показать QR телефона"
    let setupShowPhoneQRAgain = "Показать QR снова"
    let setupCloudRelayUnauthorized = "Relay отклонил учётные данные этой машины."
    func setupCloudFacts(_ account: String, _ credential: String, _ relay: String, _ pairing: String, _ receipt: String) -> String { "Аккаунт: \(account)\nУчётные данные машины: \(credential)\nRelay готов: \(relay)\nE2EE-сопряжение: \(pairing)\nПолучение Viewer: \(receipt)" }
    let setupCloudExpected = "Preview завершается, только когда аккаунт, учётные данные, Relay, E2EE-сопряжение и получение этим Viewer доказаны отдельно."
    let setupCloudRecovery = "Войдите или выполните сопряжение в настройках Cloud. Relay и получение остаются доказательствами Preview; повтор не создаёт отсутствующее доказательство."
    let setupOpenCloudSettings = "Открыть настройки Cloud"
    let setupPairCloudPhone = "Сопрячь телефон в Cloud"
    let setupReviewCloudPreview = "Проверить состояние Preview"
    let setupProofAbsent = "отсутствует"
    let setupProofReading = "чтение доказательства…"
    let setupProofUnavailable = "доказательство недоступно"
    func setupProofFailed(_ reason: String) -> String { "ошибка — \(reason)" }
    let setupCloudIdentityReadFailed = "не удалось прочитать идентификатор из Связки ключей"
    let setupCloudRelayFailed = "Relay сообщил об ошибке; проверьте настройки Cloud и журнал"
    let setupCloudPairingReadFailed = "не удалось прочитать хранилище сопряжённых устройств"
    let setupCloudPairingAmbiguous = "появилось несколько новых Viewer; начните сопряжение заново"
    func setupCloudAccountProved(_ account: String) -> String { "выполнен вход как \(account)" }
    func setupCloudCredentialProved(_ machine: String) -> String { "данные Связки ключей для \(machine)" }
    func setupCloudPairingProved(_ device: String) -> String { "закреплён точный Viewer \(device)" }
    let setupCloudflareDeviceName = "Телефон через Cloudflare"
    let setupScanLiveTunnel = "Сканируйте работающий туннель телефоном"
    let setupDismissalHint = "После закрытия Home не открывается автоматически. Откройте центр настройки через меню, Dock, значок состояния или clawdline://home."
    let setupCompletionFailed = "Не удалось сохранить завершение. Проверьте права ~/.config/clawdline и снова закройте Home."

    let menuOpen = "Открыть строку ввода"
    let menuReveal = "Перейти к нужной вкладке"
    let menuMascot = "Маскот"
    let menuLogin = "Запускать при входе"
    let menuEditConfig = "Настройки…"
    let menuReload = "Перечитать настройки"
    let menuQuit = "Выйти из Clawdline"
    let menuNoTarget = "(пока не найдено)"

    func updateAvailable(latest: String, installed: String) -> String {
        "Вышла Clawdline \(latest) — здесь \(installed)"
    }
    func compatNote(_ standing: Compat.Standing) -> String {
        switch standing {
        case .behind(let program, let installed, let builtAgainst):
            return "\(program) \(installed); эта сборка проверялась с \(builtAgainst)"
        case .ahead(let program, let installed, let builtAgainst, let release):
            return "\(program) \(installed); эта сборка проверялась с \(builtAgainst) — вышла Clawdline \(release)"
        }
    }

    func hotkeyFailedTitle(_ combo: String) -> String { "Не удалось зарегистрировать \(combo)" }
    func hotkeyFailedBody(_ configPath: String) -> String {
        """
        Скорее всего, это сочетание уже занято другим приложением — Spotlight, \
        переключатель раскладки, BetterTouchTool и тому подобное.

        Выберите другое: измените "hotkey" в \(configPath), затем выберите \
        «Перечитать настройки» в строке меню.

        До тех пор строку ввода по-прежнему открывает ✳ в строке меню.
        """
    }
    let loginFailed = "Не удалось настроить запуск при входе"
}
