import Foundation

struct Turkish: Copy {
    let placeholder = "Claude Code'a yaz…"

    let hintSend = "gönder"
    let hintNewline = "yeni satır"
    let hintSwitch = "değiştir"
    let hintList = "liste"
    let hintMascot = "maskot"
    let hintOutput = "çıktı"
    let hintFullscreen = "tam ekran"
    let hintKeys = "tuşlar"
    let hintTextSize = "yazı boyutu"
    let hintOrder = "ters sıra"
    let hintVoice = "dikte"
    func voiceListening(onDevice: Bool) -> String {
        onDevice ? "Bu Mac'te dinliyor — durdurmak için tekrar bas"
                 : "Dinliyor — bu dili Apple yazıya döküyor, bu Mac değil"
    }
    let voiceNoPermission = "Dikte için mikrofon ve konuşma tanıma izni gerekiyor"
    let voiceUnavailable = "Dikte şu anda kullanılamıyor"
    func voiceTranscribing(seconds: Double) -> String {
        String(format: "Whisper yeniden okuyor… %.1f sn", seconds)
    }
    let whisperMissing = "Whisper kurulu değil — docs/whisper.md'ye bak"
    let whisperNothingHeard = "Hiçbir şey duyulmadı"
    func dictationStatus(_ status: Whisper.Status) -> String {
        switch status {
        case .ready(let model): return "Dikte: önce Apple, sonra Whisper (\(model))"
        case .noBinary: return "Dikte: yalnızca Apple — whisper-cli yok"
        case .noModel: return "Dikte: yalnızca Apple — whisper-cli var, model yok"
        }
    }
    func voiceListeningWhisper() -> String {
        "Dinliyor — sen durunca Whisper bir kez daha bakıyor"
    }

    let scanning = "Aranıyor…"
    let noSession = "Claude Code oturumu bulunamadı"
    let nothingToSend = "Gönderilecek yer yok — önce bir terminalde Claude Code başlat"
    let sendFailed = "Gönderilemedi"
    let itermSilent = "iTerm2 yanıt vermedi"
    let itermBusy = "iTerm2 bir iletişim kutusunun yanıtlanmasını bekliyor — Mac'te yanıtlayın"
    let scriptMissing = "iterm.js yok — uygulama paketi bozuk mu?"
    let cannotList = "iTerm2 oturumları okunamadı"
    let noOutput = "Bu oturumda okunacak bir şey henüz yok."
    let imageExpired = "Görselin süresi doldu"
    let imagePreview = "Görsel önizlemesi"
    let imageClose = "Önizlemeyi kapat"
    let imageTooLarge = "Gönderilemeyecek kadar büyük ({mb} MB)"
    let imageUnavailable = "Görsel ulaşmadı"
    func outputSize(_ pt: Int) -> String { "Çıktı yazı boyutu \(pt) pt — görmek için ⌘J" }
    func foldedTools(_ count: Int) -> String { "\(count) adım" }
    func outputOrder(newestFirst: Bool) -> String {
        newestFirst ? "En yeni üstte" : "En eski üstte"
    }
    func backlogNow(_ count: Int) -> String { "şimdi \(count)" }
    func dropped(_ count: Int) -> String {
        count == 1 ? "Yol eklendi — Claude Code onu okur" : "\(count) yol eklendi"
    }
    func stackConfirm(_ command: String) -> String { "Çalıştırmak için tekrar basın:  \(command)" }
    let hintStacks = "sunucular"
    func stackTip(up: Int, total: Int) -> String { "\(total) sunucudan \(up) tanesi çalışıyor — liste için ⌘S" }
    let stackTipUnknown = "Bu projenin sunucuları var ama durum komutu henüz güvenilir değil — ⌘S"
    let stackUntrusted = "onaylanmadı"
    let stackExit = "çıkış"
    let stackActionStart = "başlat"
    let stackActionRestart = "yeniden başlat"
    let stackActionStop = "durdur"
    let stackActionLogs = "günlük"
    let stackLogAll = "tümü"
    let stackLogBack = "döküm"
    let stackActionAllow = "izin ver"
    let stackActionAgain = "tekrar bas"
    func sessionTip(index: Int, total: Int) -> String { "\(total) oturumdan \(index). — değiştirmek için ⌘K" }
    let sessionWaiting = "yanıtını bekliyor"
    let sessionAgents = "arka planda {n}"
    let sessionShellOne = "1 shell çalışıyor"
    let sessionShellMany = "{n} shell çalışıyor"
    let sessionWaitedOnByOne = "1 seni bekliyor"
    let sessionWaitedOnByMany = "{n} seni bekliyor"
    let islandDone = "bitti"
    let islandAllSessions = "Tüm oturumlar…"
    func statusWaiting(_ labels: [String]) -> String {
        labels.count == 1 ? "\(labels[0]) yanıtını bekliyor"
                          : "\(labels.count) oturum yanıtını bekliyor"
    }
    func statusWorking(_ count: Int) -> String { "\(count) çalışıyor" }

    let settingsTitle = "Clawdline Ayarları"
    let settingsGeneral = "Genel"
    let settingsBar = "Çubuk"
    let settingsReading = "Okuma"
    let settingsVoice = "Dikte"
    let settingsHotkey = "Kısayol"
    let settingsRecording = "Tuşlara bas…"
    let settingsScope = "Şurada çalışır"
    let settingsScopeGlobal = "Her uygulamada"
    let settingsScopeHint = "Boşsa her yerde çalışır; yani sonuncuyu çıkarmak yukarıdaki anahtarı açar — onu tekrar kapatmak da listeyi geri getirir. Yapılandırma dosyası bunları bundle kimliği olarak tutar, elle düzenlenmiş bir liste de aynı şekilde çalışır."
    let settingsSessionTerminal = "Yeni oturumlar şurada açılır"
    let settingsSessionTerminalHint = "Kısayolun nerede çalıştığıyla aynı şey değil. Otomatik, iTerm2 açıksa onu, değilse tmux'u kullanır; iTerm2 doğrudan iTerm2'yi ister, bu yüzden yanında çalışan bir tmux sunucusu yanıt sayılmaz ve iTerm2 kapalıysa reddedilir; tmux ise iTerm2 açık olsa bile oturumu bir tmux sunucusuna koyar. Bir sonraki oturumdan itibaren geçerlidir, yeniden başlatmak gerekmez."
    let settingsScopeAdd = "Uygulama ekle…"
    let settingsScopeChoose = "Uygulama seç…"
    let settingsScopeRunning = "Şu anda açık olanlar"
    let settingsScopeRemove = "Çıkar"
    let settingsLanguage = "Dil"
    let settingsReopen = "Çubuk terminalle birlikte gelir ve gider"
    let settingsReopenHint = "Terminalden başka bir yere geçince çubuk kalkar, terminale dönünce geri gelir. Bittiğini söyleyen şey Esc'tir."
    let settingsFollow = "Terminal, çubuğun nişan aldığı şeyi gösterir"
    let settingsFollowHint = "O oturumun sekmesini seçer. Terminali öne getirmez — getirseydi, her Tab'a basışta klavye yazmakta olduğun kutudan çıkardı."
    let settingsCodexAutoName = "Yeni oturumları adlandır"
    let settingsCodexAutoNameHint = "Adsız her oturum için seçtiğin asistanla küçük bir tur çalıştırır. İlk isteği kullanır, o asistanın kullanımından harcar ve senin seçtiğin adı değiştirmez."
    let settingsNotch = "Çentikte yaşa"
    let settingsNotchHint = "Kamera yuvasında bir karakter. Kapalı gerçekten kapalı: hiçbir şey çizilmez, pencere açılmaz."
    let settingsPosition = "Ekrandaki yükseklik"
    let settingsWidth = "Genişlik"
    let settingsOpacity = "Kart opaklığı"
    let settingsShow = "Göster"
    let settingsPaneHeight = "Panel yüksekliği"
    let settingsTextSize = "Yazı boyutu"
    let settingsPaneFont = "Panel yazı tipi"
    let settingsBlur = "Arkadaki bulanıklık"
    let settingsNewestFirst = "Önce en yeni"
    let settingsEngine = "Tanıyıcı"
    let settingsSettle = "Bir duraklama cümleyi bitirir"
    let settingsStop = "Bir sessizlik oturumu bitirir"
    let settingsAuto = "Otomatik"
    let settingsTranscript = "Döküm"
    let settingsTerminal = "Terminal"
    let settingsOff = "Kapalı"
    let settingsHooks = "Claude Code kancaları"
    let settingsHooksHint = "Kurulduğunda Claude Code bir turun başladığı, bittiği ya da yanıt beklediği anı kendisi haber verir; Clawdline'ın bir sonraki bakışını beklemez. Okuma yine ekrandan yapılır, burada belirlenen yalnızca ne kadar çabuk olduğu."
    let settingsHooksInstall = "Kur"
    let settingsHooksRemove = "Kaldır"
    let settingsHooksOff = "Kurulu değil — durum yalnızca ekrandan okunuyor"
    let settingsHooksOn = "Kurulu — henüz hiçbir oturum haber vermedi"
    let settingsHooksLive = "Kurulu, oturumlar haber veriyor"
    let settingsStateHook = "Bir oturum durum değiştirdiğinde"
    let settingsStateHookHint = "Bir oturum çalışmaya başladığında, bitirdiğinde ya da sana bir şey sorduğunda Clawdline şunu çalıştırır: kendi programını, ayrıntılar da ortam değişkenlerinde. Burada değil de yapılandırma dosyasında yazılır, çünkü bu bir komut satırı değil bir argv'dir — içinde boşluk olan bir yol tek bir yol olarak kalmak zorundadır."
    let settingsRemote = "Uzaktan erişim"
    let settingsRemoteServe = "Bir tarayıcı ya da telefonun oturumlarını görebilsin"
    let settingsRemoteHint = "Kapalıyken bu Mac'in dışından hiçbir şey hiçbir yere erişemez. Açıkken oturum listesi 127.0.0.1 üzerinden sunulur — buradaki bir tarayıcıya, tünelin ucundaki bir telefona, bir betiğe. Karşı tarafa giden şey depo adları, branch'ler ve görev başlıklarıdır; kapalı kalmasının sebebi de bu, sen aksini söyleyene kadar."
    let settingsRemoteDevices = "Eşleşen cihazlar"
    let settingsRemoteNoDevices = "Henüz yok — bu Mac'in dışından hiçbir şey okunamıyor"
    let settingsRemoteRevokeAll = "Bağlantıları kes"
    let settingsRemoteOpen = "Tarayıcıda aç"
    let pairingIgnore = "Yoksay"
    func pairingAsks(_ device: String) -> String { "\(device) bu Mac ile eşleşmek istiyor" }
    func pairingCode(_ code: String) -> String {
        """
        Bu kodu o cihaza yaz:

        \(code)

        İki dakika geçerli. Az önce bunu sen istemediysen boş ver — isteyen kişi bu kod \
        olmadan işi bitiremez.
        """
    }
    let settingsTunnel = "Bu Mac'e her yerden ulaş"
    let settingsTunnelQuick = "Üretilen bir adres"
    let settingsTunnelNamed = "Kendi alan adım"
    let settingsTunnelHostname = "Host adı"
    let settingsTunnelHint = "cloudflared üzerinden bu Mac'ten dışarı doğru bir bağlantı açar — port yönlendirme yok, ağında dinleyen hiçbir şey yok. Bir cihaz eşleşene kadar başlamaz, çünkü tünelin arkasında bu Mac'teki her depo adı ve her görev başlığı var."
    let settingsRemoteWrite = "Eşleşmiş bir cihaz bir oturuma yazabilsin"
    let settingsRemoteWriteHint = "Kapalıyken eşleşmiş bir cihaz yalnızca okuyabilir. Açıkken bir oturuma metin gönderebilir ve yeni oturumlar başlatabilir — bu da bu Mac'te kod çalıştırmak demektir, çünkü Claude Code'un yaptığı şey tam olarak budur. Yukarıdakinden başka bir karar, o yüzden ayrı bir anahtar."
    let settingsRemotePhone = "Telefon eşleştir…"
    let settingsRemotePhoneHint = "Taranacak bir kod gösterir. Kodun kendine ait bir anahtarı vardır: fotoğrafı çekilirse ortaya çıkan, bu listede görüp istediğin an kaldırabileceğin bir cihazdır — bu Mac'in kendi anahtarı değil."
    let pairingScanTitle = "Bunu telefonla tara"
    let pushWaiting = "bir yanıt bekliyor"
    let pushTest = "Bu bir deneme bildirimi. Her şey bağlı."
    let pushDelivered = "teslim etti, seni bekliyor"
    let pushDeployOk = "deploy başarıyla bitti"
    let pushDeployFail = "deploy hata verdi"
    func pushChildWaiting(minutes: Int?) -> String {
        guard let minutes else { return "alt oturumu yanıt bekliyor" }
        return "alt oturumu yanıt bekliyor — \(minutes) dk kaldı"
    }
    func pushBatchDone(done: Int, failed: Int) -> String {
        let all = "\(done) görevi bitirdi"
        return failed == 0 ? all : "\(all), \(failed) başarısız"
    }
    let settingsPushDelivery = "Bir oturum teslim ettiğini bildirince haber ver"
    let settingsPushDeliveryHint = "Bildirim başına bir kez; aynısı yinelenirse ses çıkmaz."
    let settingsPushFanout = "Toplu gönderilen işler bitince haber ver"
    let settingsPushFanoutHint = "Tüm küme için tek bildirim, kaçının başarısız olduğuyla."
    let settingsSmartNotifications = "Akıllı bildirimler"
    let settingsSmartNotificationsHint = "Haiku biten işi tek cümlede anlatır. Başarısız olursa normal bildirim gönderilir."
    func pushCoalesced(count: Int) -> String { "\(count) iş birlikte bitti" }
    let settingsSmartHealthIdle = "Henüz akıllı bildirim denenmedi."
    func settingsSmartHealth(attempts: Int, successes: Int) -> String {
        "\(attempts) denemeden \(successes) tanesi model cümlesi iletti."
    }
    func settingsSmartHealthFailure(reason: String, time: String) -> String {
        "Son geri dönüş \(time): \(reason)."
    }
    func settingsSmartTimeout(seconds: Int) -> String {
        "Claude \(seconds) saniyelik süreyi aştı ve durduruldu"
    }
    let settingsSmartQueueFull = "kuyruğun alacağından fazla iş bitti"
    let settingsSmartModelFailed = "Claude kullanılabilir bir şey döndürmedi"
    let settingsSmartNoSource = "özetlenecek bir şey yoktu"
    let settingsSmartMissing = "claude çalıştırılabilir dosyası bulunamadı"
    let settingsPushDeploy = "Deploy bitince haber ver"
    let settingsPushDeployHint = "Başarı da hata da."
    let settingsAgentNotify = "Ajanların kendi bildirimlerini göndermesine izin ver"
    let settingsAgentNotifyNote = "Yalnızca bir ajanın kendiliğinden gönderdiği içeriği denetler; bitiş, deploy ve diğer bildirimler değişmez."
    let settingsOrchestrator = "İşi başka oturuma verme"
    let settingsOrchestratorEnabled = "Bir oturum işi başka bir oturuma verebilsin"
    let settingsOrchestratorEnabledHint = "clawdline becerisi olan bir oturum yeni bir sekme açıp yönergeleri yazabilir ve iş bitince haber alır. Kapalıyken her istek geri çevrilir; hâlihazırda çalışan hiçbir şey durdurulmaz."
    let settingsOrchestratorMax = "Aynı anda alt oturum"
    let settingsOrchestratorMaxHint = "Varsayılan beş; Mac başına değil, oturum başına sayılır. Her biri, içinde bir asistanın çalıştığı bir terminal sekmesi."
    let settingsOrchestratorPermission = "Alt oturum kendi başına nereye kadar"
    let settingsOrchestratorPermissionHint = "Bir alt oturumun sekmesine kimse bakmıyor; onay için duran bir oturum süresi dolana kadar durur — ve görevlendirilen bir oturumun işi baştan sona komut çalıştırmak ve dosya yazmaktır, dolayısıyla son basamağın altındaki her şey onu bir yerde durdurur. Bir görev bundan azını isteyebilir, fazlasını asla."
    let settingsOrchestratorPermissionAsk = "Her adımdan önce sor"
    let settingsOrchestratorPermissionEdits = "Dosya yazarken sorma"
    let settingsOrchestratorPermissionFull = "Hiç sorma"
    let settingsOrchestratorNotify = "İsteyen oturuma haber ver"
    let settingsOrchestratorNotifyHint = "İş bittiğinde o oturuma tek satır yazılır."
    let settingsOrchestratorClose = "Alt oturum haber verince"
    let settingsOrchestratorCloseHint = "Haber verdikten sonra sekmesi kapatılır; süresi dolanınki okuyabilesin diye açık kalır."
    let settingsOrchestratorCloseNow = "Sekmeyi hemen kapat"
    let settingsOrchestratorCloseLinger = "Üç dakika sonra kapat"
    let settingsOrchestratorCloseKeep = "Açık bırak"
    let settingsOrchestratorPolicy = "İş nasıl dağıtılır"
    let settingsOrchestratorPolicyHint = "Clawdline her görev verişte okuduğu ve kendisi de görev verebilen her alt oturumun yönergesine kopyaladığı kurallar: hangi asistan, hangi model, grafiğin nasıl bir şekli olmalı. Boşsa kural yok."
    let settingsOrchestratorPolicyEdit = "Kuralları düzenle"
    func settingsOrchestratorPolicyOn(_ lines: Int) -> String { return "Yürürlükte — \(lines) satır" }
    let settingsOrchestratorPolicyOff = "Kural yok — her seferinde veren kendisi karar verir"
    let settingsSchedules = "Zamanlamalar"
    let settingsSchedulesEmpty = "Henüz zamanlama yok. Aşağıdaki Yeni zamanlama ilkini oluşturur."
    let settingsScheduleNew = "Yeni zamanlama"
    let settingsScheduleEdit = "Düzenle"
    let settingsScheduleSave = "Kaydet"
    let settingsScheduleDelete = "Sil"
    let settingsScheduleRun = "Şimdi çalıştır"
    let settingsScheduleReveal = "Finder’da göster"
    let settingsSchedulesFolder = "schedules klasörünü aç"
    let settingsScheduleNext = "Sonraki"
    let settingsScheduleLast = "Son"
    let settingsScheduleNever = "Henüz çalışmadı"
    let settingsScheduleStarted = "Çalıştırma başladı."
    let settingsScheduleActive = "Bu zamanlamanın önceki görevi hâlâ çalışıyor."
    let webScheduleMissed = "Son kaçırılan"
    let webScheduleNoNext = "Sonraki çalıştırma zamanlanmadı."
    func childAnnounce(_ title: String) -> String { "Clawdline'dan gelen görev alındı: \(title) — şimdi başlıyorum." }
    func settingsSeconds(_ value: Double) -> String { String(format: "%.1f sn", value) }

    let webConnLive = "canlı"
    let webConnConnecting = "bağlanıyor"
    let webConnRetrying = "{n} sn sonra tekrar"
    let webConnOffline = "bağlantı yok"
    let webConnLocked = "eşleşme yok"
    let webConnTipLive = "Uygulamadan canlı akıyor"
    let webConnTipLocked = "Bu tarayıcı Mac ile eşleşmedi"
    let webConnTipDown = "Bağlantı yok — şimdi denemek için tıkla"

    let webCountWorking = "{n} çalışıyor"
    let webCountWaiting = "{n} bekliyor"
    let webCountUnreadable = "{n} okunamadı"
    let webCountQuietOne = "{n} oturum, hepsi sakin"
    let webCountQuietMany = "{n} oturum, hepsi sakin"
    let webCountNone = "oturum yok"

    let webFilterPlaceholder = "Göreve, projeye ya da tty'ye göre süz"
    let webFilterLabel = "Oturumları süz"
    let webListLabel = "Claude Code oturumları"
    let webPull = "Yenilemek için çek"
    let webPullRelease = "Yenilemek için bırak"
    let webPullBusy = "Yenileniyor…"
    let webEmptyFilterTitle = "“{q}” ile eşleşen yok"
    let webEmptyFilterHint = "Esc süzgeci temizler"
    let webEmptyLockedTitle = "Bu cihaz eşleşmiş değil"
    let webEmptyLockedHint = "Uygulama 401 döndü — Mac'teki Clawdline'dan eşleştir"
    let webEmptyNoneHint = "Bir terminalde başlat, burada beliriverir"
    let webEmptyWaitTitle = "Uygulama bekleniyor"
    let webEmptyWaitHint = "Akıştan henüz bir şey gelmedi"
    let webStateUnreadable = "ekran okunamadı"
    let webStateWorking = "çalışıyor"
    let sessionWorkReady = "yeni iş alabilir"
    let sessionWorkUnknown = "durum bilinmiyor"
    let sessionWorkHolding = "kendi kendine ilerliyor"
    let sessionWorkOwed = "bir karar borcu var"
    let sessionWorkSelfStated = "kendi beyanı"
    let sessionWorkMilestone = "Kilometre taşı teslim edildi; inceleme veya birleştirme kalabilir"
    let sessionWorkComplete = "Aracı tarafından doğrulanan hedef dal birleştirmesi"
    let closeabilitySafe = "Güvenle kapatılabilir"
    let closeabilityBlocked = "{n} yükümlülük duruyor"
    let closeabilityBlockedOne = "1 yükümlülük duruyor"
    let closeabilityBlockedMany = "{n} yükümlülük duruyor"
    let closeabilityNeedsAttestation = "Oturumun kendi beyanı bekleniyor"
    let closeabilityUnknown = "Kapatılabilirlik bilinmiyor"
    let closeabilityWhy = "Kapatılamaz, çünkü"
    let closeabilityMoverSelf = "bunu bu oturum ilerletir"
    let closeabilityMoverPerson = "bunu siz ilerletirsiniz"
    let closeabilityMoverSession = "bunu başka bir oturum ilerletir"
    let closeabilityMoverBroker = "bunu taze bir okuma ilerletir"
    let closeabilityNotProven = "Aracı, bu oturumun güvenle kapatılabileceğini kanıtlayamadı."
    let closeabilityAttestationExplanation = "Bu, tamamlanmamış bir iş bulunduğu anlamına gelmez. Clawdline’ın denetleyebildiği noktalar temizdir; ancak bu oturum yerel değişiklik, teslim edilmemiş iş veya Clawdline dışındaki bir iş bırakıp bırakmadığını henüz doğrulamadı. Kapatmadan önce oturumu gözden geçirin."
    let closeabilityTechnicalDetails = "Teknik ayrıntılar"

    let webBack = "Oturumlar"
    let webBackLabel = "Oturum listesine dön"
    let webMenu = "Menü"
    let webPages = "Sayfalar"
    let webSessions = "Oturumlar"
    let webUsage = "Kullanım"
    let webNoSessionOpen = "Açık oturum yok"
    let webOrderTip = "Dökümü ters çevir (r)"
    let webShowOnMac = "Mac'te göster"
    let webShowOnMacTip = "Bu oturumun terminalini Mac'te öne getirir"
    let webShowOnMacOff = "Sunucu write: false diyor — henüz hiçbir şey gönderilemez"
    let webShowOnMacAsked = "Mac'ten öne getirmesi istendi"
    let webSessionActions = "Oturum işlemleri"
    let webSessionGit = "Git değişiklikleri"
    let webScreenTitle = "Ekran"
    let webScreenLive = "canlı"
    let webScreenOnDemand = "istek üzerine"
    let webScreenGone = "Bu ekran okunamadı"
    let webGitTitle = "Git değişiklikleri"
    let webGitClean = "Çalışma ağacı temiz"
    let webGitNotRepo = "Git deposu değil"
    let webGitFailed = "Git değişiklikleri okunamadı"
    let webGitRefresh = "Yenile"
    let webGitClose = "Kapat"
    let webGitStaged = "Hazırlanmış"
    let webGitUnstaged = "Hazırlanmamış"
    let webGitUntracked = "İzlenmeyen"
    let webGitConflict = "Çakışma"
    let webEndSession = "Oturumu kapat"
    let webConfirmActionTitle = "{action} çalıştırılsın mı?"
    let webConfirmActionSay = "Bu, geçerli oturuma {action} gönderir."
    let webConfirmEndTitle = "Bu oturum kapatılsın mı?"
    let webConfirmEndSay = "Asistan çıkacak, ardından terminal sekmesi kapanacak."
    let webConfirmEndLoses = "Kapatmak şunları da sonlandırır:"
    let webClawdfatherCreateLabel = "Yeni oturuma Clawdfather adını ver"
    let webClawdfatherIs = "Bu oturum {name}"
    let webClawdfatherRegisterAsk = "Bu yeni oturumu bu Mac’in Clawdfather’ı, yani makine koordinatörü olarak kaydet. Terminalden bağımsız oturum kimliğin {id}. Koordinatör kaydını ~/.config/clawdline/orchestrator-token içindeki orchestrator token ile oku. Yalnızca hiç koordinatör kayıtlı değilse, docs/orchestrator.md içindeki “Becoming Clawdfather” bölümünün kayıt kısmını izle. Kayıtlı bir koordinatör varsa, çevrimdışı olsa bile onun yerine geçme. Sonra ne olduğunu anlat."
    let webClawdfatherRegisterSent = "Yeni oturumdan Clawdfather olması istendi"
    let webClawdfatherRegisterLate = "Yeni oturum, Clawdfather adı verilecek kadar zamanında hazır olmadı."
    let webClawdfatherRegisterBlocked = "Bu Mac’in koordinatör kaydı okunamıyor, bu yüzden olduğu gibi bırakıldı."
    let webCoordSectionObserve = "Gözlem"
    let webCoordSectionCoordinate = "Eşgüdüm"
    let webCoordSectionPresence = "Varlık"
    let webCoordSectionAdmin = "Yönetim"
    let webCoordCmdStatusReport = "Durum raporu"
    let webCoordCmdStatusReportSay = "Clawdfather'ın güncel durumunu ve süren yükümlülüklerini oku."
    let webCoordCmdSinceAway = "Sen yokken"
    let webCoordCmdSinceAwaySay = "Son dönüş noktandan bu yana kaydedilen değişiklikleri ve kararları oku."
    let webCoordCmdDuplicates = "Tekrarlar, çatışmalar ve sahiplik"
    let webCoordCmdDuplicatesSay = "Tekrarlanan işi, çatışan sahiplenmeleri ve güncel sahipliği incele."
    let webCoordCmdLandingClosure = "Teslimatların kapanışı"
    let webCoordCmdLandingClosureSay = "İncelenmiş ama hâlâ kökün birleştirmesini bekleyen teslimatları oku."
    let webCoordCmdCoordinateWork = "İşi eşgüdümle"
    let webCoordCmdCoordinateWorkSay = "Zaten süren işler için eşgüdüm adımları tasla."
    let webCoordCmdDispatch = "Bağımsız iş dağıt"
    let webCoordCmdDispatchSay = "Bağımsız bir çocuk oturumu başlatacak bir dağıtımı önizle."
    let webCoordCmdAsk = "Clawdfather'a sor"
    let webCoordCmdAskSay = "Clawdfather'ın yargısına sunulacak bir soru tasla."
    let webCoordCmdQuietWatch = "Sessiz gözcülük"
    let webCoordCmdQuietWatchSay = "Bekleme uyarısı doğurmayan sessiz bir izleme isteği tasla."
    let webCoordCmdScope = "Kapsam ve izinler"
    let webCoordCmdScopeSay = "Clawdfather'ın güncel kapsamını ve verilen izinleri oku."
    let webCoordCmdStop = "Clawdfather'ı durdur"
    let webCoordCmdStopSay = "Clawdfather'ı durdurmayı önizle."
    let webCoordCmdReconnect = "Clawdfather'ı yeniden bağla"
    let webCoordCmdReconnectSay = "Clawdfather'ı yeniden bağlamayı önizle."
    let webCoordCmdDeepAudit = "Derin durum denetimi"
    let webCoordCmdDeepAuditSay = "Clawdfather’dan ilgili Session’lardaki işleri, teslimleri ve kararları denetlemesini iste."
    let webCoordTokenExpected = "Beklenen Token eforu: {effort}"
    let webCoordTokenLow = "Düşük"
    let webCoordTokenMedium = "Orta"
    let webCoordTokenHigh = "Yüksek"
    let webCoordTokenUnknown = "Bilinmiyor"
    let webCoordAuditPreview = "Yüksek Token kullanan, çok Session’lı bir istek. Henüz hiçbir şey gönderilmedi. Tam denetim talimatını tam olarak bu Clawdfather Session’ına göndermek için onaylayın. Bu ilk sürüm agent tarafından yürütülür ve broker’da kalıcı run kaydı yoktur."
    let webCoordAuditWhyOffline = "Clawdfather çevrimdışı olduğu için denetim isteği gönderilemez."
    let webCoordAuditWhyDisconnected = "Bu tarayıcı çevrimdışı olduğu için denetim isteği gönderilemez."
    let webCoordAuditWhyNoWrite = "Bu tarayıcının şu anda gönderme/yazma yetkisi yok."
    let webCoordAuditSending = "İstek gönderiliyor…"
    let webCoordAuditSent = "Denetim isteği gönderildi. Bu makbuz denetimin bittiği anlamına gelmez."
    let webCoordAuditFailed = "Denetim isteği gönderilmedi ({code}): {message}"
    let webCoordEffectRead = "Salt okunur"
    let webCoordEffectAdvisory = "Danışma"
    let webCoordEffectSpawns = "Oturum başlatır"
    let webCoordEffectMutation = "Durumu değiştirir"
    let webCoordStateAvailable = "Kullanılabilir"
    let webCoordStateDraft = "Taslak"
    let webCoordStateUnavailable = "Kullanılamaz"
    let webCoordStatePreview = "Önizleme"
    let webCoordStateDisabled = "Devre dışı"
    let webCoordOnline = "{name} çevrimiçi"
    let webCoordOffline = "{name} çevrimdışı"
    let webCoordControlsTitle = "{name} kontrolleri"
    let webCoordOpenControls = "{name} kontrollerini aç"
    let webCoordEmpty = "Tanınan hiçbir Clawdfather komutu bildirilmedi."
    let webCoordDisabledFallback = "Clawdfather tarafından devre dışı bırakıldı."
    let webCoordPreviewTitle = "Clawdfather komutu"
    let webCoordPreviewNone = "Komut seçilmedi; hiçbir şey gönderilmedi."
    let webCoordPreviewMutation = "Yalnızca önizleme — hiçbir şey gönderilmedi. Clawdfather komut API'si bağlanana dek onay kapalı kalır."
    let webCoordPreviewDraft = "Yalnızca çevrimdışı taslak — hiçbir şey gönderilmedi ve Clawdfather'ın yargısı olarak sunulmadı."
    let webCoordPreviewSpawn = "Yalnızca önizleme — hiçbir oturum başlatılmadı."
    let webCoordPreviewContract = "Yalnızca bu komutun sözleşmesi gösteriliyor; hiçbir şey gönderilmedi."
    let webCoordWhyNoCommandRoute = "Bu paneldeki bir komutu bir oturuma taşıyan bir yol henüz yok; hiçbir şey gönderilemez."
    let webCoordWhyNoReturnLedger = "Bu Mac henüz bir dönüş noktası kaydetmiyor; dolayısıyla karşılaştırıp okunacak bir şey yok."
    let webCoordWhyDeviceCannotSpawn = "Eşleştirilmiş bir aygıt asla oturum başlatamaz — bu ayrım bilinçli, ve bu düğme onu aşmayacak."
    let webCoordWhyMachineTokenOnly = "Yeniden bağlamak Mac'in kendi orkestratör anahtarını ister; eşleştirilmiş aygıt onu bilerek taşımaz."
    let webCoordReadFailed = "Clawdfather'ın durumu okunamadı."
    let webCoordActiveTasks = "{n} görev sürüyor"
    let webCoordPendingLandings = "{n} teslimat birleştirme bekliyor"
    let webCoordOpenWaits = "{n} açık dosya beklemesi"
    let webCoordCountUnknown = "{n} bilinmiyor"
    let webCoordStaleSessions = "Mac'in oturum görüntüsü bayat; bu sayılar eski olabilir."
    let webCoordUnknown = "Bilinmiyor"
    let webCoordWaitingList = "Birini bekleyenler"
    let webCoordBlockingList = "Başkalarının beklediği dosyaları tutanlar"
    let webCoordAllQuiet = "Tıkanan, çekişilen ya da sahipsiz kalan bir şey yok."
    let webCoordNoLandings = "Birleştirme bekleyen teslimat yok."
    let webCoordUnregistered = "Bu Mac'te kayıtlı bir Clawdfather yok."
    let webCoordScopeLine = "{name} bu Mac'i eşgüdümlüyor — makine kapsamı."
    let webCoordScopeDevice = "Bu panelden Clawdfather yalnızca okunabilir. İş göndermek, oturum başlatmak ve makine durumunu değiştirmek Mac'in kendi kimlik bilgilerini ister ve burada devre dışı kalır."
    let webClosing = "Kapatılıyor…"
    let webCancel = "İptal"
    let webConfirm = "Onayla"
    let webReviewBeforeClosing = "Oturumu gözden geçir"
    let webConfirmEndAnyway = "Yine de kapat"
    let webPickSession = "Soldan bir oturum seç."
    let webReading = "Okunuyor…"
    let webLoading = "Yükleniyor…"
    let webTranscriptFailed = "Döküm okunamadı"
    let webWhoYou = "sen"
    let webWhoTool = "araç"
    let webNoticeTask = "görev"
    let webNoticeCompleted = "Görev tamamlandı"
    let webNoticeFailed = "Görev başarısız oldu"
    let webNoticeTimedOut = "Görev zaman aşımına uğradı"
    let webNoticeCancelled = "Görev iptal edildi"
    let webNoticeCouldNotStart = "Görev başlatılamadı"
    let webNoticeFinished = "Görev sona erdi"
    let webNoticeWorkspaceOverlap = "Çalışma alanı çakışması"
    let webNoticeNoSiblings = "Hâlâ çalışan eş görev yok."
    let webNoticeOneSibling = "Hâlâ {n} eş görev çalışıyor."
    let webNoticeManySiblings = "Hâlâ {n} eş görev çalışıyor."
    let webNoticeClaimsReleased = "Yol ayırmaları serbest bırakıldı; alt sekme hâlâ yazıyor olabilir."
    let webNoticeFileWaitRequested = "Dosya bekleme isteği"
    let webNoticeFileWaitReleased = "Dosya beklemesi kaldırıldı"
    let webNoticeHandoffPickedUp = "Devir teslim alındı"
    let webNoticeHandoffNeedsDelivery = "Devir teslim elle ulaştırılmalı"
    let webNoticeRecheckGit = "Birleştirmeden önce HEAD, status ve diff’i yeniden denetleyin."
    let webPending = "Mac bekleniyor…"
    let webAttachedImage = "{n} resim eklendi"
    let webAttachedImages = "{n} resim eklendi"
    let webSteps = "{n} adım"
    let webJustNow = "az önce"
    let webMinutesAgo = "{n} dk önce"
    let webCodeCopy = "Bu kodu kopyala"
    let webCodeCopied = "Kod kopyalandı."
    let webCodeCopyFailed = "Kopyalanamadı — metni seçin."

    let webSend = "Gönder"
    let webAttach = "Resim ekle"
    let webRemoveShot = "{name} dosyasını kaldır"
    let webWriteOpen = "Yazmak için bir oturum aç."
    let webWriteOff = "*Gönderme kapalı* — sunucu `write: false` diyor. Kutu bağlı; bu değiştiği anda kendi kendine açılır."
    let webShotsOnlyPictures = "Bir mesajla yalnızca resim gidebilir"
    let webShotsTooMany = "Bir mesaj en çok {n} resim taşıyabilir"
    let webShotTooBig = "Bu resim küçültülse bile gönderilemeyecek kadar büyük"
    let webShotsTooBig = "Bu resimler birlikte gönderilemeyecek kadar büyük"
    let webShotUnreadable = "Bu resim okunamadı"
    let webShotNeedsSession = "Resim göndermek için bir oturum aç"

    let webVoiceStart = "Bir mesaj dikte et"
    let webVoiceStop = "Durdur ve yazıya dök"
    let webVoiceDone = "Bitti"
    let webVoiceListening = "Dinliyor… {t}"
    let webVoiceReading = "Mac'te yazıya dökülüyor… {n} sn"
    let webVoiceSlow = "Bu Mac yeniden başladıktan sonraki ilki önce modeli yüklüyor — on iki saniye kadar."
    let webVoiceLimit = "Kayıt {n} dakikada durdu; bir kayıt en fazla bu kadar sürer. Elde olan yazıya dökülüyor."
    let webVoiceEmpty = "Orada bir şey duyulmadı."
    let webVoiceTooShort = "Duyulamayacak kadar kısaydı."
    let webVoiceDenied = "Mikrofon reddedildi. Bu tarayıcının bu site için tuttuğu ayarlardan geri aç."
    let webVoiceNoMic = "Bu cihazda mikrofon bulunamadı."
    let webVoiceInUse = "Mikrofon meşgul — bu cihazda başka bir şey onu tutuyor."
    let webVoiceInsecure = "Mikrofon https ister, bu sayfa ise onun üzerinde değil. Tünel bir tane sağlar; yerel ağdaki düz bir adres sağlamaz."
    let webVoiceUnsupported = "Bu tarayıcı ses kaydedemiyor."
    let webVoiceBusy = "Biri yazıya dökülüyor, bir diğeri sırada bekliyor. Birazdan tekrar dene."
    let webVoiceNoBinary = "Mac'te Whisper kurulu değil, orada bunu yazıya dökecek bir şey yok."
    let webVoiceNoModel = "Mac'te Whisper var ama okuyacak modeli yok. `~/.cache/whisper` içinde bir ggml dosyası ona yeter."
    let webVoiceFailed = "Bu yazıya dökülemedi."

    let webHintMove = "gezin"
    let webHintOpen = "aç"
    let webHintFilter = "süz"
    let webHintPane = "panel"

    let webKeysLabel = "Klavye kısayolları"
    let webKeysTitle = "Klavye"
    let webKeysMove = "Listede gezin — `j` ve `k` de aynı işi yapar"
    let webKeysOpen = "Seçili oturumu aç"
    let webKeysFilter = "Listeyi süz"
    let webKeysEscape = "Önce süzgeci temizler, sonra geri gider"
    let webKeysList = "Oturum listesine odaklan"
    let webKeysPane = "Dökümü göster ya da gizle"
    let webKeysEnds = "Dökümün başı ya da sonu"
    let webKeysReverse = "Döküm sırasını ters çevir"
    let webKeysThis = "Bu kart"
    let webKeysFoot = "Bir metin kutusuna yazılan her şey o kutuda kalır — sen yazarken kısayollar geri çekilir."

    let webDoorLabel = "Bu tarayıcıyı eşleştir"
    let webDoorAskLede = "Bu tarayıcı henüz içeri alınmadı."
    let webDoorAskFine = "Eşleşme iste, altı haneli bir kod *Mac'te* belirsin — bu sayfaya gelen yanıtta bilerek yok. Bunu ancak o makinenin başındaki biri bitirebilir; bu bir engel değil, işin güvenliği tam olarak bu."
    let webDoorName = "Bu cihaza bir ad ver"
    let webDoorAsk = "Eşleşme iste"
    let webDoorToPassword = "Bunun yerine parolayla gir"
    let webDoorCodeLede = "Mac'e bak."
    let webDoorCodeFine = "Clawdline {left} boyunca altı hane gösteriyor. Onları buraya yaz."
    let webDoorTwoMinutes = "iki dakika"
    let webDoorDigit = "{n}. hane"
    let webDoorConfirm = "Bu cihazı eşleştir"
    let webDoorRestart = "Baştan başla"
    let webDoorPasswordLede = "Parolayla gir."
    let webDoorPasswordFine = "Mac'teki Clawdline'da, Ayarlar → Uzaktan erişim altında belirlenen parola. Hiç belirlenmemişse içeri giden yol eşleşmedir."
    let webDoorPassword = "Parola"
    let webDoorPasswordGo = "Gir"
    let webDoorToPair = "Bunun yerine eşleşme kodu kullan"
    let webDoorAsking = "Mac'e soruluyor…"
    let webDoorAskFailed = "Mac'e sorulamadı."
    let webDoorRateLimited = "Her istek Mac'te bir uyarı çıkarır, o yüzden on dakikada yalnızca üç tane var."
    let webDoorSixDigits = "Altı hane."
    let webDoorChecking = "Kontrol ediliyor…"
    let webDoorFinished = "Bu eşleşme bitti — beş kod yanlış girildi. Mac'in başındayken yeniden iste."
    let webDoorWrongCode = "Bu kod doğru değil."
    let webDoorNeedPassword = "Önce parola."
    let webDoorWrongPassword = "Parola bu değil."
    let webDoorExpired = "Bu kodun süresi doldu. Yeniden iste, Mac'te yenisi belirir."
    let webDoorPaired = "Eşleşti — bu tarayıcı içeride"

    let webOffline = "Clawdline'a ulaşılamadı. Mac'te hâlâ çalışıyor mu?"
    let webNotJSON = "Sunucu JSON olmayan bir şey gönderdi"
    let webRequestFailed = "İstek tamamlanamadı"

    let webNotifyGo = "Haber ver"
    let webNotifyAsking = "İzin isteniyor…"
    let webNotifyStop = "Durdur"
    let webNotifyStopping = "Durduruluyor…"
    let webNotifyOff = "bir oturum yanıt beklediğinde"
    let webNotifyOn = "Bu cihaz kayıtlı. Neyin haber verileceği Mac'te belirlenir."
    let webNotifyBlocked = "Bu site için bildirimler engellenmiş. O anahtar tarayıcının kendi ayarlarında, burada değil."
    let webNotifyUnsupported = "Bu tarayıcı bildirim gösteremiyor."
    let webNotifyHomeScreen = "clawdline'ı ana ekrana ekle ve oradan aç — iOS bildirimi yalnızca orada duran bir uygulamaya gönderir."
    let webNotifyOnFailed = "Bildirimler açılamadı"
    let webNotifyOffFailed = "Bildirimler kapatılamadı"

    let webSettings = "Ayarlar"
    let webSettingsNotify = "Bildirimler"
    let webSettingsAssistantIcons = "Asistan simgeleri"
    let webSettingsAssistantIconsSay = "Konuşmada Claude veya Codex adından önce simgesini göster."
    let webSettingsAssistantIconsShow = "Simgeleri göster"
    let webSettingsVersion = "Sürüm {v}"
    let webClose = "Kapat"
    let webNotifySheetOff = "Bir oturum beklerken bu cihaza haber verilmiyor."
    let webNotifyTest = "Deneme gönder"
    let webNotifyTestSent = "Gönderildi — birazdan bu cihaza ulaşması gerek."
    let webNotifyTestNone = "Mac'te bu cihaz için kayıt yok. Bildirimleri kapatıp yeniden aç, bu tarayıcı yenisini kaydeder."
    let webNotifyTestFailed = "Deneme bildirimi gönderilemedi"
    let webSending = "Gönderiliyor…"
    let webSendTip = "Return gönderir · Shift-Return satır açar"
    let webStart = "Oturum başlat"
    let webStartLabel = "Bir projede oturum başlat"
    let webStartPick = "Nerede başlasın?"
    let webStartWith = "Hangisiyle başlasın?"
    let webStartEmpty = "Henüz başlanacak bir yer yok. Mac'te bir kez Claude Code çalıştır, burada belirir."
    let webStartFilter = "Projeleri süz"
    let webStarting = "Sekme açılıyor…"
    let webStartWaiting = "Başladı. Görünmesi bekleniyor…"
    let webStartSlow = "Sekme açık ama oturum henüz haber vermedi. Mac'e bir bak."
    let webStartFailed = "Bu başlatılamadı."
    let webStartGone = "O proje artık Mac'te yok."
    let webStartTerminalClosed = "{app} Mac'te çalışmıyor. Orada aç ve yeniden dene."
    let webStartTerminalUnsupported = "Ayarlar yeni oturumları tmux'ta açıyor ama bu Mac'te tmux yok. Oraya kur ya da ayarlardan başka bir terminal seç."
    let webStartDetached = "Oturum, hiçbir şeyin bağlı olmadığı bir tmux sunucusunda başladı. Görmek için Mac'te {command} yaz."
    let webStartOff = "Oturum başlatma kapalı. Mac'te Ayarlar → Uzaktan erişim onu açar."
    let webResumeWith = "Öncekini sürdür"
    let webResumePick = "Hangi konuşma?"
    let webResumeFilter = "Konuşmaları süz"
    let webResumeEmpty = "O projede henüz hiçbir şey kaydedilmedi."
    let webResumeLive = "açık"
    let webResumeBack = "Başka bir proje"
    let webResumeGone = "O konuşma artık Mac'te değil."
    let webResumeClaudeOnly = "Sürdürülebilir konuşmaları yalnızca Claude Code saklar."
    let webResuming = "Kaldığı yerden açılıyor…"
    let webResumeCapped = "Bunlardan eskiler bu listede yok."
    let webCommand = "Ne başlatılacağını söyle"
    let webCommandLabel = "Ne yapılacağını söyleyerek oturum başlat"
    let webCommandSay = "Aşağıdaki Başlat'a basana kadar hiçbir şey gönderilmez."
    let webCommandHeard = "Ne yapmalı?"
    let webCommandThinking = "Düşünüyor…"
    let webCommandDraft = "Taslak"
    let webCommandWhere = "Nerede"
    let webCommandWith = "Hangisiyle"
    let webCommandModel = "Model"
    let webCommandFirst = "İlk mesaj"
    let webCommandGo = "Başlat"
    let webCommandUnsure = "Hangi proje olduğu belli değil — aşağıdan birini seç."
    let webCommandFailed = "Bu taslağa dönüştürülemedi."
    let webCommandNoPlanner = "Bu Mac'te bunu taslağa dönüştürecek Claude Code yok."
    let webCommandBusy = "Zaten bir cümle taslağa dönüştürülüyor — birazdan tekrar dene."
    let webCommandEmpty = "Hiçbir şey duyulmadı"
    let webScheduleNew = "Yeni zamanlama"
    let webScheduleEdit = "Zamanlamayı düzenle"
    let webScheduleNewSay = "Aşağıdaki Oluştur'a basana kadar hiçbir şey zamanlanmaz."
    let webScheduleTitle = "Başlık"
    let webScheduleAt = "Saat"
    let webScheduleOn = "Günler"
    let webScheduleWhere = "Nerede"
    let webScheduleWith = "Hangisiyle"
    let webScheduleFirst = "İlk mesaj"
    let webScheduleMore = "Daha fazla"
    let webScheduleModel = "Model"
    let webScheduleWhenDone = "Bittiğinde sekmeyi kapat"
    let webScheduleCloseSuccess = "Başarılı olursa"
    let webScheduleCloseAlways = "Her zaman"
    let webScheduleCloseNever = "Açık bırak"
    let webScheduleEnabled = "Etkin"
    let webScheduleDisabled = "Etkin değil"
    let webScheduleNotify = "Başarısız olursa bana bildir"
    let webScheduleCatchUp = "Kaçırıldıysa (saat) içinde telafi et"
    let webScheduleTimeout = "(dakika) içinde bitmezse vazgeç"
    let webScheduleCreate = "Oluştur"
    let webScheduleCreated = "Zamanlama oluşturuldu."
    let webScheduleDispatchOff = "Zamanlama oluşturuldu ve geçerli, ama görev verme kapalı — kimse çalıştırmayacak. Mac'te Ayarlar → Uzaktan erişim onu açar."
    let webScheduleFailed = "Zamanlama oluşturulamadı."
    let webScheduleSave = "Kaydet"
    let webScheduleSaved = "Zamanlama kaydedildi."
    let webScheduleDelete = "Sil"
    let webScheduleDeleteAsk = "{title} silinsin mi? Geri alınamaz."
    let webScheduleDeleted = "Zamanlama silindi."
    let webScheduleNeedsTime = "Saat duyulmadı — bir tane belirle."
    let webScheduleNeedsPlace = "Hangi proje olduğu belli değil — birini seç."
    let webScheduleDaily = "Her gün"
    let webScheduleSun = "Paz"
    let webScheduleMon = "Pzt"
    let webScheduleTue = "Sal"
    let webScheduleWed = "Çar"
    let webScheduleThu = "Per"
    let webScheduleFri = "Cum"
    let webScheduleSat = "Cmt"
    let webSnippets = "Hazır metinler"
    let webSnippetsThisProject = "Bu proje"
    let webSnippetsEveryProject = "Tüm projeler"
    let webSnippetsEmpty = "Henüz hazır metin yok. Mac'te bir tane ekle, burada görünür."
    let webSnippetsEmptyNew = "Henüz hazır metin yok. Kendin yaz ya da şunlardan biriyle başla."
    let webSnippetsReadOnly = "Bu cihaz okuyabilir ama yazamaz — hazır metin kutuya konulamaz."
    let webSnippetNew = "Yeni hazır metin"
    let webSnippetEditing = "Hazır metni düzenle"
    let webSnippetMore = "Hazır metin işlemleri"
    let webSnippetEdit = "Düzenle"
    let webSnippetDelete = "Sil"
    let webSnippetDeleteAsk = "Silmek için tekrar bas"
    let webSnippetUp = "Yukarı taşı"
    let webSnippetDown = "Aşağı taşı"
    let webSnippetToGlobal = "Tüm projelere taşı"
    let webSnippetToProject = "Sadece bu proje"
    let webSnippetTitleLabel = "Başlık"
    let webSnippetBodyLabel = "Metin"
    let webSnippetScopeLabel = "Nerede"
    let webSnippetSave = "Kaydet"
    let webSnippetFromLast = "Son mesajımdan"
    let webSnippetNeedsText = "Hazır metin için bir başlık ve biraz metin gerekir."
    let webSnippetTooLong = "Çok uzun. Başlık 60 bayt, metin 4000 bayt alır."
    let webSnippetStarterCommitTitle = "Commit, push, deploy"
    let webSnippetStarterCommitBody = "Her dosyayı adını yazarak commit et — asla git add -A yapma — sonra push ve deploy."
    let webSnippetStarterReportTitle = "Ne yaptığını söyle"
    let webSnippetStarterReportBody = "Az önce ne yaptığını, neyin eksik kaldığını ve sırada ne olduğunu söyle."
    let webLinks = "Adresler"
    let webLinksTip = "Bu proje nerede açılır"
    let webLinksPick = "Bu projenin adresi olan her şey."
    let webLinksEmpty = "Bu projenin adresi olan hiçbir şeyi yok — site yok, deploy yok, çalışan sunucu da yok."
    let webLinksFailed = "Bu projenin adresleri okunamadı."
    let webLinksLocal = "Yalnızca Mac'in kendi ağında. Buradan açılmaz."
    let webLinksFile = "Mac'teki bir dosya. Orada açılır, bu tarayıcıda değil."
    let webLinksCopy = "Yolu kopyala"
    let webLinksCopied = "Kopyalandı."
    let webLinksCopyFailed = "Bu tarayıcı sayfanın onu kopyalamasına izin vermedi."
    let webLinkOk = "iyi"
    let webLinkFail = "hata"
    let webLinkDown = "kapalı"
    let webLinkRunning = "sürüyor"
    let webSessionInfo = "Oturum bilgisi"
    let webInfoTitle = "Bu oturum hakkında"
    let webInfoEditTitle = "Oturum başlığını düzenle"
    let webInfoCopyTitle = "Bu adı kopyala"
    let webInfoTitleSaved = "Başlık kaydedildi."
    let webInfoTitleLocal = "Başlık Clawdline’a kaydedildi; alt ad değişmedi."
    let webInfoTitleQueued = "Başlık Clawdline’a kaydedildi; Codex güncellemesi sırada."
    let webInfoTitleNotDurable = "Başlık görünüyor ama bu Mac diske yazamadı; yeniden başlatınca kaybolacak."
    let webInfoTitleCloud = "Oturum başlıkları yalnızca Mac üzerinde değiştirilir, bulut bağlantısıyla değil."
    let webInfoSession = "Bu oturum"
    let webInfoAssistant = "Asistan"
    let webInfoModel = "Model"
    let webInfoSessionId = "Oturum kimliği"
    let webInfoDirectory = "Dizin"
    let webInfoRunningFor = "Çalışma süresi"
    let webInfoStatus = "Durum"
    let webInfoWorkStatusMeaning = "Bu, oturumun çalışma durumudur. Bir onay işareti teslim edildiğini ve onay beklediğini; iki işaret incelenip onaylandığını gösterir."
    let webInfoCloseabilityMeaning = "Anahtar, oturumun güvenle kapatılıp kapatılamayacağını gösterir. Teslim durumundan bağımsızdır."
    let webInfoUsage = "Token kullanımı"
    let webInfoInput = "Girdi"
    let webInfoOutput = "Çıktı"
    let webInfoCacheRead = "Önbellekten okunan"
    let webInfoCacheWrite = "Önbelleğe yazılan"
    let webInfoTotal = "Toplam"
    let webInfoCost = "Tahmini maliyet"
    let webInfoNoUsage = "Bu oturumun kaydı henüz bulunamadı."
    let webInfoLimits = "Plan limitleri"
    let webInfoLimitHit = "limite ulaşıldı"
    let webInfoResets = "{when} sıfırlanır"
    let webInfoUnknown = "bilinmiyor"
    let webInfoFiles = "Dosyalar"
    let webInfoBranch = "Dal"
    let webInfoStaged = "Hazırlanan"
    let webInfoUnstaged = "Değişen"
    let webInfoUntracked = "İzlenmeyen"
    let webInfoConflict = "Çakışmalar"
    let webInfoClean = "Commit edilmemiş bir şey yok."
    let webInfoNotRepo = "Bir git deposu değil."
    let webInfoDeploy = "Son deploy"
    let webInfoNoDeploy = "Bu proje için kayıtlı bir deploy yok."
    let webInfoFailed = "Bu oturumun bilgisi okunamadı."
    let webInfoBusy = "Mac şu anda başka oturumları okumakla meşgul. Birazdan tekrar dene."
    let webInfoRefresh = "Yenile"
    let webInfoTokens = "token"
    let webInfoSwitchModel = "Modeli değiştir"
    let webInfoModelOther = "başka bir model…"
    let webInfoModelSent = "/model {model} gönderildi. Doğrulanıyor…"
    let webInfoModelBusy = "Değişiklik oturum boşta kalana kadar bekler."
    let webInfoSwitchPermission = "İzin modunu değiştir"
    let webInfoPermissionAuto = "Otomatik"
    let webInfoPermissionManual = "El ile"
    let webInfoPermissionAcceptEdits = "Düzenlemeleri kabul et"
    let webInfoPermissionPlan = "Plan"
    let webInfoPermissionUnreadable = "Geçerli mod okunamadı."
    let webInfoPermissionSent = "{mode} moduna geçildi. Doğrulanıyor…"
    let webInfoPermissionBusy = "İzin modu değiştiriliyor."
    let webInfoLimitsClaude = "Claude Code bir pencereyi ancak tükenince yazar; o zamana kadar bir şey bilinmez."
    let webInfoCopied = "Oturum kimliği kopyalandı."
    let webInfoAsOf = "{when} itibarıyla"
    let webInfoWhyUnknown = "Neden bilinmiyor, ve sayılar nasıl alınır"
    let webSettingsOrder = "Döküm"
    let webSettingsOrderSay = "Döküm hangi uçtan okunmaya başlasın. Her oturum için geçerli, klavyede `r` de aynısını yapar."
    let webAskLabel = "sordu"
    let webAskAny = "Bunlardan kaç tane istersen"
    let webWaitingTitle = "Bu oturum yanıt bekliyor"
    let webWaitingSay = "Claude Code Mac'te bir menü gösteriyor. Clawdline buradan bir menüyü henüz okuyamıyor, seçenekler yalnızca o ekranda."
    let webWaitingSend = "*Buradan göndermek yanıtını menüye yazmaz* — menüde o an hangi satır seçiliyse onu onaylar, o da nadiren senin kastettiğindir. Bunu Mac'te yanıtla."
    let webMenuSay = "Bir yanıta dokun, doğrudan oturuma gider."
    let webMenuHighlighted = "seçili"
    let webMenuSent = "Yanıt gönderildi."
    let webAgents = "Arka plandaki ajanlar"
    let webAgentsCount = "{n} çalışıyor"
    let webAgentDone = "bitti"
    let webAgentFailed = "başarısız"
    let webShells = "Arka plandaki shell'ler"
    let webShellTitle = "Arka plandaki shell"
    let webShellOpen = "Bu komutun ne yazdığını gör"
    let webShellRunning = "hâlâ çalışıyor"
    let webShellEnded = "bitti"
    let webShellQuiet = "Henüz bir şey yazmadı."
    let webShellFailed = "Bu komutun çıktısı okunamadı."
    let webShellClose = "Kapat"
    let webShellStop = "Durdur"
    let webShellStopTitle = "Bu komut durdurulsun mu?"
    let webShellStopSay = "{command} hâlâ çalışıyor. Önce durması isteniyor, beş saniye sonra hâlâ duruyorsa öldürülüyor. Şimdiye kadar yaptıkları geri alınmaz."
    let webShellStopped = "Durması istendi."
    let webShellStopFailed = "Durdurulamadı."
    let agentRunning = "çalışıyor"
    let agentTools = "{n} araç"
    let agentEmpty = "Bu ajan henüz hiçbir şey yazmadı."
    let agentBack = "Oturum"
    let webAgentOpen = "Bu ajanın ne yaptığını gör"
    let webTaskRoot = "Kök"
    let webTaskChild = "Alt"
    let webTaskTasks = "Görevler"
    let webTaskDone = "bitti"
    let webTaskFailed = "başarısız"
    let webTaskRunning = "çalışıyor"
    let webStale = "Clawdline Mac'te yeniden derlendi. Bu sayfa eski olanı."
    let webStaleGo = "Yeniden yükle"

    // The Projects page, and the worktrees under one Project that finished a Feature.
    let webProjects = "Projeler"
    let webProjectsLede = "Bir asistanın gerçekten çalıştırıldığı ve hâlâ yerinde duran dizinler."
    let webProjectsEmpty = "Bu Mac'te henüz kayıtlı bir proje dizini yok."
    let webProjectsUnavailable = "Bu bağlantı projeleri okuyamıyor. Uygulamanın kendi adresini Mac'in ağında açın."
    let webProjectsLoading = "Bu Mac'in proje listesi okunuyor…"
    let webProjectOpenLabel = "{name} projesini aç"
    let webProjectReading = "Bu projenin defter satırları birleştiriliyor…"
    let webProjectDelivered = "Bitti, ama birleştirilmedi"
    let webProjectDeliveredSay = "Bunlar bir Feature'ı bitirdi ve işin ağaca girdiğini söyleyen hiçbir şey yok: ne bir iniş kaydı, ne de git'in birleştirilmiş dediği bir dal. İş bitmiş; kimse birleştirmemiş."
    let webProjectDeliveredNone = "Burada bekleyen bir şey yok: bu projede biten her Feature indi — bir root'un kaydıyla ya da git'in çoktan birleştirdiği bir dalla."
    let webProjectLanded = "İnmiş"
    let webProjectLandedSay = "Bir root teslimatın hedef dalına ulaştığını kaydetti ya da git o dalın zaten ağaçta olduğunu söylüyor."
    let webProjectActive = "Hâlâ çalışıyor"
    let webProjectActiveSay = "Bu worktree'den bir görev şu anda kayıt defterinde canlı."
    let webProjectAbandoned = "Bırakılmış"
    let webProjectAbandonedSay = "Burada hiçbir şey başarıyla bitmedi ve çalışan bir şey de kalmadı."
    let webProjectUnknownOutcome = "Bilinmiyor"
    let webProjectUnknownSay = "Kayıtlı hiçbir satır görev durumu taşımıyordu, bu yüzden iki yönde de tahmin yürütülmüyor."
    let webProjectBranch = "Dal, teamül gereği"
    let webProjectEvidence = "İniş kanıtı"
    let webProjectEvidenceRecord = "Bir kök doğrulayıp kaydetti"
    let webProjectEvidenceBranchMerged = "git: dal HEAD’in içinde"
    let webProjectEvidenceBranchAbsent = "git: dal artık yok"
    let webProjectEvidenceBranchUnmerged = "git: dal hâlâ birleştirilmedi"
    let webProjectEvidenceUnknown = "git’e sorulamadı"
    let webProjectRuns = "Ajan işi"
    let webProjectSeen = "Görüldüğü aralık"
    let webProjectNoWorktrees = "Bu projede bir Feature'ı bitirmiş worktree yok."
    let webProjectExcluded = "Bu projedeki {n} worktree daha hiçbir Feature bitirmedi; listelenmek yerine sayıldılar."
    let webProjectUnattributed = "Projesiz worktree'ler"
    let webProjectUnattributedSay = "{n} worktree hiçbir projeye ait değil: kanonik proje anahtarları var olmadan önce kaydedildikleri için kendi anahtarları bir çalışma kopyası yolu. Sessizce atılmak yerine burada sayılıyorlar."
    let webProjectRead = "{rows} satır okundu · {project} tanesi bu projeye ait · {worktree} tanesi bir worktree'de · {feature} tanesi bir Feature taşıyor"
    let webProjectTruncated = "Kısmi: tarama satır tavanına ulaştı, dolayısıyla yukarıdaki her şey bir toplam değil alt sınır."
    let webProjectNotFound = "Defterde bu projeye karşılık gelen bir şey yok. Altında henüz hiçbir şey kaydedilmemiş."
    let webProjectAmbiguous = "Bu adı birden fazla proje taşıyor; bu yüzden okuma, birinin adına cevaplanmak yerine reddedildi."
    let webProjectBusy = "Defter okuyucusu meşgul. Oturumlar etkilenmez — birazdan tekrar deneyin."
    let webProjectFailed = "Bu projenin worktree'leri okunamadı."

    let menuApplication = "Clawdline"
    let menuWindow = "Pencere"
    let menuHelp = "Yardım"
    let menuClose = "Pencereyi Kapat"
    let menuHome = "Ana Sayfa / Kurulum Merkezi"
    let menuHelpDocumentation = "Clawdline Belgeleri"
    func menuAbout(_ app: String) -> String { "\(app) Hakkında" }
    let menuServices = "Servisler"
    func menuHide(_ app: String) -> String { "\(app)’ı Gizle" }
    let menuHideOthers = "Diğerlerini Gizle"
    let menuShowAll = "Tümünü Göster"
    let menuMinimize = "Küçült"
    let homeTitle = "Clawdline Ana Sayfa"
    let homeWelcome = "Bağlantı amacınızı seçin. Kurulum yalnızca değiştirdiğiniz anahtarı değil, gerçek kanıtı gösterir."
    let homePurpose = "Neye bağlanmak istiyorsunuz?"
    let homeLocalTitle = "Yerel Tarayıcı"
    let homeLocalSummary = "Clawdline’ı bu Mac’teki tarayıcıda okuyun. Ayarlar’da açıkça etkinleştirmedikçe denetim kapalı kalır."
    let homeCloudPreviewTitle = "Clawdline Cloud Önizlemesi"
    let homeCloudPreviewSummary = "Canlı bağlantı kanıtlandıktan sonra barındırılan önizlemeyi kullanın."
    let homeCloudflareTitle = "Cloudflare URL’m"
    let homeCloudflareSummary = "Herkese açık HTTPS yolu kanıtlandıktan sonra kendi Cloudflare ana makine adınızı kullanın."
    let homeUnavailable = "Bu yapıda henüz hazır değil; başarılı bağlantı iddiasında bulunulmuyor."
    let setupDetected = "Algılanan durum"
    let setupNextAction = "Sonraki adım"
    let setupExpected = "Beklenen sonuç"
    let setupRecovery = "Kurtarma"
    let setupLocalServerOff = "Geri döngü sunucusu kapalı."
    let setupLocalChecking = "Gerçek /v1/health uç noktası denetleniyor…"
    let setupLocalConfigurationFailed = "Yerel tarayıcı ayarı kaydedilemedi; hiçbir şey değiştirilmedi."
    let setupLocalHealthTransport = "Sağlık uç noktasına ulaşılamadı. Bağlantı noktasını ve diğer programları denetleyin."
    let setupLocalHealthTimedOut = "Sağlık uç noktası zaman aşımına uğradı. Bağlantı noktasını denetleyip yeniden deneyin."
    func setupLocalHealthHTTP(_ status: Int) -> String { "Sağlık uç noktası sağlıklı yanıt yerine HTTP \(status) döndürdü." }
    let setupLocalHealthUnhealthy = "Uç nokta yanıt verdi ancak ok: false bildirdi."
    let setupLocalHealthInvalid = "Uç nokta geçerli bir sağlık yanıtı vermedi. Yapılandırılmış bağlantı noktasını denetleyin."
    let setupLocalReady = "Sağlık uç noktası hazır. Henüz tarayıcı kimlik bilgisi yok."
    let setupLocalWaiting = "Tarayıcı açıldı; tam olarak bu aygıtın kimlik doğrulaması bekleniyor."
    let setupLocalConnected = "Bağlandı. Bu tarayıcı aygıtı Clawdline’a ulaştı."
    let setupLocalEnable = "Yerel Tarayıcıyı Aç"
    let setupLocalRetry = "Yeniden Denetle"
    let setupLocalOpen = "Salt Okunur Tarayıcıyı Aç"
    let setupLocalOpenAgain = "Tarayıcıyı Yeniden Aç"
    let setupFinish = "Bitti"
    let setupLocalExpected = "Salt okunur tarayıcı açılıp kimlik doğrular; etkin oturum olmasa da başarılıdır."
    let setupLocalRecovery = "Takılırsa bu pencereyi açık tutup yeniden denetleyin. Sunucu ve bağlantı noktası Ayarlar’dadır."
    let setupNoRecovery = "Kurtarma gerekmiyor; bu yol kanıtlandı."
    let setupLocalReadOnlyAction = "Bu eylem salt okunur erişimi kaydeder ve denetimi kapalı tutar."
    let setupReadOnly = "Salt okunur · denetim kapalı kalır"
    let setupLocalDeviceName = "Kurulum Merkezi tarayıcısı"
    func setupTunnelFacts(_ mode: String, _ tunnel: String, _ hostname: String, _ status: String) -> String { "Mod: \(mode)\nTünel: \(tunnel)\nQR ana makinesi: \(hostname)\nDurum: \(status)" }
    let setupTunnelModeOff = "Kapalı"
    let setupTunnelModeQuick = "Hızlı"
    let setupTunnelModeNamed = "Adlandırılmış"
    let setupTunnelQuickName = "Cloudflare Hızlı Tüneli"
    let setupNone = "Yok"
    let setupControlChosen = "Okuma + kontrol · Ayarlar’da açıkça etkinleştirildi"
    let setupTunnelMissing = "cloudflared yüklü değil."
    let setupTunnelOff = "Tünel kapalı; telefon QR’ı kullanılamıyor."
    let setupTunnelStarting = "cloudflared başlıyor; telefon QR’ı henüz kullanılamıyor."
    func setupTunnelReady(_ url: String) -> String { "\(url) adresinde canlı. Henüz telefon kimliği yok." }
    func setupTunnelWaiting(_ url: String) -> String { "QR \(url) adresini gösteriyor. Tam olarak bu telefon bekleniyor." }
    func setupTunnelConnected(_ url: String) -> String { "\(url) üzerinden bağlı. Bu telefon lastSeen bildirdi." }
    let setupTunnelExpected = "QR’a yalnızca canlı tünel URL’si girer; kurulumu yalnızca bu QR’ın oluşturduğu yerel olmayan cihazın lastSeen kaydı bitirir."
    let setupTunnelRecovery = "Uzak Ayarlar’ı açın. Eksikse cloudflared kurun; değilse algılanan nedeni izleyin, tüneli açık tutup yeniden tarayın."
    let setupOpenRemoteSettings = "Uzak Ayarlar’ı Aç"
    let setupCheckTunnel = "Tüneli Yeniden Denetle"
    let setupShowPhoneQR = "Telefon QR’ını Göster"
    let setupShowPhoneQRAgain = "Telefon QR’ını Yeniden Göster"
    let setupCloudRelayUnauthorized = "Relay bu makinenin kimliğini reddetti."
    func setupCloudFacts(_ account: String, _ credential: String, _ relay: String, _ pairing: String, _ receipt: String) -> String { "Hesap: \(account)\nMakine kimliği: \(credential)\nRelay hazır: \(relay)\nE2EE eşleştirme: \(pairing)\nViewer alındısı: \(receipt)" }
    let setupCloudExpected = "Preview yalnızca hesap, makine kimliği, relay hazırlığı, E2EE eşleştirmesi ve bu viewer alındısı ayrı ayrı kanıtlandığında tamamlanır."
    let setupCloudRecovery = "Oturum açmak veya eşleştirmek için Cloud Ayarları’nı kullanın. Relay ve viewer alındısı Preview kanıtlarıdır; yeniden denemek eksik kanıt yaratmaz."
    let setupOpenCloudSettings = "Cloud Ayarları’nı Aç"
    let setupPairCloudPhone = "Cloud’da Telefon Eşleştir"
    let setupReviewCloudPreview = "Preview Durumunu İncele"
    let setupProofAbsent = "yok"
    let setupProofReading = "kanıt okunuyor…"
    let setupProofUnavailable = "kanıt kullanılamıyor"
    func setupProofFailed(_ reason: String) -> String { "başarısız — \(reason)" }
    let setupCloudIdentityReadFailed = "Anahtar Zinciri kimliği okunamadı"
    let setupCloudRelayFailed = "relay hata bildirdi; Cloud Ayarları ve günlüğü inceleyin"
    let setupCloudPairingReadFailed = "eşlenmiş cihaz deposu okunamadı"
    let setupCloudPairingAmbiguous = "birden fazla yeni viewer göründü; eşlemeyi yeniden başlatın"
    func setupCloudAccountProved(_ account: String) -> String { "\(account) olarak oturum açıldı" }
    func setupCloudCredentialProved(_ machine: String) -> String { "\(machine) için Anahtar Zinciri kimliği" }
    func setupCloudPairingProved(_ device: String) -> String { "tam viewer \(device) için sabitlendi" }
    let setupCloudflareDeviceName = "Cloudflare üzerinden telefon"
    let setupScanLiveTunnel = "Canlı tüneli telefonunuzla tarayın"
    let setupDismissalHint = "Home’u kapatmak otomatik açılmayı durdurur. Kurulum Merkezi’ni menü, Dock, durum öğesi veya clawdline://home ile yeniden açın."
    let setupCompletionFailed = "Clawdline tamamlanmayı kaydedemedi. ~/.config/clawdline izinlerini denetleyip Home’u yeniden kapatın."

    let menuOpen = "Giriş çubuğunu aç"
    let menuReveal = "Hedef sekmeye git"
    let menuMascot = "Maskot"
    let menuLogin = "Girişte başlat"
    let menuEditConfig = "Ayarlar…"
    let menuReload = "Ayarları yeniden yükle"
    let menuQuit = "Clawdline'dan çık"
    let menuNoTarget = "(henüz bulunamadı)"

    func updateAvailable(latest: String, installed: String) -> String {
        "Clawdline \(latest) çıktı — buradaki \(installed)"
    }
    func compatNote(_ standing: Compat.Standing) -> String {
        switch standing {
        case .behind(let program, let installed, let builtAgainst):
            return "\(program) \(installed); bu yapı \(builtAgainst) ile denendi"
        case .ahead(let program, let installed, let builtAgainst, let release):
            return "\(program) \(installed); bu yapı \(builtAgainst) ile denendi — Clawdline \(release) çıktı"
        }
    }

    func hotkeyFailedTitle(_ combo: String) -> String { "\(combo) kaydedilemedi" }
    func hotkeyFailedBody(_ configPath: String) -> String {
        """
        Büyük ihtimalle başka bir uygulama almış — Spotlight, klavye düzeni değiştirici, \
        BetterTouchTool ve benzerleri.

        Başka birini seç: \(configPath) içindeki "hotkey" değerini düzenle, sonra menü \
        çubuğundan "Ayarları yeniden yükle" seçeneğini seç.

        O zamana kadar menü çubuğundaki ✳ giriş çubuğunu açmayı sürdürür.
        """
    }
    let loginFailed = "Girişte başlatma ayarlanamadı"
}
