import Foundation

struct Italian: Copy {
    let placeholder = "Scrivi a Claude Code…"

    let hintSend = "invia"
    let hintNewline = "a capo"
    let hintSwitch = "cambia"
    let hintList = "elenco"
    let hintMascot = "mascotte"
    let hintOutput = "output"
    let hintFullscreen = "schermo intero"
    let hintKeys = "tasti"
    let hintTextSize = "dimensione"
    let hintOrder = "inverti"
    let hintVoice = "detta"
    func voiceListening(onDevice: Bool) -> String {
        onDevice ? "In ascolto su questo Mac — premi di nuovo per fermare"
                 : "In ascolto — questa lingua la trascrive Apple, non questo Mac"
    }
    let voiceNoPermission = "La dettatura ha bisogno di microfono e riconoscimento vocale"
    let voiceUnavailable = "La dettatura non è disponibile in questo momento"
    func voiceTranscribing(seconds: Double) -> String {
        String(format: "Whisper sta rileggendo… %.1f s", seconds)
    }
    let whisperMissing = "Whisper non è installato — vedi docs/whisper.md"
    let whisperNothingHeard = "Non ho sentito nulla"
    func dictationStatus(_ status: Whisper.Status) -> String {
        switch status {
        case .ready(let model): return "Dettatura: Apple, poi Whisper (\(model))"
        case .noBinary: return "Dettatura: solo Apple — manca whisper-cli"
        case .noModel: return "Dettatura: solo Apple — whisper-cli c'è, manca il modello"
        }
    }
    func voiceListeningWhisper() -> String {
        "In ascolto — quando ti fermi Whisper dà un'altra letta"
    }

    let scanning = "Ricerca…"
    let noSession = "Nessuna sessione di Claude Code trovata"
    let nothingToSend = "Nessuna destinazione — avvia prima Claude Code in un terminale"
    let sendFailed = "Invio non riuscito"
    let itermSilent = "iTerm2 non ha risposto"
    let scriptMissing = "Manca iterm.js — bundle dell'app danneggiato?"
    let cannotList = "Non è stato possibile leggere le sessioni di iTerm2"
    let noOutput = "In questa sessione non c'è ancora nulla da leggere."
    func outputSize(_ pt: Int) -> String { "Testo dell'output \(pt) pt — ⌘J per vederlo" }
    func foldedTools(_ count: Int) -> String { "\(count) passaggi" }
    func outputOrder(newestFirst: Bool) -> String {
        newestFirst ? "Prima i più recenti" : "Prima i più vecchi"
    }
    func backlogNow(_ count: Int) -> String { "ora \(count)" }
    func dropped(_ count: Int) -> String {
        count == 1 ? "Percorso aggiunto — Claude Code lo legge" : "Aggiunti \(count) percorsi"
    }
    func stackConfirm(_ command: String) -> String { "Premi di nuovo per eseguire:  \(command)" }
    let hintStacks = "server"
    func stackTip(up: Int, total: Int) -> String { "\(up) di \(total) server attivi — ⌘S per l\'elenco" }
    let stackTipUnknown = "Questo progetto ha server; il suo comando di stato non è ancora attendibile — ⌘S"
    let stackUntrusted = "non approvato"
    let stackExit = "uscita"
    let stackActionStart = "avvia"
    let stackActionRestart = "riavvia"
    let stackActionStop = "ferma"
    let stackActionLogs = "log"
    let stackLogAll = "tutti"
    let stackLogBack = "trascrizione"
    let stackActionAllow = "consenti"
    let stackActionAgain = "di nuovo"
    func sessionTip(index: Int, total: Int) -> String { "Sessione \(index) di \(total) — ⌘K per cambiare" }
    let sessionWaiting = "aspetta te"
    let sessionAgents = "{n} in secondo piano"
    let islandDone = "fatto"
    let islandAllSessions = "Tutte le sessioni…"
    func statusWaiting(_ labels: [String]) -> String {
        labels.count == 1 ? "\(labels[0]) sta aspettando te"
                          : "\(labels.count) sessioni stanno aspettando te"
    }
    func statusWorking(_ count: Int) -> String { "\(count) in corso" }

    let settingsTitle = "Impostazioni di Clawdline"
    let settingsGeneral = "Generale"
    let settingsBar = "La barra"
    let settingsReading = "Lettura"
    let settingsVoice = "Dettatura"
    let settingsHotkey = "Scorciatoia"
    let settingsRecording = "Premi dei tasti…"
    let settingsScope = "Attiva in"
    let settingsScopeGlobal = "In ogni app"
    let settingsScopeHint = "Vuoto significa ovunque, quindi togliere l'ultima accende l'interruttore qui sopra — e rispegnerlo rimette l'elenco. Il file di configurazione le tiene come bundle id, e un elenco modificato a mano funziona lo stesso."
    let settingsScopeAdd = "Aggiungi un'app…"
    let settingsScopeChoose = "Scegli un'app…"
    let settingsScopeRunning = "Aperte in questo momento"
    let settingsScopeRemove = "Togli"
    let settingsLanguage = "Lingua"
    let settingsReopen = "La barra va e viene con il terminale"
    let settingsReopenHint = "Uscire dal terminale mette via la barra, e tornarci la fa ricomparire. Esc è quello che vuol dire che hai finito."
    let settingsFollow = "Il terminale mostra quello che la barra sta puntando"
    let settingsFollowHint = "Seleziona la scheda di quella sessione. Non porta il terminale in primo piano: altrimenti ogni pressione di Tab toglierebbe la tastiera dalla casella in cui stai scrivendo."
    let settingsCodexAutoName = "Dai un nome alle nuove sessioni Codex"
    let settingsCodexAutoNameHint = "Esegue un piccolo turno Codex Luna per ogni sessione senza nome. Usa la prima richiesta, consuma utilizzo Codex e non sostituisce mai un nome scelto da te."
    let settingsNotch = "Vivi nel notch"
    let settingsNotchHint = "Un personaggio nell’alloggiamento della fotocamera. Off è off: non si disegna nulla e non si crea alcuna finestra."
    let settingsPosition = "Altezza sullo schermo"
    let settingsWidth = "Larghezza"
    let settingsOpacity = "Opacità della scheda"
    let settingsShow = "Mostra"
    let settingsPaneHeight = "Altezza del riquadro"
    let settingsTextSize = "Dimensione del testo"
    let settingsPaneFont = "Font del riquadro"
    let settingsBlur = "Sfocatura dietro"
    let settingsNewestFirst = "Più recenti in alto"
    let settingsEngine = "Riconoscimento"
    let settingsSettle = "Una pausa chiude la frase"
    let settingsStop = "Un silenzio chiude la sessione"
    let settingsAuto = "Auto"
    let settingsTranscript = "Trascrizione"
    let settingsTerminal = "Terminale"
    let settingsOff = "Off"
    let settingsHooks = "Hook di Claude Code"
    let settingsHooksHint = "Una volta installati, Claude Code segnala l'istante in cui un turno inizia, finisce o aspetta una risposta, invece che Clawdline se ne accorga al controllo successivo. Tutto si legge sempre dallo schermo; questo decide solo quanto in fretta."
    let settingsHooksInstall = "Installa"
    let settingsHooksRemove = "Rimuovi"
    let settingsHooksOff = "Non installati — tutto viene letto dallo schermo"
    let settingsHooksOn = "Installati — nessuna sessione si è ancora fatta sentire"
    let settingsHooksLive = "Installati, e le sessioni si fanno sentire"
    let settingsStateHook = "Quando una sessione cambia stato"
    let settingsStateHookHint = "Ogni volta che una sessione si mette a lavorare, finisce o ti chiede qualcosa, Clawdline esegue questo: il tuo programma, con i dettagli nel suo ambiente. Si scrive nel file di configurazione e non qui perché è un argv e non una riga di comando — un percorso con uno spazio dentro deve restare un percorso solo."
    let settingsRemote = "Accesso remoto"
    let settingsRemoteServe = "Lascia che un browser o il tuo telefono vedano le tue sessioni"
    let settingsRemoteHint = "Spento, niente fuori da questo Mac arriva da nessuna parte. Acceso, l'elenco delle sessioni viene servito su 127.0.0.1: per un browser qui, per un telefono in fondo a un tunnel, per uno script. Quello che consegna sono nomi di repository, branch e titoli delle attività, ed è per questo che resta spento finché non dici il contrario."
    let settingsRemoteDevices = "Dispositivi abbinati"
    let settingsRemoteNoDevices = "Nessuno per ora — fuori da questo Mac nessuno può leggere niente"
    let settingsRemoteRevokeAll = "Disconnetti tutto"
    let settingsRemoteOpen = "Apri nel browser"
    let pairingIgnore = "Ignora"
    func pairingAsks(_ device: String) -> String { "\(device) vuole abbinarsi a questo Mac" }
    func pairingCode(_ code: String) -> String {
        """
        Digita questo codice su quel dispositivo:

        \(code)

        Vale due minuti. Se non l'hai appena chiesto tu, ignoralo — senza questo codice chi \
        ha chiesto non può arrivare in fondo.
        """
    }
    let settingsTunnel = "Raggiungi questo Mac da ovunque"
    let settingsTunnelQuick = "Un indirizzo generato"
    let settingsTunnelNamed = "Il mio dominio"
    let settingsTunnelHostname = "Nome host"
    let settingsTunnelHint = "Apre una connessione in uscita attraverso cloudflared — nessun port forwarding, niente in ascolto sulla tua rete. Non parte finché non c'è un dispositivo abbinato, perché dietro al tunnel c'è il nome di ogni repository e il titolo di ogni attività su questo Mac."
    let settingsRemoteWrite = "Lascia che un dispositivo abbinato scriva in una sessione"
    let settingsRemoteWriteHint = "Spento, un dispositivo abbinato può solo leggere. Acceso, può mandare testo dentro una sessione e avviarne di nuove — e questo esegue codice su questo Mac, perché è quello che fa Claude Code. È una decisione diversa da quella sopra, quindi è un interruttore a parte."
    let settingsRemotePhone = "Abbina un telefono…"
    let settingsRemotePhoneHint = "Mostra un codice da inquadrare. Porta con sé una chiave tutta sua: una fotografia di quel codice è un dispositivo che vedi in questo elenco e che puoi togliere di nuovo — non la chiave di questo Mac."
    let pairingScanTitle = "Inquadra questo con il telefono"
    let pushWaiting = "aspetta una risposta"
    let pushTest = "Notifica di prova. È tutto collegato."
    let pushFinished = "ha finito un lavoro lungo"
    let pushDeployOk = "il deploy è andato bene"
    let pushDeployFail = "il deploy è fallito"
    let settingsPushFinish = "Avvisa quando finisce un lavoro lungo"
    let settingsPushFinishHint = "Solo oltre i due minuti."
    let settingsPushDeploy = "Avvisa quando finisce un deploy"
    let settingsPushDeployHint = "Sia se va bene sia se fallisce."
    let settingsOrchestrator = "Affidare lavoro"
    let settingsOrchestratorEnabled = "Lascia che una sessione affidi lavoro a un'altra"
    let settingsOrchestratorEnabledHint = "Una sessione con la skill clawdline può aprire una scheda, scriverci dentro le istruzioni e sapere quando il lavoro è finito. Spento, ogni richiesta viene rifiutata; nulla di ciò che sta già girando viene fermato."
    let settingsOrchestratorMax = "Sessioni figlie insieme"
    let settingsOrchestratorMaxHint = "Tre di base. Ognuna è una scheda del terminale con un assistente che ci lavora dentro."
    let settingsOrchestratorNotify = "Avvisa la sessione che ha chiesto"
    let settingsOrchestratorNotifyHint = "Una riga scritta lì dentro quando il compito finisce."
    let settingsOrchestratorClose = "Quando una sessione figlia riferisce"
    let settingsOrchestratorCloseHint = "La sua scheda viene chiusa dopo che ha riferito; quella di una scaduta resta lì, da leggere."
    let settingsOrchestratorCloseNow = "Chiudere subito la scheda"
    let settingsOrchestratorCloseLinger = "Chiuderla dopo tre minuti"
    let settingsOrchestratorCloseKeep = "Lasciarla aperta"
    func childAnnounce(_ title: String) -> String { "Incarico da Clawdline ricevuto: \(title) — comincio subito." }
    func settingsSeconds(_ value: Double) -> String { String(format: "%.1f s", value) }

    let webConnLive = "in diretta"
    let webConnConnecting = "connessione"
    let webConnRetrying = "riprovo tra {n} s"
    let webConnOffline = "non connesso"
    let webConnLocked = "non abbinato"
    let webConnTipLive = "In diretta dall'app"
    let webConnTipLocked = "Questo browser non è stato abbinato al Mac"
    let webConnTipDown = "Non connesso — fai clic per riprovare"

    let webCountWorking = "{n} in corso"
    let webCountWaiting = "{n} in attesa"
    let webCountUnreadable = "{n} illeggibili"
    let webCountQuietOne = "{n} sessione, tutto tranquillo"
    let webCountQuietMany = "{n} sessioni, tutto tranquillo"
    let webCountNone = "nessuna sessione"

    let webFilterPlaceholder = "Filtra per attività, progetto o tty"
    let webFilterLabel = "Filtra le sessioni"
    let webListLabel = "Sessioni di Claude Code"
    let webPull = "Tira per aggiornare"
    let webPullRelease = "Lascia per aggiornare"
    let webPullBusy = "Aggiornamento…"
    let webEmptyFilterTitle = "Niente corrisponde a “{q}”"
    let webEmptyFilterHint = "Esc cancella il filtro"
    let webEmptyLockedTitle = "Questo dispositivo non è abbinato"
    let webEmptyLockedHint = "L'app ha risposto 401 — abbinalo da Clawdline sul Mac"
    let webEmptyNoneHint = "Avviane una in un terminale e comparirà qui"
    let webEmptyWaitTitle = "In attesa dell'app"
    let webEmptyWaitHint = "Sullo stream non è ancora arrivato nulla"
    let webStateUnreadable = "schermo illeggibile"
    let webStateWorking = "in corso"

    let webBack = "Sessioni"
    let webBackLabel = "Torna all'elenco delle sessioni"
    let webNoSessionOpen = "Nessuna sessione aperta"
    let webOrderTip = "Inverti la trascrizione (r)"
    let webShowOnMac = "Mostra sul Mac"
    let webShowOnMacTip = "Porta in primo piano sul Mac il terminale di questa sessione"
    let webShowOnMacOff = "Il server dice write: false — non si può ancora mandare niente"
    let webShowOnMacAsked = "Ho chiesto al Mac di portarlo in primo piano"
    let webSessionActions = "Azioni della sessione"
    let webSessionGit = "Modifiche Git"
    let webGitTitle = "Modifiche Git"
    let webGitClean = "Albero di lavoro pulito"
    let webGitNotRepo = "Non è un repository Git"
    let webGitFailed = "Impossibile leggere le modifiche Git"
    let webGitRefresh = "Aggiorna"
    let webGitClose = "Chiudi"
    let webGitStaged = "In staging"
    let webGitUnstaged = "Non in staging"
    let webGitUntracked = "Non tracciato"
    let webGitConflict = "Conflitto"
    let webEndSession = "Chiudi sessione"
    let webConfirmActionTitle = "Eseguire {action}?"
    let webConfirmActionSay = "Questo invia {action} alla sessione attuale."
    let webConfirmEndTitle = "Chiudere questa sessione?"
    let webConfirmEndSay = "L’assistente uscirà, poi la sua scheda del terminale verrà chiusa."
    let webClosing = "Chiusura…"
    let webCancel = "Annulla"
    let webConfirm = "Conferma"
    let webPickSession = "Scegli una sessione a sinistra."
    let webReading = "Lettura…"
    let webLoading = "Caricamento…"
    let webTranscriptFailed = "Non è stato possibile leggere la trascrizione"
    let webWhoYou = "tu"
    let webWhoTool = "strumento"
    let webPending = "In attesa del Mac…"
    let webAttachedImage = "{n} immagine allegata"
    let webAttachedImages = "{n} immagini allegate"
    let webSteps = "{n} passaggi"
    let webJustNow = "adesso"
    let webMinutesAgo = "{n} min fa"

    let webSend = "Invia"
    let webAttach = "Allega un'immagine"
    let webRemoveShot = "Togli {name}"
    let webWriteOpen = "Apri una sessione per scriverci."
    let webWriteOff = "*L'invio è spento* — il server dice `write: false`. La casella è collegata; si accende da sola quando quello cambia."
    let webShotsOnlyPictures = "Con un messaggio possono partire solo immagini"
    let webShotsTooMany = "Un messaggio può portare al massimo {n} immagini"
    let webShotTooBig = "Quell'immagine è troppo grande da mandare, anche ridotta"
    let webShotsTooBig = "Quelle immagini sono troppo grandi per partire insieme"
    let webShotUnreadable = "Non è stato possibile leggere quell'immagine"
    let webShotNeedsSession = "Apri una sessione per mandarle un'immagine"

    let webHintMove = "scorri"
    let webHintOpen = "apri"
    let webHintFilter = "filtra"
    let webHintPane = "riquadro"

    let webKeysLabel = "Scorciatoie da tastiera"
    let webKeysTitle = "Tastiera"
    let webKeysMove = "Scorri l'elenco — `j` e `k` fanno lo stesso"
    let webKeysOpen = "Apri la sessione selezionata"
    let webKeysFilter = "Filtra l'elenco"
    let webKeysEscape = "Cancella il filtro, poi torna indietro"
    let webKeysList = "Vai all'elenco delle sessioni"
    let webKeysPane = "Mostra o nascondi la trascrizione"
    let webKeysEnds = "Inizio o fine della trascrizione"
    let webKeysReverse = "Inverti l'ordine della trascrizione"
    let webKeysThis = "Questa scheda"
    let webKeysFoot = "Quello che scrivi in una casella di testo resta nella casella — le scorciatoie si fanno da parte mentre scrivi."

    let webDoorLabel = "Abbina questo browser"
    let webDoorAskLede = "Questo browser non è ancora stato fatto entrare."
    let webDoorAskFine = "Chiedi di abbinarti e un codice di sei cifre compare *sul Mac* — di proposito non è nella risposta a questa pagina. Solo chi è davanti a quella macchina può arrivare in fondo, ed è proprio questo il punto, non l'ostacolo."
    let webDoorName = "Chiama questo dispositivo"
    let webDoorAsk = "Chiedi di abbinarti"
    let webDoorToPassword = "Accedi invece con una password"
    let webDoorCodeLede = "Guarda il Mac."
    let webDoorCodeFine = "Clawdline mostra sei cifre per altri {left}. Digitale qui."
    let webDoorTwoMinutes = "due minuti"
    let webDoorDigit = "Cifra {n}"
    let webDoorConfirm = "Abbina questo dispositivo"
    let webDoorRestart = "Ricomincia"
    let webDoorPasswordLede = "Accedi con la password."
    let webDoorPasswordFine = "Quella impostata in Clawdline sul Mac, in Impostazioni → Accesso remoto. Se non ne è stata impostata nessuna, si entra abbinandosi."
    let webDoorPassword = "Password"
    let webDoorPasswordGo = "Accedi"
    let webDoorToPair = "Usa invece un codice di abbinamento"
    let webDoorAsking = "Chiedo al Mac…"
    let webDoorAskFailed = "Non è stato possibile chiedere al Mac."
    let webDoorRateLimited = "Ogni richiesta fa comparire un avviso sul Mac, perciò se ne possono fare solo tre ogni dieci minuti."
    let webDoorSixDigits = "Sei cifre."
    let webDoorChecking = "Controllo…"
    let webDoorFinished = "Questo abbinamento è chiuso — cinque codici sbagliati. Richiedilo quando sei davanti al Mac."
    let webDoorWrongCode = "Quel codice non è giusto."
    let webDoorNeedPassword = "Prima la password."
    let webDoorWrongPassword = "Quella non è la password."
    let webDoorExpired = "Quel codice è scaduto. Richiedilo e sul Mac ne compare uno nuovo."
    let webDoorPaired = "Abbinato — questo browser è dentro"

    let webOffline = "Non ho raggiunto Clawdline. È ancora in esecuzione sul Mac?"
    let webNotJSON = "Il server ha mandato qualcosa che non è JSON"
    let webRequestFailed = "Richiesta non riuscita"

    let webNotifyGo = "Avvisami"
    let webNotifyAsking = "Chiedo…"
    let webNotifyStop = "Ferma"
    let webNotifyStopping = "Sto fermando…"
    let webNotifyOff = "quando una sessione aspetta una risposta"
    let webNotifyOn = "Questo dispositivo è iscritto. Di cosa viene avvisato si decide sul Mac."
    let webNotifyBlocked = "Le notifiche sono bloccate per questo sito. Quell'interruttore sta nelle impostazioni del browser, non qui."
    let webNotifyUnsupported = "Questo browser non sa mostrare notifiche."
    let webNotifyHomeScreen = "Aggiungi clawdline alla schermata Home e aprilo da lì — iOS manda notifiche solo a un'app che abita lì."
    let webNotifyOnFailed = "Non è stato possibile attivare le notifiche"
    let webNotifyOffFailed = "Non è stato possibile disattivare le notifiche"

    let webSettings = "Impostazioni"
    let webSettingsNotify = "Notifiche"
    let webSettingsAssistantIcons = "Icone dell’assistente"
    let webSettingsAssistantIconsSay = "Mostra il simbolo di Claude o Codex prima del nome nella conversazione."
    let webSettingsAssistantIconsShow = "Mostra icone"
    let webSettingsVersion = "Versione {v}"
    let webClose = "Chiudi"
    let webNotifySheetOff = "A questo dispositivo non viene detto quando una sessione aspetta."
    let webNotifyTest = "Manda una prova"
    let webNotifyTestSent = "Mandata — tra un attimo dovrebbe arrivare su questo dispositivo."
    let webNotifyTestNone = "Il Mac non ha nessuna iscrizione per questo dispositivo. Disattiva e riattiva le notifiche, e questo browser ne registrerà una nuova."
    let webNotifyTestFailed = "Non è stato possibile mandare una notifica di prova"
    let webSending = "Invio…"
    let webSendTip = "Invio manda · Maiusc-Invio va a capo"
    let webStart = "Avvia una sessione"
    let webStartLabel = "Avvia una sessione in un progetto"
    let webStartPick = "Dove deve partire?"
    let webStartWith = "Con quale farla partire?"
    let webStartEmpty = "Ancora nessun posto da cui partire. Fai girare Claude Code una volta sul Mac e comparirà qui."
    let webStartFilter = "Filtra i progetti"
    let webStarting = "Apro una scheda…"
    let webStartWaiting = "Avviata. Sta per comparire…"
    let webStartSlow = "La scheda è aperta, ma la sessione non si è fatta sentire. Dai un'occhiata al Mac."
    let webStartFailed = "Non è stato possibile avviarla."
    let webStartGone = "Quel progetto non è più sul Mac."
    let webStartTerminalClosed = "{app} non è in esecuzione sul Mac. Aprilo lì e riprova."
    let webStartTerminalUnsupported = "Da qui non si può avviare una sessione in {app}. Fai girare tmux lì dentro e funziona."
    let webStartOff = "L'avvio delle sessioni è spento. Si accende da Impostazioni → Accesso remoto sul Mac."
    let webLinks = "Link"
    let webLinksTip = "Dove si può aprire questo progetto"
    let webLinksPick = "Tutto quello di cui questo progetto ha un indirizzo."
    let webLinksEmpty = "Questo progetto non ha niente con un indirizzo — nessun sito, nessun deploy, e nessun server acceso."
    let webLinksFailed = "Non è stato possibile leggere i link di questo progetto."
    let webLinksLocal = "Solo sulla rete del Mac. Da qui non si apre."
    let webLinksFile = "Un file sul Mac. Si apre lì, non in questo browser."
    let webLinksCopy = "Copia il percorso"
    let webLinksCopied = "Copiato."
    let webLinksCopyFailed = "Questo browser non ha lasciato che la pagina lo copiasse."
    let webLinkOk = "ok"
    let webLinkFail = "errore"
    let webLinkDown = "spento"
    let webLinkRunning = "in corso"
    let webSessionInfo = "Info sessione"
    let webInfoTitle = "Su questa sessione"
    let webInfoSession = "Questa sessione"
    let webInfoAssistant = "Assistente"
    let webInfoModel = "Modello"
    let webInfoSessionId = "ID sessione"
    let webInfoDirectory = "Cartella"
    let webInfoRunningFor = "In corso da"
    let webInfoUsage = "Consumo di token"
    let webInfoInput = "In ingresso"
    let webInfoOutput = "In uscita"
    let webInfoCacheRead = "Cache letta"
    let webInfoCacheWrite = "Cache scritta"
    let webInfoTotal = "Totale"
    let webInfoCost = "Costo stimato"
    let webInfoNoUsage = "Nessuna trascrizione trovata per questa sessione, per ora."
    let webInfoLimits = "Limiti del piano"
    let webInfoLimitHit = "limite raggiunto"
    let webInfoResets = "si azzera {when}"
    let webInfoUnknown = "sconosciuto"
    let webInfoFiles = "File"
    let webInfoBranch = "Branch"
    let webInfoStaged = "In stage"
    let webInfoUnstaged = "Modificati"
    let webInfoUntracked = "Non tracciati"
    let webInfoConflict = "Conflitti"
    let webInfoClean = "Niente da committare."
    let webInfoNotRepo = "Non è un repository git."
    let webInfoDeploy = "Ultimo deploy"
    let webInfoNoDeploy = "Nessun deploy registrato per questo progetto."
    let webInfoFailed = "Non è stato possibile leggere le info di questa sessione."
    let webInfoRefresh = "Aggiorna"
    let webInfoTokens = "token"
    let webInfoSwitchModel = "Cambia modello"
    let webInfoModelOther = "un altro modello…"
    let webInfoModelSent = "/model {model} inviato. La scheda lo mostrerà dopo la prossima risposta."
    let webInfoModelBusy = "Il cambio aspetta che la sessione sia inattiva."
    let webInfoLimitsClaude = "Claude Code annota una finestra solo quando è esaurita; fino ad allora non si sa nulla."
    let webInfoCopied = "Id della sessione copiato."
    let webInfoAsOf = "alle {when}"
    let webInfoWhyUnknown = "Perché è sconosciuto, e come avere i numeri"
    let webSettingsOrder = "Trascrizione"
    let webSettingsOrderSay = "Da che capo iniziare a leggere una trascrizione. Vale per tutte le sessioni, e da tastiera `r` fa lo stesso."
    let webAskLabel = "ha chiesto"
    let webAskAny = "Quante ne vuoi, di queste"
    let webWaitingTitle = "Questa sessione aspetta una risposta"
    let webWaitingSay = "Claude Code sta mostrando un menu sul Mac. Clawdline da qui un menu non riesce ancora a leggerlo, quindi le scelte stanno solo su quello schermo."
    let webWaitingSend = "*Mandare da qui non scrive la tua risposta nel menu* — conferma la voce che nel menu è evidenziata, che quasi mai è quella che intendevi. A questa rispondi sul Mac."
    let webMenuSay = "Tocca una risposta e va dritta nella sessione."
    let webMenuHighlighted = "evidenziata"
    let webMenuSent = "Risposta inviata."
    let webAgents = "Agenti in secondo piano"
    let webAgentsCount = "{n} in corso"
    let webAgentDone = "fatto"
    let webAgentFailed = "fallito"
    let agentRunning = "in corso"
    let agentTools = "{n} strumenti"
    let agentEmpty = "Questo agente non ha ancora scritto nulla."
    let agentBack = "Sessione"
    let webAgentOpen = "Vedi cosa ha fatto questo agente"
    let webTaskRoot = "Padre"
    let webTaskChild = "Figlio"
    let webTaskTasks = "Attività"
    let webTaskDone = "fatto"
    let webTaskFailed = "fallito"
    let webTaskRunning = "in corso"
    let webStale = "Clawdline è stato ricompilato sul Mac. Questa pagina è quella di prima."
    let webStaleGo = "Ricarica"

    let menuOpen = "Apri la barra"
    let menuReveal = "Vai alla scheda di destinazione"
    let menuMascot = "Mascotte"
    let menuLogin = "Apri all'accesso"
    let menuEditConfig = "Impostazioni…"
    let menuReload = "Ricarica configurazione"
    let menuQuit = "Esci da Clawdline"
    let menuNoTarget = "(non ancora rilevato)"

    func hotkeyFailedTitle(_ combo: String) -> String { "Non è stato possibile registrare \(combo)" }
    func hotkeyFailedBody(_ configPath: String) -> String {
        """
        Con ogni probabilità la usa già un'altra app — Spotlight, un commutatore di \
        tastiera, BetterTouchTool e simili.

        Scegline un'altra: modifica "hotkey" in \(configPath), poi scegli \
        "Ricarica configurazione" dalla barra dei menu.

        Fino ad allora, il ✳ nella barra dei menu apre comunque la barra.
        """
    }
    let loginFailed = "Non è stato possibile impostare l'apertura all'accesso"
}
