import Foundation

/// One entry for both sides of the Atlantic. The interface words here do not differ enough to
/// justify two translations that would then drift apart; where they nearly do — tela / ecrã —
/// the Brazilian form wins, because that is where most of the readers are.
struct Portuguese: Copy {
    let placeholder = "Escreva para o Claude Code…"

    let hintSend = "enviar"
    let hintNewline = "nova linha"
    let hintSwitch = "trocar"
    let hintList = "lista"
    let hintMascot = "mascote"
    let hintOutput = "saída"
    let hintFullscreen = "tela cheia"
    let hintKeys = "teclas"
    let hintTextSize = "tamanho"
    let hintOrder = "inverter"
    let hintVoice = "ditar"
    func voiceListening(onDevice: Bool) -> String {
        onDevice ? "Ouvindo neste Mac — pressione de novo para parar"
                 : "Ouvindo — este idioma é transcrito pela Apple, não neste Mac"
    }
    let voiceNoPermission = "O ditado precisa de acesso ao microfone e ao reconhecimento de fala"
    let voiceUnavailable = "O ditado não está disponível agora"
    func voiceTranscribing(seconds: Double) -> String {
        String(format: "O Whisper está relendo… %.1f s", seconds)
    }
    let whisperMissing = "O Whisper não está instalado — veja docs/whisper.md"
    let whisperNothingHeard = "Não ouvi nada"
    func dictationStatus(_ status: Whisper.Status) -> String {
        switch status {
        case .ready(let model): return "Ditado: Apple e depois Whisper (\(model))"
        case .noBinary: return "Ditado: só Apple — falta o whisper-cli"
        case .noModel: return "Ditado: só Apple — o whisper-cli está aí, falta o modelo"
        }
    }
    func voiceListeningWhisper() -> String {
        "Ouvindo — o Whisper dá outra olhada quando você parar"
    }

    let scanning = "Procurando…"
    let noSession = "Nenhuma sessão do Claude Code encontrada"
    let nothingToSend = "Não há para onde enviar — abra o Claude Code num terminal primeiro"
    let sendFailed = "Não foi possível enviar"
    let itermSilent = "O iTerm2 não respondeu"
    let scriptMissing = "Falta o iterm.js — pacote do app corrompido?"
    let cannotList = "Não foi possível ler as sessões do iTerm2"
    let noOutput = "Ainda não há nada para ler nesta sessão."
    func outputSize(_ pt: Int) -> String { "Texto da saída \(pt) pt — ⌘J para ver" }
    func foldedTools(_ count: Int) -> String { "\(count) passos" }
    func outputOrder(newestFirst: Bool) -> String {
        newestFirst ? "Mais recentes primeiro" : "Mais antigos primeiro"
    }
    func backlogNow(_ count: Int) -> String { "agora \(count)" }
    func dropped(_ count: Int) -> String {
        count == 1 ? "Caminho adicionado — o Claude Code lê" : "\(count) caminhos adicionados"
    }
    func stackConfirm(_ command: String) -> String { "Prima novamente para executar:  \(command)" }
    let hintStacks = "servidores"
    func stackTip(up: Int, total: Int) -> String { "\(up) de \(total) servidores ativos — ⌘S para a lista" }
    let stackTipUnknown = "Este projeto tem servidores; o seu comando de estado ainda não é fiável — ⌘S"
    let stackUntrusted = "sem aprovação"
    let stackExit = "saída"
    let stackActionStart = "iniciar"
    let stackActionRestart = "reiniciar"
    let stackActionStop = "parar"
    let stackActionLogs = "registo"
    let stackLogAll = "todos"
    let stackLogBack = "transcrição"
    let stackActionAllow = "permitir"
    let stackActionAgain = "de novo"
    func sessionTip(index: Int, total: Int) -> String { "Sessão \(index) de \(total) — ⌘K para mudar" }
    let sessionWaiting = "aguarda a sua resposta"
    let sessionAgents = "{n} em segundo plano"
    let islandDone = "concluído"
    let islandAllSessions = "Todas as sessões…"
    func statusWaiting(_ labels: [String]) -> String {
        labels.count == 1 ? "\(labels[0]) aguarda a sua resposta"
                          : "\(labels.count) sessões aguardam a sua resposta"
    }
    func statusWorking(_ count: Int) -> String { "\(count) em execução" }

    let settingsTitle = "Definições do Clawdline"
    let settingsGeneral = "Geral"
    let settingsBar = "A barra"
    let settingsReading = "Leitura"
    let settingsVoice = "Ditado"
    let settingsHotkey = "Atalho"
    let settingsRecording = "Prima teclas…"
    let settingsScope = "Ativo em"
    let settingsScopeGlobal = "Em todas as apps"
    let settingsScopeHint = "Vazio significa em todo lugar, então tirar o último liga o interruptor de cima — e desligá-lo de novo traz a lista de volta. O arquivo de configuração guarda isto como bundle ids, e uma lista editada à mão continua funcionando."
    let settingsScopeAdd = "Adicionar um app…"
    let settingsScopeChoose = "Escolher um app…"
    let settingsScopeRunning = "Abertos agora"
    let settingsScopeRemove = "Remover"
    let settingsLanguage = "Idioma"
    let settingsReopen = "A barra vai e volta com o terminal"
    let settingsReopenHint = "Sair do terminal guarda a barra, e voltar para ele traz a barra de volta. Esc é o que quer dizer que você terminou com ela."
    let settingsFollow = "O terminal mostra aquilo para onde a barra está apontada"
    let settingsFollowHint = "Ele seleciona a aba daquela sessão. Não traz o terminal para a frente: se trouxesse, cada toque em Tab tiraria o teclado da caixa em que você está escrevendo."
    let settingsCodexAutoName = "Nomear novas sessões Codex"
    let settingsCodexAutoNameHint = "Executa um pequeno turno Codex Luna para cada sessão sem nome. Usa o primeiro pedido, consome uso do Codex e nunca substitui um nome escolhido por você."
    let settingsNotch = "Viver no entalhe"
    let settingsNotchHint = "Uma personagem na caixa da câmara. Desligado é desligado: nada é desenhado nem é criada janela."
    let settingsPosition = "Altura no ecrã"
    let settingsWidth = "Largura"
    let settingsOpacity = "Opacidade do cartão"
    let settingsShow = "Mostrar"
    let settingsPaneHeight = "Altura do painel"
    let settingsTextSize = "Tamanho do texto"
    let settingsPaneFont = "Tipo de letra do painel"
    let settingsBlur = "Desfoque atrás"
    let settingsNewestFirst = "Mais recentes primeiro"
    let settingsEngine = "Reconhecimento"
    let settingsSettle = "Uma pausa termina a frase"
    let settingsStop = "Um silêncio termina a sessão"
    let settingsAuto = "Automático"
    let settingsTranscript = "Transcrição"
    let settingsTerminal = "Terminal"
    let settingsOff = "Desligado"
    let settingsHooks = "Hooks do Claude Code"
    let settingsHooksHint = "Com eles instalados, o Claude Code avisa no instante em que um turno começa, termina ou espera por uma resposta, em vez de o Clawdline descobrir na verificação seguinte. Tudo continua a ser lido do ecrã; isto só decide com que rapidez."
    let settingsHooksInstall = "Instalar"
    let settingsHooksRemove = "Remover"
    let settingsHooksOff = "Não instalados — tudo é lido do ecrã"
    let settingsHooksOn = "Instalados — nenhuma sessão avisou ainda"
    let settingsHooksLive = "Instalados, e as sessões estão a avisar"
    let settingsStateHook = "Quando uma sessão muda de estado"
    let settingsStateHookHint = "Sempre que uma sessão começa a trabalhar, termina ou pergunta algo a você, o Clawdline executa isto: o seu próprio programa, com os detalhes no ambiente dele. Fica no arquivo de configuração e não aqui porque é um argv e não uma linha de comando — um caminho com espaço tem que continuar sendo um caminho só."
    let settingsRemote = "Acesso remoto"
    let settingsRemoteServe = "Deixar um navegador ou o seu celular verem as suas sessões"
    let settingsRemoteHint = "Desligado, nada fora deste Mac alcança coisa alguma. Ligado, a lista de sessões é servida em 127.0.0.1: para um navegador daqui, para um celular do outro lado de um túnel, para um script. O que isso entrega são nomes de repositórios, branches e títulos de tarefas, e é por isso que fica desligado até você dizer o contrário."
    let settingsRemoteDevices = "Dispositivos pareados"
    let settingsRemoteNoDevices = "Nenhum ainda — fora deste Mac ninguém consegue ler nada"
    let settingsRemoteRevokeAll = "Desconectar tudo"
    let settingsRemoteOpen = "Abrir no navegador"
    let pairingIgnore = "Ignorar"
    func pairingAsks(_ device: String) -> String { "\(device) quer parear com este Mac" }
    func pairingCode(_ code: String) -> String {
        """
        Digite este código nele:

        \(code)

        Vale por dois minutos. Se não foi você que acabou de pedir, ignore — sem este código, \
        quem pediu não consegue concluir.
        """
    }
    let settingsTunnel = "Chegar a este Mac de qualquer lugar"
    let settingsTunnelQuick = "Um endereço gerado"
    let settingsTunnelNamed = "Meu próprio domínio"
    let settingsTunnelHostname = "Nome do host"
    let settingsTunnelHint = "Abre uma conexão de saída através do cloudflared — sem redirecionamento de portas, nada à escuta na sua rede. Não começa enquanto não houver um dispositivo pareado, porque atrás do túnel está o nome de cada repositório e o título de cada tarefa deste Mac."
    let settingsRemoteWrite = "Deixar um dispositivo pareado escrever numa sessão"
    let settingsRemoteWriteHint = "Desligado, um dispositivo pareado só consegue ler. Ligado, ele pode mandar texto para dentro de uma sessão e abrir sessões novas — o que executa código neste Mac, porque é isso que o Claude Code faz. É uma decisão diferente da de cima, então é um interruptor separado."
    let settingsRemotePhone = "Parear um celular…"
    let settingsRemotePhoneHint = "Mostra um código para escanear. Ele carrega uma chave só dele: uma foto desse código é um dispositivo que você vê nesta lista e pode tirar de novo — não a chave deste Mac."
    let pairingScanTitle = "Escaneie isto com o celular"
    let pushWaiting = "está esperando uma resposta"
    let pushTest = "Notificação de teste. Está tudo ligado."
    let pushFinished = "terminou uma tarefa longa"
    let pushDeployOk = "o deploy deu certo"
    let pushDeployFail = "o deploy falhou"
    let settingsPushFinish = "Avisar quando uma tarefa longa terminar"
    let settingsPushFinishHint = "Só as que passam de dois minutos."
    let settingsPushDeploy = "Avisar quando um deploy terminar"
    let settingsPushDeployHint = "Tanto quando dá certo quanto quando falha."
    let settingsOrchestrator = "Tarefas entre sessões"
    let settingsOrchestratorEnabled = "Deixar uma sessão passar trabalho a outra"
    let settingsOrchestratorEnabledHint = "Uma sessão com a skill clawdline pode abrir um separador, escrever-lhe as instruções e saber quando o trabalho acabou. Desligado, todos os pedidos são recusados; nada do que já está a correr é interrompido."
    let settingsOrchestratorMax = "Sessões filhas ao mesmo tempo"
    let settingsOrchestratorMaxHint = "Três por omissão. Cada uma é um separador do terminal com um assistente a trabalhar lá dentro."
    let settingsOrchestratorNotify = "Avisar a sessão que pediu"
    let settingsOrchestratorNotifyHint = "Uma linha escrita de volta nela quando a tarefa acaba."
    let settingsOrchestratorClose = "Quando uma sessão filha dá notícias"
    let settingsOrchestratorCloseHint = "O separador dela é fechado depois de ela dar notícias; o de uma que esgotou o tempo fica lá para você ler."
    let settingsOrchestratorCloseNow = "Fechar o separador logo"
    let settingsOrchestratorCloseLinger = "Fechá-lo ao fim de três minutos"
    let settingsOrchestratorCloseKeep = "Deixá-lo aberto"
    func childAnnounce(_ title: String) -> String { "Tarefa do Clawdline recebida: \(title) — começo já." }
    func settingsSeconds(_ value: Double) -> String { String(format: "%.1f s", value) }

    let webConnLive = "ao vivo"
    let webConnConnecting = "conectando"
    let webConnRetrying = "tentando em {n}s"
    let webConnOffline = "sem conexão"
    let webConnLocked = "não pareado"
    let webConnTipLive = "Transmitindo do app"
    let webConnTipLocked = "Este navegador não foi pareado com o Mac"
    let webConnTipDown = "Sem conexão — clique para tentar agora"

    let webCountWorking = "{n} rodando"
    let webCountWaiting = "{n} esperando"
    let webCountUnreadable = "{n} ilegíveis"
    let webCountQuietOne = "{n} sessão, tudo quieto"
    let webCountQuietMany = "{n} sessões, tudo quieto"
    let webCountNone = "nenhuma sessão"

    let webFilterPlaceholder = "Filtre por tarefa, projeto ou tty"
    let webFilterLabel = "Filtrar sessões"
    let webListLabel = "Sessões do Claude Code"
    let webPull = "Puxe para atualizar"
    let webPullRelease = "Solte para atualizar"
    let webPullBusy = "Atualizando…"
    let webEmptyFilterTitle = "Nada corresponde a “{q}”"
    let webEmptyFilterHint = "Esc limpa o filtro"
    let webEmptyLockedTitle = "Este dispositivo não está pareado"
    let webEmptyLockedHint = "O app respondeu 401 — pareie pelo Clawdline no Mac"
    let webEmptyNoneHint = "Comece uma num terminal e ela aparece aqui"
    let webEmptyWaitTitle = "Esperando o app"
    let webEmptyWaitHint = "Nada chegou pela conexão ainda"
    let webStateUnreadable = "não deu para ler a tela"
    let webStateWorking = "rodando"

    let webBack = "Sessões"
    let webBackLabel = "Voltar para a lista de sessões"
    let webNoSessionOpen = "Nenhuma sessão aberta"
    let webOrderTip = "Inverter a transcrição (r)"
    let webShowOnMac = "Ver no Mac"
    let webShowOnMacTip = "Traz o terminal desta sessão para a frente no Mac"
    let webShowOnMacOff = "O servidor responde write: false — ainda não dá para enviar nada"
    let webShowOnMacAsked = "Pedimos ao Mac para trazer ele para a frente"
    let webSessionActions = "Ações da sessão"
    let webSessionGit = "Alterações do Git"
    let webGitTitle = "Alterações do Git"
    let webGitClean = "Árvore de trabalho limpa"
    let webGitNotRepo = "Não é um repositório Git"
    let webGitFailed = "Não foi possível ler as alterações do Git"
    let webGitRefresh = "Atualizar"
    let webGitClose = "Fechar"
    let webGitStaged = "Em staging"
    let webGitUnstaged = "Fora do staging"
    let webGitUntracked = "Não rastreado"
    let webGitConflict = "Conflito"
    let webEndSession = "Fechar sessão"
    let webConfirmActionTitle = "Executar {action}?"
    let webConfirmActionSay = "Isso envia {action} para a sessão atual."
    let webConfirmEndTitle = "Fechar esta sessão?"
    let webConfirmEndSay = "O assistente vai sair e depois a aba do terminal será fechada."
    let webClosing = "Fechando…"
    let webCancel = "Cancelar"
    let webConfirm = "Confirmar"
    let webPickSession = "Escolha uma sessão à esquerda."
    let webReading = "Lendo…"
    let webLoading = "Carregando…"
    let webTranscriptFailed = "Não foi possível ler a transcrição"
    let webWhoYou = "você"
    let webWhoTool = "ferramenta"
    let webPending = "Aguardando o Mac…"
    let webAttachedImage = "{n} imagem anexada"
    let webAttachedImages = "{n} imagens anexadas"
    let webSteps = "{n} passos"
    let webJustNow = "agora mesmo"
    let webMinutesAgo = "{n} min atrás"

    let webSend = "Enviar"
    let webAttach = "Anexar uma imagem"
    let webRemoveShot = "Remover {name}"
    let webWriteOpen = "Abra uma sessão para escrever nela."
    let webWriteOff = "*O envio está desligado* — o servidor responde `write: false`. A caixa está ligada; ela se acende sozinha quando isso mudar."
    let webShotsOnlyPictures = "Só imagens podem ir junto com uma mensagem"
    let webShotsTooMany = "Uma mensagem leva no máximo {n} imagens"
    let webShotTooBig = "Essa imagem é grande demais para enviar, mesmo reduzida"
    let webShotsTooBig = "Essas imagens são grandes demais para enviar juntas"
    let webShotUnreadable = "Não foi possível ler essa imagem"
    let webShotNeedsSession = "Abra uma sessão para mandar uma imagem para ela"

    let webHintMove = "mover"
    let webHintOpen = "abrir"
    let webHintFilter = "filtrar"
    let webHintPane = "painel"

    let webKeysLabel = "Atalhos de teclado"
    let webKeysTitle = "Teclado"
    let webKeysMove = "Andar pela lista — `j` e `k` fazem o mesmo"
    let webKeysOpen = "Abrir a sessão selecionada"
    let webKeysFilter = "Filtrar a lista"
    let webKeysEscape = "Limpar o filtro e depois voltar"
    let webKeysList = "Ir para a lista de sessões"
    let webKeysPane = "Mostrar ou esconder a transcrição"
    let webKeysEnds = "Início ou fim da transcrição"
    let webKeysReverse = "Inverter a ordem da transcrição"
    let webKeysThis = "Este cartão"
    let webKeysFoot = "O que você digita numa caixa de texto fica na caixa de texto — os atalhos saem de cena enquanto você escreve."

    let webDoorLabel = "Parear este navegador"
    let webDoorAskLede = "Este navegador ainda não foi liberado."
    let webDoorAskFine = "Peça para parear e um código de seis dígitos aparece *no Mac* — de propósito ele não vem na resposta para esta página. Só quem estiver naquela máquina consegue concluir isso, e é aí que está a segurança, não o incômodo."
    let webDoorName = "Dê um nome a ele"
    let webDoorAsk = "Pedir pareamento"
    let webDoorToPassword = "Entrar com senha"
    let webDoorCodeLede = "Olhe para o Mac."
    let webDoorCodeFine = "O Clawdline está mostrando seis dígitos por {left}. Digite eles aqui."
    let webDoorTwoMinutes = "dois minutos"
    let webDoorDigit = "Dígito {n}"
    let webDoorConfirm = "Parear este dispositivo"
    let webDoorRestart = "Começar de novo"
    let webDoorPasswordLede = "Entre com a senha."
    let webDoorPasswordFine = "A que está definida no Clawdline no Mac, em Definições → Acesso remoto. Se não houver nenhuma, o jeito de entrar é o pareamento."
    let webDoorPassword = "Senha"
    let webDoorPasswordGo = "Entrar"
    let webDoorToPair = "Usar um código de pareamento"
    let webDoorAsking = "Perguntando ao Mac…"
    let webDoorAskFailed = "Não foi possível perguntar ao Mac."
    let webDoorRateLimited = "Cada pedido coloca um aviso no Mac, então são só três a cada dez minutos."
    let webDoorSixDigits = "Seis dígitos."
    let webDoorChecking = "Conferindo…"
    let webDoorFinished = "Esse pareamento acabou — cinco códigos errados. Peça de novo quando estiver no Mac."
    let webDoorWrongCode = "Esse código não confere."
    let webDoorNeedPassword = "A senha, primeiro."
    let webDoorWrongPassword = "Essa não é a senha."
    let webDoorExpired = "Esse código expirou. Peça de novo e um novo aparece no Mac."
    let webDoorPaired = "Pareado — este navegador entrou"

    let webOffline = "Não deu para falar com o Clawdline. Ele ainda está rodando no Mac?"
    let webNotJSON = "O servidor mandou algo que não é JSON"
    let webRequestFailed = "O pedido falhou"

    let webNotifyGo = "Me avise"
    let webNotifyAsking = "Pedindo…"
    let webNotifyStop = "Parar"
    let webNotifyStopping = "Parando…"
    let webNotifyOff = "quando uma sessão estiver esperando uma resposta"
    let webNotifyOn = "Este dispositivo está inscrito. O que ele fica sabendo é decidido no Mac."
    let webNotifyBlocked = "As notificações estão bloqueadas para este site. Esse interruptor fica nas configurações do próprio navegador, não aqui."
    let webNotifyUnsupported = "Este navegador não consegue mostrar notificações."
    let webNotifyHomeScreen = "Adicione o clawdline à tela de início e abra por ali — o iOS só manda notificação para um app que mora lá."
    let webNotifyOnFailed = "Não foi possível ligar as notificações"
    let webNotifyOffFailed = "Não foi possível desligar as notificações"

    let webSettings = "Definições"
    let webSettingsNotify = "Notificações"
    let webSettingsAssistantIcons = "Ícones do assistente"
    let webSettingsAssistantIconsSay = "Mostra a marca do Claude ou Codex antes do nome na conversa."
    let webSettingsAssistantIconsShow = "Mostrar ícones"
    let webSettingsVersion = "Versão {v}"
    let webClose = "Fechar"
    let webNotifySheetOff = "Este dispositivo não é avisado quando uma sessão está esperando."
    let webNotifyTest = "Mandar um teste"
    let webNotifyTestSent = "Enviado — deve chegar neste dispositivo em instantes."
    let webNotifyTestNone = "O Mac não tem inscrição para este dispositivo. Desligue e ligue as notificações de novo, e este navegador registra uma nova."
    let webNotifyTestFailed = "Não foi possível mandar uma notificação de teste"
    let webSending = "Enviando…"
    let webSendTip = "Enter envia · Shift-Enter quebra a linha"
    let webStart = "Nova sessão"
    let webStartLabel = "Começar uma sessão num projeto"
    let webStartPick = "Onde ela deve começar?"
    let webStartWith = "Com qual ela deve começar?"
    let webStartEmpty = "Ainda não há onde começar. Rode o Claude Code uma vez no Mac e ele aparece aqui."
    let webStartFilter = "Filtrar projetos"
    let webStarting = "Abrindo uma aba…"
    let webStartWaiting = "Começou. Esperando ela aparecer…"
    let webStartSlow = "A aba está aberta, mas a sessão não deu sinal. Dê uma olhada no Mac."
    let webStartFailed = "Não deu para começar essa."
    let webStartGone = "Esse projeto não está mais no Mac."
    let webStartTerminalClosed = "O {app} não está aberto no Mac. Abra ele lá e tente de novo."
    let webStartTerminalUnsupported = "Daqui não dá para começar uma sessão no {app}. Rode tmux dentro dele e isso funciona."
    let webStartOff = "Começar sessões está desligado. Em Definições → Acesso remoto, no Mac, dá para ligar."
    let webLinks = "Endereços"
    let webLinksTip = "Onde este projeto pode ser aberto"
    let webLinksPick = "Tudo que tem endereço neste projeto."
    let webLinksEmpty = "Este projeto não tem nada com endereço — nem site, nem deploy, nem servidor rodando."
    let webLinksFailed = "Não foi possível ler os endereços deste projeto."
    let webLinksLocal = "Só na rede do próprio Mac. Daqui não abre."
    let webLinksFile = "Um arquivo no Mac. Ele abre lá, não neste navegador."
    let webLinksCopy = "Copiar o caminho"
    let webLinksCopied = "Copiado."
    let webLinksCopyFailed = "Este navegador não deixou a página copiar isso."
    let webLinkOk = "ok"
    let webLinkFail = "erro"
    let webLinkDown = "parado"
    let webLinkRunning = "rodando"
    let webSessionInfo = "Info da sessão"
    let webInfoTitle = "Sobre esta sessão"
    let webInfoSession = "Esta sessão"
    let webInfoAssistant = "Assistente"
    let webInfoModel = "Modelo"
    let webInfoSessionId = "ID da sessão"
    let webInfoDirectory = "Diretório"
    let webInfoRunningFor = "Rodando há"
    let webInfoUsage = "Uso de tokens"
    let webInfoInput = "Entrada"
    let webInfoOutput = "Saída"
    let webInfoCacheRead = "Cache lido"
    let webInfoCacheWrite = "Cache escrito"
    let webInfoTotal = "Total"
    let webInfoCost = "Custo estimado"
    let webInfoNoUsage = "Ainda não foi encontrada a transcrição desta sessão."
    let webInfoLimits = "Limites do plano"
    let webInfoLimitHit = "limite atingido"
    let webInfoResets = "reinicia {when}"
    let webInfoUnknown = "desconhecido"
    let webInfoFiles = "Arquivos"
    let webInfoBranch = "Branch"
    let webInfoStaged = "Preparados"
    let webInfoUnstaged = "Modificados"
    let webInfoUntracked = "Não rastreados"
    let webInfoConflict = "Conflitos"
    let webInfoClean = "Nada sem commit."
    let webInfoNotRepo = "Não é um repositório git."
    let webInfoDeploy = "Último deploy"
    let webInfoNoDeploy = "Este projeto não tem nenhum deploy registrado."
    let webInfoFailed = "Não foi possível ler as informações desta sessão."
    let webInfoRefresh = "Atualizar"
    let webInfoTokens = "tokens"
    let webInfoSwitchModel = "Trocar de modelo"
    let webInfoModelOther = "outro modelo…"
    let webInfoModelSent = "/model {model} enviado. Confirmando…"
    let webInfoModelBusy = "A troca espera a sessão ficar ociosa."
    let webInfoLimitsClaude = "O Claude Code só anota uma janela quando ela se esgota; até lá, nada se sabe."
    let webInfoCopied = "Id da sessão copiado."
    let webInfoAsOf = "às {when}"
    let webInfoWhyUnknown = "Por que é desconhecido, e como obter os números"
    let webSettingsOrder = "Transcrição"
    let webSettingsOrderSay = "De que ponta começar a ler uma transcrição. Vale para todas as sessões, e no teclado `r` faz a mesma coisa."
    let webAskLabel = "perguntou"
    let webAskAny = "Quantas você quiser destas"
    let webWaitingTitle = "Esta sessão está esperando uma resposta"
    let webWaitingSay = "O Claude Code está mostrando um menu no Mac. O Clawdline ainda não consegue ler um menu daqui, então as opções estão só naquela tela."
    let webWaitingSend = "*Enviar daqui não digita a sua resposta no menu* — confirma a opção que estiver destacada no menu, que quase nunca é a que você queria. Esta aqui, responda no Mac."
    let webMenuSay = "Toque numa resposta e ela vai direto para a sessão."
    let webMenuHighlighted = "destacada"
    let webMenuSent = "Resposta enviada."
    let webAgents = "Agentes em segundo plano"
    let webAgentsCount = "{n} em execução"
    let webAgentDone = "concluído"
    let webAgentFailed = "falhou"
    let agentRunning = "em execução"
    let agentTools = "{n} ferramentas"
    let agentEmpty = "Este agente ainda não escreveu nada."
    let agentBack = "Sessão"
    let webAgentOpen = "Ver o que este agente fez"
    let webTaskRoot = "Pai"
    let webTaskChild = "Filho"
    let webTaskTasks = "Tarefas"
    let webTaskDone = "concluído"
    let webTaskFailed = "falhou"
    let webTaskRunning = "em execução"
    let webStale = "O Clawdline foi recompilado no Mac. Esta página é a antiga."
    let webStaleGo = "Recarregar"

    let menuOpen = "Abrir a barra"
    let menuReveal = "Ir para a aba de destino"
    let menuMascot = "Mascote"
    let menuLogin = "Abrir ao fazer login"
    let menuEditConfig = "Definições…"
    let menuReload = "Recarregar configuração"
    let menuQuit = "Sair do Clawdline"
    let menuNoTarget = "(ainda não detectado)"

    func hotkeyFailedTitle(_ combo: String) -> String { "Não foi possível registrar \(combo)" }
    func hotkeyFailedBody(_ configPath: String) -> String {
        """
        Provavelmente outro app já usa esse atalho — Spotlight, troca de teclado, \
        BetterTouchTool e afins.

        Escolha outro: edite "hotkey" em \(configPath) e depois escolha \
        "Recarregar configuração" na barra de menus.

        Até lá, o ✳ na barra de menus continua abrindo a barra.
        """
    }
    let loginFailed = "Não foi possível configurar a abertura ao fazer login"
}
