import Foundation

struct Russian: Copy {
    let placeholder = "Сообщение для Claude Code…"

    let hintSend = "отправить"
    let hintNewline = "новая строка"
    let hintSwitch = "переключить"
    let hintList = "список"
    let hintMascot = "маскот"
    let hintOutput = "вывод"
    let hintFullscreen = "во весь экран"
    let hintKeys = "клавиши"
    let hintTextSize = "размер"
    let hintOrder = "обратный порядок"
    let hintVoice = "диктовка"
    func voiceListening(onDevice: Bool) -> String {
        onDevice ? "Слушает на этом Mac — нажмите ещё раз, чтобы остановить"
                 : "Слушает — этот язык распознаёт Apple, а не этот Mac"
    }
    let voiceNoPermission = "Диктовке нужен доступ к микрофону и распознаванию речи"
    let voiceUnavailable = "Диктовка сейчас недоступна"
    func voiceTranscribing(seconds: Double) -> String {
        String(format: "Whisper перечитывает… %.1f с", seconds)
    }
    let whisperMissing = "Whisper не установлен — см. docs/whisper.md"
    let whisperNothingHeard = "Ничего не услышал"
    func dictationStatus(_ status: Whisper.Status) -> String {
        switch status {
        case .ready(let model): return "Диктовка: Apple, затем Whisper (\(model))"
        case .noBinary: return "Диктовка: только Apple — нет whisper-cli"
        case .noModel: return "Диктовка: только Apple — whisper-cli есть, модели нет"
        }
    }
    func voiceListeningWhisper() -> String {
        "Слушает — когда вы закончите, Whisper перечитает"
    }

    let scanning = "Поиск…"
    let noSession = "Сессия Claude Code не найдена"
    let nothingToSend = "Некуда отправлять — сначала запустите Claude Code в терминале"
    let sendFailed = "Не удалось отправить"
    let itermSilent = "iTerm2 не ответил"
    let itermBusy = "iTerm2 ждёт ответа на диалог — закройте его на Mac"
    let scriptMissing = "Нет iterm.js — повреждённый бандл приложения?"
    let cannotList = "Не удалось прочитать сессии iTerm2"
    let noOutput = "В этой сессии пока нечего читать."
    func outputSize(_ pt: Int) -> String { "Размер текста вывода \(pt) pt — ⌘J, чтобы посмотреть" }
    func foldedTools(_ count: Int) -> String { "шагов: \(count)" }
    func outputOrder(newestFirst: Bool) -> String {
        newestFirst ? "Сначала новые" : "Сначала старые"
    }
    func backlogNow(_ count: Int) -> String { "сейчас \(count)" }
    func dropped(_ count: Int) -> String {
        count == 1 ? "Путь добавлен — Claude Code его прочитает" : "Добавлено путей: \(count)"
    }
    func stackConfirm(_ command: String) -> String { "Нажмите ещё раз, чтобы выполнить:  \(command)" }
    let hintStacks = "серверы"
    func stackTip(up: Int, total: Int) -> String { "Запущено \(up) из \(total) серверов — ⌘S для списка" }
    let stackTipUnknown = "У проекта есть серверы, но его команда состояния ещё не доверена — ⌘S"
    let stackUntrusted = "не доверено"
    let stackExit = "код выхода"
    let stackActionStart = "запустить"
    let stackActionRestart = "перезапуск"
    let stackActionStop = "остановить"
    let stackActionLogs = "журнал"
    let stackLogAll = "все"
    let stackLogBack = "расшифровка"
    let stackActionAllow = "разрешить"
    let stackActionAgain = "ещё раз"
    func sessionTip(index: Int, total: Int) -> String { "Сессия \(index) из \(total) — ⌘K для переключения" }
    let sessionWaiting = "ждёт вашего ответа"
    let sessionAgents = "{n} в фоне"
    let sessionShellOne = "1 shell работает"
    let sessionShellMany = "{n} shell работают"
    let islandDone = "готово"
    let islandAllSessions = "Все сессии…"
    func statusWaiting(_ labels: [String]) -> String {
        labels.count == 1 ? "\(labels[0]) ждёт вашего ответа"
                          : "\(labels.count) сессий ждут вашего ответа"
    }
    func statusWorking(_ count: Int) -> String { "\(count) выполняется" }

    let settingsTitle = "Настройки Clawdline"
    let settingsGeneral = "Основные"
    let settingsBar = "Строка"
    let settingsReading = "Чтение"
    let settingsVoice = "Диктовка"
    let settingsHotkey = "Сочетание клавиш"
    let settingsRecording = "Нажмите клавиши…"
    let settingsScope = "Работает в"
    let settingsScopeGlobal = "Во всех приложениях"
    let settingsScopeHint = "Пусто — значит везде, поэтому если убрать последнее, включится переключатель выше, а если выключить его обратно, список вернётся. В файле настроек это bundle id, и список, поправленный вручную, тоже работает."
    let settingsScopeAdd = "Добавить приложение…"
    let settingsScopeChoose = "Выбрать приложение…"
    let settingsScopeRunning = "Открыты прямо сейчас"
    let settingsScopeRemove = "Убрать"
    let settingsLanguage = "Язык"
    let settingsReopen = "Строка приходит и уходит вместе с терминалом"
    let settingsReopenHint = "Ушли из терминала — строка убирается, вернулись в него — строка возвращается. А Esc означает, что вы с ней закончили."
    let settingsFollow = "Терминал показывает то, на что нацелена строка"
    let settingsFollowHint = "Выбирает вкладку этой сессии. Терминал на передний план не выводится: иначе каждое нажатие Tab уводило бы клавиатуру из поля, в котором вы печатаете."
    let settingsCodexAutoName = "Называть новые сессии Codex"
    let settingsCodexAutoNameHint = "Для каждой сессии без имени запускается один небольшой ход Codex Luna. Он использует первый запрос, расходует лимит Codex и не заменяет выбранное вами имя."
    let settingsNotch = "Жить в вырезе"
    let settingsNotchHint = "Персонаж в корпусе камеры. Выключено — значит выключено: ничего не рисуется и окно не создаётся."
    let settingsPosition = "Высота на экране"
    let settingsWidth = "Ширина"
    let settingsOpacity = "Непрозрачность карточки"
    let settingsShow = "Показывать"
    let settingsPaneHeight = "Высота панели"
    let settingsTextSize = "Размер текста"
    let settingsPaneFont = "Шрифт панели"
    let settingsBlur = "Размытие позади"
    let settingsNewestFirst = "Сначала новые"
    let settingsEngine = "Распознаватель"
    let settingsSettle = "Пауза завершает фразу"
    let settingsStop = "Тишина завершает сессию"
    let settingsAuto = "Авто"
    let settingsTranscript = "Расшифровка"
    let settingsTerminal = "Терминал"
    let settingsOff = "Выкл"
    let settingsHooks = "Хуки Claude Code"
    let settingsHooksHint = "Когда они установлены, Claude Code сам сообщает момент, когда ход начался, закончился или ждёт ответа, — вместо того чтобы Clawdline узнал об этом при следующем опросе. Читается всё по-прежнему с экрана; здесь решается только, насколько быстро."
    let settingsHooksInstall = "Установить"
    let settingsHooksRemove = "Убрать"
    let settingsHooksOff = "Не установлены — состояние читается только с экрана"
    let settingsHooksOn = "Установлены — ни одна сессия ещё не отозвалась"
    let settingsHooksLive = "Установлены, сессии отзываются"
    let settingsStateHook = "Когда сессия меняет состояние"
    let settingsStateHookHint = "Каждый раз, когда сессия берётся за работу, заканчивает или о чём-то вас спрашивает, Clawdline запускает это: вашу собственную программу, с подробностями в её окружении. Задаётся в файле настроек, а не здесь, потому что это argv, а не командная строка — путь с пробелом должен остаться одним путём."
    let settingsRemote = "Удалённый доступ"
    let settingsRemoteServe = "Разрешить браузеру или телефону видеть ваши сессии"
    let settingsRemoteHint = "Выключено — снаружи этого Mac ничто ни до чего не дотянется. Включено — список сессий отдаётся на 127.0.0.1: браузеру здесь, телефону через туннель, скрипту. Отдаются при этом имена репозиториев, ветки и названия задач, поэтому оно так и стоит выключенным, пока вы не скажете иначе."
    let settingsRemoteDevices = "Сопряжённые устройства"
    let settingsRemoteNoDevices = "Пока ни одного — за пределами этого Mac ничего прочитать нельзя"
    let settingsRemoteRevokeAll = "Отключить всё"
    let settingsRemoteOpen = "Открыть в браузере"
    let pairingIgnore = "Игнорировать"
    func pairingAsks(_ device: String) -> String { "\(device) хочет создать пару с этим Mac" }
    func pairingCode(_ code: String) -> String {
        """
        Введите этот код на нём:

        \(code)

        Он действует две минуты. Если вы только что этого не запрашивали — не обращайте \
        внимания: без этого кода тот, кто запросил, ничего не завершит.
        """
    }
    let settingsTunnel = "Дотянуться до этого Mac откуда угодно"
    let settingsTunnelQuick = "Сгенерированный адрес"
    let settingsTunnelNamed = "Мой собственный домен"
    let settingsTunnelHostname = "Имя хоста"
    let settingsTunnelHint = "Открывает исходящее соединение через cloudflared — никакого проброса портов, ничего слушающего в вашей сети. Не запустится, пока не сопряжено хотя бы одно устройство: за туннелем — имя каждого репозитория и название каждой задачи на этом Mac."
    let settingsRemoteWrite = "Разрешить сопряжённому устройству писать в сессию"
    let settingsRemoteWriteHint = "Выключено — сопряжённое устройство может только читать. Включено — оно может отправлять текст в сессию и запускать новые, а это выполняет код на этом Mac, потому что Claude Code именно этим и занимается. Решение здесь другое, чем выше, поэтому и переключатель отдельный."
    let settingsRemotePhone = "Сопрячь телефон…"
    let settingsRemotePhoneHint = "Показывает код для сканирования. У кода собственный ключ: снимок этого кода — это устройство, которое видно в списке выше и которое можно отключить, а не ключ самого этого Mac."
    let pairingScanTitle = "Наведите на это телефон"
    let pushWaiting = "ждёт ответа"
    let pushTest = "Тестовое уведомление. Всё подключено."
    let pushFinished = "долгая работа закончена"
    let pushDeployOk = "деплой прошёл успешно"
    let pushDeployFail = "деплой не удался"
    let settingsPushFinish = "Сообщать, когда долгая работа закончится"
    let settingsPushFinishHint = "Только дольше двух минут."
    let settingsPushDeploy = "Сообщать, когда закончится деплой"
    let settingsPushDeployHint = "И об успехе, и об ошибке."
    let settingsOrchestrator = "Работа для другой сессии"
    let settingsOrchestratorEnabled = "Разрешить сессии передавать работу другой"
    let settingsOrchestratorEnabledHint = "Сессия со скиллом clawdline может открыть вкладку, впечатать в неё задание и узнать, когда работа сделана. Выключено — каждая заявка отклоняется; то, что уже работает, не останавливается."
    let settingsOrchestratorMax = "Дочерних сессий сразу"
    let settingsOrchestratorMaxHint = "По умолчанию пять, и счёт идёт на сессию, а не на весь Mac. Каждая — вкладка терминала, в которой работает ассистент."
    let settingsOrchestratorSubMax = "И сколько передаёт дочерняя"
    let settingsOrchestratorSubMaxHint = "По умолчанию три. Сессия, которая сама выполняет поручение, может открыть свои; под ними уже ничего не открывается."
    let settingsOrchestratorSubMaxNone = "Нисколько — дочерняя не передаёт"
    let settingsOrchestratorPermission = "Насколько далеко дочерняя идёт сама"
    let settingsOrchestratorPermissionHint = "На вкладку дочерней сессии никто не смотрит, поэтому та, что остановилась ради подтверждения, стоит до истечения времени — а работа отправленной сессии целиком состоит из запуска команд и записи файлов, так что всё, кроме последнего пункта, где-нибудь её остановит. Задача может попросить меньше этого, но не больше."
    let settingsOrchestratorPermissionAsk = "Спрашивать на каждом шаге"
    let settingsOrchestratorPermissionEdits = "Писать файлы без вопросов"
    let settingsOrchestratorPermissionFull = "Не спрашивать"
    let settingsOrchestratorNotify = "Сообщать той сессии, которая попросила"
    let settingsOrchestratorNotifyHint = "Одна строка, впечатанная в неё, когда задача заканчивается."
    let settingsOrchestratorClose = "Когда дочерняя сессия отчитается"
    let settingsOrchestratorCloseHint = "Её вкладка закрывается после отчёта; та, что не уложилась в срок, остаётся открытой — чтобы вы её прочитали."
    let settingsOrchestratorCloseNow = "Закрывать вкладку сразу"
    let settingsOrchestratorCloseLinger = "Закрывать через три минуты"
    let settingsOrchestratorCloseKeep = "Оставлять открытой"
    let settingsOrchestratorPolicy = "Как раздаётся работа"
    let settingsOrchestratorPolicyHint = "Правила, которые Clawdline читает при каждой отправке и переносит в инструкцию каждой дочерней сессии, которой можно отправлять дальше: какой ассистент, какая модель, какой формы должен быть граф. Пусто — правил нет."
    let settingsOrchestratorPolicyEdit = "Изменить правила"
    func settingsOrchestratorPolicyOn(_ lines: Int) -> String { return "Действуют — строк: \(lines)" }
    let settingsOrchestratorPolicyOff = "Правил нет — каждый раз решает тот, кто отправляет"
    func childAnnounce(_ title: String) -> String { "Задача от Clawdline принята: \(title) — приступаю." }
    func settingsSeconds(_ value: Double) -> String { String(format: "%.1f с", value) }

    let webConnLive = "на связи"
    let webConnConnecting = "подключение"
    let webConnRetrying = "повтор через {n} с"
    let webConnOffline = "нет связи"
    let webConnLocked = "нет пары"
    let webConnTipLive = "Поток из приложения"
    let webConnTipLocked = "Этот браузер не сопряжён с этим Mac"
    let webConnTipDown = "Нет связи — нажмите, чтобы попробовать"

    let webCountWorking = "в работе: {n}"
    let webCountWaiting = "в ожидании: {n}"
    let webCountUnreadable = "нечитаемых: {n}"
    let webCountQuietOne = "{n} сессия, всё тихо"
    let webCountQuietMany = "сессий: {n}, всё тихо"
    let webCountNone = "нет сессий"

    let webFilterPlaceholder = "Фильтр по задаче, проекту или tty"
    let webFilterLabel = "Фильтр сессий"
    let webListLabel = "Сессии Claude Code"
    let webPull = "Потяните, чтобы обновить"
    let webPullRelease = "Отпустите, чтобы обновить"
    let webPullBusy = "Обновление…"
    let webEmptyFilterTitle = "Ничего не подходит под «{q}»"
    let webEmptyFilterHint = "Esc очищает фильтр"
    let webEmptyLockedTitle = "Это устройство не сопряжено"
    let webEmptyLockedHint = "Приложение ответило 401 — создайте пару в Clawdline на Mac"
    let webEmptyNoneHint = "Запустите её в терминале, и она появится здесь"
    let webEmptyWaitTitle = "Ждём приложение"
    let webEmptyWaitHint = "В потоке пока ничего не появилось"
    let webStateUnreadable = "экран не прочитать"
    let webStateWorking = "в работе"

    let webBack = "Сессии"
    let webBackLabel = "Назад к списку сессий"
    let webNoSessionOpen = "Сессия не открыта"
    let webOrderTip = "Перевернуть расшифровку (r)"
    let webShowOnMac = "Показать на Mac"
    let webShowOnMacTip = "Вывести терминал этой сессии на передний план на Mac"
    let webShowOnMacOff = "Сервер сообщает write: false — отправить пока ничего нельзя"
    let webShowOnMacAsked = "Mac попросили вывести её вперёд"
    let webSessionActions = "Действия с сессией"
    let webSessionGit = "Изменения Git"
    let webGitTitle = "Изменения Git"
    let webGitClean = "Рабочее дерево не изменено"
    let webGitNotRepo = "Это не репозиторий Git"
    let webGitFailed = "Не удалось прочитать изменения Git"
    let webGitRefresh = "Обновить"
    let webGitClose = "Закрыть"
    let webGitStaged = "Добавлено в индекс"
    let webGitUnstaged = "Не добавлено в индекс"
    let webGitUntracked = "Не отслеживается"
    let webGitConflict = "Конфликт"
    let webEndSession = "Закрыть сессию"
    let webConfirmActionTitle = "Выполнить {action}?"
    let webConfirmActionSay = "Команда {action} будет отправлена в текущую сессию."
    let webConfirmEndTitle = "Закрыть эту сессию?"
    let webConfirmEndSay = "Ассистент завершит работу, затем закроется вкладка терминала."
    let webClosing = "Закрытие…"
    let webCancel = "Отмена"
    let webConfirm = "Подтвердить"
    let webPickSession = "Выберите сессию слева."
    let webReading = "Читаем…"
    let webLoading = "Загрузка…"
    let webTranscriptFailed = "Не удалось прочитать расшифровку"
    let webWhoYou = "вы"
    let webWhoTool = "инструмент"
    let webPending = "Ждём Mac…"
    let webAttachedImage = "Прикреплено изображение: {n}"
    let webAttachedImages = "Прикреплено изображений: {n}"
    let webSteps = "шагов: {n}"
    let webJustNow = "только что"
    let webMinutesAgo = "{n} мин назад"

    let webSend = "Отправить"
    let webAttach = "Прикрепить картинку"
    let webRemoveShot = "Убрать {name}"
    let webWriteOpen = "Откройте сессию, чтобы в неё писать."
    let webWriteOff = "*Отправка выключена* — сервер сообщает `write: false`. Поле подключено; оно включится само, когда это изменится."
    let webShotsOnlyPictures = "С сообщением могут уйти только картинки"
    let webShotsTooMany = "Больше {n} картинок одно сообщение не унесёт"
    let webShotTooBig = "Эта картинка слишком велика для отправки, даже уменьшенная"
    let webShotsTooBig = "Эти картинки слишком велики, чтобы уйти вместе"
    let webShotUnreadable = "Эту картинку не удалось прочитать"
    let webShotNeedsSession = "Откройте сессию, чтобы отправить в неё картинку"

    let webVoiceStart = "Продиктовать сообщение"
    let webVoiceStop = "Остановить и расшифровать"
    let webVoiceDone = "Готово"
    let webVoiceListening = "Слушаем… {t}"
    let webVoiceReading = "Расшифровываем на Mac… {n} с"
    let webVoiceSlow = "Первая после перезагрузки этого Mac сначала грузит модель — секунд двенадцать."
    let webVoiceLimit = "Запись остановилась на {n} минутах — дольше одна не идёт. Расшифровываем то, что есть."
    let webVoiceEmpty = "Там ничего не услышали."
    let webVoiceTooShort = "Это было слишком коротко, чтобы что-то расслышать."
    let webVoiceDenied = "Микрофон отклонён. Включите его обратно в настройках этого браузера для этого сайта."
    let webVoiceNoMic = "На этом устройстве микрофон не найден."
    let webVoiceInUse = "Микрофон занят — им владеет что-то другое на этом устройстве."
    let webVoiceInsecure = "Микрофону нужен https, а эта страница не по нему. Туннель его даёт; обычный адрес в локальной сети — нет."
    let webVoiceUnsupported = "Этот браузер не умеет записывать звук."
    let webVoiceBusy = "Одну сейчас расшифровывают, другая ждёт. Попробуйте через минуту."
    let webVoiceNoBinary = "На Mac нет Whisper, так что там нечем это расшифровать."
    let webVoiceNoModel = "Whisper на Mac есть, а модели для чтения нет. Ему хватит одного файла ggml в `~/.cache/whisper`."
    let webVoiceFailed = "Это не удалось расшифровать."

    let webHintMove = "листать"
    let webHintOpen = "открыть"
    let webHintFilter = "фильтр"
    let webHintPane = "панель"

    let webKeysLabel = "Сочетания клавиш"
    let webKeysTitle = "Клавиатура"
    let webKeysMove = "Двигаться по списку — `j` и `k` делают то же"
    let webKeysOpen = "Открыть выбранную сессию"
    let webKeysFilter = "Отфильтровать список"
    let webKeysEscape = "Очистить фильтр, потом шаг назад"
    let webKeysList = "Перейти к списку сессий"
    let webKeysPane = "Показать или скрыть расшифровку"
    let webKeysEnds = "Начало или конец расшифровки"
    let webKeysReverse = "Перевернуть порядок расшифровки"
    let webKeysThis = "Эта карточка"
    let webKeysFoot = "Всё, что набрано в текстовом поле, в поле и остаётся — пока вы пишете, сочетания не срабатывают."

    let webDoorLabel = "Сопрячь этот браузер"
    let webDoorAskLede = "Этот браузер сюда ещё не впустили."
    let webDoorAskFine = "Запросите пару — и шестизначный код появится *на Mac*, а не в ответе этой странице: так задумано. Довести дело до конца может только тот, кто сидит за той машиной, и в этом весь смысл, а не помеха."
    let webDoorName = "Назовите это устройство"
    let webDoorAsk = "Запросить пару"
    let webDoorToPassword = "Войти по паролю"
    let webDoorCodeLede = "Посмотрите на Mac."
    let webDoorCodeFine = "Clawdline показывает шесть цифр ещё {left}. Введите их здесь."
    let webDoorTwoMinutes = "две минуты"
    let webDoorDigit = "Цифра {n}"
    let webDoorConfirm = "Сопрячь это устройство"
    let webDoorRestart = "Начать заново"
    let webDoorPasswordLede = "Войдите по паролю."
    let webDoorPasswordFine = "Это тот пароль, что задан в Clawdline на Mac, в Настройках → Удалённый доступ. Если он не задан, внутрь ведёт только пара."
    let webDoorPassword = "Пароль"
    let webDoorPasswordGo = "Войти"
    let webDoorToPair = "Ввести код сопряжения"
    let webDoorAsking = "Спрашиваем Mac…"
    let webDoorAskFailed = "Не удалось спросить Mac."
    let webDoorRateLimited = "Каждый запрос выводит уведомление на Mac, поэтому их всего три за десять минут."
    let webDoorSixDigits = "Шесть цифр."
    let webDoorChecking = "Проверяем…"
    let webDoorFinished = "Эта пара закрыта — пять неверных кодов. Запросите заново, когда будете за Mac."
    let webDoorWrongCode = "Этот код неверный."
    let webDoorNeedPassword = "Сначала пароль."
    let webDoorWrongPassword = "Это не тот пароль."
    let webDoorExpired = "Этот код истёк. Запросите заново — на Mac появится новый."
    let webDoorPaired = "Пара создана — браузер внутри"

    let webOffline = "Не удалось достучаться до Clawdline. Он ещё запущен на Mac?"
    let webNotJSON = "Сервер прислал что-то, что не JSON"
    let webRequestFailed = "Запрос не удался"

    let webNotifyGo = "Сообщать мне"
    let webNotifyAsking = "Спрашиваем…"
    let webNotifyStop = "Отключить"
    let webNotifyStopping = "Отключаем…"
    let webNotifyOff = "когда сессия ждёт ответа"
    let webNotifyOn = "Это устройство подписано. О чём ему сообщать, задаётся на Mac."
    let webNotifyBlocked = "Уведомления для этого сайта заблокированы. Этот переключатель — в настройках самого браузера, не здесь."
    let webNotifyUnsupported = "Этот браузер не умеет показывать уведомления."
    let webNotifyHomeScreen = "Добавьте clawdline на домашний экран и открывайте оттуда — iOS шлёт уведомления только приложению, которое там живёт."
    let webNotifyOnFailed = "Не удалось включить уведомления"
    let webNotifyOffFailed = "Не удалось выключить уведомления"

    let webSettings = "Настройки"
    let webSettingsNotify = "Уведомления"
    let webSettingsAssistantIcons = "Значки ассистентов"
    let webSettingsAssistantIconsSay = "Показывать значок Claude или Codex перед его именем в диалоге."
    let webSettingsAssistantIconsShow = "Показывать значки"
    let webSettingsVersion = "Версия {v}"
    let webClose = "Закрыть"
    let webNotifySheetOff = "Этому устройству не сообщают, когда сессия ждёт."
    let webNotifyTest = "Отправить тест"
    let webNotifyTestSent = "Отправлено — вот-вот придёт на это устройство."
    let webNotifyTestNone = "На Mac нет подписки для этого устройства. Выключите и снова включите уведомления — браузер зарегистрирует новую."
    let webNotifyTestFailed = "Не удалось отправить тестовое уведомление"
    let webSending = "Отправка…"
    let webSendTip = "Return отправляет · Shift-Return переносит строку"
    let webStart = "Начать сессию"
    let webStartLabel = "Начать сессию в проекте"
    let webStartPick = "Где её начать?"
    let webStartWith = "Чем её начать?"
    let webStartEmpty = "Пока негде начинать. Запустите Claude Code на Mac один раз — и проект появится здесь."
    let webStartFilter = "Фильтр проектов"
    let webStarting = "Открываем вкладку…"
    let webStartWaiting = "Запущена. Вот-вот появится…"
    let webStartSlow = "Вкладка открыта, но сессия не отозвалась. Загляните на Mac."
    let webStartFailed = "Запустить это не удалось."
    let webStartGone = "Этого проекта на Mac больше нет."
    let webStartTerminalClosed = "На Mac не запущен {app}. Откройте его там и попробуйте снова."
    let webStartTerminalUnsupported = "Отсюда нельзя начать сессию в {app}. Запустите в нём tmux — и всё заработает."
    let webStartOff = "Запуск сессий выключен. Включается на Mac, в Настройках → Удалённый доступ."
    let webCommand = "Скажите, что начать"
    let webCommandLabel = "Начать сессию, сказав, что она должна сделать"
    let webCommandSay = "Ничего не отправляется, пока вы не нажмёте «Начать» внизу."
    let webCommandHeard = "Что нужно сделать?"
    let webCommandThinking = "Думаем…"
    let webCommandDraft = "Черновик"
    let webCommandWhere = "Где"
    let webCommandWith = "Чем"
    let webCommandFirst = "Первое сообщение"
    let webCommandGo = "Начать"
    let webCommandUnsure = "Не понятно, какой проект — выберите один ниже."
    let webCommandFailed = "Не удалось превратить это в черновик."
    let webCommandNoPlanner = "На этом Mac нет Claude Code, чтобы превратить это в черновик."
    let webCommandBusy = "Одна фраза уже превращается в черновик — попробуйте ещё раз через минуту."
    let webCommandEmpty = "Ничего не услышал"
    let webLinks = "Ссылки"
    let webLinksTip = "Где этот проект можно открыть"
    let webLinksPick = "Всё, у чего в этом проекте есть адрес."
    let webLinksEmpty = "В этом проекте нет ничего с адресом — ни сайта, ни деплоя, ни запущенных серверов."
    let webLinksFailed = "Не удалось прочитать ссылки этого проекта."
    let webLinksLocal = "Только в собственной сети Mac. Отсюда не откроется."
    let webLinksFile = "Файл на Mac. Открывается он там, а не в этом браузере."
    let webLinksCopy = "Скопировать путь"
    let webLinksCopied = "Скопировано."
    let webLinksCopyFailed = "Этот браузер не дал странице это скопировать."
    let webLinkOk = "в норме"
    let webLinkFail = "ошибка"
    let webLinkDown = "выключен"
    let webLinkRunning = "идёт"
    let webSessionInfo = "О сессии"
    let webInfoTitle = "Об этой сессии"
    let webInfoSession = "Эта сессия"
    let webInfoAssistant = "Ассистент"
    let webInfoModel = "Модель"
    let webInfoSessionId = "ID сессии"
    let webInfoDirectory = "Каталог"
    let webInfoRunningFor = "Работает уже"
    let webInfoUsage = "Расход токенов"
    let webInfoInput = "Ввод"
    let webInfoOutput = "Вывод"
    let webInfoCacheRead = "Чтение из кэша"
    let webInfoCacheWrite = "Запись в кэш"
    let webInfoTotal = "Всего"
    let webInfoCost = "Примерная стоимость"
    let webInfoNoUsage = "Транскрипт этой сессии пока не найден."
    let webInfoLimits = "Лимиты тарифа"
    let webInfoLimitHit = "лимит исчерпан"
    let webInfoResets = "сброс {when}"
    let webInfoUnknown = "неизвестно"
    let webInfoFiles = "Файлы"
    let webInfoBranch = "Ветка"
    let webInfoStaged = "В индексе"
    let webInfoUnstaged = "Изменены"
    let webInfoUntracked = "Не отслеживаются"
    let webInfoConflict = "Конфликты"
    let webInfoClean = "Незакоммиченного нет."
    let webInfoNotRepo = "Это не git-репозиторий."
    let webInfoDeploy = "Последний деплой"
    let webInfoNoDeploy = "У этого проекта нет записей о деплое."
    let webInfoFailed = "Не удалось прочитать сведения об этой сессии."
    let webInfoRefresh = "Обновить"
    let webInfoTokens = "токенов"
    let webInfoSwitchModel = "Сменить модель"
    let webInfoModelOther = "другая модель…"
    let webInfoModelSent = "Отправлено /model {model}. Проверяем…"
    let webInfoModelBusy = "Смена ждёт, пока сессия не освободится."
    let webInfoSwitchPermission = "Сменить режим разрешений"
    let webInfoPermissionAuto = "Автоматический"
    let webInfoPermissionManual = "Ручной"
    let webInfoPermissionAcceptEdits = "Принимать изменения"
    let webInfoPermissionPlan = "Планирование"
    let webInfoPermissionUnreadable = "Не удалось прочитать текущий режим."
    let webInfoPermissionSent = "Включён режим «{mode}». Проверяем…"
    let webInfoPermissionBusy = "Режим разрешений переключается."
    let webInfoLimitsClaude = "Claude Code записывает окно только когда оно исчерпано; до тех пор ничего не известно."
    let webInfoCopied = "Id сессии скопирован."
    let webInfoAsOf = "на {when}"
    let webInfoWhyUnknown = "Почему неизвестно, и как получить цифры"
    let webSettingsOrder = "Расшифровка"
    let webSettingsOrderSay = "С какого конца начинать читать расшифровку. Это касается каждой сессии, а с клавиатуры то же самое делает `r`."
    let webAskLabel = "спросил"
    let webAskAny = "Сколько угодно из этих"
    let webWaitingTitle = "Эта сессия ждёт ответа"
    let webWaitingSay = "Claude Code показывает меню на Mac. Clawdline пока не умеет читать меню отсюда, так что варианты есть только на том экране."
    let webWaitingSend = "*Отправка отсюда не впечатает ваш ответ в меню* — она подтвердит тот пункт, который в меню сейчас подсвечен, а это редко тот, что вы имели в виду. На этот вопрос ответьте на Mac."
    let webMenuSay = "Нажмите на ответ — он уйдёт прямо в сессию."
    let webMenuHighlighted = "выделен"
    let webMenuSent = "Ответ отправлен."
    let webAgents = "Фоновые агенты"
    let webAgentsCount = "{n} работают"
    let webAgentDone = "готово"
    let webAgentFailed = "не удалось"
    let webShells = "Фоновые shell"
    let webShellTitle = "Фоновый shell"
    let webShellOpen = "Посмотреть, что печатает эта команда"
    let webShellRunning = "ещё работает"
    let webShellEnded = "завершена"
    let webShellQuiet = "Пока ничего не напечатано."
    let webShellFailed = "Не удалось прочитать вывод этой команды."
    let webShellClose = "Закрыть"
    let webShellStop = "Остановить"
    let webShellStopTitle = "Остановить эту команду?"
    let webShellStopSay = "{command} ещё работает. Ей будет предложено остановиться, а через пять секунд она будет убита, если этого не сделает. Уже сделанное не отменяется."
    let webShellStopped = "Запрошена остановка."
    let webShellStopFailed = "Не удалось остановить."
    let agentRunning = "работает"
    let agentTools = "инструментов: {n}"
    let agentEmpty = "Этот агент пока ничего не записал."
    let agentBack = "Сессия"
    let webAgentOpen = "Посмотреть, что сделал этот агент"
    let webTaskRoot = "Главная"
    let webTaskChild = "Дочерняя"
    let webTaskTasks = "Задачи"
    let webTaskDone = "готово"
    let webTaskFailed = "не удалось"
    let webTaskRunning = "работает"
    let webStale = "Clawdline на Mac пересобрали. Эта страница осталась от прежней сборки."
    let webStaleGo = "Перезагрузить"

    let menuOpen = "Открыть строку ввода"
    let menuReveal = "Перейти к нужной вкладке"
    let menuMascot = "Маскот"
    let menuLogin = "Запускать при входе"
    let menuEditConfig = "Настройки…"
    let menuReload = "Перечитать настройки"
    let menuQuit = "Выйти из Clawdline"
    let menuNoTarget = "(пока не найдено)"

    func hotkeyFailedTitle(_ combo: String) -> String { "Не удалось зарегистрировать \(combo)" }
    func hotkeyFailedBody(_ configPath: String) -> String {
        """
        Скорее всего, это сочетание уже занято другим приложением — Spotlight, \
        переключатель раскладки, BetterTouchTool и тому подобное.

        Выберите другое: измените "hotkey" в \(configPath), затем выберите \
        «Перечитать настройки» в строке меню.

        До тех пор строку ввода по-прежнему открывает ✳ в строке меню.
        """
    }
    let loginFailed = "Не удалось настроить запуск при входе"
}
