import Foundation

struct Turkish: Copy {
    let placeholder = "Claude Code'a yaz…"

    let hintSend = "gönder"
    let hintNewline = "yeni satır"
    let hintSwitch = "değiştir"
    let hintList = "liste"
    let hintMascot = "maskot"
    let hintOutput = "çıktı"
    let hintFullscreen = "tam ekran"
    let hintKeys = "tuşlar"
    let hintTextSize = "yazı boyutu"
    let hintOrder = "ters sıra"
    let hintVoice = "dikte"
    func voiceListening(onDevice: Bool) -> String {
        onDevice ? "Bu Mac'te dinliyor — durdurmak için tekrar bas"
                 : "Dinliyor — bu dili Apple yazıya döküyor, bu Mac değil"
    }
    let voiceNoPermission = "Dikte için mikrofon ve konuşma tanıma izni gerekiyor"
    let voiceUnavailable = "Dikte şu anda kullanılamıyor"
    func voiceTranscribing(seconds: Double) -> String {
        String(format: "Whisper yeniden okuyor… %.1f sn", seconds)
    }
    let whisperMissing = "Whisper kurulu değil — docs/whisper.md'ye bak"
    let whisperNothingHeard = "Hiçbir şey duyulmadı"
    func dictationStatus(_ status: Whisper.Status) -> String {
        switch status {
        case .ready(let model): return "Dikte: önce Apple, sonra Whisper (\(model))"
        case .noBinary: return "Dikte: yalnızca Apple — whisper-cli yok"
        case .noModel: return "Dikte: yalnızca Apple — whisper-cli var, model yok"
        }
    }
    func voiceListeningWhisper() -> String {
        "Dinliyor — sen durunca Whisper bir kez daha bakıyor"
    }

    let scanning = "Aranıyor…"
    let noSession = "Claude Code oturumu bulunamadı"
    let nothingToSend = "Gönderilecek yer yok — önce bir terminalde Claude Code başlat"
    let sendFailed = "Gönderilemedi"
    let itermSilent = "iTerm2 yanıt vermedi"
    let itermBusy = "iTerm2 bir iletişim kutusunun yanıtlanmasını bekliyor — Mac'te yanıtlayın"
    let scriptMissing = "iterm.js yok — uygulama paketi bozuk mu?"
    let cannotList = "iTerm2 oturumları okunamadı"
    let noOutput = "Bu oturumda okunacak bir şey henüz yok."
    func outputSize(_ pt: Int) -> String { "Çıktı yazı boyutu \(pt) pt — görmek için ⌘J" }
    func foldedTools(_ count: Int) -> String { "\(count) adım" }
    func outputOrder(newestFirst: Bool) -> String {
        newestFirst ? "En yeni üstte" : "En eski üstte"
    }
    func backlogNow(_ count: Int) -> String { "şimdi \(count)" }
    func dropped(_ count: Int) -> String {
        count == 1 ? "Yol eklendi — Claude Code onu okur" : "\(count) yol eklendi"
    }
    func stackConfirm(_ command: String) -> String { "Çalıştırmak için tekrar basın:  \(command)" }
    let hintStacks = "sunucular"
    func stackTip(up: Int, total: Int) -> String { "\(total) sunucudan \(up) tanesi çalışıyor — liste için ⌘S" }
    let stackTipUnknown = "Bu projenin sunucuları var ama durum komutu henüz güvenilir değil — ⌘S"
    let stackUntrusted = "onaylanmadı"
    let stackExit = "çıkış"
    let stackActionStart = "başlat"
    let stackActionRestart = "yeniden başlat"
    let stackActionStop = "durdur"
    let stackActionLogs = "günlük"
    let stackLogAll = "tümü"
    let stackLogBack = "döküm"
    let stackActionAllow = "izin ver"
    let stackActionAgain = "tekrar bas"
    func sessionTip(index: Int, total: Int) -> String { "\(total) oturumdan \(index). — değiştirmek için ⌘K" }
    let sessionWaiting = "yanıtını bekliyor"
    let sessionAgents = "arka planda {n}"
    let sessionShellOne = "1 shell çalışıyor"
    let sessionShellMany = "{n} shell çalışıyor"
    let islandDone = "bitti"
    let islandAllSessions = "Tüm oturumlar…"
    func statusWaiting(_ labels: [String]) -> String {
        labels.count == 1 ? "\(labels[0]) yanıtını bekliyor"
                          : "\(labels.count) oturum yanıtını bekliyor"
    }
    func statusWorking(_ count: Int) -> String { "\(count) çalışıyor" }

    let settingsTitle = "Clawdline Ayarları"
    let settingsGeneral = "Genel"
    let settingsBar = "Çubuk"
    let settingsReading = "Okuma"
    let settingsVoice = "Dikte"
    let settingsHotkey = "Kısayol"
    let settingsRecording = "Tuşlara bas…"
    let settingsScope = "Şurada çalışır"
    let settingsScopeGlobal = "Her uygulamada"
    let settingsScopeHint = "Boşsa her yerde çalışır; yani sonuncuyu çıkarmak yukarıdaki anahtarı açar — onu tekrar kapatmak da listeyi geri getirir. Yapılandırma dosyası bunları bundle kimliği olarak tutar, elle düzenlenmiş bir liste de aynı şekilde çalışır."
    let settingsScopeAdd = "Uygulama ekle…"
    let settingsScopeChoose = "Uygulama seç…"
    let settingsScopeRunning = "Şu anda açık olanlar"
    let settingsScopeRemove = "Çıkar"
    let settingsLanguage = "Dil"
    let settingsReopen = "Çubuk terminalle birlikte gelir ve gider"
    let settingsReopenHint = "Terminalden başka bir yere geçince çubuk kalkar, terminale dönünce geri gelir. Bittiğini söyleyen şey Esc'tir."
    let settingsFollow = "Terminal, çubuğun nişan aldığı şeyi gösterir"
    let settingsFollowHint = "O oturumun sekmesini seçer. Terminali öne getirmez — getirseydi, her Tab'a basışta klavye yazmakta olduğun kutudan çıkardı."
    let settingsCodexAutoName = "Yeni Codex oturumlarını adlandır"
    let settingsCodexAutoNameHint = "Adsız her oturum için küçük bir Codex Luna turu çalıştırır. İlk isteği kullanır, Codex kullanımından harcar ve senin seçtiğin adı değiştirmez."
    let settingsNotch = "Çentikte yaşa"
    let settingsNotchHint = "Kamera yuvasında bir karakter. Kapalı gerçekten kapalı: hiçbir şey çizilmez, pencere açılmaz."
    let settingsPosition = "Ekrandaki yükseklik"
    let settingsWidth = "Genişlik"
    let settingsOpacity = "Kart opaklığı"
    let settingsShow = "Göster"
    let settingsPaneHeight = "Panel yüksekliği"
    let settingsTextSize = "Yazı boyutu"
    let settingsPaneFont = "Panel yazı tipi"
    let settingsBlur = "Arkadaki bulanıklık"
    let settingsNewestFirst = "Önce en yeni"
    let settingsEngine = "Tanıyıcı"
    let settingsSettle = "Bir duraklama cümleyi bitirir"
    let settingsStop = "Bir sessizlik oturumu bitirir"
    let settingsAuto = "Otomatik"
    let settingsTranscript = "Döküm"
    let settingsTerminal = "Terminal"
    let settingsOff = "Kapalı"
    let settingsHooks = "Claude Code kancaları"
    let settingsHooksHint = "Kurulduğunda Claude Code bir turun başladığı, bittiği ya da yanıt beklediği anı kendisi haber verir; Clawdline'ın bir sonraki bakışını beklemez. Okuma yine ekrandan yapılır, burada belirlenen yalnızca ne kadar çabuk olduğu."
    let settingsHooksInstall = "Kur"
    let settingsHooksRemove = "Kaldır"
    let settingsHooksOff = "Kurulu değil — durum yalnızca ekrandan okunuyor"
    let settingsHooksOn = "Kurulu — henüz hiçbir oturum haber vermedi"
    let settingsHooksLive = "Kurulu, oturumlar haber veriyor"
    let settingsStateHook = "Bir oturum durum değiştirdiğinde"
    let settingsStateHookHint = "Bir oturum çalışmaya başladığında, bitirdiğinde ya da sana bir şey sorduğunda Clawdline şunu çalıştırır: kendi programını, ayrıntılar da ortam değişkenlerinde. Burada değil de yapılandırma dosyasında yazılır, çünkü bu bir komut satırı değil bir argv'dir — içinde boşluk olan bir yol tek bir yol olarak kalmak zorundadır."
    let settingsRemote = "Uzaktan erişim"
    let settingsRemoteServe = "Bir tarayıcı ya da telefonun oturumlarını görebilsin"
    let settingsRemoteHint = "Kapalıyken bu Mac'in dışından hiçbir şey hiçbir yere erişemez. Açıkken oturum listesi 127.0.0.1 üzerinden sunulur — buradaki bir tarayıcıya, tünelin ucundaki bir telefona, bir betiğe. Karşı tarafa giden şey depo adları, branch'ler ve görev başlıklarıdır; kapalı kalmasının sebebi de bu, sen aksini söyleyene kadar."
    let settingsRemoteDevices = "Eşleşen cihazlar"
    let settingsRemoteNoDevices = "Henüz yok — bu Mac'in dışından hiçbir şey okunamıyor"
    let settingsRemoteRevokeAll = "Bağlantıları kes"
    let settingsRemoteOpen = "Tarayıcıda aç"
    let pairingIgnore = "Yoksay"
    func pairingAsks(_ device: String) -> String { "\(device) bu Mac ile eşleşmek istiyor" }
    func pairingCode(_ code: String) -> String {
        """
        Bu kodu o cihaza yaz:

        \(code)

        İki dakika geçerli. Az önce bunu sen istemediysen boş ver — isteyen kişi bu kod \
        olmadan işi bitiremez.
        """
    }
    let settingsTunnel = "Bu Mac'e her yerden ulaş"
    let settingsTunnelQuick = "Üretilen bir adres"
    let settingsTunnelNamed = "Kendi alan adım"
    let settingsTunnelHostname = "Host adı"
    let settingsTunnelHint = "cloudflared üzerinden bu Mac'ten dışarı doğru bir bağlantı açar — port yönlendirme yok, ağında dinleyen hiçbir şey yok. Bir cihaz eşleşene kadar başlamaz, çünkü tünelin arkasında bu Mac'teki her depo adı ve her görev başlığı var."
    let settingsRemoteWrite = "Eşleşmiş bir cihaz bir oturuma yazabilsin"
    let settingsRemoteWriteHint = "Kapalıyken eşleşmiş bir cihaz yalnızca okuyabilir. Açıkken bir oturuma metin gönderebilir ve yeni oturumlar başlatabilir — bu da bu Mac'te kod çalıştırmak demektir, çünkü Claude Code'un yaptığı şey tam olarak budur. Yukarıdakinden başka bir karar, o yüzden ayrı bir anahtar."
    let settingsRemotePhone = "Telefon eşleştir…"
    let settingsRemotePhoneHint = "Taranacak bir kod gösterir. Kodun kendine ait bir anahtarı vardır: fotoğrafı çekilirse ortaya çıkan, bu listede görüp istediğin an kaldırabileceğin bir cihazdır — bu Mac'in kendi anahtarı değil."
    let pairingScanTitle = "Bunu telefonla tara"
    let pushWaiting = "bir yanıt bekliyor"
    let pushTest = "Bu bir deneme bildirimi. Her şey bağlı."
    let pushFinished = "uzun bir işi bitirdi"
    let pushDeployOk = "deploy başarıyla bitti"
    let pushDeployFail = "deploy hata verdi"
    func pushChildWaiting(minutes: Int?) -> String {
        guard let minutes else { return "alt oturumu yanıt bekliyor" }
        return "alt oturumu yanıt bekliyor — \(minutes) dk kaldı"
    }
    func pushBatchDone(done: Int, failed: Int) -> String {
        let all = "\(done) görevi bitirdi"
        return failed == 0 ? all : "\(all), \(failed) başarısız"
    }
    let settingsPushFinish = "Uzun bir iş bitince haber ver"
    let settingsPushFinishHint = "Yalnızca iki dakikayı geçenler."
    let settingsPushDeploy = "Deploy bitince haber ver"
    let settingsPushDeployHint = "Başarı da hata da."
    let settingsOrchestrator = "İşi başka oturuma verme"
    let settingsOrchestratorEnabled = "Bir oturum işi başka bir oturuma verebilsin"
    let settingsOrchestratorEnabledHint = "clawdline becerisi olan bir oturum yeni bir sekme açıp yönergeleri yazabilir ve iş bitince haber alır. Kapalıyken her istek geri çevrilir; hâlihazırda çalışan hiçbir şey durdurulmaz."
    let settingsOrchestratorMax = "Aynı anda alt oturum"
    let settingsOrchestratorMaxHint = "Varsayılan beş; Mac başına değil, oturum başına sayılır. Her biri, içinde bir asistanın çalıştığı bir terminal sekmesi."
    let settingsOrchestratorSubMax = "Ve alt oturumun devredebileceği"
    let settingsOrchestratorSubMaxHint = "Varsayılan üç. Birinin işini yapan bir oturum kendi alt oturumlarını açabilir; onların altında bir şey açılmaz."
    let settingsOrchestratorSubMaxNone = "Yok — alt oturum devretmez"
    let settingsOrchestratorPermission = "Alt oturum kendi başına nereye kadar"
    let settingsOrchestratorPermissionHint = "Bir alt oturumun sekmesine kimse bakmıyor; onay için duran bir oturum süresi dolana kadar durur — ve görevlendirilen bir oturumun işi baştan sona komut çalıştırmak ve dosya yazmaktır, dolayısıyla son basamağın altındaki her şey onu bir yerde durdurur. Bir görev bundan azını isteyebilir, fazlasını asla."
    let settingsOrchestratorPermissionAsk = "Her adımdan önce sor"
    let settingsOrchestratorPermissionEdits = "Dosya yazarken sorma"
    let settingsOrchestratorPermissionFull = "Hiç sorma"
    let settingsOrchestratorNotify = "İsteyen oturuma haber ver"
    let settingsOrchestratorNotifyHint = "İş bittiğinde o oturuma tek satır yazılır."
    let settingsOrchestratorClose = "Alt oturum haber verince"
    let settingsOrchestratorCloseHint = "Haber verdikten sonra sekmesi kapatılır; süresi dolanınki okuyabilesin diye açık kalır."
    let settingsOrchestratorCloseNow = "Sekmeyi hemen kapat"
    let settingsOrchestratorCloseLinger = "Üç dakika sonra kapat"
    let settingsOrchestratorCloseKeep = "Açık bırak"
    let settingsOrchestratorPolicy = "İş nasıl dağıtılır"
    let settingsOrchestratorPolicyHint = "Clawdline her görev verişte okuduğu ve kendisi de görev verebilen her alt oturumun yönergesine kopyaladığı kurallar: hangi asistan, hangi model, grafiğin nasıl bir şekli olmalı. Boşsa kural yok."
    let settingsOrchestratorPolicyEdit = "Kuralları düzenle"
    func settingsOrchestratorPolicyOn(_ lines: Int) -> String { return "Yürürlükte — \(lines) satır" }
    let settingsOrchestratorPolicyOff = "Kural yok — her seferinde veren kendisi karar verir"
    func childAnnounce(_ title: String) -> String { "Clawdline'dan gelen görev alındı: \(title) — şimdi başlıyorum." }
    func settingsSeconds(_ value: Double) -> String { String(format: "%.1f sn", value) }

    let webConnLive = "canlı"
    let webConnConnecting = "bağlanıyor"
    let webConnRetrying = "{n} sn sonra tekrar"
    let webConnOffline = "bağlantı yok"
    let webConnLocked = "eşleşme yok"
    let webConnTipLive = "Uygulamadan canlı akıyor"
    let webConnTipLocked = "Bu tarayıcı Mac ile eşleşmedi"
    let webConnTipDown = "Bağlantı yok — şimdi denemek için tıkla"

    let webCountWorking = "{n} çalışıyor"
    let webCountWaiting = "{n} bekliyor"
    let webCountUnreadable = "{n} okunamadı"
    let webCountQuietOne = "{n} oturum, hepsi sakin"
    let webCountQuietMany = "{n} oturum, hepsi sakin"
    let webCountNone = "oturum yok"

    let webFilterPlaceholder = "Göreve, projeye ya da tty'ye göre süz"
    let webFilterLabel = "Oturumları süz"
    let webListLabel = "Claude Code oturumları"
    let webPull = "Yenilemek için çek"
    let webPullRelease = "Yenilemek için bırak"
    let webPullBusy = "Yenileniyor…"
    let webEmptyFilterTitle = "“{q}” ile eşleşen yok"
    let webEmptyFilterHint = "Esc süzgeci temizler"
    let webEmptyLockedTitle = "Bu cihaz eşleşmiş değil"
    let webEmptyLockedHint = "Uygulama 401 döndü — Mac'teki Clawdline'dan eşleştir"
    let webEmptyNoneHint = "Bir terminalde başlat, burada beliriverir"
    let webEmptyWaitTitle = "Uygulama bekleniyor"
    let webEmptyWaitHint = "Akıştan henüz bir şey gelmedi"
    let webStateUnreadable = "ekran okunamadı"
    let webStateWorking = "çalışıyor"

    let webBack = "Oturumlar"
    let webBackLabel = "Oturum listesine dön"
    let webNoSessionOpen = "Açık oturum yok"
    let webOrderTip = "Dökümü ters çevir (r)"
    let webShowOnMac = "Mac'te göster"
    let webShowOnMacTip = "Bu oturumun terminalini Mac'te öne getirir"
    let webShowOnMacOff = "Sunucu write: false diyor — henüz hiçbir şey gönderilemez"
    let webShowOnMacAsked = "Mac'ten öne getirmesi istendi"
    let webSessionActions = "Oturum işlemleri"
    let webSessionGit = "Git değişiklikleri"
    let webGitTitle = "Git değişiklikleri"
    let webGitClean = "Çalışma ağacı temiz"
    let webGitNotRepo = "Git deposu değil"
    let webGitFailed = "Git değişiklikleri okunamadı"
    let webGitRefresh = "Yenile"
    let webGitClose = "Kapat"
    let webGitStaged = "Hazırlanmış"
    let webGitUnstaged = "Hazırlanmamış"
    let webGitUntracked = "İzlenmeyen"
    let webGitConflict = "Çakışma"
    let webEndSession = "Oturumu kapat"
    let webConfirmActionTitle = "{action} çalıştırılsın mı?"
    let webConfirmActionSay = "Bu, geçerli oturuma {action} gönderir."
    let webConfirmEndTitle = "Bu oturum kapatılsın mı?"
    let webConfirmEndSay = "Asistan çıkacak, ardından terminal sekmesi kapanacak."
    let webClosing = "Kapatılıyor…"
    let webCancel = "İptal"
    let webConfirm = "Onayla"
    let webPickSession = "Soldan bir oturum seç."
    let webReading = "Okunuyor…"
    let webLoading = "Yükleniyor…"
    let webTranscriptFailed = "Döküm okunamadı"
    let webWhoYou = "sen"
    let webWhoTool = "araç"
    let webPending = "Mac bekleniyor…"
    let webAttachedImage = "{n} resim eklendi"
    let webAttachedImages = "{n} resim eklendi"
    let webSteps = "{n} adım"
    let webJustNow = "az önce"
    let webMinutesAgo = "{n} dk önce"

    let webSend = "Gönder"
    let webAttach = "Resim ekle"
    let webRemoveShot = "{name} dosyasını kaldır"
    let webWriteOpen = "Yazmak için bir oturum aç."
    let webWriteOff = "*Gönderme kapalı* — sunucu `write: false` diyor. Kutu bağlı; bu değiştiği anda kendi kendine açılır."
    let webShotsOnlyPictures = "Bir mesajla yalnızca resim gidebilir"
    let webShotsTooMany = "Bir mesaj en çok {n} resim taşıyabilir"
    let webShotTooBig = "Bu resim küçültülse bile gönderilemeyecek kadar büyük"
    let webShotsTooBig = "Bu resimler birlikte gönderilemeyecek kadar büyük"
    let webShotUnreadable = "Bu resim okunamadı"
    let webShotNeedsSession = "Resim göndermek için bir oturum aç"

    let webVoiceStart = "Bir mesaj dikte et"
    let webVoiceStop = "Durdur ve yazıya dök"
    let webVoiceDone = "Bitti"
    let webVoiceListening = "Dinliyor… {t}"
    let webVoiceReading = "Mac'te yazıya dökülüyor… {n} sn"
    let webVoiceSlow = "Bu Mac yeniden başladıktan sonraki ilki önce modeli yüklüyor — on iki saniye kadar."
    let webVoiceLimit = "Kayıt {n} dakikada durdu; bir kayıt en fazla bu kadar sürer. Elde olan yazıya dökülüyor."
    let webVoiceEmpty = "Orada bir şey duyulmadı."
    let webVoiceTooShort = "Duyulamayacak kadar kısaydı."
    let webVoiceDenied = "Mikrofon reddedildi. Bu tarayıcının bu site için tuttuğu ayarlardan geri aç."
    let webVoiceNoMic = "Bu cihazda mikrofon bulunamadı."
    let webVoiceInUse = "Mikrofon meşgul — bu cihazda başka bir şey onu tutuyor."
    let webVoiceInsecure = "Mikrofon https ister, bu sayfa ise onun üzerinde değil. Tünel bir tane sağlar; yerel ağdaki düz bir adres sağlamaz."
    let webVoiceUnsupported = "Bu tarayıcı ses kaydedemiyor."
    let webVoiceBusy = "Biri yazıya dökülüyor, bir diğeri sırada bekliyor. Birazdan tekrar dene."
    let webVoiceNoBinary = "Mac'te Whisper kurulu değil, orada bunu yazıya dökecek bir şey yok."
    let webVoiceNoModel = "Mac'te Whisper var ama okuyacak modeli yok. `~/.cache/whisper` içinde bir ggml dosyası ona yeter."
    let webVoiceFailed = "Bu yazıya dökülemedi."

    let webHintMove = "gezin"
    let webHintOpen = "aç"
    let webHintFilter = "süz"
    let webHintPane = "panel"

    let webKeysLabel = "Klavye kısayolları"
    let webKeysTitle = "Klavye"
    let webKeysMove = "Listede gezin — `j` ve `k` de aynı işi yapar"
    let webKeysOpen = "Seçili oturumu aç"
    let webKeysFilter = "Listeyi süz"
    let webKeysEscape = "Önce süzgeci temizler, sonra geri gider"
    let webKeysList = "Oturum listesine odaklan"
    let webKeysPane = "Dökümü göster ya da gizle"
    let webKeysEnds = "Dökümün başı ya da sonu"
    let webKeysReverse = "Döküm sırasını ters çevir"
    let webKeysThis = "Bu kart"
    let webKeysFoot = "Bir metin kutusuna yazılan her şey o kutuda kalır — sen yazarken kısayollar geri çekilir."

    let webDoorLabel = "Bu tarayıcıyı eşleştir"
    let webDoorAskLede = "Bu tarayıcı henüz içeri alınmadı."
    let webDoorAskFine = "Eşleşme iste, altı haneli bir kod *Mac'te* belirsin — bu sayfaya gelen yanıtta bilerek yok. Bunu ancak o makinenin başındaki biri bitirebilir; bu bir engel değil, işin güvenliği tam olarak bu."
    let webDoorName = "Bu cihaza bir ad ver"
    let webDoorAsk = "Eşleşme iste"
    let webDoorToPassword = "Bunun yerine parolayla gir"
    let webDoorCodeLede = "Mac'e bak."
    let webDoorCodeFine = "Clawdline {left} boyunca altı hane gösteriyor. Onları buraya yaz."
    let webDoorTwoMinutes = "iki dakika"
    let webDoorDigit = "{n}. hane"
    let webDoorConfirm = "Bu cihazı eşleştir"
    let webDoorRestart = "Baştan başla"
    let webDoorPasswordLede = "Parolayla gir."
    let webDoorPasswordFine = "Mac'teki Clawdline'da, Ayarlar → Uzaktan erişim altında belirlenen parola. Hiç belirlenmemişse içeri giden yol eşleşmedir."
    let webDoorPassword = "Parola"
    let webDoorPasswordGo = "Gir"
    let webDoorToPair = "Bunun yerine eşleşme kodu kullan"
    let webDoorAsking = "Mac'e soruluyor…"
    let webDoorAskFailed = "Mac'e sorulamadı."
    let webDoorRateLimited = "Her istek Mac'te bir uyarı çıkarır, o yüzden on dakikada yalnızca üç tane var."
    let webDoorSixDigits = "Altı hane."
    let webDoorChecking = "Kontrol ediliyor…"
    let webDoorFinished = "Bu eşleşme bitti — beş kod yanlış girildi. Mac'in başındayken yeniden iste."
    let webDoorWrongCode = "Bu kod doğru değil."
    let webDoorNeedPassword = "Önce parola."
    let webDoorWrongPassword = "Parola bu değil."
    let webDoorExpired = "Bu kodun süresi doldu. Yeniden iste, Mac'te yenisi belirir."
    let webDoorPaired = "Eşleşti — bu tarayıcı içeride"

    let webOffline = "Clawdline'a ulaşılamadı. Mac'te hâlâ çalışıyor mu?"
    let webNotJSON = "Sunucu JSON olmayan bir şey gönderdi"
    let webRequestFailed = "İstek tamamlanamadı"

    let webNotifyGo = "Haber ver"
    let webNotifyAsking = "İzin isteniyor…"
    let webNotifyStop = "Durdur"
    let webNotifyStopping = "Durduruluyor…"
    let webNotifyOff = "bir oturum yanıt beklediğinde"
    let webNotifyOn = "Bu cihaz kayıtlı. Neyin haber verileceği Mac'te belirlenir."
    let webNotifyBlocked = "Bu site için bildirimler engellenmiş. O anahtar tarayıcının kendi ayarlarında, burada değil."
    let webNotifyUnsupported = "Bu tarayıcı bildirim gösteremiyor."
    let webNotifyHomeScreen = "clawdline'ı ana ekrana ekle ve oradan aç — iOS bildirimi yalnızca orada duran bir uygulamaya gönderir."
    let webNotifyOnFailed = "Bildirimler açılamadı"
    let webNotifyOffFailed = "Bildirimler kapatılamadı"

    let webSettings = "Ayarlar"
    let webSettingsNotify = "Bildirimler"
    let webSettingsAssistantIcons = "Asistan simgeleri"
    let webSettingsAssistantIconsSay = "Konuşmada Claude veya Codex adından önce simgesini göster."
    let webSettingsAssistantIconsShow = "Simgeleri göster"
    let webSettingsVersion = "Sürüm {v}"
    let webClose = "Kapat"
    let webNotifySheetOff = "Bir oturum beklerken bu cihaza haber verilmiyor."
    let webNotifyTest = "Deneme gönder"
    let webNotifyTestSent = "Gönderildi — birazdan bu cihaza ulaşması gerek."
    let webNotifyTestNone = "Mac'te bu cihaz için kayıt yok. Bildirimleri kapatıp yeniden aç, bu tarayıcı yenisini kaydeder."
    let webNotifyTestFailed = "Deneme bildirimi gönderilemedi"
    let webSending = "Gönderiliyor…"
    let webSendTip = "Return gönderir · Shift-Return satır açar"
    let webStart = "Oturum başlat"
    let webStartLabel = "Bir projede oturum başlat"
    let webStartPick = "Nerede başlasın?"
    let webStartWith = "Hangisiyle başlasın?"
    let webStartEmpty = "Henüz başlanacak bir yer yok. Mac'te bir kez Claude Code çalıştır, burada belirir."
    let webStartFilter = "Projeleri süz"
    let webStarting = "Sekme açılıyor…"
    let webStartWaiting = "Başladı. Görünmesi bekleniyor…"
    let webStartSlow = "Sekme açık ama oturum henüz haber vermedi. Mac'e bir bak."
    let webStartFailed = "Bu başlatılamadı."
    let webStartGone = "O proje artık Mac'te yok."
    let webStartTerminalClosed = "{app} Mac'te çalışmıyor. Orada aç ve yeniden dene."
    let webStartTerminalUnsupported = "Buradan {app} içinde oturum başlatılamaz. İçinde tmux çalıştırırsan bu iş görür."
    let webStartOff = "Oturum başlatma kapalı. Mac'te Ayarlar → Uzaktan erişim onu açar."
    let webResumeWith = "Öncekini sürdür"
    let webResumePick = "Hangi konuşma?"
    let webResumeFilter = "Konuşmaları süz"
    let webResumeEmpty = "O projede henüz hiçbir şey kaydedilmedi."
    let webResumeLive = "açık"
    let webResumeBack = "Başka bir proje"
    let webResumeGone = "O konuşma artık Mac'te değil."
    let webResumeClaudeOnly = "Sürdürülebilir konuşmaları yalnızca Claude Code saklar."
    let webResuming = "Kaldığı yerden açılıyor…"
    let webCommand = "Ne başlatılacağını söyle"
    let webCommandLabel = "Ne yapılacağını söyleyerek oturum başlat"
    let webCommandSay = "Aşağıdaki Başlat'a basana kadar hiçbir şey gönderilmez."
    let webCommandHeard = "Ne yapmalı?"
    let webCommandThinking = "Düşünüyor…"
    let webCommandDraft = "Taslak"
    let webCommandWhere = "Nerede"
    let webCommandWith = "Hangisiyle"
    let webCommandFirst = "İlk mesaj"
    let webCommandGo = "Başlat"
    let webCommandUnsure = "Hangi proje olduğu belli değil — aşağıdan birini seç."
    let webCommandFailed = "Bu taslağa dönüştürülemedi."
    let webCommandNoPlanner = "Bu Mac'te bunu taslağa dönüştürecek Claude Code yok."
    let webCommandBusy = "Zaten bir cümle taslağa dönüştürülüyor — birazdan tekrar dene."
    let webCommandEmpty = "Hiçbir şey duyulmadı"
    let webLinks = "Adresler"
    let webLinksTip = "Bu proje nerede açılır"
    let webLinksPick = "Bu projenin adresi olan her şey."
    let webLinksEmpty = "Bu projenin adresi olan hiçbir şeyi yok — site yok, deploy yok, çalışan sunucu da yok."
    let webLinksFailed = "Bu projenin adresleri okunamadı."
    let webLinksLocal = "Yalnızca Mac'in kendi ağında. Buradan açılmaz."
    let webLinksFile = "Mac'teki bir dosya. Orada açılır, bu tarayıcıda değil."
    let webLinksCopy = "Yolu kopyala"
    let webLinksCopied = "Kopyalandı."
    let webLinksCopyFailed = "Bu tarayıcı sayfanın onu kopyalamasına izin vermedi."
    let webLinkOk = "iyi"
    let webLinkFail = "hata"
    let webLinkDown = "kapalı"
    let webLinkRunning = "sürüyor"
    let webSessionInfo = "Oturum bilgisi"
    let webInfoTitle = "Bu oturum hakkında"
    let webInfoSession = "Bu oturum"
    let webInfoAssistant = "Asistan"
    let webInfoModel = "Model"
    let webInfoSessionId = "Oturum kimliği"
    let webInfoDirectory = "Dizin"
    let webInfoRunningFor = "Çalışma süresi"
    let webInfoUsage = "Token kullanımı"
    let webInfoInput = "Girdi"
    let webInfoOutput = "Çıktı"
    let webInfoCacheRead = "Önbellekten okunan"
    let webInfoCacheWrite = "Önbelleğe yazılan"
    let webInfoTotal = "Toplam"
    let webInfoCost = "Tahmini maliyet"
    let webInfoNoUsage = "Bu oturumun kaydı henüz bulunamadı."
    let webInfoLimits = "Plan limitleri"
    let webInfoLimitHit = "limite ulaşıldı"
    let webInfoResets = "{when} sıfırlanır"
    let webInfoUnknown = "bilinmiyor"
    let webInfoFiles = "Dosyalar"
    let webInfoBranch = "Dal"
    let webInfoStaged = "Hazırlanan"
    let webInfoUnstaged = "Değişen"
    let webInfoUntracked = "İzlenmeyen"
    let webInfoConflict = "Çakışmalar"
    let webInfoClean = "Commit edilmemiş bir şey yok."
    let webInfoNotRepo = "Bir git deposu değil."
    let webInfoDeploy = "Son deploy"
    let webInfoNoDeploy = "Bu proje için kayıtlı bir deploy yok."
    let webInfoFailed = "Bu oturumun bilgisi okunamadı."
    let webInfoRefresh = "Yenile"
    let webInfoTokens = "token"
    let webInfoSwitchModel = "Modeli değiştir"
    let webInfoModelOther = "başka bir model…"
    let webInfoModelSent = "/model {model} gönderildi. Doğrulanıyor…"
    let webInfoModelBusy = "Değişiklik oturum boşta kalana kadar bekler."
    let webInfoSwitchPermission = "İzin modunu değiştir"
    let webInfoPermissionAuto = "Otomatik"
    let webInfoPermissionManual = "El ile"
    let webInfoPermissionAcceptEdits = "Düzenlemeleri kabul et"
    let webInfoPermissionPlan = "Plan"
    let webInfoPermissionUnreadable = "Geçerli mod okunamadı."
    let webInfoPermissionSent = "{mode} moduna geçildi. Doğrulanıyor…"
    let webInfoPermissionBusy = "İzin modu değiştiriliyor."
    let webInfoLimitsClaude = "Claude Code bir pencereyi ancak tükenince yazar; o zamana kadar bir şey bilinmez."
    let webInfoCopied = "Oturum kimliği kopyalandı."
    let webInfoAsOf = "{when} itibarıyla"
    let webInfoWhyUnknown = "Neden bilinmiyor, ve sayılar nasıl alınır"
    let webSettingsOrder = "Döküm"
    let webSettingsOrderSay = "Döküm hangi uçtan okunmaya başlasın. Her oturum için geçerli, klavyede `r` de aynısını yapar."
    let webAskLabel = "sordu"
    let webAskAny = "Bunlardan kaç tane istersen"
    let webWaitingTitle = "Bu oturum yanıt bekliyor"
    let webWaitingSay = "Claude Code Mac'te bir menü gösteriyor. Clawdline buradan bir menüyü henüz okuyamıyor, seçenekler yalnızca o ekranda."
    let webWaitingSend = "*Buradan göndermek yanıtını menüye yazmaz* — menüde o an hangi satır seçiliyse onu onaylar, o da nadiren senin kastettiğindir. Bunu Mac'te yanıtla."
    let webMenuSay = "Bir yanıta dokun, doğrudan oturuma gider."
    let webMenuHighlighted = "seçili"
    let webMenuSent = "Yanıt gönderildi."
    let webAgents = "Arka plandaki ajanlar"
    let webAgentsCount = "{n} çalışıyor"
    let webAgentDone = "bitti"
    let webAgentFailed = "başarısız"
    let webShells = "Arka plandaki shell'ler"
    let webShellTitle = "Arka plandaki shell"
    let webShellOpen = "Bu komutun ne yazdığını gör"
    let webShellRunning = "hâlâ çalışıyor"
    let webShellEnded = "bitti"
    let webShellQuiet = "Henüz bir şey yazmadı."
    let webShellFailed = "Bu komutun çıktısı okunamadı."
    let webShellClose = "Kapat"
    let webShellStop = "Durdur"
    let webShellStopTitle = "Bu komut durdurulsun mu?"
    let webShellStopSay = "{command} hâlâ çalışıyor. Önce durması isteniyor, beş saniye sonra hâlâ duruyorsa öldürülüyor. Şimdiye kadar yaptıkları geri alınmaz."
    let webShellStopped = "Durması istendi."
    let webShellStopFailed = "Durdurulamadı."
    let agentRunning = "çalışıyor"
    let agentTools = "{n} araç"
    let agentEmpty = "Bu ajan henüz hiçbir şey yazmadı."
    let agentBack = "Oturum"
    let webAgentOpen = "Bu ajanın ne yaptığını gör"
    let webTaskRoot = "Kök"
    let webTaskChild = "Alt"
    let webTaskTasks = "Görevler"
    let webTaskDone = "bitti"
    let webTaskFailed = "başarısız"
    let webTaskRunning = "çalışıyor"
    let webStale = "Clawdline Mac'te yeniden derlendi. Bu sayfa eski olanı."
    let webStaleGo = "Yeniden yükle"

    let menuOpen = "Giriş çubuğunu aç"
    let menuReveal = "Hedef sekmeye git"
    let menuMascot = "Maskot"
    let menuLogin = "Girişte başlat"
    let menuEditConfig = "Ayarlar…"
    let menuReload = "Ayarları yeniden yükle"
    let menuQuit = "Clawdline'dan çık"
    let menuNoTarget = "(henüz bulunamadı)"

    func hotkeyFailedTitle(_ combo: String) -> String { "\(combo) kaydedilemedi" }
    func hotkeyFailedBody(_ configPath: String) -> String {
        """
        Büyük ihtimalle başka bir uygulama almış — Spotlight, klavye düzeni değiştirici, \
        BetterTouchTool ve benzerleri.

        Başka birini seç: \(configPath) içindeki "hotkey" değerini düzenle, sonra menü \
        çubuğundan "Ayarları yeniden yükle" seçeneğini seç.

        O zamana kadar menü çubuğundaki ✳ giriş çubuğunu açmayı sürdürür.
        """
    }
    let loginFailed = "Girişte başlatma ayarlanamadı"
}
