import Foundation

struct Indonesian: Copy {
    let placeholder = "Tulis ke Claude Code…"

    let hintSend = "kirim"
    let hintNewline = "baris baru"
    let hintSwitch = "ganti"
    let hintList = "daftar"
    let hintMascot = "maskot"
    let hintOutput = "keluaran"
    let hintFullscreen = "layar penuh"
    let hintKeys = "tombol"
    let hintTextSize = "ukuran teks"
    let hintOrder = "balik urutan"
    let hintVoice = "dikte"
    func voiceListening(onDevice: Bool) -> String {
        onDevice ? "Mendengarkan di Mac ini — tekan lagi untuk berhenti"
                 : "Mendengarkan — bahasa ini ditranskripsi oleh Apple, bukan di Mac ini"
    }
    let voiceNoPermission = "Dikte memerlukan izin mikrofon dan pengenalan suara"
    let voiceUnavailable = "Dikte sedang tidak tersedia"
    func voiceTranscribing(seconds: Double) -> String {
        String(format: "Whisper sedang membacanya ulang… %.1f dtk", seconds)
    }
    let whisperMissing = "Whisper belum terpasang — lihat docs/whisper.md"
    let whisperNothingHeard = "Tidak terdengar apa pun"
    func dictationStatus(_ status: Whisper.Status) -> String {
        switch status {
        case .ready(let model): return "Dikte: Apple, lalu Whisper (\(model))"
        case .noBinary: return "Dikte: hanya Apple — tidak ada whisper-cli"
        case .noModel: return "Dikte: hanya Apple — whisper-cli ada, modelnya belum"
        }
    }
    func voiceListeningWhisper() -> String {
        "Mendengarkan — Whisper membaca ulang begitu kamu berhenti"
    }

    let scanning = "Mencari…"
    let noSession = "Tidak ada sesi Claude Code yang ditemukan"
    let nothingToSend = "Tidak ada tujuan — jalankan dulu Claude Code di terminal"
    let sendFailed = "Gagal mengirim"
    let itermSilent = "iTerm2 tidak merespons"
    let scriptMissing = "iterm.js tidak ada — bundel aplikasi rusak?"
    let cannotList = "Tidak bisa membaca sesi iTerm2"
    let noOutput = "Belum ada yang bisa dibaca dari sesi ini."
    func outputSize(_ pt: Int) -> String { "Ukuran teks keluaran \(pt) pt — ⌘J untuk melihat" }
    func foldedTools(_ count: Int) -> String { "\(count) langkah" }
    func outputOrder(newestFirst: Bool) -> String {
        newestFirst ? "Terbaru di atas" : "Terlama di atas"
    }
    func backlogNow(_ count: Int) -> String { "sekarang \(count)" }
    func dropped(_ count: Int) -> String {
        count == 1 ? "Path ditambahkan — Claude Code yang membacanya" : "\(count) path ditambahkan"
    }
    func stackConfirm(_ command: String) -> String { "Tekan lagi untuk menjalankan:  \(command)" }
    let hintStacks = "server"
    func stackTip(up: Int, total: Int) -> String { "\(up) dari \(total) server aktif — ⌘S untuk daftarnya" }
    let stackTipUnknown = "Proyek ini punya server, tetapi perintah status-nya belum dipercaya — ⌘S"
    let stackUntrusted = "belum dipercaya"
    let stackExit = "keluar"
    let stackActionStart = "mulai"
    let stackActionRestart = "mulai ulang"
    let stackActionStop = "hentikan"
    let stackActionLogs = "log"
    let stackLogAll = "semua"
    let stackLogBack = "transkrip"
    let stackActionAllow = "izinkan"
    let stackActionAgain = "tekan lagi"
    func sessionTip(index: Int, total: Int) -> String { "Sesi \(index) dari \(total) — ⌘K untuk berpindah" }
    let sessionWaiting = "menunggu jawabanmu"
    let sessionAgents = "{n} di latar belakang"
    let islandDone = "selesai"
    let islandAllSessions = "Semua sesi…"
    func statusWaiting(_ labels: [String]) -> String {
        labels.count == 1 ? "\(labels[0]) menunggu jawabanmu"
                          : "\(labels.count) sesi menunggu jawabanmu"
    }
    func statusWorking(_ count: Int) -> String { "\(count) sedang berjalan" }

    let settingsTitle = "Pengaturan Clawdline"
    let settingsGeneral = "Umum"
    let settingsBar = "Bilah"
    let settingsReading = "Membaca"
    let settingsVoice = "Dikte"
    let settingsHotkey = "Pintasan"
    let settingsRecording = "Tekan tombol…"
    let settingsScope = "Aktif di"
    let settingsScopeGlobal = "Di semua aplikasi"
    let settingsScopeHint = "Kosong berarti di mana saja, jadi mengeluarkan yang terakhir akan menyalakan sakelar di atas — dan mematikannya lagi mengembalikan daftarnya. Berkas konfigurasi menyimpannya sebagai bundle id, dan daftar yang disunting tangan tetap jalan."
    let settingsScopeAdd = "Tambah aplikasi…"
    let settingsScopeChoose = "Pilih aplikasi…"
    let settingsScopeRunning = "Terbuka sekarang"
    let settingsScopeRemove = "Keluarkan"
    let settingsLanguage = "Bahasa"
    let settingsReopen = "Bilahnya datang dan pergi bersama terminal"
    let settingsReopenHint = "Berpindah menjauh dari terminal menyimpan bilahnya, dan kembali ke terminal memunculkannya lagi. Esc-lah yang berarti sudah selesai."
    let settingsFollow = "Terminal menampilkan apa pun yang sedang dibidik bilahnya"
    let settingsFollowHint = "Ia memilih tab sesi itu. Ia tidak membawa terminal ke depan — kalau tidak, setiap kali Tab ditekan papan ketik akan keluar dari kotak yang sedang kamu tulis."
    let settingsCodexAutoName = "Namai sesi Codex baru"
    let settingsCodexAutoNameHint = "Menjalankan satu turn kecil Codex Luna untuk setiap sesi tanpa nama. Menggunakan permintaan pertama, memakai kuota Codex, dan tidak mengganti nama pilihanmu."
    let settingsNotch = "Tinggal di poni layar"
    let settingsNotchHint = "Karakter di rumah kamera. Mati berarti mati — tidak digambar, tidak ada jendela."
    let settingsPosition = "Tinggi di layar"
    let settingsWidth = "Lebar"
    let settingsOpacity = "Opasitas kartu"
    let settingsShow = "Tampilkan"
    let settingsPaneHeight = "Tinggi panel"
    let settingsTextSize = "Ukuran teks"
    let settingsPaneFont = "Font panel"
    let settingsBlur = "Buram di belakang"
    let settingsNewestFirst = "Terbaru dulu"
    let settingsEngine = "Pengenal suara"
    let settingsSettle = "Jeda mengakhiri kalimat"
    let settingsStop = "Sunyi mengakhiri sesi"
    let settingsAuto = "Otomatis"
    let settingsTranscript = "Transkrip"
    let settingsTerminal = "Terminal"
    let settingsOff = "Mati"
    let settingsHooks = "Hook Claude Code"
    let settingsHooksHint = "Setelah dipasang, Claude Code memberi tahu saat sebuah giliran dimulai, selesai, atau menunggu jawaban — bukan menunggu Clawdline melihatnya pada pemeriksaan berikutnya. Semuanya tetap dibaca dari layar; ini hanya menentukan secepat apa."
    let settingsHooksInstall = "Pasang"
    let settingsHooksRemove = "Lepas"
    let settingsHooksOff = "Belum dipasang — semua dibaca dari layar"
    let settingsHooksOn = "Terpasang — belum ada sesi yang melapor"
    let settingsHooksLive = "Terpasang, dan sesi sedang melapor"
    let settingsStateHook = "Saat sebuah sesi berganti keadaan"
    let settingsStateHookHint = "Setiap kali sebuah sesi mulai bekerja, selesai, atau menanyakan sesuatu kepadamu, Clawdline menjalankan ini: programmu sendiri, dengan rinciannya di lingkungan program itu. Ditulis di berkas konfigurasi dan bukan di sini karena ini argv, bukan baris perintah — path yang ada spasinya harus tetap satu path."
    let settingsRemote = "Akses jarak jauh"
    let settingsRemoteServe = "Biarkan peramban atau ponselmu melihat sesimu"
    let settingsRemoteHint = "Mati, tidak ada apa pun di luar Mac ini yang bisa menjangkau apa pun. Menyala, daftar sesi disajikan di 127.0.0.1 — untuk peramban di sini, untuk ponsel lewat terowongan, untuk skrip. Yang diserahkan adalah nama repositori, branch, dan judul tugas, dan karena itulah ia tetap mati sampai kamu berkata lain."
    let settingsRemoteDevices = "Perangkat berpasangan"
    let settingsRemoteNoDevices = "Belum ada — tidak ada apa pun di luar Mac ini yang bisa membaca apa pun"
    let settingsRemoteRevokeAll = "Putuskan semua"
    let settingsRemoteOpen = "Buka di peramban"
    let pairingIgnore = "Abaikan"
    func pairingAsks(_ device: String) -> String { "\(device) ingin berpasangan dengan Mac ini" }
    func pairingCode(_ code: String) -> String {
        """
        Ketik kode ini di perangkat itu:

        \(code)

        Berlaku dua menit. Kalau bukan kamu yang barusan meminta, abaikan saja — tanpa kode \
        ini yang meminta tidak bisa menyelesaikannya.
        """
    }
    let settingsTunnel = "Jangkau Mac ini dari mana saja"
    let settingsTunnelQuick = "Alamat buatan otomatis"
    let settingsTunnelNamed = "Domain milikku"
    let settingsTunnelHostname = "Nama host"
    let settingsTunnelHint = "Membuka koneksi keluar lewat cloudflared — tanpa penerusan port, tidak ada yang mendengarkan di jaringanmu. Tidak akan mulai sebelum ada satu perangkat berpasangan, karena di balik terowongan itu ada setiap nama repositori dan setiap judul tugas di Mac ini."
    let settingsRemoteWrite = "Biarkan perangkat berpasangan menulis ke dalam sesi"
    let settingsRemoteWriteHint = "Mati, perangkat berpasangan hanya bisa membaca. Menyala, ia bisa mengirim teks ke dalam sesi dan memulai sesi baru — dan itu menjalankan kode di Mac ini, karena memang itu yang dikerjakan Claude Code. Ini keputusan yang lain dari yang di atas, jadi sakelarnya juga lain."
    let settingsRemotePhone = "Pasangkan ponsel…"
    let settingsRemotePhoneHint = "Menampilkan kode untuk dipindai. Kode itu membawa kuncinya sendiri, jadi foto kode itu cuma satu perangkat yang terlihat di daftar ini dan bisa kamu cabut lagi — bukan kunci Mac ini sendiri."
    let pairingScanTitle = "Pindai ini dengan ponsel"
    let pushWaiting = "menunggu jawaban"
    let pushTest = "Ini notifikasi percobaan. Semuanya sudah tersambung."
    let pushFinished = "selesai setelah berjalan lama"
    let pushDeployOk = "berhasil di-deploy"
    let pushDeployFail = "gagal di-deploy"
    let settingsPushFinish = "Beri tahu kalau pekerjaan panjang selesai"
    let settingsPushFinishHint = "Hanya yang lebih dari dua menit."
    let settingsPushDeploy = "Beri tahu kalau deploy selesai"
    let settingsPushDeployHint = "Baik berhasil maupun gagal."
    let settingsOrchestrator = "Menitipkan pekerjaan"
    let settingsOrchestratorEnabled = "Biarkan satu sesi menitipkan pekerjaan ke sesi lain"
    let settingsOrchestratorEnabledHint = "Sesi yang punya skill clawdline bisa membuka tab baru, mengetikkan instruksinya, lalu diberi tahu setelah pekerjaannya selesai. Kalau mati, setiap permintaan ditolak; yang sudah berjalan tidak dihentikan."
    let settingsOrchestratorMax = "Sesi anak sekaligus"
    let settingsOrchestratorMaxHint = "Tiga secara bawaan. Masing-masing satu tab terminal dengan satu asisten bekerja di dalamnya."
    let settingsOrchestratorNotify = "Beri tahu sesi yang meminta"
    let settingsOrchestratorNotifyHint = "Satu baris diketikkan kembali ke sana saat tugasnya selesai."
    let settingsOrchestratorClose = "Saat sesi anak melapor"
    let settingsOrchestratorCloseHint = "Tabnya ditutup setelah melapor — yang kehabisan waktu dibiarkan terbuka supaya bisa kamu baca."
    let settingsOrchestratorCloseNow = "Tutup tabnya langsung"
    let settingsOrchestratorCloseLinger = "Tutup setelah tiga menit"
    let settingsOrchestratorCloseKeep = "Biarkan terbuka"
    func childAnnounce(_ title: String) -> String { "Tugas dari Clawdline diterima: \(title) — mulai dikerjakan sekarang." }
    func settingsSeconds(_ value: Double) -> String { String(format: "%.1f dtk", value) }

    let webConnLive = "langsung"
    let webConnConnecting = "menyambung"
    let webConnRetrying = "coba lagi {n} dtk"
    let webConnOffline = "terputus"
    let webConnLocked = "belum berpasangan"
    let webConnTipLive = "Mengalir langsung dari aplikasinya"
    let webConnTipLocked = "Peramban ini belum dipasangkan dengan Mac"
    let webConnTipDown = "Tidak tersambung — klik untuk mencoba sekarang"

    let webCountWorking = "{n} berjalan"
    let webCountWaiting = "{n} menunggu"
    let webCountUnreadable = "{n} tak terbaca"
    let webCountQuietOne = "{n} sesi, semuanya tenang"
    let webCountQuietMany = "{n} sesi, semuanya tenang"
    let webCountNone = "tidak ada sesi"

    let webFilterPlaceholder = "Saring menurut tugas, proyek, atau tty"
    let webFilterLabel = "Saring sesi"
    let webListLabel = "Sesi Claude Code"
    let webPull = "Tarik untuk menyegarkan"
    let webPullRelease = "Lepas untuk menyegarkan"
    let webPullBusy = "Menyegarkan…"
    let webEmptyFilterTitle = "Tidak ada yang cocok dengan “{q}”"
    let webEmptyFilterHint = "Esc menghapus saringannya"
    let webEmptyLockedTitle = "Perangkat ini belum berpasangan"
    let webEmptyLockedHint = "Aplikasinya menjawab 401 — pasangkan dari Clawdline di Mac"
    let webEmptyNoneHint = "Mulai satu di terminal dan ia muncul di sini"
    let webEmptyWaitTitle = "Menunggu aplikasinya"
    let webEmptyWaitHint = "Belum ada apa pun yang datang lewat sambungan"
    let webStateUnreadable = "layarnya tidak terbaca"
    let webStateWorking = "berjalan"

    let webBack = "Sesi"
    let webBackLabel = "Kembali ke daftar sesi"
    let webNoSessionOpen = "Tidak ada sesi terbuka"
    let webOrderTip = "Balik urutan transkrip (r)"
    let webShowOnMac = "Tampilkan di Mac"
    let webShowOnMacTip = "Bawa terminal sesi ini ke depan di Mac"
    let webShowOnMacOff = "Server melaporkan write: false — belum ada yang bisa dikirim"
    let webShowOnMacAsked = "Mac sudah diminta membawanya ke depan"
    let webSessionActions = "Tindakan sesi"
    let webSessionGit = "Perubahan Git"
    let webGitTitle = "Perubahan Git"
    let webGitClean = "Tidak ada perubahan di direktori kerja"
    let webGitNotRepo = "Bukan repositori Git"
    let webGitFailed = "Perubahan Git tidak dapat dibaca"
    let webGitRefresh = "Muat ulang"
    let webGitClose = "Tutup"
    let webGitStaged = "Disiapkan"
    let webGitUnstaged = "Belum disiapkan"
    let webGitUntracked = "Belum dilacak"
    let webGitConflict = "Konflik"
    let webEndSession = "Tutup sesi"
    let webConfirmActionTitle = "Jalankan {action}?"
    let webConfirmActionSay = "Ini mengirim {action} ke sesi saat ini."
    let webConfirmEndTitle = "Tutup sesi ini?"
    let webConfirmEndSay = "Asisten akan keluar, lalu tab terminalnya ditutup."
    let webClosing = "Menutup…"
    let webCancel = "Batal"
    let webConfirm = "Konfirmasi"
    let webPickSession = "Pilih sesi di sebelah kiri."
    let webReading = "Membaca…"
    let webLoading = "Memuat…"
    let webTranscriptFailed = "Transkripnya tidak bisa dibaca"
    let webWhoYou = "kamu"
    let webWhoTool = "alat"
    let webPending = "Menunggu Mac…"
    let webAttachedImage = "{n} gambar terlampir"
    let webAttachedImages = "{n} gambar terlampir"
    let webSteps = "{n} langkah"
    let webJustNow = "barusan"
    let webMinutesAgo = "{n} menit lalu"

    let webSend = "Kirim"
    let webAttach = "Lampirkan gambar"
    let webRemoveShot = "Hapus {name}"
    let webWriteOpen = "Buka sebuah sesi untuk menulis ke sana."
    let webWriteOff = "*Pengiriman mati* — server melaporkan `write: false`. Kotaknya sudah tersambung; ia menyala sendiri begitu itu berubah."
    let webShotsOnlyPictures = "Yang bisa ikut sebuah pesan hanya gambar"
    let webShotsTooMany = "Satu pesan paling banyak membawa {n} gambar"
    let webShotTooBig = "Gambar itu terlalu besar untuk dikirim, sekalipun dikecilkan"
    let webShotsTooBig = "Gambar-gambar itu terlalu besar untuk dikirim bersamaan"
    let webShotUnreadable = "Gambar itu tidak bisa dibaca"
    let webShotNeedsSession = "Buka sebuah sesi untuk mengirim gambar ke sana"

    let webHintMove = "pindah"
    let webHintOpen = "buka"
    let webHintFilter = "saring"
    let webHintPane = "panel"

    let webKeysLabel = "Pintasan papan ketik"
    let webKeysTitle = "Papan ketik"
    let webKeysMove = "Berpindah di daftar — `j` dan `k` sama saja"
    let webKeysOpen = "Buka sesi yang dipilih"
    let webKeysFilter = "Saring daftarnya"
    let webKeysEscape = "Hapus saringannya, lalu mundur"
    let webKeysList = "Fokus ke daftar sesi"
    let webKeysPane = "Tampilkan atau sembunyikan transkrip"
    let webKeysEnds = "Awal atau akhir transkrip"
    let webKeysReverse = "Balik urutan transkrip"
    let webKeysThis = "Kartu ini"
    let webKeysFoot = "Apa pun yang diketik di kotak teks tetap di kotak teks — pintasannya mundur selama kamu menulis."

    let webDoorLabel = "Pasangkan peramban ini"
    let webDoorAskLede = "Peramban ini belum diizinkan masuk."
    let webDoorAskFine = "Minta dipasangkan, lalu kode enam angka muncul *di Mac* — sengaja tidak ikut dalam jawaban ke halaman ini. Hanya orang yang ada di depan mesin itu yang bisa menyelesaikannya, dan justru di situlah pengamanannya, bukan penghalangnya."
    let webDoorName = "Beri nama perangkat ini"
    let webDoorAsk = "Minta dipasangkan"
    let webDoorToPassword = "Masuk pakai kata sandi saja"
    let webDoorCodeLede = "Lihat ke Mac."
    let webDoorCodeFine = "Clawdline menampilkan enam angka selama {left}. Ketik di sini."
    let webDoorTwoMinutes = "dua menit"
    let webDoorDigit = "Angka ke-{n}"
    let webDoorConfirm = "Pasangkan perangkat ini"
    let webDoorRestart = "Mulai lagi"
    let webDoorPasswordLede = "Masuk dengan kata sandi."
    let webDoorPasswordFine = "Yang disetel di Clawdline di Mac, di Pengaturan → Akses jarak jauh. Kalau belum ada, jalan masuknya lewat berpasangan."
    let webDoorPassword = "Kata sandi"
    let webDoorPasswordGo = "Masuk"
    let webDoorToPair = "Pakai kode pemasangan saja"
    let webDoorAsking = "Bertanya ke Mac…"
    let webDoorAskFailed = "Tidak bisa bertanya ke Mac."
    let webDoorRateLimited = "Setiap permintaan memunculkan peringatan di Mac, jadi hanya ada tiga tiap sepuluh menit."
    let webDoorSixDigits = "Enam angka."
    let webDoorChecking = "Memeriksa…"
    let webDoorFinished = "Pemasangan itu sudah habis — lima kode salah. Minta lagi saat kamu ada di depan Mac."
    let webDoorWrongCode = "Kode itu tidak cocok."
    let webDoorNeedPassword = "Kata sandinya dulu."
    let webDoorWrongPassword = "Itu bukan kata sandinya."
    let webDoorExpired = "Kode itu sudah kedaluwarsa. Minta lagi dan yang baru muncul di Mac."
    let webDoorPaired = "Berpasangan — peramban ini sudah masuk"

    let webOffline = "Clawdline tidak terjangkau. Apakah ia masih jalan di Mac?"
    let webNotJSON = "Server mengirim sesuatu yang bukan JSON"
    let webRequestFailed = "Permintaan gagal"

    let webNotifyGo = "Beri tahu aku"
    let webNotifyAsking = "Meminta izin…"
    let webNotifyStop = "Hentikan"
    let webNotifyStopping = "Menghentikan…"
    let webNotifyOff = "kalau ada sesi yang menunggu jawaban"
    let webNotifyOn = "Perangkat ini sudah berlangganan. Apa saja yang dikabarkan diatur di Mac."
    let webNotifyBlocked = "Notifikasi diblokir untuk situs ini. Sakelarnya ada di pengaturan peramban sendiri, bukan di sini."
    let webNotifyUnsupported = "Peramban ini tidak bisa menampilkan notifikasi."
    let webNotifyHomeScreen = "Tambahkan clawdline ke layar utama dan buka dari sana — iOS hanya mengirim notifikasi ke aplikasi yang tinggal di sana."
    let webNotifyOnFailed = "Tidak bisa menyalakan notifikasi"
    let webNotifyOffFailed = "Tidak bisa mematikan notifikasi"

    let webSettings = "Pengaturan"
    let webSettingsNotify = "Notifikasi"
    let webSettingsAssistantIcons = "Ikon asisten"
    let webSettingsAssistantIconsSay = "Tampilkan tanda Claude atau Codex sebelum namanya dalam percakapan."
    let webSettingsAssistantIconsShow = "Tampilkan ikon"
    let webSettingsVersion = "Versi {v}"
    let webClose = "Tutup"
    let webNotifySheetOff = "Perangkat ini tidak dikabari saat ada sesi yang menunggu."
    let webNotifyTest = "Kirim percobaan"
    let webNotifyTestSent = "Terkirim — sebentar lagi mestinya sampai di perangkat ini."
    let webNotifyTestNone = "Mac tidak punya langganan untuk perangkat ini. Matikan lalu nyalakan lagi notifikasinya, dan peramban ini akan mendaftarkan yang baru."
    let webNotifyTestFailed = "Tidak bisa mengirim notifikasi percobaan"
    let webSending = "Mengirim…"
    let webSendTip = "Return mengirim · Shift-Return membuat baris baru"
    let webStart = "Mulai sesi"
    let webStartLabel = "Mulai sesi di sebuah proyek"
    let webStartPick = "Mulai di mana?"
    let webStartWith = "Mulai dengan apa?"
    let webStartEmpty = "Belum ada tempat untuk memulai. Jalankan Claude Code sekali di Mac dan tempatnya muncul di sini."
    let webStartFilter = "Saring proyek"
    let webStarting = "Membuka tab…"
    let webStartWaiting = "Sudah dimulai. Menunggu ia muncul…"
    let webStartSlow = "Tab-nya sudah terbuka, tetapi sesinya belum melapor. Coba lihat Mac-nya."
    let webStartFailed = "Itu tidak bisa dimulai."
    let webStartGone = "Proyek itu sudah tidak ada di Mac."
    let webStartTerminalClosed = "{app} tidak sedang jalan di Mac. Buka di sana lalu coba lagi."
    let webStartTerminalUnsupported = "Sesi tidak bisa dimulai di {app} dari sini. Jalankan tmux di dalamnya dan ini akan jalan."
    let webStartOff = "Memulai sesi sedang dimatikan. Pengaturan → Akses jarak jauh di Mac yang menyalakannya."
    let webLinks = "Tautan"
    let webLinksTip = "Di mana proyek ini bisa dibuka"
    let webLinksPick = "Semua yang punya alamat di proyek ini."
    let webLinksEmpty = "Proyek ini tidak punya apa pun yang beralamat — tidak ada situs, tidak ada deploy, tidak ada server yang berjalan."
    let webLinksFailed = "Tautan proyek ini tidak bisa dibaca."
    let webLinksLocal = "Hanya di jaringan Mac sendiri. Dari sini tidak akan terbuka."
    let webLinksFile = "Sebuah berkas di Mac. Terbukanya di sana, bukan di peramban ini."
    let webLinksCopy = "Salin path"
    let webLinksCopied = "Tersalin."
    let webLinksCopyFailed = "Peramban ini tidak mengizinkan halaman menyalin itu."
    let webLinkOk = "oke"
    let webLinkFail = "gagal"
    let webLinkDown = "mati"
    let webLinkRunning = "berjalan"
    let webSessionInfo = "Info sesi"
    let webInfoTitle = "Tentang sesi ini"
    let webInfoSession = "Sesi ini"
    let webInfoAssistant = "Asisten"
    let webInfoModel = "Model"
    let webInfoSessionId = "ID sesi"
    let webInfoDirectory = "Direktori"
    let webInfoRunningFor = "Sudah berjalan"
    let webInfoUsage = "Pemakaian token"
    let webInfoInput = "Masukan"
    let webInfoOutput = "Keluaran"
    let webInfoCacheRead = "Cache dibaca"
    let webInfoCacheWrite = "Cache ditulis"
    let webInfoTotal = "Total"
    let webInfoCost = "Perkiraan biaya"
    let webInfoNoUsage = "Transkrip sesi ini belum ditemukan."
    let webInfoLimits = "Batas paket"
    let webInfoLimitHit = "batas tercapai"
    let webInfoResets = "direset {when}"
    let webInfoUnknown = "tidak diketahui"
    let webInfoFiles = "Berkas"
    let webInfoBranch = "Branch"
    let webInfoStaged = "Sudah di-stage"
    let webInfoUnstaged = "Berubah"
    let webInfoUntracked = "Belum dilacak"
    let webInfoConflict = "Konflik"
    let webInfoClean = "Tidak ada yang belum di-commit."
    let webInfoNotRepo = "Bukan repositori git."
    let webInfoDeploy = "Deploy terakhir"
    let webInfoNoDeploy = "Tidak ada catatan deploy untuk proyek ini."
    let webInfoFailed = "Info sesi ini tidak bisa dibaca."
    let webInfoRefresh = "Muat ulang"
    let webInfoTokens = "token"
    let webInfoSwitchModel = "Ganti model"
    let webInfoModelOther = "model lain…"
    let webInfoModelSent = "/model {model} terkirim. Kartu menampilkannya setelah balasan berikutnya."
    let webInfoModelBusy = "Penggantian menunggu sampai sesi diam."
    let webInfoLimitsClaude = "Claude Code baru mencatat sebuah jendela setelah habis, jadi sebelum itu tidak ada yang diketahui."
    let webInfoCopied = "Id sesi disalin."
    let webInfoAsOf = "per {when}"
    let webInfoWhyUnknown = "Mengapa tidak diketahui, dan cara mendapatkan angkanya"
    let webSettingsOrder = "Transkrip"
    let webSettingsOrderSay = "Transkrip mulai dibaca dari ujung yang mana. Ini berlaku untuk setiap sesi, dan dari papan ketik `r` melakukan hal yang sama."
    let webAskLabel = "bertanya"
    let webAskAny = "Berapa saja dari ini"
    let webWaitingTitle = "Sesi ini sedang menunggu jawaban"
    let webWaitingSay = "Claude Code sedang menampilkan menu di Mac. Clawdline belum bisa membaca menu dari sini, jadi pilihannya hanya ada di layar itu."
    let webWaitingSend = "*Mengirim dari sini tidak akan mengetikkan jawabanmu ke menu itu* — yang disahkan adalah pilihan yang sedang tersorot di menu, dan itu jarang yang kamu maksud. Yang satu ini jawab di Mac."
    let webMenuSay = "Ketuk satu jawaban, langsung dikirim ke sesi itu."
    let webMenuHighlighted = "disorot"
    let webMenuSent = "Jawaban terkirim."
    let webAgents = "Agen di latar belakang"
    let webAgentsCount = "{n} berjalan"
    let webAgentDone = "selesai"
    let webAgentFailed = "gagal"
    let agentRunning = "berjalan"
    let agentTools = "{n} alat"
    let agentEmpty = "Agen ini belum menuliskan apa pun."
    let agentBack = "Sesi"
    let webAgentOpen = "Lihat apa yang dikerjakan agen ini"
    let webTaskRoot = "Induk"
    let webTaskChild = "Anak"
    let webTaskTasks = "Tugas"
    let webTaskDone = "selesai"
    let webTaskFailed = "gagal"
    let webTaskRunning = "berjalan"
    let webStale = "Clawdline sudah dibangun ulang di Mac. Halaman ini yang lama."
    let webStaleGo = "Muat ulang"

    let menuOpen = "Buka bilah masukan"
    let menuReveal = "Ke tab tujuan"
    let menuMascot = "Maskot"
    let menuLogin = "Jalankan saat masuk"
    let menuEditConfig = "Pengaturan…"
    let menuReload = "Muat ulang konfigurasi"
    let menuQuit = "Keluar dari Clawdline"
    let menuNoTarget = "(belum terdeteksi)"

    func hotkeyFailedTitle(_ combo: String) -> String { "Tidak bisa mendaftarkan \(combo)" }
    func hotkeyFailedBody(_ configPath: String) -> String {
        """
        Kemungkinan besar sudah dipakai aplikasi lain — Spotlight, pengganti metode \
        masukan, BetterTouchTool, dan sejenisnya.

        Pilih yang lain: ubah "hotkey" di \(configPath), lalu pilih \
        "Muat ulang konfigurasi" dari bilah menu.

        Sementara itu, ✳ di bilah menu tetap membuka bilah masukan.
        """
    }
    let loginFailed = "Tidak bisa mengatur jalan saat masuk"
}
