import Foundation

/// India has the largest population of open-source contributors on GitHub, and almost all of
/// them work in English — so this is here for the people who would rather not, which is a real
/// group and not the same one. Technical nouns stay in Latin script (`terminal`, `session`,
/// `Whisper`) because that is how they are said, not because they were left untranslated.
struct Hindi: Copy {
    let placeholder = "Claude Code को लिखें…"

    let hintSend = "भेजें"
    let hintNewline = "नई पंक्ति"
    let hintSwitch = "बदलें"
    let hintList = "सूची"
    let hintMascot = "मैस्कॉट"
    let hintOutput = "आउटपुट"
    let hintFullscreen = "पूरी स्क्रीन"
    let hintKeys = "कुंजियाँ"
    let hintTextSize = "अक्षर आकार"
    let hintOrder = "उल्टा क्रम"
    let hintVoice = "बोलकर लिखें"
    func voiceListening(onDevice: Bool) -> String {
        onDevice ? "इसी Mac पर सुन रहा है — रोकने के लिए फिर दबाएँ"
                 : "सुन रहा है — यह भाषा Apple के यहाँ लिखी जाती है, इस Mac पर नहीं"
    }
    let voiceNoPermission = "बोलकर लिखने के लिए माइक्रोफ़ोन और वाक् पहचान की अनुमति चाहिए"
    let voiceUnavailable = "अभी बोलकर लिखना उपलब्ध नहीं है"
    func voiceTranscribing(seconds: Double) -> String {
        String(format: "Whisper दोबारा पढ़ रहा है… %.1f से॰", seconds)
    }
    let whisperMissing = "Whisper इंस्टॉल नहीं है — docs/whisper.md देखें"
    let whisperNothingHeard = "कुछ सुनाई नहीं दिया"
    func dictationStatus(_ status: Whisper.Status) -> String {
        switch status {
        case .ready(let model): return "बोलकर लिखना: पहले Apple, फिर Whisper (\(model))"
        case .noBinary: return "बोलकर लिखना: सिर्फ़ Apple — whisper-cli नहीं है"
        case .noModel: return "बोलकर लिखना: सिर्फ़ Apple — whisper-cli है, मॉडल नहीं"
        }
    }
    func voiceListeningWhisper() -> String {
        "सुन रहा है — आपके रुकते ही Whisper एक बार और पढ़ेगा"
    }

    let scanning = "खोज रहा है…"
    let noSession = "Claude Code का कोई session नहीं मिला"
    let nothingToSend = "भेजने की कोई जगह नहीं — पहले किसी terminal में Claude Code चलाएँ"
    let sendFailed = "भेजा नहीं जा सका"
    let itermSilent = "iTerm2 ने जवाब नहीं दिया"
    let itermBusy = "iTerm2 एक डायलॉग के जवाब का इंतज़ार कर रहा है — उसे Mac पर बंद करें"
    let scriptMissing = "iterm.js नहीं मिला — app bundle खराब है?"
    let cannotList = "iTerm2 के sessions पढ़े नहीं जा सके"
    let noOutput = "इस session में अभी पढ़ने को कुछ नहीं है।"
    func outputSize(_ pt: Int) -> String { "आउटपुट का अक्षर आकार \(pt)pt — देखने के लिए ⌘J" }
    func foldedTools(_ count: Int) -> String { "\(count) चरण" }
    func outputOrder(newestFirst: Bool) -> String {
        newestFirst ? "नए पहले" : "पुराने पहले"
    }
    func backlogNow(_ count: Int) -> String { "अभी \(count)" }
    func dropped(_ count: Int) -> String {
        count == 1 ? "पथ जोड़ दिया — Claude Code उसे पढ़ लेगा" : "\(count) पथ जोड़े"
    }
    func stackConfirm(_ command: String) -> String { "चलाने के लिए फिर से दबाएँ:  \(command)" }
    let hintStacks = "सर्वर"
    func stackTip(up: Int, total: Int) -> String { "\(total) में से \(up) सर्वर चालू — सूची के लिए ⌘S" }
    let stackTipUnknown = "इस प्रोजेक्ट में सर्वर हैं, पर इसकी status कमांड पर अभी भरोसा नहीं किया गया — ⌘S"
    let stackUntrusted = "अभी अनुमति नहीं"
    let stackExit = "एग्ज़िट कोड"
    let stackActionStart = "शुरू"
    let stackActionRestart = "रीस्टार्ट"
    let stackActionStop = "रोकें"
    let stackActionLogs = "लॉग"
    let stackLogAll = "सभी"
    let stackLogBack = "ट्रांसक्रिप्ट"
    let stackActionAllow = "अनुमति"
    let stackActionAgain = "फिर दबाएँ"
    func sessionTip(index: Int, total: Int) -> String { "\(total) में से \(index) वाँ सेशन — बदलने के लिए ⌘K" }
    let sessionWaiting = "आपके जवाब का इंतज़ार"
    let sessionAgents = "बैकग्राउंड में {n}"
    let sessionShellOne = "1 shell चल रहा है"
    let sessionShellMany = "{n} shell चल रहे हैं"
    let islandDone = "हो गया"
    let islandAllSessions = "सभी सेशन…"
    func statusWaiting(_ labels: [String]) -> String {
        labels.count == 1 ? "\(labels[0]) आपके जवाब का इंतज़ार कर रहा है"
                          : "\(labels.count) सेशन आपके जवाब का इंतज़ार कर रहे हैं"
    }
    func statusWorking(_ count: Int) -> String { "\(count) चल रहे हैं" }

    let settingsTitle = "Clawdline सेटिंग्ज़"
    let settingsGeneral = "सामान्य"
    let settingsBar = "बार"
    let settingsReading = "पढ़ना"
    let settingsVoice = "श्रुतलेख"
    let settingsHotkey = "हॉटकी"
    let settingsRecording = "कुंजियाँ दबाएँ…"
    let settingsScope = "कहाँ चले"
    let settingsScopeGlobal = "हर ऐप में"
    let settingsScopeHint = "खाली मतलब हर जगह, इसलिए आख़िरी वाला हटाते ही ऊपर वाला switch चालू हो जाता है — और उसे फिर से बंद करने पर सूची लौट आती है। config फ़ाइल इन्हें bundle id की तरह रखती है, और हाथ से लिखी सूची भी उतनी ही चलती है।"
    let settingsScopeAdd = "ऐप जोड़ें…"
    let settingsScopeChoose = "ऐप चुनें…"
    let settingsScopeRunning = "अभी खुले हुए"
    let settingsScopeRemove = "हटाएँ"
    let settingsLanguage = "भाषा"
    let settingsReopen = "बार टर्मिनल के साथ आती और जाती है"
    let settingsReopenHint = "टर्मिनल से हटते ही बार छिप जाती है, और टर्मिनल पर लौटते ही वापस आ जाती है। काम हो गया, इसका मतलब Esc है।"
    let settingsFollow = "बार जिस पर टिकी है, टर्मिनल वही दिखाता है"
    let settingsFollowHint = "यह उस session का tab चुन लेता है। टर्मिनल को सामने नहीं लाता — वरना हर बार Tab दबाते ही keyboard उस डिब्बे से निकल जाता जिसमें आप लिख रहे हैं।"
    let settingsCodexAutoName = "नई Codex sessions को नाम दें"
    let settingsCodexAutoNameHint = "हर बिना नाम वाली session के लिए एक छोटा Codex Luna turn चलाता है। यह पहली request इस्तेमाल करता है, Codex usage खर्च करता है और आपका चुना नाम नहीं बदलता।"
    let settingsNotch = "नॉच में रहे"
    let settingsNotchHint = "कैमरा हाउसिंग में एक किरदार। बंद माने बंद — कुछ नहीं बनता, कोई विंडो नहीं।"
    let settingsPosition = "स्क्रीन पर ऊँचाई"
    let settingsWidth = "चौड़ाई"
    let settingsOpacity = "कार्ड की अपारदर्शिता"
    let settingsShow = "दिखाएँ"
    let settingsPaneHeight = "पैनल की ऊँचाई"
    let settingsTextSize = "टेक्स्ट का आकार"
    let settingsPaneFont = "पैनल का फ़ॉन्ट"
    let settingsBlur = "पीछे धुँधलापन"
    let settingsNewestFirst = "नया पहले"
    let settingsEngine = "पहचानकर्ता"
    let settingsSettle = "ठहराव वाक्य ख़त्म करता है"
    let settingsStop = "सन्नाटा सत्र ख़त्म करता है"
    let settingsAuto = "स्वतः"
    let settingsTranscript = "ट्रांसक्रिप्ट"
    let settingsTerminal = "टर्मिनल"
    let settingsOff = "बंद"
    let settingsHooks = "Claude Code हुक"
    let settingsHooksHint = "ये लगे होने पर Claude Code उसी क्षण बता देता है जब कोई बारी शुरू होती है, ख़त्म होती है या जवाब माँगती है — Clawdline को अगली बार देखने तक इंतज़ार नहीं करना पड़ता। पढ़ा फिर भी स्क्रीन से ही जाता है; यह सिर्फ़ यह तय करता है कि कितनी जल्दी।"
    let settingsHooksInstall = "लगाएँ"
    let settingsHooksRemove = "हटाएँ"
    let settingsHooksOff = "नहीं लगे — सब कुछ स्क्रीन से पढ़ा जाता है"
    let settingsHooksOn = "लगे हैं — अभी किसी सत्र ने कुछ नहीं बताया"
    let settingsHooksLive = "लगे हैं, और सत्र बता रहे हैं"
    let settingsStateHook = "जब किसी session की स्थिति बदले"
    let settingsStateHookHint = "जब भी कोई session काम शुरू करे, ख़त्म करे, या आपसे कुछ पूछे, Clawdline यह चलाता है: आपका अपना प्रोग्राम, और ब्यौरा उसके environment में। यह यहाँ नहीं, config फ़ाइल में लिखा जाता है, क्योंकि यह command line नहीं बल्कि argv है — जिस path में space हो, उसे एक ही path बने रहना है।"
    let settingsRemote = "रिमोट पहुँच"
    let settingsRemoteServe = "browser या अपने फ़ोन को अपने session देखने दें"
    let settingsRemoteHint = "बंद हो तो इस Mac के बाहर से कुछ भी कहीं तक नहीं पहुँचता। चालू हो तो session की सूची 127.0.0.1 पर परोसी जाती है — यहाँ के browser के लिए, tunnel के पार रखे फ़ोन के लिए, किसी script के लिए। उसमें जो सौंपा जाता है वह repository के नाम, branch और काम के शीर्षक हैं, इसीलिए जब तक आप ख़ुद न कहें यह बंद ही रहता है।"
    let settingsRemoteDevices = "जुड़े हुए डिवाइस"
    let settingsRemoteNoDevices = "अभी कोई नहीं — इस Mac के बाहर से कुछ भी नहीं पढ़ा जा सकता"
    let settingsRemoteRevokeAll = "सभी हटाएँ"
    let settingsRemoteOpen = "browser में खोलें"
    let pairingIgnore = "अनदेखा करें"
    func pairingAsks(_ device: String) -> String { "\(device) इस Mac से जुड़ना चाहता है" }
    func pairingCode(_ code: String) -> String {
        """
        उस डिवाइस में यह कोड डालें:

        \(code)

        यह दो मिनट तक चलता है। अगर अभी आपने यह नहीं माँगा, तो अनदेखा कर दें — जिसने माँगा \
        है, वह इस कोड के बिना आगे नहीं बढ़ सकता।
        """
    }
    let settingsTunnel = "इस Mac तक कहीं से भी पहुँचें"
    let settingsTunnelQuick = "अपने आप बना पता"
    let settingsTunnelNamed = "मेरा अपना डोमेन"
    let settingsTunnelHostname = "होस्टनेम"
    let settingsTunnelHint = "cloudflared के ज़रिये इसी Mac से बाहर की ओर जुड़ता है — न port forwarding, न आपके नेटवर्क पर कुछ सुनता हुआ। जब तक कोई डिवाइस जुड़ा न हो, यह चालू नहीं होगा, क्योंकि tunnel के उस पार इस Mac का हर repository नाम और हर काम का शीर्षक है।"
    let settingsRemoteWrite = "जुड़े हुए डिवाइस को किसी session में लिखने दें"
    let settingsRemoteWriteHint = "बंद हो तो जुड़ा हुआ डिवाइस सिर्फ़ पढ़ सकता है। चालू हो तो वह किसी session में लिख भी सकता है और नए session शुरू भी कर सकता है — यानी इस Mac पर कोड चलता है, क्योंकि Claude Code यही करता है। यह ऊपर वाले से अलग फ़ैसला है, इसलिए इसका स्विच भी अलग है।"
    let settingsRemotePhone = "फ़ोन जोड़ें…"
    let settingsRemotePhoneHint = "scan करने के लिए एक code दिखाता है। उस code की अपनी एक चाबी होती है, इसलिए उसकी तस्वीर से बनता है बस एक डिवाइस — जो इसी सूची में दिखेगा और जिसे कभी भी हटाया जा सकता है — इस Mac की अपनी चाबी नहीं।"
    let pairingScanTitle = "इसे फ़ोन से scan करें"
    let pushWaiting = "जवाब का इंतज़ार कर रहा है"
    let pushTest = "यह एक test notification है। सब कुछ जुड़ा हुआ है।"
    let pushFinished = "ने एक लंबा काम पूरा किया"
    let pushDeployOk = "का deploy सफल रहा"
    let pushDeployFail = "का deploy फ़ेल हो गया"
    let settingsPushFinish = "लंबा काम पूरा होने पर बताएँ"
    let settingsPushFinishHint = "सिर्फ़ दो मिनट से लंबे कामों के लिए।"
    let settingsPushDeploy = "deploy ख़त्म होने पर बताएँ"
    let settingsPushDeployHint = "सफल हो या फ़ेल, दोनों पर।"
    let settingsOrchestrator = "काम दूसरे session को देना"
    let settingsOrchestratorEnabled = "एक session दूसरे को काम सौंप सके"
    let settingsOrchestratorEnabledHint = "clawdline स्किल वाला session एक नया टैब खोलकर उसमें निर्देश टाइप कर सकता है, और काम पूरा होने पर उसे ख़बर मिल जाती है। बंद रहने पर हर अनुरोध ठुकरा दिया जाता है; जो पहले से चल रहा है वह नहीं रुकता।"
    let settingsOrchestratorMax = "एक साथ कितने चाइल्ड session"
    let settingsOrchestratorMaxHint = "डिफ़ॉल्ट पाँच, और यह गिनती हर session की अपनी है, पूरे Mac की नहीं। हर एक टर्मिनल का एक टैब है जिसमें एक एजेंट काम कर रहा है।"
    let settingsOrchestratorSubMax = "और चाइल्ड session खुद कितने भेजे"
    let settingsOrchestratorSubMaxHint = "डिफ़ॉल्ट तीन। किसी का काम कर रहा session अपने खुद के खोल सकता है; उनके नीचे कुछ नहीं खुलता।"
    let settingsOrchestratorSubMaxNone = "कुछ नहीं — चाइल्ड आगे नहीं भेजता"
    let settingsOrchestratorPermission = "चाइल्ड कहाँ तक खुद जा सकता है"
    let settingsOrchestratorPermissionHint = "चाइल्ड के टैब को कोई नहीं देख रहा होता, इसलिए मंज़ूरी के लिए रुका हुआ session समय ख़त्म होने तक रुका रहता है — और भेजे गए session का पूरा काम ही कमांड चलाना और फ़ाइलें लिखना है, तो आख़िरी विकल्प से कम कुछ भी उसे कहीं न कहीं रोक देगा। कोई काम इससे कम माँग सकता है, ज़्यादा नहीं।"
    let settingsOrchestratorPermissionAsk = "हर क़दम पर पूछे"
    let settingsOrchestratorPermissionEdits = "फ़ाइल लिखते समय न पूछे"
    let settingsOrchestratorPermissionFull = "कभी न पूछे"
    let settingsOrchestratorNotify = "जिसने कहा था उस session को बताना"
    let settingsOrchestratorNotifyHint = "काम ख़त्म होते ही उसमें एक पंक्ति टाइप कर दी जाती है।"
    let settingsOrchestratorClose = "चाइल्ड session के ख़बर देने पर"
    let settingsOrchestratorCloseHint = "ख़बर देने के बाद उसका टैब बंद कर दिया जाता है — जिसका समय ख़त्म हो गया, वह आपके पढ़ने के लिए खुला छोड़ दिया जाता है।"
    let settingsOrchestratorCloseNow = "टैब तुरंत बंद कर दें"
    let settingsOrchestratorCloseLinger = "तीन मिनट बाद बंद करें"
    let settingsOrchestratorCloseKeep = "खुला ही रहने दें"
    let settingsOrchestratorPolicy = "काम कैसे बाँटा जाए"
    let settingsOrchestratorPolicyHint = "हर बार काम भेजते समय Clawdline इन नियमों को पढ़ता है और आगे भेज सकने वाले हर चाइल्ड की हिदायत में इन्हें जोड़ देता है: कौन-सा एजेंट, कौन-सा मॉडल, ग्राफ़ किस आकार का हो। खाली मतलब कोई नियम नहीं।"
    let settingsOrchestratorPolicyEdit = "नियम बदलें"
    func settingsOrchestratorPolicyOn(_ lines: Int) -> String { return "लागू — \(lines) पंक्तियाँ" }
    let settingsOrchestratorPolicyOff = "कोई नियम नहीं — हर बार भेजने वाला खुद तय करता है"
    func childAnnounce(_ title: String) -> String { "Clawdline से काम मिल गया: \(title) — अभी शुरू कर रहा हूँ।" }
    func settingsSeconds(_ value: Double) -> String { String(format: "%.1f से॰", value) }

    let webConnLive = "लाइव"
    let webConnConnecting = "जुड़ रहा है"
    let webConnRetrying = "{n} से॰ बाद फिर"
    let webConnOffline = "ऑफ़लाइन"
    let webConnLocked = "जुड़ा नहीं"
    let webConnTipLive = "app से सीधे आ रहा है"
    let webConnTipLocked = "यह browser अभी इस Mac से जुड़ा नहीं है"
    let webConnTipDown = "जुड़ा नहीं है — अभी कोशिश करने के लिए दबाएँ"

    let webCountWorking = "{n} चल रहे"
    let webCountWaiting = "{n} इंतज़ार में"
    let webCountUnreadable = "{n} पढ़े नहीं गए"
    let webCountQuietOne = "{n} session, सब शांत"
    let webCountQuietMany = "{n} session, सब शांत"
    let webCountNone = "कोई session नहीं"

    let webFilterPlaceholder = "काम, प्रोजेक्ट या tty से छाँटें"
    let webFilterLabel = "session छाँटें"
    let webListLabel = "Claude Code के session"
    let webPull = "ताज़ा करने को खींचें"
    let webPullRelease = "ताज़ा करने को छोड़ें"
    let webPullBusy = "ताज़ा हो रहा है…"
    let webEmptyFilterTitle = "“{q}” से कुछ नहीं मिला"
    let webEmptyFilterHint = "Esc छाँट हटा देता है"
    let webEmptyLockedTitle = "यह डिवाइस जुड़ा नहीं है"
    let webEmptyLockedHint = "app ने 401 कहा — Mac पर Clawdline से जोड़ें"
    let webEmptyNoneHint = "किसी terminal में एक शुरू करें, वह यहाँ दिखने लगेगा"
    let webEmptyWaitTitle = "app का इंतज़ार"
    let webEmptyWaitHint = "stream पर अभी कुछ नहीं आया"
    let webStateUnreadable = "स्क्रीन पढ़ी नहीं जा सकी"
    let webStateWorking = "चल रहा है"

    let webBack = "सूची"
    let webBackLabel = "session की सूची पर लौटें"
    let webNoSessionOpen = "कोई session खुला नहीं"
    let webOrderTip = "ट्रांसक्रिप्ट उलटें (r)"
    let webShowOnMac = "Mac पर दिखाएँ"
    let webShowOnMacTip = "इस session का terminal Mac पर सामने ले आएँ"
    let webShowOnMacOff = "server कहता है write: false — अभी कुछ भेजा नहीं जा सकता"
    let webShowOnMacAsked = "Mac से सामने लाने को कह दिया"
    let webSessionActions = "session के काम"
    let webSessionGit = "Git बदलाव"
    let webGitTitle = "Git बदलाव"
    let webGitClean = "वर्किंग ट्री में कोई बदलाव नहीं"
    let webGitNotRepo = "यह Git रिपॉज़िटरी नहीं है"
    let webGitFailed = "Git बदलाव पढ़े नहीं जा सके"
    let webGitRefresh = "रीफ़्रेश करें"
    let webGitClose = "बंद करें"
    let webGitStaged = "स्टेज किया हुआ"
    let webGitUnstaged = "स्टेज नहीं किया हुआ"
    let webGitUntracked = "ट्रैक नहीं किया हुआ"
    let webGitConflict = "टकराव"
    let webEndSession = "session बंद करें"
    let webConfirmActionTitle = "{action} चलाएँ?"
    let webConfirmActionSay = "यह मौजूदा session में {action} भेजेगा।"
    let webConfirmEndTitle = "यह session बंद करें?"
    let webConfirmEndSay = "assistant पहले बंद होगा, फिर उसका terminal tab बंद होगा।"
    let webClosing = "बंद हो रहा है…"
    let webCancel = "रद्द करें"
    let webConfirm = "पक्का करें"
    let webPickSession = "बाईं ओर से कोई session चुनें।"
    let webReading = "पढ़ रहा है…"
    let webLoading = "लोड हो रहा है…"
    let webTranscriptFailed = "ट्रांसक्रिप्ट पढ़ी नहीं जा सकी"
    let webWhoYou = "आप"
    let webWhoTool = "टूल"
    let webPending = "Mac का इंतज़ार है…"
    let webAttachedImage = "{n} तस्वीर जुड़ी है"
    let webAttachedImages = "{n} तस्वीरें जुड़ी हैं"
    let webSteps = "{n} चरण"
    let webJustNow = "अभी-अभी"
    let webMinutesAgo = "{n} मिनट पहले"

    let webSend = "भेजें"
    let webAttach = "तस्वीर लगाएँ"
    let webRemoveShot = "{name} हटाएँ"
    let webWriteOpen = "लिखने के लिए कोई session खोलें।"
    let webWriteOff = "*भेजना बंद है* — server कहता है `write: false`। डिब्बा जुड़ा हुआ है; वहाँ बदलते ही यह ख़ुद चालू हो जाएगा।"
    let webShotsOnlyPictures = "संदेश के साथ सिर्फ़ तस्वीरें जा सकती हैं"
    let webShotsTooMany = "एक संदेश में ज़्यादा से ज़्यादा {n} तस्वीरें"
    let webShotTooBig = "यह तस्वीर छोटी करके भी भेजने लायक़ नहीं रही"
    let webShotsTooBig = "ये तस्वीरें एक साथ भेजने के लिए बहुत बड़ी हैं"
    let webShotUnreadable = "यह तस्वीर पढ़ी नहीं जा सकी"
    let webShotNeedsSession = "तस्वीर भेजने के लिए कोई session खोलें"

    let webVoiceStart = "बोलकर संदेश लिखें"
    let webVoiceStop = "रोकें और लिखवाएँ"
    let webVoiceDone = "पूर्ण"
    let webVoiceListening = "सुन रहा है… {t}"
    let webVoiceReading = "Mac पर लिखा जा रहा है… {n} से॰"
    let webVoiceSlow = "इस Mac के दोबारा चालू होने के बाद पहली बार पहले model पढ़ा जाता है — क़रीब बारह सेकंड।"
    let webVoiceLimit = "रिकॉर्डिंग {n} मिनट पर रुक गई — एक रिकॉर्डिंग इतनी ही चलती है। जितना है उतना लिखा जा रहा है।"
    let webVoiceEmpty = "उसमें कुछ सुनाई नहीं दिया।"
    let webVoiceTooShort = "वह इतना छोटा था कि कुछ सुनाई ही नहीं दिया।"
    let webVoiceDenied = "माइक्रोफ़ोन को मना कर दिया गया। इसी browser की, इस साइट के लिए रखी गई सेटिंग्ज़ में उसे वापस चालू कीजिए।"
    let webVoiceNoMic = "इस डिवाइस पर कोई माइक्रोफ़ोन नहीं मिला।"
    let webVoiceInUse = "माइक्रोफ़ोन व्यस्त है — इस डिवाइस पर कोई और चीज़ उसे पकड़े हुए है।"
    let webVoiceInsecure = "माइक्रोफ़ोन को https चाहिए, और यह पन्ना उस पर नहीं है। tunnel एक देता है; लोकल नेटवर्क का सादा पता नहीं देता।"
    let webVoiceUnsupported = "यह browser आवाज़ रिकॉर्ड नहीं कर सकता।"
    let webVoiceBusy = "एक लिखी जा रही है और दूसरी इंतज़ार में है। थोड़ी देर बाद कोशिश कीजिए।"
    let webVoiceNoBinary = "Mac पर Whisper इंस्टॉल नहीं है, तो वहाँ इसे लिखने के लिए कुछ है ही नहीं।"
    let webVoiceNoModel = "Mac पर Whisper है, पर पढ़ने के लिए कोई model नहीं। उसे `~/.cache/whisper` में बस एक ggml फ़ाइल चाहिए।"
    let webVoiceFailed = "उसे लिखा नहीं जा सका।"

    let webHintMove = "चलें"
    let webHintOpen = "खोलें"
    let webHintFilter = "छाँटें"
    let webHintPane = "पैनल"

    let webKeysLabel = "कीबोर्ड शॉर्टकट"
    let webKeysTitle = "कीबोर्ड"
    let webKeysMove = "सूची में ऊपर-नीचे — `j` और `k` भी वही करते हैं"
    let webKeysOpen = "चुना हुआ session खोलें"
    let webKeysFilter = "सूची छाँटें"
    let webKeysEscape = "पहले छाँट हटाएँ, फिर पीछे"
    let webKeysList = "session की सूची पर जाएँ"
    let webKeysPane = "ट्रांसक्रिप्ट दिखाएँ या छिपाएँ"
    let webKeysEnds = "ट्रांसक्रिप्ट का सिरा — ऊपर या नीचे"
    let webKeysReverse = "ट्रांसक्रिप्ट का क्रम उलटें"
    let webKeysThis = "यही कार्ड"
    let webKeysFoot = "जो किसी डिब्बे में लिखा जाता है वह उसी डिब्बे में रहता है — आपके लिखते समय शॉर्टकट पीछे हट जाते हैं।"

    let webDoorLabel = "इस browser को जोड़ें"
    let webDoorAskLede = "इस browser को अभी अंदर नहीं आने दिया गया है।"
    let webDoorAskFine = "जोड़ने को कहिए और छह अंकों का कोड *उसी Mac पर* दिखेगा — इस पन्ने के जवाब में वह जान-बूझकर नहीं होता। इसे पूरा वही कर सकता है जो उस मशीन के पास है, और यही अड़चन नहीं, यही पूरी बात है।"
    let webDoorName = "इस डिवाइस का नाम"
    let webDoorAsk = "जोड़ने को कहें"
    let webDoorToPassword = "इसकी जगह पासवर्ड से लॉगिन"
    let webDoorCodeLede = "उस Mac को देखिए।"
    let webDoorCodeFine = "Clawdline छह अंक दिखा रहा है, {left} के लिए। उन्हें यहाँ लिखिए।"
    let webDoorTwoMinutes = "दो मिनट"
    let webDoorDigit = "अंक {n}"
    let webDoorConfirm = "यह डिवाइस जोड़ें"
    let webDoorRestart = "फिर से शुरू"
    let webDoorPasswordLede = "पासवर्ड से लॉगिन कीजिए।"
    let webDoorPasswordFine = "वही जो Mac पर Clawdline में सेटिंग्ज़ → रिमोट पहुँच के नीचे रखा है। अगर कोई रखा ही नहीं गया, तो अंदर आने का रास्ता जोड़ना ही है।"
    let webDoorPassword = "पासवर्ड"
    let webDoorPasswordGo = "लॉगिन"
    let webDoorToPair = "इसकी जगह जोड़ने वाला कोड"
    let webDoorAsking = "Mac से पूछ रहे हैं…"
    let webDoorAskFailed = "Mac से पूछा नहीं जा सका।"
    let webDoorRateLimited = "हर बार पूछने पर उस Mac पर एक सूचना आती है, इसलिए दस मिनट में सिर्फ़ तीन बार।"
    let webDoorSixDigits = "छह अंक।"
    let webDoorChecking = "जाँच रहे हैं…"
    let webDoorFinished = "यह जोड़ना ख़त्म हुआ — पाँच बार ग़लत कोड। जब आप Mac के पास हों, तब फिर पूछिए।"
    let webDoorWrongCode = "यह कोड सही नहीं है।"
    let webDoorNeedPassword = "पहले पासवर्ड।"
    let webDoorWrongPassword = "पासवर्ड यह नहीं है।"
    let webDoorExpired = "इस कोड का समय बीत गया। फिर पूछिए, Mac पर नया आ जाएगा।"
    let webDoorPaired = "जुड़ गया — यह browser अंदर है"

    let webOffline = "Clawdline तक नहीं पहुँचा जा सका। क्या वह अब भी उस Mac पर चल रहा है?"
    let webNotJSON = "server ने कुछ ऐसा भेजा जो JSON नहीं है"
    let webRequestFailed = "request पूरी नहीं हुई"

    let webNotifyGo = "मुझे बताएँ"
    let webNotifyAsking = "पूछ रहे हैं…"
    let webNotifyStop = "रोकें"
    let webNotifyStopping = "रुक रहा है…"
    let webNotifyOff = "जब कोई session जवाब का इंतज़ार कर रहा हो"
    let webNotifyOn = "यह डिवाइस जुड़ा हुआ है। किस बात की सूचना आएगी, यह Mac पर तय होता है।"
    let webNotifyBlocked = "इस साइट के लिए सूचनाएँ रोकी हुई हैं। वह स्विच यहाँ नहीं, browser की अपनी सेटिंग्ज़ में है।"
    let webNotifyUnsupported = "यह browser सूचनाएँ नहीं दिखा सकता।"
    let webNotifyHomeScreen = "clawdline को होम स्क्रीन पर जोड़िए और वहीं से खोलिए — iOS सूचनाएँ सिर्फ़ वहाँ रहने वाले app को भेजता है।"
    let webNotifyOnFailed = "सूचनाएँ चालू नहीं हो सकीं"
    let webNotifyOffFailed = "सूचनाएँ बंद नहीं हो सकीं"

    let webSettings = "सेटिंग्ज़"
    let webSettingsNotify = "सूचनाएँ"
    let webSettingsAssistantIcons = "सहायक आइकन"
    let webSettingsAssistantIconsSay = "बातचीत में Claude या Codex के नाम से पहले उसका चिह्न दिखाएँ।"
    let webSettingsAssistantIconsShow = "आइकन दिखाएँ"
    let webSettingsVersion = "संस्करण {v}"
    let webClose = "बंद करें"
    let webNotifySheetOff = "कोई session इंतज़ार में हो, तब भी इस डिवाइस को नहीं बताया जाता।"
    let webNotifyTest = "एक test भेजें"
    let webNotifyTestSent = "भेज दिया — अभी इस डिवाइस पर आ जाना चाहिए।"
    let webNotifyTestNone = "Mac के पास इस डिवाइस के लिए कोई subscription नहीं है। सूचनाएँ बंद करके फिर चालू कीजिए, यह browser नई दर्ज कर देगा।"
    let webNotifyTestFailed = "test सूचना भेजी नहीं जा सकी"
    let webSending = "भेज रहे हैं…"
    let webSendTip = "Return भेजता है · Shift-Return नई पंक्ति"
    let webStart = "session शुरू करें"
    let webStartLabel = "किसी प्रोजेक्ट में session शुरू करें"
    let webStartPick = "कहाँ शुरू करें?"
    let webStartWith = "किससे शुरू करें?"
    let webStartEmpty = "अभी शुरू करने की कोई जगह नहीं। Mac पर एक बार Claude Code चला लीजिए, फिर वह यहाँ होगी।"
    let webStartFilter = "प्रोजेक्ट छाँटें"
    let webStarting = "tab खोल रहे हैं…"
    let webStartWaiting = "शुरू हो गया। दिखने का इंतज़ार…"
    let webStartSlow = "tab खुल चुका है, पर session ने अभी कुछ नहीं बताया। एक बार Mac देख लीजिए।"
    let webStartFailed = "यह शुरू नहीं हो सका।"
    let webStartGone = "वह प्रोजेक्ट अब Mac पर नहीं है।"
    let webStartTerminalClosed = "{app} इस Mac पर चल नहीं रहा। पहले उसे वहाँ खोलिए, फिर कोशिश कीजिए।"
    let webStartTerminalUnsupported = "यहाँ से {app} में session शुरू नहीं किया जा सकता। उसमें tmux चलाइए, फिर यह चलेगा।"
    let webStartOff = "session शुरू करना बंद है। Mac पर सेटिंग्ज़ → रिमोट पहुँच से चालू होता है।"
    let webResumeWith = "पिछली कोई जारी रखें"
    let webResumePick = "कौन-सी बातचीत?"
    let webResumeFilter = "बातचीत छाँटें"
    let webResumeEmpty = "उस प्रोजेक्ट में अभी कुछ भी दर्ज नहीं हुआ है।"
    let webResumeLive = "खुली है"
    let webResumeBack = "दूसरा प्रोजेक्ट"
    let webResumeGone = "वह बातचीत अब Mac पर नहीं है।"
    let webResumeClaudeOnly = "जारी रखी जा सकने वाली बातचीत सिर्फ़ Claude Code सहेजता है।"
    let webResuming = "फिर से खोल रहे हैं…"
    let webCommand = "बोलकर बताएं क्या शुरू करना है"
    let webCommandLabel = "क्या करना है बोलकर session शुरू करें"
    let webCommandSay = "नीचे शुरू करें दबाने तक कुछ भी नहीं भेजा जाता।"
    let webCommandHeard = "क्या करना है?"
    let webCommandThinking = "सोच रहा है…"
    let webCommandDraft = "ड्राफ़्ट"
    let webCommandWhere = "कहाँ"
    let webCommandWith = "किससे"
    let webCommandFirst = "पहला संदेश"
    let webCommandGo = "शुरू करें"
    let webCommandUnsure = "पक्का नहीं कि कौन-सा प्रोजेक्ट — नीचे से एक चुनें।"
    let webCommandFailed = "उसे ड्राफ़्ट नहीं बना पाया।"
    let webCommandNoPlanner = "इस Mac पर Claude Code नहीं है, इसलिए ड्राफ़्ट नहीं बन सकता।"
    let webCommandBusy = "एक वाक्य पहले से ड्राफ़्ट बन रहा है — थोड़ी देर में फिर कोशिश करें।"
    let webCommandEmpty = "कुछ सुनाई नहीं दिया"
    let webLinks = "लिंक"
    let webLinksTip = "यह प्रोजेक्ट कहाँ-कहाँ खुलता है"
    let webLinksPick = "इस प्रोजेक्ट की जिस भी चीज़ का पता है, वह सब यहाँ है।"
    let webLinksEmpty = "इस प्रोजेक्ट की किसी चीज़ का कोई पता नहीं है — न साइट, न deploy, न कोई सर्वर चल रहा।"
    let webLinksFailed = "इस प्रोजेक्ट के लिंक पढ़े नहीं जा सके।"
    let webLinksLocal = "सिर्फ़ Mac के अपने नेटवर्क पर। यहाँ से यह नहीं खुलेगा।"
    let webLinksFile = "Mac पर रखी एक फ़ाइल। वह वहीं खुलती है, इस browser में नहीं।"
    let webLinksCopy = "पथ कॉपी करें"
    let webLinksCopied = "कॉपी हो गया।"
    let webLinksCopyFailed = "इस browser ने पन्ने को वह कॉपी नहीं करने दिया।"
    let webLinkOk = "ठीक"
    let webLinkFail = "फ़ेल"
    let webLinkDown = "बंद"
    let webLinkRunning = "चल रहा"
    let webSessionInfo = "session की जानकारी"
    let webInfoTitle = "इस session के बारे में"
    let webInfoSession = "यह session"
    let webInfoAssistant = "असिस्टेंट"
    let webInfoModel = "मॉडल"
    let webInfoSessionId = "session ID"
    let webInfoDirectory = "डायरेक्टरी"
    let webInfoRunningFor = "चलते हुए"
    let webInfoUsage = "टोकन का इस्तेमाल"
    let webInfoInput = "इनपुट"
    let webInfoOutput = "आउटपुट"
    let webInfoCacheRead = "कैश से पढ़ा"
    let webInfoCacheWrite = "कैश में लिखा"
    let webInfoTotal = "कुल"
    let webInfoCost = "अनुमानित लागत"
    let webInfoNoUsage = "इस session का transcript अभी नहीं मिला।"
    let webInfoLimits = "प्लान की सीमा"
    let webInfoLimitHit = "सीमा पूरी हो गई"
    let webInfoResets = "{when} रीसेट होगा"
    let webInfoUnknown = "पता नहीं"
    let webInfoFiles = "फ़ाइलें"
    let webInfoBranch = "ब्रांच"
    let webInfoStaged = "स्टेज की हुई"
    let webInfoUnstaged = "बदली हुई"
    let webInfoUntracked = "अनट्रैक्ड"
    let webInfoConflict = "टकराव"
    let webInfoClean = "कुछ भी बिना commit के नहीं है।"
    let webInfoNotRepo = "यह git repo नहीं है।"
    let webInfoDeploy = "आख़िरी deploy"
    let webInfoNoDeploy = "इस प्रोजेक्ट का कोई deploy दर्ज नहीं है।"
    let webInfoFailed = "इस session की जानकारी पढ़ी नहीं जा सकी।"
    let webInfoRefresh = "रीफ़्रेश करें"
    let webInfoTokens = "टोकन"
    let webInfoSwitchModel = "मॉडल बदलें"
    let webInfoModelOther = "कोई और मॉडल…"
    let webInfoModelSent = "/model {model} भेज दिया। पुष्टि हो रही है…"
    let webInfoModelBusy = "मॉडल तभी बदलेगा जब session खाली हो।"
    let webInfoSwitchPermission = "अनुमति मोड बदलें"
    let webInfoPermissionAuto = "स्वचालित"
    let webInfoPermissionManual = "मैन्युअल"
    let webInfoPermissionAcceptEdits = "संपादन स्वीकार करें"
    let webInfoPermissionPlan = "योजना"
    let webInfoPermissionUnreadable = "मौजूदा मोड पढ़ा नहीं जा सका।"
    let webInfoPermissionSent = "{mode} पर बदला गया। पुष्टि हो रही है…"
    let webInfoPermissionBusy = "अनुमति मोड बदला जा रहा है।"
    let webInfoLimitsClaude = "Claude Code कोई window तभी लिखता है जब वह खत्म हो जाए; तब तक कुछ पता नहीं।"
    let webInfoCopied = "Session id कॉपी हो गया।"
    let webInfoAsOf = "{when} तक"
    let webInfoWhyUnknown = "यह अज्ञात क्यों है, और आँकड़े कैसे पाएँ"
    let webSettingsOrder = "ट्रांसक्रिप्ट"
    let webSettingsOrderSay = "ट्रांसक्रिप्ट किस सिरे से पढ़नी शुरू हो। यह हर session पर लागू होता है, और कीबोर्ड पर `r` भी यही करता है।"
    let webAskLabel = "ने पूछा"
    let webAskAny = "इनमें से जितने चाहें"
    let webWaitingTitle = "यह session जवाब का इंतज़ार कर रहा है"
    let webWaitingSay = "Claude Code उस Mac पर एक मेन्यू दिखा रहा है। Clawdline अभी यहाँ से मेन्यू पढ़ नहीं सकता, इसलिए विकल्प सिर्फ़ उसी स्क्रीन पर हैं।"
    let webWaitingSend = "*यहाँ से भेजने पर आपका जवाब मेन्यू में टाइप नहीं होगा* — मेन्यू में इस समय जो विकल्प चुना हुआ है, यह उसी को पक्का कर देगा, और वह शायद ही वह होता है जो आप चाहते थे। इसका जवाब Mac पर दीजिए।"
    let webMenuSay = "किसी जवाब पर टैप करें, वह सीधे session में चला जाएगा।"
    let webMenuHighlighted = "चुना हुआ"
    let webMenuSent = "जवाब भेज दिया।"
    let webAgents = "बैकग्राउंड एजेंट"
    let webAgentsCount = "{n} चल रहे हैं"
    let webAgentDone = "हो गया"
    let webAgentFailed = "विफल"
    let webShells = "बैकग्राउंड shell"
    let webShellTitle = "बैकग्राउंड shell"
    let webShellOpen = "देखें यह कमांड क्या छाप रहा है"
    let webShellRunning = "अभी चल रहा है"
    let webShellEnded = "पूरा हुआ"
    let webShellQuiet = "अभी कुछ नहीं छपा।"
    let webShellFailed = "इस कमांड का आउटपुट नहीं पढ़ा जा सका।"
    let webShellClose = "बंद करें"
    let webShellStop = "रोकें"
    let webShellStopTitle = "यह कमांड रोकनी है?"
    let webShellStopSay = "{command} अभी चल रहा है। इसे रुकने को कहा जाएगा, और पाँच सेकंड बाद भी न रुके तो मार दिया जाएगा। जो हो चुका है वह वापस नहीं होगा।"
    let webShellStopped = "रुकने को कह दिया।"
    let webShellStopFailed = "रोका नहीं जा सका।"
    let agentRunning = "चल रहा है"
    let agentTools = "{n} टूल"
    let agentEmpty = "इस एजेंट ने अभी तक कुछ नहीं लिखा है।"
    let agentBack = "सत्र"
    let webAgentOpen = "देखें इस एजेंट ने क्या किया"
    let webTaskRoot = "रूट"
    let webTaskChild = "चाइल्ड"
    let webTaskTasks = "काम"
    let webTaskDone = "हो गया"
    let webTaskFailed = "विफल"
    let webTaskRunning = "चल रहा है"
    let webStale = "Mac पर Clawdline फिर से बनाया गया है। यह पन्ना पुराना वाला है।"
    let webStaleGo = "फिर से लोड करें"

    let menuOpen = "इनपुट बार खोलें"
    let menuReveal = "लक्ष्य tab पर जाएँ"
    let menuMascot = "मैस्कॉट"
    let menuLogin = "लॉगिन पर चालू करें"
    let menuEditConfig = "सेटिंग्ज़…"
    let menuReload = "सेटिंग्स फिर से पढ़ें"
    let menuQuit = "Clawdline बंद करें"
    let menuNoTarget = "(अभी पता नहीं चला)"

    func hotkeyFailedTitle(_ combo: String) -> String { "\(combo) दर्ज नहीं हो सका" }
    func hotkeyFailedBody(_ configPath: String) -> String {
        """
        सबसे संभव है कि कोई और app इसे पहले से ले चुका है — Spotlight, कीबोर्ड बदलने वाला \
        टूल, BetterTouchTool वग़ैरह।

        दूसरा चुनें: \(configPath) में "hotkey" बदलें, फिर मेन्यू बार से \
        "सेटिंग्स फिर से पढ़ें" चुनें।

        तब तक मेन्यू बार का ✳ इनपुट बार खोलता रहेगा।
        """
    }
    let loginFailed = "लॉगिन पर चालू करना सेट नहीं हो सका"
}
