import Foundation

struct German: Copy {
    let placeholder = "Nachricht an Claude Code…"

    let hintSend = "senden"
    let hintNewline = "neue Zeile"
    let hintSwitch = "wechseln"
    let hintList = "Liste"
    let hintMascot = "Maskottchen"
    let hintOutput = "Ausgabe"
    let hintFullscreen = "Vollbild"
    let hintKeys = "Tasten"
    let hintTextSize = "Schriftgröße"
    let hintOrder = "umkehren"
    let hintVoice = "diktieren"
    func voiceListening(onDevice: Bool) -> String {
        onDevice ? "Hört auf diesem Mac zu — nochmal drücken zum Beenden"
                 : "Hört zu — diese Sprache transkribiert Apple, nicht dieser Mac"
    }
    let voiceNoPermission = "Das Diktat braucht Zugriff auf Mikrofon und Spracherkennung"
    let voiceUnavailable = "Das Diktat ist gerade nicht verfügbar"
    func voiceTranscribing(seconds: Double) -> String {
        String(format: "Whisper liest noch einmal… %.1f s", seconds)
    }
    let whisperMissing = "Whisper ist nicht installiert — siehe docs/whisper.md"
    let whisperNothingHeard = "Nichts gehört"
    func dictationStatus(_ status: Whisper.Status) -> String {
        switch status {
        case .ready(let model): return "Diktat: Apple, danach Whisper (\(model))"
        case .noBinary: return "Diktat: nur Apple — kein whisper-cli"
        case .noModel: return "Diktat: nur Apple — whisper-cli ist da, das Modell fehlt"
        }
    }
    func voiceListeningWhisper() -> String {
        "Hört zu — Whisper schaut noch einmal drüber, wenn du aufhörst"
    }

    let scanning = "Suche…"
    let noSession = "Keine Claude-Code-Sitzung gefunden"
    let nothingToSend = "Kein Ziel — starte Claude Code zuerst in einem Terminal"
    let sendFailed = "Konnte nicht senden"
    let itermSilent = "iTerm2 hat nicht geantwortet"
    let itermBusy = "iTerm2 wartet auf einen Dialog — beantworte ihn am Mac"
    let scriptMissing = "iterm.js fehlt — beschädigtes App-Bundle?"
    let cannotList = "Konnte die iTerm2-Sitzungen nicht lesen"
    let noOutput = "In dieser Sitzung gibt es noch nichts zu lesen."
    func outputSize(_ pt: Int) -> String { "Ausgabetext \(pt) pt — ⌘J zum Anzeigen" }
    func foldedTools(_ count: Int) -> String { "\(count) Schritte" }
    func outputOrder(newestFirst: Bool) -> String {
        newestFirst ? "Neueste zuerst" : "Älteste zuerst"
    }
    func backlogNow(_ count: Int) -> String { "jetzt \(count)" }
    func dropped(_ count: Int) -> String {
        count == 1 ? "Pfad eingefügt — Claude Code liest ihn" : "\(count) Pfade eingefügt"
    }
    func stackConfirm(_ command: String) -> String { "Erneut drücken zum Ausführen:  \(command)" }
    let hintStacks = "Server"
    func stackTip(up: Int, total: Int) -> String { "\(up) von \(total) Servern laufen — ⌘S für die Liste" }
    let stackTipUnknown = "Dieses Projekt hat Server; sein Status-Befehl ist noch nicht freigegeben — ⌘S"
    let stackUntrusted = "nicht freigegeben"
    let stackExit = "Exit-Code"
    let stackActionStart = "starten"
    let stackActionRestart = "neu starten"
    let stackActionStop = "stoppen"
    let stackActionLogs = "Protokoll"
    let stackLogAll = "alle"
    let stackLogBack = "Transkript"
    let stackActionAllow = "zulassen"
    let stackActionAgain = "nochmal"
    func sessionTip(index: Int, total: Int) -> String { "Sitzung \(index) von \(total) — ⌘K zum Wechseln" }
    let sessionWaiting = "wartet auf dich"
    let sessionAgents = "{n} im Hintergrund"
    let sessionShellOne = "1 Shell läuft"
    let sessionShellMany = "{n} Shells laufen"
    let islandDone = "fertig"
    let islandAllSessions = "Alle Sitzungen …"
    func statusWaiting(_ labels: [String]) -> String {
        labels.count == 1 ? "\(labels[0]) wartet auf dich"
                          : "\(labels.count) Sitzungen warten auf dich"
    }
    func statusWorking(_ count: Int) -> String { "\(count) laufen" }

    let settingsTitle = "Clawdline Einstellungen"
    let settingsGeneral = "Allgemein"
    let settingsBar = "Die Leiste"
    let settingsReading = "Lesen"
    let settingsVoice = "Diktat"
    let settingsHotkey = "Tastenkürzel"
    let settingsRecording = "Tasten drücken …"
    let settingsScope = "Aktiv in"
    let settingsScopeGlobal = "In jeder App"
    let settingsScopeHint = "Leer heißt überall — die letzte herauszunehmen schaltet also den Schalter darüber ein, und ihn wieder auszuschalten holt die Liste zurück. Die Konfigurationsdatei hält sie als Bundle-IDs, und eine von Hand bearbeitete Liste funktioniert weiterhin."
    let settingsScopeAdd = "App hinzufügen …"
    let settingsScopeChoose = "App auswählen …"
    let settingsScopeRunning = "Gerade geöffnet"
    let settingsScopeRemove = "Entfernen"
    let settingsLanguage = "Sprache"
    let settingsReopen = "Die Leiste kommt und geht mit dem Terminal"
    let settingsReopenHint = "Vom Terminal wegzuwechseln legt die Leiste weg, und zurückzuwechseln holt sie wieder hervor. Esc ist das, was fertig heißt."
    let settingsFollow = "Das Terminal zeigt, worauf die Leiste zielt"
    let settingsFollowHint = "Es wählt den Tab dieser Sitzung aus. Es holt das Terminal nicht nach vorn — sonst würde jeder Druck auf Tab die Tastatur aus dem Feld nehmen, in das du gerade schreibst."
    let settingsCodexAutoName = "Neue Codex-Sitzungen benennen"
    let settingsCodexAutoNameHint = "Führt für jede unbenannte Sitzung einen kleinen Codex-Luna-Turn aus. Verwendet die erste Anfrage, verbraucht Codex-Nutzung und ersetzt nie einen selbst gewählten Namen."
    let settingsNotch = "In der Notch wohnen"
    let settingsNotchHint = "Eine Figur im Kameragehäuse. Aus ist aus — nichts wird gezeichnet, kein Fenster angelegt."
    let settingsPosition = "Höhe am Bildschirm"
    let settingsWidth = "Breite"
    let settingsOpacity = "Deckkraft der Karte"
    let settingsShow = "Zeigen"
    let settingsPaneHeight = "Höhe des Bereichs"
    let settingsTextSize = "Textgröße"
    let settingsPaneFont = "Schrift des Bereichs"
    let settingsBlur = "Unschärfe dahinter"
    let settingsNewestFirst = "Neueste zuerst"
    let settingsEngine = "Erkennung"
    let settingsSettle = "Eine Pause beendet den Satz"
    let settingsStop = "Stille beendet die Sitzung"
    let settingsAuto = "Automatisch"
    let settingsTranscript = "Verlauf"
    let settingsTerminal = "Terminal"
    let settingsOff = "Aus"
    let settingsHooks = "Claude-Code-Hooks"
    let settingsHooksHint = "Sind sie eingerichtet, meldet Claude Code den Moment, in dem ein Durchgang beginnt, endet oder eine Antwort braucht — statt dass Clawdline es beim nächsten Blick bemerkt. Gelesen wird weiterhin vom Bildschirm; das hier bestimmt nur, wie schnell."
    let settingsHooksInstall = "Einrichten"
    let settingsHooksRemove = "Entfernen"
    let settingsHooksOff = "Nicht eingerichtet — alles kommt vom Bildschirm"
    let settingsHooksOn = "Eingerichtet — noch keine Sitzung hat sich gemeldet"
    let settingsHooksLive = "Eingerichtet, Sitzungen melden sich"
    let settingsStateHook = "Wenn eine Sitzung ihren Zustand wechselt"
    let settingsStateHookHint = "Immer wenn eine Sitzung zu arbeiten anfängt, fertig wird oder dich etwas fragt, führt Clawdline das hier aus: dein eigenes Programm, mit den Einzelheiten in seiner Umgebung. Es steht in der Konfigurationsdatei und nicht hier, weil es ein argv ist und keine Kommandozeile — ein Pfad mit einem Leerzeichen darin muss ein Pfad bleiben."
    let settingsRemote = "Fernzugriff"
    let settingsRemoteServe = "Einen Browser oder dein Telefon deine Sitzungen sehen lassen"
    let settingsRemoteHint = "Aus, und nichts außerhalb dieses Mac erreicht irgendetwas. An, und die Liste der Sitzungen wird auf 127.0.0.1 ausgeliefert — für einen Browser hier, für ein Telefon durch einen Tunnel, für ein Skript. Was dabei herausgeht, sind Repository-Namen, Branches und Aufgabentitel; deshalb bleibt es aus, bis du etwas anderes sagst."
    let settingsRemoteDevices = "Gekoppelte Geräte"
    let settingsRemoteNoDevices = "Noch keine — außerhalb dieses Mac kann niemand etwas lesen"
    let settingsRemoteRevokeAll = "Alle trennen"
    let settingsRemoteOpen = "Im Browser öffnen"
    let pairingIgnore = "Ignorieren"
    func pairingAsks(_ device: String) -> String { "\(device) möchte sich mit diesem Mac koppeln" }
    func pairingCode(_ code: String) -> String {
        """
        Gib diesen Code dort ein:

        \(code)

        Er gilt zwei Minuten. Wenn du das gerade nicht angefragt hast, ignoriere es — ohne \
        diesen Code kommt derjenige, der gefragt hat, nicht weiter.
        """
    }
    let settingsTunnel = "Diesen Mac von überall erreichen"
    let settingsTunnelQuick = "Eine erzeugte Adresse"
    let settingsTunnelNamed = "Meine eigene Domain"
    let settingsTunnelHostname = "Hostname"
    let settingsTunnelHint = "Baut über cloudflared eine ausgehende Verbindung auf — keine Portweiterleitung, nichts, was in deinem Netz lauscht. Startet erst, wenn ein Gerät gekoppelt ist, denn dahinter liegt jeder Repository-Name und jeder Aufgabentitel auf diesem Mac."
    let settingsRemoteWrite = "Ein gekoppeltes Gerät in eine Sitzung schreiben lassen"
    let settingsRemoteWriteHint = "Aus kann ein gekoppeltes Gerät nur lesen. An kann es Text in eine Sitzung schicken und neue starten — und das führt Code auf diesem Mac aus, denn genau das tut Claude Code. Eine andere Entscheidung als die darüber, also ein eigener Schalter."
    let settingsRemotePhone = "Telefon koppeln …"
    let settingsRemotePhoneHint = "Zeigt einen Code zum Scannen. Er trägt einen eigenen Schlüssel: Ein Foto davon ist ein Gerät, das du in dieser Liste siehst und wieder wegnehmen kannst — nicht der Schlüssel dieses Mac selbst."
    let pairingScanTitle = "Scanne das mit dem Telefon"
    let pushWaiting = "wartet auf eine Antwort"
    let pushTest = "Eine Testbenachrichtigung. Alles ist angeschlossen."
    let pushFinished = "hat einen langen Durchlauf beendet"
    let pushDeployOk = "das Deploy hat geklappt"
    let pushDeployFail = "das Deploy ist fehlgeschlagen"
    func pushChildWaiting(minutes: Int?) -> String {
        guard let minutes else { return "hat eine wartende Unter-Sitzung" }
        return "hat eine wartende Unter-Sitzung — noch \(minutes) Min."
    }
    func pushBatchDone(done: Int, failed: Int) -> String {
        let all = done == 1 ? "hat 1 Aufgabe beendet" : "hat \(done) Aufgaben beendet"
        return failed == 0 ? all : "\(all), \(failed) fehlgeschlagen"
    }
    let settingsPushFinish = "Bescheid sagen, wenn ein langer Durchlauf fertig ist"
    let settingsPushFinishHint = "Nur ab zwei Minuten."
    let settingsPushDeploy = "Bescheid sagen, wenn ein Deploy endet"
    let settingsPushDeployHint = "Erfolg wie Fehlschlag."
    let settingsOrchestrator = "Arbeit weitergeben"
    let settingsOrchestratorEnabled = "Eine Sitzung darf Arbeit an eine andere abgeben"
    let settingsOrchestratorEnabledHint = "Eine Sitzung mit der clawdline-Skill kann einen Tab öffnen, die Anweisungen hineintippen und erfahren, wann die Arbeit fertig ist. Aus, und jede Anfrage wird abgelehnt; was schon läuft, wird nicht gestoppt."
    let settingsOrchestratorMax = "Gleichzeitige Kindsitzungen"
    let settingsOrchestratorMaxHint = "Standard sind fünf, und zwar pro Sitzung statt pro Mac. Jede ist ein Terminal-Tab, in dem ein Assistent arbeitet."
    let settingsOrchestratorSubMax = "Und was eine Kindsitzung weitergibt"
    let settingsOrchestratorSubMaxHint = "Standard sind drei. Eine Sitzung, die schon eine Besorgung erledigt, darf eigene öffnen; darunter kommt nichts mehr."
    let settingsOrchestratorSubMaxNone = "Nichts — eine Kindsitzung gibt nichts weiter"
    let settingsOrchestratorPermission = "Wie weit eine Kindsitzung gehen darf"
    let settingsOrchestratorPermissionHint = "Auf den Tab einer Kindsitzung schaut niemand: Eine, die auf eine Freigabe wartet, wartet bis zum Zeitlimit — und die ganze Arbeit einer vergebenen Sitzung besteht daraus, Befehle auszuführen und Dateien zu schreiben, also hält sie alles unterhalb der letzten Stufe irgendwo an. Eine Aufgabe darf weniger verlangen, nie mehr."
    let settingsOrchestratorPermissionAsk = "Vor jedem Schritt fragen"
    let settingsOrchestratorPermissionEdits = "Dateien ohne Nachfrage schreiben"
    let settingsOrchestratorPermissionFull = "Nie fragen"
    let settingsOrchestratorNotify = "Der fragenden Sitzung Bescheid geben"
    let settingsOrchestratorNotifyHint = "Eine Zeile, dort hineingetippt, sobald die Aufgabe endet."
    let settingsOrchestratorClose = "Wenn eine Kindsitzung meldet"
    let settingsOrchestratorCloseHint = "Ihr Tab wird nach der Meldung geschlossen — eine, deren Zeit ablief, bleibt zum Nachlesen offen."
    let settingsOrchestratorCloseNow = "Den Tab sofort schließen"
    let settingsOrchestratorCloseLinger = "Nach drei Minuten schließen"
    let settingsOrchestratorCloseKeep = "Offen lassen"
    let settingsOrchestratorPolicy = "Wie Arbeit verteilt wird"
    let settingsOrchestratorPolicyHint = "Regeln, die Clawdline bei jeder Vergabe liest und in die Anweisung jeder Kindsitzung kopiert, die selbst vergeben darf: welcher Assistent, welches Modell, welche Form der Graph haben soll. Leer heißt: keine Regeln."
    let settingsOrchestratorPolicyEdit = "Regeln bearbeiten"
    func settingsOrchestratorPolicyOn(_ lines: Int) -> String { return "In Kraft — \(lines) Zeilen" }
    let settingsOrchestratorPolicyOff = "Keine Regeln — jede Vergabe bleibt die Entscheidung dessen, der vergibt"
    let settingsSchedules = "Zeitpläne"
    let settingsSchedulesEmpty = "Noch keine Zeitpläne. Öffne mit der Taste unten den schedules-Ordner und füge eine JSON-Datei hinzu."
    let settingsScheduleNew = "Neuer Zeitplan"
    let settingsScheduleEdit = "Bearbeiten"
    let settingsScheduleSave = "Speichern"
    let settingsScheduleDelete = "Löschen"
    let settingsScheduleRun = "Jetzt ausführen"
    let settingsScheduleReveal = "Im Finder zeigen"
    let settingsSchedulesFolder = "schedules-Ordner öffnen"
    let settingsScheduleNext = "Nächster"
    let settingsScheduleLast = "Letzter"
    let settingsScheduleNever = "Noch nie ausgeführt"
    let settingsScheduleStarted = "Ausführung gestartet."
    let settingsScheduleActive = "Die vorherige geplante Aufgabe läuft noch."
    let webScheduleMissed = "Zuletzt verpasst"
    let webScheduleNoNext = "Keine nächste Ausführung ist geplant."
    func childAnnounce(_ title: String) -> String { "Clawdline-Auftrag erhalten: \(title) — ich fange jetzt an." }
    func settingsSeconds(_ value: Double) -> String { String(format: "%.1f s", value) }

    let webConnLive = "verbunden"
    let webConnConnecting = "verbindet"
    let webConnRetrying = "erneut in {n} s"
    let webConnOffline = "getrennt"
    let webConnLocked = "nicht gekoppelt"
    let webConnTipLive = "Streamt aus der App"
    let webConnTipLocked = "Dieser Browser ist nicht mit dem Mac gekoppelt"
    let webConnTipDown = "Nicht verbunden — zum Versuchen klicken"

    let webCountWorking = "{n} laufen"
    let webCountWaiting = "{n} warten"
    let webCountUnreadable = "{n} unlesbar"
    let webCountQuietOne = "{n} Sitzung, alles ruhig"
    let webCountQuietMany = "{n} Sitzungen, alles ruhig"
    let webCountNone = "keine Sitzungen"

    let webFilterPlaceholder = "Nach Aufgabe, Projekt oder tty filtern"
    let webFilterLabel = "Sitzungen filtern"
    let webListLabel = "Claude-Code-Sitzungen"
    let webPull = "Zum Aktualisieren ziehen"
    let webPullRelease = "Zum Aktualisieren loslassen"
    let webPullBusy = "Wird aktualisiert…"
    let webEmptyFilterTitle = "Nichts passt zu „{q}“"
    let webEmptyFilterHint = "Esc löscht den Filter"
    let webEmptyLockedTitle = "Dieses Gerät ist nicht gekoppelt"
    let webEmptyLockedHint = "Die App hat mit 401 geantwortet — koppele es in Clawdline auf dem Mac"
    let webEmptyNoneHint = "Starte eine im Terminal, dann erscheint sie hier"
    let webEmptyWaitTitle = "Warten auf die App"
    let webEmptyWaitHint = "Auf dem Stream ist noch nichts angekommen"
    let webStateUnreadable = "Bildschirm nicht lesbar"
    let webStateWorking = "läuft"

    let webBack = "Sitzungen"
    let webBackLabel = "Zurück zur Sitzungsliste"
    let webNoSessionOpen = "Keine Sitzung offen"
    let webOrderTip = "Verlauf umkehren (r)"
    let webShowOnMac = "Am Mac zeigen"
    let webShowOnMacTip = "Das Terminal dieser Sitzung auf dem Mac nach vorn holen"
    let webShowOnMacOff = "Der Server meldet write: false — es kann noch nichts gesendet werden"
    let webShowOnMacAsked = "Der Mac wurde gebeten, es nach vorn zu holen"
    let webSessionActions = "Sitzungsaktionen"
    let webSessionGit = "Git-Änderungen"
    let webGitTitle = "Git-Änderungen"
    let webGitClean = "Arbeitsverzeichnis unverändert"
    let webGitNotRepo = "Kein Git-Repository"
    let webGitFailed = "Git-Änderungen konnten nicht gelesen werden"
    let webGitRefresh = "Aktualisieren"
    let webGitClose = "Schließen"
    let webGitStaged = "Im Index"
    let webGitUnstaged = "Nicht im Index"
    let webGitUntracked = "Nicht verfolgt"
    let webGitConflict = "Konflikt"
    let webEndSession = "Sitzung schließen"
    let webConfirmActionTitle = "{action} ausführen?"
    let webConfirmActionSay = "Dadurch wird {action} an die aktuelle Sitzung gesendet."
    let webConfirmEndTitle = "Diese Sitzung schließen?"
    let webConfirmEndSay = "Der Assistent wird beendet, danach wird sein Terminal-Tab geschlossen."
    let webClosing = "Wird geschlossen…"
    let webCancel = "Abbrechen"
    let webConfirm = "Bestätigen"
    let webPickSession = "Wähle links eine Sitzung."
    let webReading = "Wird gelesen…"
    let webLoading = "Wird geladen…"
    let webTranscriptFailed = "Konnte den Verlauf nicht lesen"
    let webWhoYou = "du"
    let webWhoTool = "Werkzeug"
    let webPending = "Warten auf den Mac…"
    let webAttachedImage = "{n} Bild angehängt"
    let webAttachedImages = "{n} Bilder angehängt"
    let webSteps = "{n} Schritte"
    let webJustNow = "gerade eben"
    let webMinutesAgo = "vor {n} Min."

    let webSend = "Senden"
    let webAttach = "Ein Bild anhängen"
    let webRemoveShot = "{name} entfernen"
    let webWriteOpen = "Öffne eine Sitzung, um hineinzuschreiben."
    let webWriteOff = "*Senden ist aus* — der Server meldet `write: false`. Das Feld ist angeschlossen; es schaltet sich selbst ein, sobald sich das ändert."
    let webShotsOnlyPictures = "Mit einer Nachricht können nur Bilder mitgehen"
    let webShotsTooMany = "{n} Bilder sind das Höchste pro Nachricht"
    let webShotTooBig = "Dieses Bild ist zu groß zum Senden, auch verkleinert"
    let webShotsTooBig = "Diese Bilder sind zusammen zu groß zum Senden"
    let webShotUnreadable = "Dieses Bild konnte nicht gelesen werden"
    let webShotNeedsSession = "Öffne eine Sitzung, um ihr ein Bild zu schicken"

    let webVoiceStart = "Eine Nachricht diktieren"
    let webVoiceStop = "Anhalten und transkribieren"
    let webVoiceDone = "Fertig"
    let webVoiceListening = "Hört zu… {t}"
    let webVoiceReading = "Wird auf dem Mac transkribiert… {n} s"
    let webVoiceSlow = "Das erste Mal nach einem Neustart dieses Macs lädt zuerst das Modell — ungefähr zwölf Sekunden."
    let webVoiceLimit = "Die Aufnahme hat bei {n} Minuten aufgehört, länger wird eine nicht. Transkribiert wird, was da ist."
    let webVoiceEmpty = "Darin war nichts zu hören."
    let webVoiceTooShort = "Das war zu kurz, um etwas zu hören."
    let webVoiceDenied = "Das Mikrofon wurde abgelehnt. Schalte es in den Einstellungen dieses Browsers für diese Seite wieder ein."
    let webVoiceNoMic = "Auf diesem Gerät wurde kein Mikrofon gefunden."
    let webVoiceInUse = "Das Mikrofon ist belegt — etwas anderes auf diesem Gerät hat es."
    let webVoiceInsecure = "Ein Mikrofon braucht https, und diese Seite läuft nicht darüber. Der Tunnel bringt eines mit; eine schlichte Adresse im lokalen Netz nicht."
    let webVoiceUnsupported = "Dieser Browser kann nichts aufnehmen."
    let webVoiceBusy = "Eine davon wird gerade transkribiert, eine weitere wartet. Versuch es gleich noch einmal."
    let webVoiceNoBinary = "Auf dem Mac ist kein Whisper installiert, dort ist also nichts, womit sich das transkribieren ließe."
    let webVoiceNoModel = "Whisper ist auf dem Mac, hat aber kein Modell zum Lesen. Eine ggml-Datei in `~/.cache/whisper` genügt ihm."
    let webVoiceFailed = "Das ließ sich nicht transkribieren."

    let webHintMove = "blättern"
    let webHintOpen = "öffnen"
    let webHintFilter = "filtern"
    let webHintPane = "Bereich"

    let webKeysLabel = "Tastaturkürzel"
    let webKeysTitle = "Tastatur"
    let webKeysMove = "Durch die Liste gehen — `j` und `k` genauso"
    let webKeysOpen = "Die gewählte Sitzung öffnen"
    let webKeysFilter = "Die Liste filtern"
    let webKeysEscape = "Den Filter löschen, dann zurück"
    let webKeysList = "Zur Sitzungsliste springen"
    let webKeysPane = "Den Verlauf zeigen oder verbergen"
    let webKeysEnds = "Anfang oder Ende des Verlaufs"
    let webKeysReverse = "Die Reihenfolge des Verlaufs umkehren"
    let webKeysThis = "Diese Karte"
    let webKeysFoot = "Was in ein Textfeld getippt wird, bleibt im Textfeld — die Kürzel treten zurück, solange du schreibst."

    let webDoorLabel = "Diesen Browser koppeln"
    let webDoorAskLede = "Dieser Browser ist noch nicht eingelassen."
    let webDoorAskFine = "Frag nach der Kopplung, und auf *dem Mac* erscheint ein sechsstelliger Code — absichtlich nicht in der Antwort an diese Seite. Nur jemand an diesem Gerät kann das zu Ende bringen, und das ist der Sinn der Sache und nicht die Hürde."
    let webDoorName = "Nenne dieses Gerät"
    let webDoorAsk = "Kopplung anfragen"
    let webDoorToPassword = "Stattdessen mit Passwort anmelden"
    let webDoorCodeLede = "Schau auf den Mac."
    let webDoorCodeFine = "Clawdline zeigt noch {left} lang sechs Ziffern. Tippe sie hier ein."
    let webDoorTwoMinutes = "zwei Minuten"
    let webDoorDigit = "Ziffer {n}"
    let webDoorConfirm = "Dieses Gerät koppeln"
    let webDoorRestart = "Neu anfangen"
    let webDoorPasswordLede = "Melde dich mit dem Passwort an."
    let webDoorPasswordFine = "Dem, das in Clawdline auf dem Mac unter Einstellungen → Fernzugriff gesetzt ist. Ist keines gesetzt, führt die Kopplung hinein."
    let webDoorPassword = "Passwort"
    let webDoorPasswordGo = "Anmelden"
    let webDoorToPair = "Stattdessen einen Kopplungscode nutzen"
    let webDoorAsking = "Frage den Mac…"
    let webDoorAskFailed = "Konnte den Mac nicht fragen."
    let webDoorRateLimited = "Jede Anfrage setzt einen Hinweis auf den Mac, deshalb gibt es nur drei alle zehn Minuten."
    let webDoorSixDigits = "Sechs Ziffern."
    let webDoorChecking = "Wird geprüft…"
    let webDoorFinished = "Diese Kopplung ist beendet — fünf falsche Codes. Frag erneut, wenn du am Mac bist."
    let webDoorWrongCode = "Dieser Code stimmt nicht."
    let webDoorNeedPassword = "Erst das Passwort."
    let webDoorWrongPassword = "Das ist nicht das Passwort."
    let webDoorExpired = "Dieser Code ist abgelaufen. Frag erneut, dann erscheint ein frischer auf dem Mac."
    let webDoorPaired = "Gekoppelt — dieser Browser ist drin"

    let webOffline = "Clawdline nicht erreichbar. Läuft es noch auf dem Mac?"
    let webNotJSON = "Der Server hat etwas geschickt, das kein JSON ist"
    let webRequestFailed = "Anfrage fehlgeschlagen"

    let webNotifyGo = "Sag mir Bescheid"
    let webNotifyAsking = "Frage nach…"
    let webNotifyStop = "Stopp"
    let webNotifyStopping = "Wird gestoppt…"
    let webNotifyOff = "wenn eine Sitzung auf eine Antwort wartet"
    let webNotifyOn = "Dieses Gerät ist eingetragen. Wovon es erfährt, wird auf dem Mac festgelegt."
    let webNotifyBlocked = "Benachrichtigungen sind für diese Seite blockiert. Der Schalter dafür sitzt in den Einstellungen des Browsers, nicht hier."
    let webNotifyUnsupported = "Dieser Browser kann keine Benachrichtigungen zeigen."
    let webNotifyHomeScreen = "Leg clawdline auf den Home-Bildschirm und öffne es von dort — iOS schickt Benachrichtigungen nur an eine App, die dort wohnt."
    let webNotifyOnFailed = "Konnte Benachrichtigungen nicht einschalten"
    let webNotifyOffFailed = "Konnte Benachrichtigungen nicht ausschalten"

    let webSettings = "Einstellungen"
    let webSettingsNotify = "Benachrichtigungen"
    let webSettingsAssistantIcons = "Assistenten-Symbole"
    let webSettingsAssistantIconsSay = "Zeigt im Gespräch das Symbol von Claude oder Codex vor seinem Namen."
    let webSettingsAssistantIconsShow = "Symbole anzeigen"
    let webSettingsVersion = "Version {v}"
    let webClose = "Schließen"
    let webNotifySheetOff = "Diesem Gerät wird nicht gesagt, wenn eine Sitzung wartet."
    let webNotifyTest = "Test schicken"
    let webNotifyTestSent = "Geschickt — gleich sollte er auf diesem Gerät ankommen."
    let webNotifyTestNone = "Der Mac hat keinen Eintrag für dieses Gerät. Schalte Benachrichtigungen aus und wieder ein, dann trägt sich dieser Browser neu ein."
    let webNotifyTestFailed = "Konnte keine Testbenachrichtigung schicken"
    let webSending = "Wird gesendet…"
    let webSendTip = "Return sendet · Umschalt-Return macht eine neue Zeile"
    let webStart = "Sitzung starten"
    let webStartLabel = "Eine Sitzung in einem Projekt starten"
    let webStartPick = "Wo soll sie starten?"
    let webStartWith = "Womit soll sie starten?"
    let webStartEmpty = "Noch nirgends zu starten. Lass Claude Code einmal auf dem Mac laufen, dann steht es hier."
    let webStartFilter = "Projekte filtern"
    let webStarting = "Tab wird geöffnet…"
    let webStartWaiting = "Gestartet. Sie taucht gleich auf…"
    let webStartSlow = "Der Tab ist offen, aber die Sitzung hat sich nicht gemeldet. Schau am Mac nach."
    let webStartFailed = "Das ließ sich nicht starten."
    let webStartGone = "Dieses Projekt ist nicht mehr auf dem Mac."
    let webStartTerminalClosed = "Auf dem Mac läuft {app} nicht. Öffne es dort und versuch es noch einmal."
    let webStartTerminalUnsupported = "Von hier aus lässt sich in {app} keine Sitzung starten. Lass darin tmux laufen, dann geht es."
    let webStartOff = "Sitzungen zu starten ist ausgeschaltet. Einstellungen → Fernzugriff auf dem Mac schaltet es ein."
    let webResumeWith = "Ein früheres fortsetzen"
    let webResumePick = "Welches Gespräch?"
    let webResumeFilter = "Gespräche filtern"
    let webResumeEmpty = "In diesem Projekt wurde noch nichts aufgezeichnet."
    let webResumeLive = "offen"
    let webResumeBack = "Anderes Projekt"
    let webResumeGone = "Dieses Gespräch ist nicht mehr auf dem Mac."
    let webResumeClaudeOnly = "Nur Claude Code bewahrt Gespräche auf, die sich fortsetzen lassen."
    let webResuming = "Wird fortgesetzt…"
    let webResumeCapped = "Ältere als diese stehen nicht auf dieser Liste."
    let webCommand = "Sag, was du starten willst"
    let webCommandLabel = "Eine Sitzung starten, indem du sagst, was sie tun soll"
    let webCommandSay = "Bevor du unten auf „Starten“ drückst, wird nichts gesendet."
    let webCommandHeard = "Was soll es tun?"
    let webCommandThinking = "Denkt nach…"
    let webCommandDraft = "Entwurf"
    let webCommandWhere = "Wo"
    let webCommandWith = "Womit"
    let webCommandFirst = "Erste Nachricht"
    let webCommandGo = "Starten"
    let webCommandUnsure = "Nicht sicher, welches Projekt — wähle unten eins aus."
    let webCommandFailed = "Konnte daraus keinen Entwurf machen."
    let webCommandNoPlanner = "Dieser Mac hat kein Claude Code, um daraus einen Entwurf zu machen."
    let webCommandBusy = "Ein Satz wird gerade schon zu einem Entwurf — versuch es gleich noch mal."
    let webCommandEmpty = "Nichts gehört"
    let webScheduleNew = "Neuer Zeitplan"
    let webScheduleEdit = "Zeitplan bearbeiten"
    let webScheduleNewSay = "Bevor du unten auf „Erstellen“ drückst, wird nichts geplant."
    let webScheduleTitle = "Titel"
    let webScheduleAt = "Um"
    let webScheduleOn = "Tage"
    let webScheduleWhere = "Wo"
    let webScheduleWith = "Womit"
    let webScheduleFirst = "Erste Nachricht"
    let webScheduleMore = "Mehr"
    let webScheduleWhenDone = "Den Tab schließen, wenn es fertig ist"
    let webScheduleCloseSuccess = "Wenn es geklappt hat"
    let webScheduleCloseAlways = "Immer"
    let webScheduleCloseNever = "Offen lassen"
    let webScheduleEnabled = "Aktiviert"
    let webScheduleDisabled = "Deaktiviert"
    let webScheduleNotify = "Mir Bescheid sagen, wenn es fehlschlägt"
    let webScheduleCatchUp = "Wenn verpasst, innerhalb von (Stunden) nachholen"
    let webScheduleTimeout = "Aufgeben, wenn es nicht in (Minuten) fertig ist"
    let webScheduleCreate = "Erstellen"
    let webScheduleCreated = "Zeitplan erstellt."
    let webScheduleFailed = "Zeitplan konnte nicht erstellt werden."
    let webScheduleSave = "Speichern"
    let webScheduleSaved = "Zeitplan gespeichert."
    let webScheduleDelete = "Löschen"
    let webScheduleDeleteAsk = "{title} löschen? Das lässt sich nicht rückgängig machen."
    let webScheduleDeleted = "Zeitplan gelöscht."
    let webScheduleNeedsTime = "Keine Uhrzeit gehört — leg eine fest."
    let webScheduleNeedsPlace = "Nicht sicher, welches Projekt — wähle eins aus."
    let webScheduleDaily = "Täglich"
    let webScheduleSun = "So"
    let webScheduleMon = "Mo"
    let webScheduleTue = "Di"
    let webScheduleWed = "Mi"
    let webScheduleThu = "Do"
    let webScheduleFri = "Fr"
    let webScheduleSat = "Sa"
    let webLinks = "Adressen"
    let webLinksTip = "Wo dieses Projekt sich öffnen lässt"
    let webLinksPick = "Alles, wofür dieses Projekt eine Adresse hat."
    let webLinksEmpty = "Dieses Projekt hat nichts mit einer Adresse — keine Website, kein Deploy, und kein Server läuft."
    let webLinksFailed = "Konnte die Adressen dieses Projekts nicht lesen."
    let webLinksLocal = "Nur im Netz des Macs selbst. Von hier aus geht das nicht auf."
    let webLinksFile = "Eine Datei auf dem Mac. Sie geht dort auf, nicht in diesem Browser."
    let webLinksCopy = "Pfad kopieren"
    let webLinksCopied = "Kopiert."
    let webLinksCopyFailed = "Dieser Browser hat die Seite das nicht kopieren lassen."
    let webLinkOk = "ok"
    let webLinkFail = "Fehler"
    let webLinkDown = "aus"
    let webLinkRunning = "läuft"
    let webSessionInfo = "Sitzungsinfo"
    let webInfoTitle = "Über diese Sitzung"
    let webInfoSession = "Diese Sitzung"
    let webInfoAssistant = "Assistent"
    let webInfoModel = "Modell"
    let webInfoSessionId = "Sitzungs-ID"
    let webInfoDirectory = "Verzeichnis"
    let webInfoRunningFor = "Läuft seit"
    let webInfoUsage = "Token-Verbrauch"
    let webInfoInput = "Eingabe"
    let webInfoOutput = "Ausgabe"
    let webInfoCacheRead = "Cache gelesen"
    let webInfoCacheWrite = "Cache geschrieben"
    let webInfoTotal = "Gesamt"
    let webInfoCost = "Geschätzte Kosten"
    let webInfoNoUsage = "Für diese Sitzung wurde noch kein Transkript gefunden."
    let webInfoLimits = "Kontingent"
    let webInfoLimitHit = "Kontingent aufgebraucht"
    let webInfoResets = "wird {when} zurückgesetzt"
    let webInfoUnknown = "unbekannt"
    let webInfoFiles = "Dateien"
    let webInfoBranch = "Branch"
    let webInfoStaged = "Vorgemerkt"
    let webInfoUnstaged = "Geändert"
    let webInfoUntracked = "Nicht verfolgt"
    let webInfoConflict = "Konflikte"
    let webInfoClean = "Nichts Uncommittetes."
    let webInfoNotRepo = "Kein Git-Repository."
    let webInfoDeploy = "Letzter Deploy"
    let webInfoNoDeploy = "Für dieses Projekt ist kein Deploy verzeichnet."
    let webInfoFailed = "Konnte die Infos dieser Sitzung nicht lesen."
    let webInfoBusy = "Der Mac ist gerade mit anderen Sitzungen beschäftigt. Versuch es gleich noch mal."
    let webInfoRefresh = "Aktualisieren"
    let webInfoTokens = "Tokens"
    let webInfoSwitchModel = "Modell wechseln"
    let webInfoModelOther = "anderes Modell…"
    let webInfoModelSent = "/model {model} gesendet. Wird bestätigt…"
    let webInfoModelBusy = "Gewechselt wird erst, wenn die Sitzung untätig ist."
    let webInfoSwitchPermission = "Berechtigungsmodus wechseln"
    let webInfoPermissionAuto = "Automatisch"
    let webInfoPermissionManual = "Manuell"
    let webInfoPermissionAcceptEdits = "Änderungen akzeptieren"
    let webInfoPermissionPlan = "Plan"
    let webInfoPermissionUnreadable = "Der aktuelle Modus konnte nicht gelesen werden."
    let webInfoPermissionSent = "Zu „{mode}“ gewechselt. Wird bestätigt…"
    let webInfoPermissionBusy = "Der Berechtigungsmodus wird gerade gewechselt."
    let webInfoLimitsClaude = "Claude Code notiert ein Fenster erst, wenn es aufgebraucht ist; bis dahin ist nichts bekannt."
    let webInfoCopied = "Sitzungs-ID kopiert."
    let webInfoAsOf = "Stand {when}"
    let webInfoWhyUnknown = "Warum unbekannt, und wie die Zahlen kommen"
    let webSettingsOrder = "Verlauf"
    let webSettingsOrderSay = "Von welchem Ende her ein Verlauf gelesen wird. Das gilt für jede Sitzung, und auf der Tastatur macht `r` dasselbe."
    let webAskLabel = "hat gefragt"
    let webAskAny = "Beliebig viele davon"
    let webWaitingTitle = "Diese Sitzung wartet auf eine Antwort"
    let webWaitingSay = "Claude Code zeigt am Mac ein Menü. Clawdline kann ein Menü von hier aus noch nicht lesen, die Auswahl steht also nur auf jenem Bildschirm."
    let webWaitingSend = "*Von hier zu senden tippt deine Antwort nicht ins Menü* — es bestätigt die Zeile, die im Menü gerade hervorgehoben ist, und das ist selten die gemeinte. Diese eine beantwortest du am Mac."
    let webMenuSay = "Tipp eine Antwort an, sie geht direkt an die Sitzung."
    let webMenuHighlighted = "ausgewählt"
    let webMenuSent = "Antwort ist raus."
    let webAgents = "Agenten im Hintergrund"
    let webAgentsCount = "{n} laufen"
    let webAgentDone = "fertig"
    let webAgentFailed = "fehlgeschlagen"
    let webShells = "Shells im Hintergrund"
    let webShellTitle = "Shell im Hintergrund"
    let webShellOpen = "Ansehen, was dieser Befehl ausgibt"
    let webShellRunning = "läuft noch"
    let webShellEnded = "beendet"
    let webShellQuiet = "Noch keine Ausgabe."
    let webShellFailed = "Die Ausgabe dieses Befehls konnte nicht gelesen werden."
    let webShellClose = "Schließen"
    let webShellStop = "Stoppen"
    let webShellStopTitle = "Diesen Befehl stoppen?"
    let webShellStopSay = "{command} läuft noch. Er wird gebeten aufzuhören und fünf Sekunden später beendet, falls nicht. Was er schon getan hat, wird nicht rückgängig gemacht."
    let webShellStopped = "Stopp wurde angefordert."
    let webShellStopFailed = "Konnte nicht gestoppt werden."
    let agentRunning = "läuft"
    let agentTools = "{n} Werkzeuge"
    let agentEmpty = "Dieser Agent hat noch nichts festgehalten."
    let agentBack = "Sitzung"
    let webAgentOpen = "Ansehen, was dieser Agent gemacht hat"
    let webTaskRoot = "Eltern"
    let webTaskChild = "Kind"
    let webTaskTasks = "Aufgaben"
    let webTaskDone = "fertig"
    let webTaskFailed = "fehlgeschlagen"
    let webTaskRunning = "läuft"
    let webStale = "Clawdline wurde am Mac neu gebaut. Diese Seite ist die ältere."
    let webStaleGo = "Neu laden"

    let menuOpen = "Eingabeleiste öffnen"
    let menuReveal = "Zum Ziel-Tab springen"
    let menuMascot = "Maskottchen"
    let menuLogin = "Bei der Anmeldung öffnen"
    let menuEditConfig = "Einstellungen …"
    let menuReload = "Konfiguration neu laden"
    let menuQuit = "Clawdline beenden"
    let menuNoTarget = "(noch nicht erkannt)"

    func hotkeyFailedTitle(_ combo: String) -> String { "\(combo) ließ sich nicht registrieren" }
    func hotkeyFailedBody(_ configPath: String) -> String {
        """
        Wahrscheinlich benutzt eine andere App das Kürzel schon — Spotlight, ein \
        Eingabequellen-Umschalter, BetterTouchTool und dergleichen.

        Nimm ein anderes: Bearbeite „hotkey“ in \(configPath) und wähle dann in der \
        Menüleiste „Konfiguration neu laden“.

        Bis dahin öffnet das ✳ in der Menüleiste die Eingabeleiste weiterhin.
        """
    }
    let loginFailed = "Konnte den Start bei der Anmeldung nicht einrichten"
}
