import Foundation

struct Spanish: Copy {
    let placeholder = "Escribe a Claude Code…"

    let hintSend = "enviar"
    let hintNewline = "nueva línea"
    let hintSwitch = "cambiar"
    let hintList = "lista"
    let hintMascot = "mascota"
    let hintOutput = "salida"
    let hintFullscreen = "pantalla completa"
    let hintKeys = "teclas"
    let hintTextSize = "tamaño"
    let hintOrder = "invertir"
    let hintVoice = "dictar"
    func voiceListening(onDevice: Bool) -> String {
        onDevice ? "Escuchando en este Mac — pulsa otra vez para parar"
                 : "Escuchando — este idioma lo transcribe Apple, no este Mac"
    }
    let voiceNoPermission = "El dictado necesita acceso al micrófono y al reconocimiento de voz"
    let voiceUnavailable = "El dictado no está disponible ahora mismo"
    func voiceTranscribing(seconds: Double) -> String {
        String(format: "Whisper lo está releyendo… %.1f s", seconds)
    }
    let whisperMissing = "Whisper no está instalado — consulta docs/whisper.md"
    let whisperNothingHeard = "No se oyó nada"
    func dictationStatus(_ status: Whisper.Status) -> String {
        switch status {
        case .ready(let model): return "Dictado: Apple y después Whisper (\(model))"
        case .noBinary: return "Dictado: solo Apple — falta whisper-cli"
        case .noModel: return "Dictado: solo Apple — whisper-cli está, falta el modelo"
        }
    }
    func voiceListeningWhisper() -> String {
        "Escuchando — Whisper lo revisa otra vez cuando pares"
    }

    let scanning = "Buscando…"
    let noSession = "No se encontró ninguna sesión de Claude Code"
    let nothingToSend = "No hay destino — abre antes Claude Code en una terminal"
    let sendFailed = "No se pudo enviar"
    let itermSilent = "iTerm2 no respondió"
    let itermBusy = "iTerm2 está esperando un diálogo — respóndelo en el Mac"
    let scriptMissing = "Falta iterm.js — ¿paquete de la app dañado?"
    let cannotList = "No se pudieron leer las sesiones de iTerm2"
    let noOutput = "Todavía no hay nada que leer en esta sesión."
    let imageExpired = "Imagen caducada"
    let imagePreview = "Vista previa de la imagen"
    let imageClose = "Cerrar vista previa"
    let imageTooLarge = "Demasiado grande para enviar ({mb} MB)"
    let imageUnavailable = "La imagen no llegó"
    func outputSize(_ pt: Int) -> String { "Texto de salida \(pt) pt — ⌘J para verlo" }
    func foldedTools(_ count: Int) -> String { "\(count) pasos" }
    func outputOrder(newestFirst: Bool) -> String {
        newestFirst ? "Lo más reciente primero" : "Lo más antiguo primero"
    }
    func backlogNow(_ count: Int) -> String { "ahora \(count)" }
    func dropped(_ count: Int) -> String {
        count == 1 ? "Ruta añadida — Claude Code la lee" : "Se añadieron \(count) rutas"
    }
    func stackConfirm(_ command: String) -> String { "Pulsa otra vez para ejecutar:  \(command)" }
    let hintStacks = "servidores"
    func stackTip(up: Int, total: Int) -> String { "\(up) de \(total) servidores activos — ⌘S para la lista" }
    let stackTipUnknown = "Este proyecto tiene servidores; su comando de estado aún no es de confianza — ⌘S"
    let stackUntrusted = "sin aprobar"
    let stackExit = "salida"
    let stackActionStart = "iniciar"
    let stackActionRestart = "reiniciar"
    let stackActionStop = "detener"
    let stackActionLogs = "registro"
    let stackLogAll = "todos"
    let stackLogBack = "transcripción"
    let stackActionAllow = "permitir"
    let stackActionAgain = "otra vez"
    func sessionTip(index: Int, total: Int) -> String { "Sesión \(index) de \(total) — ⌘K para cambiar" }
    let sessionWaiting = "te está esperando"
    let sessionAgents = "{n} en segundo plano"
    let sessionShellOne = "1 shell en marcha"
    let sessionShellMany = "{n} shells en marcha"
    let sessionWaitedOnByOne = "1 te espera"
    let sessionWaitedOnByMany = "{n} te esperan"
    let islandDone = "listo"
    let islandAllSessions = "Todas las sesiones…"
    func statusWaiting(_ labels: [String]) -> String {
        labels.count == 1 ? "\(labels[0]) te está esperando"
                          : "\(labels.count) sesiones te están esperando"
    }
    func statusWorking(_ count: Int) -> String { "\(count) en marcha" }

    let settingsTitle = "Ajustes de Clawdline"
    let settingsGeneral = "General"
    let settingsBar = "La barra"
    let settingsReading = "Lectura"
    let settingsVoice = "Dictado"
    let settingsHotkey = "Atajo"
    let settingsRecording = "Pulsa unas teclas…"
    let settingsScope = "Se activa en"
    let settingsScopeGlobal = "En todas las apps"
    let settingsScopeHint = "Vacío significa en todas partes, así que quitar la última enciende el interruptor de arriba — y volver a apagarlo devuelve la lista. El archivo de configuración las guarda como identificadores de bundle, y una lista editada a mano sigue funcionando."
    let settingsSessionTerminal = "Las sesiones nuevas se abren en"
    let settingsSessionTerminalHint = "No es lo mismo que dónde funciona el atajo. Automático usa iTerm2 cuando está abierto y tmux cuando no; iTerm2 pide iTerm2 en concreto, así que un servidor tmux al lado no cuenta como respuesta y con iTerm2 cerrado hay un rechazo; tmux pone la sesión en un servidor tmux aunque iTerm2 esté abierto. Se aplica a la próxima sesión, sin reiniciar nada."
    let settingsScopeAdd = "Añadir una app…"
    let settingsScopeChoose = "Elegir una app…"
    let settingsScopeRunning = "Abiertas ahora mismo"
    let settingsScopeRemove = "Quitar"
    let settingsLanguage = "Idioma"
    let settingsReopen = "La barra va y viene con el terminal"
    let settingsReopenHint = "Salir del terminal guarda la barra, y volver a él la trae de vuelta. Esc es lo que quiere decir que has terminado con ella."
    let settingsFollow = "El terminal muestra aquello a lo que apunta la barra"
    let settingsFollowHint = "Selecciona la pestaña de esa sesión. No trae el terminal al frente: si lo hiciera, cada pulsación de Tab te sacaría el teclado de la casilla en la que estás escribiendo."
    let settingsCodexAutoName = "Nombrar nuevas sesiones"
    let settingsCodexAutoNameHint = "Ejecuta un pequeño turno con el asistente elegido por cada sesión sin nombre. Usa la primera petición, consume el uso de ese asistente y nunca sustituye un nombre que hayas elegido."
    let settingsNotch = "Vivir en la muesca"
    let settingsNotchHint = "Un personaje en la carcasa de la cámara. Desactivado es desactivado: no se dibuja nada ni se crea ventana."
    let settingsPosition = "Altura en pantalla"
    let settingsWidth = "Anchura"
    let settingsOpacity = "Opacidad de la tarjeta"
    let settingsShow = "Mostrar"
    let settingsPaneHeight = "Altura del panel"
    let settingsTextSize = "Tamaño del texto"
    let settingsPaneFont = "Fuente del panel"
    let settingsBlur = "Desenfoque detrás"
    let settingsNewestFirst = "Lo más reciente arriba"
    let settingsEngine = "Reconocedor"
    let settingsSettle = "Una pausa termina la frase"
    let settingsStop = "Un silencio termina la sesión"
    let settingsAuto = "Automático"
    let settingsTranscript = "Transcripción"
    let settingsTerminal = "Terminal"
    let settingsOff = "Desactivado"
    let settingsHooks = "Hooks de Claude Code"
    let settingsHooksHint = "Con ellos instalados, Claude Code avisa en el instante en que un turno empieza, termina o espera una respuesta, en lugar de que Clawdline se entere en la siguiente comprobación. Todo se sigue leyendo de la pantalla; esto solo decide con qué rapidez."
    let settingsHooksInstall = "Instalar"
    let settingsHooksRemove = "Quitar"
    let settingsHooksOff = "Sin instalar — todo se lee de la pantalla"
    let settingsHooksOn = "Instalados — ninguna sesión ha avisado todavía"
    let settingsHooksLive = "Instalados, y las sesiones avisan"
    let settingsStateHook = "Cuando una sesión cambia de estado"
    let settingsStateHookHint = "Cada vez que una sesión se pone a trabajar, termina o te pregunta algo, Clawdline ejecuta esto: tu propio programa, con los detalles en su entorno. Se escribe en el archivo de configuración y no aquí porque es un argv y no una línea de órdenes — una ruta con un espacio dentro tiene que seguir siendo una sola ruta."
    let settingsRemote = "Acceso remoto"
    let settingsRemoteServe = "Dejar que un navegador o tu teléfono vean tus sesiones"
    let settingsRemoteHint = "Desactivado, nada de fuera de este Mac llega a nada. Activado, la lista de sesiones se sirve en 127.0.0.1: para un navegador de aquí, para un teléfono al otro lado de un túnel, para un script. Lo que eso entrega son nombres de repositorios, ramas y títulos de tareas, y por eso sigue apagado hasta que digas lo contrario."
    let settingsRemoteDevices = "Dispositivos vinculados"
    let settingsRemoteNoDevices = "Ninguno todavía — fuera de este Mac nadie puede leer nada"
    let settingsRemoteRevokeAll = "Desconectar todo"
    let settingsRemoteOpen = "Abrir en el navegador"
    let pairingIgnore = "Ignorar"
    func pairingAsks(_ device: String) -> String { "\(device) quiere vincularse con este Mac" }
    func pairingCode(_ code: String) -> String {
        """
        Escribe este código en ese dispositivo:

        \(code)

        Vale dos minutos. Si no acabas de pedirlo tú, ignóralo — sin este código, quien lo \
        pidió no puede terminar.
        """
    }
    let settingsTunnel = "Llegar a este Mac desde cualquier sitio"
    let settingsTunnelQuick = "Una dirección generada"
    let settingsTunnelNamed = "Mi propio dominio"
    let settingsTunnelHostname = "Nombre de host"
    let settingsTunnelHint = "Abre una conexión saliente a través de cloudflared: sin redirección de puertos y sin nada a la escucha en tu red. No arranca hasta que haya un dispositivo vinculado, porque detrás del túnel está el nombre de cada repositorio y el título de cada tarea de este Mac."
    let settingsRemoteWrite = "Dejar que un dispositivo vinculado escriba en una sesión"
    let settingsRemoteWriteHint = "Desactivado, un dispositivo vinculado solo puede leer. Activado, puede enviar texto a una sesión y abrir sesiones nuevas — lo que ejecuta código en este Mac, porque eso es lo que hace Claude Code. Es una decisión distinta de la de arriba, así que es un interruptor distinto."
    let settingsRemotePhone = "Vincular un teléfono…"
    let settingsRemotePhoneHint = "Muestra un código para escanear. Lleva una clave propia: una foto de ese código es un dispositivo que ves en esta lista y que puedes quitar cuando quieras — no la clave de este Mac."
    let pairingScanTitle = "Escanea esto con el teléfono"
    let pushWaiting = "espera una respuesta"
    let pushTest = "Notificación de prueba. Todo está bien conectado."
    let pushDelivered = "ha entregado y te está esperando"
    let pushDeployOk = "el deploy ha ido bien"
    let pushDeployFail = "el deploy ha fallado"
    func pushChildWaiting(minutes: Int?) -> String {
        guard let minutes else { return "tiene una sesión hija esperando" }
        return "tiene una sesión hija esperando — quedan \(minutes) min"
    }
    func pushBatchDone(done: Int, failed: Int) -> String {
        let all = done == 1 ? "ha terminado 1 tarea" : "ha terminado \(done) tareas"
        return failed == 0 ? all : "\(all), \(failed) con error"
    }
    let settingsPushDelivery = "Avisar cuando una sesión informe de que ha entregado"
    let settingsPushDeliveryHint = "Una vez por aviso; repetir el mismo no suena."
    let settingsPushFanout = "Avisar cuando acabe un lote de tareas"
    let settingsPushFanoutHint = "Un solo aviso para todo el lote, con cuántas han fallado."
    let settingsSmartNotifications = "Notificaciones inteligentes"
    let settingsSmartNotificationsHint = "Haiku resume en una frase el trabajo terminado. Si falla, se envía el aviso normal."
    func pushCoalesced(count: Int) -> String { "\(count) trabajos terminados a la vez" }
    let settingsSmartHealthIdle = "Aún no se ha intentado ninguna notificación inteligente."
    func settingsSmartHealth(attempts: Int, successes: Int) -> String {
        "\(successes) de \(attempts) intentos entregaron una frase del modelo."
    }
    func settingsSmartHealthFailure(reason: String, time: String) -> String {
        "Último repliegue a las \(time): \(reason)."
    }
    func settingsSmartTimeout(seconds: Int) -> String {
        "Claude superó el plazo de \(seconds) s y fue interrumpido"
    }
    let settingsSmartQueueFull = "llegaron más finales de los que caben en la cola"
    let settingsSmartModelFailed = "Claude no devolvió nada utilizable"
    let settingsSmartNoSource = "no había nada que resumir"
    let settingsSmartMissing = "no se encontró el ejecutable claude"
    let settingsPushDeploy = "Avisar cuando acabe un deploy"
    let settingsPushDeployHint = "Tanto si sale bien como si falla."
    let settingsAgentNotify = "Permitir que los agentes envíen sus propias notificaciones"
    let settingsAgentNotifyNote = "Solo controla el contenido que un agente envía por iniciativa propia; las notificaciones de fin, deploy y las demás no cambian."
    let settingsOrchestrator = "Tareas entre sesiones"
    let settingsOrchestratorEnabled = "Dejar que una sesión encargue trabajo a otra"
    let settingsOrchestratorEnabledHint = "Una sesión con la skill clawdline puede abrir una pestaña, dictarle las instrucciones y enterarse cuando el trabajo termina. Apagado, se rechaza cada encargo; nada de lo que ya está en marcha se detiene."
    let settingsOrchestratorMax = "Sesiones hijas a la vez"
    let settingsOrchestratorMaxHint = "Cinco por defecto, y se cuentan por sesión, no por Mac. Cada una es una pestaña del terminal con un asistente trabajando dentro."
    let settingsOrchestratorPermission = "Hasta dónde puede llegar una hija"
    let settingsOrchestratorPermissionHint = "Nadie está mirando la pestaña de una sesión hija, así que una que se detiene a pedir permiso se detiene hasta que expira — y el trabajo de una sesión despachada consiste por completo en ejecutar comandos y escribir archivos, así que cualquier cosa por debajo de la última opción la detiene en algún punto. Una tarea puede pedir menos que esto, nunca más."
    let settingsOrchestratorPermissionAsk = "Preguntar en cada paso"
    let settingsOrchestratorPermissionEdits = "Escribir archivos sin preguntar"
    let settingsOrchestratorPermissionFull = "No preguntar nunca"
    let settingsOrchestratorNotify = "Avisar a la sesión que lo pidió"
    let settingsOrchestratorNotifyHint = "Una línea escrita de vuelta en ella cuando la tarea termina."
    let settingsOrchestratorClose = "Cuando una sesión hija informa"
    let settingsOrchestratorCloseHint = "Su pestaña se cierra después de informar; la de una que se quedó sin tiempo se queda ahí para que la leas."
    let settingsOrchestratorCloseNow = "Cerrar la pestaña enseguida"
    let settingsOrchestratorCloseLinger = "Cerrarla a los tres minutos"
    let settingsOrchestratorCloseKeep = "Dejarla abierta"
    let settingsOrchestratorPolicy = "Cómo se reparte el trabajo"
    let settingsOrchestratorPolicyHint = "Reglas que Clawdline lee en cada envío y copia en las instrucciones de cada sesión hija que puede enviar a su vez: qué asistente, qué modelo, qué forma debe tener el grafo. Vacío significa sin reglas."
    let settingsOrchestratorPolicyEdit = "Editar las reglas"
    func settingsOrchestratorPolicyOn(_ lines: Int) -> String { return "En vigor — \(lines) líneas" }
    let settingsOrchestratorPolicyOff = "Sin reglas — cada envío lo decide quien lo hace"
    let settingsSchedules = "Tareas programadas"
    let settingsSchedulesEmpty = "Aún no hay programaciones. El botón Nueva programación de abajo crea la primera."
    let settingsScheduleNew = "Nueva tarea programada"
    let settingsScheduleEdit = "Editar"
    let settingsScheduleSave = "Guardar"
    let settingsScheduleDelete = "Eliminar"
    let settingsScheduleRun = "Ejecutar ahora"
    let settingsScheduleReveal = "Mostrar en Finder"
    let settingsSchedulesFolder = "Abrir carpeta schedules"
    let settingsScheduleNext = "Próxima"
    let settingsScheduleLast = "Última"
    let settingsScheduleNever = "Sin ejecuciones"
    let settingsScheduleStarted = "Ejecución iniciada."
    let settingsScheduleActive = "La tarea programada anterior sigue activa."
    let webScheduleMissed = "Última omitida"
    let webScheduleNoNext = "No hay una próxima ejecución programada."
    func childAnnounce(_ title: String) -> String { "Encargo de Clawdline recibido: \(title) — empiezo ahora." }
    func settingsSeconds(_ value: Double) -> String { String(format: "%.1f s", value) }

    let webConnLive = "en vivo"
    let webConnConnecting = "conectando"
    let webConnRetrying = "reintento en {n}s"
    let webConnOffline = "sin conexión"
    let webConnLocked = "sin vincular"
    let webConnTipLive = "En vivo desde la app"
    let webConnTipLocked = "Este navegador no está vinculado con el Mac"
    let webConnTipDown = "Sin conexión — pulsa para intentarlo ahora"

    let webCountWorking = "{n} en marcha"
    let webCountWaiting = "{n} esperando"
    let webCountUnreadable = "{n} ilegibles"
    let webCountQuietOne = "{n} sesión, todo tranquilo"
    let webCountQuietMany = "{n} sesiones, todo tranquilo"
    let webCountNone = "sin sesiones"

    let webFilterPlaceholder = "Filtra por tarea, proyecto o tty"
    let webFilterLabel = "Filtrar sesiones"
    let webListLabel = "Sesiones de Claude Code"
    let webPull = "Tira para actualizar"
    let webPullRelease = "Suelta para actualizar"
    let webPullBusy = "Actualizando…"
    let webEmptyFilterTitle = "Nada coincide con “{q}”"
    let webEmptyFilterHint = "Esc borra el filtro"
    let webEmptyLockedTitle = "Este dispositivo no está vinculado"
    let webEmptyLockedHint = "La app respondió 401 — vincúlalo desde Clawdline en el Mac"
    let webEmptyNoneHint = "Inicia una en un terminal y aparecerá aquí"
    let webEmptyWaitTitle = "Esperando a la app"
    let webEmptyWaitHint = "Todavía no ha llegado nada por la conexión"
    let webStateUnreadable = "no se pudo leer la pantalla"
    let webStateWorking = "en marcha"
    let sessionWorkReady = "puede recibir trabajo"
    let sessionWorkUnknown = "estado desconocido"
    let sessionWorkHolding = "avanza por sí solo"
    let sessionWorkOwed = "se le debe una decisión"
    let sessionWorkSelfStated = "autodeclarado"
    let sessionWorkMilestone = "Hito entregado; puede quedar revisión o integración"
    let sessionWorkComplete = "Integración en la rama de destino verificada por el broker"
    let closeabilitySafe = "Se puede cerrar sin riesgo"
    let closeabilityBlocked = "Quedan {n} obligaciones"
    let closeabilityBlockedOne = "Queda 1 obligación"
    let closeabilityBlockedMany = "Quedan {n} obligaciones"
    let closeabilityNeedsAttestation = "Esperando la atestación de la sesión"
    let closeabilityUnknown = "Cierre indeterminado"
    let closeabilityWhy = "No se puede cerrar porque"
    let closeabilityMoverSelf = "lo mueve esta sesión"
    let closeabilityMoverPerson = "lo mueves tú"
    let closeabilityMoverSession = "lo mueve otra sesión"
    let closeabilityMoverBroker = "lo mueve una lectura nueva"
    let closeabilityNotProven = "El broker no pudo probar que esta sesión se puede cerrar sin riesgo."
    let closeabilityAttestationExplanation = "Esto no significa que se haya encontrado trabajo sin terminar. Las comprobaciones que Clawdline puede hacer están resueltas, pero esta sesión aún no confirmó si dejó cambios locales, trabajo sin entregar o trabajo fuera de Clawdline. Revisa la sesión antes de cerrarla."
    let closeabilityTechnicalDetails = "Detalles técnicos"

    let webBack = "Sesiones"
    let webBackLabel = "Volver a la lista de sesiones"
    let webMenu = "Menú"
    let webPages = "Páginas"
    let webSessions = "Sesiones"
    let webUsage = "Uso"
    let webNoSessionOpen = "Ninguna sesión abierta"
    let webOrderTip = "Invertir la transcripción (r)"
    let webShowOnMac = "Ver en el Mac"
    let webShowOnMacTip = "Trae al frente el terminal de esta sesión en el Mac"
    let webShowOnMacOff = "El servidor responde write: false — todavía no se puede enviar nada"
    let webShowOnMacAsked = "Le pedimos al Mac que lo traiga al frente"
    let webSessionActions = "Acciones de la sesión"
    let webSessionGit = "Cambios de Git"
    let webScreenTitle = "Pantalla"
    let webScreenLive = "en vivo"
    let webScreenOnDemand = "a petición"
    let webScreenGone = "No se pudo leer esa pantalla"
    let webGitTitle = "Cambios de Git"
    let webGitClean = "Árbol de trabajo limpio"
    let webGitNotRepo = "No es un repositorio Git"
    let webGitFailed = "No se pudieron leer los cambios de Git"
    let webGitRefresh = "Actualizar"
    let webGitClose = "Cerrar"
    let webGitStaged = "Preparado"
    let webGitUnstaged = "Sin preparar"
    let webGitUntracked = "Sin seguimiento"
    let webGitConflict = "Conflicto"
    let webEndSession = "Cerrar sesión"
    let webConfirmActionTitle = "¿Ejecutar {action}?"
    let webConfirmActionSay = "Esto envía {action} a la sesión actual."
    let webConfirmEndTitle = "¿Cerrar esta sesión?"
    let webConfirmEndSay = "El asistente saldrá y después se cerrará su pestaña del terminal."
    let webConfirmEndLoses = "Cerrar también termina:"
    let webClawdfatherCreateLabel = "Nombrar Clawdfather a la nueva sesión"
    let webClawdfatherIs = "Esta sesión es {name}"
    let webClawdfatherRegisterAsk = "Registra esta nueva sesión como el Clawdfather de este Mac, el coordinador de la máquina. Tu id de sesión neutral respecto al terminal es {id}. Lee el registro del coordinador con el token de orquestador de ~/.config/clawdline/orchestrator-token. Solo si no hay ningún coordinador configurado, sigue la parte de registro de «Becoming Clawdfather» en docs/orchestrator.md. Si ya hay un coordinador configurado, aunque esté desconectado, no lo sustituyas. Después cuenta qué pasó."
    let webClawdfatherRegisterSent = "Se pidió a la nueva sesión que sea Clawdfather"
    let webClawdfatherRegisterLate = "La nueva sesión no estuvo lista a tiempo para nombrarla Clawdfather."
    let webClawdfatherRegisterBlocked = "El registro del coordinador de este Mac no se puede leer, así que se deja intacto."
    let webCoordSectionObserve = "Observar"
    let webCoordSectionCoordinate = "Coordinar"
    let webCoordSectionPresence = "Presencia"
    let webCoordSectionAdmin = "Administración"
    let webCoordCmdStatusReport = "Informe de estado"
    let webCoordCmdStatusReportSay = "Leer el estado actual de Clawdfather y sus obligaciones activas."
    let webCoordCmdSinceAway = "Desde que te fuiste"
    let webCoordCmdSinceAwaySay = "Leer los cambios y decisiones registrados desde tu último punto de regreso."
    let webCoordCmdDuplicates = "Duplicados, conflictos y propiedad"
    let webCoordCmdDuplicatesSay = "Examinar el trabajo duplicado, las reclamaciones en conflicto y la propiedad actual."
    let webCoordCmdLandingClosure = "Cierre de entregas"
    let webCoordCmdLandingClosureSay = "Leer las entregas revisadas que aún esperan la integración de la raíz."
    let webCoordCmdCoordinateWork = "Coordinar el trabajo"
    let webCoordCmdCoordinateWorkSay = "Redactar pasos de coordinación para el trabajo ya en curso."
    let webCoordCmdDispatch = "Delegar trabajo independiente"
    let webCoordCmdDispatchSay = "Previsualizar una delegación que iniciaría una sesión hija independiente."
    let webCoordCmdAsk = "Preguntar a Clawdfather"
    let webCoordCmdAskSay = "Redactar una pregunta para el juicio de Clawdfather."
    let webCoordCmdQuietWatch = "Vigilancia silenciosa"
    let webCoordCmdQuietWatchSay = "Redactar una petición de vigilancia discreta sin levantar una alerta de espera."
    let webCoordCmdScope = "Alcance y permisos"
    let webCoordCmdScopeSay = "Leer el alcance actual de Clawdfather y los permisos concedidos."
    let webCoordCmdStop = "Detener Clawdfather"
    let webCoordCmdStopSay = "Previsualizar la detención de Clawdfather."
    let webCoordCmdReconnect = "Reconectar Clawdfather"
    let webCoordCmdReconnectSay = "Previsualizar la reconexión de Clawdfather."
    let webCoordCmdDeepAudit = "Auditoría profunda de estado"
    let webCoordCmdDeepAuditSay = "Pedir a Clawdfather que audite el trabajo, las entregas y las decisiones de las Sessions pertinentes."
    let webCoordTokenExpected = "Esfuerzo de Token esperado: {effort}"
    let webCoordTokenLow = "Bajo"
    let webCoordTokenMedium = "Medio"
    let webCoordTokenHigh = "Alto"
    let webCoordTokenUnknown = "Desconocido"
    let webCoordAuditPreview = "Solicitud de varias Sessions con alto uso de Tokens. Aún no se ha enviado nada. Confirma para enviar la instrucción completa a esta Session exacta de Clawdfather. Esta primera versión la ejecuta el agente y no tiene un registro de run persistente en el broker."
    let webCoordAuditWhyOffline = "Clawdfather está sin conexión, así que no se puede enviar la solicitud de auditoría."
    let webCoordAuditWhyDisconnected = "Este navegador está sin conexión, así que no se puede enviar la solicitud de auditoría."
    let webCoordAuditWhyNoWrite = "Este navegador no tiene actualmente capacidad de envío/escritura."
    let webCoordAuditSending = "Enviando solicitud…"
    let webCoordAuditSent = "Solicitud de auditoría enviada. Este recibo no significa que la auditoría haya terminado."
    let webCoordAuditFailed = "La solicitud de auditoría no se envió ({code}): {message}"
    let webCoordEffectRead = "Solo lectura"
    let webCoordEffectAdvisory = "Consultivo"
    let webCoordEffectSpawns = "Inicia sesión"
    let webCoordEffectMutation = "Cambia el estado"
    let webCoordStateAvailable = "Disponible"
    let webCoordStateDraft = "Borrador"
    let webCoordStateUnavailable = "No disponible"
    let webCoordStatePreview = "Vista previa"
    let webCoordStateDisabled = "Desactivado"
    let webCoordOnline = "{name} en línea"
    let webCoordOffline = "{name} desconectado"
    let webCoordControlsTitle = "Controles de {name}"
    let webCoordOpenControls = "Abrir los controles de {name}"
    let webCoordEmpty = "No se anunció ningún comando de Clawdfather reconocido."
    let webCoordDisabledFallback = "Desactivado por Clawdfather."
    let webCoordPreviewTitle = "Comando de Clawdfather"
    let webCoordPreviewNone = "Ningún comando seleccionado; no se ha enviado nada."
    let webCoordPreviewMutation = "Solo vista previa — no se ha enviado nada. La confirmación sigue bloqueada hasta que la API de comandos de Clawdfather esté conectada."
    let webCoordPreviewDraft = "Solo borrador sin conexión — no se ha enviado nada ni se ha presentado como juicio de Clawdfather."
    let webCoordPreviewSpawn = "Solo vista previa — no se ha iniciado ninguna sesión."
    let webCoordPreviewContract = "Solo se muestra el contrato de este comando; no se ha enviado nada."
    let webCoordWhyNoCommandRoute = "Todavía ninguna ruta lleva un comando de este panel a una sesión, así que no se puede enviar nada."
    let webCoordWhyNoReturnLedger = "Este Mac aún no registra un punto de regreso, así que no hay nada contra lo que leer."
    let webCoordWhyDeviceCannotSpawn = "Un dispositivo emparejado nunca puede iniciar una sesión — esa separación es deliberada, y este botón no la cruzará."
    let webCoordWhyMachineTokenOnly = "Reconectar exige el token de orquestador del propio Mac, que un dispositivo emparejado deliberadamente no posee."
    let webCoordReadFailed = "No se pudo leer la situación de Clawdfather."
    let webCoordActiveTasks = "{n} tareas en curso"
    let webCoordPendingLandings = "{n} entregas esperando integración"
    let webCoordOpenWaits = "{n} esperas de archivos abiertas"
    let webCoordCountUnknown = "{n} desconocidos"
    let webCoordStaleSessions = "La imagen de sesiones del Mac está desactualizada; estos números pueden ser viejos."
    let webCoordUnknown = "Desconocido"
    let webCoordWaitingList = "Esperando a alguien"
    let webCoordBlockingList = "Retiene archivos que otros esperan"
    let webCoordAllQuiet = "Nada está bloqueado, disputado ni sin dueño."
    let webCoordNoLandings = "Ninguna entrega espera su integración."
    let webCoordUnregistered = "No hay ningún Clawdfather registrado en este Mac."
    let webCoordScopeLine = "{name} coordina este Mac — alcance de máquina."
    let webCoordScopeDevice = "Desde este panel, Clawdfather solo puede leerse. Enviar trabajo, iniciar sesiones y cambiar el estado de la máquina exigen las credenciales del propio Mac, y aquí siguen desactivados."
    let webClosing = "Cerrando…"
    let webCancel = "Cancelar"
    let webConfirm = "Confirmar"
    let webReviewBeforeClosing = "Revisar la sesión"
    let webConfirmEndAnyway = "Cerrar de todos modos"
    let webPickSession = "Elige una sesión de la izquierda."
    let webReading = "Leyendo…"
    let webLoading = "Cargando…"
    let webTranscriptFailed = "No se pudo leer la transcripción"
    let webWhoYou = "tú"
    let webWhoTool = "herramienta"
    let webNoticeTask = "tarea"
    let webNoticeCompleted = "Tarea completada"
    let webNoticeFailed = "Tarea fallida"
    let webNoticeTimedOut = "Se agotó el tiempo de la tarea"
    let webNoticeCancelled = "Tarea cancelada"
    let webNoticeCouldNotStart = "No se pudo iniciar la tarea"
    let webNoticeFinished = "Tarea finalizada"
    let webNoticeWorkspaceOverlap = "Superposición del espacio de trabajo"
    let webNoticeNoSiblings = "No hay tareas hermanas aún en ejecución."
    let webNoticeOneSibling = "{n} tarea hermana sigue en ejecución."
    let webNoticeManySiblings = "{n} tareas hermanas siguen en ejecución."
    let webNoticeClaimsReleased = "Las reservas de rutas se liberaron; la pestaña hija aún podría estar escribiendo."
    let webNoticeFileWaitRequested = "Espera de archivos solicitada"
    let webNoticeFileWaitReleased = "Espera de archivos liberada"
    let webNoticeHandoffPickedUp = "Traspaso recogido"
    let webNoticeHandoffNeedsDelivery = "El traspaso requiere entrega manual"
    let webNoticeRecheckGit = "Vuelve a comprobar HEAD, status y diff antes de integrar."
    let webPending = "Esperando al Mac…"
    let webAttachedImage = "{n} imagen adjunta"
    let webAttachedImages = "{n} imágenes adjuntas"
    let webSteps = "{n} pasos"
    let webJustNow = "ahora mismo"
    let webMinutesAgo = "hace {n} min"
    let webCodeCopy = "Copiar este código"
    let webCodeCopied = "Código copiado."
    let webCodeCopyFailed = "No se pudo copiar; selecciona el texto."

    let webSend = "Enviar"
    let webAttach = "Adjuntar una imagen"
    let webRemoveShot = "Quitar {name}"
    let webWriteOpen = "Abre una sesión para escribirle."
    let webWriteOff = "*El envío está desactivado* — el servidor responde `write: false`. La casilla está lista; se enciende sola en cuanto eso cambie."
    let webShotsOnlyPictures = "Con un mensaje solo pueden ir imágenes"
    let webShotsTooMany = "Un mensaje admite {n} imágenes como mucho"
    let webShotTooBig = "Esa imagen es demasiado grande para enviarla, incluso reducida"
    let webShotsTooBig = "Esas imágenes son demasiado grandes para enviarlas juntas"
    let webShotUnreadable = "No se pudo leer esa imagen"
    let webShotNeedsSession = "Abre una sesión para enviarle una imagen"

    let webVoiceStart = "Dictar un mensaje"
    let webVoiceStop = "Parar y transcribir"
    let webVoiceDone = "Listo"
    let webVoiceListening = "Escuchando… {t}"
    let webVoiceReading = "Transcribiendo en el Mac… {n} s"
    let webVoiceSlow = "La primera después de reiniciar este Mac carga antes el modelo — unos doce segundos."
    let webVoiceLimit = "La grabación se paró a los {n} minutos, que es lo máximo que dura una. Se transcribe lo que hay."
    let webVoiceEmpty = "Ahí no se oyó nada."
    let webVoiceTooShort = "Eso fue demasiado corto para oírlo."
    let webVoiceDenied = "Se denegó el micrófono. Vuelve a activarlo en los ajustes de este navegador para este sitio."
    let webVoiceNoMic = "No se encontró ningún micrófono en este dispositivo."
    let webVoiceInUse = "El micrófono está ocupado — lo tiene otra cosa de este dispositivo."
    let webVoiceInsecure = "Un micrófono necesita https, y esta página no lo tiene. El túnel lo da; una dirección normal en la red local, no."
    let webVoiceUnsupported = "Este navegador no puede grabar audio."
    let webVoiceBusy = "Una se está transcribiendo y otra está esperando. Inténtalo dentro de un momento."
    let webVoiceNoBinary = "Whisper no está instalado en el Mac, así que allí no hay nada con lo que transcribir."
    let webVoiceNoModel = "Whisper está en el Mac pero no tiene modelo con el que leer. Le basta un archivo ggml en `~/.cache/whisper`."
    let webVoiceFailed = "No se pudo transcribir eso."

    let webHintMove = "mover"
    let webHintOpen = "abrir"
    let webHintFilter = "filtrar"
    let webHintPane = "panel"

    let webKeysLabel = "Atajos de teclado"
    let webKeysTitle = "Teclado"
    let webKeysMove = "Moverte por la lista — `j` y `k` hacen lo mismo"
    let webKeysOpen = "Abrir la sesión seleccionada"
    let webKeysFilter = "Filtrar la lista"
    let webKeysEscape = "Borrar el filtro y luego volver atrás"
    let webKeysList = "Ir a la lista de sesiones"
    let webKeysPane = "Mostrar u ocultar la transcripción"
    let webKeysEnds = "Principio o final de la transcripción"
    let webKeysReverse = "Invertir el orden de la transcripción"
    let webKeysThis = "Esta tarjeta"
    let webKeysFoot = "Lo que escribas en una casilla de texto se queda en la casilla — los atajos se apartan mientras escribes."

    let webDoorLabel = "Vincular este navegador"
    let webDoorAskLede = "A este navegador todavía no se le ha dejado entrar."
    let webDoorAskFine = "Pide vincularte y aparecerá un código de seis dígitos *en el Mac* — a propósito no viene en la respuesta a esta página. Solo alguien que esté delante de esa máquina puede terminar esto, y en eso consiste la seguridad, no es una molestia."
    let webDoorName = "Ponle un nombre"
    let webDoorAsk = "Pedir vinculación"
    let webDoorToPassword = "Mejor entrar con contraseña"
    let webDoorCodeLede = "Mira el Mac."
    let webDoorCodeFine = "Clawdline muestra seis dígitos durante {left}. Escríbelos aquí."
    let webDoorTwoMinutes = "dos minutos"
    let webDoorDigit = "Dígito {n}"
    let webDoorConfirm = "Vincular este dispositivo"
    let webDoorRestart = "Empezar de nuevo"
    let webDoorPasswordLede = "Entra con la contraseña."
    let webDoorPasswordFine = "La que esté puesta en Clawdline en el Mac, en Ajustes → Acceso remoto. Si no hay ninguna, la forma de entrar es vincularse."
    let webDoorPassword = "Contraseña"
    let webDoorPasswordGo = "Entrar"
    let webDoorToPair = "Mejor usar un código de vinculación"
    let webDoorAsking = "Preguntando al Mac…"
    let webDoorAskFailed = "No se pudo preguntar al Mac."
    let webDoorRateLimited = "Cada petición saca un aviso en el Mac, así que solo hay tres cada diez minutos."
    let webDoorSixDigits = "Seis dígitos."
    let webDoorChecking = "Comprobando…"
    let webDoorFinished = "Esa vinculación se acabó — cinco códigos mal. Vuelve a pedirla cuando estés delante del Mac."
    let webDoorWrongCode = "Ese código no es correcto."
    let webDoorNeedPassword = "Primero, la contraseña."
    let webDoorWrongPassword = "Esa no es la contraseña."
    let webDoorExpired = "Ese código ha caducado. Vuelve a pedirlo y aparecerá uno nuevo en el Mac."
    let webDoorPaired = "Vinculado — este navegador ya está dentro"

    let webOffline = "No se pudo llegar a Clawdline. ¿Sigue abierto en el Mac?"
    let webNotJSON = "El servidor envió algo que no es JSON"
    let webRequestFailed = "La petición falló"

    let webNotifyGo = "Avísame"
    let webNotifyAsking = "Pidiendo…"
    let webNotifyStop = "Parar"
    let webNotifyStopping = "Parando…"
    let webNotifyOff = "cuando una sesión esté esperando una respuesta"
    let webNotifyOn = "Este dispositivo está suscrito. De qué se le avisa se decide en el Mac."
    let webNotifyBlocked = "Las notificaciones están bloqueadas para este sitio. Ese interruptor está en los ajustes del navegador, no aquí."
    let webNotifyUnsupported = "Este navegador no puede mostrar notificaciones."
    let webNotifyHomeScreen = "Añade clawdline a la pantalla de inicio y ábrelo desde ahí — iOS solo envía notificaciones a una app que viva ahí."
    let webNotifyOnFailed = "No se pudieron activar las notificaciones"
    let webNotifyOffFailed = "No se pudieron desactivar las notificaciones"

    let webSettings = "Ajustes"
    let webSettingsNotify = "Notificaciones"
    let webSettingsAssistantIcons = "Iconos del asistente"
    let webSettingsAssistantIconsSay = "Muestra la marca de Claude o Codex antes de su nombre en la conversación."
    let webSettingsAssistantIconsShow = "Mostrar iconos"
    let webSettingsVersion = "Versión {v}"
    let webClose = "Cerrar"
    let webNotifySheetOff = "A este dispositivo no se le avisa cuando una sesión está esperando."
    let webNotifyTest = "Enviar una prueba"
    let webNotifyTestSent = "Enviada — debería llegar a este dispositivo en un momento."
    let webNotifyTestNone = "El Mac no tiene ninguna suscripción para este dispositivo. Desactiva las notificaciones y vuelve a activarlas, y este navegador registrará una nueva."
    let webNotifyTestFailed = "No se pudo enviar la notificación de prueba"
    let webSending = "Enviando…"
    let webSendTip = "Intro envía · Mayús-Intro salta de línea"
    let webStart = "Nueva sesión"
    let webStartLabel = "Empezar una sesión nueva en un proyecto"
    let webStartPick = "¿Dónde la empezamos?"
    let webStartWith = "¿Con cuál la empezamos?"
    let webStartEmpty = "Todavía no hay dónde empezar. Ejecuta Claude Code una vez en el Mac y aparecerá aquí."
    let webStartFilter = "Filtrar proyectos"
    let webStarting = "Abriendo una pestaña…"
    let webStartWaiting = "Ya está en marcha. Esperando a que aparezca…"
    let webStartSlow = "La pestaña está abierta, pero la sesión no ha dado señales. Echa un vistazo al Mac."
    let webStartFailed = "No se pudo empezar esa sesión."
    let webStartGone = "Ese proyecto ya no está en el Mac."
    let webStartTerminalClosed = "{app} no está abierto en el Mac. Ábrelo allí y vuelve a intentarlo."
    let webStartTerminalUnsupported = "Los ajustes abren las sesiones nuevas en tmux, y este Mac no tiene tmux. Instálalo ahí, o elige otro terminal en los ajustes."
    let webStartDetached = "Se inició en un servidor tmux al que no hay nada conectado. Escribe {command} en el Mac para verlo."
    let webStartOff = "Empezar sesiones está desactivado. Se activa en Ajustes → Acceso remoto, en el Mac."
    let webResumeWith = "Retomar una anterior"
    let webResumePick = "¿Qué conversación?"
    let webResumeFilter = "Filtrar conversaciones"
    let webResumeEmpty = "En ese proyecto todavía no hay nada registrado."
    let webResumeLive = "abierta"
    let webResumeBack = "Otro proyecto"
    let webResumeGone = "Esa conversación ya no está en el Mac."
    let webResumeClaudeOnly = "Solo Claude Code guarda conversaciones que se puedan retomar."
    let webResuming = "Retomándola…"
    let webResumeCapped = "Las más antiguas no están en esta lista."
    let webCommand = "Di qué quieres empezar"
    let webCommandLabel = "Empezar una sesión diciendo qué debe hacer"
    let webCommandSay = "No se envía nada hasta que pulses Empezar más abajo."
    let webCommandHeard = "¿Qué debe hacer?"
    let webCommandThinking = "Pensando…"
    let webCommandDraft = "Borrador"
    let webCommandWhere = "Dónde"
    let webCommandWith = "Con"
    let webCommandModel = "Modelo"
    let webCommandFirst = "Primer mensaje"
    let webCommandGo = "Empezar"
    let webCommandUnsure = "No está claro qué proyecto — elige uno abajo."
    let webCommandFailed = "No se pudo convertir eso en un borrador."
    let webCommandNoPlanner = "Este Mac no tiene Claude Code para convertir eso en un borrador."
    let webCommandBusy = "Ya hay una frase convirtiéndose en borrador — inténtalo de nuevo en un momento."
    let webCommandEmpty = "No se oyó nada"
    let webScheduleNew = "Nueva tarea programada"
    let webScheduleEdit = "Editar tarea programada"
    let webScheduleNewSay = "No se programa nada hasta que pulses Crear más abajo."
    let webScheduleTitle = "Título"
    let webScheduleAt = "Hora"
    let webScheduleOn = "Días"
    let webScheduleWhere = "Dónde"
    let webScheduleWith = "Con"
    let webScheduleFirst = "Primer mensaje"
    let webScheduleMore = "Más"
    let webScheduleModel = "Modelo"
    let webScheduleWhenDone = "Cerrar la pestaña al terminar"
    let webScheduleCloseSuccess = "Si tiene éxito"
    let webScheduleCloseAlways = "Siempre"
    let webScheduleCloseNever = "Dejarla abierta"
    let webScheduleEnabled = "Activado"
    let webScheduleDisabled = "Desactivado"
    let webScheduleNotify = "Avísame si falla"
    let webScheduleCatchUp = "Si se pasó la hora, recuperarla en (horas)"
    let webScheduleTimeout = "Rendirse si no termina en (minutos)"
    let webScheduleCreate = "Crear"
    let webScheduleCreated = "Tarea programada creada."
    let webScheduleDispatchOff = "La tarea programada está creada y es válida, pero el envío está apagado — nadie la ejecutará. Se activa en Ajustes → Acceso remoto, en el Mac."
    let webScheduleFailed = "No se pudo crear la tarea programada."
    let webScheduleSave = "Guardar"
    let webScheduleSaved = "Tarea programada guardada."
    let webScheduleDelete = "Eliminar"
    let webScheduleDeleteAsk = "¿Eliminar {title}? No se puede deshacer."
    let webScheduleDeleted = "Tarea programada eliminada."
    let webScheduleNeedsTime = "No se oyó una hora — indica una."
    let webScheduleNeedsPlace = "No está claro qué proyecto — elige uno."
    let webScheduleDaily = "Diario"
    let webScheduleSun = "Dom"
    let webScheduleMon = "Lun"
    let webScheduleTue = "Mar"
    let webScheduleWed = "Mié"
    let webScheduleThu = "Jue"
    let webScheduleFri = "Vie"
    let webScheduleSat = "Sáb"
    let webLinks = "Enlaces"
    let webLinksTip = "Dónde se puede abrir este proyecto"
    let webLinksPick = "Todo aquello de lo que este proyecto tiene una dirección."
    let webLinksEmpty = "Este proyecto no tiene nada con dirección — ni sitio, ni deploy, ni ningún servidor en marcha."
    let webLinksFailed = "No se pudieron leer los enlaces de este proyecto."
    let webLinksLocal = "Solo en la red del propio Mac. Desde aquí no se abre."
    let webLinksFile = "Un archivo del Mac. Se abre allí, no en este navegador."
    let webLinksCopy = "Copiar la ruta"
    let webLinksCopied = "Copiado."
    let webLinksCopyFailed = "Este navegador no dejó que la página copiara eso."
    let webLinkOk = "ok"
    let webLinkFail = "error"
    let webLinkDown = "apagado"
    let webLinkRunning = "en curso"
    let webSessionInfo = "Info de la sesión"
    let webInfoTitle = "Sobre esta sesión"
    let webInfoEditTitle = "Editar título de la sesión"
    let webInfoCopyTitle = "Copiar este nombre"
    let webInfoTitleSaved = "Título guardado."
    let webInfoTitleLocal = "Título guardado en Clawdline; el nombre posterior no cambió."
    let webInfoTitleQueued = "Título guardado en Clawdline; actualización de Codex en cola."
    let webInfoTitleNotDurable = "El título está aplicado, pero este Mac no pudo guardarlo en disco; desaparecerá al reiniciar."
    let webInfoTitleCloud = "Los títulos de sesión solo se cambian en el propio Mac, no por la conexión en la nube."
    let webInfoSession = "Esta sesión"
    let webInfoAssistant = "Asistente"
    let webInfoModel = "Modelo"
    let webInfoSessionId = "ID de sesión"
    let webInfoDirectory = "Directorio"
    let webInfoRunningFor = "En marcha desde hace"
    let webInfoStatus = "Estado"
    let webInfoWorkStatusMeaning = "Este es el estado del trabajo de la sesión. Una marca significa entregado y pendiente de aprobación; dos significan revisado y aprobado."
    let webInfoCloseabilityMeaning = "La llave indica si la sesión se puede cerrar de forma segura. Es independiente del estado de entrega."
    let webInfoUsage = "Uso de tokens"
    let webInfoInput = "Entrada"
    let webInfoOutput = "Salida"
    let webInfoCacheRead = "Caché leída"
    let webInfoCacheWrite = "Caché escrita"
    let webInfoTotal = "Total"
    let webInfoCost = "Coste estimado"
    let webInfoNoUsage = "Todavía no se encontró la transcripción de esta sesión."
    let webInfoLimits = "Límites del plan"
    let webInfoLimitHit = "límite alcanzado"
    let webInfoResets = "se reinicia {when}"
    let webInfoUnknown = "desconocido"
    let webInfoFiles = "Archivos"
    let webInfoBranch = "Rama"
    let webInfoStaged = "Preparados"
    let webInfoUnstaged = "Modificados"
    let webInfoUntracked = "Sin seguimiento"
    let webInfoConflict = "Conflictos"
    let webInfoClean = "Nada sin commit."
    let webInfoNotRepo = "No es un repositorio git."
    let webInfoDeploy = "Último deploy"
    let webInfoNoDeploy = "Este proyecto no tiene ningún deploy registrado."
    let webInfoFailed = "No se pudo leer la información de esta sesión."
    let webInfoBusy = "El Mac está ocupado leyendo otras sesiones. Inténtalo dentro de un momento."
    let webInfoRefresh = "Actualizar"
    let webInfoTokens = "tokens"
    let webInfoSwitchModel = "Cambiar de modelo"
    let webInfoModelOther = "otro modelo…"
    let webInfoModelSent = "/model {model} enviado. Confirmando…"
    let webInfoModelBusy = "El cambio espera a que la sesión esté inactiva."
    let webInfoSwitchPermission = "Cambiar modo de permisos"
    let webInfoPermissionAuto = "Automático"
    let webInfoPermissionManual = "Manual"
    let webInfoPermissionAcceptEdits = "Aceptar cambios"
    let webInfoPermissionPlan = "Planificación"
    let webInfoPermissionUnreadable = "No se pudo leer el modo actual."
    let webInfoPermissionSent = "Se cambió a {mode}. Confirmando…"
    let webInfoPermissionBusy = "Se está cambiando el modo de permisos."
    let webInfoLimitsClaude = "Claude Code solo anota una ventana cuando se agota; hasta entonces no se sabe nada."
    let webInfoCopied = "Id de sesión copiado."
    let webInfoAsOf = "a las {when}"
    let webInfoWhyUnknown = "Por qué es desconocido, y cómo obtener las cifras"
    let webSettingsOrder = "Transcripción"
    let webSettingsOrderSay = "Por qué extremo empezar a leer una transcripción. Vale para todas las sesiones, y desde el teclado `r` hace lo mismo."
    let webAskLabel = "preguntó"
    let webAskAny = "Las que quieras de estas"
    let webWaitingTitle = "Esta sesión está esperando una respuesta"
    let webWaitingSay = "Claude Code está mostrando un menú en el Mac. Clawdline todavía no sabe leer un menú desde aquí, así que las opciones solo están en esa pantalla."
    let webWaitingSend = "*Enviar desde aquí no escribe tu respuesta en el menú* — confirma la opción que el menú tenga resaltada, que casi nunca es la que querías. Esta contéstala en el Mac."
    let webMenuSay = "Toca una respuesta y va directa a la sesión."
    let webMenuHighlighted = "resaltada"
    let webMenuSent = "Respuesta enviada."
    let webAgents = "Agentes en segundo plano"
    let webAgentsCount = "{n} en marcha"
    let webAgentDone = "hecho"
    let webAgentFailed = "falló"
    let webShells = "Shells en segundo plano"
    let webShellTitle = "Shell en segundo plano"
    let webShellOpen = "Ver lo que imprime este comando"
    let webShellRunning = "en marcha"
    let webShellEnded = "terminado"
    let webShellQuiet = "Todavía no ha impreso nada."
    let webShellFailed = "No se pudo leer la salida de este comando."
    let webShellClose = "Cerrar"
    let webShellStop = "Detener"
    let webShellStopTitle = "¿Detener este comando?"
    let webShellStopSay = "{command} sigue en marcha. Se le pide que pare y, cinco segundos después, se mata si no lo ha hecho. Lo que ya hizo no se deshace."
    let webShellStopped = "Se le pidió que parara."
    let webShellStopFailed = "No se pudo detener."
    let agentRunning = "en marcha"
    let agentTools = "{n} herramientas"
    let agentEmpty = "Este agente aún no ha escrito nada."
    let agentBack = "Sesión"
    let webAgentOpen = "Ver qué hizo este agente"
    let webTaskRoot = "Padre"
    let webTaskChild = "Hijo"
    let webTaskTasks = "Tareas"
    let webTaskDone = "hecho"
    let webTaskFailed = "falló"
    let webTaskRunning = "en marcha"
    let webStale = "Clawdline se ha vuelto a compilar en el Mac. Esta página es la de antes."
    let webStaleGo = "Recargar"

    let menuApplication = "Clawdline"
    let menuWindow = "Ventana"
    let menuHelp = "Ayuda"
    let menuClose = "Cerrar ventana"
    let menuHome = "Inicio / Centro de configuración"
    let menuHelpDocumentation = "Documentación de Clawdline"
    func menuAbout(_ app: String) -> String { "Acerca de \(app)" }
    let menuServices = "Servicios"
    func menuHide(_ app: String) -> String { "Ocultar \(app)" }
    let menuHideOthers = "Ocultar los demás"
    let menuShowAll = "Mostrar todo"
    let menuMinimize = "Minimizar"
    let homeTitle = "Inicio de Clawdline"
    let homeWelcome = "Elige qué quieres conectar. La configuración muestra las pruebas reales, no solo el interruptor cambiado."
    let homePurpose = "¿Qué quieres conectar?"
    let homeLocalTitle = "Navegador local"
    let homeLocalSummary = "Lee Clawdline en un navegador de este Mac. El control sigue desactivado salvo que lo actives expresamente en Ajustes."
    let homeCloudPreviewTitle = "Vista previa de Clawdline Cloud"
    let homeCloudPreviewSummary = "Usa la vista alojada de Clawdline cuando pueda comprobarse la conexión activa."
    let homeCloudflareTitle = "Mi URL de Cloudflare"
    let homeCloudflareSummary = "Usa tu nombre de host de Cloudflare cuando pueda comprobarse la ruta HTTPS pública."
    let homeUnavailable = "Aún no está listo en esta versión; no se afirma que la conexión haya funcionado."
    let setupDetected = "Estado detectado"
    let setupNextAction = "Siguiente paso"
    let setupExpected = "Resultado esperado"
    let setupRecovery = "Recuperación"
    let setupLocalServerOff = "El servidor de bucle local está desactivado."
    let setupLocalChecking = "Comprobando el endpoint /v1/health real…"
    let setupLocalConfigurationFailed = "No se pudo guardar el ajuste del navegador local; no cambió nada."
    let setupLocalHealthTransport = "No se pudo alcanzar el endpoint de salud. Revisa el puerto y otros programas."
    let setupLocalHealthTimedOut = "El endpoint de salud agotó el tiempo. Revisa el puerto y reintenta."
    func setupLocalHealthHTTP(_ status: Int) -> String { "El endpoint de salud devolvió HTTP \(status), no una respuesta sana." }
    let setupLocalHealthUnhealthy = "El endpoint respondió, pero indicó ok: false."
    let setupLocalHealthInvalid = "El endpoint no devolvió una respuesta de salud válida. Revisa quién usa el puerto."
    let setupLocalReady = "El endpoint de estado está listo. Aún no hay credenciales del navegador."
    let setupLocalWaiting = "El navegador se abrió; esperando que este dispositivo exacto se autentique."
    let setupLocalConnected = "Conectado. Este dispositivo del navegador contactó con Clawdline."
    let setupLocalEnable = "Activar navegador local"
    let setupLocalRetry = "Comprobar de nuevo"
    let setupLocalOpen = "Abrir navegador de solo lectura"
    let setupLocalOpenAgain = "Abrir navegador de nuevo"
    let setupFinish = "Listo"
    let setupLocalExpected = "Se abre y autentica un navegador de solo lectura; también funciona sin sesiones activas."
    let setupLocalRecovery = "Si se detiene, mantén esta ventana abierta y vuelve a comprobar. Puedes revisar servidor y puerto en Ajustes."
    let setupNoRecovery = "No hace falta recuperación; esta ruta está probada."
    let setupLocalReadOnlyAction = "Esta acción guarda el acceso de solo lectura y mantiene el control desactivado."
    let setupReadOnly = "Solo lectura · el control sigue desactivado"
    let setupLocalDeviceName = "Navegador del Centro de configuración"
    func setupTunnelFacts(_ mode: String, _ tunnel: String, _ hostname: String, _ status: String) -> String { "Modo: \(mode)\nTúnel: \(tunnel)\nHost del QR: \(hostname)\nEstado: \(status)" }
    let setupTunnelModeOff = "Desactivado"
    let setupTunnelModeQuick = "Rápido"
    let setupTunnelModeNamed = "Con nombre"
    let setupTunnelQuickName = "Túnel rápido de Cloudflare"
    let setupNone = "Ninguno"
    let setupControlChosen = "Lectura + control · activado explícitamente en Ajustes"
    let setupTunnelMissing = "cloudflared no está instalado."
    let setupTunnelOff = "El túnel está desactivado; no hay QR para el teléfono."
    let setupTunnelStarting = "cloudflared está arrancando; aún no hay QR para el teléfono."
    func setupTunnelReady(_ url: String) -> String { "Activo en \(url). Aún no existe credencial del teléfono." }
    func setupTunnelWaiting(_ url: String) -> String { "El QR apunta a \(url). Esperando a este teléfono exacto." }
    func setupTunnelConnected(_ url: String) -> String { "Conectado mediante \(url). Este teléfono exacto informó lastSeen." }
    let setupTunnelExpected = "Solo una URL de túnel activa entra en el QR; solo lastSeen del dispositivo no local creado por este QR completa la configuración."
    let setupTunnelRecovery = "Abre Ajustes remotos. Instala cloudflared si falta; si no, sigue el motivo detectado, mantén el túnel activo y vuelve a escanear."
    let setupOpenRemoteSettings = "Abrir ajustes remotos"
    let setupCheckTunnel = "Comprobar túnel otra vez"
    let setupShowPhoneQR = "Mostrar QR del teléfono"
    let setupShowPhoneQRAgain = "Volver a mostrar QR"
    let setupCloudRelayUnauthorized = "El relay rechazó la credencial de esta máquina."
    func setupCloudFacts(_ account: String, _ credential: String, _ relay: String, _ pairing: String, _ receipt: String) -> String { "Cuenta: \(account)\nCredencial de máquina: \(credential)\nRelay listo: \(relay)\nEmparejamiento E2EE: \(pairing)\nRecepción del viewer: \(receipt)" }
    let setupCloudExpected = "Preview solo termina cuando cuenta, credencial, relay, emparejamiento E2EE y recepción de este viewer se prueban por separado."
    let setupCloudRecovery = "Usa Ajustes de Cloud para iniciar sesión o emparejar. El relay y la recepción siguen siendo pruebas de Preview; reintentar no crea evidencia."
    let setupOpenCloudSettings = "Abrir ajustes de Cloud"
    let setupPairCloudPhone = "Emparejar teléfono en Cloud"
    let setupReviewCloudPreview = "Revisar estado de Preview"
    let setupProofAbsent = "ausente"
    let setupProofReading = "leyendo la prueba…"
    let setupProofUnavailable = "prueba no disponible"
    func setupProofFailed(_ reason: String) -> String { "falló — \(reason)" }
    let setupCloudIdentityReadFailed = "no se pudo leer la identidad del Llavero"
    let setupCloudRelayFailed = "el relay informó de un fallo; revisa Ajustes de Cloud y el registro"
    let setupCloudPairingReadFailed = "no se pudo leer el almacén de dispositivos enlazados"
    let setupCloudPairingAmbiguous = "apareció más de un viewer nuevo; reinicia el enlace"
    func setupCloudAccountProved(_ account: String) -> String { "sesión iniciada como \(account)" }
    func setupCloudCredentialProved(_ machine: String) -> String { "credencial del Llavero para \(machine)" }
    func setupCloudPairingProved(_ device: String) -> String { "fijado para el viewer exacto \(device)" }
    let setupCloudflareDeviceName = "Teléfono por Cloudflare"
    let setupScanLiveTunnel = "Escanea el túnel activo con el teléfono"
    let setupDismissalHint = "Cerrar Inicio detiene la apertura automática. Reabre el Centro de configuración desde el menú, Dock, estado o clawdline://home."
    let setupCompletionFailed = "Clawdline no pudo guardar la finalización. Revisa los permisos de ~/.config/clawdline y vuelve a cerrar Inicio."

    let menuOpen = "Abrir la barra"
    let menuReveal = "Ir a la pestaña destino"
    let menuMascot = "Mascota"
    let menuLogin = "Abrir al iniciar sesión"
    let menuEditConfig = "Ajustes…"
    let menuReload = "Recargar configuración"
    let menuQuit = "Salir de Clawdline"
    let menuNoTarget = "(aún sin detectar)"

    func hotkeyFailedTitle(_ combo: String) -> String { "No se pudo registrar \(combo)" }
    func hotkeyFailedBody(_ configPath: String) -> String {
        """
        Lo más probable es que otra app ya la use — Spotlight, un cambiador de teclado, \
        BetterTouchTool y demás.

        Elige otra: edita "hotkey" en \(configPath) y luego elige \
        "Recargar configuración" en la barra de menús.

        Mientras tanto, el ✳ de la barra de menús sigue abriendo la barra.
        """
    }
    let loginFailed = "No se pudo configurar el arranque al iniciar sesión"
}
