import Foundation

struct Korean: Copy {
    let placeholder = "Claude Code에 메시지…"

    let hintSend = "보내기"
    let hintNewline = "줄바꿈"
    let hintSwitch = "전환"
    let hintList = "목록"
    let hintMascot = "마스코트"
    let hintOutput = "출력"
    let hintFullscreen = "전체 화면"
    let hintKeys = "단축키"
    let hintTextSize = "글자 크기"
    let hintOrder = "역순"
    let hintVoice = "받아쓰기"
    func voiceListening(onDevice: Bool) -> String {
        onDevice ? "이 Mac에서 듣는 중 — 다시 누르면 중지"
                 : "듣는 중 — 이 언어는 이 Mac이 아니라 Apple이 인식합니다"
    }
    let voiceNoPermission = "받아쓰기에는 마이크와 음성 인식 권한이 필요합니다"
    let voiceUnavailable = "지금은 받아쓰기를 사용할 수 없습니다"
    func voiceTranscribing(seconds: Double) -> String {
        String(format: "Whisper가 다시 듣는 중… %.1f초", seconds)
    }
    let whisperMissing = "Whisper가 설치되어 있지 않습니다 — docs/whisper.md 참고"
    let whisperNothingHeard = "아무것도 들리지 않았습니다"
    func dictationStatus(_ status: Whisper.Status) -> String {
        switch status {
        case .ready(let model): return "받아쓰기: Apple 다음 Whisper (\(model))"
        case .noBinary: return "받아쓰기: Apple만 — whisper-cli 없음"
        case .noModel: return "받아쓰기: Apple만 — whisper-cli는 있고 모델이 없음"
        }
    }
    func voiceListeningWhisper() -> String { "듣는 중 — 멈추면 Whisper가 한 번 더 봅니다" }

    let scanning = "찾는 중…"
    let noSession = "Claude Code 세션을 찾지 못했습니다"
    let nothingToSend = "보낼 곳이 없습니다 — 먼저 터미널에서 Claude Code를 실행하세요"
    let sendFailed = "보내지 못했습니다"
    let itermSilent = "iTerm2가 응답하지 않았습니다"
    let itermBusy = "iTerm2가 대화상자 응답을 기다리고 있습니다 — Mac에서 처리해 주세요"
    let scriptMissing = "iterm.js가 없습니다 — 앱 번들이 손상되었을 수 있습니다"
    let cannotList = "iTerm2 세션을 읽지 못했습니다"
    let noOutput = "이 세션에서 아직 읽을 것이 없습니다."
    let imageExpired = "이미지가 만료되었습니다"
    let imagePreview = "이미지 미리보기"
    let imageClose = "미리보기 닫기"
    func outputSize(_ pt: Int) -> String { "출력 글자 크기 \(pt)pt — ⌘J로 보기" }
    func foldedTools(_ count: Int) -> String { "\(count)단계" }
    func outputOrder(newestFirst: Bool) -> String {
        newestFirst ? "최신순" : "오래된순"
    }
    func backlogNow(_ count: Int) -> String { "현재 \(count)" }
    func dropped(_ count: Int) -> String {
        count == 1 ? "경로를 넣었습니다 — Claude Code가 읽습니다" : "경로 \(count)개를 넣었습니다"
    }
    func stackConfirm(_ command: String) -> String { "다시 누르면 실행합니다: \(command)" }
    let hintStacks = "서버"
    func stackTip(up: Int, total: Int) -> String { "서버 \(total)개 중 \(up)개 실행 중 — ⌘S로 목록 보기" }
    let stackTipUnknown = "이 프로젝트에는 서버가 있지만 status 명령이 아직 신뢰되지 않았습니다 — ⌘S"
    let stackUntrusted = "미승인"
    let stackExit = "종료 코드"
    let stackActionStart = "시작"
    let stackActionRestart = "재시작"
    let stackActionStop = "중지"
    let stackActionLogs = "로그"
    let stackLogAll = "전체"
    let stackLogBack = "대화 기록"
    let stackActionAllow = "허용"
    let stackActionAgain = "다시 누르기"
    func sessionTip(index: Int, total: Int) -> String { "\(total)개 중 \(index)번째 세션 — ⌘K로 전환" }
    let sessionWaiting = "답변 대기 중"
    let sessionAgents = "백그라운드에 {n}개"
    let sessionShellOne = "셸 1개 실행 중"
    let sessionShellMany = "셸 {n}개 실행 중"
    let sessionWaitedOnByOne = "1개가 당신을 기다림"
    let sessionWaitedOnByMany = "{n}개가 당신을 기다림"
    let islandDone = "완료"
    let islandAllSessions = "모든 세션…"
    func statusWaiting(_ labels: [String]) -> String {
        labels.count == 1 ? "\(labels[0]) 세션이 답변을 기다립니다"
                          : "\(labels.count)개 세션이 답변을 기다립니다"
    }
    func statusWorking(_ count: Int) -> String { "\(count)개 실행 중" }

    let settingsTitle = "Clawdline 설정"
    let settingsGeneral = "일반"
    let settingsBar = "막대"
    let settingsReading = "읽기"
    let settingsVoice = "받아쓰기"
    let settingsHotkey = "단축키"
    let settingsRecording = "키를 누르세요…"
    let settingsScope = "작동하는 곳"
    let settingsScopeGlobal = "모든 앱에서"
    let settingsScopeHint = "비워 두면 어디서나 동작합니다. 그래서 마지막 하나를 빼면 위의 스위치가 켜지고, 그 스위치를 다시 끄면 목록이 돌아옵니다. 설정 파일에는 번들 ID로 남고, 손으로 고친 목록도 그대로 동작합니다."
    let settingsScopeAdd = "앱 추가…"
    let settingsScopeChoose = "앱 고르기…"
    let settingsScopeRunning = "지금 열려 있는 앱"
    let settingsScopeRemove = "빼기"
    let settingsLanguage = "언어"
    let settingsReopen = "막대가 터미널을 따라 나왔다 들어가기"
    let settingsReopenHint = "터미널에서 다른 곳으로 넘어가면 막대는 들어가고, 터미널로 돌아오면 막대도 돌아옵니다. 다 썼다는 뜻이 되는 것은 Esc입니다."
    let settingsFollow = "막대가 겨냥한 것을 터미널에도 띄우기"
    let settingsFollowHint = "그 세션의 탭을 선택합니다. 터미널을 맨 앞으로 가져오지는 않습니다. 그랬다가는 Tab을 누를 때마다 지금 입력하던 칸에서 키보드가 빠져나가기 때문입니다."
    let settingsCodexAutoName = "새 세션 자동 이름 지정"
    let settingsCodexAutoNameHint = "이름 없는 세션마다 선택한 어시스턴트로 작은 turn을 한 번 실행합니다. 첫 요청과 해당 어시스턴트의 사용량을 쓰며, 직접 정한 이름은 바꾸지 않습니다."
    let settingsNotch = "노치에 살기"
    let settingsNotchHint = "카메라 하우징에 사는 캐릭터. 끄면 끝 — 아무것도 그리지 않고 창도 만들지 않습니다."
    let settingsPosition = "화면에서의 높이"
    let settingsWidth = "너비"
    let settingsOpacity = "카드 불투명도"
    let settingsShow = "표시"
    let settingsPaneHeight = "패널 높이"
    let settingsTextSize = "글자 크기"
    let settingsPaneFont = "패널 글꼴"
    let settingsBlur = "뒤쪽 흐림"
    let settingsNewestFirst = "최신 항목 먼저"
    let settingsEngine = "인식기"
    let settingsSettle = "이만큼 쉬면 문장이 끝남"
    let settingsStop = "이만큼 조용하면 세션 종료"
    let settingsAuto = "자동"
    let settingsTranscript = "트랜스크립트"
    let settingsTerminal = "터미널"
    let settingsOff = "끔"
    let settingsHooks = "Claude Code 훅"
    let settingsHooksHint = "설치해 두면 한 차례가 시작되거나 끝나거나 답을 기다리는 순간을 Claude Code가 곧바로 알려 줍니다. Clawdline이 다음에 확인할 때까지 기다리지 않습니다. 상태를 읽는 곳은 여전히 화면이고, 여기서 정해지는 것은 얼마나 빨리인지뿐입니다."
    let settingsHooksInstall = "설치"
    let settingsHooksRemove = "제거"
    let settingsHooksOff = "설치 안 됨 — 상태는 모두 화면에서 읽습니다"
    let settingsHooksOn = "설치됨 — 아직 알려 온 세션이 없습니다"
    let settingsHooksLive = "설치됨. 세션이 알려 오고 있습니다"
    let settingsStateHook = "세션 상태가 바뀔 때"
    let settingsStateHookHint = "세션이 일을 시작하거나, 끝내거나, 무언가를 물어볼 때마다 Clawdline이 이것을 실행합니다. 당신의 프로그램을, 자세한 내용은 환경 변수에 담아서. 여기가 아니라 설정 파일에 적는 이유는 이것이 명령줄이 아니라 argv 목록이기 때문입니다. 공백이 든 경로는 끝까지 하나의 경로로 남아야 합니다."
    let settingsRemote = "원격"
    let settingsRemoteServe = "브라우저나 휴대폰에서 세션을 볼 수 있게 하기"
    let settingsRemoteHint = "꺼져 있으면 이 Mac 바깥에서는 아무것도 닿지 않습니다. 켜면 세션 목록이 127.0.0.1에 올라갑니다. 여기 브라우저에도, 터널 너머의 휴대폰에도, 스크립트에도. 그렇게 넘어가는 것이 저장소 이름과 브랜치, 작업 제목이라서 당신이 말하기 전까지는 꺼진 채로 있습니다."
    let settingsRemoteDevices = "페어링된 기기"
    let settingsRemoteNoDevices = "아직 없음 — 이 Mac 밖에서는 아무것도 읽을 수 없습니다"
    let settingsRemoteRevokeAll = "모두 연결 해제"
    let settingsRemoteOpen = "브라우저에서 열기"
    let pairingIgnore = "무시"
    func pairingAsks(_ device: String) -> String { "\(device)에서 이 Mac과 페어링을 요청합니다" }
    func pairingCode(_ code: String) -> String {
        """
        그 기기에 이 코드를 입력하세요:

        \(code)

        2분 동안만 유효합니다. 방금 요청한 적이 없다면 무시해도 됩니다. 이 코드 없이는 \
        요청한 쪽이 끝낼 수 없습니다.
        """
    }
    let settingsTunnel = "어디서든 이 Mac에 닿기"
    let settingsTunnelQuick = "자동 생성된 주소"
    let settingsTunnelNamed = "내 도메인"
    let settingsTunnelHostname = "호스트 이름"
    let settingsTunnelHint = "cloudflared를 통해 이 Mac에서 바깥으로 연결을 겁니다. 포트 포워딩도 없고, 네트워크에서 듣고 있는 것도 없습니다. 기기가 하나 페어링될 때까지는 시작하지 않습니다. 터널 너머에 있는 것이 이 Mac의 모든 저장소 이름과 모든 작업 제목이기 때문입니다."
    let settingsRemoteWrite = "페어링된 기기가 세션에 쓸 수 있게 하기"
    let settingsRemoteWriteHint = "꺼져 있으면 페어링된 기기는 읽기만 할 수 있습니다. 켜면 세션에 텍스트를 보내고 새 세션을 시작할 수도 있습니다. 그것은 이 Mac에서 코드를 실행한다는 뜻입니다. Claude Code가 하는 일이 바로 그것이기 때문입니다. 위쪽과는 다른 결정이라 스위치도 따로 두었습니다."
    let settingsRemotePhone = "휴대폰 페어링…"
    let settingsRemotePhoneHint = "스캔할 코드를 보여줍니다. 그 코드는 자기 키를 따로 갖고 있어서, 사진으로 찍히더라도 남는 것은 이 목록에 보이고 언제든 지울 수 있는 기기 하나뿐입니다. 이 Mac 자신의 키가 아닙니다."
    let pairingScanTitle = "휴대폰으로 이것을 스캔하세요"
    let pushWaiting = "이 답을 기다리는 중"
    let pushTest = "테스트 알림입니다. 필요한 것은 다 연결되어 있습니다."
    let pushFinished = "의 긴 작업이 끝났습니다"
    let pushDeployOk = "의 배포가 성공했습니다"
    let pushDeployFail = "의 배포가 실패했습니다"
    func pushChildWaiting(minutes: Int?) -> String {
        guard let minutes else { return "의 하위 세션이 답을 기다리는 중" }
        return "의 하위 세션이 답을 기다리는 중 — \(minutes)분 남음"
    }
    func pushBatchDone(done: Int, failed: Int) -> String {
        let all = "의 작업 \(done)개가 끝났습니다"
        return failed == 0 ? all : "\(all), \(failed)개 실패"
    }
    let settingsPushFinish = "긴 작업이 끝나면 알리기"
    let settingsPushFinishHint = "2분이 넘는 작업만입니다."
    let settingsSmartNotifications = "스마트 알림"
    let settingsSmartNotificationsHint = "Haiku가 완료한 내용을 한 문장으로 알려 줍니다. 실패하면 일반 알림을 보냅니다."
    func pushCoalesced(count: Int) -> String { "\(count)건의 작업이 한꺼번에 완료" }
    let settingsSmartHealthIdle = "아직 스마트 알림을 시도한 적이 없습니다."
    func settingsSmartHealth(attempts: Int, successes: Int) -> String {
        "\(attempts)회 시도 중 \(successes)회가 모델 문장을 전달했습니다."
    }
    func settingsSmartHealthFailure(reason: String, time: String) -> String {
        "마지막으로 일반 알림으로 대체된 시각 \(time): \(reason)."
    }
    func settingsSmartTimeout(seconds: Int) -> String {
        "Claude가 \(seconds)초 제한을 넘겨 중단되었습니다"
    }
    let settingsSmartQueueFull = "동시에 끝난 작업이 대기열 용량을 넘었습니다"
    let settingsSmartModelFailed = "Claude가 쓸 만한 출력을 내지 못했습니다"
    let settingsSmartNoSource = "요약할 내용이 없었습니다"
    let settingsSmartMissing = "claude 실행 파일을 찾을 수 없습니다"
    let settingsPushDeploy = "배포가 끝나면 알리기"
    let settingsPushDeployHint = "성공도 실패도 알립니다."
    let settingsAgentNotify = "에이전트가 직접 알림을 보내도록 허용"
    let settingsAgentNotifyNote = "에이전트가 먼저 보내는 내용만 제어합니다. 작업 완료, 배포 및 다른 알림에는 영향을 주지 않습니다."
    let settingsOrchestrator = "다른 세션에 일 맡기기"
    let settingsOrchestratorEnabled = "세션이 다른 세션에 일을 넘길 수 있게"
    let settingsOrchestratorEnabledHint = "clawdline 스킬을 가진 세션이 새 탭을 열고 지시를 입력한 뒤, 끝나면 알림을 받습니다. 꺼두면 모든 요청을 거절합니다. 이미 돌고 있는 것은 멈추지 않습니다."
    let settingsOrchestratorMax = "동시에 돌릴 자식 세션"
    let settingsOrchestratorMaxHint = "기본값은 다섯 개. Mac 전체가 아니라 세션마다 세는 숫자입니다. 하나하나가 어시스턴트가 들어 있는 터미널 탭입니다."
    let settingsOrchestratorPermission = "자식 세션이 어디까지 스스로 갈지"
    let settingsOrchestratorPermissionHint = "자식 세션의 탭은 아무도 보고 있지 않아서, 승인을 기다리며 멈춘 세션은 시간이 다 될 때까지 멈춰 있습니다. 그리고 맡겨진 세션의 일이란 곧 명령을 실행하고 파일을 쓰는 것이므로, 마지막 칸이 아니면 어딘가에서 멈춥니다. 작업은 이보다 조심스럽게 요청할 수 있지만, 더 나아갈 수는 없습니다."
    let settingsOrchestratorPermissionAsk = "한 걸음마다 묻기"
    let settingsOrchestratorPermissionEdits = "파일 쓰기는 묻지 않기"
    let settingsOrchestratorPermissionFull = "묻지 않기"
    let settingsOrchestratorNotify = "요청한 세션에 알리기"
    let settingsOrchestratorNotifyHint = "일이 끝나면 그 세션에 한 줄을 입력합니다."
    let settingsOrchestratorClose = "자식 세션이 보고하면"
    let settingsOrchestratorCloseHint = "보고한 뒤에 그 탭을 닫습니다. 시간이 다 된 것은 읽어 볼 수 있게 남겨 둡니다."
    let settingsOrchestratorCloseNow = "탭을 바로 닫기"
    let settingsOrchestratorCloseLinger = "3분 뒤에 닫기"
    let settingsOrchestratorCloseKeep = "닫지 않고 두기"
    let settingsOrchestratorPolicy = "일을 나누는 규칙"
    let settingsOrchestratorPolicyHint = "맡길 때마다 Clawdline이 읽고, 다시 맡길 수 있는 모든 자식 세션의 지시문에 그대로 옮겨 적는 규칙입니다. 어느 어시스턴트를, 어느 모델을, 그래프를 어떤 모양으로. 비워 두면 규칙 없음입니다."
    let settingsOrchestratorPolicyEdit = "규칙 편집"
    func settingsOrchestratorPolicyOn(_ lines: Int) -> String { return "적용 중 — \(lines)줄" }
    let settingsOrchestratorPolicyOff = "규칙 없음 — 맡길 때마다 맡기는 쪽이 정합니다"
    let settingsSchedules = "예약 작업"
    let settingsSchedulesEmpty = "아직 일정이 없습니다. 아래 새 일정으로 첫 일정을 만드세요."
    let settingsScheduleNew = "새 예약"
    let settingsScheduleEdit = "편집"
    let settingsScheduleSave = "저장"
    let settingsScheduleDelete = "삭제"
    let settingsScheduleRun = "지금 실행"
    let settingsScheduleReveal = "Finder에서 보기"
    let settingsSchedulesFolder = "schedules 폴더 열기"
    let settingsScheduleNext = "다음"
    let settingsScheduleLast = "최근"
    let settingsScheduleNever = "실행 기록 없음"
    let settingsScheduleStarted = "실행을 시작했습니다."
    let settingsScheduleActive = "이전 예약 작업이 아직 실행 중입니다."
    let webScheduleMissed = "최근 놓친 실행"
    let webScheduleNoNext = "다음 실행이 예약되지 않았습니다."
    func childAnnounce(_ title: String) -> String { "Clawdline이 맡긴 일을 받았습니다: \(title) — 지금 시작합니다." }
    func settingsSeconds(_ value: Double) -> String { String(format: "%.1f초", value) }

    let webConnLive = "실시간"
    let webConnConnecting = "연결 중"
    let webConnRetrying = "{n}초 후 재시도"
    let webConnOffline = "오프라인"
    let webConnLocked = "페어링 안 됨"
    let webConnTipLive = "앱에서 실시간으로 받는 중"
    let webConnTipLocked = "이 브라우저는 아직 Mac과 페어링되지 않았습니다"
    let webConnTipDown = "연결되지 않음 — 눌러서 지금 시도"

    let webCountWorking = "{n}개 실행 중"
    let webCountWaiting = "{n}개 대기 중"
    let webCountUnreadable = "{n}개 읽을 수 없음"
    let webCountQuietOne = "세션 {n}개, 모두 조용함"
    let webCountQuietMany = "세션 {n}개, 모두 조용함"
    let webCountNone = "세션 없음"

    let webFilterPlaceholder = "작업, 프로젝트, tty로 거르기"
    let webFilterLabel = "세션 거르기"
    let webListLabel = "Claude Code 세션"
    let webPull = "당겨서 새로고침"
    let webPullRelease = "놓으면 새로고침"
    let webPullBusy = "새로고침 중…"
    let webEmptyFilterTitle = "“{q}”에 맞는 것이 없습니다"
    let webEmptyFilterHint = "Esc를 누르면 지워집니다"
    let webEmptyLockedTitle = "이 기기는 페어링되지 않았습니다"
    let webEmptyLockedHint = "앱이 401을 돌려주었습니다 — Mac의 Clawdline에서 페어링하세요"
    let webEmptyNoneHint = "터미널에서 하나 시작하면 여기 나타납니다"
    let webEmptyWaitTitle = "앱을 기다리는 중"
    let webEmptyWaitHint = "아직 아무것도 들어오지 않았습니다"
    let webStateUnreadable = "화면을 읽지 못함"
    let webStateWorking = "실행 중"
    let sessionWorkReady = "새 작업을 맡길 수 있음"
    let sessionWorkUnknown = "상태 알 수 없음"
    let sessionWorkHolding = "스스로 진행 중"
    let sessionWorkOwed = "결정이 밀려 있음"
    let sessionWorkSelfStated = "자체 보고"
    let sessionWorkMilestone = "마일스톤 전달됨. 검토 또는 반영이 남아 있을 수 있음"
    let sessionWorkComplete = "브로커가 검증한 대상 브랜치 반영"
    let closeabilitySafe = "안전하게 닫을 수 있음"
    let closeabilityBlocked = "남은 의무 {n}건"
    let closeabilityBlockedOne = "남은 의무 1건"
    let closeabilityBlockedMany = "남은 의무 {n}건"
    let closeabilityNeedsAttestation = "세션 자체의 확인을 기다리는 중"
    let closeabilityUnknown = "닫아도 되는지 알 수 없음"
    let closeabilityWhy = "닫을 수 없는 이유"
    let closeabilityMoverSelf = "이 세션이 움직입니다"
    let closeabilityMoverPerson = "당신이 움직입니다"
    let closeabilityMoverSession = "다른 세션이 움직입니다"
    let closeabilityMoverBroker = "다시 읽어야 알 수 있습니다"
    let closeabilityNotProven = "브로커가 이 세션을 안전하게 닫을 수 있다고 증명하지 못했습니다."
    let closeabilityAttestationExplanation = "완료되지 않은 작업이 발견되었다는 뜻은 아닙니다. Clawdline이 확인할 수 있는 항목은 모두 정리되었지만, 이 세션은 로컬 변경 사항, 전달하지 않은 작업 또는 Clawdline 외부 작업이 남아 있는지 아직 확인하지 않았습니다. 닫기 전에 세션을 확인하세요."
    let closeabilityTechnicalDetails = "기술 세부 정보"

    let webBack = "세션"
    let webBackLabel = "세션 목록으로 돌아가기"
    let webNoSessionOpen = "열린 세션 없음"
    let webOrderTip = "트랜스크립트 뒤집기 (r)"
    let webShowOnMac = "Mac에 띄우기"
    let webShowOnMacTip = "이 세션의 터미널을 Mac 맨 앞으로 가져옵니다"
    let webShowOnMacOff = "서버가 write: false라고 답합니다 — 아직 아무것도 보낼 수 없습니다"
    let webShowOnMacAsked = "Mac에 앞으로 가져오라고 했습니다"
    let webSessionActions = "세션 작업"
    let webSessionGit = "Git 변경 사항"
    let webGitTitle = "Git 변경 사항"
    let webGitClean = "작업 트리에 변경 사항 없음"
    let webGitNotRepo = "Git 저장소가 아님"
    let webGitFailed = "Git 변경 사항을 읽을 수 없음"
    let webGitRefresh = "새로고침"
    let webGitClose = "닫기"
    let webGitStaged = "스테이징됨"
    let webGitUnstaged = "스테이징되지 않음"
    let webGitUntracked = "추적되지 않음"
    let webGitConflict = "충돌"
    let webEndSession = "세션 닫기"
    let webConfirmActionTitle = "{action}을 실행할까요?"
    let webConfirmActionSay = "현재 세션에 {action}을 보냅니다."
    let webConfirmEndTitle = "이 세션을 닫을까요?"
    let webConfirmEndSay = "어시스턴트를 종료한 뒤 터미널 탭을 닫습니다."
    let webConfirmEndLoses = "닫으면 함께 종료됩니다:"
    let webClawdfatherCreateLabel = "새 세션을 Clawdfather로 지정"
    let webClawdfatherIs = "이 세션이 {name}입니다"
    let webClawdfatherRegisterAsk = "이 새 세션을 이 Mac의 Clawdfather, 즉 machine coordinator로 등록해 주세요. 당신의 terminal-neutral session id는 {id}입니다. 먼저 ~/.config/clawdline/orchestrator-token의 orchestrator token으로 coordinator 기록을 읽으세요. 등록된 coordinator가 하나도 없을 때에 한해 docs/orchestrator.md의 “Becoming Clawdfather” 중 등록 절차를 따르세요. 이미 등록된 coordinator가 있으면 오프라인이더라도 대체하지 마세요. 끝나면 결과를 알려 주세요."
    let webClawdfatherRegisterSent = "새 세션에 Clawdfather가 되라고 요청했습니다"
    let webClawdfatherRegisterLate = "새 세션이 제때 준비되지 않아 Clawdfather로 지정하지 못했습니다."
    let webClawdfatherRegisterBlocked = "이 Mac의 coordinator 기록을 읽을 수 없어 그대로 두었습니다."
    let webCoordSectionObserve = "관찰"
    let webCoordSectionCoordinate = "조율"
    let webCoordSectionPresence = "접속 상태"
    let webCoordSectionAdmin = "관리"
    let webCoordCmdStatusReport = "상태 보고"
    let webCoordCmdStatusReportSay = "Clawdfather의 현재 상태와 진행 중인 책무를 읽습니다."
    let webCoordCmdSinceAway = "자리를 비운 사이"
    let webCoordCmdSinceAwaySay = "마지막 복귀 지점 이후 기록된 변경과 결정을 읽습니다."
    let webCoordCmdDuplicates = "중복·충돌·담당"
    let webCoordCmdDuplicatesSay = "중복된 작업, 충돌하는 선점, 현재 담당을 살펴봅니다."
    let webCoordCmdLandingClosure = "반영 마무리"
    let webCoordCmdLandingClosureSay = "리뷰를 마치고 아직 root의 반영을 기다리는 전달물을 읽습니다."
    let webCoordCmdCoordinateWork = "작업 조율"
    let webCoordCmdCoordinateWorkSay = "이미 진행 중인 작업에 대한 조율 단계를 초안으로 만듭니다."
    let webCoordCmdDispatch = "독립 작업 배정"
    let webCoordCmdDispatchSay = "독립된 자식 세션을 열게 될 배정을 미리 봅니다."
    let webCoordCmdAsk = "Clawdfather에게 묻기"
    let webCoordCmdAskSay = "Clawdfather의 판단을 구할 질문을 초안으로 만듭니다."
    let webCoordCmdQuietWatch = "조용한 지켜보기"
    let webCoordCmdQuietWatchSay = "대기 알림을 울리지 않는 조용한 관찰 요청을 초안으로 만듭니다."
    let webCoordCmdScope = "범위와 권한"
    let webCoordCmdScopeSay = "Clawdfather의 현재 범위와 부여된 권한을 읽습니다."
    let webCoordCmdStop = "Clawdfather 중지"
    let webCoordCmdStopSay = "Clawdfather 중지를 미리 봅니다."
    let webCoordCmdReconnect = "Clawdfather 재연결"
    let webCoordCmdReconnectSay = "Clawdfather 재연결을 미리 봅니다."
    let webCoordCmdDeepAudit = "심층 상태 감사"
    let webCoordCmdDeepAuditSay = "Clawdfather에게 관련 Session의 작업, 전달 및 결정을 감사하도록 요청합니다."
    let webCoordTokenExpected = "예상 Token 작업량: {effort}"
    let webCoordTokenLow = "낮음"
    let webCoordTokenMedium = "중간"
    let webCoordTokenHigh = "높음"
    let webCoordTokenUnknown = "알 수 없음"
    let webCoordAuditPreview = "Token 소모가 큰 다중 Session 요청입니다. 아직 아무것도 전송되지 않았습니다. 확인하면 전체 감사 지시를 이 정확한 Clawdfather Session에 보냅니다. 첫 버전은 agent가 수행하며 broker에 영구 run 기록이 없습니다."
    let webCoordAuditWhyOffline = "Clawdfather가 오프라인이므로 감사 요청을 보낼 수 없습니다."
    let webCoordAuditWhyDisconnected = "이 브라우저가 오프라인이므로 감사 요청을 보낼 수 없습니다."
    let webCoordAuditWhyNoWrite = "이 브라우저에는 현재 보내기/쓰기 권한이 없습니다."
    let webCoordAuditSending = "요청을 보내는 중…"
    let webCoordAuditSent = "감사 요청을 보냈습니다. 이 영수증은 감사 완료를 뜻하지 않습니다."
    let webCoordAuditFailed = "감사 요청을 보내지 못했습니다({code}): {message}"
    let webCoordEffectRead = "읽기 전용"
    let webCoordEffectAdvisory = "자문"
    let webCoordEffectSpawns = "세션 시작"
    let webCoordEffectMutation = "상태 변경"
    let webCoordStateAvailable = "사용 가능"
    let webCoordStateDraft = "초안"
    let webCoordStateUnavailable = "사용 불가"
    let webCoordStatePreview = "미리보기"
    let webCoordStateDisabled = "비활성화"
    let webCoordOnline = "{name} 온라인"
    let webCoordOffline = "{name} 오프라인"
    let webCoordControlsTitle = "{name} 제어판"
    let webCoordOpenControls = "{name} 제어판 열기"
    let webCoordEmpty = "이 페이지가 아는 Clawdfather 명령이 도착하지 않았습니다."
    let webCoordDisabledFallback = "Clawdfather가 비활성화했습니다."
    let webCoordPreviewTitle = "Clawdfather 명령"
    let webCoordPreviewNone = "선택된 명령이 없습니다. 아무것도 보내지 않았습니다."
    let webCoordPreviewMutation = "미리보기일 뿐 — 아무것도 보내지 않았습니다. Clawdfather 명령 API가 연결되기 전까지 확인 버튼은 눌리지 않습니다."
    let webCoordPreviewDraft = "오프라인 초안일 뿐 — 아무것도 보내지 않았고, Clawdfather의 판단으로 제시되지도 않았습니다."
    let webCoordPreviewSpawn = "미리보기일 뿐 — 어떤 세션도 시작되지 않았습니다."
    let webCoordPreviewContract = "이 명령의 계약을 보여줄 뿐입니다. 아무것도 보내지 않았습니다."
    let webCoordWhyNoCommandRoute = "이 패널의 명령을 세션으로 나르는 경로가 아직 없어서 아무것도 보낼 수 없습니다."
    let webCoordWhyNoReturnLedger = "이 Mac은 아직 복귀 지점을 기록하지 않아서 대조해 읽을 것이 없습니다."
    let webCoordWhyDeviceCannotSpawn = "페어링된 기기는 결코 세션을 시작할 수 없습니다 — 이 구분은 의도된 것이고, 이 버튼은 그 선을 넘지 않습니다."
    let webCoordWhyMachineTokenOnly = "재연결에는 Mac 자신의 orchestrator 토큰이 필요한데, 페어링된 기기는 의도적으로 그것을 갖지 않습니다."
    let webCoordReadFailed = "Clawdfather의 현황을 읽지 못했습니다."
    let webCoordActiveTasks = "{n}개 작업 진행 중"
    let webCoordPendingLandings = "{n}개 전달물이 반영 대기 중"
    let webCoordOpenWaits = "{n}개 파일 대기가 미해제"
    let webCoordCountUnknown = "{n}개 상태 알 수 없음"
    let webCoordStaleSessions = "Mac의 세션 상황이 오래되었습니다. 이 숫자들은 옛것일 수 있습니다."
    let webCoordUnknown = "상태 알 수 없음"
    let webCoordWaitingList = "누군가를 기다리는 중"
    let webCoordBlockingList = "남이 기다리는 파일을 쥔 세션"
    let webCoordAllQuiet = "막힌 것도, 다투는 것도, 임자 없는 것도 없습니다."
    let webCoordNoLandings = "반영을 기다리는 전달물이 없습니다."
    let webCoordUnregistered = "이 Mac에는 등록된 Clawdfather가 없습니다."
    let webCoordScopeLine = "{name}이(가) 이 Mac을 조율합니다 — 머신 범위."
    let webCoordScopeDevice = "이 패널에서는 Clawdfather를 읽을 수만 있습니다. 작업 보내기, 세션 시작, 머신 상태 변경은 Mac 자신의 자격 증명이 필요하며, 여기서는 계속 비활성화됩니다."
    let webClosing = "닫는 중…"
    let webCancel = "취소"
    let webConfirm = "확인"
    let webReviewBeforeClosing = "세션 확인"
    let webConfirmEndAnyway = "그래도 닫기"
    let webPickSession = "왼쪽에서 세션을 고르세요."
    let webReading = "읽는 중…"
    let webLoading = "불러오는 중…"
    let webTranscriptFailed = "트랜스크립트를 읽지 못했습니다"
    let webWhoYou = "나"
    let webWhoTool = "도구"
    let webNoticeTask = "작업"
    let webNoticeCompleted = "작업 완료"
    let webNoticeFailed = "작업 실패"
    let webNoticeTimedOut = "작업 시간 초과"
    let webNoticeCancelled = "작업 취소됨"
    let webNoticeCouldNotStart = "작업을 시작할 수 없음"
    let webNoticeFinished = "작업 종료"
    let webNoticeWorkspaceOverlap = "작업 공간 겹침"
    let webNoticeNoSiblings = "실행 중인 같은 계층 작업이 없습니다."
    let webNoticeOneSibling = "같은 계층 작업 {n}개가 아직 실행 중입니다."
    let webNoticeManySiblings = "같은 계층 작업 {n}개가 아직 실행 중입니다."
    let webNoticeClaimsReleased = "경로 예약이 해제되었지만 하위 탭에서 계속 쓸 수 있습니다."
    let webNoticeFileWaitRequested = "파일 대기 요청"
    let webNoticeFileWaitReleased = "파일 대기 해제"
    let webNoticeHandoffPickedUp = "인계받음"
    let webNoticeHandoffNeedsDelivery = "인계를 수동으로 전달해야 함"
    let webNoticeRecheckGit = "통합하기 전에 HEAD, status 및 diff를 다시 확인하세요."
    let webPending = "Mac을 기다리는 중…"
    let webAttachedImage = "이미지 {n}개 첨부됨"
    let webAttachedImages = "이미지 {n}개 첨부됨"
    let webSteps = "{n}단계"
    let webJustNow = "방금"
    let webMinutesAgo = "{n}분 전"
    let webCodeCopy = "이 코드 복사"
    let webCodeCopied = "코드를 복사했습니다."
    let webCodeCopyFailed = "복사하지 못했습니다. 직접 선택해 주세요."

    let webSend = "보내기"
    let webAttach = "사진 첨부"
    let webRemoveShot = "{name} 빼기"
    let webWriteOpen = "쓰려면 세션을 여세요."
    let webWriteOff = "*보내기가 꺼져 있습니다* — 서버가 `write: false`라고 답합니다. 칸은 이어져 있고, 그쪽이 바뀌면 스스로 켜집니다."
    let webShotsOnlyPictures = "메시지에 함께 보낼 수 있는 것은 사진뿐입니다"
    let webShotsTooMany = "한 메시지에 담을 수 있는 사진은 {n}장까지입니다"
    let webShotTooBig = "이 사진은 줄여도 보내기엔 너무 큽니다"
    let webShotsTooBig = "이 사진들은 함께 보내기엔 너무 큽니다"
    let webShotUnreadable = "이 사진을 읽지 못했습니다"
    let webShotNeedsSession = "사진을 보내려면 세션을 여세요"

    let webVoiceStart = "말로 메시지 쓰기"
    let webVoiceStop = "멈추고 받아쓰기"
    let webVoiceDone = "완료"
    let webVoiceListening = "듣는 중… {t}"
    let webVoiceReading = "Mac에서 받아쓰는 중… {n}초"
    let webVoiceSlow = "이 Mac을 재부팅한 뒤 첫 번째는 모델부터 읽습니다 — 열두 초쯤."
    let webVoiceLimit = "녹음이 {n}분에서 멈췄습니다. 한 번에 가는 길이가 거기까지입니다. 녹음된 데까지 받아씁니다."
    let webVoiceEmpty = "거기서 아무것도 들리지 않았습니다."
    let webVoiceTooShort = "너무 짧아서 알아들을 수 없었습니다."
    let webVoiceDenied = "마이크가 거부되었습니다. 이 사이트에 대한 이 브라우저 설정에서 다시 켜 주세요."
    let webVoiceNoMic = "이 기기에서 마이크를 찾지 못했습니다."
    let webVoiceInUse = "마이크가 사용 중입니다 — 이 기기의 다른 무언가가 쥐고 있습니다."
    let webVoiceInsecure = "마이크에는 https가 필요한데, 이 페이지는 https가 아닙니다. 터널은 https를 붙여 주지만, 로컬 네트워크의 평범한 주소는 그렇지 않습니다."
    let webVoiceUnsupported = "이 브라우저는 녹음할 수 없습니다."
    let webVoiceBusy = "하나는 받아쓰는 중이고 다른 하나가 기다리고 있습니다. 잠시 뒤에 다시 해 보세요."
    let webVoiceNoBinary = "Mac에 Whisper가 설치되어 있지 않아, 거기에는 받아쓸 것이 없습니다."
    let webVoiceNoModel = "Mac에 Whisper는 있지만 읽을 모델이 없습니다. `~/.cache/whisper`에 ggml 파일 하나면 됩니다."
    let webVoiceFailed = "그것은 받아쓰지 못했습니다."

    let webHintMove = "이동"
    let webHintOpen = "열기"
    let webHintFilter = "거르기"
    let webHintPane = "패널"

    let webKeysLabel = "키보드 단축키"
    let webKeysTitle = "키보드"
    let webKeysMove = "목록을 오르내리기 — `j`와 `k`도 같습니다"
    let webKeysOpen = "고른 세션 열기"
    let webKeysFilter = "목록 거르기"
    let webKeysEscape = "거른 것을 지우고, 그다음 뒤로"
    let webKeysList = "세션 목록으로 포커스"
    let webKeysPane = "트랜스크립트 보이기·숨기기"
    let webKeysEnds = "트랜스크립트의 맨 위나 맨 아래"
    let webKeysReverse = "트랜스크립트 순서 뒤집기"
    let webKeysThis = "이 카드"
    let webKeysFoot = "입력란에 친 것은 입력란에 남습니다 — 쓰는 동안 단축키는 물러나 있습니다."

    let webDoorLabel = "이 브라우저 페어링"
    let webDoorAskLede = "이 브라우저는 아직 들어오지 못했습니다."
    let webDoorAskFine = "페어링을 요청하면 여섯 자리 코드가 *Mac에* 뜹니다 — 이 페이지로 오는 답에는 일부러 넣지 않았습니다. 그 앞에 있는 사람만 끝낼 수 있고, 그것이 번거로움이 아니라 이 방식의 핵심입니다."
    let webDoorName = "이 기기의 이름"
    let webDoorAsk = "페어링 요청"
    let webDoorToPassword = "대신 비밀번호로 로그인"
    let webDoorCodeLede = "Mac을 보세요."
    let webDoorCodeFine = "Clawdline이 여섯 자리를 보여 줍니다. 남은 시간 {left}. 여기에 입력하세요."
    let webDoorTwoMinutes = "2분"
    let webDoorDigit = "{n}번째 자리"
    let webDoorConfirm = "이 기기 페어링"
    let webDoorRestart = "다시 시작"
    let webDoorPasswordLede = "비밀번호로 로그인합니다."
    let webDoorPasswordFine = "Mac의 Clawdline에서 설정 → 원격에 정해 둔 그것입니다. 정해 둔 적이 없다면 페어링이 들어오는 길입니다."
    let webDoorPassword = "비밀번호"
    let webDoorPasswordGo = "로그인"
    let webDoorToPair = "대신 페어링 코드 쓰기"
    let webDoorAsking = "Mac에 묻는 중…"
    let webDoorAskFailed = "Mac에 묻지 못했습니다."
    let webDoorRateLimited = "한 번 요청할 때마다 Mac에 알림이 뜨기 때문에 10분에 세 번까지입니다."
    let webDoorSixDigits = "여섯 자리입니다."
    let webDoorChecking = "확인 중…"
    let webDoorFinished = "이 페어링은 끝났습니다 — 다섯 번 틀렸습니다. Mac 앞에 있을 때 다시 요청하세요."
    let webDoorWrongCode = "그 코드가 아닙니다."
    let webDoorNeedPassword = "비밀번호부터."
    let webDoorWrongPassword = "그 비밀번호가 아닙니다."
    let webDoorExpired = "그 코드는 만료되었습니다. 다시 요청하면 새 코드가 Mac에 뜹니다."
    let webDoorPaired = "페어링 완료 — 이 브라우저는 들어왔습니다"

    let webOffline = "Clawdline에 닿지 못했습니다. Mac에서 아직 돌고 있나요?"
    let webNotJSON = "서버가 JSON이 아닌 것을 보냈습니다"
    let webRequestFailed = "요청 실패"

    let webNotifyGo = "알려 주세요"
    let webNotifyAsking = "묻는 중…"
    let webNotifyStop = "그만"
    let webNotifyStopping = "끄는 중…"
    let webNotifyOff = "세션이 답을 기다릴 때"
    let webNotifyOn = "이 기기는 등록되어 있습니다. 무엇을 알릴지는 Mac에서 정합니다."
    let webNotifyBlocked = "이 사이트의 알림이 막혀 있습니다. 그 스위치는 여기가 아니라 브라우저 자체 설정에 있습니다."
    let webNotifyUnsupported = "이 브라우저는 알림을 띄울 수 없습니다."
    let webNotifyHomeScreen = "clawdline을 홈 화면에 추가하고 거기서 여세요 — iOS는 거기 있는 앱에만 알림을 보냅니다."
    let webNotifyOnFailed = "알림을 켜지 못했습니다"
    let webNotifyOffFailed = "알림을 끄지 못했습니다"

    let webSettings = "설정"
    let webSettingsNotify = "알림"
    let webSettingsAssistantIcons = "어시스턴트 아이콘"
    let webSettingsAssistantIconsSay = "대화에서 Claude 또는 Codex 이름 앞에 아이콘을 표시합니다."
    let webSettingsAssistantIconsShow = "아이콘 표시"
    let webSettingsVersion = "버전 {v}"
    let webClose = "닫기"
    let webNotifySheetOff = "세션이 기다려도 이 기기에는 알리지 않습니다."
    let webNotifyTest = "테스트 보내기"
    let webNotifyTestSent = "보냈습니다 — 곧 이 기기에 도착할 것입니다."
    let webNotifyTestNone = "Mac에 이 기기의 등록이 없습니다. 알림을 껐다 켜면 이 브라우저가 새로 등록합니다."
    let webNotifyTestFailed = "테스트 알림을 보내지 못했습니다"
    let webSending = "보내는 중…"
    let webSendTip = "Return으로 보내기 · Shift-Return으로 줄바꿈"
    let webStart = "세션 시작"
    let webStartLabel = "프로젝트에서 세션 시작"
    let webStartPick = "어디서 시작할까요?"
    let webStartWith = "무엇으로 시작할까요?"
    let webStartEmpty = "아직 시작할 곳이 없습니다. Mac에서 Claude Code를 한 번 돌리면 여기에 나타납니다."
    let webStartFilter = "프로젝트 거르기"
    let webStarting = "탭을 여는 중…"
    let webStartWaiting = "시작했습니다. 나타나기를 기다리는 중…"
    let webStartSlow = "탭은 열렸지만 세션이 아직 알려 오지 않았습니다. Mac을 한번 보세요."
    let webStartFailed = "이것은 시작하지 못했습니다."
    let webStartGone = "그 프로젝트는 이제 Mac에 없습니다."
    let webStartTerminalClosed = "{app} 앱이 Mac에서 돌고 있지 않습니다. 거기서 연 뒤에 다시 해 보세요."
    let webStartTerminalUnsupported = "여기서는 {app} 안에서 세션을 시작할 수 없습니다. 그 안에서 tmux를 돌리면 됩니다."
    let webStartOff = "세션 시작이 꺼져 있습니다. Mac의 설정 → 원격에서 켤 수 있습니다."
    let webResumeWith = "이어서 하기"
    let webResumePick = "어느 대화를?"
    let webResumeFilter = "대화 거르기"
    let webResumeEmpty = "그 프로젝트에는 아직 아무것도 기록되지 않았습니다."
    let webResumeLive = "열려 있음"
    let webResumeBack = "다른 프로젝트"
    let webResumeGone = "그 대화는 이제 Mac에 없습니다."
    let webResumeClaudeOnly = "이어서 열 수 있는 대화를 남기는 건 Claude Code뿐입니다."
    let webResuming = "이어서 여는 중…"
    let webResumeCapped = "이보다 오래된 것은 이 목록에 없습니다."
    let webCommand = "무엇을 시작할지 말하기"
    let webCommandLabel = "말해서 세션 시작하기"
    let webCommandSay = "아래 시작을 누르기 전에는 아무것도 보내지 않습니다."
    let webCommandHeard = "무엇을 할까요?"
    let webCommandThinking = "생각하는 중…"
    let webCommandDraft = "초안"
    let webCommandWhere = "어디"
    let webCommandWith = "무엇으로"
    let webCommandModel = "모델"
    let webCommandFirst = "첫 메시지"
    let webCommandGo = "시작"
    let webCommandUnsure = "어느 프로젝트인지 확실하지 않습니다 — 아래에서 하나를 고르세요."
    let webCommandFailed = "초안으로 바꾸지 못했습니다."
    let webCommandNoPlanner = "이 Mac에는 초안으로 바꿔줄 Claude Code가 없습니다."
    let webCommandBusy = "이미 한 문장이 초안이 되는 중입니다 — 잠시 후 다시 시도하세요."
    let webCommandEmpty = "아무것도 들리지 않았습니다"
    let webScheduleNew = "새 예약"
    let webScheduleEdit = "예약 편집"
    let webScheduleNewSay = "아래 만들기를 누르기 전에는 아무것도 예약되지 않습니다."
    let webScheduleTitle = "제목"
    let webScheduleAt = "시간"
    let webScheduleOn = "요일"
    let webScheduleWhere = "어디"
    let webScheduleWith = "무엇으로"
    let webScheduleFirst = "첫 메시지"
    let webScheduleMore = "더 보기"
    let webScheduleModel = "모델"
    let webScheduleWhenDone = "끝나면 탭 닫기"
    let webScheduleCloseSuccess = "성공하면"
    let webScheduleCloseAlways = "항상"
    let webScheduleCloseNever = "열어 두기"
    let webScheduleEnabled = "사용"
    let webScheduleDisabled = "사용 안 함"
    let webScheduleNotify = "실패하면 알려주기"
    let webScheduleCatchUp = "놓쳤으면 (시간) 안에 만회하기"
    let webScheduleTimeout = "(분) 안에 못 끝내면 포기하기"
    let webScheduleCreate = "만들기"
    let webScheduleCreated = "예약을 만들었습니다."
    let webScheduleDispatchOff = "예약은 만들어졌고 유효하지만, 맡기기가 꺼져 있어서 아무도 실행하지 않습니다. Mac의 설정 → 원격에서 켤 수 있습니다."
    let webScheduleFailed = "예약을 만들지 못했습니다."
    let webScheduleSave = "저장"
    let webScheduleSaved = "예약을 저장했습니다."
    let webScheduleDelete = "삭제"
    let webScheduleDeleteAsk = "{title} 을(를) 삭제할까요? 되돌릴 수 없습니다."
    let webScheduleDeleted = "예약을 삭제했습니다."
    let webScheduleNeedsTime = "시간을 듣지 못했습니다 — 하나 정하세요."
    let webScheduleNeedsPlace = "어느 프로젝트인지 확실하지 않습니다 — 하나 고르세요."
    let webScheduleDaily = "매일"
    let webScheduleSun = "일"
    let webScheduleMon = "월"
    let webScheduleTue = "화"
    let webScheduleWed = "수"
    let webScheduleThu = "목"
    let webScheduleFri = "금"
    let webScheduleSat = "토"
    let webLinks = "링크"
    let webLinksTip = "이 프로젝트를 열 수 있는 곳"
    let webLinksPick = "이 프로젝트에 주소가 있는 것은 이게 전부입니다."
    let webLinksEmpty = "이 프로젝트에는 주소가 있는 것이 없습니다 — 사이트도, 배포도, 돌고 있는 서버도 없습니다."
    let webLinksFailed = "이 프로젝트의 링크를 읽지 못했습니다."
    let webLinksLocal = "Mac 자신의 네트워크에서만 닿습니다. 여기서는 열리지 않습니다."
    let webLinksFile = "Mac에 있는 파일입니다. 거기서 열리지, 이 브라우저에서 열리지 않습니다."
    let webLinksCopy = "경로 복사"
    let webLinksCopied = "복사했습니다."
    let webLinksCopyFailed = "이 브라우저가 페이지의 복사를 막았습니다."
    let webLinkOk = "정상"
    let webLinkFail = "오류"
    let webLinkDown = "꺼짐"
    let webLinkRunning = "진행 중"
    let webSessionInfo = "세션 정보"
    let webInfoTitle = "이 세션에 대하여"
    let webInfoEditTitle = "세션 제목 편집"
    let webInfoCopyTitle = "이 이름 복사"
    let webInfoTitleSaved = "제목을 저장했습니다."
    let webInfoTitleLocal = "Clawdline에 저장했습니다. 하위 이름은 바뀌지 않았습니다."
    let webInfoTitleQueued = "Clawdline에 저장했습니다. Codex 업데이트가 대기 중입니다."
    let webInfoTitleNotDurable = "제목은 지금 보이지만 이 Mac에 저장하지 못했습니다. 다시 시작하면 사라집니다."
    let webInfoTitleCloud = "세션 제목은 Mac에서만 바꿀 수 있고 클라우드 연결로는 바꿀 수 없습니다."
    let webInfoSession = "이 세션"
    let webInfoAssistant = "어시스턴트"
    let webInfoModel = "모델"
    let webInfoSessionId = "세션 ID"
    let webInfoDirectory = "디렉터리"
    let webInfoRunningFor = "실행 시간"
    let webInfoStatus = "상태"
    let webInfoWorkStatusMeaning = "이 세션의 작업 상태입니다. 체크 하나는 전달되어 승인 대기 중임을, 두 개는 검토와 승인이 끝났음을 뜻합니다."
    let webInfoCloseabilityMeaning = "열쇠는 이 세션을 안전하게 닫을 수 있는지를 나타냅니다. 전달 상태와는 별개입니다."
    let webInfoUsage = "토큰 사용량"
    let webInfoInput = "입력"
    let webInfoOutput = "출력"
    let webInfoCacheRead = "캐시 읽기"
    let webInfoCacheWrite = "캐시 쓰기"
    let webInfoTotal = "합계"
    let webInfoCost = "예상 비용"
    let webInfoNoUsage = "이 세션의 기록을 아직 찾지 못했습니다."
    let webInfoLimits = "플랜 한도"
    let webInfoLimitHit = "한도 도달"
    let webInfoResets = "{when} 초기화"
    let webInfoUnknown = "알 수 없음"
    let webInfoFiles = "파일"
    let webInfoBranch = "브랜치"
    let webInfoStaged = "스테이징됨"
    let webInfoUnstaged = "변경됨"
    let webInfoUntracked = "추적 안 됨"
    let webInfoConflict = "충돌"
    let webInfoClean = "커밋하지 않은 것이 없습니다."
    let webInfoNotRepo = "git 저장소가 아닙니다."
    let webInfoDeploy = "마지막 배포"
    let webInfoNoDeploy = "이 프로젝트에는 배포 기록이 없습니다."
    let webInfoFailed = "이 세션의 정보를 읽지 못했습니다."
    let webInfoBusy = "Mac이 다른 세션을 읽느라 바쁩니다. 잠시 뒤에 다시 해 보세요."
    let webInfoRefresh = "새로고침"
    let webInfoTokens = "토큰"
    let webInfoSwitchModel = "모델 바꾸기"
    let webInfoModelOther = "다른 모델…"
    let webInfoModelSent = "/model {model}을 보냈습니다. 확인 중…"
    let webInfoModelBusy = "세션이 쉬고 있을 때만 바꿀 수 있습니다."
    let webInfoSwitchPermission = "권한 모드 전환"
    let webInfoPermissionAuto = "자동"
    let webInfoPermissionManual = "수동"
    let webInfoPermissionAcceptEdits = "편집 수락"
    let webInfoPermissionPlan = "계획"
    let webInfoPermissionUnreadable = "현재 모드를 읽을 수 없습니다."
    let webInfoPermissionSent = "{mode} 모드로 전환했습니다. 확인 중…"
    let webInfoPermissionBusy = "권한 모드를 전환하는 중입니다."
    let webInfoLimitsClaude = "Claude Code는 한도를 다 쓴 뒤에야 기록하므로, 그 전에는 알 수 없습니다."
    let webInfoCopied = "세션 id를 복사했습니다."
    let webInfoAsOf = "{when} 기준"
    let webInfoWhyUnknown = "왜 알 수 없는지, 숫자를 받아오는 방법"
    let webSettingsOrder = "트랜스크립트"
    let webSettingsOrderSay = "트랜스크립트를 어느 쪽 끝부터 읽기 시작할지. 모든 세션에 적용되고, 키보드에서는 `r`이 같은 일을 합니다."
    let webAskLabel = "물었습니다"
    let webAskAny = "몇 개든 고를 수 있습니다"
    let webWaitingTitle = "이 세션이 답을 기다리고 있습니다"
    let webWaitingSay = "Claude Code가 Mac에 메뉴를 띄우고 있습니다. Clawdline은 아직 여기서 메뉴를 읽지 못해서, 고를 것들은 그 화면에만 있습니다."
    let webWaitingSend = "*여기서 보내도 답이 메뉴에 입력되지 않습니다* — 메뉴에서 지금 선택되어 있는 항목을 그대로 확정할 뿐이고, 그건 대개 뜻한 것이 아닙니다. 이건 Mac에서 답하세요."
    let webMenuSay = "답을 누르면 그대로 세션으로 갑니다."
    let webMenuHighlighted = "선택됨"
    let webMenuSent = "답을 보냈습니다."
    let webAgents = "백그라운드 에이전트"
    let webAgentsCount = "{n}개 실행 중"
    let webAgentDone = "완료"
    let webAgentFailed = "실패"
    let webShells = "백그라운드 셸"
    let webShellTitle = "백그라운드 셸"
    let webShellOpen = "이 명령이 무엇을 출력하는지 보기"
    let webShellRunning = "실행 중"
    let webShellEnded = "완료"
    let webShellQuiet = "아직 출력된 것이 없습니다."
    let webShellFailed = "이 명령의 출력을 읽지 못했습니다."
    let webShellClose = "닫기"
    let webShellStop = "중지"
    let webShellStopTitle = "이 명령을 중지할까요?"
    let webShellStopSay = "{command} 이(가) 아직 실행 중입니다. 먼저 중지를 요청하고, 5초 뒤에도 남아 있으면 강제로 종료합니다. 이미 한 일은 되돌아가지 않습니다."
    let webShellStopped = "중지를 요청했습니다."
    let webShellStopFailed = "중지하지 못했습니다."
    let agentRunning = "실행 중"
    let agentTools = "도구 {n}회"
    let agentEmpty = "이 에이전트는 아직 아무것도 남기지 않았습니다."
    let agentBack = "세션"
    let webAgentOpen = "이 에이전트가 한 일 보기"
    let webTaskRoot = "부모"
    let webTaskChild = "자식"
    let webTaskTasks = "작업"
    let webTaskDone = "완료"
    let webTaskFailed = "실패"
    let webTaskRunning = "실행 중"
    let webStale = "Mac에서 Clawdline을 다시 빌드했습니다. 이 페이지는 그 전 것입니다."
    let webStaleGo = "새로고침"

    let menuApplication = "Clawdline"
    let menuWindow = "윈도우"
    let menuHelp = "도움말"
    let menuClose = "윈도우 닫기"
    let menuHome = "홈 / 설정 센터"
    let menuHelpDocumentation = "Clawdline 문서"
    func menuAbout(_ app: String) -> String { "\(app)에 관하여" }
    let menuServices = "서비스"
    func menuHide(_ app: String) -> String { "\(app) 가리기" }
    let menuHideOthers = "기타 가리기"
    let menuShowAll = "모두 보기"
    let menuMinimize = "최소화"
    let homeTitle = "Clawdline 홈"
    let homeWelcome = "원하는 연결 목적을 선택하세요. 설정한 스위치뿐 아니라 실제로 확인된 증거를 표시합니다."
    let homePurpose = "무엇에 연결할까요?"
    let homeLocalTitle = "로컬 브라우저"
    let homeLocalSummary = "이 Mac의 브라우저에서 Clawdline을 읽습니다. 설정에서 명시적으로 켜지 않으면 제어는 꺼진 상태로 유지됩니다."
    let homeCloudPreviewTitle = "Clawdline Cloud 미리보기"
    let homeCloudPreviewSummary = "실시간 연결을 확인한 뒤 Clawdline 호스팅 미리보기 경로를 사용합니다."
    let homeCloudflareTitle = "내 Cloudflare URL"
    let homeCloudflareSummary = "공개 HTTPS 경로를 확인한 뒤 자신의 Cloudflare 호스트 이름을 사용합니다."
    let homeUnavailable = "이 빌드에서는 아직 준비되지 않았으며 연결 성공으로 표시하지 않습니다."
    let setupDetected = "감지된 상태"
    let setupNextAction = "다음 단계"
    let setupExpected = "예상 결과"
    let setupRecovery = "복구 방법"
    let setupLocalServerOff = "루프백 서버가 꺼져 있습니다."
    let setupLocalChecking = "실제 /v1/health 엔드포인트 확인 중…"
    let setupLocalConfigurationFailed = "로컬 브라우저 설정을 저장하지 못했습니다. 변경 사항은 적용되지 않았습니다."
    let setupLocalHealthTransport = "상태 엔드포인트에 연결할 수 없습니다. 포트와 다른 프로그램을 확인하세요."
    let setupLocalHealthTimedOut = "상태 엔드포인트 시간이 초과되었습니다. 포트를 확인하고 다시 시도하세요."
    func setupLocalHealthHTTP(_ status: Int) -> String { "상태 엔드포인트가 정상 응답 대신 HTTP \(status)을 반환했습니다." }
    let setupLocalHealthUnhealthy = "엔드포인트가 응답했지만 ok: false를 보고했습니다."
    let setupLocalHealthInvalid = "유효한 상태 응답이 아닙니다. 설정한 포트를 누가 사용하는지 확인하세요."
    let setupLocalReady = "상태 엔드포인트가 준비되었습니다. 브라우저 자격 증명은 아직 없습니다."
    let setupLocalWaiting = "브라우저를 열었습니다. 이 장치의 인증을 기다리는 중입니다."
    let setupLocalConnected = "연결되었습니다. 이 브라우저 장치가 Clawdline에 접속했습니다."
    let setupLocalEnable = "로컬 브라우저 켜기"
    let setupLocalRetry = "다시 확인"
    let setupLocalOpen = "읽기 전용 브라우저 열기"
    let setupLocalOpenAgain = "브라우저 다시 열기"
    let setupFinish = "완료"
    let setupLocalExpected = "읽기 전용 브라우저가 열리고 인증됩니다. 활성 세션이 없어도 성공입니다."
    let setupLocalRecovery = "멈추면 이 윈도우를 열어 둔 채 다시 확인하세요. 설정에서 서버와 포트도 확인할 수 있습니다."
    let setupNoRecovery = "복구가 필요 없습니다. 이 경로는 증명되었습니다."
    let setupLocalReadOnlyAction = "이 동작은 읽기 전용을 저장하고 · 제어를 끕니다"
    let setupReadOnly = "읽기 전용 · 제어는 계속 꺼짐"
    let setupLocalDeviceName = "설정 센터 브라우저"
    func setupTunnelFacts(_ mode: String, _ tunnel: String, _ hostname: String, _ status: String) -> String { "모드: \(mode)\n터널: \(tunnel)\nQR 호스트 이름: \(hostname)\n상태: \(status)" }
    let setupTunnelModeOff = "끔"
    let setupTunnelModeQuick = "빠른"
    let setupTunnelModeNamed = "이름 지정"
    let setupTunnelQuickName = "Cloudflare 빠른 터널"
    let setupNone = "없음"
    let setupControlChosen = "읽기 + 제어 · 설정에서 명시적으로 활성화됨"
    let setupTunnelMissing = "cloudflared가 설치되지 않았습니다."
    let setupTunnelOff = "터널이 꺼져 있어 휴대폰 QR을 사용할 수 없습니다."
    let setupTunnelStarting = "cloudflared가 시작 중이며 아직 QR을 사용할 수 없습니다."
    func setupTunnelReady(_ url: String) -> String { "\(url)에서 실행 중입니다. 휴대폰 자격 증명은 아직 없습니다." }
    func setupTunnelWaiting(_ url: String) -> String { "QR이 \(url)을 가리킵니다. 바로 이 휴대폰을 기다립니다." }
    func setupTunnelConnected(_ url: String) -> String { "\(url)을 통해 연결되었습니다. 이 휴대폰이 lastSeen을 보고했습니다." }
    let setupTunnelExpected = "실행 중인 터널 URL만 QR에 들어가며, 이 QR이 만든 비로컬 기기의 lastSeen만 설정을 완료합니다."
    let setupTunnelRecovery = "원격 설정을 여세요. cloudflared가 없으면 설치하고, 아니면 감지된 이유를 따라 터널을 유지한 뒤 다시 스캔하세요."
    let setupOpenRemoteSettings = "원격 설정 열기"
    let setupCheckTunnel = "터널 다시 확인"
    let setupShowPhoneQR = "휴대폰 QR 표시"
    let setupShowPhoneQRAgain = "휴대폰 QR 다시 표시"
    let setupCloudRelayUnauthorized = "Relay가 이 기기의 자격 증명을 거부했습니다."
    func setupCloudFacts(_ account: String, _ credential: String, _ relay: String, _ pairing: String, _ receipt: String) -> String { "계정: \(account)\n기기 자격 증명: \(credential)\nRelay 준비: \(relay)\nE2EE 페어링: \(pairing)\nViewer 수신 증명: \(receipt)" }
    let setupCloudExpected = "Preview는 계정, 기기 자격 증명, Relay, E2EE 페어링, 이 Viewer의 수신이 각각 증명되어야 완료됩니다."
    let setupCloudRecovery = "Cloud 설정에서 로그인하거나 페어링하세요. Relay와 Viewer 수신은 Preview 증명이며 재시도로 없는 증거가 생기지 않습니다."
    let setupOpenCloudSettings = "Cloud 설정 열기"
    let setupPairCloudPhone = "Cloud에서 휴대폰 페어링"
    let setupReviewCloudPreview = "Preview 상태 검토"
    let setupProofAbsent = "없음"
    let setupProofUnavailable = "증명 사용 불가"
    func setupProofFailed(_ reason: String) -> String { "실패 — \(reason)" }
    let setupCloudIdentityReadFailed = "키체인 신원을 읽지 못했습니다"
    let setupCloudRelayFailed = "Relay가 실패를 보고했습니다. Cloud 설정과 로그를 확인하세요"
    let setupCloudPairingReadFailed = "페어링 기기 저장소를 읽지 못했습니다"
    let setupCloudPairingAmbiguous = "새 Viewer가 여러 개 나타났습니다. 페어링을 다시 시작하세요"
    func setupCloudAccountProved(_ account: String) -> String { "\(account)(으)로 로그인됨" }
    func setupCloudCredentialProved(_ machine: String) -> String { "\(machine)의 키체인 자격 증명" }
    func setupCloudPairingProved(_ device: String) -> String { "정확한 Viewer \(device)에 고정됨" }
    let setupCloudflareDeviceName = "Cloudflare를 통한 휴대폰"
    let setupScanLiveTunnel = "휴대폰으로 실행 중인 터널 스캔"
    let setupDismissalHint = "Home을 닫으면 자동으로 열리지 않습니다. App 메뉴, Dock, 상태 항목 또는 clawdline://home에서 설정 센터를 다시 여세요."
    let setupCompletionFailed = "완료 상태를 저장하지 못했습니다. ~/.config/clawdline 권한을 확인하고 Home을 다시 닫으세요."

    let menuOpen = "입력창 열기"
    let menuReveal = "대상 탭으로 이동"
    let menuMascot = "마스코트"
    let menuLogin = "로그인 시 실행"
    let menuEditConfig = "설정…"
    let menuReload = "설정 다시 읽기"
    let menuQuit = "Clawdline 종료"
    let menuNoTarget = "(아직 찾지 못함)"

    func hotkeyFailedTitle(_ combo: String) -> String { "\(combo)를 등록하지 못했습니다" }
    func hotkeyFailedBody(_ configPath: String) -> String {
        """
        다른 앱이 이미 쓰고 있을 가능성이 큽니다 — Spotlight, 입력기 전환, \
        BetterTouchTool 등.

        다른 키를 고르세요: \(configPath)의 "hotkey"를 편집한 뒤 \
        메뉴 막대에서 "설정 다시 읽기"를 선택합니다.

        그때까지도 메뉴 막대의 ✳로 입력창을 열 수 있습니다.
        """
    }
    let loginFailed = "로그인 시 실행을 설정하지 못했습니다"
}
