import Foundation

struct Italian: Copy {
    let placeholder = "Scrivi a Claude Code…"

    let hintSend = "invia"
    let hintNewline = "a capo"
    let hintSwitch = "cambia"
    let hintList = "elenco"
    let hintMascot = "mascotte"
    let hintOutput = "output"
    let hintFullscreen = "schermo intero"
    let hintKeys = "tasti"
    let hintTextSize = "dimensione"
    let hintOrder = "inverti"
    let hintVoice = "detta"
    func voiceListening(onDevice: Bool) -> String {
        onDevice ? "In ascolto su questo Mac — premi di nuovo per fermare"
                 : "In ascolto — questa lingua la trascrive Apple, non questo Mac"
    }
    let voiceNoPermission = "La dettatura ha bisogno di microfono e riconoscimento vocale"
    let voiceUnavailable = "La dettatura non è disponibile in questo momento"
    func voiceTranscribing(seconds: Double) -> String {
        String(format: "Whisper sta rileggendo… %.1f s", seconds)
    }
    let whisperMissing = "Whisper non è installato — vedi docs/whisper.md"
    let whisperNothingHeard = "Non ho sentito nulla"
    func dictationStatus(_ status: Whisper.Status) -> String {
        switch status {
        case .ready(let model): return "Dettatura: Apple, poi Whisper (\(model))"
        case .noBinary: return "Dettatura: solo Apple — manca whisper-cli"
        case .noModel: return "Dettatura: solo Apple — whisper-cli c'è, manca il modello"
        }
    }
    func voiceListeningWhisper() -> String {
        "In ascolto — quando ti fermi Whisper dà un'altra letta"
    }

    let scanning = "Ricerca…"
    let noSession = "Nessuna sessione di Claude Code trovata"
    let nothingToSend = "Nessuna destinazione — avvia prima Claude Code in un terminale"
    let sendFailed = "Invio non riuscito"
    let itermSilent = "iTerm2 non ha risposto"
    let itermBusy = "iTerm2 è in attesa di una finestra di dialogo — rispondi sul Mac"
    let scriptMissing = "Manca iterm.js — bundle dell'app danneggiato?"
    let cannotList = "Non è stato possibile leggere le sessioni di iTerm2"
    let noOutput = "In questa sessione non c'è ancora nulla da leggere."
    func outputSize(_ pt: Int) -> String { "Testo dell'output \(pt) pt — ⌘J per vederlo" }
    func foldedTools(_ count: Int) -> String { "\(count) passaggi" }
    func outputOrder(newestFirst: Bool) -> String {
        newestFirst ? "Prima i più recenti" : "Prima i più vecchi"
    }
    func backlogNow(_ count: Int) -> String { "ora \(count)" }
    func dropped(_ count: Int) -> String {
        count == 1 ? "Percorso aggiunto — Claude Code lo legge" : "Aggiunti \(count) percorsi"
    }
    func stackConfirm(_ command: String) -> String { "Premi di nuovo per eseguire:  \(command)" }
    let hintStacks = "server"
    func stackTip(up: Int, total: Int) -> String { "\(up) di \(total) server attivi — ⌘S per l\'elenco" }
    let stackTipUnknown = "Questo progetto ha server; il suo comando di stato non è ancora attendibile — ⌘S"
    let stackUntrusted = "non approvato"
    let stackExit = "uscita"
    let stackActionStart = "avvia"
    let stackActionRestart = "riavvia"
    let stackActionStop = "ferma"
    let stackActionLogs = "log"
    let stackLogAll = "tutti"
    let stackLogBack = "trascrizione"
    let stackActionAllow = "consenti"
    let stackActionAgain = "di nuovo"
    func sessionTip(index: Int, total: Int) -> String { "Sessione \(index) di \(total) — ⌘K per cambiare" }
    let sessionWaiting = "aspetta te"
    let sessionAgents = "{n} in secondo piano"
    let sessionShellOne = "1 shell in esecuzione"
    let sessionShellMany = "{n} shell in esecuzione"
    let sessionWaitedOnByOne = "1 aspetta te"
    let sessionWaitedOnByMany = "{n} aspettano te"
    let islandDone = "fatto"
    let islandAllSessions = "Tutte le sessioni…"
    func statusWaiting(_ labels: [String]) -> String {
        labels.count == 1 ? "\(labels[0]) sta aspettando te"
                          : "\(labels.count) sessioni stanno aspettando te"
    }
    func statusWorking(_ count: Int) -> String { "\(count) in corso" }

    let settingsTitle = "Impostazioni di Clawdline"
    let settingsGeneral = "Generale"
    let settingsBar = "La barra"
    let settingsReading = "Lettura"
    let settingsVoice = "Dettatura"
    let settingsHotkey = "Scorciatoia"
    let settingsRecording = "Premi dei tasti…"
    let settingsScope = "Attiva in"
    let settingsScopeGlobal = "In ogni app"
    let settingsScopeHint = "Vuoto significa ovunque, quindi togliere l'ultima accende l'interruttore qui sopra — e rispegnerlo rimette l'elenco. Il file di configurazione le tiene come bundle id, e un elenco modificato a mano funziona lo stesso."
    let settingsScopeAdd = "Aggiungi un'app…"
    let settingsScopeChoose = "Scegli un'app…"
    let settingsScopeRunning = "Aperte in questo momento"
    let settingsScopeRemove = "Togli"
    let settingsLanguage = "Lingua"
    let settingsReopen = "La barra va e viene con il terminale"
    let settingsReopenHint = "Uscire dal terminale mette via la barra, e tornarci la fa ricomparire. Esc è quello che vuol dire che hai finito."
    let settingsFollow = "Il terminale mostra quello che la barra sta puntando"
    let settingsFollowHint = "Seleziona la scheda di quella sessione. Non porta il terminale in primo piano: altrimenti ogni pressione di Tab toglierebbe la tastiera dalla casella in cui stai scrivendo."
    let settingsCodexAutoName = "Dai un nome alle nuove sessioni Codex"
    let settingsCodexAutoNameHint = "Esegue un piccolo turno Codex Luna per ogni sessione senza nome. Usa la prima richiesta, consuma utilizzo Codex e non sostituisce mai un nome scelto da te."
    let settingsNotch = "Vivi nel notch"
    let settingsNotchHint = "Un personaggio nell’alloggiamento della fotocamera. Off è off: non si disegna nulla e non si crea alcuna finestra."
    let settingsPosition = "Altezza sullo schermo"
    let settingsWidth = "Larghezza"
    let settingsOpacity = "Opacità della scheda"
    let settingsShow = "Mostra"
    let settingsPaneHeight = "Altezza del riquadro"
    let settingsTextSize = "Dimensione del testo"
    let settingsPaneFont = "Font del riquadro"
    let settingsBlur = "Sfocatura dietro"
    let settingsNewestFirst = "Più recenti in alto"
    let settingsEngine = "Riconoscimento"
    let settingsSettle = "Una pausa chiude la frase"
    let settingsStop = "Un silenzio chiude la sessione"
    let settingsAuto = "Auto"
    let settingsTranscript = "Trascrizione"
    let settingsTerminal = "Terminale"
    let settingsOff = "Off"
    let settingsHooks = "Hook di Claude Code"
    let settingsHooksHint = "Una volta installati, Claude Code segnala l'istante in cui un turno inizia, finisce o aspetta una risposta, invece che Clawdline se ne accorga al controllo successivo. Tutto si legge sempre dallo schermo; questo decide solo quanto in fretta."
    let settingsHooksInstall = "Installa"
    let settingsHooksRemove = "Rimuovi"
    let settingsHooksOff = "Non installati — tutto viene letto dallo schermo"
    let settingsHooksOn = "Installati — nessuna sessione si è ancora fatta sentire"
    let settingsHooksLive = "Installati, e le sessioni si fanno sentire"
    let settingsStateHook = "Quando una sessione cambia stato"
    let settingsStateHookHint = "Ogni volta che una sessione si mette a lavorare, finisce o ti chiede qualcosa, Clawdline esegue questo: il tuo programma, con i dettagli nel suo ambiente. Si scrive nel file di configurazione e non qui perché è un argv e non una riga di comando — un percorso con uno spazio dentro deve restare un percorso solo."
    let settingsRemote = "Accesso remoto"
    let settingsRemoteServe = "Lascia che un browser o il tuo telefono vedano le tue sessioni"
    let settingsRemoteHint = "Spento, niente fuori da questo Mac arriva da nessuna parte. Acceso, l'elenco delle sessioni viene servito su 127.0.0.1: per un browser qui, per un telefono in fondo a un tunnel, per uno script. Quello che consegna sono nomi di repository, branch e titoli delle attività, ed è per questo che resta spento finché non dici il contrario."
    let settingsRemoteDevices = "Dispositivi abbinati"
    let settingsRemoteNoDevices = "Nessuno per ora — fuori da questo Mac nessuno può leggere niente"
    let settingsRemoteRevokeAll = "Disconnetti tutto"
    let settingsRemoteOpen = "Apri nel browser"
    let pairingIgnore = "Ignora"
    func pairingAsks(_ device: String) -> String { "\(device) vuole abbinarsi a questo Mac" }
    func pairingCode(_ code: String) -> String {
        """
        Digita questo codice su quel dispositivo:

        \(code)

        Vale due minuti. Se non l'hai appena chiesto tu, ignoralo — senza questo codice chi \
        ha chiesto non può arrivare in fondo.
        """
    }
    let settingsTunnel = "Raggiungi questo Mac da ovunque"
    let settingsTunnelQuick = "Un indirizzo generato"
    let settingsTunnelNamed = "Il mio dominio"
    let settingsTunnelHostname = "Nome host"
    let settingsTunnelHint = "Apre una connessione in uscita attraverso cloudflared — nessun port forwarding, niente in ascolto sulla tua rete. Non parte finché non c'è un dispositivo abbinato, perché dietro al tunnel c'è il nome di ogni repository e il titolo di ogni attività su questo Mac."
    let settingsRemoteWrite = "Lascia che un dispositivo abbinato scriva in una sessione"
    let settingsRemoteWriteHint = "Spento, un dispositivo abbinato può solo leggere. Acceso, può mandare testo dentro una sessione e avviarne di nuove — e questo esegue codice su questo Mac, perché è quello che fa Claude Code. È una decisione diversa da quella sopra, quindi è un interruttore a parte."
    let settingsRemotePhone = "Abbina un telefono…"
    let settingsRemotePhoneHint = "Mostra un codice da inquadrare. Porta con sé una chiave tutta sua: una fotografia di quel codice è un dispositivo che vedi in questo elenco e che puoi togliere di nuovo — non la chiave di questo Mac."
    let pairingScanTitle = "Inquadra questo con il telefono"
    let pushWaiting = "aspetta una risposta"
    let pushTest = "Notifica di prova. È tutto collegato."
    let pushFinished = "ha finito un lavoro lungo"
    let pushDeployOk = "il deploy è andato bene"
    let pushDeployFail = "il deploy è fallito"
    func pushChildWaiting(minutes: Int?) -> String {
        guard let minutes else { return "ha una sessione figlia in attesa" }
        return "ha una sessione figlia in attesa — \(minutes) min rimasti"
    }
    func pushBatchDone(done: Int, failed: Int) -> String {
        let all = done == 1 ? "ha completato 1 attività" : "ha completato \(done) attività"
        return failed == 0 ? all : "\(all), \(failed) non riuscite"
    }
    let settingsPushFinish = "Avvisa quando finisce un lavoro lungo"
    let settingsPushFinishHint = "Solo oltre i due minuti."
    let settingsSmartNotifications = "Notifiche intelligenti"
    let settingsSmartNotificationsHint = "Haiku riassume in una frase il lavoro concluso. Se fallisce, arriva la notifica normale."
    func pushCoalesced(count: Int) -> String { "\(count) lavori conclusi insieme" }
    let settingsSmartHealthIdle = "Nessuna notifica intelligente ancora tentata."
    func settingsSmartHealth(attempts: Int, successes: Int) -> String {
        "\(successes) tentativi su \(attempts) hanno consegnato una frase del modello."
    }
    func settingsSmartHealthFailure(reason: String, time: String) -> String {
        "Ultimo ripiego alle \(time): \(reason)."
    }
    func settingsSmartTimeout(seconds: Int) -> String {
        "Claude ha superato il limite di \(seconds) s ed è stato interrotto"
    }
    let settingsSmartQueueFull = "più lavori conclusi di quanti la coda ne tenga"
    let settingsSmartModelFailed = "Claude non ha restituito nulla di utilizzabile"
    let settingsSmartNoSource = "non c’era nulla da riassumere"
    let settingsSmartMissing = "eseguibile claude non trovato"
    let settingsPushDeploy = "Avvisa quando finisce un deploy"
    let settingsPushDeployHint = "Sia se va bene sia se fallisce."
    let settingsAgentNotify = "Consenti agli agent di inviare notifiche proprie"
    let settingsAgentNotifyNote = "Controlla solo i contenuti inviati spontaneamente da un agent; le notifiche di fine, deploy e tutte le altre non cambiano."
    let settingsOrchestrator = "Affidare lavoro"
    let settingsOrchestratorEnabled = "Lascia che una sessione affidi lavoro a un'altra"
    let settingsOrchestratorEnabledHint = "Una sessione con la skill clawdline può aprire una scheda, scriverci dentro le istruzioni e sapere quando il lavoro è finito. Spento, ogni richiesta viene rifiutata; nulla di ciò che sta già girando viene fermato."
    let settingsOrchestratorMax = "Sessioni figlie insieme"
    let settingsOrchestratorMaxHint = "Cinque di base, contate per sessione e non per Mac. Ognuna è una scheda del terminale con un assistente che ci lavora dentro."
    let settingsOrchestratorSubMax = "E quante ne passa una sessione figlia"
    let settingsOrchestratorSubMaxHint = "Tre di base. Una sessione che sta già facendo una commissione può aprirne di sue; sotto quelle non si apre nulla."
    let settingsOrchestratorSubMaxNone = "Nessuna — una figlia non passa lavoro"
    let settingsOrchestratorPermission = "Fin dove può spingersi una figlia"
    let settingsOrchestratorPermissionHint = "Nessuno guarda la scheda di una sessione figlia: una che si ferma per un'autorizzazione si ferma fino alla scadenza — e il lavoro di una sessione delegata consiste tutto nell'eseguire comandi e scrivere file, quindi qualsiasi cosa prima dell'ultima voce la ferma da qualche parte. Un compito può chiedere meno di così, mai di più."
    let settingsOrchestratorPermissionAsk = "Chiedere a ogni passo"
    let settingsOrchestratorPermissionEdits = "Scrivere file senza chiedere"
    let settingsOrchestratorPermissionFull = "Non chiedere mai"
    let settingsOrchestratorNotify = "Avvisa la sessione che ha chiesto"
    let settingsOrchestratorNotifyHint = "Una riga scritta lì dentro quando il compito finisce."
    let settingsOrchestratorClose = "Quando una sessione figlia riferisce"
    let settingsOrchestratorCloseHint = "La sua scheda viene chiusa dopo che ha riferito; quella di una scaduta resta lì, da leggere."
    let settingsOrchestratorCloseNow = "Chiudere subito la scheda"
    let settingsOrchestratorCloseLinger = "Chiuderla dopo tre minuti"
    let settingsOrchestratorCloseKeep = "Lasciarla aperta"
    let settingsOrchestratorPolicy = "Come si distribuisce il lavoro"
    let settingsOrchestratorPolicyHint = "Regole che Clawdline legge a ogni invio e ricopia nelle istruzioni di ogni sessione figlia che può inviarne a sua volta: quale assistente, quale modello, che forma deve avere il grafo. Vuoto significa nessuna regola."
    let settingsOrchestratorPolicyEdit = "Modifica le regole"
    func settingsOrchestratorPolicyOn(_ lines: Int) -> String { return "In vigore — \(lines) righe" }
    let settingsOrchestratorPolicyOff = "Nessuna regola — ogni invio è deciso da chi lo fa"
    let settingsSchedules = "Attività pianificate"
    let settingsSchedulesEmpty = "Nessuna pianificazione. Il pulsante Nuova pianificazione qui sotto ne crea una."
    let settingsScheduleNew = "Nuova attività pianificata"
    let settingsScheduleEdit = "Modifica"
    let settingsScheduleSave = "Salva"
    let settingsScheduleDelete = "Elimina"
    let settingsScheduleRun = "Esegui ora"
    let settingsScheduleReveal = "Mostra nel Finder"
    let settingsSchedulesFolder = "Apri cartella schedules"
    let settingsScheduleNext = "Prossima"
    let settingsScheduleLast = "Ultima"
    let settingsScheduleNever = "Mai eseguita"
    let settingsScheduleStarted = "Esecuzione avviata."
    let settingsScheduleActive = "L'attività pianificata precedente è ancora in esecuzione."
    let webScheduleMissed = "Ultima esecuzione mancata"
    let webScheduleNoNext = "Non è prevista una prossima esecuzione."
    func childAnnounce(_ title: String) -> String { "Incarico da Clawdline ricevuto: \(title) — comincio subito." }
    func settingsSeconds(_ value: Double) -> String { String(format: "%.1f s", value) }

    let webConnLive = "in diretta"
    let webConnConnecting = "connessione"
    let webConnRetrying = "riprovo tra {n} s"
    let webConnOffline = "non connesso"
    let webConnLocked = "non abbinato"
    let webConnTipLive = "In diretta dall'app"
    let webConnTipLocked = "Questo browser non è stato abbinato al Mac"
    let webConnTipDown = "Non connesso — fai clic per riprovare"

    let webCountWorking = "{n} in corso"
    let webCountWaiting = "{n} in attesa"
    let webCountUnreadable = "{n} illeggibili"
    let webCountQuietOne = "{n} sessione, tutto tranquillo"
    let webCountQuietMany = "{n} sessioni, tutto tranquillo"
    let webCountNone = "nessuna sessione"

    let webFilterPlaceholder = "Filtra per attività, progetto o tty"
    let webFilterLabel = "Filtra le sessioni"
    let webListLabel = "Sessioni di Claude Code"
    let webPull = "Tira per aggiornare"
    let webPullRelease = "Lascia per aggiornare"
    let webPullBusy = "Aggiornamento…"
    let webEmptyFilterTitle = "Niente corrisponde a “{q}”"
    let webEmptyFilterHint = "Esc cancella il filtro"
    let webEmptyLockedTitle = "Questo dispositivo non è abbinato"
    let webEmptyLockedHint = "L'app ha risposto 401 — abbinalo da Clawdline sul Mac"
    let webEmptyNoneHint = "Avviane una in un terminale e comparirà qui"
    let webEmptyWaitTitle = "In attesa dell'app"
    let webEmptyWaitHint = "Sullo stream non è ancora arrivato nulla"
    let webStateUnreadable = "schermo illeggibile"
    let webStateWorking = "in corso"
    let sessionWorkReady = "pronto"
    let sessionWorkNeedsTriage = "stato da verificare"
    let sessionWorkMilestone = "Traguardo consegnato; revisione o integrazione possono restare"
    let sessionWorkComplete = "Integrazione nel ramo di destinazione verificata dal broker"

    let webBack = "Sessioni"
    let webBackLabel = "Torna all'elenco delle sessioni"
    let webNoSessionOpen = "Nessuna sessione aperta"
    let webOrderTip = "Inverti la trascrizione (r)"
    let webShowOnMac = "Mostra sul Mac"
    let webShowOnMacTip = "Porta in primo piano sul Mac il terminale di questa sessione"
    let webShowOnMacOff = "Il server dice write: false — non si può ancora mandare niente"
    let webShowOnMacAsked = "Ho chiesto al Mac di portarlo in primo piano"
    let webSessionActions = "Azioni della sessione"
    let webSessionGit = "Modifiche Git"
    let webGitTitle = "Modifiche Git"
    let webGitClean = "Albero di lavoro pulito"
    let webGitNotRepo = "Non è un repository Git"
    let webGitFailed = "Impossibile leggere le modifiche Git"
    let webGitRefresh = "Aggiorna"
    let webGitClose = "Chiudi"
    let webGitStaged = "In staging"
    let webGitUnstaged = "Non in staging"
    let webGitUntracked = "Non tracciato"
    let webGitConflict = "Conflitto"
    let webEndSession = "Chiudi sessione"
    let webConfirmActionTitle = "Eseguire {action}?"
    let webConfirmActionSay = "Questo invia {action} alla sessione attuale."
    let webConfirmEndTitle = "Chiudere questa sessione?"
    let webConfirmEndSay = "L’assistente uscirà, poi la sua scheda del terminale verrà chiusa."
    let webMakeClawdfather = "Rendi questa sessione il Clawdfather"
    let webClawdfatherIs = "Questa sessione è {name}"
    let webConfirmClawdfatherTitle = "Rendere questa sessione il Clawdfather?"
    let webConfirmClawdfatherSay = "Viene digitata un’istruzione nella sessione. È lei a leggere il record del coordinatore di questo Mac e a registrarsi, o a riconnettere quello offline: non subentra mai a un coordinatore ancora attivo."
    let webClawdfatherAsk = "Rendi questa sessione il Clawdfather di questo Mac, cioè il coordinatore della macchina. Il tuo id di sessione neutro rispetto al terminale è {id}. Segui la ricetta «Becoming Clawdfather» in docs/orchestrator.md, presente anche nella skill Clawdline: leggi GET /v1/orchestrator/coordinator con il token orchestrator da ~/.config/clawdline/orchestrator-token, registrati se non ne è configurato nessuno, riconnetti con rebind se quello registrato è offline e non subentrare mai a uno ancora online. Poi racconta com’è andata."
    let webClawdfatherAsked = "Chiesto alla sessione di diventare Clawdfather"
    let webCoordSectionObserve = "Osservare"
    let webCoordSectionCoordinate = "Coordinare"
    let webCoordSectionPresence = "Presenza"
    let webCoordSectionAdmin = "Amministrazione"
    let webCoordCmdStatusReport = "Rapporto di stato"
    let webCoordCmdStatusReportSay = "Leggere lo stato attuale di Clawdfather e i suoi obblighi in corso."
    let webCoordCmdSinceAway = "Da quando sei via"
    let webCoordCmdSinceAwaySay = "Leggere le modifiche e le decisioni registrate dal tuo ultimo punto di ritorno."
    let webCoordCmdDuplicates = "Duplicati, conflitti e proprietà"
    let webCoordCmdDuplicatesSay = "Esaminare il lavoro duplicato, le rivendicazioni in conflitto e la proprietà attuale."
    let webCoordCmdLandingClosure = "Chiusura delle consegne"
    let webCoordCmdLandingClosureSay = "Leggere le consegne revisionate che attendono ancora l'integrazione della radice."
    let webCoordCmdCoordinateWork = "Coordinare il lavoro"
    let webCoordCmdCoordinateWorkSay = "Abbozzare passi di coordinamento per il lavoro già in corso."
    let webCoordCmdDispatch = "Delegare lavoro indipendente"
    let webCoordCmdDispatchSay = "Vedere in anteprima una delega che avvierebbe una sessione figlia indipendente."
    let webCoordCmdAsk = "Chiedere a Clawdfather"
    let webCoordCmdAskSay = "Abbozzare una domanda per il giudizio di Clawdfather."
    let webCoordCmdQuietWatch = "Sorveglianza silenziosa"
    let webCoordCmdQuietWatchSay = "Abbozzare una richiesta di sorveglianza discreta senza sollevare un avviso di attesa."
    let webCoordCmdScope = "Ambito e permessi"
    let webCoordCmdScopeSay = "Leggere l'ambito attuale di Clawdfather e i permessi concessi."
    let webCoordCmdStop = "Fermare Clawdfather"
    let webCoordCmdStopSay = "Vedere in anteprima l'arresto di Clawdfather."
    let webCoordCmdReconnect = "Riconnettere Clawdfather"
    let webCoordCmdReconnectSay = "Vedere in anteprima la riconnessione di Clawdfather."
    let webCoordEffectRead = "Sola lettura"
    let webCoordEffectAdvisory = "Consultivo"
    let webCoordEffectSpawns = "Avvia una sessione"
    let webCoordEffectMutation = "Cambia lo stato"
    let webCoordStateAvailable = "Disponibile"
    let webCoordStateDraft = "Bozza"
    let webCoordStateUnavailable = "Non disponibile"
    let webCoordStatePreview = "Anteprima"
    let webCoordStateDisabled = "Disattivato"
    let webCoordOnline = "{name} in linea"
    let webCoordOffline = "{name} non in linea"
    let webCoordControlsTitle = "Controlli di {name}"
    let webCoordOpenControls = "Aprire i controlli di {name}"
    let webCoordEmpty = "Non è stato annunciato alcun comando Clawdfather riconosciuto."
    let webCoordDisabledFallback = "Disattivato da Clawdfather."
    let webCoordPreviewTitle = "Comando Clawdfather"
    let webCoordPreviewNone = "Nessun comando selezionato; non è stato inviato nulla."
    let webCoordPreviewMutation = "Solo anteprima — non è stato inviato nulla. La conferma resta bloccata finché l'API dei comandi Clawdfather non è collegata."
    let webCoordPreviewDraft = "Solo bozza offline — non è stato inviato nulla né presentato come giudizio di Clawdfather."
    let webCoordPreviewSpawn = "Solo anteprima — nessuna sessione è stata avviata."
    let webCoordPreviewContract = "Viene mostrato solo il contratto di questo comando; non è stato inviato nulla."
    let webCoordWhyNoCommandRoute = "Nessuna rotta porta ancora un comando da questo pannello a una sessione, quindi non si può inviare nulla."
    let webCoordWhyNoReturnLedger = "Questo Mac non registra ancora un punto di ritorno, quindi non c'è nulla contro cui leggere."
    let webCoordWhyDeviceCannotSpawn = "Un dispositivo abbinato non può mai avviare una sessione — quella separazione è voluta, e questo pulsante non la attraverserà."
    let webCoordWhyMachineTokenOnly = "La riconnessione richiede il token dell'orchestratore del Mac, che un dispositivo abbinato volutamente non possiede."
    let webCoordReadFailed = "Impossibile leggere la situazione di Clawdfather."
    let webCoordActiveTasks = "{n} compiti in corso"
    let webCoordPendingLandings = "{n} consegne in attesa di integrazione"
    let webCoordOpenWaits = "{n} attese di file aperte"
    let webCoordCountTriage = "{n} da smistare"
    let webCoordStaleSessions = "L'immagine delle sessioni del Mac è datata; questi numeri potrebbero essere vecchi."
    let webCoordNeedsTriage = "Da smistare"
    let webCoordWaitingList = "In attesa di qualcuno"
    let webCoordBlockingList = "Trattiene file che altri attendono"
    let webCoordAllQuiet = "Nulla è bloccato, conteso o senza proprietario."
    let webCoordNoLandings = "Nessuna consegna attende l'integrazione."
    let webCoordUnregistered = "Nessun Clawdfather è registrato su questo Mac."
    let webCoordScopeLine = "{name} coordina questo Mac — ambito macchina."
    let webCoordScopeDevice = "Da questo pannello Clawdfather può solo essere letto. Inviare lavoro, avviare sessioni e cambiare lo stato della macchina richiedono le credenziali del Mac stesso, e qui restano disattivati."
    let webClosing = "Chiusura…"
    let webCancel = "Annulla"
    let webConfirm = "Conferma"
    let webPickSession = "Scegli una sessione a sinistra."
    let webReading = "Lettura…"
    let webLoading = "Caricamento…"
    let webTranscriptFailed = "Non è stato possibile leggere la trascrizione"
    let webWhoYou = "tu"
    let webWhoTool = "strumento"
    let webNoticeTask = "attività"
    let webNoticeCompleted = "Attività completata"
    let webNoticeFailed = "Attività non riuscita"
    let webNoticeTimedOut = "Attività scaduta"
    let webNoticeCancelled = "Attività annullata"
    let webNoticeCouldNotStart = "Impossibile avviare l’attività"
    let webNoticeFinished = "Attività terminata"
    let webNoticeWorkspaceOverlap = "Sovrapposizione dell’area di lavoro"
    let webNoticeNoSiblings = "Nessuna attività parallela è ancora in esecuzione."
    let webNoticeOneSibling = "{n} attività parallela è ancora in esecuzione."
    let webNoticeManySiblings = "{n} attività parallele sono ancora in esecuzione."
    let webNoticeClaimsReleased = "Le prenotazioni dei percorsi sono state rilasciate; la scheda figlia potrebbe ancora scrivere."
    let webNoticeFileWaitRequested = "Attesa file richiesta"
    let webNoticeFileWaitReleased = "Attesa file terminata"
    let webNoticeHandoffPickedUp = "Passaggio di consegne preso in carico"
    let webNoticeHandoffNeedsDelivery = "Il passaggio richiede una consegna manuale"
    let webNoticeRecheckGit = "Ricontrolla HEAD, status e diff prima dell’integrazione."
    let webPending = "In attesa del Mac…"
    let webAttachedImage = "{n} immagine allegata"
    let webAttachedImages = "{n} immagini allegate"
    let webSteps = "{n} passaggi"
    let webJustNow = "adesso"
    let webMinutesAgo = "{n} min fa"

    let webSend = "Invia"
    let webAttach = "Allega un'immagine"
    let webRemoveShot = "Togli {name}"
    let webWriteOpen = "Apri una sessione per scriverci."
    let webWriteOff = "*L'invio è spento* — il server dice `write: false`. La casella è collegata; si accende da sola quando quello cambia."
    let webShotsOnlyPictures = "Con un messaggio possono partire solo immagini"
    let webShotsTooMany = "Un messaggio può portare al massimo {n} immagini"
    let webShotTooBig = "Quell'immagine è troppo grande da mandare, anche ridotta"
    let webShotsTooBig = "Quelle immagini sono troppo grandi per partire insieme"
    let webShotUnreadable = "Non è stato possibile leggere quell'immagine"
    let webShotNeedsSession = "Apri una sessione per mandarle un'immagine"

    let webVoiceStart = "Detta un messaggio"
    let webVoiceStop = "Ferma e trascrivi"
    let webVoiceDone = "Fine"
    let webVoiceListening = "In ascolto… {t}"
    let webVoiceReading = "Trascrizione sul Mac… {n} s"
    let webVoiceSlow = "La prima dopo un riavvio di questo Mac carica prima il modello — una dozzina di secondi."
    let webVoiceLimit = "La registrazione si è fermata a {n} minuti, tanto dura al massimo. Si trascrive quel che c'è."
    let webVoiceEmpty = "Lì non si è sentito nulla."
    let webVoiceTooShort = "È stato troppo breve per sentirci qualcosa."
    let webVoiceDenied = "Il microfono è stato negato. Riaccendilo nelle impostazioni di questo browser per questo sito."
    let webVoiceNoMic = "Su questo dispositivo non si trova nessun microfono."
    let webVoiceInUse = "Il microfono è occupato — ce l'ha qualcos'altro su questo dispositivo."
    let webVoiceInsecure = "Un microfono vuole https, e questa pagina non ce l'ha. Il tunnel te lo dà; un normale indirizzo sulla rete locale no."
    let webVoiceUnsupported = "Questo browser non sa registrare audio."
    let webVoiceBusy = "Una è in trascrizione e un'altra è in attesa. Riprova fra un momento."
    let webVoiceNoBinary = "Sul Mac non c'è Whisper, quindi lì non c'è niente con cui trascrivere."
    let webVoiceNoModel = "Whisper sul Mac c'è, ma non ha un modello con cui leggere. Gli basta un file ggml in `~/.cache/whisper`."
    let webVoiceFailed = "Non è stato possibile trascriverlo."

    let webHintMove = "scorri"
    let webHintOpen = "apri"
    let webHintFilter = "filtra"
    let webHintPane = "riquadro"

    let webKeysLabel = "Scorciatoie da tastiera"
    let webKeysTitle = "Tastiera"
    let webKeysMove = "Scorri l'elenco — `j` e `k` fanno lo stesso"
    let webKeysOpen = "Apri la sessione selezionata"
    let webKeysFilter = "Filtra l'elenco"
    let webKeysEscape = "Cancella il filtro, poi torna indietro"
    let webKeysList = "Vai all'elenco delle sessioni"
    let webKeysPane = "Mostra o nascondi la trascrizione"
    let webKeysEnds = "Inizio o fine della trascrizione"
    let webKeysReverse = "Inverti l'ordine della trascrizione"
    let webKeysThis = "Questa scheda"
    let webKeysFoot = "Quello che scrivi in una casella di testo resta nella casella — le scorciatoie si fanno da parte mentre scrivi."

    let webDoorLabel = "Abbina questo browser"
    let webDoorAskLede = "Questo browser non è ancora stato fatto entrare."
    let webDoorAskFine = "Chiedi di abbinarti e un codice di sei cifre compare *sul Mac* — di proposito non è nella risposta a questa pagina. Solo chi è davanti a quella macchina può arrivare in fondo, ed è proprio questo il punto, non l'ostacolo."
    let webDoorName = "Chiama questo dispositivo"
    let webDoorAsk = "Chiedi di abbinarti"
    let webDoorToPassword = "Accedi invece con una password"
    let webDoorCodeLede = "Guarda il Mac."
    let webDoorCodeFine = "Clawdline mostra sei cifre per altri {left}. Digitale qui."
    let webDoorTwoMinutes = "due minuti"
    let webDoorDigit = "Cifra {n}"
    let webDoorConfirm = "Abbina questo dispositivo"
    let webDoorRestart = "Ricomincia"
    let webDoorPasswordLede = "Accedi con la password."
    let webDoorPasswordFine = "Quella impostata in Clawdline sul Mac, in Impostazioni → Accesso remoto. Se non ne è stata impostata nessuna, si entra abbinandosi."
    let webDoorPassword = "Password"
    let webDoorPasswordGo = "Accedi"
    let webDoorToPair = "Usa invece un codice di abbinamento"
    let webDoorAsking = "Chiedo al Mac…"
    let webDoorAskFailed = "Non è stato possibile chiedere al Mac."
    let webDoorRateLimited = "Ogni richiesta fa comparire un avviso sul Mac, perciò se ne possono fare solo tre ogni dieci minuti."
    let webDoorSixDigits = "Sei cifre."
    let webDoorChecking = "Controllo…"
    let webDoorFinished = "Questo abbinamento è chiuso — cinque codici sbagliati. Richiedilo quando sei davanti al Mac."
    let webDoorWrongCode = "Quel codice non è giusto."
    let webDoorNeedPassword = "Prima la password."
    let webDoorWrongPassword = "Quella non è la password."
    let webDoorExpired = "Quel codice è scaduto. Richiedilo e sul Mac ne compare uno nuovo."
    let webDoorPaired = "Abbinato — questo browser è dentro"

    let webOffline = "Non ho raggiunto Clawdline. È ancora in esecuzione sul Mac?"
    let webNotJSON = "Il server ha mandato qualcosa che non è JSON"
    let webRequestFailed = "Richiesta non riuscita"

    let webNotifyGo = "Avvisami"
    let webNotifyAsking = "Chiedo…"
    let webNotifyStop = "Ferma"
    let webNotifyStopping = "Sto fermando…"
    let webNotifyOff = "quando una sessione aspetta una risposta"
    let webNotifyOn = "Questo dispositivo è iscritto. Di cosa viene avvisato si decide sul Mac."
    let webNotifyBlocked = "Le notifiche sono bloccate per questo sito. Quell'interruttore sta nelle impostazioni del browser, non qui."
    let webNotifyUnsupported = "Questo browser non sa mostrare notifiche."
    let webNotifyHomeScreen = "Aggiungi clawdline alla schermata Home e aprilo da lì — iOS manda notifiche solo a un'app che abita lì."
    let webNotifyOnFailed = "Non è stato possibile attivare le notifiche"
    let webNotifyOffFailed = "Non è stato possibile disattivare le notifiche"

    let webSettings = "Impostazioni"
    let webSettingsNotify = "Notifiche"
    let webSettingsAssistantIcons = "Icone dell’assistente"
    let webSettingsAssistantIconsSay = "Mostra il simbolo di Claude o Codex prima del nome nella conversazione."
    let webSettingsAssistantIconsShow = "Mostra icone"
    let webSettingsVersion = "Versione {v}"
    let webClose = "Chiudi"
    let webNotifySheetOff = "A questo dispositivo non viene detto quando una sessione aspetta."
    let webNotifyTest = "Manda una prova"
    let webNotifyTestSent = "Mandata — tra un attimo dovrebbe arrivare su questo dispositivo."
    let webNotifyTestNone = "Il Mac non ha nessuna iscrizione per questo dispositivo. Disattiva e riattiva le notifiche, e questo browser ne registrerà una nuova."
    let webNotifyTestFailed = "Non è stato possibile mandare una notifica di prova"
    let webSending = "Invio…"
    let webSendTip = "Invio manda · Maiusc-Invio va a capo"
    let webStart = "Avvia una sessione"
    let webStartLabel = "Avvia una sessione in un progetto"
    let webStartPick = "Dove deve partire?"
    let webStartWith = "Con quale farla partire?"
    let webStartEmpty = "Ancora nessun posto da cui partire. Fai girare Claude Code una volta sul Mac e comparirà qui."
    let webStartFilter = "Filtra i progetti"
    let webStarting = "Apro una scheda…"
    let webStartWaiting = "Avviata. Sta per comparire…"
    let webStartSlow = "La scheda è aperta, ma la sessione non si è fatta sentire. Dai un'occhiata al Mac."
    let webStartFailed = "Non è stato possibile avviarla."
    let webStartGone = "Quel progetto non è più sul Mac."
    let webStartTerminalClosed = "{app} non è in esecuzione sul Mac. Aprilo lì e riprova."
    let webStartTerminalUnsupported = "Da qui non si può avviare una sessione in {app}. Fai girare tmux lì dentro e funziona."
    let webStartOff = "L'avvio delle sessioni è spento. Si accende da Impostazioni → Accesso remoto sul Mac."
    let webResumeWith = "Riprendi una precedente"
    let webResumePick = "Quale conversazione?"
    let webResumeFilter = "Filtra le conversazioni"
    let webResumeEmpty = "In quel progetto non è ancora stato registrato nulla."
    let webResumeLive = "aperta"
    let webResumeBack = "Un altro progetto"
    let webResumeGone = "Quella conversazione non è più sul Mac."
    let webResumeClaudeOnly = "Solo Claude Code conserva conversazioni che si possono riprendere."
    let webResuming = "La sto riprendendo…"
    let webResumeCapped = "Quelle più vecchie non sono in questo elenco."
    let webCommand = "Di' cosa vuoi avviare"
    let webCommandLabel = "Avviare una sessione dicendo cosa deve fare"
    let webCommandSay = "Non viene inviato nulla finché non premi Avvia qui sotto."
    let webCommandHeard = "Cosa deve fare?"
    let webCommandThinking = "Sto pensando…"
    let webCommandDraft = "Bozza"
    let webCommandWhere = "Dove"
    let webCommandWith = "Con"
    let webCommandModel = "Modello"
    let webCommandFirst = "Primo messaggio"
    let webCommandGo = "Avvia"
    let webCommandUnsure = "Non è chiaro quale progetto — scegline uno qui sotto."
    let webCommandFailed = "Non sono riuscito a farne una bozza."
    let webCommandNoPlanner = "Questo Mac non ha Claude Code per farne una bozza."
    let webCommandBusy = "C'è già una frase che sta diventando una bozza — riprova tra un momento."
    let webCommandEmpty = "Non ho sentito nulla"
    let webScheduleNew = "Nuova attività pianificata"
    let webScheduleEdit = "Modifica attività pianificata"
    let webScheduleNewSay = "Non viene pianificato nulla finché non premi Crea qui sotto."
    let webScheduleTitle = "Titolo"
    let webScheduleAt = "Ora"
    let webScheduleOn = "Giorni"
    let webScheduleWhere = "Dove"
    let webScheduleWith = "Con"
    let webScheduleFirst = "Primo messaggio"
    let webScheduleMore = "Altro"
    let webScheduleModel = "Modello"
    let webScheduleWhenDone = "Chiudere la scheda al termine"
    let webScheduleCloseSuccess = "Se ha successo"
    let webScheduleCloseAlways = "Sempre"
    let webScheduleCloseNever = "Lasciarla aperta"
    let webScheduleEnabled = "Attivo"
    let webScheduleDisabled = "Inattivo"
    let webScheduleNotify = "Avvisami se fallisce"
    let webScheduleCatchUp = "Se è stata persa, recuperarla entro (ore)"
    let webScheduleTimeout = "Arrendersi se non finisce entro (minuti)"
    let webScheduleCreate = "Crea"
    let webScheduleCreated = "Attività pianificata creata."
    let webScheduleDispatchOff = "L'attività pianificata è creata e valida, ma l'invio è spento — nessuno la eseguirà. Si accende da Impostazioni → Accesso remoto sul Mac."
    let webScheduleFailed = "Non sono riuscito a creare l'attività pianificata."
    let webScheduleSave = "Salva"
    let webScheduleSaved = "Attività pianificata salvata."
    let webScheduleDelete = "Elimina"
    let webScheduleDeleteAsk = "Eliminare {title}? Non si può annullare."
    let webScheduleDeleted = "Attività pianificata eliminata."
    let webScheduleNeedsTime = "Non ho sentito un orario — impostane uno."
    let webScheduleNeedsPlace = "Non è chiaro quale progetto — scegline uno."
    let webScheduleDaily = "Ogni giorno"
    let webScheduleSun = "Dom"
    let webScheduleMon = "Lun"
    let webScheduleTue = "Mar"
    let webScheduleWed = "Mer"
    let webScheduleThu = "Gio"
    let webScheduleFri = "Ven"
    let webScheduleSat = "Sab"
    let webLinks = "Link"
    let webLinksTip = "Dove si può aprire questo progetto"
    let webLinksPick = "Tutto quello di cui questo progetto ha un indirizzo."
    let webLinksEmpty = "Questo progetto non ha niente con un indirizzo — nessun sito, nessun deploy, e nessun server acceso."
    let webLinksFailed = "Non è stato possibile leggere i link di questo progetto."
    let webLinksLocal = "Solo sulla rete del Mac. Da qui non si apre."
    let webLinksFile = "Un file sul Mac. Si apre lì, non in questo browser."
    let webLinksCopy = "Copia il percorso"
    let webLinksCopied = "Copiato."
    let webLinksCopyFailed = "Questo browser non ha lasciato che la pagina lo copiasse."
    let webLinkOk = "ok"
    let webLinkFail = "errore"
    let webLinkDown = "spento"
    let webLinkRunning = "in corso"
    let webSessionInfo = "Info sessione"
    let webInfoTitle = "Su questa sessione"
    let webInfoEditTitle = "Modifica titolo sessione"
    let webInfoCopyTitle = "Copia questo nome"
    let webInfoTitleSaved = "Titolo salvato."
    let webInfoTitleLocal = "Titolo salvato in Clawdline; nome a valle invariato."
    let webInfoTitleQueued = "Titolo salvato in Clawdline; aggiornamento Codex in coda."
    let webInfoTitleNotDurable = "Titolo applicato, ma questo Mac non è riuscito a salvarlo su disco; sparirà al riavvio."
    let webInfoTitleCloud = "I titoli di sessione si cambiano solo sul Mac, non tramite la connessione cloud."
    let webInfoSession = "Questa sessione"
    let webInfoAssistant = "Assistente"
    let webInfoModel = "Modello"
    let webInfoSessionId = "ID sessione"
    let webInfoDirectory = "Cartella"
    let webInfoRunningFor = "In corso da"
    let webInfoUsage = "Consumo di token"
    let webInfoInput = "In ingresso"
    let webInfoOutput = "In uscita"
    let webInfoCacheRead = "Cache letta"
    let webInfoCacheWrite = "Cache scritta"
    let webInfoTotal = "Totale"
    let webInfoCost = "Costo stimato"
    let webInfoNoUsage = "Nessuna trascrizione trovata per questa sessione, per ora."
    let webInfoLimits = "Limiti del piano"
    let webInfoLimitHit = "limite raggiunto"
    let webInfoResets = "si azzera {when}"
    let webInfoUnknown = "sconosciuto"
    let webInfoFiles = "File"
    let webInfoBranch = "Branch"
    let webInfoStaged = "In stage"
    let webInfoUnstaged = "Modificati"
    let webInfoUntracked = "Non tracciati"
    let webInfoConflict = "Conflitti"
    let webInfoClean = "Niente da committare."
    let webInfoNotRepo = "Non è un repository git."
    let webInfoDeploy = "Ultimo deploy"
    let webInfoNoDeploy = "Nessun deploy registrato per questo progetto."
    let webInfoFailed = "Non è stato possibile leggere le info di questa sessione."
    let webInfoBusy = "Il Mac è occupato a leggere altre sessioni. Riprova fra un momento."
    let webInfoRefresh = "Aggiorna"
    let webInfoTokens = "token"
    let webInfoSwitchModel = "Cambia modello"
    let webInfoModelOther = "un altro modello…"
    let webInfoModelSent = "/model {model} inviato. Conferma in corso…"
    let webInfoModelBusy = "Il cambio aspetta che la sessione sia inattiva."
    let webInfoSwitchPermission = "Cambia modalità di autorizzazione"
    let webInfoPermissionAuto = "Automatica"
    let webInfoPermissionManual = "Manuale"
    let webInfoPermissionAcceptEdits = "Accetta modifiche"
    let webInfoPermissionPlan = "Pianificazione"
    let webInfoPermissionUnreadable = "Impossibile leggere la modalità corrente."
    let webInfoPermissionSent = "Modalità {mode} attivata. Verifica in corso…"
    let webInfoPermissionBusy = "È in corso il cambio della modalità di autorizzazione."
    let webInfoLimitsClaude = "Claude Code annota una finestra solo quando è esaurita; fino ad allora non si sa nulla."
    let webInfoCopied = "Id della sessione copiato."
    let webInfoAsOf = "alle {when}"
    let webInfoWhyUnknown = "Perché è sconosciuto, e come avere i numeri"
    let webSettingsOrder = "Trascrizione"
    let webSettingsOrderSay = "Da che capo iniziare a leggere una trascrizione. Vale per tutte le sessioni, e da tastiera `r` fa lo stesso."
    let webAskLabel = "ha chiesto"
    let webAskAny = "Quante ne vuoi, di queste"
    let webWaitingTitle = "Questa sessione aspetta una risposta"
    let webWaitingSay = "Claude Code sta mostrando un menu sul Mac. Clawdline da qui un menu non riesce ancora a leggerlo, quindi le scelte stanno solo su quello schermo."
    let webWaitingSend = "*Mandare da qui non scrive la tua risposta nel menu* — conferma la voce che nel menu è evidenziata, che quasi mai è quella che intendevi. A questa rispondi sul Mac."
    let webMenuSay = "Tocca una risposta e va dritta nella sessione."
    let webMenuHighlighted = "evidenziata"
    let webMenuSent = "Risposta inviata."
    let webAgents = "Agenti in secondo piano"
    let webAgentsCount = "{n} in corso"
    let webAgentDone = "fatto"
    let webAgentFailed = "fallito"
    let webShells = "Shell in secondo piano"
    let webShellTitle = "Shell in secondo piano"
    let webShellOpen = "Vedi cosa sta stampando questo comando"
    let webShellRunning = "in corso"
    let webShellEnded = "terminato"
    let webShellQuiet = "Non ha ancora stampato nulla."
    let webShellFailed = "Impossibile leggere l'output di questo comando."
    let webShellClose = "Chiudi"
    let webShellStop = "Ferma"
    let webShellStopTitle = "Fermare questo comando?"
    let webShellStopSay = "{command} è ancora in esecuzione. Gli viene chiesto di fermarsi, e viene ucciso cinque secondi dopo se non lo fa. Quello che ha già fatto non viene annullato."
    let webShellStopped = "Gli è stato chiesto di fermarsi."
    let webShellStopFailed = "Non è stato possibile fermarlo."
    let agentRunning = "in corso"
    let agentTools = "{n} strumenti"
    let agentEmpty = "Questo agente non ha ancora scritto nulla."
    let agentBack = "Sessione"
    let webAgentOpen = "Vedi cosa ha fatto questo agente"
    let webTaskRoot = "Padre"
    let webTaskChild = "Figlio"
    let webTaskTasks = "Attività"
    let webTaskDone = "fatto"
    let webTaskFailed = "fallito"
    let webTaskRunning = "in corso"
    let webStale = "Clawdline è stato ricompilato sul Mac. Questa pagina è quella di prima."
    let webStaleGo = "Ricarica"

    let menuOpen = "Apri la barra"
    let menuReveal = "Vai alla scheda di destinazione"
    let menuMascot = "Mascotte"
    let menuLogin = "Apri all'accesso"
    let menuEditConfig = "Impostazioni…"
    let menuReload = "Ricarica configurazione"
    let menuQuit = "Esci da Clawdline"
    let menuNoTarget = "(non ancora rilevato)"

    func hotkeyFailedTitle(_ combo: String) -> String { "Non è stato possibile registrare \(combo)" }
    func hotkeyFailedBody(_ configPath: String) -> String {
        """
        Con ogni probabilità la usa già un'altra app — Spotlight, un commutatore di \
        tastiera, BetterTouchTool e simili.

        Scegline un'altra: modifica "hotkey" in \(configPath), poi scegli \
        "Ricarica configurazione" dalla barra dei menu.

        Fino ad allora, il ✳ nella barra dei menu apre comunque la barra.
        """
    }
    let loginFailed = "Non è stato possibile impostare l'apertura all'accesso"
}
