import Foundation

struct French: Copy {
    let placeholder = "Écrire à Claude Code…"

    let hintSend = "envoyer"
    let hintNewline = "nouvelle ligne"
    let hintSwitch = "changer"
    let hintList = "liste"
    let hintMascot = "mascotte"
    let hintOutput = "sortie"
    let hintFullscreen = "plein écran"
    let hintKeys = "touches"
    let hintTextSize = "taille"
    let hintOrder = "inverser"
    let hintVoice = "dicter"
    func voiceListening(onDevice: Bool) -> String {
        onDevice ? "À l'écoute sur ce Mac — appuyez à nouveau pour arrêter"
                 : "À l'écoute — cette langue est transcrite par Apple, pas sur ce Mac"
    }
    let voiceNoPermission = "La dictée a besoin du micro et de la reconnaissance vocale"
    let voiceUnavailable = "La dictée n'est pas disponible pour le moment"
    func voiceTranscribing(seconds: Double) -> String {
        String(format: "Whisper relit… %.1f s", seconds)
    }
    let whisperMissing = "Whisper n'est pas installé — voir docs/whisper.md"
    let whisperNothingHeard = "Rien entendu"
    func dictationStatus(_ status: Whisper.Status) -> String {
        switch status {
        case .ready(let model): return "Dictée : Apple, puis Whisper (\(model))"
        case .noBinary: return "Dictée : Apple seulement — pas de whisper-cli"
        case .noModel: return "Dictée : Apple seulement — whisper-cli est là, pas de modèle"
        }
    }
    func voiceListeningWhisper() -> String {
        "À l'écoute — Whisper relit tout quand vous vous arrêtez"
    }

    let scanning = "Recherche…"
    let noSession = "Aucune session Claude Code trouvée"
    let nothingToSend = "Aucune destination — lancez d'abord Claude Code dans un terminal"
    let sendFailed = "Envoi impossible"
    let itermSilent = "iTerm2 n'a pas répondu"
    let scriptMissing = "iterm.js est introuvable — paquet de l'app abîmé ?"
    let cannotList = "Impossible de lire les sessions iTerm2"
    let noOutput = "Rien à lire dans cette session pour l'instant."
    func outputSize(_ pt: Int) -> String { "Texte de sortie \(pt) pt — ⌘J pour l'afficher" }
    func foldedTools(_ count: Int) -> String { "\(count) étapes" }
    func outputOrder(newestFirst: Bool) -> String {
        newestFirst ? "Le plus récent en haut" : "Le plus ancien en haut"
    }
    func backlogNow(_ count: Int) -> String { "maintenant \(count)" }
    func dropped(_ count: Int) -> String {
        count == 1 ? "Chemin ajouté — Claude Code le lit" : "\(count) chemins ajoutés"
    }
    func stackConfirm(_ command: String) -> String { "Appuyez à nouveau pour exécuter :  \(command)" }
    let hintStacks = "serveurs"
    func stackTip(up: Int, total: Int) -> String { "\(up) serveurs sur \(total) actifs — ⌘S pour la liste" }
    let stackTipUnknown = "Ce projet a des serveurs ; sa commande d'état n'est pas encore approuvée — ⌘S"
    let stackUntrusted = "non approuvé"
    let stackExit = "sortie"
    let stackActionStart = "démarrer"
    let stackActionRestart = "redémarrer"
    let stackActionStop = "arrêter"
    let stackActionLogs = "journal"
    let stackLogAll = "tout"
    let stackLogBack = "transcription"
    let stackActionAllow = "autoriser"
    let stackActionAgain = "à nouveau"
    func sessionTip(index: Int, total: Int) -> String { "Session \(index) sur \(total) — ⌘K pour changer" }
    let sessionWaiting = "attend ta réponse"
    let sessionAgents = "{n} en arrière-plan"
    let islandDone = "terminé"
    let islandAllSessions = "Toutes les sessions…"
    func statusWaiting(_ labels: [String]) -> String {
        labels.count == 1 ? "\(labels[0]) attend ta réponse"
                          : "\(labels.count) sessions attendent ta réponse"
    }
    func statusWorking(_ count: Int) -> String { "\(count) en cours" }

    let settingsTitle = "Réglages de Clawdline"
    let settingsGeneral = "Général"
    let settingsBar = "La barre"
    let settingsReading = "Lecture"
    let settingsVoice = "Dictée"
    let settingsHotkey = "Raccourci"
    let settingsRecording = "Appuie sur des touches…"
    let settingsScope = "Actif dans"
    let settingsScopeGlobal = "Dans toutes les apps"
    let settingsScopeHint = "Vide veut dire partout, donc retirer la dernière allume l'interrupteur du dessus — et le rééteindre remet la liste. Le fichier de configuration les garde sous forme d'identifiants de bundle, et une liste modifiée à la main marche toujours."
    let settingsScopeAdd = "Ajouter une app…"
    let settingsScopeChoose = "Choisir une app…"
    let settingsScopeRunning = "Ouvertes en ce moment"
    let settingsScopeRemove = "Retirer"
    let settingsLanguage = "Langue"
    let settingsReopen = "La barre va et vient avec le terminal"
    let settingsReopenHint = "Quitter le terminal range la barre, y revenir la fait revenir. C'est Esc qui veut dire que vous en avez fini."
    let settingsFollow = "Le terminal montre ce que la barre vise"
    let settingsFollowHint = "Elle sélectionne l'onglet de cette session. Elle ne met pas le terminal au premier plan : sinon chaque appui sur Tab sortirait le clavier de la case dans laquelle vous écrivez."
    let settingsCodexAutoName = "Nommer les nouvelles sessions Codex"
    let settingsCodexAutoNameHint = "Lance un petit tour Codex Luna pour chaque session sans nom. Il utilise la première demande, consomme l’usage Codex et ne remplace jamais un nom choisi."
    let settingsNotch = "Habiter l’encoche"
    let settingsNotchHint = "Un personnage dans le boîtier de la caméra. Désactivé = rien n’est dessiné, aucune fenêtre créée."
    let settingsPosition = "Hauteur à l’écran"
    let settingsWidth = "Largeur"
    let settingsOpacity = "Opacité de la carte"
    let settingsShow = "Afficher"
    let settingsPaneHeight = "Hauteur du volet"
    let settingsTextSize = "Taille du texte"
    let settingsPaneFont = "Police du volet"
    let settingsBlur = "Flou derrière"
    let settingsNewestFirst = "Plus récent en haut"
    let settingsEngine = "Reconnaissance"
    let settingsSettle = "Une pause termine la phrase"
    let settingsStop = "Un silence termine la séance"
    let settingsAuto = "Auto"
    let settingsTranscript = "Transcription"
    let settingsTerminal = "Terminal"
    let settingsOff = "Désactivé"
    let settingsHooks = "Hooks Claude Code"
    let settingsHooksHint = "Une fois installés, Claude Code signale l'instant où un tour commence, se termine ou attend une réponse, au lieu que Clawdline l'apprenne au prochain coup d'œil. Tout se lit toujours sur l'écran ; ceci ne décide que du moment de la lecture."
    let settingsHooksInstall = "Installer"
    let settingsHooksRemove = "Retirer"
    let settingsHooksOff = "Non installés — tout est lu sur l'écran"
    let settingsHooksOn = "Installés — aucune session ne s'est encore signalée"
    let settingsHooksLive = "Installés, et les sessions se signalent"
    let settingsStateHook = "Quand une session change d'état"
    let settingsStateHookHint = "Chaque fois qu'une session se met au travail, termine, ou vous pose une question, Clawdline lance ceci : votre propre programme, avec les détails dans son environnement. Cela s'écrit dans le fichier de configuration et non ici, parce que c'est un argv et pas une ligne de commande — un chemin avec une espace dedans doit rester un seul chemin."
    let settingsRemote = "À distance"
    let settingsRemoteServe = "Laisser un navigateur ou votre téléphone voir vos sessions"
    let settingsRemoteHint = "Désactivé, rien en dehors de ce Mac n'atteint quoi que ce soit. Activé, la liste des sessions est servie sur 127.0.0.1 : pour un navigateur ici, pour un téléphone au bout d'un tunnel, pour un script. Ce que cela livre, ce sont des noms de dépôts, des branches et des titres de tâches, et c'est pour ça que ça reste désactivé tant que vous n'avez pas dit le contraire."
    let settingsRemoteDevices = "Appareils jumelés"
    let settingsRemoteNoDevices = "Aucun pour l'instant — rien en dehors de ce Mac ne peut rien lire"
    let settingsRemoteRevokeAll = "Tout déconnecter"
    let settingsRemoteOpen = "Ouvrir dans un navigateur"
    let pairingIgnore = "Ignorer"
    func pairingAsks(_ device: String) -> String { "\(device) veut se jumeler à ce Mac" }
    func pairingCode(_ code: String) -> String {
        """
        Saisissez ce code sur cet appareil :

        \(code)

        Il est valable deux minutes. Si vous ne venez pas de le demander, ignorez-le — sans ce \
        code, celui qui a demandé ne peut pas aller au bout.
        """
    }
    let settingsTunnel = "Joindre ce Mac depuis n'importe où"
    let settingsTunnelQuick = "Une adresse générée"
    let settingsTunnelNamed = "Mon propre domaine"
    let settingsTunnelHostname = "Nom d'hôte"
    let settingsTunnelHint = "Ouvre une connexion sortante via cloudflared — aucune redirection de port, rien à l'écoute sur votre réseau. Ne démarre pas tant qu'aucun appareil n'est jumelé, parce que derrière le tunnel il y a le nom de chaque dépôt et le titre de chaque tâche de ce Mac."
    let settingsRemoteWrite = "Laisser un appareil jumelé écrire dans une session"
    let settingsRemoteWriteHint = "Désactivé, un appareil jumelé ne peut que lire. Activé, il peut envoyer du texte dans une session et en ouvrir de nouvelles — ce qui exécute du code sur ce Mac, puisque c'est ce que fait Claude Code. Ce n'est pas la même décision que celle du dessus, donc ce n'est pas le même interrupteur."
    let settingsRemotePhone = "Jumeler un téléphone…"
    let settingsRemotePhoneHint = "Affiche un code à scanner. Il porte une clé bien à lui : une photo de ce code, c'est un appareil que vous voyez dans cette liste et que vous pouvez retirer — pas la clé de ce Mac."
    let pairingScanTitle = "Scannez ceci avec le téléphone"
    let pushWaiting = "attend une réponse"
    let pushTest = "Notification de test. Tout est bien branché."
    let pushFinished = "a terminé une longue tâche"
    let pushDeployOk = "le déploiement a réussi"
    let pushDeployFail = "le déploiement a échoué"
    let settingsPushFinish = "Prévenir quand une longue tâche se termine"
    let settingsPushFinishHint = "Seulement au-delà de deux minutes."
    let settingsPushDeploy = "Prévenir quand un déploiement se termine"
    let settingsPushDeployHint = "Réussite comme échec."
    let settingsOrchestrator = "Confier du travail"
    let settingsOrchestratorEnabled = "Laisser une session confier du travail à une autre"
    let settingsOrchestratorEnabledHint = "Une session munie de la skill clawdline peut ouvrir un onglet, y taper les consignes et être prévenue quand c'est fini. Désactivé, toute demande est refusée ; rien de ce qui tourne déjà n'est arrêté."
    let settingsOrchestratorMax = "Sessions filles en même temps"
    let settingsOrchestratorMaxHint = "Trois par défaut. Chacune est un onglet de terminal avec un assistant qui travaille dedans."
    let settingsOrchestratorNotify = "Prévenir la session qui a demandé"
    let settingsOrchestratorNotifyHint = "Une ligne tapée chez elle quand sa tâche se termine."
    let settingsOrchestratorClose = "Quand une session fille rend compte"
    let settingsOrchestratorCloseHint = "Son onglet est fermé une fois qu'elle a rendu compte ; celui d'une session expirée reste là, pour que vous puissiez le lire."
    let settingsOrchestratorCloseNow = "Fermer l'onglet tout de suite"
    let settingsOrchestratorCloseLinger = "Le fermer au bout de trois minutes"
    let settingsOrchestratorCloseKeep = "Le laisser ouvert"
    func settingsSeconds(_ value: Double) -> String { String(format: "%.1f s", value) }

    let webConnLive = "en direct"
    let webConnConnecting = "connexion"
    let webConnRetrying = "réessai dans {n} s"
    let webConnOffline = "hors ligne"
    let webConnLocked = "non jumelé"
    let webConnTipLive = "Flux en direct depuis l'app"
    let webConnTipLocked = "Ce navigateur n'a pas été jumelé avec le Mac"
    let webConnTipDown = "Pas connecté — cliquez pour réessayer"

    let webCountWorking = "{n} en cours"
    let webCountWaiting = "{n} en attente"
    let webCountUnreadable = "{n} illisibles"
    let webCountQuietOne = "{n} session, tout est calme"
    let webCountQuietMany = "{n} sessions, tout est calme"
    let webCountNone = "aucune session"

    let webFilterPlaceholder = "Filtrer par tâche, projet ou tty"
    let webFilterLabel = "Filtrer les sessions"
    let webListLabel = "Sessions Claude Code"
    let webPull = "Tirez pour actualiser"
    let webPullRelease = "Lâchez pour actualiser"
    let webPullBusy = "Actualisation…"
    let webEmptyFilterTitle = "Rien ne correspond à « {q} »"
    let webEmptyFilterHint = "Esc efface le filtre"
    let webEmptyLockedTitle = "Cet appareil n'est pas jumelé"
    let webEmptyLockedHint = "L'app a répondu 401 — jumelez-le depuis Clawdline sur le Mac"
    let webEmptyNoneHint = "Lancez-en une dans un terminal et elle apparaît ici"
    let webEmptyWaitTitle = "En attente de l'app"
    let webEmptyWaitHint = "Rien n'est encore arrivé sur le flux"
    let webStateUnreadable = "écran illisible"
    let webStateWorking = "en cours"

    let webBack = "Sessions"
    let webBackLabel = "Retour à la liste des sessions"
    let webNoSessionOpen = "Aucune session ouverte"
    let webOrderTip = "Inverser la transcription (r)"
    let webShowOnMac = "Afficher sur le Mac"
    let webShowOnMacTip = "Mettre le terminal de cette session au premier plan sur le Mac"
    let webShowOnMacOff = "Le serveur annonce write: false — rien ne peut encore être envoyé"
    let webShowOnMacAsked = "Demandé au Mac de le mettre au premier plan"
    let webSessionActions = "Actions de la session"
    let webSessionGit = "Modifications Git"
    let webGitTitle = "Modifications Git"
    let webGitClean = "Arbre de travail propre"
    let webGitNotRepo = "Ce n’est pas un dépôt Git"
    let webGitFailed = "Impossible de lire les modifications Git"
    let webGitRefresh = "Actualiser"
    let webGitClose = "Fermer"
    let webGitStaged = "Indexé"
    let webGitUnstaged = "Non indexé"
    let webGitUntracked = "Non suivi"
    let webGitConflict = "Conflit"
    let webEndSession = "Fermer la session"
    let webConfirmActionTitle = "Exécuter {action} ?"
    let webConfirmActionSay = "Cela envoie {action} à la session actuelle."
    let webConfirmEndTitle = "Fermer cette session ?"
    let webConfirmEndSay = "L’assistant va quitter, puis son onglet de terminal se fermera."
    let webCancel = "Annuler"
    let webConfirm = "Confirmer"
    let webPickSession = "Choisissez une session à gauche."
    let webReading = "Lecture…"
    let webLoading = "Chargement…"
    let webTranscriptFailed = "Impossible de lire la transcription"
    let webWhoYou = "vous"
    let webWhoTool = "outil"
    let webSteps = "{n} étapes"
    let webJustNow = "à l'instant"
    let webMinutesAgo = "il y a {n} min"

    let webSend = "Envoyer"
    let webAttach = "Joindre une image"
    let webRemoveShot = "Retirer {name}"
    let webWriteOpen = "Ouvrez une session pour y écrire."
    let webWriteOff = "*L'envoi est désactivé* — le serveur annonce `write: false`. La case est branchée ; elle s'allumera toute seule quand ça changera."
    let webShotsOnlyPictures = "Seules des images peuvent accompagner un message"
    let webShotsTooMany = "{n} images au maximum dans un même message"
    let webShotTooBig = "Cette image est trop lourde à envoyer, même réduite"
    let webShotsTooBig = "Ces images sont trop lourdes pour partir ensemble"
    let webShotUnreadable = "Cette image n'a pas pu être lue"
    let webShotNeedsSession = "Ouvrez une session pour y envoyer une image"

    let webHintMove = "naviguer"
    let webHintOpen = "ouvrir"
    let webHintFilter = "filtrer"
    let webHintPane = "volet"

    let webKeysLabel = "Raccourcis clavier"
    let webKeysTitle = "Clavier"
    let webKeysMove = "Parcourir la liste — `j` et `k` font pareil"
    let webKeysOpen = "Ouvrir la session sélectionnée"
    let webKeysFilter = "Filtrer la liste"
    let webKeysEscape = "Effacer le filtre, puis revenir en arrière"
    let webKeysList = "Aller à la liste des sessions"
    let webKeysPane = "Afficher ou masquer la transcription"
    let webKeysEnds = "Haut ou bas de la transcription"
    let webKeysReverse = "Inverser l'ordre de la transcription"
    let webKeysThis = "Cette carte"
    let webKeysFoot = "Ce qui est tapé dans une case de texte reste dans la case — les raccourcis se retirent pendant que vous écrivez."

    let webDoorLabel = "Jumeler ce navigateur"
    let webDoorAskLede = "Ce navigateur n'est pas encore admis."
    let webDoorAskFine = "Demandez le jumelage et un code à six chiffres apparaît *sur le Mac* — il n'est volontairement pas dans la réponse envoyée à cette page. Seul quelqu'un devant cette machine peut aller au bout, et c'est justement le principe, pas l'obstacle."
    let webDoorName = "Appelez cet appareil"
    let webDoorAsk = "Demander le jumelage"
    let webDoorToPassword = "Utiliser plutôt un mot de passe"
    let webDoorCodeLede = "Regardez le Mac."
    let webDoorCodeFine = "Clawdline affiche six chiffres pendant encore {left}. Saisissez-les ici."
    let webDoorTwoMinutes = "deux minutes"
    let webDoorDigit = "Chiffre {n}"
    let webDoorConfirm = "Jumeler cet appareil"
    let webDoorRestart = "Recommencer"
    let webDoorPasswordLede = "Connectez-vous avec le mot de passe."
    let webDoorPasswordFine = "Celui défini dans Clawdline sur le Mac, dans Réglages → À distance. Si aucun n'a été défini, c'est le jumelage qui ouvre."
    let webDoorPassword = "Mot de passe"
    let webDoorPasswordGo = "Se connecter"
    let webDoorToPair = "Utiliser plutôt un code de jumelage"
    let webDoorAsking = "Demande au Mac…"
    let webDoorAskFailed = "Impossible de demander au Mac."
    let webDoorRateLimited = "Chaque demande fait apparaître une alerte sur le Mac : il n'y en a donc que trois toutes les dix minutes."
    let webDoorSixDigits = "Six chiffres."
    let webDoorChecking = "Vérification…"
    let webDoorFinished = "Ce jumelage est terminé — cinq codes faux. Redemandez quand vous serez devant le Mac."
    let webDoorWrongCode = "Ce code n'est pas le bon."
    let webDoorNeedPassword = "Le mot de passe, d'abord."
    let webDoorWrongPassword = "Ce n'est pas le mot de passe."
    let webDoorExpired = "Ce code a expiré. Redemandez et un nouveau apparaît sur le Mac."
    let webDoorPaired = "Jumelé — ce navigateur est entré"

    let webOffline = "Impossible de joindre Clawdline. Tourne-t-il toujours sur le Mac ?"
    let webNotJSON = "Le serveur a envoyé autre chose que du JSON"
    let webRequestFailed = "Échec de la requête"

    let webNotifyGo = "Me prévenir"
    let webNotifyAsking = "Demande…"
    let webNotifyStop = "Arrêter"
    let webNotifyStopping = "Arrêt…"
    let webNotifyOff = "quand une session attend une réponse"
    let webNotifyOn = "Cet appareil est abonné. Ce dont il est prévenu se règle sur le Mac."
    let webNotifyBlocked = "Les notifications sont bloquées pour ce site. Cet interrupteur est dans les réglages du navigateur, pas ici."
    let webNotifyUnsupported = "Ce navigateur ne sait pas afficher de notifications."
    let webNotifyHomeScreen = "Ajoutez clawdline à votre écran d'accueil et ouvrez-le depuis là — iOS n'envoie de notifications qu'à une app qui y habite."
    let webNotifyOnFailed = "Impossible d'activer les notifications"
    let webNotifyOffFailed = "Impossible de désactiver les notifications"

    let webSettings = "Réglages"
    let webSettingsNotify = "Notifications"
    let webSettingsAssistantIcons = "Icônes de l’assistant"
    let webSettingsAssistantIconsSay = "Afficher le symbole de Claude ou Codex avant son nom dans la conversation."
    let webSettingsAssistantIconsShow = "Afficher les icônes"
    let webSettingsVersion = "Version {v}"
    let webClose = "Fermer"
    let webNotifySheetOff = "Cet appareil n'est pas prévenu quand une session attend."
    let webNotifyTest = "Envoyer un test"
    let webNotifyTestSent = "Envoyé — ça devrait arriver sur cet appareil dans un instant."
    let webNotifyTestNone = "Le Mac n'a aucun abonnement pour cet appareil. Désactivez puis réactivez les notifications, et ce navigateur en enregistrera un tout neuf."
    let webNotifyTestFailed = "Impossible d'envoyer une notification de test"
    let webSending = "Envoi…"
    let webSendTip = "Entrée envoie · Maj-Entrée passe à la ligne"
    let webStart = "Lancer une session"
    let webStartLabel = "Lancer une session dans un projet"
    let webStartPick = "Où faut-il la lancer ?"
    let webStartWith = "Avec quoi la lancer ?"
    let webStartEmpty = "Nulle part où lancer pour l'instant. Faites tourner Claude Code une fois sur le Mac et ce sera là."
    let webStartFilter = "Filtrer les projets"
    let webStarting = "Ouverture d'un onglet…"
    let webStartWaiting = "C'est lancé. On attend qu'elle apparaisse…"
    let webStartSlow = "L'onglet est ouvert, mais la session ne s'est pas signalée. Jetez un œil au Mac."
    let webStartFailed = "Ça n'a pas pu être lancé."
    let webStartGone = "Ce projet n'est plus sur le Mac."
    let webStartTerminalClosed = "{app} ne tourne pas sur le Mac. Ouvrez-le là-bas et réessayez."
    let webStartTerminalUnsupported = "D'ici, on ne peut pas lancer de session dans {app}. Faites-y tourner tmux et ça marche."
    let webStartOff = "Le lancement de sessions est désactivé. C'est Réglages → À distance, sur le Mac, qui l'active."
    let webLinks = "Liens"
    let webLinksTip = "Où ce projet peut s'ouvrir"
    let webLinksPick = "Tout ce dont ce projet a une adresse."
    let webLinksEmpty = "Ce projet n'a rien qui ait une adresse — pas de site, pas de déploiement, et aucun serveur qui tourne."
    let webLinksFailed = "Impossible de lire les liens de ce projet."
    let webLinksLocal = "Sur le réseau du Mac uniquement. Ça ne s'ouvrira pas d'ici."
    let webLinksFile = "Un fichier sur le Mac. Il s'ouvre là-bas, pas dans ce navigateur."
    let webLinksCopy = "Copier le chemin"
    let webLinksCopied = "Copié."
    let webLinksCopyFailed = "Ce navigateur n'a pas laissé la page copier ça."
    let webLinkOk = "ok"
    let webLinkFail = "en échec"
    let webLinkDown = "éteint"
    let webLinkRunning = "en cours"
    let webSessionInfo = "Infos de la session"
    let webInfoTitle = "À propos de cette session"
    let webInfoSession = "Cette session"
    let webInfoAssistant = "Assistant"
    let webInfoModel = "Modèle"
    let webInfoSessionId = "Identifiant de session"
    let webInfoDirectory = "Dossier"
    let webInfoRunningFor = "En cours depuis"
    let webInfoUsage = "Consommation de tokens"
    let webInfoInput = "Entrée"
    let webInfoOutput = "Sortie"
    let webInfoCacheRead = "Cache lu"
    let webInfoCacheWrite = "Cache écrit"
    let webInfoTotal = "Total"
    let webInfoCost = "Coût estimé"
    let webInfoNoUsage = "Aucune transcription trouvée pour cette session pour l'instant."
    let webInfoLimits = "Quotas du forfait"
    let webInfoLimitHit = "quota atteint"
    let webInfoResets = "remise à zéro {when}"
    let webInfoUnknown = "inconnu"
    let webInfoFiles = "Fichiers"
    let webInfoBranch = "Branche"
    let webInfoStaged = "Indexés"
    let webInfoUnstaged = "Modifiés"
    let webInfoUntracked = "Non suivis"
    let webInfoConflict = "Conflits"
    let webInfoClean = "Rien qui ne soit pas commité."
    let webInfoNotRepo = "Ce n'est pas un dépôt git."
    let webInfoDeploy = "Dernier déploiement"
    let webInfoNoDeploy = "Aucun déploiement enregistré pour ce projet."
    let webInfoFailed = "Impossible de lire les infos de cette session."
    let webInfoRefresh = "Actualiser"
    let webInfoTokens = "jetons"
    let webInfoSwitchModel = "Changer de modèle"
    let webInfoModelOther = "un autre modèle…"
    let webInfoModelSent = "/model {model} envoyé. La carte l'affichera après la prochaine réponse."
    let webInfoModelBusy = "Le changement attend que la session soit inactive."
    let webInfoLimitsClaude = "Claude Code ne note une fenêtre qu'une fois épuisée ; d'ici là, rien n'est connu."
    let webInfoCopied = "Identifiant de session copié."
    let webInfoAsOf = "au {when}"
    let webInfoWhyUnknown = "Pourquoi c'est inconnu, et comment obtenir les chiffres"
    let webSettingsOrder = "Transcription"
    let webSettingsOrderSay = "Par quel bout commencer à lire une transcription. Ça vaut pour toutes les sessions, et `r` fait pareil au clavier."
    let webAskLabel = "a demandé"
    let webAskAny = "Autant que vous voulez"
    let webWaitingTitle = "Cette session attend une réponse"
    let webWaitingSay = "Claude Code affiche un menu sur le Mac. Clawdline ne sait pas encore lire un menu d'ici : les choix ne sont que sur cet écran-là."
    let webWaitingSend = "*Envoyer d'ici n'écrira pas votre réponse dans le menu* — cela valide l'option que le menu a sous le curseur, qui est rarement celle que vous vouliez. Celle-ci, répondez-y sur le Mac."
    let webMenuSay = "Touche une réponse et elle part directement dans la session."
    let webMenuHighlighted = "sélectionnée"
    let webMenuSent = "Réponse envoyée."
    let webAgents = "Agents en arrière-plan"
    let webAgentsCount = "{n} en cours"
    let webAgentDone = "terminé"
    let webAgentFailed = "échoué"
    let agentRunning = "en cours"
    let agentTools = "{n} outils"
    let agentEmpty = "Cet agent n'a encore rien écrit."
    let agentBack = "Conversation"
    let webAgentOpen = "Voir ce qu'a fait cet agent"
    let webTaskRoot = "Parent"
    let webTaskChild = "Enfant"
    let webTaskTasks = "Tâches"
    let webTaskDone = "terminé"
    let webTaskFailed = "échoué"
    let webTaskRunning = "en cours"
    let webStale = "Clawdline a été reconstruit sur le Mac. Cette page est l'ancienne."
    let webStaleGo = "Recharger"

    let menuOpen = "Ouvrir la barre"
    let menuReveal = "Aller à l'onglet cible"
    let menuMascot = "Mascotte"
    let menuLogin = "Ouvrir à la connexion"
    let menuEditConfig = "Réglages…"
    let menuReload = "Recharger la configuration"
    let menuQuit = "Quitter Clawdline"
    let menuNoTarget = "(pas encore détecté)"

    func hotkeyFailedTitle(_ combo: String) -> String { "Impossible d'enregistrer \(combo)" }
    func hotkeyFailedBody(_ configPath: String) -> String {
        """
        Une autre app l'utilise sans doute déjà — Spotlight, un changeur de clavier, \
        BetterTouchTool, etc.

        Choisissez-en un autre : modifiez « hotkey » dans \(configPath), puis choisissez \
        « Recharger la configuration » dans la barre des menus.

        En attendant, le ✳ de la barre des menus ouvre toujours la barre.
        """
    }
    let loginFailed = "Impossible de configurer l'ouverture à la connexion"
}
