import Foundation

struct Indonesian: Copy {
    let placeholder = "Tulis ke Claude Code…"

    let hintSend = "kirim"
    let hintNewline = "baris baru"
    let hintSwitch = "ganti"
    let hintList = "daftar"
    let hintMascot = "maskot"
    let hintOutput = "keluaran"
    let hintFullscreen = "layar penuh"
    let hintKeys = "tombol"
    let hintTextSize = "ukuran teks"
    let hintOrder = "balik urutan"
    let hintVoice = "dikte"
    func voiceListening(onDevice: Bool) -> String {
        onDevice ? "Mendengarkan di Mac ini — tekan lagi untuk berhenti"
                 : "Mendengarkan — bahasa ini ditranskripsi oleh Apple, bukan di Mac ini"
    }
    let voiceNoPermission = "Dikte memerlukan izin mikrofon dan pengenalan suara"
    let voiceUnavailable = "Dikte sedang tidak tersedia"
    func voiceTranscribing(seconds: Double) -> String {
        String(format: "Whisper sedang membacanya ulang… %.1f dtk", seconds)
    }
    let whisperMissing = "Whisper belum terpasang — lihat docs/whisper.md"
    let whisperNothingHeard = "Tidak terdengar apa pun"
    func dictationStatus(_ status: Whisper.Status) -> String {
        switch status {
        case .ready(let model): return "Dikte: Apple, lalu Whisper (\(model))"
        case .noBinary: return "Dikte: hanya Apple — tidak ada whisper-cli"
        case .noModel: return "Dikte: hanya Apple — whisper-cli ada, modelnya belum"
        }
    }
    func voiceListeningWhisper() -> String {
        "Mendengarkan — Whisper membaca ulang begitu kamu berhenti"
    }

    let scanning = "Mencari…"
    let noSession = "Tidak ada sesi Claude Code yang ditemukan"
    let nothingToSend = "Tidak ada tujuan — jalankan dulu Claude Code di terminal"
    let sendFailed = "Gagal mengirim"
    let itermSilent = "iTerm2 tidak merespons"
    let itermBusy = "iTerm2 sedang menunggu dialog — jawab di Mac"
    let scriptMissing = "iterm.js tidak ada — bundel aplikasi rusak?"
    let cannotList = "Tidak bisa membaca sesi iTerm2"
    let noOutput = "Belum ada yang bisa dibaca dari sesi ini."
    let imageExpired = "Gambar kedaluwarsa"
    let imagePreview = "Pratinjau gambar"
    let imageClose = "Tutup pratinjau"
    let imageTooLarge = "Terlalu besar untuk dikirim ({mb} MB)"
    let imageUnavailable = "Gambar tidak sampai"
    func outputSize(_ pt: Int) -> String { "Ukuran teks keluaran \(pt) pt — ⌘J untuk melihat" }
    func foldedTools(_ count: Int) -> String { "\(count) langkah" }
    func outputOrder(newestFirst: Bool) -> String {
        newestFirst ? "Terbaru di atas" : "Terlama di atas"
    }
    func backlogNow(_ count: Int) -> String { "sekarang \(count)" }
    func dropped(_ count: Int) -> String {
        count == 1 ? "Path ditambahkan — Claude Code yang membacanya" : "\(count) path ditambahkan"
    }
    func stackConfirm(_ command: String) -> String { "Tekan lagi untuk menjalankan:  \(command)" }
    let hintStacks = "server"
    func stackTip(up: Int, total: Int) -> String { "\(up) dari \(total) server aktif — ⌘S untuk daftarnya" }
    let stackTipUnknown = "Proyek ini punya server, tetapi perintah status-nya belum dipercaya — ⌘S"
    let stackUntrusted = "belum dipercaya"
    let stackExit = "keluar"
    let stackActionStart = "mulai"
    let stackActionRestart = "mulai ulang"
    let stackActionStop = "hentikan"
    let stackActionLogs = "log"
    let stackLogAll = "semua"
    let stackLogBack = "transkrip"
    let stackActionAllow = "izinkan"
    let stackActionAgain = "tekan lagi"
    func sessionTip(index: Int, total: Int) -> String { "Sesi \(index) dari \(total) — ⌘K untuk berpindah" }
    let sessionWaiting = "menunggu jawabanmu"
    let sessionAgents = "{n} di latar belakang"
    let sessionShellOne = "1 shell berjalan"
    let sessionShellMany = "{n} shell berjalan"
    let sessionWaitedOnByOne = "1 menunggumu"
    let sessionWaitedOnByMany = "{n} menunggumu"
    let islandDone = "selesai"
    let islandAllSessions = "Semua sesi…"
    func statusWaiting(_ labels: [String]) -> String {
        labels.count == 1 ? "\(labels[0]) menunggu jawabanmu"
                          : "\(labels.count) sesi menunggu jawabanmu"
    }
    func statusWorking(_ count: Int) -> String { "\(count) sedang berjalan" }

    let settingsTitle = "Pengaturan Clawdline"
    let settingsGeneral = "Umum"
    let settingsBar = "Bilah"
    let settingsReading = "Membaca"
    let settingsVoice = "Dikte"
    let settingsHotkey = "Pintasan"
    let settingsRecording = "Tekan tombol…"
    let settingsScope = "Aktif di"
    let settingsScopeGlobal = "Di semua aplikasi"
    let settingsScopeHint = "Kosong berarti di mana saja, jadi mengeluarkan yang terakhir akan menyalakan sakelar di atas — dan mematikannya lagi mengembalikan daftarnya. Berkas konfigurasi menyimpannya sebagai bundle id, dan daftar yang disunting tangan tetap jalan."
    let settingsSessionTerminal = "Sesi baru dibuka di"
    let settingsSessionTerminalHint = "Bukan hal yang sama dengan di mana pintasan berlaku. Otomatis memakai iTerm2 kalau sedang terbuka dan tmux kalau tidak; iTerm2 meminta iTerm2 itu sendiri, jadi server tmux yang jalan di sebelahnya bukan jawaban dan iTerm2 yang tertutup berarti penolakan; tmux menaruh sesi di server tmux meski iTerm2 sedang jalan. Berlaku untuk sesi berikutnya, tanpa perlu memulai ulang."
    let settingsScopeAdd = "Tambah aplikasi…"
    let settingsScopeChoose = "Pilih aplikasi…"
    let settingsScopeRunning = "Terbuka sekarang"
    let settingsScopeRemove = "Keluarkan"
    let settingsLanguage = "Bahasa"
    let settingsReopen = "Bilahnya datang dan pergi bersama terminal"
    let settingsReopenHint = "Berpindah menjauh dari terminal menyimpan bilahnya, dan kembali ke terminal memunculkannya lagi. Esc-lah yang berarti sudah selesai."
    let settingsFollow = "Terminal menampilkan apa pun yang sedang dibidik bilahnya"
    let settingsFollowHint = "Ia memilih tab sesi itu. Ia tidak membawa terminal ke depan — kalau tidak, setiap kali Tab ditekan papan ketik akan keluar dari kotak yang sedang kamu tulis."
    let settingsCodexAutoName = "Namai sesi baru"
    let settingsCodexAutoNameHint = "Menjalankan satu turn kecil dengan asisten pilihanmu untuk setiap sesi tanpa nama. Menggunakan permintaan pertama, memakai kuota asisten itu, dan tidak mengganti nama pilihanmu."
    let settingsNotch = "Tinggal di poni layar"
    let settingsNotchHint = "Karakter di rumah kamera. Mati berarti mati — tidak digambar, tidak ada jendela."
    let settingsPosition = "Tinggi di layar"
    let settingsWidth = "Lebar"
    let settingsOpacity = "Opasitas kartu"
    let settingsShow = "Tampilkan"
    let settingsPaneHeight = "Tinggi panel"
    let settingsTextSize = "Ukuran teks"
    let settingsPaneFont = "Font panel"
    let settingsBlur = "Buram di belakang"
    let settingsNewestFirst = "Terbaru dulu"
    let settingsEngine = "Pengenal suara"
    let settingsSettle = "Jeda mengakhiri kalimat"
    let settingsStop = "Sunyi mengakhiri sesi"
    let settingsAuto = "Otomatis"
    let settingsTranscript = "Transkrip"
    let settingsTerminal = "Terminal"
    let settingsOff = "Mati"
    let settingsHooks = "Hook Claude Code"
    let settingsHooksHint = "Setelah dipasang, Claude Code memberi tahu saat sebuah giliran dimulai, selesai, atau menunggu jawaban — bukan menunggu Clawdline melihatnya pada pemeriksaan berikutnya. Semuanya tetap dibaca dari layar; ini hanya menentukan secepat apa."
    let settingsHooksInstall = "Pasang"
    let settingsHooksRemove = "Lepas"
    let settingsHooksOff = "Belum dipasang — semua dibaca dari layar"
    let settingsHooksOn = "Terpasang — belum ada sesi yang melapor"
    let settingsHooksLive = "Terpasang, dan sesi sedang melapor"
    let settingsStateHook = "Saat sebuah sesi berganti keadaan"
    let settingsStateHookHint = "Setiap kali sebuah sesi mulai bekerja, selesai, atau menanyakan sesuatu kepadamu, Clawdline menjalankan ini: programmu sendiri, dengan rinciannya di lingkungan program itu. Ditulis di berkas konfigurasi dan bukan di sini karena ini argv, bukan baris perintah — path yang ada spasinya harus tetap satu path."
    let settingsRemote = "Akses jarak jauh"
    let settingsRemoteServe = "Biarkan peramban atau ponselmu melihat sesimu"
    let settingsRemoteHint = "Mati, tidak ada apa pun di luar Mac ini yang bisa menjangkau apa pun. Menyala, daftar sesi disajikan di 127.0.0.1 — untuk peramban di sini, untuk ponsel lewat terowongan, untuk skrip. Yang diserahkan adalah nama repositori, branch, dan judul tugas, dan karena itulah ia tetap mati sampai kamu berkata lain."
    let settingsRemoteDevices = "Perangkat berpasangan"
    let settingsRemoteNoDevices = "Belum ada — tidak ada apa pun di luar Mac ini yang bisa membaca apa pun"
    let settingsRemoteRevokeAll = "Putuskan semua"
    let settingsRemoteOpen = "Buka di peramban"
    let pairingIgnore = "Abaikan"
    func pairingAsks(_ device: String) -> String { "\(device) ingin berpasangan dengan Mac ini" }
    func pairingCode(_ code: String) -> String {
        """
        Ketik kode ini di perangkat itu:

        \(code)

        Berlaku dua menit. Kalau bukan kamu yang barusan meminta, abaikan saja — tanpa kode \
        ini yang meminta tidak bisa menyelesaikannya.
        """
    }
    let settingsTunnel = "Jangkau Mac ini dari mana saja"
    let settingsTunnelQuick = "Alamat buatan otomatis"
    let settingsTunnelNamed = "Domain milikku"
    let settingsTunnelHostname = "Nama host"
    let settingsTunnelHint = "Membuka koneksi keluar lewat cloudflared — tanpa penerusan port, tidak ada yang mendengarkan di jaringanmu. Tidak akan mulai sebelum ada satu perangkat berpasangan, karena di balik terowongan itu ada setiap nama repositori dan setiap judul tugas di Mac ini."
    let settingsRemoteWrite = "Biarkan perangkat berpasangan menulis ke dalam sesi"
    let settingsRemoteWriteHint = "Mati, perangkat berpasangan hanya bisa membaca. Menyala, ia bisa mengirim teks ke dalam sesi dan memulai sesi baru — dan itu menjalankan kode di Mac ini, karena memang itu yang dikerjakan Claude Code. Ini keputusan yang lain dari yang di atas, jadi sakelarnya juga lain."
    let settingsRemotePhone = "Pasangkan ponsel…"
    let settingsRemotePhoneHint = "Menampilkan kode untuk dipindai. Kode itu membawa kuncinya sendiri, jadi foto kode itu cuma satu perangkat yang terlihat di daftar ini dan bisa kamu cabut lagi — bukan kunci Mac ini sendiri."
    let pairingScanTitle = "Pindai ini dengan ponsel"
    let pushWaiting = "menunggu jawaban"
    let pushTest = "Ini notifikasi percobaan. Semuanya sudah tersambung."
    let pushDelivered = "melapor sudah menyerahkan hasil dan menunggu kamu"
    let pushDeployOk = "berhasil di-deploy"
    let pushDeployFail = "gagal di-deploy"
    func pushChildWaiting(minutes: Int?) -> String {
        guard let minutes else { return "punya sesi anak yang menunggu jawaban" }
        return "punya sesi anak yang menunggu jawaban — sisa \(minutes) mnt"
    }
    func pushBatchDone(done: Int, failed: Int) -> String {
        let all = "menyelesaikan \(done) tugas"
        return failed == 0 ? all : "\(all), \(failed) gagal"
    }
    let settingsPushDelivery = "Beri tahu kalau sebuah sesi melapor sudah menyerahkan hasil"
    let settingsPushDeliveryHint = "Sekali per laporan; laporan yang sama diulang tidak berbunyi."
    let settingsPushFanout = "Beri tahu kalau sekumpulan tugas selesai"
    let settingsPushFanoutHint = "Satu notifikasi untuk seluruh kumpulan, dengan jumlah yang gagal."
    let settingsSmartNotifications = "Notifikasi pintar"
    let settingsSmartNotificationsHint = "Haiku merangkum pekerjaan yang selesai dalam satu kalimat. Jika gagal, notifikasi biasa tetap dikirim."
    func pushCoalesced(count: Int) -> String { "\(count) pekerjaan selesai bersamaan" }
    let settingsSmartHealthIdle = "Belum ada notifikasi pintar yang dicoba."
    func settingsSmartHealth(attempts: Int, successes: Int) -> String {
        "\(successes) dari \(attempts) percobaan mengirim kalimat model."
    }
    func settingsSmartHealthFailure(reason: String, time: String) -> String {
        "Terakhir kembali ke notifikasi biasa pukul \(time): \(reason)."
    }
    func settingsSmartTimeout(seconds: Int) -> String {
        "Claude melewati batas \(seconds) detik dan dihentikan"
    }
    let settingsSmartQueueFull = "lebih banyak pekerjaan selesai daripada daya tampung antrean"
    let settingsSmartModelFailed = "Claude tidak mengembalikan hasil yang bisa dipakai"
    let settingsSmartNoSource = "tidak ada yang bisa diringkas"
    let settingsSmartMissing = "berkas claude tidak ditemukan"
    let settingsPushDeploy = "Beri tahu kalau deploy selesai"
    let settingsPushDeployHint = "Baik berhasil maupun gagal."
    let settingsAgentNotify = "Izinkan agen mengirim notifikasinya sendiri"
    let settingsAgentNotifyNote = "Hanya mengatur isi yang dikirim agen atas inisiatifnya sendiri; notifikasi selesai, deploy, dan lainnya tidak berubah."
    let settingsOrchestrator = "Menitipkan pekerjaan"
    let settingsOrchestratorEnabled = "Biarkan satu sesi menitipkan pekerjaan ke sesi lain"
    let settingsOrchestratorEnabledHint = "Sesi yang punya skill clawdline bisa membuka tab baru, mengetikkan instruksinya, lalu diberi tahu setelah pekerjaannya selesai. Kalau mati, setiap permintaan ditolak; yang sudah berjalan tidak dihentikan."
    let settingsOrchestratorMax = "Sesi anak sekaligus"
    let settingsOrchestratorMaxHint = "Lima secara bawaan, dihitung per sesi dan bukan per Mac. Masing-masing satu tab terminal dengan satu asisten bekerja di dalamnya."
    let settingsOrchestratorPermission = "Sejauh mana sesi anak boleh jalan"
    let settingsOrchestratorPermissionHint = "Tidak ada yang menonton tab sesi anak, jadi yang berhenti menunggu persetujuan akan berhenti sampai waktunya habis — dan seluruh pekerjaan sesi yang ditugaskan adalah menjalankan perintah dan menulis berkas, sehingga apa pun selain pilihan terakhir akan menghentikannya di suatu tempat. Sebuah tugas boleh meminta lebih sedikit dari ini, tidak pernah lebih."
    let settingsOrchestratorPermissionAsk = "Tanya sebelum tiap langkah"
    let settingsOrchestratorPermissionEdits = "Menulis berkas tanpa bertanya"
    let settingsOrchestratorPermissionFull = "Jangan pernah bertanya"
    let settingsOrchestratorNotify = "Beri tahu sesi yang meminta"
    let settingsOrchestratorNotifyHint = "Satu baris diketikkan kembali ke sana saat tugasnya selesai."
    let settingsOrchestratorClose = "Saat sesi anak melapor"
    let settingsOrchestratorCloseHint = "Tabnya ditutup setelah melapor — yang kehabisan waktu dibiarkan terbuka supaya bisa kamu baca."
    let settingsOrchestratorCloseNow = "Tutup tabnya langsung"
    let settingsOrchestratorCloseLinger = "Tutup setelah tiga menit"
    let settingsOrchestratorCloseKeep = "Biarkan terbuka"
    let settingsOrchestratorPolicy = "Cara pekerjaan dibagikan"
    let settingsOrchestratorPolicyHint = "Aturan yang dibaca Clawdline setiap kali menugaskan dan disalin ke pengarahan setiap sesi anak yang boleh menugaskan lagi: asisten mana, model mana, bentuk grafnya seperti apa. Kosong berarti tidak ada aturan."
    let settingsOrchestratorPolicyEdit = "Ubah aturan"
    func settingsOrchestratorPolicyOn(_ lines: Int) -> String { return "Berlaku — \(lines) baris" }
    let settingsOrchestratorPolicyOff = "Tidak ada aturan — setiap penugasan diputuskan sendiri oleh yang menugaskan"
    let settingsSchedules = "Jadwal"
    let settingsSchedulesEmpty = "Belum ada jadwal. Tombol Jadwal baru di bawah membuat yang pertama."
    let settingsScheduleNew = "Jadwal baru"
    let settingsScheduleEdit = "Ubah"
    let settingsScheduleSave = "Simpan"
    let settingsScheduleDelete = "Hapus"
    let settingsScheduleRun = "Jalankan sekarang"
    let settingsScheduleReveal = "Tampilkan di Finder"
    let settingsSchedulesFolder = "Buka folder schedules"
    let settingsScheduleNext = "Berikutnya"
    let settingsScheduleLast = "Terakhir"
    let settingsScheduleNever = "Belum pernah dijalankan"
    let settingsScheduleStarted = "Mulai dijalankan."
    let settingsScheduleActive = "Tugas sebelumnya dari jadwal ini masih berjalan."
    let webScheduleMissed = "Terakhir terlewat"
    let webScheduleNoNext = "Tidak ada eksekusi berikutnya yang dijadwalkan."
    func childAnnounce(_ title: String) -> String { "Tugas dari Clawdline diterima: \(title) — mulai dikerjakan sekarang." }
    func settingsSeconds(_ value: Double) -> String { String(format: "%.1f dtk", value) }

    let webConnLive = "langsung"
    let webConnConnecting = "menyambung"
    let webConnRetrying = "coba lagi {n} dtk"
    let webConnOffline = "terputus"
    let webConnLocked = "belum berpasangan"
    let webConnTipLive = "Mengalir langsung dari aplikasinya"
    let webConnTipLocked = "Peramban ini belum dipasangkan dengan Mac"
    let webConnTipDown = "Tidak tersambung — klik untuk mencoba sekarang"

    let webCountWorking = "{n} berjalan"
    let webCountWaiting = "{n} menunggu"
    let webCountUnreadable = "{n} tak terbaca"
    let webCountQuietOne = "{n} sesi, semuanya tenang"
    let webCountQuietMany = "{n} sesi, semuanya tenang"
    let webCountNone = "tidak ada sesi"

    let webFilterPlaceholder = "Saring menurut tugas, proyek, atau tty"
    let webFilterLabel = "Saring sesi"
    let webListLabel = "Sesi Claude Code"
    let webPull = "Tarik untuk menyegarkan"
    let webPullRelease = "Lepas untuk menyegarkan"
    let webPullBusy = "Menyegarkan…"
    let webEmptyFilterTitle = "Tidak ada yang cocok dengan “{q}”"
    let webEmptyFilterHint = "Esc menghapus saringannya"
    let webEmptyLockedTitle = "Perangkat ini belum berpasangan"
    let webEmptyLockedHint = "Aplikasinya menjawab 401 — pasangkan dari Clawdline di Mac"
    let webEmptyNoneHint = "Mulai satu di terminal dan ia muncul di sini"
    let webEmptyWaitTitle = "Menunggu aplikasinya"
    let webEmptyWaitHint = "Belum ada apa pun yang datang lewat sambungan"
    let webStateUnreadable = "layarnya tidak terbaca"
    let webStateWorking = "berjalan"
    let sessionWorkReady = "bisa menerima pekerjaan baru"
    let sessionWorkUnknown = "status tidak diketahui"
    let sessionWorkHolding = "berjalan sendiri"
    let sessionWorkOwed = "ada keputusan yang terutang"
    let sessionWorkSelfStated = "dilaporkan sendiri"
    let sessionWorkMilestone = "Tonggak telah dikirim; tinjauan atau pendaratan mungkin tersisa"
    let sessionWorkComplete = "Pendaratan cabang target terverifikasi broker"
    let closeabilitySafe = "Aman untuk ditutup"
    let closeabilityBlocked = "{n} kewajiban tersisa"
    let closeabilityBlockedOne = "1 kewajiban tersisa"
    let closeabilityBlockedMany = "{n} kewajiban tersisa"
    let closeabilityNeedsAttestation = "Menunggu pernyataan sesi"
    let closeabilityUnknown = "Kelayakan tutup tidak diketahui"
    let closeabilityWhy = "Tidak bisa ditutup karena"
    let closeabilityMoverSelf = "sesi ini yang menggerakkannya"
    let closeabilityMoverPerson = "Anda yang menggerakkannya"
    let closeabilityMoverSession = "sesi lain yang menggerakkannya"
    let closeabilityMoverBroker = "pembacaan baru yang menggerakkannya"
    let closeabilityNotProven = "Broker tidak dapat membuktikan sesi ini aman untuk ditutup."
    let closeabilityAttestationExplanation = "Ini bukan berarti ada pekerjaan belum selesai yang ditemukan. Pemeriksaan yang dapat dilakukan Clawdline sudah bersih, tetapi sesi ini belum mengonfirmasi apakah ada perubahan lokal, pekerjaan yang belum diserahkan, atau pekerjaan di luar Clawdline yang tertinggal. Periksa sesi sebelum menutupnya."
    let closeabilityTechnicalDetails = "Detail teknis"

    let webBack = "Sesi"
    let webBackLabel = "Kembali ke daftar sesi"
    let webMenu = "Menu"
    let webPages = "Halaman"
    let webSessions = "Sesi"
    let webUsage = "Pemakaian"
    let webNoSessionOpen = "Tidak ada sesi terbuka"
    let webOrderTip = "Balik urutan transkrip (r)"
    let webShowOnMac = "Tampilkan di Mac"
    let webShowOnMacTip = "Bawa terminal sesi ini ke depan di Mac"
    let webShowOnMacOff = "Server melaporkan write: false — belum ada yang bisa dikirim"
    let webShowOnMacAsked = "Mac sudah diminta membawanya ke depan"
    let webSessionActions = "Tindakan sesi"
    let webSessionGit = "Perubahan Git"
    let webScreenTitle = "Layar"
    let webScreenLive = "langsung"
    let webScreenOnDemand = "sesuai permintaan"
    let webScreenGone = "Layar itu tidak dapat dibaca"
    let webGitTitle = "Perubahan Git"
    let webGitClean = "Tidak ada perubahan di direktori kerja"
    let webGitNotRepo = "Bukan repositori Git"
    let webGitFailed = "Perubahan Git tidak dapat dibaca"
    let webGitRefresh = "Muat ulang"
    let webGitClose = "Tutup"
    let webGitStaged = "Disiapkan"
    let webGitUnstaged = "Belum disiapkan"
    let webGitUntracked = "Belum dilacak"
    let webGitConflict = "Konflik"
    let webEndSession = "Tutup sesi"
    let webConfirmActionTitle = "Jalankan {action}?"
    let webConfirmActionSay = "Ini mengirim {action} ke sesi saat ini."
    let webConfirmEndTitle = "Tutup sesi ini?"
    let webConfirmEndSay = "Asisten akan keluar, lalu tab terminalnya ditutup."
    let webConfirmEndLoses = "Menutup juga mengakhiri:"
    let webClawdfatherCreateLabel = "Beri nama Clawdfather untuk sesi baru"
    let webClawdfatherIs = "Sesi ini adalah {name}"
    let webClawdfatherRegisterAsk = "Daftarkan sesi baru ini sebagai Clawdfather Mac ini, yaitu koordinator mesin. Id sesi terminal-neutral milikmu adalah {id}. Baca catatan koordinator dengan orchestrator token dari ~/.config/clawdline/orchestrator-token. Hanya jika tidak ada koordinator yang dikonfigurasi, ikuti bagian pendaftaran dari “Becoming Clawdfather” di docs/orchestrator.md. Jika sudah ada koordinator yang dikonfigurasi, sekalipun sedang offline, jangan gantikan. Lalu ceritakan apa yang terjadi."
    let webClawdfatherRegisterSent = "Sesi baru diminta menjadi Clawdfather"
    let webClawdfatherRegisterLate = "Sesi baru belum siap tepat waktu untuk diberi nama Clawdfather."
    let webClawdfatherRegisterBlocked = "Catatan koordinator Mac ini tidak bisa dibaca, jadi dibiarkan apa adanya."
    let webCoordSectionObserve = "Pantau"
    let webCoordSectionCoordinate = "Koordinasi"
    let webCoordSectionPresence = "Kehadiran"
    let webCoordSectionAdmin = "Administrasi"
    let webCoordCmdStatusReport = "Laporan status"
    let webCoordCmdStatusReportSay = "Baca status Clawdfather saat ini dan kewajibannya yang sedang berjalan."
    let webCoordCmdSinceAway = "Sejak Anda pergi"
    let webCoordCmdSinceAwaySay = "Baca perubahan dan keputusan yang tercatat sejak titik kembali terakhir Anda."
    let webCoordCmdDuplicates = "Duplikat, konflik & kepemilikan"
    let webCoordCmdDuplicatesSay = "Periksa pekerjaan ganda, klaim yang berbenturan, dan kepemilikan saat ini."
    let webCoordCmdLandingClosure = "Penutupan serah terima"
    let webCoordCmdLandingClosureSay = "Baca serah terima yang sudah ditinjau dan masih menunggu integrasi oleh root."
    let webCoordCmdCoordinateWork = "Koordinasikan pekerjaan"
    let webCoordCmdCoordinateWorkSay = "Susun draf langkah koordinasi untuk pekerjaan yang sudah berjalan."
    let webCoordCmdDispatch = "Delegasikan pekerjaan mandiri"
    let webCoordCmdDispatchSay = "Pratinjau delegasi yang akan memulai sesi anak yang mandiri."
    let webCoordCmdAsk = "Tanya Clawdfather"
    let webCoordCmdAskSay = "Susun draf pertanyaan untuk pertimbangan Clawdfather."
    let webCoordCmdQuietWatch = "Pengawasan senyap"
    let webCoordCmdQuietWatchSay = "Susun draf permintaan pemantauan senyap tanpa membunyikan peringatan menunggu."
    let webCoordCmdScope = "Cakupan & izin"
    let webCoordCmdScopeSay = "Baca cakupan Clawdfather saat ini dan izin yang diberikan."
    let webCoordCmdStop = "Hentikan Clawdfather"
    let webCoordCmdStopSay = "Pratinjau penghentian Clawdfather."
    let webCoordCmdReconnect = "Sambungkan ulang Clawdfather"
    let webCoordCmdReconnectSay = "Pratinjau penyambungan ulang Clawdfather."
    let webCoordCmdDeepAudit = "Audit status mendalam"
    let webCoordCmdDeepAuditSay = "Minta Clawdfather mengaudit pekerjaan, kiriman, dan keputusan di Session terkait."
    let webCoordTokenExpected = "Upaya Token yang diperkirakan: {effort}"
    let webCoordTokenLow = "Rendah"
    let webCoordTokenMedium = "Sedang"
    let webCoordTokenHigh = "Tinggi"
    let webCoordTokenUnknown = "Tidak diketahui"
    let webCoordAuditPreview = "Permintaan lintas Session dengan Token tinggi. Belum ada yang dikirim. Konfirmasikan untuk mengirim instruksi audit lengkap ke Session Clawdfather yang tepat ini. Versi pertama ini dijalankan agen dan belum memiliki catatan run broker yang persisten."
    let webCoordAuditWhyOffline = "Clawdfather sedang offline, jadi permintaan audit tidak dapat dikirim."
    let webCoordAuditWhyDisconnected = "Browser ini sedang offline, jadi permintaan audit tidak dapat dikirim."
    let webCoordAuditWhyNoWrite = "Browser ini saat ini tidak memiliki kemampuan kirim/tulis."
    let webCoordAuditSending = "Mengirim permintaan…"
    let webCoordAuditSent = "Permintaan audit terkirim. Tanda terima ini tidak berarti audit telah selesai."
    let webCoordAuditFailed = "Permintaan audit tidak terkirim ({code}): {message}"
    let webCoordEffectRead = "Hanya baca"
    let webCoordEffectAdvisory = "Penasihat"
    let webCoordEffectSpawns = "Memulai sesi"
    let webCoordEffectMutation = "Mengubah keadaan"
    let webCoordStateAvailable = "Tersedia"
    let webCoordStateDraft = "Draf"
    let webCoordStateUnavailable = "Tak tersedia"
    let webCoordStatePreview = "Pratinjau"
    let webCoordStateDisabled = "Dinonaktifkan"
    let webCoordOnline = "{name} daring"
    let webCoordOffline = "{name} luring"
    let webCoordControlsTitle = "Kendali {name}"
    let webCoordOpenControls = "Buka kendali {name}"
    let webCoordEmpty = "Tidak ada perintah Clawdfather yang dikenali diumumkan."
    let webCoordDisabledFallback = "Dinonaktifkan oleh Clawdfather."
    let webCoordPreviewTitle = "Perintah Clawdfather"
    let webCoordPreviewNone = "Tidak ada perintah dipilih; tidak ada yang dikirim."
    let webCoordPreviewMutation = "Hanya pratinjau — tidak ada yang dikirim. Konfirmasi tetap terkunci sampai API perintah Clawdfather tersambung."
    let webCoordPreviewDraft = "Hanya draf luring — tidak ada yang dikirim atau disajikan sebagai pertimbangan Clawdfather."
    let webCoordPreviewSpawn = "Hanya pratinjau — tidak ada sesi yang dimulai."
    let webCoordPreviewContract = "Hanya kontrak perintah ini yang ditampilkan; tidak ada yang dikirim."
    let webCoordWhyNoCommandRoute = "Belum ada rute yang membawa perintah dari panel ini ke sebuah sesi, jadi tidak ada yang bisa dikirim."
    let webCoordWhyNoReturnLedger = "Mac ini belum mencatat titik kembali, jadi tidak ada yang bisa dibaca sebagai pembanding."
    let webCoordWhyDeviceCannotSpawn = "Perangkat yang dipasangkan tidak pernah bisa memulai sesi — pemisahan itu disengaja, dan tombol ini tidak akan melewatinya."
    let webCoordWhyMachineTokenOnly = "Menyambung ulang butuh token orkestrator milik Mac sendiri, yang sengaja tidak dipegang perangkat yang dipasangkan."
    let webCoordReadFailed = "Tidak bisa membaca situasi Clawdfather."
    let webCoordActiveTasks = "{n} tugas sedang berjalan"
    let webCoordPendingLandings = "{n} serah terima menunggu integrasi"
    let webCoordOpenWaits = "{n} penantian berkas masih terbuka"
    let webCoordCountUnknown = "{n} tidak diketahui"
    let webCoordStaleSessions = "Gambaran sesi di Mac sudah usang; angka-angka ini mungkin lama."
    let webCoordUnknown = "Tidak diketahui"
    let webCoordWaitingList = "Menunggu seseorang"
    let webCoordBlockingList = "Memegang berkas yang ditunggu orang lain"
    let webCoordAllQuiet = "Tidak ada yang terblokir, diperebutkan, atau tanpa pemilik."
    let webCoordNoLandings = "Tidak ada serah terima yang menunggu integrasi."
    let webCoordUnregistered = "Tidak ada Clawdfather yang terdaftar di Mac ini."
    let webCoordScopeLine = "{name} mengoordinasikan Mac ini — cakupan mesin."
    let webCoordScopeDevice = "Dari panel ini Clawdfather hanya bisa dibaca. Mengirim pekerjaan, memulai sesi, dan mengubah keadaan mesin butuh kredensial Mac sendiri, dan tetap dinonaktifkan di sini."
    let webClosing = "Menutup…"
    let webCancel = "Batal"
    let webConfirm = "Konfirmasi"
    let webReviewBeforeClosing = "Periksa sesi"
    let webConfirmEndAnyway = "Tetap tutup"
    let webPickSession = "Pilih sesi di sebelah kiri."
    let webReading = "Membaca…"
    let webLoading = "Memuat…"
    let webTranscriptFailed = "Transkripnya tidak bisa dibaca"
    let webWhoYou = "kamu"
    let webWhoTool = "alat"
    let webNoticeTask = "tugas"
    let webNoticeCompleted = "Tugas selesai"
    let webNoticeFailed = "Tugas gagal"
    let webNoticeTimedOut = "Waktu tugas habis"
    let webNoticeCancelled = "Tugas dibatalkan"
    let webNoticeCouldNotStart = "Tugas tidak dapat dimulai"
    let webNoticeFinished = "Tugas berakhir"
    let webNoticeWorkspaceOverlap = "Ruang kerja tumpang tindih"
    let webNoticeNoSiblings = "Tidak ada tugas sejajar yang masih berjalan."
    let webNoticeOneSibling = "{n} tugas sejajar masih berjalan."
    let webNoticeManySiblings = "{n} tugas sejajar masih berjalan."
    let webNoticeClaimsReleased = "Klaim jalur telah dilepas; tab turunan mungkin masih menulis."
    let webNoticeFileWaitRequested = "Penantian berkas diminta"
    let webNoticeFileWaitReleased = "Penantian berkas dilepas"
    let webNoticeHandoffPickedUp = "Serah terima diambil"
    let webNoticeHandoffNeedsDelivery = "Serah terima perlu dikirim manual"
    let webNoticeRecheckGit = "Periksa kembali HEAD, status, dan diff sebelum mengintegrasikan."
    let webPending = "Menunggu Mac…"
    let webAttachedImage = "{n} gambar terlampir"
    let webAttachedImages = "{n} gambar terlampir"
    let webSteps = "{n} langkah"
    let webJustNow = "barusan"
    let webMinutesAgo = "{n} menit lalu"
    let webCodeCopy = "Salin kode ini"
    let webCodeCopied = "Kode disalin."
    let webCodeCopyFailed = "Tidak bisa menyalin; pilih teksnya."

    let webSend = "Kirim"
    let webAttach = "Lampirkan gambar"
    let webRemoveShot = "Hapus {name}"
    let webWriteOpen = "Buka sebuah sesi untuk menulis ke sana."
    let webWriteOff = "*Pengiriman mati* — server melaporkan `write: false`. Kotaknya sudah tersambung; ia menyala sendiri begitu itu berubah."
    let webShotsOnlyPictures = "Yang bisa ikut sebuah pesan hanya gambar"
    let webShotsTooMany = "Satu pesan paling banyak membawa {n} gambar"
    let webShotTooBig = "Gambar itu terlalu besar untuk dikirim, sekalipun dikecilkan"
    let webShotsTooBig = "Gambar-gambar itu terlalu besar untuk dikirim bersamaan"
    let webShotUnreadable = "Gambar itu tidak bisa dibaca"
    let webShotNeedsSession = "Buka sebuah sesi untuk mengirim gambar ke sana"

    let webVoiceStart = "Dikte sebuah pesan"
    let webVoiceStop = "Berhenti dan transkripsikan"
    let webVoiceDone = "Selesai"
    let webVoiceListening = "Mendengarkan… {t}"
    let webVoiceReading = "Sedang ditranskripsi di Mac… {n} dtk"
    let webVoiceSlow = "Yang pertama setelah Mac ini dinyalakan ulang memuat modelnya dulu — sekitar dua belas detik."
    let webVoiceLimit = "Rekaman berhenti di {n} menit, selama itulah satu rekaman berjalan. Yang sudah ada ditranskripsi."
    let webVoiceEmpty = "Tidak ada yang terdengar di situ."
    let webVoiceTooShort = "Itu terlalu pendek untuk terdengar."
    let webVoiceDenied = "Mikrofonnya ditolak. Nyalakan lagi di pengaturan peramban ini untuk situs ini."
    let webVoiceNoMic = "Tidak ada mikrofon yang ditemukan di perangkat ini."
    let webVoiceInUse = "Mikrofonnya sedang dipakai — ada hal lain di perangkat ini yang memegangnya."
    let webVoiceInsecure = "Mikrofon butuh https, dan halaman ini tidak lewat https. Terowongan menyediakannya; alamat biasa di jaringan lokal tidak."
    let webVoiceUnsupported = "Peramban ini tidak bisa merekam suara."
    let webVoiceBusy = "Satu sedang ditranskripsi dan satu lagi menunggu. Coba lagi sebentar lagi."
    let webVoiceNoBinary = "Whisper belum terpasang di Mac, jadi di sana tidak ada yang bisa dipakai untuk mentranskripsi."
    let webVoiceNoModel = "Whisper ada di Mac tapi tidak punya model untuk membaca. Satu berkas ggml di `~/.cache/whisper` sudah cukup."
    let webVoiceFailed = "Itu tidak bisa ditranskripsi."

    let webHintMove = "pindah"
    let webHintOpen = "buka"
    let webHintFilter = "saring"
    let webHintPane = "panel"

    let webKeysLabel = "Pintasan papan ketik"
    let webKeysTitle = "Papan ketik"
    let webKeysMove = "Berpindah di daftar — `j` dan `k` sama saja"
    let webKeysOpen = "Buka sesi yang dipilih"
    let webKeysFilter = "Saring daftarnya"
    let webKeysEscape = "Hapus saringannya, lalu mundur"
    let webKeysList = "Fokus ke daftar sesi"
    let webKeysPane = "Tampilkan atau sembunyikan transkrip"
    let webKeysEnds = "Awal atau akhir transkrip"
    let webKeysReverse = "Balik urutan transkrip"
    let webKeysThis = "Kartu ini"
    let webKeysFoot = "Apa pun yang diketik di kotak teks tetap di kotak teks — pintasannya mundur selama kamu menulis."

    let webDoorLabel = "Pasangkan peramban ini"
    let webDoorAskLede = "Peramban ini belum diizinkan masuk."
    let webDoorAskFine = "Minta dipasangkan, lalu kode enam angka muncul *di Mac* — sengaja tidak ikut dalam jawaban ke halaman ini. Hanya orang yang ada di depan mesin itu yang bisa menyelesaikannya, dan justru di situlah pengamanannya, bukan penghalangnya."
    let webDoorName = "Beri nama perangkat ini"
    let webDoorAsk = "Minta dipasangkan"
    let webDoorToPassword = "Masuk pakai kata sandi saja"
    let webDoorCodeLede = "Lihat ke Mac."
    let webDoorCodeFine = "Clawdline menampilkan enam angka selama {left}. Ketik di sini."
    let webDoorTwoMinutes = "dua menit"
    let webDoorDigit = "Angka ke-{n}"
    let webDoorConfirm = "Pasangkan perangkat ini"
    let webDoorRestart = "Mulai lagi"
    let webDoorPasswordLede = "Masuk dengan kata sandi."
    let webDoorPasswordFine = "Yang disetel di Clawdline di Mac, di Pengaturan → Akses jarak jauh. Kalau belum ada, jalan masuknya lewat berpasangan."
    let webDoorPassword = "Kata sandi"
    let webDoorPasswordGo = "Masuk"
    let webDoorToPair = "Pakai kode pemasangan saja"
    let webDoorAsking = "Bertanya ke Mac…"
    let webDoorAskFailed = "Tidak bisa bertanya ke Mac."
    let webDoorRateLimited = "Setiap permintaan memunculkan peringatan di Mac, jadi hanya ada tiga tiap sepuluh menit."
    let webDoorSixDigits = "Enam angka."
    let webDoorChecking = "Memeriksa…"
    let webDoorFinished = "Pemasangan itu sudah habis — lima kode salah. Minta lagi saat kamu ada di depan Mac."
    let webDoorWrongCode = "Kode itu tidak cocok."
    let webDoorNeedPassword = "Kata sandinya dulu."
    let webDoorWrongPassword = "Itu bukan kata sandinya."
    let webDoorExpired = "Kode itu sudah kedaluwarsa. Minta lagi dan yang baru muncul di Mac."
    let webDoorPaired = "Berpasangan — peramban ini sudah masuk"

    let webOffline = "Clawdline tidak terjangkau. Apakah ia masih jalan di Mac?"
    let webNotJSON = "Server mengirim sesuatu yang bukan JSON"
    let webRequestFailed = "Permintaan gagal"

    let webNotifyGo = "Beri tahu aku"
    let webNotifyAsking = "Meminta izin…"
    let webNotifyStop = "Hentikan"
    let webNotifyStopping = "Menghentikan…"
    let webNotifyOff = "kalau ada sesi yang menunggu jawaban"
    let webNotifyOn = "Perangkat ini sudah berlangganan. Apa saja yang dikabarkan diatur di Mac."
    let webNotifyBlocked = "Notifikasi diblokir untuk situs ini. Sakelarnya ada di pengaturan peramban sendiri, bukan di sini."
    let webNotifyUnsupported = "Peramban ini tidak bisa menampilkan notifikasi."
    let webNotifyHomeScreen = "Tambahkan clawdline ke layar utama dan buka dari sana — iOS hanya mengirim notifikasi ke aplikasi yang tinggal di sana."
    let webNotifyOnFailed = "Tidak bisa menyalakan notifikasi"
    let webNotifyOffFailed = "Tidak bisa mematikan notifikasi"

    let webSettings = "Pengaturan"
    let webSettingsNotify = "Notifikasi"
    let webSettingsAssistantIcons = "Ikon asisten"
    let webSettingsAssistantIconsSay = "Tampilkan tanda Claude atau Codex sebelum namanya dalam percakapan."
    let webSettingsAssistantIconsShow = "Tampilkan ikon"
    let webSettingsVersion = "Versi {v}"
    let webClose = "Tutup"
    let webNotifySheetOff = "Perangkat ini tidak dikabari saat ada sesi yang menunggu."
    let webNotifyTest = "Kirim percobaan"
    let webNotifyTestSent = "Terkirim — sebentar lagi mestinya sampai di perangkat ini."
    let webNotifyTestNone = "Mac tidak punya langganan untuk perangkat ini. Matikan lalu nyalakan lagi notifikasinya, dan peramban ini akan mendaftarkan yang baru."
    let webNotifyTestFailed = "Tidak bisa mengirim notifikasi percobaan"
    let webSending = "Mengirim…"
    let webSendTip = "Return mengirim · Shift-Return membuat baris baru"
    let webStart = "Mulai sesi"
    let webStartLabel = "Mulai sesi di sebuah proyek"
    let webStartPick = "Mulai di mana?"
    let webStartWith = "Mulai dengan apa?"
    let webStartEmpty = "Belum ada tempat untuk memulai. Jalankan Claude Code sekali di Mac dan tempatnya muncul di sini."
    let webStartFilter = "Saring proyek"
    let webStarting = "Membuka tab…"
    let webStartWaiting = "Sudah dimulai. Menunggu ia muncul…"
    let webStartSlow = "Tab-nya sudah terbuka, tetapi sesinya belum melapor. Coba lihat Mac-nya."
    let webStartFailed = "Itu tidak bisa dimulai."
    let webStartGone = "Proyek itu sudah tidak ada di Mac."
    let webStartTerminalClosed = "{app} tidak sedang jalan di Mac. Buka di sana lalu coba lagi."
    let webStartTerminalUnsupported = "Pengaturan membuka sesi baru di tmux, dan Mac ini tidak punya tmux. Pasang di sana, atau pilih terminal lain di pengaturan."
    let webStartDetached = "Sesi ini dimulai di server tmux yang tidak ada yang terhubung. Ketik {command} di Mac untuk melihatnya."
    let webStartOff = "Memulai sesi sedang dimatikan. Pengaturan → Akses jarak jauh di Mac yang menyalakannya."
    let webResumeWith = "Lanjutkan yang lama"
    let webResumePick = "Percakapan yang mana?"
    let webResumeFilter = "Saring percakapan"
    let webResumeEmpty = "Belum ada apa pun yang tercatat di proyek itu."
    let webResumeLive = "terbuka"
    let webResumeBack = "Proyek lain"
    let webResumeGone = "Percakapan itu sudah tidak ada di Mac."
    let webResumeClaudeOnly = "Hanya Claude Code yang menyimpan percakapan yang bisa dilanjutkan."
    let webResuming = "Membukanya kembali…"
    let webResumeCapped = "Yang lebih lama tidak ada di daftar ini."
    let webCommand = "Katakan yang mau dimulai"
    let webCommandLabel = "Mulai sesi dengan mengatakan yang harus dilakukan"
    let webCommandSay = "Belum ada yang dikirim sebelum menekan Mulai di bawah."
    let webCommandHeard = "Harus melakukan apa?"
    let webCommandThinking = "Memikirkan…"
    let webCommandDraft = "Draf"
    let webCommandWhere = "Di mana"
    let webCommandWith = "Dengan apa"
    let webCommandModel = "Model"
    let webCommandFirst = "Pesan pertama"
    let webCommandGo = "Mulai"
    let webCommandUnsure = "Belum jelas proyek yang mana — pilih salah satu di bawah."
    let webCommandFailed = "Tidak bisa mengubahnya jadi draf."
    let webCommandNoPlanner = "Mac ini tidak punya Claude Code untuk mengubahnya jadi draf."
    let webCommandBusy = "Sudah ada satu kalimat yang sedang jadi draf — coba lagi sebentar lagi."
    let webCommandEmpty = "Tidak terdengar apa pun"
    let webScheduleNew = "Jadwal baru"
    let webScheduleEdit = "Ubah jadwal"
    let webScheduleNewSay = "Belum ada yang dijadwalkan sebelum menekan Buat di bawah."
    let webScheduleTitle = "Judul"
    let webScheduleAt = "Waktu"
    let webScheduleOn = "Hari"
    let webScheduleWhere = "Di mana"
    let webScheduleWith = "Dengan apa"
    let webScheduleFirst = "Pesan pertama"
    let webScheduleMore = "Lainnya"
    let webScheduleModel = "Model"
    let webScheduleWhenDone = "Tutup tab setelah selesai"
    let webScheduleCloseSuccess = "Jika berhasil"
    let webScheduleCloseAlways = "Selalu"
    let webScheduleCloseNever = "Biarkan tetap terbuka"
    let webScheduleEnabled = "Aktif"
    let webScheduleDisabled = "Nonaktif"
    let webScheduleNotify = "Beri tahu aku kalau gagal"
    let webScheduleCatchUp = "Kalau terlewat, susulkan dalam (jam)"
    let webScheduleTimeout = "Menyerah kalau belum selesai dalam (menit)"
    let webScheduleCreate = "Buat"
    let webScheduleCreated = "Jadwal dibuat."
    let webScheduleDispatchOff = "Jadwal sudah dibuat dan sah, tapi penitipan pekerjaan sedang mati — tidak ada yang akan menjalankannya. Pengaturan → Akses jarak jauh di Mac yang menyalakannya."
    let webScheduleFailed = "Tidak bisa membuat jadwal."
    let webScheduleSave = "Simpan"
    let webScheduleSaved = "Jadwal disimpan."
    let webScheduleDelete = "Hapus"
    let webScheduleDeleteAsk = "Hapus {title}? Tidak bisa dibatalkan."
    let webScheduleDeleted = "Jadwal dihapus."
    let webScheduleNeedsTime = "Waktu tidak terdengar — atur salah satu."
    let webScheduleNeedsPlace = "Belum jelas proyek yang mana — pilih salah satu."
    let webScheduleDaily = "Setiap hari"
    let webScheduleSun = "Min"
    let webScheduleMon = "Sen"
    let webScheduleTue = "Sel"
    let webScheduleWed = "Rab"
    let webScheduleThu = "Kam"
    let webScheduleFri = "Jum"
    let webScheduleSat = "Sab"
    let webSnippets = "Frasa"
    let webSnippetsThisProject = "Proyek ini"
    let webSnippetsEveryProject = "Semua proyek"
    let webSnippetsEmpty = "Belum ada frasa. Tambahkan satu di Mac, nanti muncul di sini."
    let webSnippetsEmptyNew = "Belum ada frasa. Tulis satu, atau mulai dari salah satu ini."
    let webSnippetsReadOnly = "Perangkat ini boleh membaca, tapi tidak menulis — frasa tidak bisa masuk ke kotak."
    let webSnippetNew = "Frasa baru"
    let webSnippetEditing = "Ubah frasa"
    let webSnippetMore = "Tindakan frasa"
    let webSnippetEdit = "Ubah"
    let webSnippetDelete = "Hapus"
    let webSnippetDeleteAsk = "Tekan lagi untuk menghapus"
    let webSnippetUp = "Naikkan"
    let webSnippetDown = "Turunkan"
    let webSnippetToGlobal = "Pindahkan ke semua proyek"
    let webSnippetToProject = "Hanya proyek ini"
    let webSnippetTitleLabel = "Judul"
    let webSnippetBodyLabel = "Teks"
    let webSnippetScopeLabel = "Di mana"
    let webSnippetSave = "Simpan"
    let webSnippetFromLast = "Dari pesan terakhir saya"
    let webSnippetNeedsText = "Frasa perlu judul dan sedikit teks."
    let webSnippetStarterCommitTitle = "Commit, push, deploy"
    let webSnippetStarterCommitBody = "Commit tiap berkas dengan menyebut namanya — jangan pernah git add -A — lalu push dan deploy."
    let webSnippetStarterReportTitle = "Bilang apa yang sudah dikerjakan"
    let webSnippetStarterReportBody = "Bilang apa yang barusan kamu kerjakan, apa yang belum, dan apa berikutnya."
    let webLinks = "Tautan"
    let webLinksTip = "Di mana proyek ini bisa dibuka"
    let webLinksPick = "Semua yang punya alamat di proyek ini."
    let webLinksEmpty = "Proyek ini tidak punya apa pun yang beralamat — tidak ada situs, tidak ada deploy, tidak ada server yang berjalan."
    let webLinksFailed = "Tautan proyek ini tidak bisa dibaca."
    let webLinksLocal = "Hanya di jaringan Mac sendiri. Dari sini tidak akan terbuka."
    let webLinksFile = "Sebuah berkas di Mac. Terbukanya di sana, bukan di peramban ini."
    let webLinksCopy = "Salin path"
    let webLinksCopied = "Tersalin."
    let webLinksCopyFailed = "Peramban ini tidak mengizinkan halaman menyalin itu."
    let webLinkOk = "oke"
    let webLinkFail = "gagal"
    let webLinkDown = "mati"
    let webLinkRunning = "berjalan"
    let webSessionInfo = "Info sesi"
    let webInfoTitle = "Tentang sesi ini"
    let webInfoEditTitle = "Edit judul sesi"
    let webInfoCopyTitle = "Salin nama ini"
    let webInfoTitleSaved = "Judul disimpan."
    let webInfoTitleLocal = "Judul disimpan di Clawdline; nama hilir tidak diubah."
    let webInfoTitleQueued = "Judul disimpan di Clawdline; pembaruan Codex mengantre."
    let webInfoTitleNotDurable = "Judul sudah tampil, tetapi Mac ini tidak dapat menyimpannya ke disk; akan hilang setelah dimulai ulang."
    let webInfoTitleCloud = "Judul sesi hanya bisa diubah di Mac itu sendiri, bukan lewat koneksi cloud."
    let webInfoSession = "Sesi ini"
    let webInfoAssistant = "Asisten"
    let webInfoModel = "Model"
    let webInfoSessionId = "ID sesi"
    let webInfoDirectory = "Direktori"
    let webInfoRunningFor = "Sudah berjalan"
    let webInfoStatus = "Status sesi"
    let webInfoWorkStatusMeaning = "Ini adalah status pekerjaan sesi. Satu tanda centang berarti sudah dikirim dan menunggu persetujuan; dua berarti sudah ditinjau dan disetujui."
    let webInfoCloseabilityMeaning = "Kunci menunjukkan apakah sesi ini aman untuk ditutup. Ini terpisah dari status pengiriman."
    let webInfoUsage = "Pemakaian token"
    let webInfoInput = "Masukan"
    let webInfoOutput = "Keluaran"
    let webInfoCacheRead = "Cache dibaca"
    let webInfoCacheWrite = "Cache ditulis"
    let webInfoTotal = "Total"
    let webInfoCost = "Perkiraan biaya"
    let webInfoNoUsage = "Transkrip sesi ini belum ditemukan."
    let webInfoLimits = "Batas paket"
    let webInfoLimitHit = "batas tercapai"
    let webInfoResets = "direset {when}"
    let webInfoUnknown = "tidak diketahui"
    let webInfoFiles = "Berkas"
    let webInfoBranch = "Branch"
    let webInfoStaged = "Sudah di-stage"
    let webInfoUnstaged = "Berubah"
    let webInfoUntracked = "Belum dilacak"
    let webInfoConflict = "Konflik"
    let webInfoClean = "Tidak ada yang belum di-commit."
    let webInfoNotRepo = "Bukan repositori git."
    let webInfoDeploy = "Deploy terakhir"
    let webInfoNoDeploy = "Tidak ada catatan deploy untuk proyek ini."
    let webInfoFailed = "Info sesi ini tidak bisa dibaca."
    let webInfoBusy = "Mac sedang sibuk membaca sesi lain. Coba lagi sebentar lagi."
    let webInfoRefresh = "Muat ulang"
    let webInfoTokens = "token"
    let webInfoSwitchModel = "Ganti model"
    let webInfoModelOther = "model lain…"
    let webInfoModelSent = "/model {model} terkirim. Mengonfirmasi…"
    let webInfoModelBusy = "Penggantian menunggu sampai sesi diam."
    let webInfoSwitchPermission = "Ganti mode izin"
    let webInfoPermissionAuto = "Otomatis"
    let webInfoPermissionManual = "Manual"
    let webInfoPermissionAcceptEdits = "Terima edit"
    let webInfoPermissionPlan = "Perencanaan"
    let webInfoPermissionUnreadable = "Mode saat ini tidak dapat dibaca."
    let webInfoPermissionSent = "Beralih ke {mode}. Mengonfirmasi…"
    let webInfoPermissionBusy = "Mode izin sedang diganti."
    let webInfoLimitsClaude = "Claude Code baru mencatat sebuah jendela setelah habis, jadi sebelum itu tidak ada yang diketahui."
    let webInfoCopied = "Id sesi disalin."
    let webInfoAsOf = "per {when}"
    let webInfoWhyUnknown = "Mengapa tidak diketahui, dan cara mendapatkan angkanya"
    let webSettingsOrder = "Transkrip"
    let webSettingsOrderSay = "Transkrip mulai dibaca dari ujung yang mana. Ini berlaku untuk setiap sesi, dan dari papan ketik `r` melakukan hal yang sama."
    let webAskLabel = "bertanya"
    let webAskAny = "Berapa saja dari ini"
    let webWaitingTitle = "Sesi ini sedang menunggu jawaban"
    let webWaitingSay = "Claude Code sedang menampilkan menu di Mac. Clawdline belum bisa membaca menu dari sini, jadi pilihannya hanya ada di layar itu."
    let webWaitingSend = "*Mengirim dari sini tidak akan mengetikkan jawabanmu ke menu itu* — yang disahkan adalah pilihan yang sedang tersorot di menu, dan itu jarang yang kamu maksud. Yang satu ini jawab di Mac."
    let webMenuSay = "Ketuk satu jawaban, langsung dikirim ke sesi itu."
    let webMenuHighlighted = "disorot"
    let webMenuSent = "Jawaban terkirim."
    let webAgents = "Agen di latar belakang"
    let webAgentsCount = "{n} berjalan"
    let webAgentDone = "selesai"
    let webAgentFailed = "gagal"
    let webShells = "Shell di latar belakang"
    let webShellTitle = "Shell di latar belakang"
    let webShellOpen = "Lihat apa yang dicetak perintah ini"
    let webShellRunning = "masih berjalan"
    let webShellEnded = "selesai"
    let webShellQuiet = "Belum mencetak apa pun."
    let webShellFailed = "Tidak bisa membaca keluaran perintah ini."
    let webShellClose = "Tutup"
    let webShellStop = "Hentikan"
    let webShellStopTitle = "Hentikan perintah ini?"
    let webShellStopSay = "{command} masih berjalan. Ia diminta berhenti, lalu dimatikan lima detik kemudian kalau belum. Yang sudah terlanjur dikerjakan tidak dibatalkan."
    let webShellStopped = "Sudah diminta berhenti."
    let webShellStopFailed = "Tidak bisa dihentikan."
    let agentRunning = "berjalan"
    let agentTools = "{n} alat"
    let agentEmpty = "Agen ini belum menuliskan apa pun."
    let agentBack = "Sesi"
    let webAgentOpen = "Lihat apa yang dikerjakan agen ini"
    let webTaskRoot = "Induk"
    let webTaskChild = "Anak"
    let webTaskTasks = "Tugas"
    let webTaskDone = "selesai"
    let webTaskFailed = "gagal"
    let webTaskRunning = "berjalan"
    let webStale = "Clawdline sudah dibangun ulang di Mac. Halaman ini yang lama."
    let webStaleGo = "Muat ulang"

    // The Projects page, and the worktrees under one Project that finished a Feature.
    let webProjects = "Proyek"
    let webProjectsLede = "Direktori tempat asisten benar-benar pernah dijalankan dan yang masih ada."
    let webProjectsEmpty = "Belum ada direktori proyek yang tercatat di Mac ini."
    let webProjectsUnavailable = "Koneksi ini tidak bisa membaca proyek. Buka alamat aplikasi sendiri di jaringan Mac."
    let webProjectsLoading = "Membaca daftar proyek Mac ini…"
    let webProjectOpenLabel = "Buka {name}"
    let webProjectReading = "Menggabungkan baris ledger proyek ini…"
    let webProjectDelivered = "Selesai, belum digabung"
    let webProjectDeliveredSay = "Semua ini menyelesaikan sebuah Feature, dan tidak ada catatan landing yang mengatakan pekerjaannya sampai ke sebuah branch. Pekerjaannya selesai; hanya belum ada yang menggabungkannya."
    let webProjectDeliveredNone = "Tidak ada yang menunggu di sini: setiap Feature yang selesai di proyek ini punya catatan landing."
    let webProjectLanded = "Sudah digabung"
    let webProjectLandedSay = "Sebuah root mencatat bahwa hasil kerja ini sampai ke branch tujuannya."
    let webProjectActive = "Masih berjalan"
    let webProjectActiveSay = "Sebuah tugas dari worktree ini masih hidup di registry saat ini."
    let webProjectAbandoned = "Ditinggalkan"
    let webProjectAbandonedSay = "Tidak ada yang berhasil di sini, dan tidak ada pula yang masih berjalan."
    let webProjectUnknownOutcome = "Tidak diketahui"
    let webProjectUnknownSay = "Tidak ada baris tersimpan yang membawa status tugas, jadi tidak ada tebakan ke arah mana pun."
    let webProjectBranch = "Branch, menurut konvensi"
    let webProjectRuns = "Kerja agen"
    let webProjectSeen = "Terlihat"
    let webProjectNoWorktrees = "Tidak ada worktree di proyek ini yang menyelesaikan sebuah Feature."
    let webProjectExcluded = "{n} worktree lain di proyek ini tidak menyelesaikan Feature apa pun, jadi dihitung dan bukan didaftar."
    let webProjectUnattributed = "Worktree tanpa proyek"
    let webProjectUnattributedSay = "{n} worktree tidak termasuk proyek mana pun: semuanya tercatat sebelum kunci proyek kanonik ada, jadi kuncinya sendiri berupa path checkout. Dihitung di sini alih-alih dibuang diam-diam."
    let webProjectRead = "{rows} baris dibaca · {project} milik proyek ini · {worktree} berjalan di worktree · {feature} membawa Feature"
    let webProjectTruncated = "Sebagian: pemindaian mencapai batas barisnya, jadi semua di atas adalah batas bawah, bukan jumlah total."
    let webProjectNotFound = "Tidak ada di ledger yang cocok dengan proyek ini. Belum ada apa pun yang tercatat di bawahnya."
    let webProjectAmbiguous = "Lebih dari satu proyek bernama sama, jadi pembacaan ditolak alih-alih dijawab untuk salah satunya."
    let webProjectBusy = "Pembaca ledger sedang sibuk. Sesi tidak terpengaruh — coba lagi sebentar."
    let webProjectFailed = "Worktree proyek ini tidak bisa dibaca."

    let menuApplication = "Clawdline"
    let menuWindow = "Jendela"
    let menuHelp = "Bantuan"
    let menuClose = "Tutup jendela"
    let menuHome = "Beranda / Pusat penyiapan"
    let menuHelpDocumentation = "Dokumentasi Clawdline"
    func menuAbout(_ app: String) -> String { "Tentang \(app)" }
    let menuServices = "Layanan"
    func menuHide(_ app: String) -> String { "Sembunyikan \(app)" }
    let menuHideOthers = "Sembunyikan Lainnya"
    let menuShowAll = "Tampilkan Semua"
    let menuMinimize = "Minimalkan"
    let homeTitle = "Beranda Clawdline"
    let homeWelcome = "Pilih tujuan koneksi. Penyiapan menampilkan bukti nyata, bukan sekadar sakelar yang diubah."
    let homePurpose = "Apa yang ingin Anda hubungkan?"
    let homeLocalTitle = "Browser lokal"
    let homeLocalSummary = "Baca Clawdline di browser pada Mac ini. Kendali tetap mati kecuali Anda menyalakannya secara tegas di Pengaturan."
    let homeCloudPreviewTitle = "Pratinjau Clawdline Cloud"
    let homeCloudPreviewSummary = "Gunakan pratinjau terkelola setelah koneksi langsungnya dapat dibuktikan."
    let homeCloudflareTitle = "URL Cloudflare saya"
    let homeCloudflareSummary = "Gunakan hostname Cloudflare Anda setelah jalur HTTPS publik dapat dibuktikan."
    let homeUnavailable = "Belum siap dalam build ini; tidak ada klaim koneksi berhasil."
    let setupDetected = "Status terdeteksi"
    let setupNextAction = "Langkah berikutnya"
    let setupExpected = "Hasil yang diharapkan"
    let setupRecovery = "Pemulihan"
    let setupLocalServerOff = "Server loopback mati."
    let setupLocalChecking = "Memeriksa endpoint /v1/health yang sebenarnya…"
    let setupLocalConfigurationFailed = "Pengaturan browser lokal tidak dapat disimpan; tidak ada perubahan."
    let setupLocalHealthTransport = "Endpoint kesehatan tidak dapat dijangkau. Periksa port dan program lain yang memakainya."
    let setupLocalHealthTimedOut = "Endpoint kesehatan kehabisan waktu. Periksa port lalu coba lagi."
    func setupLocalHealthHTTP(_ status: Int) -> String { "Endpoint kesehatan mengembalikan HTTP \(status), bukan respons sehat." }
    let setupLocalHealthUnhealthy = "Endpoint menjawab, tetapi melaporkan ok: false."
    let setupLocalHealthInvalid = "Endpoint tidak memberi respons kesehatan yang valid. Periksa pemilik port."
    let setupLocalReady = "Endpoint kesehatan siap. Kredensial browser belum ada."
    let setupLocalWaiting = "Browser terbuka; menunggu perangkat ini melakukan autentikasi."
    let setupLocalConnected = "Terhubung. Perangkat browser ini telah menghubungi Clawdline."
    let setupLocalEnable = "Nyalakan browser lokal"
    let setupLocalRetry = "Periksa lagi"
    let setupLocalOpen = "Buka browser hanya-baca"
    let setupLocalOpenAgain = "Buka browser lagi"
    let setupFinish = "Selesai"
    let setupLocalExpected = "Browser hanya-baca terbuka dan terautentikasi, bahkan tanpa sesi aktif."
    let setupLocalRecovery = "Jika macet, biarkan jendela ini terbuka lalu periksa lagi. Server dan port tersedia di Pengaturan."
    let setupNoRecovery = "Tidak perlu pemulihan; rute ini telah terbukti."
    let setupLocalReadOnlyAction = "Tindakan ini menyimpan akses hanya baca dan membiarkan kendali tetap mati."
    let setupReadOnly = "Hanya baca · kendali tetap mati"
    let setupLocalDeviceName = "Browser Pusat Penyiapan"
    func setupTunnelFacts(_ mode: String, _ tunnel: String, _ hostname: String, _ status: String) -> String { "Mode: \(mode)\nTunnel: \(tunnel)\nHostname QR: \(hostname)\nStatus: \(status)" }
    let setupTunnelModeOff = "Mati"
    let setupTunnelModeQuick = "Cepat"
    let setupTunnelModeNamed = "Bernama"
    let setupTunnelQuickName = "Terowongan Cepat Cloudflare"
    let setupNone = "Tidak ada"
    let setupControlChosen = "Baca + kontrol · diaktifkan secara eksplisit di Pengaturan"
    let setupTunnelMissing = "cloudflared belum terpasang."
    let setupTunnelOff = "Tunnel mati; QR ponsel tidak tersedia."
    let setupTunnelStarting = "cloudflared sedang mulai; QR ponsel belum tersedia."
    func setupTunnelReady(_ url: String) -> String { "Aktif di \(url). Kredensial ponsel belum dibuat." }
    func setupTunnelWaiting(_ url: String) -> String { "QR menuju \(url). Menunggu ponsel ini persis." }
    func setupTunnelConnected(_ url: String) -> String { "Terhubung melalui \(url). Ponsel ini melaporkan lastSeen." }
    let setupTunnelExpected = "Hanya URL tunnel aktif yang masuk ke QR; hanya lastSeen perangkat nonlokal dari QR ini yang menyelesaikan penyiapan."
    let setupTunnelRecovery = "Buka Pengaturan Jarak Jauh. Pasang cloudflared jika belum ada; selain itu ikuti alasan yang terdeteksi, pertahankan tunnel, lalu pindai lagi."
    let setupOpenRemoteSettings = "Buka Pengaturan Jarak Jauh"
    let setupCheckTunnel = "Periksa Tunnel Lagi"
    let setupShowPhoneQR = "Tampilkan QR Ponsel"
    let setupShowPhoneQRAgain = "Tampilkan Lagi QR Ponsel"
    let setupCloudRelayUnauthorized = "Relay menolak kredensial mesin ini."
    func setupCloudFacts(_ account: String, _ credential: String, _ relay: String, _ pairing: String, _ receipt: String) -> String { "Akun: \(account)\nKredensial mesin: \(credential)\nRelay siap: \(relay)\nPemasangan E2EE: \(pairing)\nTanda terima viewer: \(receipt)" }
    let setupCloudExpected = "Preview selesai hanya bila akun, kredensial, kesiapan relay, pemasangan E2EE, dan tanda terima viewer ini terbukti masing-masing."
    let setupCloudRecovery = "Gunakan Pengaturan Cloud untuk masuk atau memasangkan. Kesiapan relay dan tanda terima tetap bukti Preview; mencoba lagi tidak menciptakan bukti."
    let setupOpenCloudSettings = "Buka Pengaturan Cloud"
    let setupPairCloudPhone = "Pasangkan Ponsel di Cloud"
    let setupReviewCloudPreview = "Tinjau Status Preview"
    let setupProofAbsent = "tidak ada"
    let setupProofReading = "membaca bukti…"
    let setupProofUnavailable = "bukti tidak tersedia"
    func setupProofFailed(_ reason: String) -> String { "gagal — \(reason)" }
    let setupCloudIdentityReadFailed = "identitas Keychain tidak dapat dibaca"
    let setupCloudRelayFailed = "relay melaporkan kegagalan; periksa Pengaturan Cloud dan log"
    let setupCloudPairingReadFailed = "penyimpanan perangkat terpasang tidak dapat dibaca"
    let setupCloudPairingAmbiguous = "lebih dari satu viewer baru muncul; mulai pemasangan lagi"
    func setupCloudAccountProved(_ account: String) -> String { "masuk sebagai \(account)" }
    func setupCloudCredentialProved(_ machine: String) -> String { "kredensial Keychain untuk \(machine)" }
    func setupCloudPairingProved(_ device: String) -> String { "disematkan untuk viewer tepat \(device)" }
    let setupCloudflareDeviceName = "Ponsel melalui Cloudflare"
    let setupScanLiveTunnel = "Pindai tunnel aktif dengan ponsel"
    let setupDismissalHint = "Menutup Beranda menghentikan pembukaan otomatis. Buka lagi Pusat Penyiapan dari menu app, Dock, item status, atau clawdline://home."
    let setupCompletionFailed = "Clawdline tidak dapat menyimpan bahwa penyiapan selesai. Periksa izin ~/.config/clawdline lalu tutup Beranda lagi."

    let menuOpen = "Buka bilah masukan"
    let menuReveal = "Ke tab tujuan"
    let menuMascot = "Maskot"
    let menuLogin = "Jalankan saat masuk"
    let menuEditConfig = "Pengaturan…"
    let menuReload = "Muat ulang konfigurasi"
    let menuQuit = "Keluar dari Clawdline"
    let menuNoTarget = "(belum terdeteksi)"

    func updateAvailable(latest: String, installed: String) -> String {
        "Clawdline \(latest) sudah rilis — ini \(installed)"
    }
    func compatNote(_ standing: Compat.Standing) -> String {
        switch standing {
        case .behind(let program, let installed, let builtAgainst):
            return "\(program) \(installed); build ini diperiksa terhadap \(builtAgainst)"
        case .ahead(let program, let installed, let builtAgainst, let release):
            return "\(program) \(installed); build ini diperiksa terhadap \(builtAgainst) — Clawdline \(release) sudah rilis"
        }
    }

    func hotkeyFailedTitle(_ combo: String) -> String { "Tidak bisa mendaftarkan \(combo)" }
    func hotkeyFailedBody(_ configPath: String) -> String {
        """
        Kemungkinan besar sudah dipakai aplikasi lain — Spotlight, pengganti metode \
        masukan, BetterTouchTool, dan sejenisnya.

        Pilih yang lain: ubah "hotkey" di \(configPath), lalu pilih \
        "Muat ulang konfigurasi" dari bilah menu.

        Sementara itu, ✳ di bilah menu tetap membuka bilah masukan.
        """
    }
    let loginFailed = "Tidak bisa mengatur jalan saat masuk"
}
