import Foundation

/// Two scripts, two structs. Not one struct plus a transliterator: the wording differs as well
/// as the characters (a tab is 分頁 in Taipei and 标签页 in Beijing), and a converter would get
/// the characters right and the words wrong — which reads worse than a plain translation, because
/// it is fluent enough that nobody flags it.
struct TraditionalChinese: Copy {
    let placeholder = "跟 Claude 說⋯⋯"

    let hintSend = "送出"
    let hintNewline = "換行"
    let hintSwitch = "換分頁"
    let hintList = "清單"
    let hintMascot = "換角色"
    let hintOutput = "看輸出"
    let hintFullscreen = "全螢幕"
    let hintKeys = "快速鍵"
    let hintTextSize = "字級"
    let hintOrder = "反序"
    let hintVoice = "語音"
    func voiceListening(onDevice: Bool) -> String {
        onDevice ? "在這台 Mac 上聽——再按一次結束"
                 : "聽著——這個語言由 Apple 辨識，不在這台機器上"
    }
    let voiceNoPermission = "語音輸入需要麥克風與語音辨識權限"
    let voiceUnavailable = "現在無法使用語音輸入"
    func voiceTranscribing(seconds: Double) -> String {
        String(format: "Whisper 重讀中⋯ %.1f 秒", seconds)
    }
    let whisperMissing = "沒有裝 Whisper——見 docs/whisper.md"
    let whisperNothingHeard = "沒聽到東西"
    func dictationStatus(_ status: Whisper.Status) -> String {
        switch status {
        case .ready(let model): return "語音：Apple，之後 Whisper（\(model)）"
        case .noBinary: return "語音：只有 Apple——沒有 whisper-cli"
        case .noModel: return "語音：只有 Apple——whisper-cli 有了，缺模型"
        }
    }
    func voiceListeningWhisper() -> String { "聽著——停下來時 Whisper 會再看一遍" }

    let scanning = "掃描中⋯"
    let noSession = "找不到在跑 Claude Code 的分頁"
    let nothingToSend = "沒有可以送的分頁——先在終端機裡開一個 Claude Code"
    let sendFailed = "送不出去"
    let itermSilent = "iTerm2 沒有回應"
    let itermBusy = "iTerm2 有一個對話框在等回答——請到 Mac 上按掉它"
    let scriptMissing = "找不到 iterm.js——app bundle 壞了？"
    let cannotList = "讀不到 iTerm2 的 session"
    let noOutput = "還讀不到這個分頁的內容。"
    let imageExpired = "圖片已過期"
    let imagePreview = "圖片預覽"
    let imageClose = "關閉預覽"
    func outputSize(_ pt: Int) -> String { "輸出字級 \(pt)pt——按 ⌘J 看" }
    func foldedTools(_ count: Int) -> String { "\(count) 個動作" }
    func outputOrder(newestFirst: Bool) -> String {
        newestFirst ? "最新的在最上面" : "最舊的在最上面"
    }
    func backlogNow(_ count: Int) -> String { "現在\(count)" }
    func dropped(_ count: Int) -> String {
        count == 1 ? "路徑加進去了——Claude Code 會自己讀" : "加了 \(count) 個路徑"
    }
    func stackConfirm(_ command: String) -> String { "再按一次就執行：\(command)" }
    let hintStacks = "伺服器"
    func stackTip(up: Int, total: Int) -> String { "\(total) 個伺服器，\(up) 個活著——⌘S 打開清單" }
    let stackTipUnknown = "這個專案有伺服器，但它的狀態指令還沒被信任——⌘S"
    let stackUntrusted = "尚未信任"
    let stackExit = "離開碼"
    let stackActionStart = "啟動"
    let stackActionRestart = "重啟"
    let stackActionStop = "停止"
    let stackActionLogs = "紀錄"
    let stackLogAll = "全部"
    let stackLogBack = "逐字稿"
    let stackActionAllow = "允許"
    let stackActionAgain = "再按一次"
    func sessionTip(index: Int, total: Int) -> String { "第 \(index) 個 session，共 \(total) 個——⌘K 切換" }
    let sessionWaiting = "在等你回答"
    let sessionAgents = "{n} 個在背景"
    let sessionShellOne = "1 個 shell 在跑"
    let sessionShellMany = "{n} 個 shell 在跑"
    let sessionWaitedOnByOne = "1 個在等你放行"
    let sessionWaitedOnByMany = "{n} 個在等你放行"
    let islandDone = "跑完了"
    let islandAllSessions = "所有 session⋯"
    func statusWaiting(_ labels: [String]) -> String {
        labels.count == 1 ? "\(labels[0]) 在等你回答"
                          : "\(labels.count) 個 session 在等你回答"
    }
    func statusWorking(_ count: Int) -> String { "\(count) 個在跑" }

    let settingsTitle = "Clawdline 設定"
    let settingsGeneral = "一般"
    let settingsBar = "輸入條"
    let settingsReading = "閱讀"
    let settingsVoice = "語音輸入"
    let settingsHotkey = "快速鍵"
    let settingsRecording = "按下按鍵……"
    let settingsScope = "在哪裡生效"
    let settingsScopeGlobal = "所有 app"
    let settingsScopeHint = "留空就是到處都能按，所以把最後一個移掉，上面那個開關就會自己打開——再把它關掉，清單就回來了。設定檔裡存的是 bundle id，自己手動編輯的清單一樣有效。"
    let settingsScopeAdd = "加入 app……"
    let settingsScopeChoose = "選擇其他 app……"
    let settingsScopeRunning = "現在開著的"
    let settingsScopeRemove = "移除"
    let settingsLanguage = "語言"
    let settingsReopen = "輸入條跟著終端機出現和收起"
    let settingsReopenHint = "從終端機切到別的地方，輸入條就收起來；切回終端機，它就回來。Esc 才是「這次用完了」的意思。"
    let settingsFollow = "終端機顯示輸入條指著的那個 session"
    let settingsFollowHint = "它會把那個 session 的分頁選起來。它不會把終端機叫到最前面——不然每按一次 Tab，鍵盤就從你正在打字的那個框裡跑掉了。"
    let settingsCodexAutoName = "自動命名新的 session"
    let settingsCodexAutoNameHint = "每個尚未命名的 session 會由你選的助理跑一次小型 turn。它使用第一則需求、消耗該助理的額度，而且不會蓋掉你自己取的名稱。"
    let settingsNotch = "住在瀏海裡"
    let settingsNotchHint = "在鏡頭那塊住一隻角色。關掉就是真的關掉——什麼都不畫，視窗也不會建立。"
    let settingsPosition = "在螢幕上的高度"
    let settingsWidth = "寬度"
    let settingsOpacity = "卡片不透明度"
    let settingsShow = "顯示"
    let settingsPaneHeight = "面板高度"
    let settingsTextSize = "文字大小"
    let settingsPaneFont = "面板字型"
    let settingsBlur = "背後模糊"
    let settingsNewestFirst = "最新的在最上面"
    let settingsEngine = "辨識引擎"
    let settingsSettle = "停頓多久算一句話結束"
    let settingsStop = "安靜多久算整段結束"
    let settingsAuto = "自動"
    let settingsTranscript = "對話記錄"
    let settingsTerminal = "終端機畫面"
    let settingsOff = "關閉"
    let settingsHooks = "Claude Code Hook"
    let settingsHooksHint = "裝上之後，一輪對話開始、結束、或是需要你回答的當下，Claude Code 會直接說一聲，不必等 Clawdline 下一次去看。每一次判讀仍然來自畫面，這裡只決定判讀發生得多快。"
    let settingsHooksInstall = "安裝"
    let settingsHooksRemove = "移除"
    let settingsHooksOff = "未安裝——狀態全部從畫面讀"
    let settingsHooksOn = "已安裝——還沒有 session 回報過"
    let settingsHooksLive = "已安裝，session 正在回報"
    let settingsStateHook = "session 換狀態的時候"
    let settingsStateHookHint = "只要有 session 開始跑、跑完、或是要問你話，Clawdline 就會執行這個：你自己的程式，細節放在它的環境變數裡。它寫在設定檔而不是這裡，因為那是一串 argv、不是一行命令列——路徑裡有空格，它也還是一整個路徑。"
    let settingsRemote = "遠端"
    let settingsRemoteServe = "讓瀏覽器或你的手機看得到你的 session"
    let settingsRemoteHint = "關著的時候，這台 Mac 以外的東西什麼都碰不到。打開之後，session 清單就在 127.0.0.1 上讀得到——給這裡的瀏覽器，給隔著通道連進來的手機，給一支腳本。交出去的是儲存庫名稱、分支和工作標題，所以在你開口之前，它一直是關著的。"
    let settingsRemoteDevices = "已配對的裝置"
    let settingsRemoteNoDevices = "還沒有——這台 Mac 以外的東西什麼都讀不到"
    let settingsRemoteRevokeAll = "全部斷開"
    let settingsRemoteOpen = "用瀏覽器打開"
    let pairingIgnore = "忽略"
    func pairingAsks(_ device: String) -> String { "\(device) 想跟這台 Mac 配對" }
    func pairingCode(_ code: String) -> String {
        """
        在它上面輸入這組代碼：

        \(code)

        兩分鐘內有效。如果剛才不是你要求的，不用理會——對方沒有這組代碼，就完成不了。
        """
    }
    let settingsTunnel = "從任何地方連到這台 Mac"
    let settingsTunnelQuick = "自動產生的網址"
    let settingsTunnelNamed = "我自己的網域"
    let settingsTunnelHostname = "主機名稱"
    let settingsTunnelHint = "透過 cloudflared 從這台 Mac 往外連出去——不必開通訊埠轉發，你的網路上也沒有東西在聽。要先配對過一台裝置它才會啟動，因為通道後面就是這台 Mac 上每一個儲存庫名稱、每一個工作標題。"
    let settingsRemoteWrite = "讓配對過的裝置寫進 session"
    let settingsRemoteWriteHint = "關著的時候，配對過的裝置只能讀。打開之後，它可以把文字送進 session，也可以開新的 session——那就是在這台 Mac 上執行程式碼，因為 Claude Code 做的就是這件事。這跟上面那一題是兩回事，所以它是另一個開關。"
    let settingsRemotePhone = "配對手機……"
    let settingsRemotePhoneHint = "顯示一張可以掃的 QR code。它自己帶著一把鑰匙，所以就算被拍走，被拍走的也只是一台會出現在上面清單裡、隨時拿得掉的裝置——不是這台 Mac 自己的鑰匙。"
    let pairingScanTitle = "用手機掃這張 QR code"
    let pushWaiting = "在等你回答"
    let pushTest = "這是一則測試通知，該接的都接好了。"
    let pushFinished = "跑完一段長工作了"
    let pushDeployOk = "deploy 成功了"
    let pushDeployFail = "deploy 失敗了"
    func pushChildWaiting(minutes: Int?) -> String {
        guard let minutes else { return "有子 session 在等回答" }
        return "有子 session 在等回答，還剩 \(minutes) 分鐘"
    }
    func pushBatchDone(done: Int, failed: Int) -> String {
        let all = "跑完 \(done) 件任務"
        return failed == 0 ? all : "\(all)，\(failed) 件失敗"
    }
    let settingsPushFinish = "一段長工作跑完時通知我"
    let settingsPushFinishHint = "只有跑超過兩分鐘的才算。"
    let settingsSmartNotifications = "智慧通知"
    let settingsSmartNotificationsHint = "用 Haiku 說明剛完成了什麼；產生失敗時仍會送出原本的通知。"
    func pushCoalesced(count: Int) -> String { "\(count) 件工作同時完成" }
    let settingsSmartHealthIdle = "還沒有嘗試過智慧通知。"
    func settingsSmartHealth(attempts: Int, successes: Int) -> String {
        "\(attempts) 次嘗試中，有 \(successes) 次送出了模型寫的句子。"
    }
    func settingsSmartHealthFailure(reason: String, time: String) -> String {
        "最近一次退回原本通知在 \(time)：\(reason)。"
    }
    func settingsSmartTimeout(seconds: Int) -> String { "Claude 超過 \(seconds) 秒沒完成，被中止" }
    let settingsSmartQueueFull = "同時完成的數量超過佇列容量"
    let settingsSmartModelFailed = "Claude 沒有回覆可用的內容"
    let settingsSmartNoSource = "沒有可摘要的內容"
    let settingsSmartMissing = "找不到 claude 執行檔"
    let settingsPushDeploy = "deploy 結束時通知我"
    let settingsPushDeployHint = "成功和失敗都會通知。"
    let settingsAgentNotify = "允許 agent 主動推播"
    let settingsAgentNotifyNote = "只管 agent 主動送出的內容；工作完成、deploy 與其他通知都不受影響。"
    let settingsOrchestrator = "派工作給別的 session"
    let settingsOrchestratorEnabled = "讓一個 session 把工作派給另一個"
    let settingsOrchestratorEnabledHint = "帶著 clawdline skill 的 session 可以開一個新分頁、把指示打進去，做完再回頭跟它說一聲。關著的時候，每一次派工都會被擋下來——已經在跑的不會被停掉。"
    let settingsOrchestratorMax = "同時最多幾個子 session"
    let settingsOrchestratorMaxHint = "預設五個，一個 session 算一份，不是整台 Mac 算一份。每一個都是一個終端機分頁，裡面有一個 assistant 在做事。"
    let settingsOrchestratorPermission = "child 可以自己走多遠"
    let settingsOrchestratorPermissionHint = "child 的分頁沒有人在看，停下來等核准的 session 會一路停到逾時——而派出去的 session 整份工作就是跑指令和寫檔案，所以只要不是最後一格，它就會停在某個地方。任務可以要求比這裡保守，但不能超過。"
    let settingsOrchestratorPermissionAsk = "每一步都先問"
    let settingsOrchestratorPermissionEdits = "寫檔案不用問"
    let settingsOrchestratorPermissionFull = "都不要問"
    let settingsOrchestratorNotify = "做完之後回報給發派的 session"
    let settingsOrchestratorNotifyHint = "工作結束的時候，往那個 session 裡打一行字。"
    let settingsOrchestratorClose = "子 session 回報之後"
    let settingsOrchestratorCloseHint = "回報過了就把它的分頁關掉——逾時的那個會留著，讓你自己看是怎麼回事。"
    let settingsOrchestratorCloseNow = "馬上把分頁關掉"
    let settingsOrchestratorCloseLinger = "三分鐘後再關"
    let settingsOrchestratorCloseKeep = "留著不要關"
    let settingsOrchestratorPolicy = "派工的規矩"
    let settingsOrchestratorPolicyHint = "每次派工 Clawdline 都會讀這份規矩，並且抄進每一個「還能再往下派」的 child 的指示裡：用哪個助理、用哪個模型、整張圖該長什麼樣。留空 ＝ 沒有規矩。"
    let settingsOrchestratorPolicyEdit = "編輯規矩"
    func settingsOrchestratorPolicyOn(_ lines: Int) -> String { return "生效中——\(lines) 行" }
    let settingsOrchestratorPolicyOff = "沒有規矩——每次派工由派的人自己決定"
    let settingsSchedules = "排程"
    let settingsSchedulesEmpty = "還沒有任何排程。用下面的「新增排程」做一個。"
    let settingsScheduleNew = "新增排程"
    let settingsScheduleEdit = "編輯"
    let settingsScheduleSave = "儲存"
    let settingsScheduleDelete = "刪除"
    let settingsScheduleRun = "立即執行"
    let settingsScheduleReveal = "在 Finder 顯示"
    let settingsSchedulesFolder = "開啟 schedules 資料夾"
    let settingsScheduleNext = "下次"
    let settingsScheduleLast = "上次"
    let settingsScheduleNever = "尚未執行"
    let settingsScheduleStarted = "已開始執行。"
    let settingsScheduleActive = "上一個排程工作還在執行中。"
    let webScheduleMissed = "上次錯過"
    let webScheduleNoNext = "沒有排定下次執行。"
    func childAnnounce(_ title: String) -> String { "收到 Clawdline 派來的任務：\(title)——開始處理。" }
    func settingsSeconds(_ value: Double) -> String { String(format: "%.1f 秒", value) }

    let webConnLive = "已連上"
    let webConnConnecting = "連線中"
    let webConnRetrying = "{n} 秒後重試"
    let webConnOffline = "離線"
    let webConnLocked = "未配對"
    let webConnTipLive = "正從 app 串流過來"
    let webConnTipLocked = "這個瀏覽器還沒跟那台 Mac 配對過"
    let webConnTipDown = "沒連上——點一下馬上試"

    let webCountWorking = "{n} 個在跑"
    let webCountWaiting = "{n} 個在等你"
    let webCountUnreadable = "{n} 個讀不到"
    let webCountQuietOne = "{n} 個 session，都很安靜"
    let webCountQuietMany = "{n} 個 session，都很安靜"
    let webCountNone = "沒有 session"

    let webFilterPlaceholder = "用工作、專案或 tty 篩選"
    let webFilterLabel = "篩選 session"
    let webListLabel = "Claude Code session 清單"
    let webPull = "下拉重新整理"
    let webPullRelease = "放開就重新整理"
    let webPullBusy = "重新整理中⋯"
    let webEmptyFilterTitle = "沒有東西符合「{q}」"
    let webEmptyFilterHint = "Esc 清掉篩選"
    let webEmptyLockedTitle = "這台裝置還沒配對"
    let webEmptyLockedHint = "app 回了 401——在 Mac 上的 Clawdline 裡配對"
    let webEmptyNoneHint = "在終端機裡開一個，它就會出現在這裡"
    let webEmptyWaitTitle = "在等 app"
    let webEmptyWaitHint = "串流上還沒有東西進來"
    let webStateUnreadable = "畫面讀不到"
    let webStateWorking = "在跑"
    let sessionWorkReady = "可接新工作"
    let sessionWorkUnknown = "狀態未知"
    let sessionWorkHolding = "自行推進中"
    let sessionWorkOwed = "欠一個決定"
    let sessionWorkSelfStated = "自述"
    let sessionWorkMilestone = "已交付，等待驗收"
    let sessionWorkComplete = "已驗收完成"
    let closeabilitySafe = "可以安全關閉"
    let closeabilityBlocked = "還有 {n} 項未了結"
    let closeabilityBlockedOne = "還有 1 項未了結"
    let closeabilityBlockedMany = "還有 {n} 項未了結"
    let closeabilityNeedsAttestation = "等這個 session 自己確認"
    let closeabilityUnknown = "無法判斷能否關閉"
    let closeabilityWhy = "不能關閉的原因"
    let closeabilityMoverSelf = "由這個 session 推進"
    let closeabilityMoverPerson = "由你推進"
    let closeabilityMoverSession = "由另一個 session 推進"
    let closeabilityMoverBroker = "重新讀一次才知道"
    let closeabilityNotProven = "broker 無法證明這個 session 可以安全關閉。"
    let closeabilityAttestationExplanation = "這不是系統發現工作尚未完成。Clawdline 能檢查的項目都已經通過，但這個 session 還沒確認是否留有本機修改、未交付事項或 Clawdline 以外的工作。請先回到這個 session 檢查，再決定是否關閉。"
    let closeabilityTechnicalDetails = "技術細節"

    let webBack = "清單"
    let webBackLabel = "回到 session 清單"
    let webNoSessionOpen = "沒有打開的 session"
    let webOrderTip = "把對話記錄反過來（r）"
    let webShowOnMac = "在 Mac 上顯示"
    let webShowOnMacTip = "把這個 session 的終端機叫到 Mac 最前面"
    let webShowOnMacOff = "伺服器回報 write: false——現在什麼都送不出去"
    let webShowOnMacAsked = "已經請 Mac 把它叫到前面"
    let webSessionActions = "Session 快捷動作"
    let webSessionGit = "Git 變更"
    let webGitTitle = "Git 變更"
    let webGitClean = "工作目錄沒有變更"
    let webGitNotRepo = "不是 Git 儲存庫"
    let webGitFailed = "無法讀取 Git 變更"
    let webGitRefresh = "重新整理"
    let webGitClose = "關閉"
    let webGitStaged = "已暫存"
    let webGitUnstaged = "未暫存"
    let webGitUntracked = "未追蹤"
    let webGitConflict = "衝突"
    let webEndSession = "關閉 session"
    let webConfirmActionTitle = "要執行 {action} 嗎？"
    let webConfirmActionSay = "這會把 {action} 送進目前的 session。"
    let webConfirmEndTitle = "要關閉這個 session 嗎？"
    let webConfirmEndSay = "Agent 會先結束，接著關閉它的終端機分頁。"
    let webConfirmEndLoses = "關閉會一併終止："
    let webClawdfatherCreateLabel = "把新的 session 命名為 Clawdfather"
    let webClawdfatherIs = "這個 session 就是 {name}"
    let webClawdfatherRegisterAsk = "請把這個新的 session 註冊成這台 Mac 的 Clawdfather，也就是 machine coordinator。你的 terminal-neutral session id 是 {id}。先用 ~/.config/clawdline/orchestrator-token 裡的 orchestrator token 讀 coordinator 紀錄。只有在完全沒有 coordinator 登記時，才照 docs/orchestrator.md 裡「Becoming Clawdfather」的註冊那一段做。只要已經有登記的 coordinator，就算它離線了，也不要取代它。做完告訴我結果。"
    let webClawdfatherRegisterSent = "已經請新的 session 去當 Clawdfather"
    let webClawdfatherRegisterLate = "新的 session 沒能及時就緒，來不及命名為 Clawdfather。"
    let webClawdfatherRegisterBlocked = "這台 Mac 的 coordinator 紀錄讀不出來，所以完全不會去動它。"
    let webCoordSectionObserve = "觀察"
    let webCoordSectionCoordinate = "協調"
    let webCoordSectionPresence = "在線狀態"
    let webCoordSectionAdmin = "管理"
    let webCoordCmdStatusReport = "狀態報告"
    let webCoordCmdStatusReportSay = "讀取 Clawdfather 目前的狀態與進行中的職責。"
    let webCoordCmdSinceAway = "你離開之後"
    let webCoordCmdSinceAwaySay = "讀取自上一個回歸點以來記錄的變更與決定。"
    let webCoordCmdDuplicates = "重工、衝突與歸屬"
    let webCoordCmdDuplicatesSay = "檢視重複的工作、互相衝突的認領與目前的歸屬。"
    let webCoordCmdLandingClosure = "落地收尾"
    let webCoordCmdLandingClosureSay = "讀取已通過複審、仍在等 root 落地的交付。"
    let webCoordCmdCoordinateWork = "協調工作"
    let webCoordCmdCoordinateWorkSay = "就進行中的工作草擬協調步驟。"
    let webCoordCmdDispatch = "派出獨立工作"
    let webCoordCmdDispatchSay = "預覽一次會開出獨立 child session 的派工。"
    let webCoordCmdAsk = "問 Clawdfather"
    let webCoordCmdAskSay = "草擬一個要請 Clawdfather 判斷的問題。"
    let webCoordCmdQuietWatch = "安靜監看"
    let webCoordCmdQuietWatchSay = "草擬一個不發「有人在等」警示的安靜監看請求。"
    let webCoordCmdScope = "範圍與權限"
    let webCoordCmdScopeSay = "讀取 Clawdfather 目前的範圍與被授予的權限。"
    let webCoordCmdStop = "停止 Clawdfather"
    let webCoordCmdStopSay = "預覽停止 Clawdfather。"
    let webCoordCmdReconnect = "重新連上 Clawdfather"
    let webCoordCmdReconnectSay = "預覽重新連上 Clawdfather。"
    let webCoordCmdDeepAudit = "深度狀態盤點"
    let webCoordCmdDeepAuditSay = "請 Clawdfather 稽核相關 Session 的進行中工作、交付與待決事項。"
    let webCoordTokenExpected = "預期 Token 負擔：{effort}"
    let webCoordTokenLow = "低"
    let webCoordTokenMedium = "中"
    let webCoordTokenHigh = "高"
    let webCoordTokenUnknown = "未知"
    let webCoordAuditPreview = "這是高 Token、多 Session 的請求，目前尚未送出。確認後才會把完整稽核指示送到這個確切的 Clawdfather Session。第一版由 Agent 執行，broker 尚無持久 run 紀錄。"
    let webCoordAuditWhyOffline = "Clawdfather 已離線，無法送出稽核請求。"
    let webCoordAuditWhyDisconnected = "這個瀏覽器已離線，無法送出稽核請求。"
    let webCoordAuditWhyNoWrite = "這個瀏覽器目前沒有傳送／寫入能力。"
    let webCoordAuditSending = "正在送出請求…"
    let webCoordAuditSent = "已送出稽核請求；這張收據不代表稽核已完成。"
    let webCoordAuditFailed = "未送出稽核請求（{code}）：{message}"
    let webCoordEffectRead = "唯讀"
    let webCoordEffectAdvisory = "建議性"
    let webCoordEffectSpawns = "會開 session"
    let webCoordEffectMutation = "會改狀態"
    let webCoordStateAvailable = "可用"
    let webCoordStateDraft = "草稿"
    let webCoordStateUnavailable = "不可用"
    let webCoordStatePreview = "預覽"
    let webCoordStateDisabled = "已停用"
    let webCoordOnline = "{name} 在線"
    let webCoordOffline = "{name} 離線"
    let webCoordControlsTitle = "{name} 控制面板"
    let webCoordOpenControls = "打開 {name} 控制面板"
    let webCoordEmpty = "沒有收到任何這個頁面認得的 Clawdfather 指令。"
    let webCoordDisabledFallback = "Clawdfather 已停用這個指令。"
    let webCoordPreviewTitle = "Clawdfather 指令"
    let webCoordPreviewNone = "還沒選擇指令；什麼都沒有送出。"
    let webCoordPreviewMutation = "僅預覽——什麼都沒有送出。在 Clawdfather 指令 API 接上之前，確認鈕維持不可按。"
    let webCoordPreviewDraft = "僅離線草稿——什麼都沒有送出，也不代表 Clawdfather 的判斷。"
    let webCoordPreviewSpawn = "僅預覽——沒有開出任何 session。"
    let webCoordPreviewContract = "這裡只展示這個指令的合約；什麼都沒有送出。"
    let webCoordWhyNoCommandRoute = "還沒有任何路由能把這個面板的指令送進 session，所以什麼都送不出去。"
    let webCoordWhyNoReturnLedger = "這台 Mac 還沒有記錄回歸點，所以沒有東西可以對照著讀。"
    let webCoordWhyDeviceCannotSpawn = "配對裝置永遠不能開 session——這道分隔是刻意的，這顆按鈕不會跨過去。"
    let webCoordWhyMachineTokenOnly = "重新連上需要 Mac 自己的 orchestrator token，配對裝置刻意不持有它。"
    let webCoordReadFailed = "讀不到 Clawdfather 的 Bearings。"
    let webCoordActiveTasks = "{n} 個任務進行中"
    let webCoordPendingLandings = "{n} 個交付等著落地"
    let webCoordOpenWaits = "{n} 個檔案等待尚未解除"
    let webCoordCountUnknown = "{n} 個狀態未知"
    let webCoordStaleSessions = "Mac 的 session 快照已過時；這些數字可能是舊的。"
    let webCoordUnknown = "狀態未知"
    let webCoordWaitingList = "在等別人"
    let webCoordBlockingList = "握著別人在等的檔案"
    let webCoordAllQuiet = "目前沒有東西被卡住、被搶或沒人認領。"
    let webCoordNoLandings = "沒有交付在等落地。"
    let webCoordUnregistered = "這台 Mac 上沒有登記任何 Clawdfather。"
    let webCoordScopeLine = "{name} 協調這台 Mac——machine 範圍。"
    let webCoordScopeDevice = "在這個面板上，Clawdfather 只能被讀取。送出工作、開 session、改機器狀態都需要 Mac 自己的憑證，在這裡一律停用。"
    let webClosing = "關閉中⋯"
    let webCancel = "取消"
    let webConfirm = "確認"
    let webReviewBeforeClosing = "回到 session 檢查"
    let webConfirmEndAnyway = "仍要關閉"
    let webPickSession = "在左邊挑一個 session。"
    let webReading = "讀取中⋯"
    let webLoading = "載入中⋯"
    let webTranscriptFailed = "讀不到對話記錄"
    let webWhoYou = "你"
    let webWhoTool = "工具"
    let webNoticeTask = "任務"
    let webNoticeCompleted = "任務已完成"
    let webNoticeFailed = "任務失敗"
    let webNoticeTimedOut = "任務逾時"
    let webNoticeCancelled = "任務已取消"
    let webNoticeCouldNotStart = "任務無法啟動"
    let webNoticeFinished = "任務已結束"
    let webNoticeWorkspaceOverlap = "工作區重疊"
    let webNoticeNoSiblings = "沒有其他同層任務仍在執行。"
    let webNoticeOneSibling = "仍有 {n} 個同層任務在執行。"
    let webNoticeManySiblings = "仍有 {n} 個同層任務在執行。"
    let webNoticeClaimsReleased = "路徑宣告已釋放；child 的分頁可能仍會寫入。"
    let webNoticeFileWaitRequested = "等待檔案釋放"
    let webNoticeFileWaitReleased = "檔案已釋放"
    let webNoticeHandoffPickedUp = "交接已接手"
    let webNoticeHandoffNeedsDelivery = "交接需要手動投遞"
    let webNoticeRecheckGit = "整合前請重新檢查 HEAD、status 與 diff。"
    let webPending = "還在等 Mac⋯"
    let webAttachedImage = "已附上 {n} 張圖"
    let webAttachedImages = "已附上 {n} 張圖"
    let webSteps = "{n} 個動作"
    let webJustNow = "剛剛"
    let webMinutesAgo = "{n} 分鐘前"
    let webCodeCopy = "複製這段程式碼"
    let webCodeCopied = "已複製程式碼。"
    let webCodeCopyFailed = "複製失敗，請改用手動選取。"

    let webSend = "送出"
    let webAttach = "附一張圖"
    let webRemoveShot = "移除 {name}"
    let webWriteOpen = "先打開一個 session 才能寫進去。"
    let webWriteOff = "*現在不能送*——伺服器回報 `write: false`。這個框是接好的，那邊一改它就自己開。"
    let webShotsOnlyPictures = "只有圖片可以跟著訊息一起送"
    let webShotsTooMany = "一則訊息最多帶 {n} 張圖"
    let webShotTooBig = "這張圖太大了，縮過也送不出去"
    let webShotsTooBig = "這幾張圖加起來太大，送不出去"
    let webShotUnreadable = "這張圖讀不到"
    let webShotNeedsSession = "先打開一個 session 才能送圖過去"

    let webVoiceStart = "用說的寫一則訊息"
    let webVoiceStop = "停下來，轉成文字"
    let webVoiceDone = "完成"
    let webVoiceListening = "聽著⋯ {t}"
    let webVoiceReading = "Mac 正在轉文字⋯ {n} 秒"
    let webVoiceSlow = "這台 Mac 重開機之後的第一次要先載模型——大概十二秒。"
    let webVoiceLimit = "錄音在 {n} 分鐘停了，一次最長就是這麼久。先把錄到的轉出來。"
    let webVoiceEmpty = "那一段裡沒聽到東西。"
    let webVoiceTooShort = "那段太短了，聽不出東西。"
    let webVoiceDenied = "麥克風被拒絕了。到這個瀏覽器針對這個網站的設定裡把它開回來。"
    let webVoiceNoMic = "這台裝置上找不到麥克風。"
    let webVoiceInUse = "麥克風忙著——這台裝置上有別的東西佔著它。"
    let webVoiceInsecure = "麥克風要 https，而這一頁沒有。通道會給你一個；區域網路上的普通位址不會。"
    let webVoiceUnsupported = "這個瀏覽器沒辦法錄音。"
    let webVoiceBusy = "已經有一段在轉、一段在等了。等一下再試。"
    let webVoiceNoBinary = "Mac 上沒有裝 Whisper，那邊沒有東西可以拿來轉文字。"
    let webVoiceNoModel = "Mac 上有 Whisper，但沒有模型可以讀。它只要 `~/.cache/whisper` 裡有一個 ggml 檔就行。"
    let webVoiceFailed = "那一段轉不出文字。"

    let webHintMove = "移動"
    let webHintOpen = "打開"
    let webHintFilter = "篩選"
    let webHintPane = "面板"

    let webKeysLabel = "鍵盤快速鍵"
    let webKeysTitle = "鍵盤"
    let webKeysMove = "在清單裡上下移動——`j` 和 `k` 一樣"
    let webKeysOpen = "打開選起來的 session"
    let webKeysFilter = "篩選清單"
    let webKeysEscape = "先清掉篩選，再退回去"
    let webKeysList = "游標回到 session 清單"
    let webKeysPane = "顯示或隱藏對話記錄"
    let webKeysEnds = "對話記錄的最上面或最下面"
    let webKeysReverse = "把對話記錄的順序反過來"
    let webKeysThis = "這張卡"
    let webKeysFoot = "打進文字框裡的東西就留在文字框裡——你在打字的時候，快速鍵會先讓開。"

    let webDoorLabel = "配對這個瀏覽器"
    let webDoorAskLede = "這個瀏覽器還沒被放進來。"
    let webDoorAskFine = "按下要求配對，六位數字會出現*在那台 Mac 上*——它刻意不放在給這一頁的回應裡。只有人在那台機器旁邊才完成得了，這正是重點，不是刁難。"
    let webDoorName = "幫這台裝置取個名字"
    let webDoorAsk = "要求配對"
    let webDoorToPassword = "改用密碼登入"
    let webDoorCodeLede = "看那台 Mac。"
    let webDoorCodeFine = "Clawdline 正在顯示六位數字，還有 {left}。打在這裡。"
    let webDoorTwoMinutes = "兩分鐘"
    let webDoorDigit = "第 {n} 位"
    let webDoorConfirm = "配對這台裝置"
    let webDoorRestart = "重來一次"
    let webDoorPasswordLede = "用密碼登入。"
    let webDoorPasswordFine = "就是 Mac 上 Clawdline 裡「設定 → 遠端」設的那組。沒設過的話，配對就是進來的方法。"
    let webDoorPassword = "密碼"
    let webDoorPasswordGo = "登入"
    let webDoorToPair = "改用配對代碼"
    let webDoorAsking = "正在問那台 Mac⋯"
    let webDoorAskFailed = "問不到那台 Mac。"
    let webDoorRateLimited = "每問一次，那台 Mac 上就跳一次提示，所以十分鐘只有三次。"
    let webDoorSixDigits = "六位數字。"
    let webDoorChecking = "檢查中⋯"
    let webDoorFinished = "這次配對結束了——錯了五次。等你人在 Mac 旁邊再問一次。"
    let webDoorWrongCode = "這組代碼不對。"
    let webDoorNeedPassword = "先填密碼。"
    let webDoorWrongPassword = "密碼不是這個。"
    let webDoorExpired = "這組代碼過期了。再問一次，Mac 上就會出現新的。"
    let webDoorPaired = "配對好了——這個瀏覽器進來了"

    let webOffline = "連不到 Clawdline。它還在那台 Mac 上跑著嗎？"
    let webNotJSON = "伺服器送回來的東西不是 JSON"
    let webRequestFailed = "請求失敗"

    let webNotifyGo = "通知我"
    let webNotifyAsking = "詢問中⋯"
    let webNotifyStop = "停掉"
    let webNotifyStopping = "停止中⋯"
    let webNotifyOff = "有 session 在等你回答的時候"
    let webNotifyOn = "這台裝置已經訂閱了。要通知哪些事，在 Mac 上決定。"
    let webNotifyBlocked = "這個網站的通知被擋掉了。那個開關在瀏覽器自己的設定裡，不在這裡。"
    let webNotifyUnsupported = "這個瀏覽器沒辦法顯示通知。"
    let webNotifyHomeScreen = "把 clawdline 加到主畫面，再從那裡打開——iOS 只把通知送給住在那裡的 app。"
    let webNotifyOnFailed = "通知打不開"
    let webNotifyOffFailed = "通知關不掉"

    let webSettings = "設定"
    let webSettingsNotify = "通知"
    let webSettingsAssistantIcons = "助理圖示"
    let webSettingsAssistantIconsSay = "在對話中，於 Claude 或 Codex 名稱前顯示其圖示。"
    let webSettingsAssistantIconsShow = "顯示圖示"
    let webSettingsVersion = "版本 {v}"
    let webClose = "關閉"
    let webNotifySheetOff = "有 session 在等的時候，不會通知這台裝置。"
    let webNotifyTest = "送一則測試"
    let webNotifyTestSent = "送出去了——馬上就會到這台裝置。"
    let webNotifyTestNone = "那台 Mac 上沒有這台裝置的訂閱。把通知關掉再打開，這個瀏覽器就會重新註冊一組。"
    let webNotifyTestFailed = "測試通知送不出去"
    let webSending = "送出中⋯"
    let webSendTip = "Return 送出 · Shift-Return 換行"
    let webStart = "開一個 session"
    let webStartLabel = "在某個專案裡開一個 session"
    let webStartPick = "要在哪裡開？"
    let webStartWith = "要用哪一個開？"
    let webStartEmpty = "還沒有地方可以開。在 Mac 上跑過一次 Claude Code，它就會出現在這裡。"
    let webStartFilter = "篩選專案"
    let webStarting = "正在開分頁⋯"
    let webStartWaiting = "開好了。等它出現⋯"
    let webStartSlow = "分頁已經開了，但那個 session 還沒回報。去 Mac 上看一下。"
    let webStartFailed = "這個開不起來。"
    let webStartGone = "那個專案已經不在 Mac 上了。"
    let webStartTerminalClosed = "{app} 沒有在 Mac 上跑。先在那邊打開它，再試一次。"
    let webStartTerminalUnsupported = "從這裡沒辦法在 {app} 裡開 session。在它裡面跑 tmux 就可以了。"
    let webStartOff = "從遠端開 session 是關著的。在 Mac 上的「設定 → 遠端」可以打開。"
    let webResumeWith = "接續之前的"
    let webResumePick = "要接哪一段？"
    let webResumeFilter = "篩選對話"
    let webResumeEmpty = "那個專案還沒留下任何紀錄。"
    let webResumeLive = "開著"
    let webResumeBack = "換一個專案"
    let webResumeGone = "那段對話已經不在 Mac 上了。"
    let webResumeClaudeOnly = "只有 Claude Code 留得下能接續的對話。"
    let webResuming = "正在接回去⋯"
    let webResumeCapped = "比這些更早的不在這份清單上。"
    let webCommand = "說要開什麼"
    let webCommandLabel = "用說的開一個 session"
    let webCommandSay = "按下面的「開始」之前，什麼都不會送出去。"
    let webCommandHeard = "要它做什麼？"
    let webCommandThinking = "思考中⋯"
    let webCommandDraft = "草稿"
    let webCommandWhere = "專案"
    let webCommandWith = "助理"
    let webCommandModel = "模型"
    let webCommandFirst = "第一則訊息"
    let webCommandGo = "開始"
    let webCommandUnsure = "不確定是哪個專案，自己選一個。"
    let webCommandFailed = "沒辦法把它變成草稿。"
    let webCommandNoPlanner = "這台 Mac 沒有 Claude Code，沒辦法把它變成草稿。"
    let webCommandBusy = "已經有一句在變成草稿了，等一下再試。"
    let webCommandEmpty = "沒聽到東西"
    let webScheduleNew = "新增排程"
    let webScheduleEdit = "編輯排程"
    let webScheduleNewSay = "按下面的「建立」之前，不會排定任何東西。"
    let webScheduleTitle = "標題"
    let webScheduleAt = "時間"
    let webScheduleOn = "星期"
    let webScheduleWhere = "專案"
    let webScheduleWith = "助理"
    let webScheduleFirst = "第一則訊息"
    let webScheduleMore = "更多"
    let webScheduleModel = "模型"
    let webScheduleWhenDone = "結束之後關掉分頁"
    let webScheduleCloseSuccess = "成功時"
    let webScheduleCloseAlways = "一律"
    let webScheduleCloseNever = "不要關"
    let webScheduleEnabled = "啟用"
    let webScheduleDisabled = "停用"
    let webScheduleNotify = "失敗時通知我"
    let webScheduleCatchUp = "錯過了，幾小時內還要補跑"
    let webScheduleTimeout = "跑多久沒完就放棄（分鐘）"
    let webScheduleCreate = "建立"
    let webScheduleCreated = "已建立排程。"
    let webScheduleDispatchOff = "排程建好了，也有效，只是派工是關著的，不會有人執行它。在 Mac 上的「設定 → 遠端」可以打開。"
    let webScheduleFailed = "沒辦法建立排程。"
    let webScheduleSave = "儲存"
    let webScheduleSaved = "已儲存排程。"
    let webScheduleDelete = "刪除"
    let webScheduleDeleteAsk = "要刪除 {title} 嗎？沒有辦法復原。"
    let webScheduleDeleted = "已刪除排程。"
    let webScheduleNeedsTime = "沒聽到時間，自己填一個。"
    let webScheduleNeedsPlace = "不確定是哪個專案，自己選一個。"
    let webScheduleDaily = "每天"
    let webScheduleSun = "日"
    let webScheduleMon = "一"
    let webScheduleTue = "二"
    let webScheduleWed = "三"
    let webScheduleThu = "四"
    let webScheduleFri = "五"
    let webScheduleSat = "六"
    let webLinks = "連結"
    let webLinksTip = "這個專案可以從哪些地方打開"
    let webLinksPick = "這個專案能打開的地方，都在這裡。"
    let webLinksEmpty = "這個專案沒有任何可以打開的地方——沒有網站，沒有 deploy，也沒有伺服器在跑。"
    let webLinksFailed = "讀不到這個專案的連結。"
    let webLinksLocal = "只在那台 Mac 自己的網路裡才通。從這裡打不開。"
    let webLinksFile = "Mac 上的一個檔案。它在那邊打開，不在這個瀏覽器裡。"
    let webLinksCopy = "複製路徑"
    let webLinksCopied = "複製好了。"
    let webLinksCopyFailed = "這個瀏覽器不讓這一頁複製那個。"
    let webLinkOk = "正常"
    let webLinkFail = "出錯"
    let webLinkDown = "沒開"
    let webLinkRunning = "進行中"
    let webSessionInfo = "Session 資訊"
    let webInfoTitle = "關於這個 session"
    let webInfoEditTitle = "編輯 session 標題"
    let webInfoCopyTitle = "複製這個名字"
    let webInfoTitleSaved = "標題已儲存。"
    let webInfoTitleLocal = "標題已存進 Clawdline；下游名稱沒有跟著改。"
    let webInfoTitleQueued = "標題已存進 Clawdline；Codex 更新已排隊。"
    let webInfoTitleNotDurable = "標題已生效，但這台 Mac 沒能寫進設定檔；重開就會不見。"
    let webInfoTitleCloud = "session 標題只能在那台 Mac 上改，雲端連線改不了。"
    let webInfoSession = "這個 session"
    let webInfoAssistant = "助理"
    let webInfoModel = "模型"
    let webInfoSessionId = "Session ID"
    let webInfoDirectory = "目錄"
    let webInfoRunningFor = "已跑了"
    let webInfoStatus = "狀態"
    let webInfoWorkStatusMeaning = "這是這個 session 的工作狀態。一個勾表示已交付、等待驗收；兩個勾才表示已驗收完成。"
    let webInfoCloseabilityMeaning = "鑰匙表示這個 session 現在能不能安全關閉，與是否已交付是兩件不同的事。"
    let webInfoUsage = "Token 用量"
    let webInfoInput = "輸入"
    let webInfoOutput = "輸出"
    let webInfoCacheRead = "快取讀取"
    let webInfoCacheWrite = "快取寫入"
    let webInfoTotal = "合計"
    let webInfoCost = "估算費用"
    let webInfoNoUsage = "還找不到這個 session 的對話記錄。"
    let webInfoLimits = "方案額度"
    let webInfoLimitHit = "額度用完"
    let webInfoResets = "{when} 重設"
    let webInfoUnknown = "未知"
    let webInfoFiles = "檔案變化"
    let webInfoBranch = "分支"
    let webInfoStaged = "已暫存"
    let webInfoUnstaged = "已修改"
    let webInfoUntracked = "未追蹤"
    let webInfoConflict = "衝突"
    let webInfoClean = "沒有未 commit 的東西。"
    let webInfoNotRepo = "這不是一個 git repo。"
    let webInfoDeploy = "最近一次 deploy"
    let webInfoNoDeploy = "這個專案沒有 deploy 紀錄。"
    let webInfoFailed = "讀不到這個 session 的資訊。"
    let webInfoBusy = "Mac 正忙著讀別的 session，等一下再試。"
    let webInfoRefresh = "重新整理"
    let webInfoTokens = "tokens"
    let webInfoSwitchModel = "切換模型"
    let webInfoModelOther = "其他模型…"
    let webInfoModelSent = "已送出 /model {model}，確認中…"
    let webInfoModelBusy = "要等 session 閒置時才能切換模型。"
    let webInfoSwitchPermission = "切換權限模式"
    let webInfoPermissionAuto = "自動"
    let webInfoPermissionManual = "手動"
    let webInfoPermissionAcceptEdits = "接受編輯"
    let webInfoPermissionPlan = "計畫"
    let webInfoPermissionUnreadable = "讀不到目前的模式。"
    let webInfoPermissionSent = "已切換到「{mode}」，確認中…"
    let webInfoPermissionBusy = "正在送出權限模式切換。"
    let webInfoLimitsClaude = "Claude Code 只在額度用完時才會記下來，在那之前這裡沒有資料。"
    let webInfoCopied = "已複製 session id。"
    let webInfoAsOf = "截至 {when}"
    let webInfoWhyUnknown = "為什麼是未知、怎麼把數字接上"
    let webSettingsOrder = "對話記錄"
    let webSettingsOrderSay = "對話記錄要從哪一頭開始讀。每個 session 都算，鍵盤上按 `r` 也是同一件事。"
    let webAskLabel = "問了"
    let webAskAny = "這些選幾個都可以"
    let webWaitingTitle = "這個 session 在等你回答"
    let webWaitingSay = "Claude Code 正在 Mac 上顯示一個選單。Clawdline 還沒辦法從這裡讀選單，所以那些選項只在那個畫面上。"
    let webWaitingSend = "*從這裡送出，不會把你的回答打進選單裡*——它只會確認選單上反白的那一個，而那很少是你要的。這一題請在 Mac 上回答。"
    let webMenuSay = "點一個答案，它會直接送到那個 session。"
    let webMenuHighlighted = "反白中"
    let webMenuSent = "答案送出了。"
    let webAgents = "背景 agent"
    let webAgentsCount = "{n} 個在跑"
    let webAgentDone = "完成"
    let webAgentFailed = "失敗"
    let webShells = "背景 shell"
    let webShellTitle = "背景 shell"
    let webShellOpen = "看這個指令印了什麼"
    let webShellRunning = "還在跑"
    let webShellEnded = "已結束"
    let webShellQuiet = "還沒印出任何東西。"
    let webShellFailed = "讀不到這個指令的輸出。"
    let webShellClose = "關閉"
    let webShellStop = "停掉"
    let webShellStopTitle = "要停掉這個指令嗎？"
    let webShellStopSay = "{command} 還在跑。會先請它自己收尾，五秒後還沒停就直接砍掉。它已經做完的事不會回復。"
    let webShellStopped = "已經請它停下來。"
    let webShellStopFailed = "停不掉。"
    let agentRunning = "在跑"
    let agentTools = "{n} 個工具"
    let agentEmpty = "這個 agent 還沒留下任何紀錄。"
    let agentBack = "對話"
    let webAgentOpen = "看這個 agent 做了什麼"
    let webTaskRoot = "主 session"
    let webTaskChild = "子 session"
    let webTaskTasks = "工作"
    let webTaskDone = "完成"
    let webTaskFailed = "失敗"
    let webTaskRunning = "在跑"
    let webStale = "Clawdline 在 Mac 上重新編過了。這一頁是舊的那一版。"
    let webStaleGo = "重新載入"

    let menuApplication = "Clawdline"
    let menuWindow = "視窗"
    let menuHelp = "輔助說明"
    let menuClose = "關閉視窗"
    let menuHome = "主頁／設定中心"
    let menuHelpDocumentation = "Clawdline 說明文件"
    let homeTitle = "Clawdline 主頁"
    let homeWelcome = "先選你想連到哪裡。設定畫面會顯示實際證據，不只顯示你切換了哪個開關。"
    let homePurpose = "你想連接什麼？"
    let homeLocalTitle = "本機瀏覽器"
    let homeLocalSummary = "在這台 Mac 的瀏覽器讀取 Clawdline。除非你在「設定」明確開啟，控制功能會保持關閉。"
    let homeCloudPreviewTitle = "Clawdline Cloud 預覽"
    let homeCloudPreviewSummary = "等即時連線可被驗證後，使用 Clawdline 的託管預覽路徑。"
    let homeCloudflareTitle = "我的 Cloudflare 網址"
    let homeCloudflareSummary = "等公開 HTTPS 路徑可被驗證後，使用你自己的 Cloudflare 主機名稱。"
    let homeUnavailable = "這個版本尚未就緒，也不會宣稱連線成功。"
    let setupDetected = "偵測到的狀態"
    let setupNextAction = "下一步"
    let setupExpected = "預期結果"
    let setupRecovery = "復原方式"
    let setupLocalServerOff = "本機回送伺服器已關閉。"
    let setupLocalChecking = "正在檢查實際的 /v1/health 端點⋯⋯"
    let setupLocalReady = "健康狀態端點已就緒，尚未建立瀏覽器憑證。"
    let setupLocalWaiting = "瀏覽器已開啟；正在等候這個裝置完成驗證。"
    let setupLocalConnected = "已連線。這個瀏覽器裝置確實已聯絡 Clawdline。"
    let setupLocalEnable = "開啟本機瀏覽器"
    let setupLocalRetry = "再檢查一次"
    let setupLocalOpen = "開啟唯讀瀏覽器"
    let setupLocalOpenAgain = "再次開啟瀏覽器"
    let setupFinish = "完成"
    let setupLocalExpected = "唯讀瀏覽器會開啟並完成驗證；即使沒有作用中的工作階段也算成功。"
    let setupLocalRecovery = "若停在這裡，請保持此視窗開啟並再次檢查。你也可在「設定」查看伺服器與連接埠。"
    let setupReadOnly = "唯讀 · 控制功能保持關閉"
    let setupLocalDeviceName = "這台 Mac 上的瀏覽器"

    let menuOpen = "打開輸入框"
    let menuReveal = "跳到目標分頁"
    let menuMascot = "吉祥物"
    let menuLogin = "開機時啟動"
    let menuEditConfig = "設定⋯"
    let menuReload = "重新載入設定"
    let menuQuit = "結束 Clawdline"
    let menuNoTarget = "（尚未偵測）"

    func hotkeyFailedTitle(_ combo: String) -> String { "\(combo) 註冊不起來" }
    func hotkeyFailedBody(_ configPath: String) -> String {
        """
        多半是被別的軟體佔走了——Spotlight、輸入法切換、BetterTouchTool 之類。

        換一個：編輯 \(configPath) 裡的 hotkey，然後從選單列選「重新載入設定」。

        在那之前，選單列的 ✳ 一樣打得開輸入框。
        """
    }
    let loginFailed = "設定開機啟動失敗"
}

struct SimplifiedChinese: Copy {
    let placeholder = "跟 Claude 说……"

    let hintSend = "发送"
    let hintNewline = "换行"
    let hintSwitch = "换标签"
    let hintList = "列表"
    let hintMascot = "换角色"
    let hintOutput = "看输出"
    let hintFullscreen = "全屏"
    let hintKeys = "快捷键"
    let hintTextSize = "字号"
    let hintOrder = "倒序"
    let hintVoice = "语音"
    func voiceListening(onDevice: Bool) -> String {
        onDevice ? "在这台 Mac 上听——再按一次结束"
                 : "听着——这个语言由 Apple 识别，不在这台机器上"
    }
    let voiceNoPermission = "语音输入需要麦克风与语音识别权限"
    let voiceUnavailable = "现在无法使用语音输入"
    func voiceTranscribing(seconds: Double) -> String {
        String(format: "Whisper 重读中…… %.1f 秒", seconds)
    }
    let whisperMissing = "没有装 Whisper——见 docs/whisper.md"
    let whisperNothingHeard = "没听到东西"
    func dictationStatus(_ status: Whisper.Status) -> String {
        switch status {
        case .ready(let model): return "语音：Apple，之后 Whisper（\(model)）"
        case .noBinary: return "语音：只有 Apple——没有 whisper-cli"
        case .noModel: return "语音：只有 Apple——whisper-cli 有了，缺模型"
        }
    }
    func voiceListeningWhisper() -> String { "听着——停下来时 Whisper 会再看一遍" }

    let scanning = "扫描中……"
    let noSession = "找不到在跑 Claude Code 的标签页"
    let nothingToSend = "没有可以发送的标签页——先在终端里开一个 Claude Code"
    let sendFailed = "发送不出去"
    let itermSilent = "iTerm2 没有响应"
    let itermBusy = "iTerm2 有一个对话框在等回答——请到 Mac 上按掉它"
    let scriptMissing = "找不到 iterm.js——app bundle 坏了？"
    let cannotList = "读不到 iTerm2 的 session"
    let noOutput = "还读不到这个标签页的内容。"
    let imageExpired = "图片已过期"
    let imagePreview = "图片预览"
    let imageClose = "关闭预览"
    func outputSize(_ pt: Int) -> String { "输出字号 \(pt)pt——按 ⌘J 看" }
    func foldedTools(_ count: Int) -> String { "\(count) 个动作" }
    func outputOrder(newestFirst: Bool) -> String {
        newestFirst ? "最新的在最上面" : "最旧的在最上面"
    }
    func backlogNow(_ count: Int) -> String { "现在\(count)" }
    func dropped(_ count: Int) -> String {
        count == 1 ? "路径加进去了——Claude Code 会自己读" : "加了 \(count) 个路径"
    }
    func stackConfirm(_ command: String) -> String { "再按一次就执行：\(command)" }
    let hintStacks = "服务器"
    func stackTip(up: Int, total: Int) -> String { "\(total) 个服务器，\(up) 个活着——⌘S 打开列表" }
    let stackTipUnknown = "这个项目有服务器，但它的状态命令还没被信任——⌘S"
    let stackUntrusted = "尚未信任"
    let stackExit = "退出码"
    let stackActionStart = "启动"
    let stackActionRestart = "重启"
    let stackActionStop = "停止"
    let stackActionLogs = "记录"
    let stackLogAll = "全部"
    let stackLogBack = "逐字稿"
    let stackActionAllow = "允许"
    let stackActionAgain = "再按一次"
    func sessionTip(index: Int, total: Int) -> String { "第 \(index) 个 session，共 \(total) 个——⌘K 切换" }
    let sessionWaiting = "在等你回答"
    let sessionAgents = "{n} 个在后台"
    let sessionShellOne = "1 个 shell 在跑"
    let sessionShellMany = "{n} 个 shell 在跑"
    let sessionWaitedOnByOne = "1 个在等你放行"
    let sessionWaitedOnByMany = "{n} 个在等你放行"
    let islandDone = "跑完了"
    let islandAllSessions = "所有 session……"
    func statusWaiting(_ labels: [String]) -> String {
        labels.count == 1 ? "\(labels[0]) 在等你回答"
                          : "\(labels.count) 个 session 在等你回答"
    }
    func statusWorking(_ count: Int) -> String { "\(count) 个在跑" }

    let settingsTitle = "Clawdline 设置"
    let settingsGeneral = "一般"
    let settingsBar = "输入条"
    let settingsReading = "阅读"
    let settingsVoice = "语音输入"
    let settingsHotkey = "快捷键"
    let settingsRecording = "按下按键……"
    let settingsScope = "在哪里生效"
    let settingsScopeGlobal = "所有 app"
    let settingsScopeHint = "留空就是到处都能按，所以把最后一个移掉，上面那个开关就会自己打开——再把它关掉，列表就回来了。配置文件里存的是 bundle id，自己手动编辑的列表一样有效。"
    let settingsScopeAdd = "添加 app……"
    let settingsScopeChoose = "选择其他 app……"
    let settingsScopeRunning = "现在开着的"
    let settingsScopeRemove = "移除"
    let settingsLanguage = "语言"
    let settingsReopen = "输入条跟着终端出现和收起"
    let settingsReopenHint = "从终端切到别的地方，输入条就收起来；切回终端，它就回来。Esc 才是「这次用完了」的意思。"
    let settingsFollow = "终端显示输入条指着的那个 session"
    let settingsFollowHint = "它会把那个 session 的标签页选中。它不会把终端拉到最前面——不然每按一次 Tab，键盘就从你正在打字的那个框里跑掉了。"
    let settingsCodexAutoName = "自动命名新的 session"
    let settingsCodexAutoNameHint = "每个尚未命名的 session 会由你选择的助手运行一次小型 turn。它使用第一条需求、消耗该助手的额度，而且不会覆盖你自己取的名称。"
    let settingsNotch = "住在刘海里"
    let settingsNotchHint = "在镜头那块住一只角色。关掉就是真的关掉——什么都不画，窗口也不会建立。"
    let settingsPosition = "在屏幕上的高度"
    let settingsWidth = "宽度"
    let settingsOpacity = "卡片不透明度"
    let settingsShow = "显示"
    let settingsPaneHeight = "面板高度"
    let settingsTextSize = "文字大小"
    let settingsPaneFont = "面板字体"
    let settingsBlur = "背后模糊"
    let settingsNewestFirst = "最新的在最上面"
    let settingsEngine = "识别引擎"
    let settingsSettle = "停顿多久算一句话结束"
    let settingsStop = "安静多久算整段结束"
    let settingsAuto = "自动"
    let settingsTranscript = "对话记录"
    let settingsTerminal = "终端画面"
    let settingsOff = "关闭"
    let settingsHooks = "Claude Code Hook"
    let settingsHooksHint = "装上之后，一轮对话开始、结束、或是需要你回答的当下，Claude Code 会直接说一声，不必等 Clawdline 下一次去看。每一次判读仍然来自画面，这里只决定判读发生得多快。"
    let settingsHooksInstall = "安装"
    let settingsHooksRemove = "移除"
    let settingsHooksOff = "未安装——状态全部从画面读"
    let settingsHooksOn = "已安装——还没有 session 回报过"
    let settingsHooksLive = "已安装，session 正在回报"
    let settingsStateHook = "session 换状态的时候"
    let settingsStateHookHint = "只要有 session 开始跑、跑完、或者要问你话，Clawdline 就会执行这个：你自己的程序，细节放在它的环境变量里。它写在配置文件而不是这里，因为那是一串 argv、不是一行命令行——路径里有空格，它也还是一整个路径。"
    let settingsRemote = "远程"
    let settingsRemoteServe = "让浏览器或者你的手机看得到你的 session"
    let settingsRemoteHint = "关着的时候，这台 Mac 以外的东西什么都碰不到。打开之后，session 列表就在 127.0.0.1 上读得到——给这里的浏览器，给隔着隧道连进来的手机，给一个脚本。交出去的是仓库名称、分支和任务标题，所以在你开口之前，它一直是关着的。"
    let settingsRemoteDevices = "已配对的设备"
    let settingsRemoteNoDevices = "还没有——这台 Mac 以外的东西什么都读不到"
    let settingsRemoteRevokeAll = "全部断开"
    let settingsRemoteOpen = "用浏览器打开"
    let pairingIgnore = "忽略"
    func pairingAsks(_ device: String) -> String { "\(device) 想跟这台 Mac 配对" }
    func pairingCode(_ code: String) -> String {
        """
        在它上面输入这组代码：

        \(code)

        两分钟内有效。如果刚才不是你要求的，不用理会——对方没有这组代码，就完成不了。
        """
    }
    let settingsTunnel = "从任何地方连到这台 Mac"
    let settingsTunnelQuick = "自动生成的网址"
    let settingsTunnelNamed = "我自己的域名"
    let settingsTunnelHostname = "主机名"
    let settingsTunnelHint = "通过 cloudflared 从这台 Mac 往外连出去——不用做端口转发，你的网络上也没有东西在监听。要先配对过一台设备它才会启动，因为隧道后面就是这台 Mac 上每一个仓库名称、每一个任务标题。"
    let settingsRemoteWrite = "让配对过的设备写进 session"
    let settingsRemoteWriteHint = "关着的时候，配对过的设备只能读。打开之后，它可以把文字送进 session，也可以开新的 session——那就是在这台 Mac 上执行代码，因为 Claude Code 做的就是这件事。这跟上面那一题是两回事，所以它是另一个开关。"
    let settingsRemotePhone = "配对手机……"
    let settingsRemotePhoneHint = "显示一张可以扫的 QR code。它自己带着一把钥匙，所以就算被拍走，被拍走的也只是一台会出现在上面列表里、随时拿得掉的设备——不是这台 Mac 自己的钥匙。"
    let pairingScanTitle = "用手机扫这张 QR code"
    let pushWaiting = "在等你回答"
    let pushTest = "这是一条测试通知，该接的都接上了。"
    let pushFinished = "跑完一段长任务了"
    let pushDeployOk = "deploy 成功了"
    let pushDeployFail = "deploy 失败了"
    func pushChildWaiting(minutes: Int?) -> String {
        guard let minutes else { return "有子 session 在等回答" }
        return "有子 session 在等回答，还剩 \(minutes) 分钟"
    }
    func pushBatchDone(done: Int, failed: Int) -> String {
        let all = "跑完 \(done) 件任务"
        return failed == 0 ? all : "\(all)，\(failed) 件失败"
    }
    let settingsPushFinish = "一段长任务跑完时通知我"
    let settingsPushFinishHint = "只有跑超过两分钟的才算。"
    let settingsSmartNotifications = "智能通知"
    let settingsSmartNotificationsHint = "用 Haiku 说明刚完成了什么；生成失败时仍会发送原来的通知。"
    func pushCoalesced(count: Int) -> String { "\(count) 件任务同时完成" }
    let settingsSmartHealthIdle = "还没有尝试过智能通知。"
    func settingsSmartHealth(attempts: Int, successes: Int) -> String {
        "\(attempts) 次尝试中，有 \(successes) 次发出了模型写的句子。"
    }
    func settingsSmartHealthFailure(reason: String, time: String) -> String {
        "最近一次退回原来通知在 \(time)：\(reason)。"
    }
    func settingsSmartTimeout(seconds: Int) -> String { "Claude 超过 \(seconds) 秒没完成，被中止" }
    let settingsSmartQueueFull = "同时完成的数量超过队列容量"
    let settingsSmartModelFailed = "Claude 没有返回可用的内容"
    let settingsSmartNoSource = "没有可摘要的内容"
    let settingsSmartMissing = "找不到 claude 可执行文件"
    let settingsPushDeploy = "deploy 结束时通知我"
    let settingsPushDeployHint = "成功和失败都会通知。"
    let settingsAgentNotify = "允许 agent 主动推送"
    let settingsAgentNotifyNote = "只管 agent 主动发送的内容；任务完成、deploy 和其他通知都不受影响。"
    let settingsOrchestrator = "把活派给别的 session"
    let settingsOrchestratorEnabled = "让一个 session 把活派给另一个"
    let settingsOrchestratorEnabledHint = "带着 clawdline skill 的 session 可以开一个新标签页、把指示打进去，做完再回头跟它说一声。关着的时候，每一次派活都会被挡下来——已经在跑的不会被停掉。"
    let settingsOrchestratorMax = "同时最多几个子 session"
    let settingsOrchestratorMaxHint = "默认五个，一个 session 算一份，不是整台 Mac 算一份。每一个都是一个终端标签页，里面有一个 assistant 在做事。"
    let settingsOrchestratorPermission = "child 可以自己走多远"
    let settingsOrchestratorPermissionHint = "child 的标签页没有人在看，停下来等核准的 session 会一路停到超时——而派出去的 session 整份工作就是跑指令和写文件，所以只要不是最后一格，它就会停在某个地方。任务可以要求比这里保守，但不能超过。"
    let settingsOrchestratorPermissionAsk = "每一步都先问"
    let settingsOrchestratorPermissionEdits = "写文件不用问"
    let settingsOrchestratorPermissionFull = "都不要问"
    let settingsOrchestratorNotify = "做完之后回报给派活的 session"
    let settingsOrchestratorNotifyHint = "活干完的时候，往那个 session 里打一行字。"
    let settingsOrchestratorClose = "子 session 回报之后"
    let settingsOrchestratorCloseHint = "回报过了就把它的标签页关掉——超时的那个会留着，让你自己看是怎么回事。"
    let settingsOrchestratorCloseNow = "马上把标签页关掉"
    let settingsOrchestratorCloseLinger = "三分钟后再关"
    let settingsOrchestratorCloseKeep = "留着不要关"
    let settingsOrchestratorPolicy = "派工的规矩"
    let settingsOrchestratorPolicyHint = "每次派工 Clawdline 都会读这份规矩，并且抄进每一个「还能再往下派」的 child 的指示里：用哪个助理、用哪个模型、整张图该长什么样。留空 ＝ 没有规矩。"
    let settingsOrchestratorPolicyEdit = "编辑规矩"
    func settingsOrchestratorPolicyOn(_ lines: Int) -> String { return "生效中——\(lines) 行" }
    let settingsOrchestratorPolicyOff = "没有规矩——每次派工由派的人自己决定"
    let settingsSchedules = "计划任务"
    let settingsSchedulesEmpty = "还没有任何计划任务。用下面的「新建计划任务」做一个。"
    let settingsScheduleNew = "新建计划任务"
    let settingsScheduleEdit = "编辑"
    let settingsScheduleSave = "保存"
    let settingsScheduleDelete = "删除"
    let settingsScheduleRun = "立即运行"
    let settingsScheduleReveal = "在 Finder 中显示"
    let settingsSchedulesFolder = "打开 schedules 文件夹"
    let settingsScheduleNext = "下次"
    let settingsScheduleLast = "上次"
    let settingsScheduleNever = "尚未运行"
    let settingsScheduleStarted = "已开始运行。"
    let settingsScheduleActive = "上一个计划任务仍在运行。"
    let webScheduleMissed = "上次错过"
    let webScheduleNoNext = "没有安排下次运行。"
    func childAnnounce(_ title: String) -> String { "收到 Clawdline 派来的任务：\(title)——开始处理。" }
    func settingsSeconds(_ value: Double) -> String { String(format: "%.1f 秒", value) }

    let webConnLive = "已连上"
    let webConnConnecting = "连接中"
    let webConnRetrying = "{n} 秒后重试"
    let webConnOffline = "离线"
    let webConnLocked = "未配对"
    let webConnTipLive = "正从 app 推送过来"
    let webConnTipLocked = "这个浏览器还没跟那台 Mac 配对过"
    let webConnTipDown = "没连上——点一下马上试"

    let webCountWorking = "{n} 个在跑"
    let webCountWaiting = "{n} 个在等你"
    let webCountUnreadable = "{n} 个读不到"
    let webCountQuietOne = "{n} 个 session，都很安静"
    let webCountQuietMany = "{n} 个 session，都很安静"
    let webCountNone = "没有 session"

    let webFilterPlaceholder = "用任务、项目或 tty 筛选"
    let webFilterLabel = "筛选 session"
    let webListLabel = "Claude Code session 列表"
    let webPull = "下拉刷新"
    let webPullRelease = "松手就刷新"
    let webPullBusy = "刷新中……"
    let webEmptyFilterTitle = "没有东西匹配「{q}」"
    let webEmptyFilterHint = "Esc 清掉筛选"
    let webEmptyLockedTitle = "这台设备还没配对"
    let webEmptyLockedHint = "app 回了 401——在 Mac 上的 Clawdline 里配对"
    let webEmptyNoneHint = "在终端里开一个，它就会出现在这里"
    let webEmptyWaitTitle = "在等 app"
    let webEmptyWaitHint = "流上还没有东西进来"
    let webStateUnreadable = "画面读不到"
    let webStateWorking = "在跑"
    let sessionWorkReady = "可接新工作"
    let sessionWorkUnknown = "状态未知"
    let sessionWorkHolding = "自行推进中"
    let sessionWorkOwed = "欠一个决定"
    let sessionWorkSelfStated = "自述"
    let sessionWorkMilestone = "已交付，等待验收"
    let sessionWorkComplete = "已验收完成"
    let closeabilitySafe = "可以安全关闭"
    let closeabilityBlocked = "还有 {n} 项未了结"
    let closeabilityBlockedOne = "还有 1 项未了结"
    let closeabilityBlockedMany = "还有 {n} 项未了结"
    let closeabilityNeedsAttestation = "等这个 session 自己确认"
    let closeabilityUnknown = "无法判断能否关闭"
    let closeabilityWhy = "不能关闭的原因"
    let closeabilityMoverSelf = "由这个 session 推进"
    let closeabilityMoverPerson = "由你推进"
    let closeabilityMoverSession = "由另一个 session 推进"
    let closeabilityMoverBroker = "重新读一次才知道"
    let closeabilityNotProven = "broker 无法证明这个 session 可以安全关闭。"
    let closeabilityAttestationExplanation = "这不是系统发现工作尚未完成。Clawdline 能检查的项目都已经通过，但这个 session 还没确认是否留有本机修改、未交付事项或 Clawdline 以外的工作。请先回到这个 session 检查，再决定是否关闭。"
    let closeabilityTechnicalDetails = "技术细节"

    let webBack = "列表"
    let webBackLabel = "回到 session 列表"
    let webNoSessionOpen = "没有打开的 session"
    let webOrderTip = "把对话记录倒过来（r）"
    let webShowOnMac = "在 Mac 上显示"
    let webShowOnMacTip = "把这个 session 的终端叫到 Mac 最前面"
    let webShowOnMacOff = "服务器回报 write: false——现在什么都发不出去"
    let webShowOnMacAsked = "已经让 Mac 把它拿到前面"
    let webSessionActions = "Session 快捷操作"
    let webSessionGit = "Git 更改"
    let webGitTitle = "Git 更改"
    let webGitClean = "工作区没有更改"
    let webGitNotRepo = "不是 Git 仓库"
    let webGitFailed = "无法读取 Git 更改"
    let webGitRefresh = "刷新"
    let webGitClose = "关闭"
    let webGitStaged = "已暂存"
    let webGitUnstaged = "未暂存"
    let webGitUntracked = "未跟踪"
    let webGitConflict = "冲突"
    let webEndSession = "关闭 session"
    let webConfirmActionTitle = "要执行 {action} 吗？"
    let webConfirmActionSay = "这会把 {action} 发送到当前 session。"
    let webConfirmEndTitle = "要关闭这个 session 吗？"
    let webConfirmEndSay = "Agent 会先退出，然后关闭它的终端标签页。"
    let webConfirmEndLoses = "关闭会一并终止："
    let webClawdfatherCreateLabel = "把新的 session 命名为 Clawdfather"
    let webClawdfatherIs = "这个 session 就是 {name}"
    let webClawdfatherRegisterAsk = "请把这个新的 session 注册成这台 Mac 的 Clawdfather，也就是 machine coordinator。你的 terminal-neutral session id 是 {id}。先用 ~/.config/clawdline/orchestrator-token 里的 orchestrator token 读 coordinator 记录。只有完全没有 coordinator 登记时，才照 docs/orchestrator.md 里“Becoming Clawdfather”的注册那一段做。只要已经有登记的 coordinator，就算它离线了，也不要取代它。做完告诉我结果。"
    let webClawdfatherRegisterSent = "已经请新的 session 去当 Clawdfather"
    let webClawdfatherRegisterLate = "新的 session 没能及时就绪，来不及命名为 Clawdfather。"
    let webClawdfatherRegisterBlocked = "这台 Mac 的 coordinator 记录读不出来，所以完全不会去动它。"
    let webCoordSectionObserve = "观察"
    let webCoordSectionCoordinate = "协调"
    let webCoordSectionPresence = "在线状态"
    let webCoordSectionAdmin = "管理"
    let webCoordCmdStatusReport = "状态报告"
    let webCoordCmdStatusReportSay = "读取 Clawdfather 当前的状态与进行中的职责。"
    let webCoordCmdSinceAway = "你离开之后"
    let webCoordCmdSinceAwaySay = "读取自上一个回归点以来记录的变更与决定。"
    let webCoordCmdDuplicates = "重复、冲突与归属"
    let webCoordCmdDuplicatesSay = "查看重复的工作、相互冲突的认领与当前的归属。"
    let webCoordCmdLandingClosure = "落地收尾"
    let webCoordCmdLandingClosureSay = "读取已通过复审、仍在等 root 落地的交付。"
    let webCoordCmdCoordinateWork = "协调工作"
    let webCoordCmdCoordinateWorkSay = "就进行中的工作起草协调步骤。"
    let webCoordCmdDispatch = "派出独立工作"
    let webCoordCmdDispatchSay = "预览一次会开出独立 child session 的派工。"
    let webCoordCmdAsk = "问 Clawdfather"
    let webCoordCmdAskSay = "起草一个要请 Clawdfather 判断的问题。"
    let webCoordCmdQuietWatch = "安静监看"
    let webCoordCmdQuietWatchSay = "起草一个不发“有人在等”警示的安静监看请求。"
    let webCoordCmdScope = "范围与权限"
    let webCoordCmdScopeSay = "读取 Clawdfather 当前的范围与被授予的权限。"
    let webCoordCmdStop = "停止 Clawdfather"
    let webCoordCmdStopSay = "预览停止 Clawdfather。"
    let webCoordCmdReconnect = "重新连上 Clawdfather"
    let webCoordCmdReconnectSay = "预览重新连上 Clawdfather。"
    let webCoordCmdDeepAudit = "深度状态盘点"
    let webCoordCmdDeepAuditSay = "请 Clawdfather 审计相关 Session 的进行中工作、交付与待决事项。"
    let webCoordTokenExpected = "预期 Token 负担：{effort}"
    let webCoordTokenLow = "低"
    let webCoordTokenMedium = "中"
    let webCoordTokenHigh = "高"
    let webCoordTokenUnknown = "未知"
    let webCoordAuditPreview = "这是高 Token、多 Session 的请求，目前尚未发送。确认后才会把完整审计指示发送到这个确切的 Clawdfather Session。第一版由 Agent 执行，broker 尚无持久 run 记录。"
    let webCoordAuditWhyOffline = "Clawdfather 已离线，无法发送审计请求。"
    let webCoordAuditWhyDisconnected = "这个浏览器已离线，无法发送审计请求。"
    let webCoordAuditWhyNoWrite = "这个浏览器目前没有发送／写入能力。"
    let webCoordAuditSending = "正在发送请求…"
    let webCoordAuditSent = "已发送审计请求；这张回执不代表审计已完成。"
    let webCoordAuditFailed = "未发送审计请求（{code}）：{message}"
    let webCoordEffectRead = "只读"
    let webCoordEffectAdvisory = "建议性"
    let webCoordEffectSpawns = "会开 session"
    let webCoordEffectMutation = "会改状态"
    let webCoordStateAvailable = "可用"
    let webCoordStateDraft = "草稿"
    let webCoordStateUnavailable = "不可用"
    let webCoordStatePreview = "预览"
    let webCoordStateDisabled = "已停用"
    let webCoordOnline = "{name} 在线"
    let webCoordOffline = "{name} 离线"
    let webCoordControlsTitle = "{name} 控制面板"
    let webCoordOpenControls = "打开 {name} 控制面板"
    let webCoordEmpty = "没有收到任何这个页面认得的 Clawdfather 指令。"
    let webCoordDisabledFallback = "Clawdfather 已停用这个指令。"
    let webCoordPreviewTitle = "Clawdfather 指令"
    let webCoordPreviewNone = "还没选择指令；什么都没有发出。"
    let webCoordPreviewMutation = "仅预览——什么都没有发出。在 Clawdfather 指令 API 接上之前，确认按钮保持不可按。"
    let webCoordPreviewDraft = "仅离线草稿——什么都没有发出，也不代表 Clawdfather 的判断。"
    let webCoordPreviewSpawn = "仅预览——没有开出任何 session。"
    let webCoordPreviewContract = "这里只展示这个指令的契约；什么都没有发出。"
    let webCoordWhyNoCommandRoute = "还没有任何路由能把这个面板的指令送进 session，所以什么都发不出去。"
    let webCoordWhyNoReturnLedger = "这台 Mac 还没有记录回归点，所以没有东西可以对照着读。"
    let webCoordWhyDeviceCannotSpawn = "配对设备永远不能开 session——这道分隔是刻意的，这个按钮不会跨过去。"
    let webCoordWhyMachineTokenOnly = "重新连上需要 Mac 自己的 orchestrator token，配对设备刻意不持有它。"
    let webCoordReadFailed = "读不到 Clawdfather 的 Bearings。"
    let webCoordActiveTasks = "{n} 个任务进行中"
    let webCoordPendingLandings = "{n} 个交付等着落地"
    let webCoordOpenWaits = "{n} 个文件等待尚未解除"
    let webCoordCountUnknown = "{n} 个状态未知"
    let webCoordStaleSessions = "Mac 的 session 快照已过时；这些数字可能是旧的。"
    let webCoordUnknown = "状态未知"
    let webCoordWaitingList = "在等别人"
    let webCoordBlockingList = "握着别人在等的文件"
    let webCoordAllQuiet = "当前没有东西被卡住、被抢或没人认领。"
    let webCoordNoLandings = "没有交付在等落地。"
    let webCoordUnregistered = "这台 Mac 上没有登记任何 Clawdfather。"
    let webCoordScopeLine = "{name} 协调这台 Mac——machine 范围。"
    let webCoordScopeDevice = "在这个面板上，Clawdfather 只能被读取。发出工作、开 session、改机器状态都需要 Mac 自己的凭证，在这里一律停用。"
    let webClosing = "关闭中……"
    let webCancel = "取消"
    let webConfirm = "确认"
    let webReviewBeforeClosing = "回到 session 检查"
    let webConfirmEndAnyway = "仍要关闭"
    let webPickSession = "在左边挑一个 session。"
    let webReading = "读取中……"
    let webLoading = "加载中……"
    let webTranscriptFailed = "读不到对话记录"
    let webWhoYou = "你"
    let webWhoTool = "工具"
    let webNoticeTask = "任务"
    let webNoticeCompleted = "任务已完成"
    let webNoticeFailed = "任务失败"
    let webNoticeTimedOut = "任务超时"
    let webNoticeCancelled = "任务已取消"
    let webNoticeCouldNotStart = "任务无法启动"
    let webNoticeFinished = "任务已结束"
    let webNoticeWorkspaceOverlap = "工作区重叠"
    let webNoticeNoSiblings = "没有其他同级任务仍在运行。"
    let webNoticeOneSibling = "仍有 {n} 个同级任务在运行。"
    let webNoticeManySiblings = "仍有 {n} 个同级任务在运行。"
    let webNoticeClaimsReleased = "路径声明已释放；子任务标签页可能仍会写入。"
    let webNoticeFileWaitRequested = "等待文件释放"
    let webNoticeFileWaitReleased = "文件已释放"
    let webNoticeHandoffPickedUp = "交接已接手"
    let webNoticeHandoffNeedsDelivery = "交接需要手动投递"
    let webNoticeRecheckGit = "集成前请重新检查 HEAD、status 和 diff。"
    let webPending = "还在等 Mac……"
    let webAttachedImage = "已附上 {n} 张图"
    let webAttachedImages = "已附上 {n} 张图"
    let webSteps = "{n} 个动作"
    let webJustNow = "刚刚"
    let webMinutesAgo = "{n} 分钟前"
    let webCodeCopy = "复制这段代码"
    let webCodeCopied = "已复制代码。"
    let webCodeCopyFailed = "复制失败，请改用手动选取。"

    let webSend = "发送"
    let webAttach = "附一张图"
    let webRemoveShot = "移除 {name}"
    let webWriteOpen = "先打开一个 session 才能写进去。"
    let webWriteOff = "*现在不能发*——服务器回报 `write: false`。这个框是接好的，那边一改它就自己开。"
    let webShotsOnlyPictures = "只有图片能跟着消息一起发"
    let webShotsTooMany = "一条消息最多带 {n} 张图"
    let webShotTooBig = "这张图太大了，压过也发不出去"
    let webShotsTooBig = "这几张图加起来太大，发不出去"
    let webShotUnreadable = "这张图读不到"
    let webShotNeedsSession = "先打开一个 session 才能把图发过去"

    let webVoiceStart = "用说的写一条消息"
    let webVoiceStop = "停下来，转成文字"
    let webVoiceDone = "完成"
    let webVoiceListening = "听着…… {t}"
    let webVoiceReading = "Mac 正在转文字…… {n} 秒"
    let webVoiceSlow = "这台 Mac 重启之后的第一次要先载模型——大概十二秒。"
    let webVoiceLimit = "录音在 {n} 分钟停了，一次最长就是这么久。先把录到的转出来。"
    let webVoiceEmpty = "那一段里没听到东西。"
    let webVoiceTooShort = "那段太短了，听不出东西。"
    let webVoiceDenied = "麦克风被拒绝了。到这个浏览器针对这个网站的设置里把它开回来。"
    let webVoiceNoMic = "这台设备上找不到麦克风。"
    let webVoiceInUse = "麦克风忙着——这台设备上有别的东西占着它。"
    let webVoiceInsecure = "麦克风要 https，而这一页没有。隧道会给你一个；局域网上的普通地址不会。"
    let webVoiceUnsupported = "这个浏览器没法录音。"
    let webVoiceBusy = "已经有一段在转、一段在等了。等一下再试。"
    let webVoiceNoBinary = "Mac 上没有装 Whisper，那边没有东西可以拿来转文字。"
    let webVoiceNoModel = "Mac 上有 Whisper，但没有模型可以读。它只要 `~/.cache/whisper` 里有一个 ggml 文件就行。"
    let webVoiceFailed = "那一段转不出文字。"

    let webHintMove = "移动"
    let webHintOpen = "打开"
    let webHintFilter = "筛选"
    let webHintPane = "面板"

    let webKeysLabel = "键盘快捷键"
    let webKeysTitle = "键盘"
    let webKeysMove = "在列表里上下移动——`j` 和 `k` 一样"
    let webKeysOpen = "打开选中的 session"
    let webKeysFilter = "筛选列表"
    let webKeysEscape = "先清掉筛选，再退回去"
    let webKeysList = "光标回到 session 列表"
    let webKeysPane = "显示或隐藏对话记录"
    let webKeysEnds = "对话记录的最上面或最下面"
    let webKeysReverse = "把对话记录的顺序倒过来"
    let webKeysThis = "这张卡"
    let webKeysFoot = "打进文本框里的东西就留在文本框里——你在打字的时候，快捷键会先让开。"

    let webDoorLabel = "配对这个浏览器"
    let webDoorAskLede = "这个浏览器还没被放进来。"
    let webDoorAskFine = "按下请求配对，六位数字会出现*在那台 Mac 上*——它故意不放在给这一页的回应里。只有人在那台机器旁边才做得完，这正是重点，不是刁难。"
    let webDoorName = "给这台设备取个名字"
    let webDoorAsk = "请求配对"
    let webDoorToPassword = "改用密码登录"
    let webDoorCodeLede = "看那台 Mac。"
    let webDoorCodeFine = "Clawdline 正在显示六位数字，还有 {left}。打在这里。"
    let webDoorTwoMinutes = "两分钟"
    let webDoorDigit = "第 {n} 位"
    let webDoorConfirm = "配对这台设备"
    let webDoorRestart = "重来一次"
    let webDoorPasswordLede = "用密码登录。"
    let webDoorPasswordFine = "就是 Mac 上 Clawdline 里「设置 → 远程」设的那组。没设过的话，配对就是进来的办法。"
    let webDoorPassword = "密码"
    let webDoorPasswordGo = "登录"
    let webDoorToPair = "改用配对代码"
    let webDoorAsking = "正在问那台 Mac……"
    let webDoorAskFailed = "问不到那台 Mac。"
    let webDoorRateLimited = "每问一次，那台 Mac 上就弹一次提示，所以十分钟只有三次。"
    let webDoorSixDigits = "六位数字。"
    let webDoorChecking = "检查中……"
    let webDoorFinished = "这次配对结束了——错了五次。等你人在 Mac 旁边再问一次。"
    let webDoorWrongCode = "这组代码不对。"
    let webDoorNeedPassword = "先填密码。"
    let webDoorWrongPassword = "密码不是这个。"
    let webDoorExpired = "这组代码过期了。再问一次，Mac 上就会出现新的。"
    let webDoorPaired = "配对好了——这个浏览器进来了"

    let webOffline = "连不上 Clawdline。它还在那台 Mac 上跑着吗？"
    let webNotJSON = "服务器发回来的东西不是 JSON"
    let webRequestFailed = "请求失败"

    let webNotifyGo = "通知我"
    let webNotifyAsking = "询问中……"
    let webNotifyStop = "停掉"
    let webNotifyStopping = "停止中……"
    let webNotifyOff = "有 session 在等你回答的时候"
    let webNotifyOn = "这台设备已经订阅了。要通知哪些事，在 Mac 上定。"
    let webNotifyBlocked = "这个网站的通知被挡掉了。那个开关在浏览器自己的设置里，不在这里。"
    let webNotifyUnsupported = "这个浏览器没法显示通知。"
    let webNotifyHomeScreen = "把 clawdline 添加到主屏幕，再从那里打开——iOS 只把通知发给住在那里的 app。"
    let webNotifyOnFailed = "通知打不开"
    let webNotifyOffFailed = "通知关不掉"

    let webSettings = "设置"
    let webSettingsNotify = "通知"
    let webSettingsAssistantIcons = "助理图标"
    let webSettingsAssistantIconsSay = "在对话中，于 Claude 或 Codex 名称前显示其图标。"
    let webSettingsAssistantIconsShow = "显示图标"
    let webSettingsVersion = "版本 {v}"
    let webClose = "关闭"
    let webNotifySheetOff = "有 session 在等的时候，不会通知这台设备。"
    let webNotifyTest = "发一条测试"
    let webNotifyTestSent = "发出去了——马上就会到这台设备。"
    let webNotifyTestNone = "那台 Mac 上没有这台设备的订阅。把通知关掉再打开，这个浏览器就会重新注册一个。"
    let webNotifyTestFailed = "测试通知发不出去"
    let webSending = "发送中……"
    let webSendTip = "Return 发送 · Shift-Return 换行"
    let webStart = "开一个 session"
    let webStartLabel = "在某个项目里开一个 session"
    let webStartPick = "要在哪里开？"
    let webStartWith = "要用哪一个开？"
    let webStartEmpty = "还没有地方可以开。在 Mac 上跑过一次 Claude Code，它就会出现在这里。"
    let webStartFilter = "筛选项目"
    let webStarting = "正在开标签页……"
    let webStartWaiting = "开好了。等它出现……"
    let webStartSlow = "标签页已经开了，但那个 session 还没回报。去 Mac 上看一下。"
    let webStartFailed = "这个开不起来。"
    let webStartGone = "那个项目已经不在 Mac 上了。"
    let webStartTerminalClosed = "{app} 没有在 Mac 上跑。先在那边打开它，再试一次。"
    let webStartTerminalUnsupported = "从这里没法在 {app} 里开 session。在它里面跑 tmux 就可以了。"
    let webStartOff = "从远程开 session 是关着的。在 Mac 上的「设置 → 远程」可以打开。"
    let webResumeWith = "接续之前的"
    let webResumePick = "要接哪一段？"
    let webResumeFilter = "筛选对话"
    let webResumeEmpty = "那个项目还没留下任何记录。"
    let webResumeLive = "开着"
    let webResumeBack = "换一个项目"
    let webResumeGone = "那段对话已经不在 Mac 上了。"
    let webResumeClaudeOnly = "只有 Claude Code 留得下能接续的对话。"
    let webResuming = "正在接回去⋯"
    let webResumeCapped = "比这些更早的不在这份清单上。"
    let webCommand = "说要开什么"
    let webCommandLabel = "用说的开一个 session"
    let webCommandSay = "按下面的「开始」之前，什么都不会发出去。"
    let webCommandHeard = "要它做什么？"
    let webCommandThinking = "思考中……"
    let webCommandDraft = "草稿"
    let webCommandWhere = "项目"
    let webCommandWith = "助手"
    let webCommandModel = "模型"
    let webCommandFirst = "第一条消息"
    let webCommandGo = "开始"
    let webCommandUnsure = "不确定是哪个项目，自己选一个。"
    let webCommandFailed = "没办法把它变成草稿。"
    let webCommandNoPlanner = "这台 Mac 没有 Claude Code，没办法把它变成草稿。"
    let webCommandBusy = "已经有一句在变成草稿了，等一下再试。"
    let webCommandEmpty = "没听到东西"
    let webScheduleNew = "新建计划任务"
    let webScheduleEdit = "编辑计划任务"
    let webScheduleNewSay = "按下面的「创建」之前，不会安排任何东西。"
    let webScheduleTitle = "标题"
    let webScheduleAt = "时间"
    let webScheduleOn = "星期"
    let webScheduleWhere = "项目"
    let webScheduleWith = "助手"
    let webScheduleFirst = "第一条消息"
    let webScheduleMore = "更多"
    let webScheduleModel = "模型"
    let webScheduleWhenDone = "结束之后关掉分页"
    let webScheduleCloseSuccess = "成功时"
    let webScheduleCloseAlways = "一律"
    let webScheduleCloseNever = "不要关"
    let webScheduleEnabled = "启用"
    let webScheduleDisabled = "停用"
    let webScheduleNotify = "失败时通知我"
    let webScheduleCatchUp = "错过了，几小时内还要补跑"
    let webScheduleTimeout = "跑多久没完就放弃（分钟）"
    let webScheduleCreate = "创建"
    let webScheduleCreated = "已创建计划任务。"
    let webScheduleDispatchOff = "计划任务建好了，也有效，只是派活是关着的，不会有人执行它。在 Mac 上的「设置 → 远程」可以打开。"
    let webScheduleFailed = "没办法创建计划任务。"
    let webScheduleSave = "保存"
    let webScheduleSaved = "已保存计划任务。"
    let webScheduleDelete = "删除"
    let webScheduleDeleteAsk = "要删除 {title} 吗？无法撤销。"
    let webScheduleDeleted = "已删除计划任务。"
    let webScheduleNeedsTime = "没听到时间，自己填一个。"
    let webScheduleNeedsPlace = "不确定是哪个项目，自己选一个。"
    let webScheduleDaily = "每天"
    let webScheduleSun = "日"
    let webScheduleMon = "一"
    let webScheduleTue = "二"
    let webScheduleWed = "三"
    let webScheduleThu = "四"
    let webScheduleFri = "五"
    let webScheduleSat = "六"
    let webLinks = "链接"
    let webLinksTip = "这个项目可以从哪些地方打开"
    let webLinksPick = "这个项目能打开的地方，都在这里。"
    let webLinksEmpty = "这个项目没有任何可以打开的地方——没有网站，没有 deploy，也没有服务器在跑。"
    let webLinksFailed = "读不到这个项目的链接。"
    let webLinksLocal = "只在那台 Mac 自己的网络里才通。从这里打不开。"
    let webLinksFile = "Mac 上的一个文件。它在那边打开，不在这个浏览器里。"
    let webLinksCopy = "复制路径"
    let webLinksCopied = "复制好了。"
    let webLinksCopyFailed = "这个浏览器不让这一页复制那个。"
    let webLinkOk = "正常"
    let webLinkFail = "出错"
    let webLinkDown = "没开"
    let webLinkRunning = "进行中"
    let webSessionInfo = "Session 信息"
    let webInfoTitle = "关于这个 session"
    let webInfoEditTitle = "编辑 session 标题"
    let webInfoCopyTitle = "复制这个名字"
    let webInfoTitleSaved = "标题已保存。"
    let webInfoTitleLocal = "标题已存入 Clawdline；下游名称没有跟着改。"
    let webInfoTitleQueued = "标题已存入 Clawdline；Codex 更新已排队。"
    let webInfoTitleNotDurable = "标题已生效，但这台 Mac 没能写入配置文件；重开就会不见。"
    let webInfoTitleCloud = "session 标题只能在那台 Mac 上改，云端连接改不了。"
    let webInfoSession = "这个 session"
    let webInfoAssistant = "助手"
    let webInfoModel = "模型"
    let webInfoSessionId = "Session ID"
    let webInfoDirectory = "目录"
    let webInfoRunningFor = "已运行"
    let webInfoStatus = "状态"
    let webInfoWorkStatusMeaning = "这是这个 session 的工作状态。一个勾表示已交付、等待验收；两个勾才表示已验收完成。"
    let webInfoCloseabilityMeaning = "钥匙表示这个 session 现在能不能安全关闭，与是否已交付是两件不同的事。"
    let webInfoUsage = "Token 用量"
    let webInfoInput = "输入"
    let webInfoOutput = "输出"
    let webInfoCacheRead = "缓存读取"
    let webInfoCacheWrite = "缓存写入"
    let webInfoTotal = "合计"
    let webInfoCost = "估算费用"
    let webInfoNoUsage = "还找不到这个 session 的对话记录。"
    let webInfoLimits = "套餐额度"
    let webInfoLimitHit = "额度用完"
    let webInfoResets = "{when} 重置"
    let webInfoUnknown = "未知"
    let webInfoFiles = "文件变化"
    let webInfoBranch = "分支"
    let webInfoStaged = "已暂存"
    let webInfoUnstaged = "已修改"
    let webInfoUntracked = "未跟踪"
    let webInfoConflict = "冲突"
    let webInfoClean = "没有未 commit 的东西。"
    let webInfoNotRepo = "这不是一个 git 仓库。"
    let webInfoDeploy = "最近一次 deploy"
    let webInfoNoDeploy = "这个项目没有 deploy 记录。"
    let webInfoFailed = "读不到这个 session 的信息。"
    let webInfoBusy = "Mac 正忙着读别的 session，等一下再试。"
    let webInfoRefresh = "刷新"
    let webInfoTokens = "tokens"
    let webInfoSwitchModel = "切换模型"
    let webInfoModelOther = "其他模型…"
    let webInfoModelSent = "已发送 /model {model}，确认中…"
    let webInfoModelBusy = "要等会话空闲时才能切换模型。"
    let webInfoSwitchPermission = "切换权限模式"
    let webInfoPermissionAuto = "自动"
    let webInfoPermissionManual = "手动"
    let webInfoPermissionAcceptEdits = "接受编辑"
    let webInfoPermissionPlan = "计划"
    let webInfoPermissionUnreadable = "读不到当前模式。"
    let webInfoPermissionSent = "已切换到“{mode}”，确认中…"
    let webInfoPermissionBusy = "正在发送权限模式切换。"
    let webInfoLimitsClaude = "Claude Code 只在额度用完时才会记录，在那之前这里没有数据。"
    let webInfoCopied = "已复制会话 id。"
    let webInfoAsOf = "截至 {when}"
    let webInfoWhyUnknown = "为什么是未知、怎么把数字接上"
    let webSettingsOrder = "对话记录"
    let webSettingsOrderSay = "对话记录要从哪一头开始读。每个 session 都算，键盘上按 `r` 也是同一件事。"
    let webAskLabel = "问了"
    let webAskAny = "这些选几个都可以"
    let webWaitingTitle = "这个 session 在等你回答"
    let webWaitingSay = "Claude Code 正在 Mac 上显示一个菜单。Clawdline 还没法从这里读菜单，所以那些选项只在那个屏幕上。"
    let webWaitingSend = "*从这里发出去，不会把你的回答打进菜单里*——它只会确认菜单上高亮的那一个，而那很少是你要的。这一题请在 Mac 上回答。"
    let webMenuSay = "点一个答案，它会直接发到那个 session。"
    let webMenuHighlighted = "高亮中"
    let webMenuSent = "答案发出去了。"
    let webAgents = "后台 agent"
    let webAgentsCount = "{n} 个在跑"
    let webAgentDone = "完成"
    let webAgentFailed = "失败"
    let webShells = "后台 shell"
    let webShellTitle = "后台 shell"
    let webShellOpen = "看这个命令打印了什么"
    let webShellRunning = "还在跑"
    let webShellEnded = "已结束"
    let webShellQuiet = "还没打印任何东西。"
    let webShellFailed = "读不到这个命令的输出。"
    let webShellClose = "关闭"
    let webShellStop = "停掉"
    let webShellStopTitle = "要停掉这个命令吗？"
    let webShellStopSay = "{command} 还在跑。会先请它自己收尾，五秒后还没停就直接砍掉。它已经做完的事不会回复。"
    let webShellStopped = "已经请它停下来。"
    let webShellStopFailed = "停不掉。"
    let agentRunning = "在跑"
    let agentTools = "{n} 个工具"
    let agentEmpty = "这个 agent 还没留下任何记录。"
    let agentBack = "对话"
    let webAgentOpen = "看这个 agent 做了什么"
    let webTaskRoot = "主 session"
    let webTaskChild = "子 session"
    let webTaskTasks = "工作"
    let webTaskDone = "完成"
    let webTaskFailed = "失败"
    let webTaskRunning = "在跑"
    let webStale = "Clawdline 在 Mac 上重新编过了。这一页是旧的那一版。"
    let webStaleGo = "重新加载"

    let menuApplication = "Clawdline"
    let menuWindow = "窗口"
    let menuHelp = "帮助"
    let menuClose = "关闭窗口"
    let menuHome = "主页／设置中心"
    let menuHelpDocumentation = "Clawdline 文档"
    let homeTitle = "Clawdline 主页"
    let homeWelcome = "先选择你想连接到哪里。设置会显示实际证据，而不只是你切换了哪个开关。"
    let homePurpose = "你想连接什么？"
    let homeLocalTitle = "本机浏览器"
    let homeLocalSummary = "在这台 Mac 的浏览器中读取 Clawdline。除非你在“设置”中明确开启，否则控制功能保持关闭。"
    let homeCloudPreviewTitle = "Clawdline Cloud 预览"
    let homeCloudPreviewSummary = "实时连接可验证后，使用 Clawdline 托管的预览路径。"
    let homeCloudflareTitle = "我的 Cloudflare 网址"
    let homeCloudflareSummary = "公开 HTTPS 路径可验证后，使用你自己的 Cloudflare 主机名。"
    let homeUnavailable = "此版本尚未就绪，也不会声称连接成功。"
    let setupDetected = "检测到的状态"
    let setupNextAction = "下一步"
    let setupExpected = "预期结果"
    let setupRecovery = "恢复方法"
    let setupLocalServerOff = "本机回环服务器已关闭。"
    let setupLocalChecking = "正在检查实际的 /v1/health 端点…"
    let setupLocalReady = "健康端点已就绪，尚未创建浏览器凭据。"
    let setupLocalWaiting = "浏览器已打开；正在等待此设备完成验证。"
    let setupLocalConnected = "已连接。这个浏览器设备确实已联系 Clawdline。"
    let setupLocalEnable = "开启本机浏览器"
    let setupLocalRetry = "再次检查"
    let setupLocalOpen = "打开只读浏览器"
    let setupLocalOpenAgain = "再次打开浏览器"
    let setupFinish = "完成"
    let setupLocalExpected = "只读浏览器会打开并完成验证；即使没有活动会话也算成功。"
    let setupLocalRecovery = "如果停在这里，请保持窗口打开并再次检查。也可在“设置”中查看服务器和端口。"
    let setupReadOnly = "只读 · 控制功能保持关闭"
    let setupLocalDeviceName = "这台 Mac 上的浏览器"

    let menuOpen = "打开输入框"
    let menuReveal = "跳到目标标签页"
    let menuMascot = "吉祥物"
    let menuLogin = "开机时启动"
    let menuEditConfig = "设置……"
    let menuReload = "重新加载配置"
    let menuQuit = "退出 Clawdline"
    let menuNoTarget = "（尚未检测到）"

    func hotkeyFailedTitle(_ combo: String) -> String { "\(combo) 注册不上" }
    func hotkeyFailedBody(_ configPath: String) -> String {
        """
        多半是被别的软件占走了——Spotlight、输入法切换、BetterTouchTool 之类。

        换一个：编辑 \(configPath) 里的 hotkey，然后从菜单栏选「重新加载配置」。

        在那之前，菜单栏的 ✳ 一样打得开输入框。
        """
    }
    let loginFailed = "设置开机启动失败"
}
