import Foundation

struct Japanese: Copy {
    let placeholder = "Claude Code にメッセージ…"

    let hintSend = "送信"
    let hintNewline = "改行"
    let hintSwitch = "切替"
    let hintList = "一覧"
    let hintMascot = "マスコット"
    let hintOutput = "出力"
    let hintFullscreen = "全画面"
    let hintKeys = "キー"
    let hintTextSize = "文字サイズ"
    let hintOrder = "逆順"
    let hintVoice = "音声入力"
    func voiceListening(onDevice: Bool) -> String {
        onDevice ? "この Mac で認識中 — もう一度押すと終了"
                 : "認識中 — この言語は Apple 側で処理されます（この Mac ではありません）"
    }
    let voiceNoPermission = "音声入力にはマイクと音声認識の許可が必要です"
    let voiceUnavailable = "音声入力は現在使えません"
    func voiceTranscribing(seconds: Double) -> String {
        String(format: "Whisper が読み直しています… %.1f 秒", seconds)
    }
    let whisperMissing = "Whisper がインストールされていません — docs/whisper.md を参照"
    let whisperNothingHeard = "何も聞こえませんでした"
    func dictationStatus(_ status: Whisper.Status) -> String {
        switch status {
        case .ready(let model): return "音声入力：Apple のあとに Whisper（\(model)）"
        case .noBinary: return "音声入力：Apple のみ — whisper-cli がありません"
        case .noModel: return "音声入力：Apple のみ — whisper-cli はあるがモデルがありません"
        }
    }
    func voiceListeningWhisper() -> String { "認識中 — 話し終えると Whisper が読み直します" }

    let scanning = "検索中…"
    let noSession = "Claude Code のセッションが見つかりません"
    let nothingToSend = "送信先がありません — まずターミナルで Claude Code を起動してください"
    let sendFailed = "送信できませんでした"
    let itermSilent = "iTerm2 から応答がありません"
    let itermBusy = "iTerm2 がダイアログの返事を待っています — Mac で応答してください"
    let scriptMissing = "iterm.js が見つかりません — アプリバンドルが壊れている可能性があります"
    let cannotList = "iTerm2 のセッションを読み取れませんでした"
    let noOutput = "このセッションにはまだ読むものがありません。"
    let imageExpired = "画像の有効期限が切れました"
    let imagePreview = "画像プレビュー"
    let imageClose = "プレビューを閉じる"
    func outputSize(_ pt: Int) -> String { "出力の文字サイズ \(pt)pt — ⌘J で表示" }
    func foldedTools(_ count: Int) -> String { "\(count) ステップ" }
    func outputOrder(newestFirst: Bool) -> String {
        newestFirst ? "新しい順" : "古い順"
    }
    func backlogNow(_ count: Int) -> String { "現在 \(count)" }
    func dropped(_ count: Int) -> String {
        count == 1 ? "パスを追加しました — Claude Code が読み込みます" : "\(count) 件のパスを追加しました"
    }
    func stackConfirm(_ command: String) -> String { "もう一度押すと実行します：\(command)" }
    let hintStacks = "サーバー"
    func stackTip(up: Int, total: Int) -> String { "サーバー \(total) 個のうち \(up) 個が稼働中 — ⌘S で一覧" }
    let stackTipUnknown = "このプロジェクトにはサーバーがありますが、status コマンドはまだ信頼されていません — ⌘S"
    let stackUntrusted = "未承認"
    let stackExit = "終了コード"
    let stackActionStart = "起動"
    let stackActionRestart = "再起動"
    let stackActionStop = "停止"
    let stackActionLogs = "ログ"
    let stackLogAll = "すべて"
    let stackLogBack = "トランスクリプト"
    let stackActionAllow = "許可"
    let stackActionAgain = "もう一度"
    func sessionTip(index: Int, total: Int) -> String { "\(total) 件中 \(index) 番目のセッション — ⌘K で切り替え" }
    let sessionWaiting = "返事待ち"
    let sessionAgents = "バックグラウンドに {n} 件"
    let sessionShellOne = "シェル 1 件実行中"
    let sessionShellMany = "シェル {n} 件実行中"
    let sessionWaitedOnByOne = "1 件があなた待ち"
    let sessionWaitedOnByMany = "{n} 件があなた待ち"
    let islandDone = "完了"
    let islandAllSessions = "すべてのセッション…"
    func statusWaiting(_ labels: [String]) -> String {
        labels.count == 1 ? "\(labels[0]) が返事を待っています"
                          : "\(labels.count) 件のセッションが返事を待っています"
    }
    func statusWorking(_ count: Int) -> String { "\(count) 件が実行中" }

    let settingsTitle = "Clawdline の設定"
    let settingsGeneral = "一般"
    let settingsBar = "バー"
    let settingsReading = "読む"
    let settingsVoice = "音声入力"
    let settingsHotkey = "ホットキー"
    let settingsRecording = "キーを押してください…"
    let settingsScope = "有効にするアプリ"
    let settingsScopeGlobal = "すべてのアプリ"
    let settingsScopeHint = "空ならどこでも効きます。だから最後のひとつを外すと上のスイッチが入り、それをまた切るとこの一覧が戻ります。設定ファイルにはバンドル ID として入っていて、手で書いた一覧もそのまま使えます。"
    let settingsSessionTerminal = "新しいセッションを開く場所"
    let settingsSessionTerminalHint = "上のホットキーが効く場所とは別の設定です。自動は iTerm2 が開いていればそちら、開いていなければ tmux。iTerm2 を選ぶと iTerm2 そのものを指名することになり、横で tmux サーバーが動いていても答えにはならず、iTerm2 が閉じていれば断ります。tmux を選ぶと iTerm2 が開いていても tmux サーバーの中に入ります。次に開くセッションから効き、再起動は要りません。"
    let settingsScopeAdd = "アプリを追加…"
    let settingsScopeChoose = "アプリを選ぶ…"
    let settingsScopeRunning = "いま開いているもの"
    let settingsScopeRemove = "外す"
    let settingsLanguage = "言語"
    let settingsReopen = "バーはターミナルと一緒に出入りする"
    let settingsReopenHint = "ターミナルから離れるとバーはしまわれ、ターミナルに戻るとまた出てきます。終わったという意味になるのは Esc です。"
    let settingsFollow = "バーが狙っているものをターミナルにも出す"
    let settingsFollowHint = "そのセッションのタブを選びます。ターミナルを前面には出しません。出してしまうと、Tab を押すたびに入力中の欄からキーボードが離れてしまうからです。"
    let settingsCodexAutoName = "新しいセッションに名前を付ける"
    let settingsCodexAutoNameHint = "名前のないセッションごとに、選んだアシスタントで小さな turn を一度実行します。最初の依頼を使い、そのアシスタントの利用量を消費し、自分で付けた名前は変更しません。"
    let settingsNotch = "ノッチに住む"
    let settingsNotchHint = "カメラ部分にキャラクターが出ます。オフなら何も描かず、ウィンドウも作りません。"
    let settingsPosition = "画面上の高さ"
    let settingsWidth = "幅"
    let settingsOpacity = "カードの不透明度"
    let settingsShow = "表示"
    let settingsPaneHeight = "ペインの高さ"
    let settingsTextSize = "文字サイズ"
    let settingsPaneFont = "ペインのフォント"
    let settingsBlur = "背景のぼかし"
    let settingsNewestFirst = "新しい順"
    let settingsEngine = "認識エンジン"
    let settingsSettle = "この長さの間で文を区切る"
    let settingsStop = "この長さの無音で終了"
    let settingsAuto = "自動"
    let settingsTranscript = "トランスクリプト"
    let settingsTerminal = "ターミナル"
    let settingsOff = "オフ"
    let settingsHooks = "Claude Code のフック"
    let settingsHooksHint = "入れておくと、応答が始まった瞬間、終わった瞬間、返事を待っている瞬間を Claude Code のほうから知らせます。Clawdline が次に見にいくまで待ちません。読み取り自体はこれまでどおり画面からで、ここで決まるのは速さだけです。"
    let settingsHooksInstall = "入れる"
    let settingsHooksRemove = "外す"
    let settingsHooksOff = "未設定 — 状態はすべて画面から読んでいます"
    let settingsHooksOn = "設定済み — まだどのセッションからも届いていません"
    let settingsHooksLive = "設定済み。セッションから届いています"
    let settingsStateHook = "セッションの状態が変わったとき"
    let settingsStateHookHint = "セッションが動き出したとき、終わったとき、あなたに何か尋ねたとき、Clawdline はこれを実行します。あなた自身のプログラムを、詳細を環境変数に入れて渡します。ここではなく設定ファイルで書くのは、これがコマンドラインではなく argv の並びだからです。空白の入ったパスは、ひとつのパスのままでなければなりません。"
    let settingsRemote = "リモート"
    let settingsRemoteServe = "ブラウザやスマートフォンからセッションを見られるようにする"
    let settingsRemoteHint = "オフのあいだ、この Mac の外からは何にも届きません。オンにすると、セッションの一覧が 127.0.0.1 に出ます。ここのブラウザにも、トンネル越しのスマートフォンにも、スクリプトにも。そこで渡るのはリポジトリ名とブランチとタスクの見出しなので、あなたが言い出すまではオフのままです。"
    let settingsRemoteDevices = "ペアリング済み機器"
    let settingsRemoteNoDevices = "まだありません — この Mac の外からは何も読めません"
    let settingsRemoteRevokeAll = "すべて切断"
    let settingsRemoteOpen = "ブラウザで開く"
    let pairingIgnore = "無視"
    func pairingAsks(_ device: String) -> String { "\(device) がこの Mac とペアリングしようとしています" }
    func pairingCode(_ code: String) -> String {
        """
        その機器に次のコードを入力してください：

        \(code)

        有効なのは 2 分間です。心当たりがなければ無視してかまいません。このコードがなければ、\
        求めてきた相手は先へ進めません。
        """
    }
    let settingsTunnel = "どこからでもこの Mac に届く"
    let settingsTunnelQuick = "自動で作られるアドレス"
    let settingsTunnelNamed = "自分のドメイン"
    let settingsTunnelHostname = "ホスト名"
    let settingsTunnelHint = "cloudflared を通して、この Mac のほうから外へつなぎます。ポート開放も要らず、あなたのネットワークで待ち受けるものもありません。機器がひとつペアリングされるまでは起動しません。トンネルの向こうにあるのは、この Mac のリポジトリ名とタスクの見出しのすべてだからです。"
    let settingsRemoteWrite = "ペアリング済みの機器がセッションに書き込めるようにする"
    let settingsRemoteWriteHint = "オフのあいだ、ペアリング済みの機器は読むだけです。オンにすると、セッションに文字を送ることも、新しいセッションを始めることもできます。それはこの Mac 上でコードを実行するということです。Claude Code がやっているのはまさにそれだからです。上の項目とは別の判断なので、スイッチも別にしてあります。"
    let settingsRemotePhone = "スマートフォンとペアリング…"
    let settingsRemotePhoneHint = "読み取るためのコードを表示します。そのコードは自分の鍵を持っているので、写真に撮られても増えるのは、この一覧に出てきていつでも外せる機器がひとつだけです。この Mac 自身の鍵ではありません。"
    let pairingScanTitle = "これをスマートフォンで読み取ってください"
    let pushWaiting = "が答えを待っています"
    let pushTest = "これはテスト通知です。ひととおりつながっています。"
    let pushDelivered = "が完了を報告しました。確認待ちです"
    let pushDeployOk = "のデプロイが成功しました"
    let pushDeployFail = "のデプロイが失敗しました"
    func pushChildWaiting(minutes: Int?) -> String {
        guard let minutes else { return "の子セッションが答えを待っています" }
        return "の子セッションが答えを待っています — 残り \(minutes) 分"
    }
    func pushBatchDone(done: Int, failed: Int) -> String {
        let all = "の \(done) 件のタスクが終わりました"
        return failed == 0 ? all : "\(all)（\(failed) 件失敗）"
    }
    let settingsPushDelivery = "セッションが完了を報告したら知らせる"
    let settingsPushDeliveryHint = "報告 1 件につき 1 回。同じ報告の繰り返しでは鳴りません。"
    let settingsPushFanout = "まとめて出したタスクが全部終わったら知らせる"
    let settingsPushFanoutHint = "ひとまとまりにつき 1 通、失敗した件数つきです。"
    let settingsSmartNotifications = "スマート通知"
    let settingsSmartNotificationsHint = "Haiku が完了した内容を一文で伝えます。失敗時は通常の通知に戻ります。"
    func pushCoalesced(count: Int) -> String { "\(count) 件の作業がまとめて完了" }
    let settingsSmartHealthIdle = "スマート通知はまだ試行されていません。"
    func settingsSmartHealth(attempts: Int, successes: Int) -> String {
        "\(attempts) 回の試行のうち \(successes) 回がモデルの文を届けました。"
    }
    func settingsSmartHealthFailure(reason: String, time: String) -> String {
        "最後に通常の通知へ戻ったのは \(time)：\(reason)。"
    }
    func settingsSmartTimeout(seconds: Int) -> String {
        "Claude が \(seconds) 秒の期限を超えたため打ち切られました"
    }
    let settingsSmartQueueFull = "同時に完了した数がキューの容量を超えました"
    let settingsSmartModelFailed = "Claude から使える出力がありませんでした"
    let settingsSmartNoSource = "要約できる内容がありませんでした"
    let settingsSmartMissing = "claude の実行ファイルが見つかりません"
    let settingsPushDeploy = "デプロイが終わったら知らせる"
    let settingsPushDeployHint = "成功も失敗も知らせます。"
    let settingsAgentNotify = "エージェントからの通知を許可する"
    let settingsAgentNotifyNote = "エージェントが自分から送る内容だけを管理します。作業完了、デプロイ、その他の通知には影響しません。"
    let settingsOrchestrator = "別のセッションに任せる"
    let settingsOrchestratorEnabled = "セッションが別のセッションに仕事を出せるようにする"
    let settingsOrchestratorEnabledHint = "clawdline スキルを持つセッションが、新しいタブを開いて指示を打ち込み、終わったら知らせを受け取れます。オフのあいだは依頼をすべて断ります。すでに動いているものは止めません。"
    let settingsOrchestratorMax = "同時に動かす子セッション"
    let settingsOrchestratorMaxHint = "既定は 5 つ。Mac 全体ではなくセッションごとの数です。どれもアシスタントが 1 つ入ったターミナルのタブです。"
    let settingsOrchestratorPermission = "子セッションがどこまで自分で進むか"
    let settingsOrchestratorPermissionHint = "子セッションのタブは誰も見ていないので、承認待ちで止まったセッションはタイムアウトまで止まったままです。そして派遣されたセッションの仕事はまるごとコマンドの実行とファイルの書き込みなので、最後の段より手前だとどこかで必ず止まります。タスクはこれより控えめに要求できますが、これを超えることはできません。"
    let settingsOrchestratorPermissionAsk = "一歩ごとに確認する"
    let settingsOrchestratorPermissionEdits = "ファイルの書き込みは確認しない"
    let settingsOrchestratorPermissionFull = "確認しない"
    let settingsOrchestratorNotify = "頼んだセッションに知らせる"
    let settingsOrchestratorNotifyHint = "仕事が終わったとき、そのセッションに 1 行打ち込みます。"
    let settingsOrchestratorClose = "子セッションが報告したら"
    let settingsOrchestratorCloseHint = "報告のあとでタブを閉じます。時間切れになったものは、読めるように残します。"
    let settingsOrchestratorCloseNow = "すぐにタブを閉じる"
    let settingsOrchestratorCloseLinger = "3 分たってから閉じる"
    let settingsOrchestratorCloseKeep = "閉じずに残す"
    let settingsOrchestratorPolicy = "仕事の配り方"
    let settingsOrchestratorPolicyHint = "派遣のたびに Clawdline が読み、さらに派遣できる子セッションすべての指示に書き写すルールです。どのアシスタントか、どのモデルか、グラフをどんな形にするか。空なら決まりごとはありません。"
    let settingsOrchestratorPolicyEdit = "ルールを編集"
    func settingsOrchestratorPolicyOn(_ lines: Int) -> String { return "有効 — \(lines) 行" }
    let settingsOrchestratorPolicyOff = "決まりごとなし — 出すたびに出す側が決めます"
    let settingsSchedules = "スケジュール"
    let settingsSchedulesEmpty = "スケジュールはまだありません。下の「新しいスケジュール」で最初の一つを作れます。"
    let settingsScheduleNew = "新しいスケジュール"
    let settingsScheduleEdit = "編集"
    let settingsScheduleSave = "保存"
    let settingsScheduleDelete = "削除"
    let settingsScheduleRun = "今すぐ実行"
    let settingsScheduleReveal = "Finderで表示"
    let settingsSchedulesFolder = "schedulesフォルダを開く"
    let settingsScheduleNext = "次回"
    let settingsScheduleLast = "前回"
    let settingsScheduleNever = "未実行"
    let settingsScheduleStarted = "実行を開始しました。"
    let settingsScheduleActive = "前回のスケジュールタスクはまだ実行中です。"
    let webScheduleMissed = "前回の未実行"
    let webScheduleNoNext = "次回の実行予定はありません。"
    func childAnnounce(_ title: String) -> String { "Clawdline から依頼を受け取りました：\(title)——いまから取りかかります。" }
    func settingsSeconds(_ value: Double) -> String { String(format: "%.1f 秒", value) }

    let webConnLive = "受信中"
    let webConnConnecting = "接続中"
    let webConnRetrying = "{n} 秒後に再接続"
    let webConnOffline = "オフライン"
    let webConnLocked = "未ペアリング"
    let webConnTipLive = "アプリから流れてきています"
    let webConnTipLocked = "このブラウザはまだ Mac とペアリングされていません"
    let webConnTipDown = "つながっていません — 押すといま試します"

    let webCountWorking = "{n} 件が実行中"
    let webCountWaiting = "{n} 件が返事待ち"
    let webCountUnreadable = "{n} 件が読めません"
    let webCountQuietOne = "セッション {n} 件、どれも静か"
    let webCountQuietMany = "セッション {n} 件、どれも静か"
    let webCountNone = "セッションなし"

    let webFilterPlaceholder = "タスク・プロジェクト・tty で絞り込む"
    let webFilterLabel = "セッションを絞り込む"
    let webListLabel = "Claude Code のセッション"
    let webPull = "引いて更新"
    let webPullRelease = "離すと更新"
    let webPullBusy = "更新中…"
    let webEmptyFilterTitle = "「{q}」に合うものがありません"
    let webEmptyFilterHint = "Esc で絞り込みが消えます"
    let webEmptyLockedTitle = "この端末はペアリングされていません"
    let webEmptyLockedHint = "アプリが 401 を返しました — Mac の Clawdline からペアリングしてください"
    let webEmptyNoneHint = "ターミナルで始めればここに出てきます"
    let webEmptyWaitTitle = "アプリを待っています"
    let webEmptyWaitHint = "まだ何も届いていません"
    let webStateUnreadable = "画面を読めませんでした"
    let webStateWorking = "実行中"
    let sessionWorkReady = "新しい作業を渡せます"
    let sessionWorkUnknown = "状態不明"
    let sessionWorkHolding = "自動で進行中"
    let sessionWorkOwed = "決定が保留中です"
    let sessionWorkSelfStated = "自己申告"
    let sessionWorkMilestone = "マイルストーン納品済み。レビューまたは反映が残っている可能性があります"
    let sessionWorkComplete = "ブローカー検証済みの対象ブランチ反映"
    let closeabilitySafe = "安全に閉じられます"
    let closeabilityBlocked = "未了の義務が {n} 件"
    let closeabilityBlockedOne = "未了の義務が 1 件"
    let closeabilityBlockedMany = "未了の義務が {n} 件"
    let closeabilityNeedsAttestation = "セッション自身の確認待ち"
    let closeabilityUnknown = "閉じてよいか不明"
    let closeabilityWhy = "閉じられない理由"
    let closeabilityMoverSelf = "このセッションが動かします"
    let closeabilityMoverPerson = "あなたが動かします"
    let closeabilityMoverSession = "別のセッションが動かします"
    let closeabilityMoverBroker = "読み直しが必要です"
    let closeabilityNotProven = "このセッションを安全に閉じられるとブローカーは証明できませんでした。"
    let closeabilityAttestationExplanation = "未完了の作業が見つかったという意味ではありません。Clawdline が確認できる項目には問題ありませんが、このセッションはローカルの変更、未提出の作業、または Clawdline 外の作業が残っていないかをまだ確認していません。閉じる前にセッションを確認してください。"
    let closeabilityTechnicalDetails = "技術的な詳細"

    let webBack = "セッション"
    let webBackLabel = "セッション一覧に戻る"
    let webNoSessionOpen = "開いているセッションがありません"
    let webOrderTip = "トランスクリプトを逆順に（r）"
    let webShowOnMac = "Mac に表示"
    let webShowOnMacTip = "このセッションのターミナルを Mac の前面に出します"
    let webShowOnMacOff = "サーバーが write: false と答えています — まだ何も送れません"
    let webShowOnMacAsked = "前面に出すよう Mac に頼みました"
    let webSessionActions = "セッション操作"
    let webSessionGit = "Git の変更"
    let webGitTitle = "Git の変更"
    let webGitClean = "作業ツリーに変更はありません"
    let webGitNotRepo = "Git リポジトリではありません"
    let webGitFailed = "Git の変更を読み込めませんでした"
    let webGitRefresh = "再読み込み"
    let webGitClose = "閉じる"
    let webGitStaged = "ステージ済み"
    let webGitUnstaged = "未ステージ"
    let webGitUntracked = "未追跡"
    let webGitConflict = "競合"
    let webEndSession = "セッションを閉じる"
    let webConfirmActionTitle = "{action} を実行しますか？"
    let webConfirmActionSay = "現在のセッションに {action} を送信します。"
    let webConfirmEndTitle = "このセッションを閉じますか？"
    let webConfirmEndSay = "アシスタントを終了してから、ターミナルのタブを閉じます。"
    let webConfirmEndLoses = "閉じると同時に終了します："
    let webClawdfatherCreateLabel = "新しいセッションを Clawdfather と名づける"
    let webClawdfatherIs = "このセッションが {name} です"
    let webClawdfatherRegisterAsk = "この新しいセッションを、この Mac の Clawdfather、つまり machine coordinator として登録してください。あなたの terminal-neutral session id は {id} です。まず ~/.config/clawdline/orchestrator-token の orchestrator token で coordinator の記録を読んでください。coordinator が 1 つも登録されていない場合にかぎり、docs/orchestrator.md の「Becoming Clawdfather」の登録の手順に従ってください。すでに登録された coordinator があるなら、たとえオフラインでも置き換えないでください。終わったら結果を教えてください。"
    let webClawdfatherRegisterSent = "新しいセッションに Clawdfather になるよう伝えました"
    let webClawdfatherRegisterLate = "新しいセッションが間に合わず、Clawdfather と名づけられませんでした。"
    let webClawdfatherRegisterBlocked = "この Mac の coordinator の記録が読めないので、そのままにしてあります。"
    let webCoordSectionObserve = "観察"
    let webCoordSectionCoordinate = "調整"
    let webCoordSectionPresence = "在席状況"
    let webCoordSectionAdmin = "管理"
    let webCoordCmdStatusReport = "状況報告"
    let webCoordCmdStatusReportSay = "Clawdfather の現在の状況と進行中の責務を読みます。"
    let webCoordCmdSinceAway = "離れていた間に"
    let webCoordCmdSinceAwaySay = "前回の復帰点以降に記録された変更と決定を読みます。"
    let webCoordCmdDuplicates = "重複・衝突・担当"
    let webCoordCmdDuplicatesSay = "重複した作業、衝突する担当宣言、現在の担当を確かめます。"
    let webCoordCmdLandingClosure = "取り込みの締め"
    let webCoordCmdLandingClosureSay = "レビュー済みでまだ root の取り込みを待つ納品を読みます。"
    let webCoordCmdCoordinateWork = "作業の調整"
    let webCoordCmdCoordinateWorkSay = "進行中の作業に対する調整手順の下書きを作ります。"
    let webCoordCmdDispatch = "独立作業の割り当て"
    let webCoordCmdDispatchSay = "独立した子セッションを開くことになる割り当てをプレビューします。"
    let webCoordCmdAsk = "Clawdfather に尋ねる"
    let webCoordCmdAskSay = "Clawdfather の判断を仰ぐ質問の下書きを作ります。"
    let webCoordCmdQuietWatch = "静かな見守り"
    let webCoordCmdQuietWatchSay = "待機アラートを立てない静かな監視依頼の下書きを作ります。"
    let webCoordCmdScope = "範囲と権限"
    let webCoordCmdScopeSay = "Clawdfather の現在の範囲と与えられた権限を読みます。"
    let webCoordCmdStop = "Clawdfather を停止"
    let webCoordCmdStopSay = "Clawdfather の停止をプレビューします。"
    let webCoordCmdReconnect = "Clawdfather を再接続"
    let webCoordCmdReconnectSay = "Clawdfather の再接続をプレビューします。"
    let webCoordCmdDeepAudit = "詳細ステータス監査"
    let webCoordCmdDeepAuditSay = "関連する Session の作業、納品、判断を Clawdfather に監査させます。"
    let webCoordTokenExpected = "予想 Token 負荷：{effort}"
    let webCoordTokenLow = "低"
    let webCoordTokenMedium = "中"
    let webCoordTokenHigh = "高"
    let webCoordTokenUnknown = "不明"
    let webCoordAuditPreview = "Token 負荷が高い複数 Session の要求です。まだ何も送信されていません。確認すると、完全な監査指示をこの Clawdfather Session に送信します。この初版は agent 駆動で、broker に永続的な run 記録はありません。"
    let webCoordAuditWhyOffline = "Clawdfather はオフラインのため、監査要求を送信できません。"
    let webCoordAuditWhyDisconnected = "このブラウザはオフラインのため、監査要求を送信できません。"
    let webCoordAuditWhyNoWrite = "このブラウザには現在、送信／書き込み権限がありません。"
    let webCoordAuditSending = "要求を送信中…"
    let webCoordAuditSent = "監査要求を送信しました。この受領表示は監査完了を意味しません。"
    let webCoordAuditFailed = "監査要求は送信されませんでした（{code}）：{message}"
    let webCoordEffectRead = "読み取りのみ"
    let webCoordEffectAdvisory = "助言"
    let webCoordEffectSpawns = "セッションを開始"
    let webCoordEffectMutation = "状態を変更"
    let webCoordStateAvailable = "利用可"
    let webCoordStateDraft = "下書き"
    let webCoordStateUnavailable = "利用不可"
    let webCoordStatePreview = "プレビュー"
    let webCoordStateDisabled = "無効"
    let webCoordOnline = "{name} はオンライン"
    let webCoordOffline = "{name} はオフライン"
    let webCoordControlsTitle = "{name} の操作"
    let webCoordOpenControls = "{name} の操作を開く"
    let webCoordEmpty = "このページが知っている Clawdfather コマンドは届いていません。"
    let webCoordDisabledFallback = "Clawdfather により無効化されています。"
    let webCoordPreviewTitle = "Clawdfather コマンド"
    let webCoordPreviewNone = "コマンドが選ばれていません。何も送信されていません。"
    let webCoordPreviewMutation = "プレビューのみ — 何も送信されていません。Clawdfather コマンド API が接続されるまで、確認は押せないままです。"
    let webCoordPreviewDraft = "オフラインの下書きのみ — 何も送信されておらず、Clawdfather の判断として示されてもいません。"
    let webCoordPreviewSpawn = "プレビューのみ — セッションは開始されていません。"
    let webCoordPreviewContract = "このコマンドの契約を示しているだけです。何も送信されていません。"
    let webCoordWhyNoCommandRoute = "このパネルからセッションへコマンドを運ぶ経路がまだないため、何も送れません。"
    let webCoordWhyNoReturnLedger = "この Mac はまだ復帰点を記録していないため、照らして読むものがありません。"
    let webCoordWhyDeviceCannotSpawn = "ペアリングされた端末は決してセッションを開始できません — この分離は意図されたもので、このボタンはそれを越えません。"
    let webCoordWhyMachineTokenOnly = "再接続には Mac 自身の orchestrator トークンが必要で、ペアリングされた端末は意図的にそれを持ちません。"
    let webCoordReadFailed = "Clawdfather の現況を読めませんでした。"
    let webCoordActiveTasks = "{n} 件のタスクが進行中"
    let webCoordPendingLandings = "{n} 件の納品が取り込み待ち"
    let webCoordOpenWaits = "{n} 件のファイル待ちが未解除"
    let webCoordCountUnknown = "{n} 件状態不明"
    let webCoordStaleSessions = "Mac のセッション像が古くなっています。これらの数字は古い可能性があります。"
    let webCoordUnknown = "状態不明"
    let webCoordWaitingList = "誰かを待っている"
    let webCoordBlockingList = "他が待つファイルを保持"
    let webCoordAllQuiet = "詰まっているもの、取り合いになっているもの、担当のないものはありません。"
    let webCoordNoLandings = "取り込みを待つ納品はありません。"
    let webCoordUnregistered = "この Mac には Clawdfather が登録されていません。"
    let webCoordScopeLine = "{name} はこの Mac を調整します — 範囲はマシン全体。"
    let webCoordScopeDevice = "このパネルからは Clawdfather を読むことしかできません。作業の送信、セッションの開始、マシン状態の変更には Mac 自身の資格情報が必要で、ここでは無効のままです。"
    let webClosing = "閉じています…"
    let webCancel = "キャンセル"
    let webConfirm = "確認"
    let webReviewBeforeClosing = "セッションを確認"
    let webConfirmEndAnyway = "このまま閉じる"
    let webPickSession = "左からセッションを選んでください。"
    let webReading = "読み取り中…"
    let webLoading = "読み込み中…"
    let webTranscriptFailed = "トランスクリプトを読めませんでした"
    let webWhoYou = "あなた"
    let webWhoTool = "ツール"
    let webNoticeTask = "タスク"
    let webNoticeCompleted = "タスク完了"
    let webNoticeFailed = "タスク失敗"
    let webNoticeTimedOut = "タスクがタイムアウトしました"
    let webNoticeCancelled = "タスクはキャンセルされました"
    let webNoticeCouldNotStart = "タスクを開始できませんでした"
    let webNoticeFinished = "タスク終了"
    let webNoticeWorkspaceOverlap = "ワークスペースの重複"
    let webNoticeNoSiblings = "実行中の同階層タスクはありません。"
    let webNoticeOneSibling = "同階層タスクが {n} 件実行中です。"
    let webNoticeManySiblings = "同階層タスクが {n} 件実行中です。"
    let webNoticeClaimsReleased = "パスの予約は解除されましたが、子タブがまだ書き込む可能性があります。"
    let webNoticeFileWaitRequested = "ファイル待機の依頼"
    let webNoticeFileWaitReleased = "ファイル待機を解除"
    let webNoticeHandoffPickedUp = "引き継ぎを受け取りました"
    let webNoticeHandoffNeedsDelivery = "引き継ぎを手動で届けてください"
    let webNoticeRecheckGit = "統合前に HEAD、status、diff を再確認してください。"
    let webPending = "Mac を待っています…"
    let webAttachedImage = "画像 {n} 枚を添付"
    let webAttachedImages = "画像 {n} 枚を添付"
    let webSteps = "{n} ステップ"
    let webJustNow = "たった今"
    let webMinutesAgo = "{n} 分前"
    let webCodeCopy = "このコードをコピー"
    let webCodeCopied = "コードをコピーしました。"
    let webCodeCopyFailed = "コピーできませんでした。テキストを選択してください。"

    let webSend = "送信"
    let webAttach = "画像を添付"
    let webRemoveShot = "{name} を外す"
    let webWriteOpen = "書き込むにはセッションを開いてください。"
    let webWriteOff = "*送信はオフです* — サーバーが `write: false` と答えています。この欄はつながっているので、そちらが変われば自分で使えるようになります。"
    let webShotsOnlyPictures = "メッセージに付けられるのは画像だけです"
    let webShotsTooMany = "1 通に付けられる画像は {n} 枚までです"
    let webShotTooBig = "この画像は縮めても送るには大きすぎます"
    let webShotsTooBig = "これらの画像はまとめて送るには大きすぎます"
    let webShotUnreadable = "この画像を読めませんでした"
    let webShotNeedsSession = "画像を送るにはセッションを開いてください"

    let webVoiceStart = "話してメッセージを書く"
    let webVoiceStop = "止めて文字にする"
    let webVoiceDone = "完了"
    let webVoiceListening = "聞いています… {t}"
    let webVoiceReading = "Mac で文字にしています… {n} 秒"
    let webVoiceSlow = "この Mac を再起動したあとの一回目はモデルの読み込みから始まります — 十二秒ほど。"
    let webVoiceLimit = "録音は {n} 分で止まりました。一回はそこまでです。ここまでの分を文字にします。"
    let webVoiceEmpty = "そこには何も聞こえませんでした。"
    let webVoiceTooShort = "短すぎて聞き取れませんでした。"
    let webVoiceDenied = "マイクが拒否されました。このブラウザの、このサイトの設定でオンに戻してください。"
    let webVoiceNoMic = "この端末にマイクが見つかりません。"
    let webVoiceInUse = "マイクが使用中です — この端末の別のものが握っています。"
    let webVoiceInsecure = "マイクには https が要りますが、このページはそうではありません。トンネルなら https が付いてきます。ローカルネットワークの素のアドレスには付いてきません。"
    let webVoiceUnsupported = "このブラウザは録音できません。"
    let webVoiceBusy = "一件を文字にしていて、もう一件が待っています。少ししてからどうぞ。"
    let webVoiceNoBinary = "Mac に Whisper が入っていないので、あちらには文字にするものがありません。"
    let webVoiceNoModel = "Mac に Whisper はありますが、読むためのモデルがありません。`~/.cache/whisper` に ggml ファイルが一つあれば足ります。"
    let webVoiceFailed = "それは文字にできませんでした。"

    let webHintMove = "移動"
    let webHintOpen = "開く"
    let webHintFilter = "絞り込み"
    let webHintPane = "ペイン"

    let webKeysLabel = "キーボードショートカット"
    let webKeysTitle = "キーボード"
    let webKeysMove = "一覧を上下に移動 — `j` と `k` も同じ"
    let webKeysOpen = "選んだセッションを開く"
    let webKeysFilter = "一覧を絞り込む"
    let webKeysEscape = "絞り込みを消して、それから戻る"
    let webKeysList = "セッション一覧にフォーカス"
    let webKeysPane = "トランスクリプトの表示を切り替え"
    let webKeysEnds = "トランスクリプトの先頭か末尾へ"
    let webKeysReverse = "トランスクリプトの順序を反転"
    let webKeysThis = "このカード"
    let webKeysFoot = "入力欄に打ったものは入力欄に残ります — 書いているあいだ、ショートカットは引っ込みます。"

    let webDoorLabel = "このブラウザをペアリング"
    let webDoorAskLede = "このブラウザはまだ通されていません。"
    let webDoorAskFine = "ペアリングを求めると、6 桁のコードが *Mac のほうに* 出ます — このページへの返事には、わざと入れていません。あの機械の前にいる人だけが終わらせられる。それが面倒ではなく、狙いそのものです。"
    let webDoorName = "この端末の名前"
    let webDoorAsk = "ペアリングを求める"
    let webDoorToPassword = "パスワードでサインインする"
    let webDoorCodeLede = "Mac を見てください。"
    let webDoorCodeFine = "Clawdline が 6 桁を映しています。残り {left}。ここに打ってください。"
    let webDoorTwoMinutes = "2 分"
    let webDoorDigit = "{n} 桁目"
    let webDoorConfirm = "この端末をペアリング"
    let webDoorRestart = "やり直す"
    let webDoorPasswordLede = "パスワードでサインインします。"
    let webDoorPasswordFine = "Mac の Clawdline の「設定 → リモート」で決めたものです。決めていなければ、ペアリングが入り口です。"
    let webDoorPassword = "パスワード"
    let webDoorPasswordGo = "サインイン"
    let webDoorToPair = "ペアリングコードを使う"
    let webDoorAsking = "Mac に頼んでいます…"
    let webDoorAskFailed = "Mac に頼めませんでした。"
    let webDoorRateLimited = "頼むたびに Mac に知らせが出るので、10 分に 3 回までです。"
    let webDoorSixDigits = "6 桁です。"
    let webDoorChecking = "確認中…"
    let webDoorFinished = "このペアリングは終わりました — 5 回間違えています。Mac の前に行ってから、もう一度どうぞ。"
    let webDoorWrongCode = "そのコードは違います。"
    let webDoorNeedPassword = "まずパスワードを。"
    let webDoorWrongPassword = "そのパスワードは違います。"
    let webDoorExpired = "そのコードは期限切れです。もう一度頼めば、新しいものが Mac に出ます。"
    let webDoorPaired = "ペアリングできました — このブラウザは中にいます"

    let webOffline = "Clawdline に届きませんでした。Mac でまだ動いていますか。"
    let webNotJSON = "サーバーが JSON でないものを返しました"
    let webRequestFailed = "リクエストに失敗しました"

    let webNotifyGo = "知らせてほしい"
    let webNotifyAsking = "確認中…"
    let webNotifyStop = "やめる"
    let webNotifyStopping = "停止中…"
    let webNotifyOff = "セッションが返事を待っているときに"
    let webNotifyOn = "この端末は登録済みです。何を知らせるかは Mac のほうで決まります。"
    let webNotifyBlocked = "このサイトの通知はブロックされています。そのスイッチはここではなく、ブラウザ自身の設定にあります。"
    let webNotifyUnsupported = "このブラウザは通知を出せません。"
    let webNotifyHomeScreen = "clawdline をホーム画面に追加して、そこから開いてください — iOS が通知を送るのは、そこに置かれたアプリだけです。"
    let webNotifyOnFailed = "通知をオンにできませんでした"
    let webNotifyOffFailed = "通知をオフにできませんでした"

    let webSettings = "設定"
    let webSettingsNotify = "通知"
    let webSettingsAssistantIcons = "アシスタントのアイコン"
    let webSettingsAssistantIconsSay = "会話で Claude または Codex の名前の前にアイコンを表示します。"
    let webSettingsAssistantIconsShow = "アイコンを表示"
    let webSettingsVersion = "バージョン {v}"
    let webClose = "閉じる"
    let webNotifySheetOff = "セッションが待っていても、この端末には知らせません。"
    let webNotifyTest = "テストを送る"
    let webNotifyTestSent = "送りました — すぐこの端末に届くはずです。"
    let webNotifyTestNone = "Mac にはこの端末の登録がありません。通知をいったんオフにしてから入れ直すと、このブラウザが新しく登録します。"
    let webNotifyTestFailed = "テスト通知を送れませんでした"
    let webSending = "送信中…"
    let webSendTip = "Return で送信 · Shift-Return で改行"
    let webStart = "セッションを始める"
    let webStartLabel = "プロジェクトでセッションを始める"
    let webStartPick = "どこで始めますか"
    let webStartWith = "どれで始めますか"
    let webStartEmpty = "始められる場所がまだありません。Mac で Claude Code を一度動かせば、ここに出てきます。"
    let webStartFilter = "プロジェクトを絞り込む"
    let webStarting = "タブを開いています…"
    let webStartWaiting = "始まりました。出てくるのを待っています…"
    let webStartSlow = "タブは開いていますが、セッションからまだ届いていません。Mac を見てみてください。"
    let webStartFailed = "これは始められませんでした。"
    let webStartGone = "そのプロジェクトはもう Mac にありません。"
    let webStartTerminalClosed = "{app} が Mac で動いていません。あちらで開いてから、もう一度どうぞ。"
    let webStartTerminalUnsupported = "設定では新しいセッションを tmux で開きますが、この Mac に tmux がありません。Mac に入れるか、設定で別のターミナルを選んでください。"
    let webStartDetached = "セッションは、誰も接続していない tmux サーバーの中で始まりました。Mac で {command} と入力すると見られます。"
    let webStartOff = "セッションを始めるのはオフです。Mac の「設定 → リモート」で入ります。"
    let webResumeWith = "前の続きから"
    let webResumePick = "どの会話を？"
    let webResumeFilter = "会話を絞り込む"
    let webResumeEmpty = "そのプロジェクトにはまだ何も記録されていません。"
    let webResumeLive = "開いています"
    let webResumeBack = "別のプロジェクト"
    let webResumeGone = "その会話はもう Mac にありません。"
    let webResumeClaudeOnly = "続きから開ける会話を残すのは Claude Code だけです。"
    let webResuming = "続きを開いています…"
    let webResumeCapped = "これより古いものはこの一覧にありません。"
    let webCommand = "話して何を始めるか伝える"
    let webCommandLabel = "話して何をするか伝え、セッションを始める"
    let webCommandSay = "下の「始める」を押すまでは、何も送信されません。"
    let webCommandHeard = "何をしますか"
    let webCommandThinking = "考えています…"
    let webCommandDraft = "下書き"
    let webCommandWhere = "プロジェクト"
    let webCommandWith = "アシスタント"
    let webCommandModel = "モデル"
    let webCommandFirst = "最初のメッセージ"
    let webCommandGo = "始める"
    let webCommandUnsure = "どのプロジェクトかはっきりしません。下から選んでください。"
    let webCommandFailed = "下書きにできませんでした。"
    let webCommandNoPlanner = "この Mac には Claude Code がなく、下書きにできません。"
    let webCommandBusy = "すでに1文が下書きになっている最中です。少し待ってからもう一度お試しください。"
    let webCommandEmpty = "何も聞こえませんでした"
    let webScheduleNew = "新しいスケジュール"
    let webScheduleEdit = "スケジュールを編集"
    let webScheduleNewSay = "下の「作成」を押すまでは、何も予定されません。"
    let webScheduleTitle = "タイトル"
    let webScheduleAt = "時刻"
    let webScheduleOn = "曜日"
    let webScheduleWhere = "プロジェクト"
    let webScheduleWith = "アシスタント"
    let webScheduleFirst = "最初のメッセージ"
    let webScheduleMore = "詳細"
    let webScheduleModel = "モデル"
    let webScheduleWhenDone = "終わったらタブを閉じる"
    let webScheduleCloseSuccess = "成功したら"
    let webScheduleCloseAlways = "常に"
    let webScheduleCloseNever = "開いたままにする"
    let webScheduleEnabled = "有効"
    let webScheduleDisabled = "無効"
    let webScheduleNotify = "失敗したら知らせる"
    let webScheduleCatchUp = "見逃したら巻き返す（時間）"
    let webScheduleTimeout = "終わらなければあきらめる（分）"
    let webScheduleCreate = "作成"
    let webScheduleCreated = "スケジュールを作成しました。"
    let webScheduleDispatchOff = "スケジュールはできていて有効ですが、派遣がオフなので誰も動かしません。Mac の「設定 → リモート」で入ります。"
    let webScheduleFailed = "スケジュールを作成できませんでした。"
    let webScheduleSave = "保存"
    let webScheduleSaved = "スケジュールを保存しました。"
    let webScheduleDelete = "削除"
    let webScheduleDeleteAsk = "{title} を削除しますか？元に戻せません。"
    let webScheduleDeleted = "スケジュールを削除しました。"
    let webScheduleNeedsTime = "時刻がはっきりしません。設定してください。"
    let webScheduleNeedsPlace = "どのプロジェクトかはっきりしません。選んでください。"
    let webScheduleDaily = "毎日"
    let webScheduleSun = "日"
    let webScheduleMon = "月"
    let webScheduleTue = "火"
    let webScheduleWed = "水"
    let webScheduleThu = "木"
    let webScheduleFri = "金"
    let webScheduleSat = "土"
    let webLinks = "リンク"
    let webLinksTip = "このプロジェクトを開ける場所"
    let webLinksPick = "このプロジェクトにアドレスがあるものは、これで全部です。"
    let webLinksEmpty = "このプロジェクトにはアドレスのあるものがありません — サイトもデプロイも、動いているサーバーもありません。"
    let webLinksFailed = "このプロジェクトのリンクを読めませんでした。"
    let webLinksLocal = "Mac 自身のネットワークの中だけです。ここからは開きません。"
    let webLinksFile = "Mac にあるファイルです。開くのはあちらで、このブラウザではありません。"
    let webLinksCopy = "パスをコピー"
    let webLinksCopied = "コピーしました。"
    let webLinksCopyFailed = "このブラウザは、このページにコピーをさせませんでした。"
    let webLinkOk = "正常"
    let webLinkFail = "エラー"
    let webLinkDown = "停止"
    let webLinkRunning = "進行中"
    let webSessionInfo = "セッション情報"
    let webInfoTitle = "このセッションについて"
    let webInfoEditTitle = "セッション名を編集"
    let webInfoCopyTitle = "この名前をコピー"
    let webInfoTitleSaved = "タイトルを保存しました。"
    let webInfoTitleLocal = "Clawdline に保存しました。下流の名前は未変更です。"
    let webInfoTitleQueued = "Clawdline に保存しました。Codex の更新は待機中です。"
    let webInfoTitleNotDurable = "タイトルは反映しましたが、この Mac に保存できませんでした。再起動すると消えます。"
    let webInfoTitleCloud = "セッションのタイトルは Mac 上でしか変更できません。クラウド接続からは変更できません。"
    let webInfoSession = "このセッション"
    let webInfoAssistant = "アシスタント"
    let webInfoModel = "モデル"
    let webInfoSessionId = "セッション ID"
    let webInfoDirectory = "ディレクトリ"
    let webInfoRunningFor = "経過時間"
    let webInfoStatus = "状態"
    let webInfoWorkStatusMeaning = "このセッションの作業状態です。チェック1つは納品済みで承認待ち、2つは確認・承認済みを表します。"
    let webInfoCloseabilityMeaning = "鍵は、このセッションを安全に閉じられるかを示します。納品状態とは別の情報です。"
    let webInfoUsage = "トークン使用量"
    let webInfoInput = "入力"
    let webInfoOutput = "出力"
    let webInfoCacheRead = "キャッシュ読み取り"
    let webInfoCacheWrite = "キャッシュ書き込み"
    let webInfoTotal = "合計"
    let webInfoCost = "推定コスト"
    let webInfoNoUsage = "このセッションの記録はまだ見つかっていません。"
    let webInfoLimits = "プランの上限"
    let webInfoLimitHit = "上限に達しました"
    let webInfoResets = "{when} にリセット"
    let webInfoUnknown = "不明"
    let webInfoFiles = "ファイル"
    let webInfoBranch = "ブランチ"
    let webInfoStaged = "ステージ済み"
    let webInfoUnstaged = "変更あり"
    let webInfoUntracked = "未追跡"
    let webInfoConflict = "競合"
    let webInfoClean = "コミットしていないものはありません。"
    let webInfoNotRepo = "git リポジトリではありません。"
    let webInfoDeploy = "最後のデプロイ"
    let webInfoNoDeploy = "このプロジェクトにはデプロイの記録がありません。"
    let webInfoFailed = "このセッションの情報を読めませんでした。"
    let webInfoBusy = "Mac がほかのセッションの読み込みで手一杯です。少ししてからどうぞ。"
    let webInfoRefresh = "更新"
    let webInfoTokens = "トークン"
    let webInfoSwitchModel = "モデルを切り替える"
    let webInfoModelOther = "ほかのモデル…"
    let webInfoModelSent = "/model {model} を送りました。確認中…"
    let webInfoModelBusy = "切り替えはセッションが待機中のときだけできます。"
    let webInfoSwitchPermission = "権限モードを切り替える"
    let webInfoPermissionAuto = "自動"
    let webInfoPermissionManual = "手動"
    let webInfoPermissionAcceptEdits = "編集を承認"
    let webInfoPermissionPlan = "プラン"
    let webInfoPermissionUnreadable = "現在のモードを読み取れません。"
    let webInfoPermissionSent = "{mode} に切り替えました。確認中…"
    let webInfoPermissionBusy = "権限モードを切り替えています。"
    let webInfoLimitsClaude = "Claude Code は枠を使い切ったときにしか記録しないので、それまでは不明です。"
    let webInfoCopied = "セッション id をコピーしました。"
    let webInfoAsOf = "{when} 時点"
    let webInfoWhyUnknown = "不明の理由と、数字を出す方法"
    let webSettingsOrder = "トランスクリプト"
    let webSettingsOrderSay = "トランスクリプトをどちらの端から読み始めるか。どのセッションにも効きますし、キーボードの `r` も同じことをします。"
    let webAskLabel = "質問しました"
    let webAskAny = "いくつ選んでも構いません"
    let webWaitingTitle = "このセッションは返事を待っています"
    let webWaitingSay = "Claude Code が Mac にメニューを出しています。Clawdline はまだここからメニューを読めないので、選択肢はあの画面にしかありません。"
    let webWaitingSend = "*ここから送っても、答えはメニューに打ち込まれません* — メニューでいま選ばれている行をそのまま確定するだけで、それはたいてい狙ったものではありません。これは Mac のほうで答えてください。"
    let webMenuSay = "答えをタップすれば、そのままセッションに届きます。"
    let webMenuHighlighted = "選択中"
    let webMenuSent = "回答を送りました。"
    let webAgents = "バックグラウンドのエージェント"
    let webAgentsCount = "{n} 件実行中"
    let webAgentDone = "完了"
    let webAgentFailed = "失敗"
    let webShells = "バックグラウンドのシェル"
    let webShellTitle = "バックグラウンドのシェル"
    let webShellOpen = "このコマンドの出力を見る"
    let webShellRunning = "実行中"
    let webShellEnded = "終了"
    let webShellQuiet = "まだ何も出力されていません。"
    let webShellFailed = "このコマンドの出力を読み取れませんでした。"
    let webShellClose = "閉じる"
    let webShellStop = "停止"
    let webShellStopTitle = "このコマンドを停止しますか？"
    let webShellStopSay = "{command} はまだ実行中です。まず停止を要求し、5 秒後にまだ動いていれば強制終了します。すでに行われたことは元に戻りません。"
    let webShellStopped = "停止を要求しました。"
    let webShellStopFailed = "停止できませんでした。"
    let agentRunning = "実行中"
    let agentTools = "ツール {n} 回"
    let agentEmpty = "このエージェントはまだ何も書き残していません。"
    let agentBack = "セッション"
    let webAgentOpen = "このエージェントの記録を見る"
    let webTaskRoot = "親"
    let webTaskChild = "子"
    let webTaskTasks = "タスク"
    let webTaskDone = "完了"
    let webTaskFailed = "失敗"
    let webTaskRunning = "実行中"
    let webStale = "Mac で Clawdline が作り直されました。このページは古いほうです。"
    let webStaleGo = "再読み込み"

    let menuApplication = "Clawdline"
    let menuWindow = "ウインドウ"
    let menuHelp = "ヘルプ"
    let menuClose = "ウインドウを閉じる"
    let menuHome = "ホーム／設定センター"
    let menuHelpDocumentation = "Clawdline ドキュメント"
    func menuAbout(_ app: String) -> String { "\(app) について" }
    let menuServices = "サービス"
    func menuHide(_ app: String) -> String { "\(app) を隠す" }
    let menuHideOthers = "ほかを隠す"
    let menuShowAll = "すべてを表示"
    let menuMinimize = "しまう"
    let homeTitle = "Clawdline ホーム"
    let homeWelcome = "接続したい用途を選んでください。設定したスイッチだけでなく、確認できた証拠を表示します。"
    let homePurpose = "何に接続しますか？"
    let homeLocalTitle = "ローカルブラウザ"
    let homeLocalSummary = "この Mac のブラウザで Clawdline を閲覧します。設定で明示的に有効にしない限り、操作はオフのままです。"
    let homeCloudPreviewTitle = "Clawdline Cloud プレビュー"
    let homeCloudPreviewSummary = "ライブ接続を確認できた後に、Clawdline のホスト型プレビューを使います。"
    let homeCloudflareTitle = "自分の Cloudflare URL"
    let homeCloudflareSummary = "公開 HTTPS 経路を確認できた後に、自分の Cloudflare ホスト名を使います。"
    let homeUnavailable = "このビルドでは未準備です。接続成功とは表示しません。"
    let setupDetected = "検出した状態"
    let setupNextAction = "次の操作"
    let setupExpected = "期待する結果"
    let setupRecovery = "復旧方法"
    let setupLocalServerOff = "ループバックサーバはオフです。"
    let setupLocalChecking = "実際の /v1/health エンドポイントを確認中…"
    let setupLocalConfigurationFailed = "ローカルブラウザ設定を保存できませんでした。変更は適用されていません。"
    let setupLocalHealthTransport = "ヘルスエンドポイントに接続できません。ポートと他のプログラムを確認してください。"
    let setupLocalHealthTimedOut = "ヘルスエンドポイントがタイムアウトしました。ポートを確認して再試行してください。"
    func setupLocalHealthHTTP(_ status: Int) -> String { "ヘルスエンドポイントは正常な応答ではなく HTTP \(status) を返しました。" }
    let setupLocalHealthUnhealthy = "エンドポイントは応答しましたが、ok: false でした。"
    let setupLocalHealthInvalid = "有効なヘルス応答ではありません。設定したポートの使用元を確認してください。"
    let setupLocalReady = "ヘルスエンドポイントは準備完了です。ブラウザ認証情報はまだありません。"
    let setupLocalWaiting = "ブラウザを開きました。この端末の認証を待っています。"
    let setupLocalConnected = "接続しました。このブラウザ端末が Clawdline に到達しました。"
    let setupLocalEnable = "ローカルブラウザをオン"
    let setupLocalRetry = "もう一度確認"
    let setupLocalOpen = "読み取り専用ブラウザを開く"
    let setupLocalOpenAgain = "ブラウザをもう一度開く"
    let setupFinish = "完了"
    let setupLocalExpected = "読み取り専用ブラウザが開いて認証されます。アクティブなセッションがなくても成功です。"
    let setupLocalRecovery = "止まった場合はこのウインドウを開いたまま再確認してください。設定でサーバとポートも確認できます。"
    let setupNoRecovery = "復旧は不要です。この経路は証明済みです。"
    let setupLocalReadOnlyAction = "この操作は読み取り専用アクセスを保存し、操作機能をオフのままにします。"
    let setupReadOnly = "読み取り専用 · 操作はオフのまま"
    let setupLocalDeviceName = "設定センターのブラウザ"
    func setupTunnelFacts(_ mode: String, _ tunnel: String, _ hostname: String, _ status: String) -> String { "モード：\(mode)\nトンネル：\(tunnel)\nQR ホスト名：\(hostname)\n状態：\(status)" }
    let setupTunnelModeOff = "オフ"
    let setupTunnelModeQuick = "クイック"
    let setupTunnelModeNamed = "名前付き"
    let setupTunnelQuickName = "Cloudflare クイックトンネル"
    let setupNone = "なし"
    let setupControlChosen = "読み取り + 操作 · 設定で明示的に有効化済み"
    let setupTunnelMissing = "cloudflared がインストールされていません。"
    let setupTunnelOff = "トンネルはオフです。スマートフォン用 QR はありません。"
    let setupTunnelStarting = "cloudflared を起動中です。QR はまだありません。"
    func setupTunnelReady(_ url: String) -> String { "\(url) で稼働中。スマートフォンの資格情報はまだありません。" }
    func setupTunnelWaiting(_ url: String) -> String { "QR は \(url) を指しています。このスマートフォンを待っています。" }
    func setupTunnelConnected(_ url: String) -> String { "\(url) 経由で接続済み。このスマートフォンが lastSeen を報告しました。" }
    let setupTunnelExpected = "稼働中のトンネル URL だけが QR に入り、その QR が作った非ローカル端末の lastSeen だけが設定を完了します。"
    let setupTunnelRecovery = "リモート設定を開きます。cloudflared がなければインストールし、それ以外は検出された理由に従い、トンネルを保って再スキャンしてください。"
    let setupOpenRemoteSettings = "リモート設定を開く"
    let setupCheckTunnel = "トンネルを再確認"
    let setupShowPhoneQR = "スマートフォン QR を表示"
    let setupShowPhoneQRAgain = "QR をもう一度表示"
    let setupCloudRelayUnauthorized = "Relay がこのマシンの資格情報を拒否しました。"
    func setupCloudFacts(_ account: String, _ credential: String, _ relay: String, _ pairing: String, _ receipt: String) -> String { "アカウント：\(account)\nマシン資格情報：\(credential)\nRelay 準備：\(relay)\nE2EE ペアリング：\(pairing)\nViewer 受信証明：\(receipt)" }
    let setupCloudExpected = "Preview は、アカウント、マシン資格情報、Relay、E2EE ペアリング、この Viewer の受信が個別に証明された場合のみ完了します。"
    let setupCloudRecovery = "Cloud 設定でサインインまたはペアリングします。Relay と Viewer 受信は Preview の証明であり、再試行で不足した証拠が生まれることはありません。"
    let setupOpenCloudSettings = "Cloud 設定を開く"
    let setupPairCloudPhone = "Cloud でスマートフォンをペアリング"
    let setupReviewCloudPreview = "Preview 状態を確認"
    let setupProofAbsent = "存在しません"
    let setupProofReading = "証明を読み取り中…"
    let setupProofUnavailable = "証明を取得できません"
    func setupProofFailed(_ reason: String) -> String { "失敗 — \(reason)" }
    let setupCloudIdentityReadFailed = "キーチェーンの識別情報を読み取れませんでした"
    let setupCloudRelayFailed = "Relay が失敗を報告しました。Cloud 設定とログを確認してください"
    let setupCloudPairingReadFailed = "ペアリング済み端末の保存領域を読み取れませんでした"
    let setupCloudPairingAmbiguous = "複数の新しい Viewer が現れました。ペアリングをやり直してください"
    func setupCloudAccountProved(_ account: String) -> String { "\(account) でサインイン済み" }
    func setupCloudCredentialProved(_ machine: String) -> String { "\(machine) のキーチェーン資格情報" }
    func setupCloudPairingProved(_ device: String) -> String { "Viewer \(device) を固定済み" }
    let setupCloudflareDeviceName = "Cloudflare 経由のスマートフォン"
    let setupScanLiveTunnel = "スマートフォンで稼働中のトンネルを読み取る"
    let setupDismissalHint = "Home を閉じると自動表示を停止します。App メニュー、Dock、ステータス項目、clawdline://home から設定センターを再表示できます。"
    let setupCompletionFailed = "完了状態を保存できませんでした。~/.config/clawdline の権限を確認して Home をもう一度閉じてください。"

    let menuOpen = "入力バーを開く"
    let menuReveal = "対象のタブへ移動"
    let menuMascot = "マスコット"
    let menuLogin = "ログイン時に起動"
    let menuEditConfig = "設定…"
    let menuReload = "設定を再読み込み"
    let menuQuit = "Clawdline を終了"
    let menuNoTarget = "（未検出）"

    func hotkeyFailedTitle(_ combo: String) -> String { "\(combo) を登録できませんでした" }
    func hotkeyFailedBody(_ configPath: String) -> String {
        """
        ほかのアプリが使っている可能性が高いです — Spotlight、入力ソースの切り替え、\
        BetterTouchTool など。

        別のキーにしてください：\(configPath) の "hotkey" を編集し、\
        メニューバーから「設定を再読み込み」を選びます。

        それまでは、メニューバーの ✳ から入力バーを開けます。
        """
    }
    let loginFailed = "ログイン時の起動を設定できませんでした"
}
