import Foundation

struct Russian: Copy {
    let placeholder = "Сообщение для Claude Code…"

    let hintSend = "отправить"
    let hintNewline = "новая строка"
    let hintSwitch = "переключить"
    let hintList = "список"
    let hintMascot = "маскот"
    let hintOutput = "вывод"
    let hintFullscreen = "во весь экран"
    let hintKeys = "клавиши"
    let hintTextSize = "размер"
    let hintOrder = "обратный порядок"
    let hintVoice = "диктовка"
    func voiceListening(onDevice: Bool) -> String {
        onDevice ? "Слушает на этом Mac — нажмите ещё раз, чтобы остановить"
                 : "Слушает — этот язык распознаёт Apple, а не этот Mac"
    }
    let voiceNoPermission = "Диктовке нужен доступ к микрофону и распознаванию речи"
    let voiceUnavailable = "Диктовка сейчас недоступна"
    func voiceTranscribing(seconds: Double) -> String {
        String(format: "Whisper перечитывает… %.1f с", seconds)
    }
    let whisperMissing = "Whisper не установлен — см. docs/whisper.md"
    let whisperNothingHeard = "Ничего не услышал"
    func dictationStatus(_ status: Whisper.Status) -> String {
        switch status {
        case .ready(let model): return "Диктовка: Apple, затем Whisper (\(model))"
        case .noBinary: return "Диктовка: только Apple — нет whisper-cli"
        case .noModel: return "Диктовка: только Apple — whisper-cli есть, модели нет"
        }
    }
    func voiceListeningWhisper() -> String {
        "Слушает — когда вы закончите, Whisper перечитает"
    }

    let scanning = "Поиск…"
    let noSession = "Сессия Claude Code не найдена"
    let nothingToSend = "Некуда отправлять — сначала запустите Claude Code в терминале"
    let sendFailed = "Не удалось отправить"
    let itermSilent = "iTerm2 не ответил"
    let scriptMissing = "Нет iterm.js — повреждённый бандл приложения?"
    let cannotList = "Не удалось прочитать сессии iTerm2"
    let noOutput = "В этой сессии пока нечего читать."
    func outputSize(_ pt: Int) -> String { "Размер текста вывода \(pt) pt — ⌘J, чтобы посмотреть" }
    func foldedTools(_ count: Int) -> String { "шагов: \(count)" }
    func outputOrder(newestFirst: Bool) -> String {
        newestFirst ? "Сначала новые" : "Сначала старые"
    }
    func backlogNow(_ count: Int) -> String { "сейчас \(count)" }
    func dropped(_ count: Int) -> String {
        count == 1 ? "Путь добавлен — Claude Code его прочитает" : "Добавлено путей: \(count)"
    }
    func stackConfirm(_ command: String) -> String { "Нажмите ещё раз, чтобы выполнить:  \(command)" }
    let hintStacks = "серверы"
    func stackTip(up: Int, total: Int) -> String { "Запущено \(up) из \(total) серверов — ⌘S для списка" }
    let stackTipUnknown = "У проекта есть серверы, но его команда состояния ещё не доверена — ⌘S"
    let stackUntrusted = "не доверено"
    let stackActionStart = "запустить"
    let stackActionRestart = "перезапуск"
    let stackActionStop = "остановить"
    let stackActionLogs = "журнал"
    let stackLogAll = "все"
    let stackLogBack = "расшифровка"
    let stackActionAllow = "разрешить"
    let stackActionAgain = "ещё раз"
    func sessionTip(index: Int, total: Int) -> String { "Сессия \(index) из \(total) — ⌘K для переключения" }
    let sessionWaiting = "ждёт вашего ответа"
    let islandDone = "готово"
    let islandAllSessions = "Все сессии…"
    func statusWaiting(_ labels: [String]) -> String {
        labels.count == 1 ? "\(labels[0]) ждёт вашего ответа"
                          : "\(labels.count) сессий ждут вашего ответа"
    }
    func statusWorking(_ count: Int) -> String { "\(count) выполняется" }

    let settingsTitle = "Настройки Clawdline"
    let settingsGeneral = "Основные"
    let settingsBar = "Строка"
    let settingsReading = "Чтение"
    let settingsVoice = "Диктовка"
    let settingsHotkey = "Сочетание клавиш"
    let settingsRecording = "Нажмите клавиши…"
    let settingsScope = "Работает в"
    let settingsScopeGlobal = "Во всех приложениях"
    let settingsScopeHint = "Пусто — значит везде, поэтому если убрать последнее, включится переключатель выше, а если выключить его обратно, список вернётся. В файле настроек это bundle id, и список, поправленный вручную, тоже работает."
    let settingsScopeAdd = "Добавить приложение…"
    let settingsScopeChoose = "Выбрать приложение…"
    let settingsScopeRunning = "Открыты прямо сейчас"
    let settingsScopeRemove = "Убрать"
    let settingsLanguage = "Язык"
    let settingsReopen = "Строка приходит и уходит вместе с терминалом"
    let settingsReopenHint = "Ушли из терминала — строка убирается, вернулись в него — строка возвращается. А Esc означает, что вы с ней закончили."
    let settingsFollow = "Терминал показывает то, на что нацелена строка"
    let settingsFollowHint = "Выбирает вкладку этой сессии. Терминал на передний план не выводится: иначе каждое нажатие Tab уводило бы клавиатуру из поля, в котором вы печатаете."
    let settingsNotch = "Жить в вырезе"
    let settingsNotchHint = "Персонаж в корпусе камеры. Выключено — значит выключено: ничего не рисуется и окно не создаётся."
    let settingsPosition = "Высота на экране"
    let settingsWidth = "Ширина"
    let settingsOpacity = "Непрозрачность карточки"
    let settingsShow = "Показывать"
    let settingsPaneHeight = "Высота панели"
    let settingsTextSize = "Размер текста"
    let settingsPaneFont = "Шрифт панели"
    let settingsBlur = "Размытие позади"
    let settingsNewestFirst = "Сначала новые"
    let settingsEngine = "Распознаватель"
    let settingsSettle = "Пауза завершает фразу"
    let settingsStop = "Тишина завершает сессию"
    let settingsAuto = "Авто"
    let settingsTranscript = "Расшифровка"
    let settingsTerminal = "Терминал"
    let settingsOff = "Выкл"
    let settingsHooks = "Хуки Claude Code"
    let settingsHooksHint = "Когда они установлены, Claude Code сам сообщает момент, когда ход начался, закончился или ждёт ответа, — вместо того чтобы Clawdline узнал об этом при следующем опросе. Читается всё по-прежнему с экрана; здесь решается только, насколько быстро."
    let settingsHooksInstall = "Установить"
    let settingsHooksRemove = "Убрать"
    let settingsHooksOff = "Не установлены — состояние читается только с экрана"
    let settingsHooksOn = "Установлены — ни одна сессия ещё не отозвалась"
    let settingsHooksLive = "Установлены, сессии отзываются"
    let settingsStateHook = "Когда сессия меняет состояние"
    let settingsStateHookHint = "Каждый раз, когда сессия берётся за работу, заканчивает или о чём-то вас спрашивает, Clawdline запускает это: вашу собственную программу, с подробностями в её окружении. Задаётся в файле настроек, а не здесь, потому что это argv, а не командная строка — путь с пробелом должен остаться одним путём."
    let settingsRemote = "Удалённый доступ"
    let settingsRemoteServe = "Разрешить браузеру или телефону видеть ваши сессии"
    let settingsRemoteHint = "Выключено — снаружи этого Mac ничто ни до чего не дотянется. Включено — список сессий отдаётся на 127.0.0.1: браузеру здесь, телефону через туннель, скрипту. Отдаются при этом имена репозиториев, ветки и названия задач, поэтому оно так и стоит выключенным, пока вы не скажете иначе."
    let settingsRemoteDevices = "Сопряжённые устройства"
    let settingsRemoteNoDevices = "Пока ни одного — за пределами этого Mac ничего прочитать нельзя"
    let settingsRemoteRevokeAll = "Отключить всё"
    let settingsRemoteOpen = "Открыть в браузере"
    let pairingIgnore = "Игнорировать"
    func pairingAsks(_ device: String) -> String { "\(device) хочет создать пару с этим Mac" }
    func pairingCode(_ code: String) -> String {
        """
        Введите этот код на нём:

        \(code)

        Он действует две минуты. Если вы только что этого не запрашивали — не обращайте \
        внимания: без этого кода тот, кто запросил, ничего не завершит.
        """
    }
    let settingsTunnel = "Дотянуться до этого Mac откуда угодно"
    let settingsTunnelQuick = "Сгенерированный адрес"
    let settingsTunnelNamed = "Мой собственный домен"
    let settingsTunnelHostname = "Имя хоста"
    let settingsTunnelHint = "Открывает исходящее соединение через cloudflared — никакого проброса портов, ничего слушающего в вашей сети. Не запустится, пока не сопряжено хотя бы одно устройство: за туннелем — имя каждого репозитория и название каждой задачи на этом Mac."
    let settingsRemoteWrite = "Разрешить сопряжённому устройству писать в сессию"
    let settingsRemoteWriteHint = "Выключено — сопряжённое устройство может только читать. Включено — оно может отправлять текст в сессию и запускать новые, а это выполняет код на этом Mac, потому что Claude Code именно этим и занимается. Решение здесь другое, чем выше, поэтому и переключатель отдельный."
    let settingsRemotePhone = "Сопрячь телефон…"
    let settingsRemotePhoneHint = "Показывает код для сканирования. У кода собственный ключ: снимок этого кода — это устройство, которое видно в списке выше и которое можно отключить, а не ключ самого этого Mac."
    let pairingScanTitle = "Наведите на это телефон"
    let pushWaiting = "ждёт ответа"
    let pushTest = "Тестовое уведомление. Всё подключено."
    let pushFinished = "долгая работа закончена"
    let pushDeployOk = "деплой прошёл успешно"
    let pushDeployFail = "деплой не удался"
    let settingsPushFinish = "Сообщать, когда долгая работа закончится"
    let settingsPushFinishHint = "Только дольше двух минут."
    let settingsPushDeploy = "Сообщать, когда закончится деплой"
    let settingsPushDeployHint = "И об успехе, и об ошибке."
    func settingsSeconds(_ value: Double) -> String { String(format: "%.1f с", value) }

    let webConnLive = "на связи"
    let webConnConnecting = "подключение"
    let webConnRetrying = "повтор через {n} с"
    let webConnOffline = "нет связи"
    let webConnLocked = "нет пары"
    let webConnTipLive = "Поток из приложения"
    let webConnTipLocked = "Этот браузер не сопряжён с этим Mac"
    let webConnTipDown = "Нет связи — нажмите, чтобы попробовать"

    let webCountWorking = "в работе: {n}"
    let webCountWaiting = "в ожидании: {n}"
    let webCountUnreadable = "нечитаемых: {n}"
    let webCountQuietOne = "{n} сессия, всё тихо"
    let webCountQuietMany = "сессий: {n}, всё тихо"
    let webCountNone = "нет сессий"

    let webFilterPlaceholder = "Фильтр по задаче, проекту или tty"
    let webFilterLabel = "Фильтр сессий"
    let webListLabel = "Сессии Claude Code"
    let webPull = "Потяните, чтобы обновить"
    let webPullRelease = "Отпустите, чтобы обновить"
    let webPullBusy = "Обновление…"
    let webEmptyFilterTitle = "Ничего не подходит под «{q}»"
    let webEmptyFilterHint = "Esc очищает фильтр"
    let webEmptyLockedTitle = "Это устройство не сопряжено"
    let webEmptyLockedHint = "Приложение ответило 401 — создайте пару в Clawdline на Mac"
    let webEmptyNoneHint = "Запустите её в терминале, и она появится здесь"
    let webEmptyWaitTitle = "Ждём приложение"
    let webEmptyWaitHint = "В потоке пока ничего не появилось"
    let webStateUnreadable = "экран не прочитать"
    let webStateWorking = "в работе"

    let webBack = "Сессии"
    let webBackLabel = "Назад к списку сессий"
    let webNoSessionOpen = "Сессия не открыта"
    let webOrderTip = "Перевернуть расшифровку (r)"
    let webShowOnMac = "Показать на Mac"
    let webShowOnMacTip = "Вывести терминал этой сессии на передний план на Mac"
    let webShowOnMacOff = "Сервер сообщает write: false — отправить пока ничего нельзя"
    let webShowOnMacAsked = "Mac попросили вывести её вперёд"
    let webPickSession = "Выберите сессию слева."
    let webReading = "Читаем…"
    let webLoading = "Загрузка…"
    let webTranscriptFailed = "Не удалось прочитать расшифровку"
    let webWhoYou = "вы"
    let webWhoTool = "инструмент"
    let webSteps = "шагов: {n}"
    let webJustNow = "только что"
    let webMinutesAgo = "{n} мин назад"

    let webSend = "Отправить"
    let webAttach = "Прикрепить картинку"
    let webRemoveShot = "Убрать {name}"
    let webWriteOpen = "Откройте сессию, чтобы в неё писать."
    let webWriteOff = "*Отправка выключена* — сервер сообщает `write: false`. Поле подключено; оно включится само, когда это изменится."
    let webShotsOnlyPictures = "С сообщением могут уйти только картинки"
    let webShotsTooMany = "Больше {n} картинок одно сообщение не унесёт"
    let webShotTooBig = "Эта картинка слишком велика для отправки, даже уменьшенная"
    let webShotsTooBig = "Эти картинки слишком велики, чтобы уйти вместе"
    let webShotUnreadable = "Эту картинку не удалось прочитать"
    let webShotNeedsSession = "Откройте сессию, чтобы отправить в неё картинку"

    let webHintMove = "листать"
    let webHintOpen = "открыть"
    let webHintFilter = "фильтр"
    let webHintPane = "панель"

    let webKeysLabel = "Сочетания клавиш"
    let webKeysTitle = "Клавиатура"
    let webKeysMove = "Двигаться по списку — `j` и `k` делают то же"
    let webKeysOpen = "Открыть выбранную сессию"
    let webKeysFilter = "Отфильтровать список"
    let webKeysEscape = "Очистить фильтр, потом шаг назад"
    let webKeysList = "Перейти к списку сессий"
    let webKeysPane = "Показать или скрыть расшифровку"
    let webKeysEnds = "Начало или конец расшифровки"
    let webKeysReverse = "Перевернуть порядок расшифровки"
    let webKeysThis = "Эта карточка"
    let webKeysFoot = "Всё, что набрано в текстовом поле, в поле и остаётся — пока вы пишете, сочетания не срабатывают."

    let webDoorLabel = "Сопрячь этот браузер"
    let webDoorAskLede = "Этот браузер сюда ещё не впустили."
    let webDoorAskFine = "Запросите пару — и шестизначный код появится *на Mac*, а не в ответе этой странице: так задумано. Довести дело до конца может только тот, кто сидит за той машиной, и в этом весь смысл, а не помеха."
    let webDoorName = "Назовите это устройство"
    let webDoorAsk = "Запросить пару"
    let webDoorToPassword = "Войти по паролю"
    let webDoorCodeLede = "Посмотрите на Mac."
    let webDoorCodeFine = "Clawdline показывает шесть цифр ещё {left}. Введите их здесь."
    let webDoorTwoMinutes = "две минуты"
    let webDoorDigit = "Цифра {n}"
    let webDoorConfirm = "Сопрячь это устройство"
    let webDoorRestart = "Начать заново"
    let webDoorPasswordLede = "Войдите по паролю."
    let webDoorPasswordFine = "Это тот пароль, что задан в Clawdline на Mac, в Настройках → Удалённый доступ. Если он не задан, внутрь ведёт только пара."
    let webDoorPassword = "Пароль"
    let webDoorPasswordGo = "Войти"
    let webDoorToPair = "Ввести код сопряжения"
    let webDoorAsking = "Спрашиваем Mac…"
    let webDoorAskFailed = "Не удалось спросить Mac."
    let webDoorRateLimited = "Каждый запрос выводит уведомление на Mac, поэтому их всего три за десять минут."
    let webDoorSixDigits = "Шесть цифр."
    let webDoorChecking = "Проверяем…"
    let webDoorFinished = "Эта пара закрыта — пять неверных кодов. Запросите заново, когда будете за Mac."
    let webDoorWrongCode = "Этот код неверный."
    let webDoorNeedPassword = "Сначала пароль."
    let webDoorWrongPassword = "Это не тот пароль."
    let webDoorExpired = "Этот код истёк. Запросите заново — на Mac появится новый."
    let webDoorPaired = "Пара создана — браузер внутри"

    let webOffline = "Не удалось достучаться до Clawdline. Он ещё запущен на Mac?"
    let webNotJSON = "Сервер прислал что-то, что не JSON"
    let webRequestFailed = "Запрос не удался"

    let webNotifyGo = "Сообщать мне"
    let webNotifyAsking = "Спрашиваем…"
    let webNotifyStop = "Отключить"
    let webNotifyStopping = "Отключаем…"
    let webNotifyOff = "когда сессия ждёт ответа"
    let webNotifyOn = "Это устройство подписано. О чём ему сообщать, задаётся на Mac."
    let webNotifyBlocked = "Уведомления для этого сайта заблокированы. Этот переключатель — в настройках самого браузера, не здесь."
    let webNotifyUnsupported = "Этот браузер не умеет показывать уведомления."
    let webNotifyHomeScreen = "Добавьте clawdline на домашний экран и открывайте оттуда — iOS шлёт уведомления только приложению, которое там живёт."
    let webNotifyOnFailed = "Не удалось включить уведомления"
    let webNotifyOffFailed = "Не удалось выключить уведомления"

    let webSettings = "Настройки"
    let webSettingsNotify = "Уведомления"
    let webSettingsVersion = "Версия {v}"
    let webClose = "Закрыть"
    let webNotifySheetOff = "Этому устройству не сообщают, когда сессия ждёт."
    let webNotifyTest = "Отправить тест"
    let webNotifyTestSent = "Отправлено — вот-вот придёт на это устройство."
    let webNotifyTestNone = "На Mac нет подписки для этого устройства. Выключите и снова включите уведомления — браузер зарегистрирует новую."
    let webNotifyTestFailed = "Не удалось отправить тестовое уведомление"
    let webSending = "Отправка…"
    let webSendTip = "Return отправляет · Shift-Return переносит строку"
    let webStart = "Начать сессию"
    let webStartLabel = "Начать сессию в проекте"
    let webStartPick = "Где её начать?"
    let webStartEmpty = "Пока негде начинать. Запустите Claude Code на Mac один раз — и проект появится здесь."
    let webStartFilter = "Фильтр проектов"
    let webStarting = "Открываем вкладку…"
    let webStartWaiting = "Запущена. Вот-вот появится…"
    let webStartSlow = "Вкладка открыта, но сессия не отозвалась. Загляните на Mac."
    let webStartFailed = "Запустить это не удалось."
    let webStartGone = "Этого проекта на Mac больше нет."
    let webStartTerminalClosed = "На Mac не запущен {app}. Откройте его там и попробуйте снова."
    let webStartTerminalUnsupported = "Отсюда нельзя начать сессию в {app}. Запустите в нём tmux — и всё заработает."
    let webStartOff = "Запуск сессий выключен. Включается на Mac, в Настройках → Удалённый доступ."
    let webAskLabel = "спросил"
    let webAskAny = "Сколько угодно из этих"
    let webWaitingTitle = "Эта сессия ждёт ответа"
    let webWaitingSay = "Claude Code показывает меню на Mac. Clawdline пока не умеет читать меню отсюда, так что варианты есть только на том экране."
    let webWaitingSend = "*Отправка отсюда не впечатает ваш ответ в меню* — она подтвердит тот пункт, который в меню сейчас подсвечен, а это редко тот, что вы имели в виду. На этот вопрос ответьте на Mac."
    let webStale = "Clawdline на Mac пересобрали. Эта страница осталась от прежней сборки."
    let webStaleGo = "Перезагрузить"

    let menuOpen = "Открыть строку ввода"
    let menuReveal = "Перейти к нужной вкладке"
    let menuMascot = "Маскот"
    let menuLogin = "Запускать при входе"
    let menuEditConfig = "Настройки…"
    let menuReload = "Перечитать настройки"
    let menuQuit = "Выйти из Clawdline"
    let menuNoTarget = "(пока не найдено)"

    func hotkeyFailedTitle(_ combo: String) -> String { "Не удалось зарегистрировать \(combo)" }
    func hotkeyFailedBody(_ configPath: String) -> String {
        """
        Скорее всего, это сочетание уже занято другим приложением — Spotlight, \
        переключатель раскладки, BetterTouchTool и тому подобное.

        Выберите другое: измените "hotkey" в \(configPath), затем выберите \
        «Перечитать настройки» в строке меню.

        До тех пор строку ввода по-прежнему открывает ✳ в строке меню.
        """
    }
    let loginFailed = "Не удалось настроить запуск при входе"
}
