package persona

// The product, quality and operations teams' bots, in the same body as the
// rest. Each team is a family: product in warm yellows, quality in teals and
// greens, operations in slate with orange. The accessories: a flag, ranked
// bars, a funnel, a trend line, sticky notes; a flask, a figure, a lightning
// bolt, a plug, a snapshot; a pulse, pipeline chevrons, a siren, a coin stack
// and a key.
var productQualityOperationsIcons = map[string]art{
	"product-manager": {accent: 'B', palette: map[byte]string{'B': "#e8b923", 'o': ink, 'p': ink, 'R': "#e5484d"},
		rows: [iconHeight]string{
			"...pRRR.",
			"...pRR..",
			".BBpBBB.",
			".BoBBoB.",
			".BBBBBB.",
			".BBBBBB.",
			"..B..B..",
		}},
	"sprint-prioritizer": {accent: 'B', palette: map[byte]string{'B': "#f0a830", 'o': ink, 'd': "#6b3f0c", 'A': "#fff1c7"},
		rows: [iconHeight]string{
			"...AA...",
			"...BB...",
			".BBBBBB.",
			".BoBBoB.",
			".BddddB.",
			".BdddBB.",
			".BddBBB.",
		}},
	"feedback-synthesizer": {accent: 'B', palette: map[byte]string{'B': "#d9a520", 'o': ink, 'W': "#f4efe3"},
		rows: [iconHeight]string{
			".WWWWWW.",
			"..WWWW..",
			".BBWWBB.",
			".BoBBoB.",
			".BBBBBB.",
			".BBBBBB.",
			"..B..B..",
		}},
	"trend-researcher": {accent: 'B', palette: map[byte]string{'B': "#f2c94c", 'o': ink, 'W': "#fff4d6", 'L': "#3b5bdb", 'A': "#fff1c7"},
		rows: [iconHeight]string{
			"...AA...",
			"...BB...",
			".BBBBBB.",
			".BoBBoB.",
			".WWWWWL.",
			".WWLWLW.",
			".WLWWWW.",
		}},
	"ux-researcher": {accent: 'B', palette: map[byte]string{'B': "#e6a23c", 'o': ink, 'P': "#ff8fb1", 'C': "#7cc4ff", 'A': "#fff1c7"},
		rows: [iconHeight]string{
			"...AA...",
			"...BB...",
			".BBBBBB.",
			".BoBBoB.",
			".BPPCCB.",
			".BPPCCB.",
			"..B..B..",
		}},
	"test-automation": {accent: 'B', palette: map[byte]string{'B': "#1f9e8f", 'o': ink, 'W': "#e8ecf2", 'G': "#7ef0a0"},
		rows: [iconHeight]string{
			"...WW...",
			"..WGGW..",
			".BBBBBB.",
			".BoBBoB.",
			".BBBBBB.",
			".BBBBBB.",
			"..B..B..",
		}},
	"accessibility": {accent: 'B', palette: map[byte]string{'B': "#2bb3a3", 'o': ink, 'W': "#ffffff", 'A': "#d8f5f0"},
		rows: [iconHeight]string{
			"...AA...",
			"...BB...",
			".BBBBBB.",
			".BoBBoB.",
			".BWWWWB.",
			".BBWWBB.",
			".BWBBWB.",
		}},
	"performance": {accent: 'B', palette: map[byte]string{'B': "#3cb371", 'o': ink, 'Y': "#ffe066"},
		rows: [iconHeight]string{
			"....YY..",
			"...YY...",
			".BBYYBB.",
			".BoBBoB.",
			".BBBBBB.",
			".BBBBBB.",
			"..B..B..",
		}},
	"api-tester": {accent: 'B', palette: map[byte]string{'B': "#16a085", 'o': ink, 's': ink, 'P': "#d8dee6"},
		rows: [iconHeight]string{
			"..s..s..",
			"..PPPP..",
			".BBBBBB.",
			".BoBBoB.",
			".BBBBBB.",
			".BBBBBB.",
			"..B..B..",
		}},
	"evidence-collector": {accent: 'B', palette: map[byte]string{'B': "#4fb58a", 'o': ink, 'W': "#f4efe3", 'p': "#5fa8e8", 'A': "#d8f5e5"},
		rows: [iconHeight]string{
			"...AA...",
			"...BB...",
			".BBBBBB.",
			".BoBBoB.",
			".BWWWWB.",
			".BWppWB.",
			".BWWWWB.",
		}},
	"sre": {accent: 'B', palette: map[byte]string{'B': "#5b6b7f", 'o': ink, 'D': "#1e2530", 'O': "#ff8c42", 'A': "#ffd0a8"},
		rows: [iconHeight]string{
			"...AA...",
			"...BB...",
			".BBBBBB.",
			".BoBBoB.",
			".DDODDD.",
			".OODDOO.",
			".DDDODD.",
		}},
	"devops": {accent: 'B', palette: map[byte]string{'B': "#475569", 'o': ink, 'O': "#ff8c42", 'A': "#ffd0a8"},
		rows: [iconHeight]string{
			"...AA...",
			"...BB...",
			".BBBBBB.",
			".BoBBoB.",
			".BOBOBB.",
			".BBOBOB.",
			".BOBOBB.",
		}},
	"incident-commander": {accent: 'B', palette: map[byte]string{'B': "#64748b", 'o': ink, 'R': "#ff5a36", 'r': "#ffb199"},
		rows: [iconHeight]string{
			".r.RR.r.",
			"..RRRR..",
			".BBBBBB.",
			".BoBBoB.",
			".BBBBBB.",
			".BBBBBB.",
			"..B..B..",
		}},
	"finops": {accent: 'B', palette: map[byte]string{'B': "#52606d", 'o': ink, 'C': "#f6a623", 'c': "#b36b00", 'A': "#ffd0a8"},
		rows: [iconHeight]string{
			"...AA...",
			"...BB...",
			".BBBBBB.",
			".BoBBoB.",
			".BBBBBCC",
			".BBBBBcc",
			"..B..BCC",
		}},
	"secrets": {accent: 'B', palette: map[byte]string{'B': "#3e4c5e", 'o': ink, 'K': "#ffb347"},
		rows: [iconHeight]string{
			".KK..K.K",
			".KKKKKKK",
			".BBBBBB.",
			".BoBBoB.",
			".BBBBBB.",
			".BBBBBB.",
			"..B..B..",
		}},
}
