// Code generated by tools/contract-gen from api/v1. DO NOT EDIT.
//
// The schemas are the contract. Edit those and rerun:
//
//	go run ./tools/contract-gen

// Package contract carries the wire types this daemon speaks.
//
// They are deliberately separate from the domain types. A transport that
// marshalled its domain directly would let an internal rename change the API
// with nothing to notice, which is the defect this package exists to remove.
package contract

// What actually happened. `typed` is the strongest thing a send can claim: the
// bytes reached the tty. Whether the assistant took the turn is a separate
// fact, read from the fleet list, and this never asserts it.
type ActionResult struct {
	Action string `json:"action"`

	// Present on a close that went ahead over open obligations.
	Forced bool   `json:"forced,omitempty"`
	ID     string `json:"id"`
	OK     bool   `json:"ok"`
}

type Assistant string

const (
	AssistantClaude Assistant = "claude"
	AssistantCodex  Assistant = "codex"
)

// AssistantValues is every value the contract allows, in contract order.
var AssistantValues = []Assistant{AssistantClaude, AssistantCodex}

type Backend string

const (
	BackendIterm Backend = "iterm"
	BackendTmux  Backend = "tmux"
	BackendOwned Backend = "owned"
)

// BackendValues is every value the contract allows, in contract order.
var BackendValues = []Backend{BackendIterm, BackendTmux, BackendOwned}

type BoardSnapshot struct {
	At            int64       `json:"at"`
	Projects      []Project   `json:"projects"`
	Revision      int64       `json:"revision"`
	SchemaVersion int64       `json:"schemaVersion"`
	Source        BoardSource `json:"source"`
}

// A board built from a partial inventory is not a board with fewer projects; it
// is a board that does not know.
type BoardSource struct {
	Complete   bool   `json:"complete"`
	ObservedAt int64  `json:"observedAt"`
	Provenance string `json:"provenance"`
}

type BoardWriteResult struct {
	OK bool `json:"ok"`

	// True when this request id had already been applied with the same body. The
	// original outcome is the answer and nothing moved.
	Replayed bool  `json:"replayed"`
	Revision int64 `json:"revision"`
}

// Who clears the thing standing in the way. `self` distinguishes the session
// that has to act from another one, which is the difference between a thing a
// reader can do now and a thing they can only wait for.
type CloseMover struct {
	Kind         string `json:"kind"`
	PersonNeeded bool   `json:"person_needed"`
	Self         bool   `json:"self"`
}

// One thing in the way. It names the machine code, the subject it is about and
// who moves it: a code alone says there is a problem but not which object has
// it, and a sentence alone cannot be grepped for in a log.
type CloseReason struct {
	Code        string     `json:"code"`
	Kind        string     `json:"kind"`
	Mover       CloseMover `json:"mover"`
	SubjectID   string     `json:"subject_id"`
	SubjectKind string     `json:"subject_kind"`
}

// A close refused by what the session still owes. It carries the same reasons
// the fleet list was already showing, so the screen and the action never
// disagree.
type CloseRefusal struct {
	Detail  string        `json:"detail"`
	Error   string        `json:"error"`
	Reasons []CloseReason `json:"reasons"`
}

type CloseRequest struct {
	// Close although something is still owed. It cannot override an unreadable
	// obligation list: overriding a refusal is a decision, and there is nothing to
	// decide about when the list could not be read.
	Force bool `json:"force,omitempty"`
}

// Where the reading came from and how old it is. `freshness` is what stops a
// stale `safe` being read as a current one — the console refuses to call
// anything safe unless this says `current`.
type CloseSource struct {
	Freshness     string `json:"freshness"`
	MaxAgeSeconds int64  `json:"max_age_seconds"`
	ObservedAt    int64  `json:"observed_at"`
	Provenance    string `json:"provenance"`
}

// Whether this session can end. A separate question from whether it can take
// work, and neither may be read off the other. `safe` is a positive claim and
// the reader enforces what it costs: no reasons, a current source, an
// attestation id and a version, and a session that is not working, waiting or
// unreadable. Anything short of that reads as `unknown`, which is why an
// unreadable obligation list can never come out as safe.
type Closeability struct {
	// Absent here. The Swift app counts activity for its own caching and this daemon
	// has no such counter; a number invented to fill the field would be a counter that
	// never moves, which is worse than a field that is not there. Nothing in the
	// console's projection reads it.
	ActivityGeneration int64 `json:"activity_generation,omitempty"`

	// The identifier of the reading that proves nothing is owed. Null until something
	// attests, and a null here is exactly why a state that would otherwise be safe
	// reads as unknown.
	AttestationID *string    `json:"attestation_id"`
	Mover         CloseMover `json:"mover"`

	// Absent here, for the same reason as `activity_generation`.
	ObligationGeneration int64         `json:"obligation_generation,omitempty"`
	ObservedAt           int64         `json:"observed_at"`
	Provenance           []string      `json:"provenance"`
	Reasons              []CloseReason `json:"reasons"`

	// Which reading of the machine this came from — the same counter the snapshot's
	// scan carries, so a closeability and the list it arrived with can be told apart
	// from a later pair.
	SessionGeneration int64             `json:"session_generation,omitempty"`
	Source            CloseSource       `json:"source"`
	State             CloseabilityState `json:"state"`

	// Which computation produced this. A reading with no version is a reading nobody
	// can say the rules for, and the console treats it as unproven.
	Version string `json:"version"`
}

// `safe` is a positive claim that nothing is owed. An unreadable obligation
// list must produce `unknown`, never `safe`.
type CloseabilityState string

const (
	CloseabilityStateSafe             CloseabilityState = "safe"
	CloseabilityStateBlocked          CloseabilityState = "blocked"
	CloseabilityStateNeedsAttestation CloseabilityState = "needs_attestation"
	CloseabilityStateUnknown          CloseabilityState = "unknown"
)

// CloseabilityStateValues is every value the contract allows, in contract order.
var CloseabilityStateValues = []CloseabilityState{CloseabilityStateSafe, CloseabilityStateBlocked, CloseabilityStateNeedsAttestation, CloseabilityStateUnknown}

type CoordinatorRecord struct {
	Assistant      Assistant `json:"assistant"`
	ConversationID string    `json:"conversationId"`

	// Increments on every rebind, so a stale caller holding an old view cannot move a
	// role that has already moved.
	Generation   int64  `json:"generation"`
	ID           string `json:"id"`
	Label        string `json:"label"`
	PID          int64  `json:"pid"`
	ReboundAt    int64  `json:"reboundAt,omitempty"`
	RegisteredAt int64  `json:"registeredAt"`
	SessionID    string `json:"sessionId"`
}

type CoordinatorRequest struct {
	Assistant        Assistant `json:"assistant,omitempty"`
	ConversationID   string    `json:"conversationId,omitempty"`
	ExpectGeneration int64     `json:"expectGeneration,omitempty"`
	ExpectID         string    `json:"expectId,omitempty"`
	Label            string    `json:"label,omitempty"`
	Operation        string    `json:"operation"`
	PID              int64     `json:"pid,omitempty"`
	SessionID        string    `json:"sessionId,omitempty"`
}

type CoordinatorResult struct {
	OK     bool              `json:"ok"`
	Record CoordinatorRecord `json:"record"`
}

type CoordinatorSnapshot struct {
	Candidates []string           `json:"candidates"`
	Liveness   Liveness           `json:"liveness"`
	Record     *CoordinatorRecord `json:"record"`
	Registered bool               `json:"registered"`
}

type DispatchRequest struct {
	Assistant Assistant `json:"assistant"`

	// The paths this task intends to write, declared before it starts. Absent is
	// refused and an empty list is accepted: `I declared none` and `I did not say` are
	// different requests, and only one of them can be arbitrated against another root.
	// This is a dispatch-time reservation compared between roots, not filesystem
	// enforcement — nothing stops a child writing outside it, and pretending
	// otherwise would be the more dangerous lie.
	Claims       []string `json:"claims,omitempty"`
	Instructions string   `json:"instructions"`
	ProjectDir   string   `json:"project_dir"`

	// Supply one to make the dispatch idempotent: the same id with the same body
	// replays rather than starting a second session.
	TaskID string `json:"task_id,omitempty"`
}

// The intent committed. It does not say the assistant received anything —
// that is a later fact with its own evidence, and `replayed` is how a caller
// tells a fresh dispatch from one it had already made.
type DispatchResult struct {
	OK       bool   `json:"ok"`
	Replayed bool   `json:"replayed"`
	TaskDir  string `json:"task_dir"`
	TaskID   string `json:"task_id"`
}

// How loud an obligation has become. Escalation changes visibility, never
// verdict: nothing here ever declares a session dead.
type Escalation string

const (
	EscalationQuiet   Escalation = "quiet"
	EscalationAging   Escalation = "aging"
	EscalationOverdue Escalation = "overdue"
)

// EscalationValues is every value the contract allows, in contract order.
var EscalationValues = []Escalation{EscalationQuiet, EscalationAging, EscalationOverdue}

// HOW a reading was obtained. Every observed field travels with one of these,
// because a structured event and a screen guess are different kinds of fact and
// a reader must be able to tell them apart.
type Evidence string

const (
	EvidenceStructured Evidence = "structured"
	EvidenceTranscript Evidence = "transcript"
	EvidenceProcess    Evidence = "process"
	EvidenceScreen     Evidence = "screen"
	EvidenceRegistry   Evidence = "registry"
	EvidenceNone       Evidence = "none"
)

// EvidenceValues is every value the contract allows, in contract order.
var EvidenceValues = []Evidence{EvidenceStructured, EvidenceTranscript, EvidenceProcess, EvidenceScreen, EvidenceRegistry, EvidenceNone}

type Health struct {
	At        int64          `json:"at"`
	Dir       string         `json:"dir"`
	OK        bool           `json:"ok"`
	Port      int64          `json:"port"`
	Scheduler SchedulerPulse `json:"scheduler"`

	// Which implementation answered. This is how a reader tells the Go daemon from the
	// Swift app on the same port.
	ServedBy string `json:"served_by"`
	Upstream int64  `json:"upstream"`
}

// A project's mark: rows of `#RRGGBB`, with null for transparent. It is derived
// from the project path and the machine's icon registry by the same rules the
// Swift app uses, so both apps draw the same creature — a mark somebody
// recognises by colour and shape is not recognisable if the second app draws it
// differently, and near-identical is worse than obviously different.
type Icon struct {
	Accent string      `json:"accent"`
	Cells  [][]*string `json:"cells"`
}

type Inventory struct {
	At       int64              `json:"at"`
	Scan     InventoryScan      `json:"scan"`
	ServedBy string             `json:"served_by"`
	Sessions []InventorySession `json:"sessions"`
}

type InventoryScan struct {
	Complete   bool     `json:"complete"`
	Notes      []string `json:"notes"`
	Provenance string   `json:"provenance"`
}

// A raw row of the terminal reading, before the fleet list drops the rows that
// are not assistants.
type InventorySession struct {
	Assistant      Assistant    `json:"assistant,omitempty"`
	Backend        Backend      `json:"backend"`
	ConversationID string       `json:"conversation_id,omitempty"`
	CWD            string       `json:"cwd,omitempty"`
	Evidence       Evidence     `json:"evidence"`
	ID             string       `json:"id"`
	Label          string       `json:"label,omitempty"`
	PID            int64        `json:"pid,omitempty"`
	State          SessionState `json:"state"`
	TTY            string       `json:"tty,omitempty"`
}

// What a current inventory says about the bound process. An incomplete reading
// answers `unknown`, never `offline`: absence of evidence is not proof of
// death.
type Liveness string

const (
	LivenessOnline  Liveness = "online"
	LivenessOffline Liveness = "offline"
	LivenessUnknown Liveness = "unknown"
)

// LivenessValues is every value the contract allows, in contract order.
var LivenessValues = []Liveness{LivenessOnline, LivenessOffline, LivenessUnknown}

type ModelUsage struct {
	CacheReadTokens  int64 `json:"cacheReadTokens"`
	CacheWriteTokens int64 `json:"cacheWriteTokens"`
	InputTokens      int64 `json:"inputTokens"`

	// Empty where the record did not name one. Codex's cumulative total does not, and
	// it is left blank rather than guessed from the session's current configuration,
	// which can have changed partway through a thread.
	Model          string `json:"model"`
	OutputTokens   int64  `json:"outputTokens"`
	ThinkingTokens int64  `json:"thinkingTokens"`
}

type Mover struct {
	ID   string    `json:"id"`
	Kind MoverKind `json:"kind"`
}

// Who can clear an obligation. Naming the mover is what turns a stuck list into
// an actionable one.
type MoverKind string

const (
	MoverKindThisSession  MoverKind = "this_session"
	MoverKindOtherSession MoverKind = "other_session"
	MoverKindPerson       MoverKind = "person"
	MoverKindTask         MoverKind = "task"
	MoverKindBroker       MoverKind = "broker"
)

// MoverKindValues is every value the contract allows, in contract order.
var MoverKindValues = []MoverKind{MoverKindThisSession, MoverKindOtherSession, MoverKindPerson, MoverKindTask, MoverKindBroker}

type Obligation struct {
	AgeSeconds int64          `json:"age_seconds"`
	Escalation Escalation     `json:"escalation"`
	Evidence   Evidence       `json:"evidence"`
	ID         string         `json:"id"`
	Kind       ObligationKind `json:"kind"`
	Mover      Mover          `json:"mover"`
	Note       string         `json:"note"`
	OpenedAt   int64          `json:"opened_at"`
	Subject    string         `json:"subject"`
}

type ObligationKind string

const (
	ObligationKindWait       ObligationKind = "wait"
	ObligationKindLanding    ObligationKind = "landing"
	ObligationKindHandoff    ObligationKind = "handoff"
	ObligationKindSuccession ObligationKind = "succession"
	ObligationKindAssignment ObligationKind = "assignment"
	ObligationKindDeadletter ObligationKind = "deadletter"
	ObligationKindReview     ObligationKind = "review"
)

// ObligationKindValues is every value the contract allows, in contract order.
var ObligationKindValues = []ObligationKind{ObligationKindWait, ObligationKindLanding, ObligationKindHandoff, ObligationKindSuccession, ObligationKindAssignment, ObligationKindDeadletter, ObligationKindReview}

type ObligationList struct {
	At          int64        `json:"at"`
	Obligations []Obligation `json:"obligations"`

	// How many rows are past their overdue threshold. A count, not a verdict.
	Stuck int64 `json:"stuck"`
}

type Project struct {
	DisplayPath string `json:"displayPath"`
	ID          string `json:"id"`
	Name        string `json:"name"`

	// A reading, not a stored count, so it cannot drift from the thing it describes.
	SessionCount int64 `json:"sessionCount"`
}

// Every refusal on this daemon has this shape. A caller reads `error` as the
// code and never parses `detail`.
type Refusal struct {
	Detail   string `json:"detail"`
	Error    string `json:"error"`
	Route    string `json:"route,omitempty"`
	Upstream string `json:"upstream,omitempty"`
}

// What the reading behind this snapshot knows about itself. Without it an empty
// list cannot be told apart from a failed scan.
type Scan struct {
	Complete  bool          `json:"complete"`
	Completed ScanCompleted `json:"completed"`

	// An empty list is only authoritative when the reading was complete. This is what
	// stops a client reading a failed scan as `every session went away`.
	EmptyAuthoritative bool `json:"emptyAuthoritative"`

	// Identifies the process. A client reconnecting to a restarted daemon uses it to
	// tell a reset generation from one that went backwards.
	Epoch      int64  `json:"epoch"`
	Generation int64  `json:"generation"`
	Provenance string `json:"provenance"`
}

type ScanCompleted struct {
	Complete bool  `json:"complete"`
	Sequence int64 `json:"sequence"`
}

type ScheduleList struct {
	Schedules []ScheduleRow `json:"schedules"`
}

// The body POST /v1/schedules accepts. `claims` absent is refused rather than
// read as none: a dispatch that declared nothing and a dispatch that declared
// an empty set are different requests.
type ScheduleRequest struct {
	Assistant Assistant `json:"assistant"`
	Brief     string    `json:"brief"`
	Claims    []string  `json:"claims,omitempty"`
	Dir       string    `json:"dir"`
	ID        string    `json:"id"`
	Name      string    `json:"name"`
	When      string    `json:"when"`
}

type ScheduleRow struct {
	Assistant Assistant `json:"assistant"`
	Dir       string    `json:"dir"`
	Enabled   bool      `json:"enabled"`
	ID        string    `json:"id"`

	// 0 means never run, rather than the Unix value of the zero time.
	LastRun  int64  `json:"lastRun"`
	LastTask string `json:"lastTask"`
	Name     string `json:"name"`

	// Present and true when this schedule's stored spelling did not parse. It is
	// switched off, and `when` carries the spelling as written rather than a parsed
	// value — otherwise an unreadable row renders as `every 0s`, which reads like a
	// setting somebody chose.
	Unreadable bool   `json:"unreadable,omitempty"`
	When       string `json:"when"`
}

type ScheduleSaved struct {
	ID   string `json:"id"`
	OK   bool   `json:"ok"`
	When string `json:"when"`
}

// What the clock says about its own last pass. A pass that fired nothing and a
// scheduler that stopped are both silence from outside, so the clock reports
// itself the way a scan does.
type SchedulerPulse struct {
	// When the last pass ran. Absent means no pass has finished yet, which is the
	// ordinary state for the first tick after startup.
	At         int64 `json:"at,omitempty"`
	Considered int64 `json:"considered"`

	// How many came due on this pass. Separate from `fired` because a due schedule
	// whose dispatch was refused is not the same as nothing being due.
	Due   int64 `json:"due"`
	Fired int64 `json:"fired"`

	// Why a pass did nothing, when the reason was not that nothing was due.
	Note        string `json:"note,omitempty"`
	TickSeconds int64  `json:"tickSeconds"`
}

type SendRequest struct {
	Text string `json:"text"`
}

// One assistant session. Fields this daemon cannot support are absent rather
// than invented; a reader that handles absence handles this too.
type SessionRow struct {
	Assistant    Assistant    `json:"assistant,omitempty"`
	Backend      Backend      `json:"backend"`
	Closeability Closeability `json:"closeability"`
	CWD          string       `json:"cwd,omitempty"`
	Evidence     Evidence     `json:"evidence"`
	Icon         *Icon        `json:"icon,omitempty"`
	ID           string       `json:"id"`
	IsClaude     bool         `json:"isClaude"`
	Label        string       `json:"label,omitempty"`

	// What a working session says it is doing, read from its screen with the
	// assistant's own clock in it. Present only while working. The Swift app sends it
	// under this name and the row's height depends on it.
	Line string `json:"line,omitempty"`

	// The assistant's own conversation id, when one was recovered from its command
	// line.
	SessionID      string         `json:"sessionId,omitempty"`
	State          SessionState   `json:"state"`
	TTY            string         `json:"tty,omitempty"`
	WorkProvenance WorkProvenance `json:"work_provenance,omitempty"`
	WorkState      WorkState      `json:"work_state"`
}

// What the session appears to be doing. `unknown` is a real answer and is never
// flattened into `idle`.
type SessionState string

const (
	SessionStateWorking SessionState = "working"
	SessionStateWaiting SessionState = "waiting"
	SessionStateIdle    SessionState = "idle"
	SessionStateUnknown SessionState = "unknown"
)

// SessionStateValues is every value the contract allows, in contract order.
var SessionStateValues = []SessionState{SessionStateWorking, SessionStateWaiting, SessionStateIdle, SessionStateUnknown}

type SessionsSnapshot struct {
	At       int64        `json:"at"`
	Scan     Scan         `json:"scan"`
	Sessions []SessionRow `json:"sessions"`
}

// Whether the task has written a result yet. `settled` false is not a failure;
// it means nothing has been written, which is the ordinary state of work still
// in progress.
type SettleResult struct {
	OK      bool      `json:"ok"`
	Settled bool      `json:"settled"`
	State   TaskState `json:"state,omitempty"`
	TaskID  string    `json:"task_id"`
}

type TaskList struct {
	Tasks []TaskRow `json:"tasks"`
}

type TaskRow struct {
	Assistant  Assistant `json:"assistant"`
	Claims     []string  `json:"claims"`
	CreatedAt  int64     `json:"created_at"`
	ProjectDir string    `json:"project_dir"`
	State      TaskState `json:"state"`
	TaskID     string    `json:"task_id"`
}

type TaskState string

const (
	TaskStateQueued      TaskState = "queued"
	TaskStateSpawning    TaskState = "spawning"
	TaskStateBriefed     TaskState = "briefed"
	TaskStateSuccess     TaskState = "success"
	TaskStateFailure     TaskState = "failure"
	TaskStateTimeout     TaskState = "timeout"
	TaskStateCancelled   TaskState = "cancelled"
	TaskStateSpawnFailed TaskState = "spawn_failed"
)

// TaskStateValues is every value the contract allows, in contract order.
var TaskStateValues = []TaskState{TaskStateQueued, TaskStateSpawning, TaskStateBriefed, TaskStateSuccess, TaskStateFailure, TaskStateTimeout, TaskStateCancelled, TaskStateSpawnFailed}

type TranscriptPage struct {
	Evidence Evidence `json:"evidence"`
	ID       string   `json:"id"`
	Note     string   `json:"note,omitempty"`

	// Which file this was read from. A reading that cannot name its source is not
	// evidence.
	Path  string `json:"path,omitempty"`
	Turns []Turn `json:"turns"`
}

// One thing that was said. Tool calls are named rather than expanded: a panel
// that reproduced every payload would be the log file again.
type Turn struct {
	At   string `json:"at"`
	Role string `json:"role"`
	Text string `json:"text"`
	Tool string `json:"tool,omitempty"`
}

type UsageReport struct {
	At       int64      `json:"at"`
	Sessions []UsageRow `json:"sessions"`

	// The sum of the rows that could be read. Rows carrying `evidence: none`
	// contribute nothing, so this can be smaller than the truth and never larger.
	TotalTokens int64 `json:"totalTokens"`
}

// One session's usage, as its own transcript records it. This is what the
// transcript accounts for, which is a smaller claim than what the session
// spent: one conversation's own turns cannot see work another model did on its
// behalf.
type UsageRow struct {
	Assistant Assistant `json:"assistant,omitempty"`
	Evidence  Evidence  `json:"evidence"`
	ID        string    `json:"id"`
	Label     string    `json:"label,omitempty"`

	// How many assistant turns were counted. Absent for a source that reports a
	// cumulative total rather than per-turn figures.
	Messages int64        `json:"messages,omitempty"`
	Models   []ModelUsage `json:"models"`

	// Why a row could not be read. Present with `evidence: none`, and never alongside
	// a number.
	Note        string `json:"note,omitempty"`
	TotalTokens int64  `json:"totalTokens"`
}

// Who decided a row's work state. `broker` means this daemon projected it from
// what it could read; `self` means the session said so. Only `broker` is
// produced here, because nothing yet takes a session's own word for what it
// needs — and emitting `self` where that is untrue would make a projection
// look like testimony.
type WorkProvenance string

const (
	WorkProvenanceBroker WorkProvenance = "broker"
	WorkProvenanceSelf   WorkProvenance = "self"
)

// WorkProvenanceValues is every value the contract allows, in contract order.
var WorkProvenanceValues = []WorkProvenance{WorkProvenanceBroker, WorkProvenanceSelf}

// One projection of what this session needs, ranked so a reader can sort by it.
// `unknown` outranks nothing and means the inputs were incomplete.
type WorkState string

const (
	WorkStateReady             WorkState = "ready"
	WorkStateWorking           WorkState = "working"
	WorkStateHolding           WorkState = "holding"
	WorkStateWaitingYou        WorkState = "waiting_you"
	WorkStateWaitingSession    WorkState = "waiting_session"
	WorkStateUnknown           WorkState = "unknown"
	WorkStateMilestoneComplete WorkState = "milestone_complete"
	WorkStateWorkComplete      WorkState = "work_complete"
)

// WorkStateValues is every value the contract allows, in contract order.
var WorkStateValues = []WorkState{WorkStateReady, WorkStateWorking, WorkStateHolding, WorkStateWaitingYou, WorkStateWaitingSession, WorkStateUnknown, WorkStateMilestoneComplete, WorkStateWorkComplete}
