package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"os"
	"sort"

	httptransport "github.com/sainteye/clawdline/internal/transport/http"
)

// routesFile is api/v1/routes.json: the daemon's route table and the level it
// answers, for a console that has to know which features a machine can reach
// before it asks (docs/updates.md). The schemas say what a route carries; this
// says which routes there are.
type routesFile struct {
	Description string     `json:"description"`
	APILevel    int        `json:"api_level"`
	Routes      []routeRow `json:"routes"`
}

// routeRow is one registered pattern and the level that first had it.
type routeRow struct {
	Method  string `json:"method"`
	Pattern string `json:"pattern"`
	Since   int    `json:"since"`
}

const routesDescription = "Generated by tools/contract-gen from httptransport.Routes() and httptransport.APILevel; do not edit. " +
	"api_level rises whenever a route is added or removed, and GET /v1/health reports the level a daemon was built at. " +
	"since is the level a route first appeared at."

// planRoutes is the routes file this table makes, given the one already
// written (nil when there is none).
//
// It refuses two things. A level lower than the one written, which would make
// an older console believe a newer daemon lacks what it has. And a route set
// that changed at the level already written: the level is how a console tells
// two daemons apart, so two different route sets under one level is exactly
// the ambiguity it exists to remove.
func planRoutes(prior *routesFile, table []httptransport.Route, level int) (routesFile, error) {
	if level < 1 {
		return routesFile{}, fmt.Errorf("httptransport.APILevel is %d; it starts at 1", level)
	}
	since := map[httptransport.Route]int{}
	if prior != nil {
		if level < prior.APILevel {
			return routesFile{}, fmt.Errorf("httptransport.APILevel is %d but api/v1/routes.json is already at %d; a level never goes down", level, prior.APILevel)
		}
		for _, r := range prior.Routes {
			since[httptransport.Route{Method: r.Method, Pattern: r.Pattern}] = r.Since
		}
	}
	out := routesFile{Description: routesDescription, APILevel: level}
	seen := map[httptransport.Route]bool{}
	var added, removed []string
	for _, r := range table {
		if seen[r] {
			return routesFile{}, fmt.Errorf("the route table registers %s %s twice", r.Method, r.Pattern)
		}
		seen[r] = true
		s, ok := since[r]
		if !ok {
			s = level
			if prior != nil {
				added = append(added, r.Method+" "+r.Pattern)
			}
		}
		out.Routes = append(out.Routes, routeRow{Method: r.Method, Pattern: r.Pattern, Since: s})
	}
	if prior != nil {
		for _, r := range prior.Routes {
			if !seen[httptransport.Route{Method: r.Method, Pattern: r.Pattern}] {
				removed = append(removed, r.Method+" "+r.Pattern)
			}
		}
	}
	if prior != nil && level == prior.APILevel && (len(added) > 0 || len(removed) > 0) {
		sort.Strings(added)
		sort.Strings(removed)
		return routesFile{}, fmt.Errorf("the route set changed (added %v, removed %v) but api_level did not rise from %d; "+
			"raise APILevel in internal/transport/http/routes.go, then run: go run ./tools/contract-gen", added, removed, level)
	}
	sort.Slice(out.Routes, func(i, j int) bool {
		if out.Routes[i].Pattern != out.Routes[j].Pattern {
			return out.Routes[i].Pattern < out.Routes[j].Pattern
		}
		return out.Routes[i].Method < out.Routes[j].Method
	})
	return out, nil
}

// readRoutes is the routes file at path, or nil when there is none yet.
func readRoutes(path string) (*routesFile, error) {
	raw, err := os.ReadFile(path)
	if os.IsNotExist(err) {
		return nil, nil
	}
	if err != nil {
		return nil, err
	}
	var f routesFile
	if err := json.Unmarshal(raw, &f); err != nil {
		return nil, fmt.Errorf("%s: %v", path, err)
	}
	return &f, nil
}

func renderRoutes(f routesFile) []byte {
	var b bytes.Buffer
	enc := json.NewEncoder(&b)
	enc.SetEscapeHTML(false)
	enc.SetIndent("", "  ")
	if err := enc.Encode(f); err != nil {
		fatal("routes: %v", err)
	}
	return b.Bytes()
}
