// Code generated by tools/contract-gen from api/v1. DO NOT EDIT.
//
// The schemas are the contract. Edit those and rerun:
//
//   go run ./tools/contract-gen
//
// This module holds types only. It imports nothing, touches no DOM and no
// React Native API, so the web console and a native app can both read it.

/**
 * What actually happened. `typed` is the strongest thing a send can claim: the
 * bytes reached the tty. Whether the assistant took the turn is a separate fact,
 * read from the fleet list, and this never asserts it.
 */
export interface ActionResult {
  action: string

  /**
   * Present on a close that went ahead over open obligations.
   */
  forced?: boolean
  id: string
  ok: boolean
}

export type Assistant =
    "claude"
  | "codex"

export const AssistantValues: readonly Assistant[] = ["claude", "codex"] as const

export type Backend =
    "iterm"
  | "tmux"
  | "owned"

export const BackendValues: readonly Backend[] = ["iterm", "tmux", "owned"] as const

export interface BoardSnapshot {
  at: number
  projects: Project[]
  revision: number
  schemaVersion: number
  source: BoardSource
}

/**
 * A board built from a partial inventory is not a board with fewer projects; it is
 * a board that does not know.
 */
export interface BoardSource {
  complete: boolean
  observedAt: number
  provenance: string
}

export interface BoardWriteResult {
  ok: boolean

  /**
   * True when this request id had already been applied with the same body. The
   * original outcome is the answer and nothing moved.
   */
  replayed: boolean
  revision: number
}

/**
 * Who clears the thing standing in the way, as the Swift app's
 * CloseabilityMover.wire spells it. `self` distinguishes the session that has to
 * act from another one, which is the difference between a thing a reader can do now
 * and a thing they can only wait for. `self` is always present here; the Swift app
 * leaves it out for a person, a task and the broker, where it would be false.
 */
export interface CloseMover {
  kind: string
  person_needed: boolean
  self: boolean

  /**
   * The other session that moves it, when `kind` is `session` and `self` is false.
   */
  session_id?: string

  /**
   * The task that moves it, when `kind` is `task`.
   */
  task_id?: string
}

/**
 * One thing in the way. It names the machine code, the subject it is about and who
 * moves it: a code alone says there is a problem but not which object has it, and a
 * sentence alone cannot be grepped for in a log. `subject_kind` and `subject_id`
 * are absent for the evidence reasons that are about the reading rather than an
 * object.
 */
export interface CloseReason {
  code: string
  kind: string
  mover: CloseMover
  subject_id?: string
  subject_kind?: string
}

/**
 * A close refused by what the session still owes. It carries the same reasons the
 * fleet list was already showing, so the screen and the action never disagree.
 */
export interface CloseRefusal {
  detail: string
  error: string
  reasons: CloseReason[]
}

export interface CloseRequest {
  /**
   * Close although something is still owed. It cannot override an unreadable
   * obligation list: overriding a refusal is a decision, and there is nothing to
   * decide about when the list could not be read.
   */
  force?: boolean
}

/**
 * Where the reading came from and how old it is. `provenance` is `session_watch`,
 * the scan of the machine's sessions this row came from. `freshness` is what stops
 * a stale `safe` being read as a current one — the console refuses to call
 * anything safe unless this says `current`.
 */
export interface CloseSource {
  freshness: string
  max_age_seconds: number
  observed_at: number
  provenance: string
}

/**
 * Whether this session can end, by the Swift app's rules
 * (Orchestrator.projectCloseability, CloseabilityIndex.swift) over the Swift app's
 * store, read-only, plus this daemon's own obligations. A separate question from
 * whether it can take work, and neither may be read off the other. `safe` is a
 * positive claim and the reader enforces what it costs: no reasons, a current
 * source, an attestation id and a version, and a session that is not working,
 * waiting or unreadable. Anything short of that reads as `unknown`. An unreadable
 * store is an `evidence` reason (`swift_store_unreadable`), so it can never come
 * out as safe or as an empty list. `attestation_id` and `mover` are always present
 * and may be null.
 */
export interface Closeability {
  /**
   * This terminal's turn clock from the Swift store (`session_activity`); 0 when it
   * has none. An attestation names it, so a turn started after attesting
   * invalidates the claim.
   */
  activity_generation: number

  /**
   * The identifier of the reading that proves nothing is owed. Null until something
   * attests, and a null here is exactly why a state that would otherwise be safe
   * reads as unknown.
   */
  attestation_id: string | null

  /**
   * The one mover every reason points at; null when they point at more than one,
   * which is itself the answer.
   */
  mover: CloseMover | null

  /**
   * The Swift store's machine-wide obligation clock.
   */
  obligation_generation: number
  observed_at: number

  /**
   * `broker`, and `self` beside it when the session's own attestation matched this
   * process.
   */
  provenance: string[]
  reasons: CloseReason[]

  /**
   * Which reading of the machine this came from — the same counter the snapshot's
   * scan carries, so a closeability and the list it arrived with can be told apart
   * from a later pair.
   */
  session_generation: number
  source: CloseSource
  state: CloseabilityState

  /**
   * `cl1_` and 32 hex digits: the Swift app's closeabilityVersion over the exact
   * process identity, the two clocks and the state. A reading with no version is a
   * reading nobody can say the rules for.
   */
  version: string
}

/**
 * `safe` is a positive claim that nothing is owed. An unreadable obligation list
 * must produce `unknown`, never `safe`.
 */
export type CloseabilityState =
    "safe"
  | "blocked"
  | "needs_attestation"
  | "unknown"

export const CloseabilityStateValues: readonly CloseabilityState[] = ["safe", "blocked", "needs_attestation", "unknown"] as const

/**
 * One file-ownership wait between sessions, from the Swift store's
 * `coordination_waits`, as Orchestrator.coordination(forTerminal:) shapes it. On
 * the waiting side it carries `reason` and `waiterCreatedAt`; on the owner's side
 * `waiterSessionId` and `reason`. The label beside a session id is present when
 * that session is on screen.
 */
export interface CoordinationWaitRow {
  createdAt: number
  id: string
  ownerLabel?: string
  ownerSessionId: string
  paths: string[]
  reason?: string
  releaseCondition: string
  repository: string
  waiterCreatedAt?: number
  waiterLabel?: string
  waiterSessionId?: string
}

export interface CoordinatorRecord {
  assistant: Assistant
  conversationId: string

  /**
   * Increments on every rebind, so a stale caller holding an old view cannot move a
   * role that has already moved.
   */
  generation: number
  id: string
  label: string
  pid: number
  reboundAt?: number
  registeredAt: number
  sessionId: string
}

export interface CoordinatorRequest {
  assistant?: Assistant
  conversationId?: string
  expectGeneration?: number
  expectId?: string
  label?: string
  operation: string
  pid?: number
  sessionId?: string
}

export interface CoordinatorResult {
  ok: boolean
  record: CoordinatorRecord
}

export interface CoordinatorSnapshot {
  candidates: string[]
  liveness: Liveness
  record: CoordinatorRecord | null
  registered: boolean
}

export interface DispatchRequest {
  assistant: Assistant

  /**
   * The paths this task intends to write, declared before it starts. Absent is
   * refused and an empty list is accepted: `I declared none` and `I did not say`
   * are different requests, and only one of them can be arbitrated against another
   * root. This is a dispatch-time reservation compared between roots, not
   * filesystem enforcement — nothing stops a child writing outside it, and
   * pretending otherwise would be the more dangerous lie.
   */
  claims?: string[]
  instructions: string
  project_dir: string

  /**
   * Supply one to make the dispatch idempotent: the same id with the same body
   * replays rather than starting a second session.
   */
  task_id?: string
}

/**
 * The intent committed. It does not say the assistant received anything — that is
 * a later fact with its own evidence, and `replayed` is how a caller tells a fresh
 * dispatch from one it had already made.
 */
export interface DispatchResult {
  ok: boolean
  replayed: boolean
  task_dir: string
  task_id: string
}

/**
 * How loud an obligation has become. Escalation changes visibility, never verdict:
 * nothing here ever declares a session dead.
 */
export type Escalation =
    "quiet"
  | "aging"
  | "overdue"

export const EscalationValues: readonly Escalation[] = ["quiet", "aging", "overdue"] as const

/**
 * HOW a reading was obtained. Every observed field travels with one of these,
 * because a structured event and a screen guess are different kinds of fact and a
 * reader must be able to tell them apart.
 */
export type Evidence =
    "structured"
  | "transcript"
  | "process"
  | "screen"
  | "registry"
  | "none"

export const EvidenceValues: readonly Evidence[] = ["structured", "transcript", "process", "screen", "registry", "none"] as const

export interface Health {
  at: number
  dir: string
  ok: boolean
  port: number
  scheduler: SchedulerPulse

  /**
   * Which implementation answered. This is how a reader tells the Go daemon from
   * the Swift app on the same port.
   */
  served_by: string
  upstream: number
}

/**
 * A project's mark: rows of `#RRGGBB`, with null for transparent. It is derived
 * from the project path and the machine's icon registry by the same rules the Swift
 * app uses, so both apps draw the same creature — a mark somebody recognises by
 * colour and shape is not recognisable if the second app draws it differently, and
 * near-identical is worse than obviously different.
 */
export interface Icon {
  accent: string
  cells: ((string | null)[])[]
}

export interface Inventory {
  at: number
  scan: InventoryScan
  served_by: string
  sessions: InventorySession[]
}

export interface InventoryScan {
  complete: boolean
  notes: string[] | null
  provenance: string
}

/**
 * A raw row of the terminal reading, before the fleet list drops the rows that are
 * not assistants.
 */
export interface InventorySession {
  assistant?: Assistant
  backend: Backend
  conversation_id?: string
  cwd?: string
  evidence: Evidence
  id: string
  label?: string
  pid?: number
  state: SessionState
  tty?: string
}

/**
 * What a current inventory says about the bound process. An incomplete reading
 * answers `unknown`, never `offline`: absence of evidence is not proof of death.
 */
export type Liveness =
    "online"
  | "offline"
  | "unknown"

export const LivenessValues: readonly Liveness[] = ["online", "offline", "unknown"] as const

export interface ModelUsage {
  cacheReadTokens: number
  cacheWriteTokens: number
  inputTokens: number

  /**
   * Empty where the record did not name one. Codex's cumulative total does not, and
   * it is left blank rather than guessed from the session's current configuration,
   * which can have changed partway through a thread.
   */
  model: string
  outputTokens: number
  thinkingTokens: number
}

export interface Mover {
  id: string
  kind: MoverKind
}

/**
 * Who can clear an obligation. Naming the mover is what turns a stuck list into an
 * actionable one.
 */
export type MoverKind =
    "this_session"
  | "other_session"
  | "person"
  | "task"
  | "broker"

export const MoverKindValues: readonly MoverKind[] = ["this_session", "other_session", "person", "task", "broker"] as const

export interface Obligation {
  age_seconds: number
  escalation: Escalation
  evidence: Evidence
  id: string
  kind: ObligationKind
  mover: Mover
  note: string
  opened_at: number
  subject: string
}

export type ObligationKind =
    "wait"
  | "landing"
  | "handoff"
  | "succession"
  | "assignment"
  | "deadletter"
  | "review"

export const ObligationKindValues: readonly ObligationKind[] = ["wait", "landing", "handoff", "succession", "assignment", "deadletter", "review"] as const

export interface ObligationList {
  at: number
  obligations: Obligation[]

  /**
   * How many rows are past their overdue threshold. A count, not a verdict.
   */
  stuck: number
}

export interface Project {
  displayPath: string
  id: string
  name: string

  /**
   * A reading, not a stored count, so it cannot drift from the thing it describes.
   */
  sessionCount: number
}

/**
 * Every refusal on this daemon has this shape. A caller reads `error` as the code
 * and never parses `detail`.
 */
export interface Refusal {
  detail: string
  error: string
  route?: string
  upstream?: string
}

/**
 * A broker-proved independent Feature Root this session owns.
 */
export interface RootAssignmentRecord {
  explanation: string
  id: string
  label: string
  ownership: string
  state: string
}

/**
 * What the reading behind this snapshot knows about itself. Without it an empty
 * list cannot be told apart from a failed scan.
 */
export interface Scan {
  complete: boolean
  completed: ScanCompleted

  /**
   * An empty list is only authoritative when the reading was complete. This is what
   * stops a client reading a failed scan as `every session went away`.
   */
  emptyAuthoritative: boolean

  /**
   * Identifies the process. A client reconnecting to a restarted daemon uses it to
   * tell a reset generation from one that went backwards.
   */
  epoch: number
  generation: number
  provenance: string
}

export interface ScanCompleted {
  complete: boolean
  sequence: number
}

export interface ScheduleList {
  schedules: ScheduleRow[]
}

/**
 * The body POST /v1/schedules accepts. `claims` absent is refused rather than read
 * as none: a dispatch that declared nothing and a dispatch that declared an empty
 * set are different requests.
 */
export interface ScheduleRequest {
  assistant: Assistant
  brief: string
  claims?: string[]
  dir: string
  id: string
  name: string
  when: string
}

export interface ScheduleRow {
  assistant: Assistant
  dir: string
  enabled: boolean
  id: string

  /**
   * 0 means never run, rather than the Unix value of the zero time.
   */
  lastRun: number
  lastTask: string
  name: string

  /**
   * Present and true when this schedule's stored spelling did not parse. It is
   * switched off, and `when` carries the spelling as written rather than a parsed
   * value — otherwise an unreadable row renders as `every 0s`, which reads like a
   * setting somebody chose.
   */
  unreadable?: boolean
  when: string
}

export interface ScheduleSaved {
  id: string
  ok: boolean
  when: string
}

/**
 * What the clock says about its own last pass. A pass that fired nothing and a
 * scheduler that stopped are both silence from outside, so the clock reports itself
 * the way a scan does.
 */
export interface SchedulerPulse {
  /**
   * When the last pass ran. Absent means no pass has finished yet, which is the
   * ordinary state for the first tick after startup.
   */
  at?: number
  considered: number

  /**
   * How many came due on this pass. Separate from `fired` because a due schedule
   * whose dispatch was refused is not the same as nothing being due.
   */
  due: number
  fired: number

  /**
   * Why a pass did nothing, when the reason was not that nothing was due.
   */
  note?: string
  tickSeconds: number
}

export interface SendRequest {
  text: string
}

/**
 * Who this session is parked on, and who is parked on it. Absent when neither.
 * `state` is `waiting_on_session` whenever `waitingOn` is not empty, otherwise
 * `has_waiters`.
 */
export interface SessionCoordination {
  state: string
  waitedOnBy: CoordinationWaitRow[]
  waitingOn: CoordinationWaitRow[]
}

/**
 * Present on exactly the row whose live process is the one
 * ~/.config/clawdline/coordinator.json registers — terminal, assistant, tty, pid,
 * start time and conversation all equal. `status` is always `online` here, because
 * the field is only attached to a matching live row.
 */
export interface SessionCoordinator {
  commands: SessionCoordinatorCommand[]
  label: string
  status: string
}

/**
 * One command in the Clawdfather panel. The list is the Swift app's fixed table
 * (Coordinator.swift `commands`), in its order. `reason` and `why` are present only
 * when `enabled` is false.
 */
export interface SessionCoordinatorCommand {
  enabled: boolean
  reason?: string
  token_effort: string
  token_effort_basis: string
  type: string
  why?: string
}

/**
 * The facts behind the status line under an open session. This daemon serves the
 * transcript-derived part the Swift app calls the summary; the working tree,
 * context use, plan windows, links, permission and fast mode are not read here and
 * their keys are absent.
 */
export interface SessionInfo {
  models: SessionModel[]
  session: SessionInfoSession
  usage?: SessionInfoUsage
}

/**
 * GET /v1/sessions/{id}/info. Kept off the session stream because answering reads
 * the session's record; the console holds an answer for a minute.
 */
export interface SessionInfoReply {
  info: SessionInfo
}

export interface SessionInfoSession {
  assistant?: Assistant
  cwd?: string
  id: string

  /**
   * The model the session is on, as its record last named it: the newest assistant
   * turn's model, or a `/model` switch made after it. Absent when the record says
   * nothing.
   */
  model?: string
  sessionId?: string

  /**
   * The same label the session list shows.
   */
  title?: string
}

/**
 * What the conversation has spent. For Claude it is the sum of every assistant turn
 * in the transcript and is absent when the transcript is larger than 8 MiB, because
 * a partial sum is not a total. For Codex it is Codex's own running total.
 */
export interface SessionInfoUsage {
  cacheRead: number
  cacheWrite: number

  /**
   * US dollars. Claude Code's own session total from its status-line cache when it
   * wrote one, otherwise these tokens at list price. Absent when neither is known,
   * which is always the case for Codex; also absent at exactly zero.
   */
  costUsd?: number
  input: number

  /**
   * The model the last counted turn named, as written.
   */
  model?: string
  output: number
  total: number
}

/**
 * One model this session's assistant can be switched to. A session's current model
 * is matched against `id` by prefix, so a dated id still finds its row; `name` is
 * what a reader is shown for it.
 */
export interface SessionModel {
  command: string
  id: string
  name: string
}

/**
 * One assistant session. Fields that cannot be supported are absent rather than
 * invented; a reader that handles absence handles this too.
 */
export interface SessionRow {
  assistant?: Assistant
  backend: Backend
  closeability: Closeability
  coordination?: SessionCoordination
  coordinator?: SessionCoordinator
  cwd?: string
  disposition?: WorkDisposition
  evidence: Evidence
  icon?: Icon
  id: string
  isClaude: boolean

  /**
   * What the session is called, by the Swift app's rungs (ITerm.swift
   * preferredDisplayLabel): a name typed in Clawdline (the Swift store's
   * config.json `session_titles`), the title of the task, handoff or Feature Root
   * Clawdline opened the tab for (orchestrator.json), the conversation's own title
   * (`/rename`, else `aiTitle`), Codex's thread name or an automatic title, Claude
   * Code's registry handle — the first that has something. Never a terminal
   * title. Absent when nothing names the session.
   */
  label?: string

  /**
   * What a working session says it is doing, read from its screen with the
   * assistant's own clock in it. Present only while working. The Swift app sends it
   * under this name and the row's height depends on it.
   */
  line?: string
  owed?: WorkOwed
  root_assignment?: RootAssignmentRecord

  /**
   * The assistant's own conversation id, when one was recovered from its command
   * line.
   */
  sessionId?: string

  /**
   * The commands this session left running in the background, newest first, at most
   * six. Absent rather than empty when there are none, as the Swift app sends it;
   * always absent for Codex, which keeps no record of them.
   */
  shells?: SessionShell[]
  state: SessionState
  tty?: string

  /**
   * Who the declaring session said will move it — a session id, or a person.
   */
  work_moved_by?: string

  /**
   * The session's own words for its state, present only when its declaration
   * decided `work_state` (then `work_provenance` is `self`).
   */
  work_note?: string

  /**
   * Whether that mover is a person. Absent unless the declaration decided the
   * state; present and false is a real answer.
   */
  work_person_needed?: boolean
  work_provenance?: WorkProvenance

  /**
   * Unix seconds: when that declaration was made.
   */
  work_since?: number
  work_state: WorkState
}

/**
 * One background command a session started and has not finished: its output file
 * has no ending written under it, and the session's transcript announced its id as
 * a background command. `at` is when it last printed something.
 */
export interface SessionShell {
  /**
   * Unix seconds.
   */
  at: number

  /**
   * The command line that started it, on one line. Absent when the two transcript
   * records it is joined from straddled a read.
   */
  command?: string

  /**
   * The last line it printed, clipped to 160 characters.
   */
  doing?: string

  /**
   * Claude Code's own id for it.
   */
  id: string

  /**
   * The description written beside the command, when there was one.
   */
  what?: string
}

/**
 * What the session appears to be doing. `unknown` is a real answer and is never
 * flattened into `idle`.
 */
export type SessionState =
    "working"
  | "waiting"
  | "idle"
  | "unknown"

export const SessionStateValues: readonly SessionState[] = ["working", "waiting", "idle", "unknown"] as const

export interface SessionsSnapshot {
  at: number
  scan: Scan
  sessions: SessionRow[]
}

/**
 * Whether the task has written a result yet. `settled` false is not a failure; it
 * means nothing has been written, which is the ordinary state of work still in
 * progress.
 */
export interface SettleResult {
  ok: boolean
  settled: boolean
  state?: TaskState
  task_id: string
}

/**
 * Whether the Swift app's store was read for this answer: `current`; `stale`, an
 * earlier reading carried because the newest one was half-written; or `unknown`,
 * nothing could be read. Unknown is never the same as empty.
 */
export type StoreReading =
    "current"
  | "stale"
  | "unknown"

export const StoreReadingValues: readonly StoreReading[] = ["current", "stale", "unknown"] as const

/**
 * The tab the task was opened in.
 */
export interface TaskChild {
  backend?: string
  sessionId?: string
  terminalId?: string
}

/**
 * `at` is when the answer was built. With `store` at `unknown` the list holds only
 * this daemon's own tasks, which is not the same as the machine having no others.
 */
export interface TaskList {
  at: number
  page: TaskPage
  store: StoreReading
  tasks: TaskRow[]
}

/**
 * Which finished tasks this answer carries. Unfinished ones ride on every page.
 */
export interface TaskPage {
  cursor: number
  fields: string
  finished: number
  limit: number

  /**
   * Where the next page starts. The Swift app sends null on the last page; here the
   * key is absent.
   */
  nextCursor?: number
  unfinished: number
}

/**
 * The session that asked for the task. `terminalId` is not stored: it is resolved
 * on every read against the sessions on screen — the parent task's child terminal
 * first, otherwise the one live session whose conversation is `sessionId` — and
 * is absent when that is not exactly one.
 */
export interface TaskRoot {
  assistant?: string
  label?: string
  sessionId?: string
  taskId?: string
  terminalId?: string
}

/**
 * One task. The camelCase keys are the Swift app's list projection, which the
 * copied console reads (`view/derive.js`: id, title, state, created, finishedAt,
 * child, root, usage). The four snake_case keys `task_id`, `project_dir`,
 * `created_at` and `claims` are this daemon's older names, kept beside them because
 * the Dashboard panel still reads them. The Swift app's `projectDir` is sent only
 * as `project_dir`: the generator gives both spellings one Go name, and the copied
 * console reads neither. `claims` is therefore always present here, where the Swift
 * app leaves it out when none were declared (`claims_declared` says which). Omitted
 * from the Swift projection because no page here reads them: worktree (its presence
 * is `isolation`), executor, completion_delivery, verification, landing,
 * landing_paths, terminal_intervention, released_claims, respawn_of, waiting_on.
 */
export interface TaskRow {
  artifacts?: string[]
  assistant: Assistant
  attachSession?: string
  attached?: boolean
  briefedAt?: number
  child?: TaskChild
  claims: string[]
  claims_declared: boolean

  /**
   * Unix seconds.
   */
  created: number

  /**
   * Unix seconds; the same instant as `created`.
   */
  created_at: number
  depth: number
  dir: string
  finishedAt?: number
  id: string
  isolation?: string
  kind: string
  model?: string
  permission: string
  project_dir: string
  reasoning_effort?: string
  resultVerifiedAt?: number
  root?: TaskRoot
  schedule_id?: string
  session_root?: boolean
  spawnedAt?: number
  state: TaskState
  task_id: string
  title: string
  untouched_claims?: string[]
  usage?: TaskUsage
  workItemId?: string
  workPhase?: string
}

export type TaskState =
    "queued"
  | "spawning"
  | "briefed"
  | "success"
  | "failure"
  | "timeout"
  | "cancelled"
  | "spawn_failed"

export const TaskStateValues: readonly TaskState[] = ["queued", "spawning", "briefed", "success", "failure", "timeout", "cancelled", "spawn_failed"] as const

/**
 * What the child spent. `costUsd` is absent where nothing priced it, which is
 * always the case for Codex.
 */
export interface TaskUsage {
  cacheRead: number
  cacheWrite: number
  costUsd?: number
  input: number
  model?: string
  output: number
  total: number
}

export interface TranscriptAction {
  command?: string

  /**
   * read or search.
   */
  kind: string
  name?: string
  path?: string
  query?: string
}

/**
 * What a Codex tool item recorded about itself: `called` for an MCP call with a
 * title, `explored` for a shell command Codex classified as reads and searches.
 */
export interface TranscriptActivity {
  actions: TranscriptAction[]

  /**
   * How long the item took. -1 when the record did not say, which the Swift app
   * sends as an absent key; 0 is a real, sub-millisecond duration and is drawn as
   * one.
   */
  durationMs: number
  kind: string

  /**
   * A called tool's result text, cut at 4,000 characters.
   */
  result?: string

  /**
   * inProgress, pending, completed or failed.
   */
  status?: string
  title?: string
}

/**
 * One thing in a conversation, in the shape the Swift app's `transcriptRows` writes
 * it. A tool call and what the tool returned both carry `role: tool`; only the call
 * names its tool. A call's `text` is the one line describing what it was asked to
 * do — a command, a path, a query — which is what a folded row shows as its
 * subject. An `AskUserQuestion` call carries its questions instead, after the
 * U+0001 `ask` U+0001 marker.
 */
export interface TranscriptEntry {
  activity?: TranscriptActivity

  /**
   * Unix seconds. Absent when the record carried no timestamp this reader accepts.
   */
  at?: number

  /**
   * Exact edits: a Codex patch, or the whole file a Claude `Write` created. Absent
   * on every other entry.
   */
  fileChanges?: TranscriptFileChange[]

  /**
   * Images attached to a user turn. Absent when there were none: the Swift app
   * writes an explicit 0 on user rows, and a reader treats absence as that 0.
   */
  imageCount?: number
  notice?: TranscriptNotice

  /**
   * A complete Codex checklist update.
   */
  plan?: TranscriptPlanStep[]

  /**
   * user, assistant, peer (another Claude Code session), message (another session
   * through Clawdline), notice (Clawdline about a task) or tool.
   */
  role: string

  /**
   * The human-facing name of the session a peer or message row came from.
   */
  source?: string

  /**
   * Which assistant sent a Clawdline session message.
   */
  sourceAssistant?: string

  /**
   * How a peer or message row arrived: the peer's own mode, or `clawdline`.
   */
  sourceMode?: string
  text: string

  /**
   * The tool a call used. Absent on a tool's result and on prose.
   */
  tool?: string
}

export interface TranscriptFileChange {
  /**
   * The whole file, for an addition, a deletion or a Claude `Write`.
   */
  content?: string

  /**
   * add, delete, update or write, as the record spelled it; `change` when it did
   * not.
   */
  kind: string
  movePath?: string
  path: string
  unifiedDiff?: string
}

/**
 * A decoded Clawdline notice without its protocol, version and body — the Swift
 * app's `webObject`. Which fields are present depends on `kind`: task_finished,
 * workspace_overlap, file_wait_request, file_wait_release or handoff_receipt.
 */
export interface TranscriptNotice {
  ack_path?: string
  assistant?: string
  audience?: string

  /**
   * Present only when true.
   */
  child_may_still_write?: boolean

  /**
   * Present only when true.
   */
  claims_released?: boolean
  commit?: string
  handoff_id?: string
  kind: string
  note?: string
  notice_id?: string

  /**
   * task_finished only, where the decoder requires it, so absence there means 0.
   */
  outstanding?: number
  overlaps?: TranscriptNoticeOverlap[]
  paths?: string[]
  project_dir?: string
  reason?: string
  release_condition?: string
  repository?: string
  result_path?: string
  state?: string
  task?: TranscriptNoticeTask
  title?: string
  wait_id?: string
  waiter_session_id?: string
}

export interface TranscriptNoticeOverlap {
  path: string
  task: TranscriptNoticeTask
}

export interface TranscriptNoticeTask {
  id: string
  title: string
}

/**
 * `entries`, `signature` and `truncation` are the Swift app's transcript payload;
 * `evidence`, `path` and `note` say where the reading came from.
 */
export interface TranscriptPage {
  /**
   * Oldest first.
   */
  entries: TranscriptEntry[]
  evidence: Evidence
  id: string
  note?: string

  /**
   * Which file this was read from. A reading that cannot name its source is not
   * evidence.
   */
  path?: string

  /**
   * The record's size and modification time, `<bytes>-<unix seconds>`, and empty
   * when nothing was read. It changes whenever the entries could have.
   */
  signature: string
  truncation?: TranscriptTruncation
}

export interface TranscriptPlanStep {
  /**
   * pending, inProgress or completed — Codex app-server's spelling, not the
   * rollout's in_progress.
   */
  status: string
  step: string
}

/**
 * The newest entries were kept and older ones left out, because the whole page
 * would have passed its byte budget.
 */
export interface TranscriptTruncation {
  budgetBytes: number
  entriesOmittedCount: number

  /**
   * transcript_byte_budget.
   */
  reason: string
}

export interface UsageReport {
  at: number
  sessions: UsageRow[]

  /**
   * The sum of the rows that could be read. Rows carrying `evidence: none`
   * contribute nothing, so this can be smaller than the truth and never larger.
   */
  totalTokens: number
}

/**
 * One session's usage, as its own transcript records it. This is what the
 * transcript accounts for, which is a smaller claim than what the session spent:
 * one conversation's own turns cannot see work another model did on its behalf.
 */
export interface UsageRow {
  assistant?: Assistant
  evidence: Evidence
  id: string
  label?: string

  /**
   * How many assistant turns were counted. Absent for a source that reports a
   * cumulative total rather than per-turn figures.
   */
  messages?: number
  models: ModelUsage[]

  /**
   * Why a row could not be read. Present with `evidence: none`, and never alongside
   * a number.
   */
  note?: string
  totalTokens: number
}

/**
 * What a finished row delivered, present only with `milestone_complete` or
 * `work_complete`. `scope` is `session` for a session's own delivery receipt and
 * `task` for the task that opened it; the landing fields are present only when a
 * broker-verified landing backs `work_complete`.
 */
export interface WorkDisposition {
  commit?: string
  evidence: string
  landedAt?: number
  receiptAt?: number
  scope: string
  target?: string
  targetCommit?: string
  taskId?: string
  title: string
}

/**
 * Something this session declared it is owed, beside whatever its work state is.
 */
export interface WorkOwed {
  moved_by?: string
  note: string
  person_needed: boolean
  provenance: string
  since: number
}

/**
 * Who decided a row's work state. `broker` means it was projected from what could
 * be read; `self` means the session's own declaration (the Swift store's
 * `session_self_states`) is what decided it.
 */
export type WorkProvenance =
    "broker"
  | "self"

export const WorkProvenanceValues: readonly WorkProvenance[] = ["broker", "self"] as const

/**
 * One projection of what this session needs, ranked so a reader can sort by it.
 * `unknown` outranks nothing and means the inputs were incomplete.
 */
export type WorkState =
    "ready"
  | "working"
  | "holding"
  | "waiting_you"
  | "waiting_session"
  | "unknown"
  | "milestone_complete"
  | "work_complete"

export const WorkStateValues: readonly WorkState[] = ["ready", "working", "holding", "waiting_you", "waiting_session", "unknown", "milestone_complete", "work_complete"] as const
