// Code generated by tools/contract-gen from api/v1. DO NOT EDIT.
//
// The schemas are the contract. Edit those and rerun:
//
//   go run ./tools/contract-gen
//
// This module holds types only. It imports nothing, touches no DOM and no
// React Native API, so the web console and a native app can both read it.

/**
 * What actually happened. `typed` is the strongest thing a send can claim: the
 * bytes reached the tty. Whether the assistant took the turn is a separate fact,
 * read from the fleet list, and this never asserts it.
 */
export interface ActionResult {
  action: string

  /**
   * Present on a close that went ahead over open obligations.
   */
  forced?: boolean
  id: string
  ok: boolean
}

export type Assistant =
    "claude"
  | "codex"

export const AssistantValues: readonly Assistant[] = ["claude", "codex"] as const

export type Backend =
    "iterm"
  | "tmux"
  | "owned"

export const BackendValues: readonly Backend[] = ["iterm", "tmux", "owned"] as const

export interface BoardSnapshot {
  at: number
  projects: Project[]
  revision: number
  schemaVersion: number
  source: BoardSource
}

/**
 * A board built from a partial inventory is not a board with fewer projects; it is
 * a board that does not know.
 */
export interface BoardSource {
  complete: boolean
  observedAt: number
  provenance: string
}

export interface BoardWriteResult {
  ok: boolean

  /**
   * True when this request id had already been applied with the same body. The
   * original outcome is the answer and nothing moved.
   */
  replayed: boolean
  revision: number
}

/**
 * Who clears the thing standing in the way. `self` distinguishes the session that
 * has to act from another one, which is the difference between a thing a reader can
 * do now and a thing they can only wait for.
 */
export interface CloseMover {
  kind: string
  person_needed: boolean
  self: boolean
}

/**
 * One thing in the way. It names the machine code, the subject it is about and who
 * moves it: a code alone says there is a problem but not which object has it, and a
 * sentence alone cannot be grepped for in a log.
 */
export interface CloseReason {
  code: string
  kind: string
  mover: CloseMover
  subject_id: string
  subject_kind: string
}

/**
 * A close refused by what the session still owes. It carries the same reasons the
 * fleet list was already showing, so the screen and the action never disagree.
 */
export interface CloseRefusal {
  detail: string
  error: string
  reasons: CloseReason[]
}

export interface CloseRequest {
  /**
   * Close although something is still owed. It cannot override an unreadable
   * obligation list: overriding a refusal is a decision, and there is nothing to
   * decide about when the list could not be read.
   */
  force?: boolean
}

/**
 * Where the reading came from and how old it is. `freshness` is what stops a stale
 * `safe` being read as a current one — the console refuses to call anything safe
 * unless this says `current`.
 */
export interface CloseSource {
  freshness: string
  max_age_seconds: number
  observed_at: number
  provenance: string
}

/**
 * Whether this session can end. A separate question from whether it can take work,
 * and neither may be read off the other. `safe` is a positive claim and the reader
 * enforces what it costs: no reasons, a current source, an attestation id and a
 * version, and a session that is not working, waiting or unreadable. Anything short
 * of that reads as `unknown`, which is why an unreadable obligation list can never
 * come out as safe.
 */
export interface Closeability {
  /**
   * Absent here. The Swift app counts activity for its own caching and this daemon
   * has no such counter; a number invented to fill the field would be a counter
   * that never moves, which is worse than a field that is not there. Nothing in the
   * console's projection reads it.
   */
  activity_generation?: number

  /**
   * The identifier of the reading that proves nothing is owed. Null until something
   * attests, and a null here is exactly why a state that would otherwise be safe
   * reads as unknown.
   */
  attestation_id: string | null
  mover: CloseMover

  /**
   * Absent here, for the same reason as `activity_generation`.
   */
  obligation_generation?: number
  observed_at: number
  provenance: string[]
  reasons: CloseReason[]

  /**
   * Which reading of the machine this came from — the same counter the snapshot's
   * scan carries, so a closeability and the list it arrived with can be told apart
   * from a later pair.
   */
  session_generation?: number
  source: CloseSource
  state: CloseabilityState

  /**
   * Which computation produced this. A reading with no version is a reading nobody
   * can say the rules for, and the console treats it as unproven.
   */
  version: string
}

/**
 * `safe` is a positive claim that nothing is owed. An unreadable obligation list
 * must produce `unknown`, never `safe`.
 */
export type CloseabilityState =
    "safe"
  | "blocked"
  | "needs_attestation"
  | "unknown"

export const CloseabilityStateValues: readonly CloseabilityState[] = ["safe", "blocked", "needs_attestation", "unknown"] as const

export interface CoordinatorRecord {
  assistant: Assistant
  conversationId: string

  /**
   * Increments on every rebind, so a stale caller holding an old view cannot move a
   * role that has already moved.
   */
  generation: number
  id: string
  label: string
  pid: number
  reboundAt?: number
  registeredAt: number
  sessionId: string
}

export interface CoordinatorRequest {
  assistant?: Assistant
  conversationId?: string
  expectGeneration?: number
  expectId?: string
  label?: string
  operation: string
  pid?: number
  sessionId?: string
}

export interface CoordinatorResult {
  ok: boolean
  record: CoordinatorRecord
}

export interface CoordinatorSnapshot {
  candidates: string[]
  liveness: Liveness
  record: CoordinatorRecord | null
  registered: boolean
}

export interface DispatchRequest {
  assistant: Assistant

  /**
   * The paths this task intends to write, declared before it starts. Absent is
   * refused and an empty list is accepted: `I declared none` and `I did not say`
   * are different requests, and only one of them can be arbitrated against another
   * root. This is a dispatch-time reservation compared between roots, not
   * filesystem enforcement — nothing stops a child writing outside it, and
   * pretending otherwise would be the more dangerous lie.
   */
  claims?: string[]
  instructions: string
  project_dir: string

  /**
   * Supply one to make the dispatch idempotent: the same id with the same body
   * replays rather than starting a second session.
   */
  task_id?: string
}

/**
 * The intent committed. It does not say the assistant received anything — that is
 * a later fact with its own evidence, and `replayed` is how a caller tells a fresh
 * dispatch from one it had already made.
 */
export interface DispatchResult {
  ok: boolean
  replayed: boolean
  task_dir: string
  task_id: string
}

/**
 * How loud an obligation has become. Escalation changes visibility, never verdict:
 * nothing here ever declares a session dead.
 */
export type Escalation =
    "quiet"
  | "aging"
  | "overdue"

export const EscalationValues: readonly Escalation[] = ["quiet", "aging", "overdue"] as const

/**
 * HOW a reading was obtained. Every observed field travels with one of these,
 * because a structured event and a screen guess are different kinds of fact and a
 * reader must be able to tell them apart.
 */
export type Evidence =
    "structured"
  | "transcript"
  | "process"
  | "screen"
  | "registry"
  | "none"

export const EvidenceValues: readonly Evidence[] = ["structured", "transcript", "process", "screen", "registry", "none"] as const

export interface Health {
  at: number
  dir: string
  ok: boolean
  port: number
  scheduler: SchedulerPulse

  /**
   * Which implementation answered. This is how a reader tells the Go daemon from
   * the Swift app on the same port.
   */
  served_by: string
  upstream: number
}

/**
 * A project's mark: rows of `#RRGGBB`, with null for transparent. It is derived
 * from the project path and the machine's icon registry by the same rules the Swift
 * app uses, so both apps draw the same creature — a mark somebody recognises by
 * colour and shape is not recognisable if the second app draws it differently, and
 * near-identical is worse than obviously different.
 */
export interface Icon {
  accent: string
  cells: ((string | null)[])[]
}

export interface Inventory {
  at: number
  scan: InventoryScan
  served_by: string
  sessions: InventorySession[]
}

export interface InventoryScan {
  complete: boolean
  notes: string[] | null
  provenance: string
}

/**
 * A raw row of the terminal reading, before the fleet list drops the rows that are
 * not assistants.
 */
export interface InventorySession {
  assistant?: Assistant
  backend: Backend
  conversation_id?: string
  cwd?: string
  evidence: Evidence
  id: string
  label?: string
  pid?: number
  state: SessionState
  tty?: string
}

/**
 * What a current inventory says about the bound process. An incomplete reading
 * answers `unknown`, never `offline`: absence of evidence is not proof of death.
 */
export type Liveness =
    "online"
  | "offline"
  | "unknown"

export const LivenessValues: readonly Liveness[] = ["online", "offline", "unknown"] as const

export interface ModelUsage {
  cacheReadTokens: number
  cacheWriteTokens: number
  inputTokens: number

  /**
   * Empty where the record did not name one. Codex's cumulative total does not, and
   * it is left blank rather than guessed from the session's current configuration,
   * which can have changed partway through a thread.
   */
  model: string
  outputTokens: number
  thinkingTokens: number
}

export interface Mover {
  id: string
  kind: MoverKind
}

/**
 * Who can clear an obligation. Naming the mover is what turns a stuck list into an
 * actionable one.
 */
export type MoverKind =
    "this_session"
  | "other_session"
  | "person"
  | "task"
  | "broker"

export const MoverKindValues: readonly MoverKind[] = ["this_session", "other_session", "person", "task", "broker"] as const

export interface Obligation {
  age_seconds: number
  escalation: Escalation
  evidence: Evidence
  id: string
  kind: ObligationKind
  mover: Mover
  note: string
  opened_at: number
  subject: string
}

export type ObligationKind =
    "wait"
  | "landing"
  | "handoff"
  | "succession"
  | "assignment"
  | "deadletter"
  | "review"

export const ObligationKindValues: readonly ObligationKind[] = ["wait", "landing", "handoff", "succession", "assignment", "deadletter", "review"] as const

export interface ObligationList {
  at: number
  obligations: Obligation[]

  /**
   * How many rows are past their overdue threshold. A count, not a verdict.
   */
  stuck: number
}

export interface Project {
  displayPath: string
  id: string
  name: string

  /**
   * A reading, not a stored count, so it cannot drift from the thing it describes.
   */
  sessionCount: number
}

/**
 * Every refusal on this daemon has this shape. A caller reads `error` as the code
 * and never parses `detail`.
 */
export interface Refusal {
  detail: string
  error: string
  route?: string
  upstream?: string
}

/**
 * What the reading behind this snapshot knows about itself. Without it an empty
 * list cannot be told apart from a failed scan.
 */
export interface Scan {
  complete: boolean
  completed: ScanCompleted

  /**
   * An empty list is only authoritative when the reading was complete. This is what
   * stops a client reading a failed scan as `every session went away`.
   */
  emptyAuthoritative: boolean

  /**
   * Identifies the process. A client reconnecting to a restarted daemon uses it to
   * tell a reset generation from one that went backwards.
   */
  epoch: number
  generation: number
  provenance: string
}

export interface ScanCompleted {
  complete: boolean
  sequence: number
}

export interface ScheduleList {
  schedules: ScheduleRow[]
}

/**
 * The body POST /v1/schedules accepts. `claims` absent is refused rather than read
 * as none: a dispatch that declared nothing and a dispatch that declared an empty
 * set are different requests.
 */
export interface ScheduleRequest {
  assistant: Assistant
  brief: string
  claims?: string[]
  dir: string
  id: string
  name: string
  when: string
}

export interface ScheduleRow {
  assistant: Assistant
  dir: string
  enabled: boolean
  id: string

  /**
   * 0 means never run, rather than the Unix value of the zero time.
   */
  lastRun: number
  lastTask: string
  name: string

  /**
   * Present and true when this schedule's stored spelling did not parse. It is
   * switched off, and `when` carries the spelling as written rather than a parsed
   * value — otherwise an unreadable row renders as `every 0s`, which reads like a
   * setting somebody chose.
   */
  unreadable?: boolean
  when: string
}

export interface ScheduleSaved {
  id: string
  ok: boolean
  when: string
}

/**
 * What the clock says about its own last pass. A pass that fired nothing and a
 * scheduler that stopped are both silence from outside, so the clock reports itself
 * the way a scan does.
 */
export interface SchedulerPulse {
  /**
   * When the last pass ran. Absent means no pass has finished yet, which is the
   * ordinary state for the first tick after startup.
   */
  at?: number
  considered: number

  /**
   * How many came due on this pass. Separate from `fired` because a due schedule
   * whose dispatch was refused is not the same as nothing being due.
   */
  due: number
  fired: number

  /**
   * Why a pass did nothing, when the reason was not that nothing was due.
   */
  note?: string
  tickSeconds: number
}

export interface SendRequest {
  text: string
}

/**
 * One assistant session. Fields this daemon cannot support are absent rather than
 * invented; a reader that handles absence handles this too.
 */
export interface SessionRow {
  assistant?: Assistant
  backend: Backend
  closeability: Closeability
  cwd?: string
  evidence: Evidence
  icon?: Icon
  id: string
  isClaude: boolean
  label?: string

  /**
   * The assistant's own conversation id, when one was recovered from its command
   * line.
   */
  sessionId?: string
  state: SessionState
  tty?: string
  work_provenance?: WorkProvenance
  work_state: WorkState
}

/**
 * What the session appears to be doing. `unknown` is a real answer and is never
 * flattened into `idle`.
 */
export type SessionState =
    "working"
  | "waiting"
  | "idle"
  | "unknown"

export const SessionStateValues: readonly SessionState[] = ["working", "waiting", "idle", "unknown"] as const

export interface SessionsSnapshot {
  at: number
  scan: Scan
  sessions: SessionRow[]
}

/**
 * Whether the task has written a result yet. `settled` false is not a failure; it
 * means nothing has been written, which is the ordinary state of work still in
 * progress.
 */
export interface SettleResult {
  ok: boolean
  settled: boolean
  state?: TaskState
  task_id: string
}

export interface TaskList {
  tasks: TaskRow[]
}

export interface TaskRow {
  assistant: Assistant
  claims: string[]
  created_at: number
  project_dir: string
  state: TaskState
  task_id: string
}

export type TaskState =
    "queued"
  | "spawning"
  | "briefed"
  | "success"
  | "failure"
  | "timeout"
  | "cancelled"
  | "spawn_failed"

export const TaskStateValues: readonly TaskState[] = ["queued", "spawning", "briefed", "success", "failure", "timeout", "cancelled", "spawn_failed"] as const

export interface TranscriptPage {
  evidence: Evidence
  id: string
  note?: string

  /**
   * Which file this was read from. A reading that cannot name its source is not
   * evidence.
   */
  path?: string
  turns: Turn[]
}

/**
 * One thing that was said. Tool calls are named rather than expanded: a panel that
 * reproduced every payload would be the log file again.
 */
export interface Turn {
  at: string
  role: string
  text: string
  tool?: string
}

export interface UsageReport {
  at: number
  sessions: UsageRow[]

  /**
   * The sum of the rows that could be read. Rows carrying `evidence: none`
   * contribute nothing, so this can be smaller than the truth and never larger.
   */
  totalTokens: number
}

/**
 * One session's usage, as its own transcript records it. This is what the
 * transcript accounts for, which is a smaller claim than what the session spent:
 * one conversation's own turns cannot see work another model did on its behalf.
 */
export interface UsageRow {
  assistant?: Assistant
  evidence: Evidence
  id: string
  label?: string

  /**
   * How many assistant turns were counted. Absent for a source that reports a
   * cumulative total rather than per-turn figures.
   */
  messages?: number
  models: ModelUsage[]

  /**
   * Why a row could not be read. Present with `evidence: none`, and never alongside
   * a number.
   */
  note?: string
  totalTokens: number
}

/**
 * Who decided a row's work state. `broker` means this daemon projected it from what
 * it could read; `self` means the session said so. Only `broker` is produced here,
 * because nothing yet takes a session's own word for what it needs — and emitting
 * `self` where that is untrue would make a projection look like testimony.
 */
export type WorkProvenance =
    "broker"
  | "self"

export const WorkProvenanceValues: readonly WorkProvenance[] = ["broker", "self"] as const

/**
 * One projection of what this session needs, ranked so a reader can sort by it.
 * `unknown` outranks nothing and means the inputs were incomplete.
 */
export type WorkState =
    "ready"
  | "working"
  | "holding"
  | "waiting_you"
  | "waiting_session"
  | "unknown"
  | "milestone_complete"
  | "work_complete"

export const WorkStateValues: readonly WorkState[] = ["ready", "working", "holding", "waiting_you", "waiting_session", "unknown", "milestone_complete", "work_complete"] as const
