// Code generated by tools/contract-gen from api/v1. DO NOT EDIT.
//
// The schemas are the contract. Edit those and rerun:
//
//   go run ./tools/contract-gen
//
// This module holds types only. It imports nothing, touches no DOM and no
// React Native API, so the web console and a native app can both read it.

/**
 * What actually happened. `keyed` says the keystrokes of an answer reached the tty
 * and, for a digit, that a Return followed only if the screen showed the digit
 * landed. `typed` is the strongest thing a send can claim: the bytes reached the
 * tty. Whether the assistant took the turn is a separate fact, read from the fleet
 * list, and this never asserts it.
 */
export interface ActionResult {
  action: string

  /**
   * Present on a close that went ahead over open obligations.
   */
  forced?: boolean
  id: string
  ok: boolean
}

/**
 * POST /v1/auth/adopt: a token the page was handed in a URL fragment, traded for
 * the cookie EventSource needs. Nothing is granted: an unknown token is 401.
 */
export interface AdoptRequest {
  token: string
}

/**
 * What attribution this service can hold.
 */
export interface AnalyticsAttributionCapabilities {
  automaticFeatureAttribution: boolean
  decisions: string[]
  dimensions: string[]
  featureAggregation: string
  featureProducer: string
  llmEvidence: string
  sources: string[]
}

/**
 * complete, or partial with scan_limit_reached.
 */
export interface AnalyticsAvailability {
  reason?: string
  status: string
}

/**
 * A summary for one group, with the group's key.
 */
export interface AnalyticsBreakdown {
  costs: AnalyticsCostSeries[]
  coverage: AnalyticsCoverageSummary

  /**
   * The group's value; null for rows without one.
   */
  key: string | null

  /**
   * Sum of the known parts of every row that knew any; null when none did.
   */
  measuredFloor: number | null

  /**
   * Rows by origin: manual, dispatch, schedule, follow_up.
   */
  origins: AnalyticsCounts
  rows: number
  scheduledRuns: number

  /**
   * Sum of whole rows; null when any row is incomplete or there are none.
   */
  strictTotal: number | null
  tokenPartsUnknown: AnalyticsCounts
  tokenRowsUnknown: number
  tokens: AnalyticsTokens
  unavailableCost: AnalyticsUnavailableCost
}

/**
 * The query language this service accepts.
 */
export interface AnalyticsCapabilities {
  attribution: AnalyticsAttributionCapabilities
  buckets: string[]
  exports: string[]
  filters: string[]
  groupBy: string[]
  maxPageSize: number
  maxScannedRows: number
  views: string[]
}

/**
 * The Feature classifier; this daemon runs none, so `configured` is false and
 * nothing else is sent.
 */
export interface AnalyticsClassifier {
  configured: boolean
  id?: string
  threshold?: number
  version?: string
}

/**
 * Output against the equal previous range. `status` is comparable or unavailable;
 * `reason` is closed_range_required, range_truncated, no_previous_data or
 * incomplete_output.
 */
export interface AnalyticsComparison {
  absolute?: number
  current?: number
  currentRange?: AnalyticsDayRange

  /**
   * Null when the previous output was 0.
   */
  percent: number | null
  percentReason: string | null
  previous?: number
  previousRange: AnalyticsDayRange | null
  reason?: string
  status: string
}

/**
 * One (unit, basis) cost series.
 */
export interface AnalyticsCostSeries {
  /**
   * list_price_estimate, published_rate_estimate, provider_actual or unknown.
   */
  basis: string
  priceSnapshotIds: string[]
  rows: number

  /**
   * USD or credits.
   */
  unit: string
  value: number
}

/**
 * A map, keyed by name, of counts. contract-gen has no map type, so the generated
 * type is empty and a reader indexes it by key.
 */
export interface AnalyticsCounts {
}

/**
 * A set of rows' coverage, with its verdict.
 */
export interface AnalyticsCoverage {
  completeRows: number
  partialRows: number
  reasons: AnalyticsCounts
  rows: number
  states: AnalyticsCounts

  /**
   * unavailable, complete or partial.
   */
  status: string
  unknownOutputRuns: number
}

/**
 * How much of a set of rows could be measured.
 */
export interface AnalyticsCoverageSummary {
  /**
   * Rows by named coverage reason.
   */
  reasons: AnalyticsCounts

  /**
   * Rows by coverage: complete, partial, source_missing.
   */
  states: AnalyticsCounts

  /**
   * Rows by token part that was unknown; only parts with a count appear.
   */
  tokenPartsUnknown: AnalyticsCounts

  /**
   * Rows with at least one unknown token part.
   */
  tokenRowsUnknown: number
}

/**
 * A from/to pair of local days.
 */
export interface AnalyticsDayRange {
  from: string | null
  to: string | null
}

/**
 * One Feature with one unambiguous accepted head. `usageByRole` is open:
 * implementation, review and undeclared readings.
 */
export interface AnalyticsFeature {
  coverage: AnalyticsCoverage
  id: string
  label: string
  output: number | null
  project: AnalyticsFeatureProject
  runs: number
  unknownOutputRuns: number
  usageByRole: AnalyticsCounts
}

/**
 * The Project a Feature belongs to.
 */
export interface AnalyticsFeatureProject {
  icon?: Icon
  id: string | null
  label: string
  reason?: string
}

/**
 * Accepted Feature attribution. This daemon records none, so `groups` is empty and
 * every run is the Unknown Feature.
 */
export interface AnalyticsFeatures {
  automaticAttribution: boolean
  classifier: AnalyticsClassifier
  groups: AnalyticsFeature[]
  policy: string
  roleEvidence: AnalyticsRoleEvidence

  /**
   * available or no_accepted_attribution.
   */
  status: string
  unknown: AnalyticsUnknownFeature
}

/**
 * How recent the whole store is.
 */
export interface AnalyticsFreshness {
  ageSeconds: number | null
  generatedAt: string
  latestObservedAt: string | null
  scanTruncated: boolean

  /**
   * empty, current or stale (older than 600 s).
   */
  status: string
}

/**
 * Whether a Project could be named.
 */
export interface AnalyticsIdentity {
  reasons: string[]

  /**
   * available or unavailable.
   */
  status: string
}

/**
 * One operational clue: top_mover, context_to_output, coverage_degradation or
 * cost_concentration. At most four, in that order.
 */
export interface AnalyticsInsight {
  detail: string
  kind: string

  /**
   * Absent for coverage_degradation.
   */
  projectId?: string
  title: string
}

/**
 * Runs by role; scheduled work is never guessed as root or child.
 */
export interface AnalyticsLineage {
  childRuns: number
  reason: string | null
  rootRuns: number
  scheduledRuns: number

  /**
   * available, partial or unavailable.
   */
  status: string
  unknownRuns: number
}

/**
 * One slice of a Project's assistant or work mix.
 */
export interface AnalyticsMix {
  label: string
  output: number | null
  runs: number
  unknownOutputRuns: number
}

/**
 * Where the next page starts.
 */
export interface AnalyticsPagination {
  hasMore: boolean
  limit: number

  /**
   * An opaque continuation; null on the last page.
   */
  nextCursor: string | null
}

/**
 * The Project Portfolio.
 */
export interface AnalyticsPortfolio {
  comparison: AnalyticsComparison
  features: AnalyticsFeatures
  insights: AnalyticsInsight[]
  primarySignal: string
  projects: AnalyticsProject[]
  runs: number
  scheduledWork: AnalyticsScheduledWork
  schemaVersion: number
  scoreWarning: string
}

/**
 * Which list-price table priced the rows.
 */
export interface AnalyticsPriceSnapshot {
  activeId: string
  meaning: string
  observedIds: string[]
}

/**
 * One Project in the portfolio, ranked by generated output.
 */
export interface AnalyticsProject {
  assistantMix: AnalyticsMix[]
  comparison: AnalyticsComparison
  cost: AnalyticsProjectCost
  coverage: AnalyticsCoverage

  /**
   * project-<16 hex>, or unknown-project.
   */
  id: string
  identity: AnalyticsIdentity
  label: string
  lineage: AnalyticsLineage
  output: number | null
  rank: number

  /**
   * Up to six rows, newest first, with `project` set to this Project's label.
   */
  recentWork: AnalyticsRow[]

  /**
   * Distinct tasks, or distinct sessions without one.
   */
  runs: number
  scheduledOutput: number | null
  scheduledRuns: number
  tokenPartsUnknown: AnalyticsCounts
  tokens: AnalyticsTokens
  trend: AnalyticsTrendBucket[]
  unknownOutputRuns: number
  workMix: AnalyticsMix[]
}

/**
 * Claude Code's comparable cost for a Project. unavailable carries a reason:
 * no_claude_code_usage, partial_cost_coverage, no_cost_series or mixed_cost_series.
 */
export interface AnalyticsProjectCost {
  assistant: string
  basis?: string
  reason?: string
  rows?: number
  status: string
  unavailableRows?: number
  unit?: string
  value?: number
}

/**
 * The inclusive local dates asked for.
 */
export interface AnalyticsRange {
  from: string | null

  /**
   * IANA zone.
   */
  timezone: string
  to: string | null
}

/**
 * How recent the matched rows are.
 */
export interface AnalyticsRangeFreshness {
  ageSeconds: number | null
  dataThrough: string | null

  /**
   * empty, current or historical.
   */
  status: string
}

/**
 * How much review evidence was read.
 */
export interface AnalyticsReviewReceipts {
  limit: number
  read: number
  status: string
  truncated: boolean
}

/**
 * Evidence behind the per-role split.
 */
export interface AnalyticsRoleEvidence {
  reviewReceipts: AnalyticsReviewReceipts
}

/**
 * One usage interval. On this daemon an interval is one conversation as its own
 * record accounts for it. Prompts, session ids and paths are never sent.
 */
export interface AnalyticsRow {
  /**
   * claude or codex.
   */
  assistant: string
  cost: AnalyticsRowCost | null

  /**
   * complete, partial or source_missing.
   */
  coverage: string
  coverageReasons: string[]

  /**
   * Null while the conversation is still being written.
   */
  endedAt: string | null

  /**
   * The interval key.
   */
  id: string

  /**
   * excludes_cache (Claude) or includes_cache (Codex).
   */
  inputBasis: string | null
  lineage: AnalyticsRowLineage
  measuredFloor: number | null
  missingCostReason: string | null
  model: string | null

  /**
   * manual, dispatch or schedule.
   */
  origin: string

  /**
   * The Project's final name; null for a missing key or a managed worktree.
   */
  project: string | null
  reconciliation: string | null
  scheduleId: string | null

  /**
   * The record's own total, as it counts.
   */
  sourceTotal: number | null

  /**
   * ISO 8601, UTC, whole seconds.
   */
  startedAt: string
  strictTotal: number | null
  taskId: string | null
  tokens: AnalyticsTokens
  unknownTokenParts: string[]
}

/**
 * A recorded or estimated cost.
 */
export interface AnalyticsRowCost {
  basis: string
  priceSnapshotId: string | null
  unit: string
  value: number
}

/**
 * What is known of the row's place in a task graph; every key may be null.
 */
export interface AnalyticsRowLineage {
  attempt: number | null
  disposition: string | null
  graphId: string | null
  landingState: string | null
  landingVerified: boolean | null
  parentTaskId: string | null
  retryOf: string | null
}

/**
 * One schedule's work.
 */
export interface AnalyticsSchedule {
  activeDays: number
  coverage: AnalyticsCoverage
  id: string
  label: string
  lastRunAt: string | null
  output: number | null
  runs: number
  unknownOutputRuns: number
}

/**
 * Work with explicit schedule identity.
 */
export interface AnalyticsScheduledWork {
  output: number | null
  reason: string | null
  runs: number
  schedules: AnalyticsSchedule[]
  status: string
  unknownOutputRuns: number
  unknownSchedule: AnalyticsUnknownSchedule
}

/**
 * `UsageQueryService.summary` over a set of rows.
 */
export interface AnalyticsSummary {
  costs: AnalyticsCostSeries[]
  coverage: AnalyticsCoverageSummary

  /**
   * Sum of the known parts of every row that knew any; null when none did.
   */
  measuredFloor: number | null

  /**
   * Rows by origin: manual, dispatch, schedule, follow_up.
   */
  origins: AnalyticsCounts
  rows: number
  scheduledRuns: number

  /**
   * Sum of whole rows; null when any row is incomplete or there are none.
   */
  strictTotal: number | null
  tokenPartsUnknown: AnalyticsCounts
  tokenRowsUnknown: number
  tokens: AnalyticsTokens
  unavailableCost: AnalyticsUnavailableCost
}

/**
 * The four token parts. A part no row could measure is null, never 0.
 */
export interface AnalyticsTokens {
  cacheRead: number | null
  cacheWrite: number | null
  inputNew: number | null
  output: number | null
}

/**
 * One bucket of the trend; empty buckets are not sent.
 */
export interface AnalyticsTrendBucket {
  /**
   * YYYY-MM-DD for day and week (weeks start on Sunday), YYYY-MM for month.
   */
  bucket: string
  coverage: AnalyticsCoverageSummary
  measuredFloor: number | null
  strictTotal: number | null
  tokens: AnalyticsTokens
}

/**
 * Rows without a cost, by why.
 */
export interface AnalyticsUnavailableCost {
  /**
   * plan_billed, no_price_for_model, unknown_model or no_cost_recorded.
   */
  reasons: AnalyticsCounts
  rows: number
}

/**
 * Views this service refuses to infer.
 */
export interface AnalyticsUnavailableDimensions {
  dimensions: string[]
  featureAvailability: string
  featureView: boolean
  graphView: boolean
  landingView: boolean
  reason: string
  retryView: boolean
}

/**
 * What the named Features do not account for.
 */
export interface AnalyticsUnknownFeature {
  label: string
  output: number | null
  reason: string
  runs: number
  unknownOutputRuns: number
}

/**
 * Scheduled runs with no schedule identity.
 */
export interface AnalyticsUnknownSchedule {
  reason: string
  runs: number
}

export type Assistant =
    "claude"
  | "codex"

export const AssistantValues: readonly Assistant[] = ["claude", "codex"] as const

/**
 * The inside of every refusal the gate and the auth routes give. `code` is the part
 * a client may branch on; `message` is English, for a person.
 */
export interface AuthError {
  /**
   * unauthorized, forbidden, wrong_code, expired, rate_limited, bad_request,
   * not_found, store_unavailable, unsupported_media_type.
   */
  code: string
  message: string

  /**
   * A fresh lowercase UUID per refusal, for finding it in a log.
   */
  request_id: string

  /**
   * Only on wrong_code: how many guesses pairing has left, so a page need not count
   * for itself. The count is across pairings, not per pairing: asking again does
   * not refill it.
   */
  tries_left?: number
}

/**
 * POST /v1/auth/logout, and the device routes that only change something.
 */
export interface AuthOK {
  ok: boolean
}

export interface AuthRefusal {
  error: AuthError
}

export type Backend =
    "iterm"
  | "tmux"
  | "owned"

export const BackendValues: readonly Backend[] = ["iterm", "tmux", "owned"] as const

export interface BoardSnapshot {
  at: number
  projects: Project[]
  revision: number
  schemaVersion: number
  source: BoardSource
}

/**
 * A board built from a partial inventory is not a board with fewer projects; it is
 * a board that does not know.
 */
export interface BoardSource {
  complete: boolean
  observedAt: number
  provenance: string
}

export interface BoardWriteResult {
  ok: boolean

  /**
   * True when this request id had already been applied with the same body. The
   * original outcome is the answer and nothing moved.
   */
  replayed: boolean
  revision: number
}

/**
 * A device minted for a browser on this machine. `url` carries the token in its
 * fragment, which a browser never sends and never logs; the page trades it for the
 * cookie with /v1/auth/adopt.
 */
export interface BrowserDevice {
  id: string
  token: string
  url: string
}

/**
 * POST /v1/auth/devices/browser: `clawdline open` asking for a device of its own.
 * Local token only.
 */
export interface BrowserRequest {
  /**
   * Also grant send. Off unless the person at this machine asked.
   */
  send?: boolean
}

/**
 * POST /v1/auth/devices/{id}/caps. read is always kept; send is the only other
 * grant. Local token only.
 */
export interface CapsRequest {
  caps: string[]
}

export interface CatalogError {
  code: string
  message: string
}

/**
 * How completely the Board store's own ingestion covered its sources. This daemon
 * does not ingest, so it says unknown.
 */
export interface CatalogIngestion {
  status: string
}

/**
 * One Project in the Board store. `label`, `displayPath` and `icon` are present
 * only for a Project a start place resolves to (`isStartPoint`). `activeItemCount`
 * and `summaryCoverage` are absent: they are the Swift app's progress projection,
 * which this daemon does not restate, and an absent count is drawn as unknown,
 * never as zero.
 */
export interface CatalogProject {
  displayPath?: string
  icon?: Icon
  id: string
  isStartPoint: boolean

  /**
   * Items the store files under this Project.
   */
  itemCount: number
  label?: string
  name: string
}

export interface CatalogReadState {
  error?: CatalogError

  /**
   * Unix seconds of the reading, when there is one.
   */
  observedAt?: number
  status: CatalogReadStatus
}

/**
 * ready: the store was read now. stale: the newest read failed and an earlier one
 * is carried. error: nothing could be read.
 */
export type CatalogReadStatus =
    "ready"
  | "stale"
  | "error"

export const CatalogReadStatusValues: readonly CatalogReadStatus[] = ["ready", "stale", "error"] as const

export interface CatalogSource {
  ingestion: CatalogIngestion
  truncated: boolean
}

/**
 * Who clears the thing standing in the way, as the Swift app's
 * CloseabilityMover.wire spells it. `self` distinguishes the session that has to
 * act from another one, which is the difference between a thing a reader can do now
 * and a thing they can only wait for. `self` is always present here; the Swift app
 * leaves it out for a person, a task and the broker, where it would be false.
 */
export interface CloseMover {
  kind: string
  person_needed: boolean
  self: boolean

  /**
   * The other session that moves it, when `kind` is `session` and `self` is false.
   */
  session_id?: string

  /**
   * The task that moves it, when `kind` is `task`.
   */
  task_id?: string
}

/**
 * One thing in the way. It names the machine code, the subject it is about and who
 * moves it: a code alone says there is a problem but not which object has it, and a
 * sentence alone cannot be grepped for in a log. `subject_kind` and `subject_id`
 * are absent for the evidence reasons that are about the reading rather than an
 * object.
 */
export interface CloseReason {
  code: string
  kind: string
  mover: CloseMover
  subject_id?: string
  subject_kind?: string
}

/**
 * A close refused by what the session still owes. It carries the same reasons the
 * fleet list was already showing, so the screen and the action never disagree.
 */
export interface CloseRefusal {
  detail: string
  error: string
  reasons: CloseReason[]
}

export interface CloseRequest {
  /**
   * Close although something is still owed. It cannot override an unreadable
   * obligation list: overriding a refusal is a decision, and there is nothing to
   * decide about when the list could not be read.
   */
  force?: boolean
}

/**
 * Where the reading came from and how old it is. `provenance` is `session_watch`,
 * the scan of the machine's sessions this row came from. `freshness` is what stops
 * a stale `safe` being read as a current one — the console refuses to call
 * anything safe unless this says `current`.
 */
export interface CloseSource {
  freshness: string
  max_age_seconds: number
  observed_at: number
  provenance: string
}

/**
 * Whether this session can end, by the Swift app's rules
 * (Orchestrator.projectCloseability, CloseabilityIndex.swift) over the Swift app's
 * store, read-only, plus this daemon's own obligations. A separate question from
 * whether it can take work, and neither may be read off the other. `safe` is a
 * positive claim and the reader enforces what it costs: no reasons, a current
 * source, an attestation id and a version, and a session that is not working,
 * waiting or unreadable. Anything short of that reads as `unknown`. An unreadable
 * store is an `evidence` reason (`swift_store_unreadable`), so it can never come
 * out as safe or as an empty list. `attestation_id` and `mover` are always present
 * and may be null.
 */
export interface Closeability {
  /**
   * This terminal's turn clock from the Swift store (`session_activity`); 0 when it
   * has none. An attestation names it, so a turn started after attesting
   * invalidates the claim.
   */
  activity_generation: number

  /**
   * The identifier of the reading that proves nothing is owed. Null until something
   * attests, and a null here is exactly why a state that would otherwise be safe
   * reads as unknown.
   */
  attestation_id: string | null

  /**
   * The one mover every reason points at; null when they point at more than one,
   * which is itself the answer.
   */
  mover: CloseMover | null

  /**
   * The Swift store's machine-wide obligation clock.
   */
  obligation_generation: number
  observed_at: number

  /**
   * `broker`, and `self` beside it when the session's own attestation matched this
   * process.
   */
  provenance: string[]
  reasons: CloseReason[]

  /**
   * Which reading of the machine this came from — the same counter the snapshot's
   * scan carries, so a closeability and the list it arrived with can be told apart
   * from a later pair.
   */
  session_generation: number
  source: CloseSource
  state: CloseabilityState

  /**
   * `cl1_` and 32 hex digits: the Swift app's closeabilityVersion over the exact
   * process identity, the two clocks and the state. A reading with no version is a
   * reading nobody can say the rules for.
   */
  version: string
}

/**
 * `safe` is a positive claim that nothing is owed. An unreadable obligation list
 * must produce `unknown`, never `safe`.
 */
export type CloseabilityState =
    "safe"
  | "blocked"
  | "needs_attestation"
  | "unknown"

export const CloseabilityStateValues: readonly CloseabilityState[] = ["safe", "blocked", "needs_attestation", "unknown"] as const

/**
 * One file-ownership wait between sessions, from the Swift store's
 * `coordination_waits`, as Orchestrator.coordination(forTerminal:) shapes it. On
 * the waiting side it carries `reason` and `waiterCreatedAt`; on the owner's side
 * `waiterSessionId` and `reason`. The label beside a session id is present when
 * that session is on screen.
 */
export interface CoordinationWaitRow {
  createdAt: number
  id: string
  ownerLabel?: string
  ownerSessionId: string
  paths: string[]
  reason?: string
  releaseCondition: string
  repository: string
  waiterCreatedAt?: number
  waiterLabel?: string
  waiterSessionId?: string
}

export interface CoordinatorRecord {
  assistant: Assistant
  conversationId: string

  /**
   * Increments on every rebind, so a stale caller holding an old view cannot move a
   * role that has already moved.
   */
  generation: number
  id: string
  label: string
  pid: number
  reboundAt?: number
  registeredAt: number
  sessionId: string
}

export interface CoordinatorRequest {
  assistant?: Assistant
  conversationId?: string
  expectGeneration?: number
  expectId?: string
  label?: string
  operation: string
  pid?: number
  sessionId?: string
}

export interface CoordinatorResult {
  ok: boolean
  record: CoordinatorRecord
}

export interface CoordinatorSnapshot {
  candidates: string[]
  liveness: Liveness
  record: CoordinatorRecord | null
  registered: boolean
}

/**
 * GET /v1/auth/devices. This machine's own token only; a paired device is refused.
 */
export interface DeviceList {
  /**
   * Whether a person has paired something or set a password — the tunnel
   * interlock's question. This machine's own token does not count.
   */
  configured: boolean
  devices: PairedDevice[]
  password: boolean
}

/**
 * GET /v1/diagnostics, this machine's own token only (a paired device is 403): what
 * health used to carry about the process — its state directory, its ports and the
 * clock's last pass.
 */
export interface Diagnostics {
  at: number
  dir: string
  ok: boolean
  port: number
  scheduler: SchedulerPulse
  served_by: string
  upstream: number
}

export interface DispatchRequest {
  assistant: Assistant

  /**
   * The paths this task intends to write, declared before it starts. Absent is
   * refused and an empty list is accepted: `I declared none` and `I did not say`
   * are different requests, and only one of them can be arbitrated against another
   * root. This is a dispatch-time reservation compared between roots, not
   * filesystem enforcement — nothing stops a child writing outside it, and
   * pretending otherwise would be the more dangerous lie.
   */
  claims?: string[]
  instructions: string
  project_dir: string

  /**
   * Supply one to make the dispatch idempotent: the same id with the same body
   * replays rather than starting a second session.
   */
  task_id?: string
}

/**
 * The intent committed. It does not say the assistant received anything — that is
 * a later fact with its own evidence, and `replayed` is how a caller tells a fresh
 * dispatch from one it had already made.
 */
export interface DispatchResult {
  ok: boolean
  replayed: boolean
  task_dir: string
  task_id: string
}

export interface DocumentList {
  documents: DocumentRow[]
}

/**
 * One document a paired device may read. `label` repeats `path` because the page
 * checks that they agree; `url` is this daemon's own address for the bytes and is
 * dropped by the page, which builds its own from the locator.
 */
export interface DocumentRow {
  /**
   * The file's size when it was checked, never above the two-megabyte cap.
   */
  bytes: number
  label: string

  /**
   * Unix seconds with a fraction, as the filesystem reported them.
   */
  modified: number

  /**
   * Relative to its root, `/`-separated, at most six segments, none of them
   * starting with a dot.
   */
  path: string
  source: DocumentSource
  task?: DocumentTask
  url: string
}

/**
 * Which root this document is in: the project's `<cwd>/artifacts`, or one task's
 * `<task dir>/artifacts`.
 */
export type DocumentSource =
    "project"
  | "task"

export const DocumentSourceValues: readonly DocumentSource[] = ["project", "task"] as const

/**
 * The task a `task`-scoped row belongs to. Exactly these two keys: the page checks
 * the count.
 */
export interface DocumentTask {
  /**
   * The dispatched task's id, which is what the read address names.
   */
  id: string

  /**
   * What that task was called, empty when it was called nothing.
   */
  title: string
}

/**
 * How loud an obligation has become. Escalation changes visibility, never verdict:
 * nothing here ever declares a session dead.
 */
export type Escalation =
    "quiet"
  | "aging"
  | "overdue"

export const EscalationValues: readonly Escalation[] = ["quiet", "aging", "overdue"] as const

/**
 * HOW a reading was obtained. Every observed field travels with one of these,
 * because a structured event and a screen guess are different kinds of fact and a
 * reader must be able to tell them apart.
 */
export type Evidence =
    "structured"
  | "transcript"
  | "process"
  | "screen"
  | "registry"
  | "none"

export const EvidenceValues: readonly Evidence[] = ["structured", "transcript", "process", "screen", "registry", "none"] as const

/**
 * GET /v1/health, open without a token: that this daemon is alive and which
 * implementation it is, and nothing else. No path, no port, nothing about the work;
 * those are in Diagnostics.
 */
export interface Health {
  at: number
  ok: boolean

  /**
   * Which implementation answered. This is how a reader tells the Go daemon from
   * the Swift app on the same port.
   */
  served_by: string
}

/**
 * A project's mark: rows of `#RRGGBB`, with null for transparent. It is derived
 * from the project path and the machine's icon registry by the same rules the Swift
 * app uses, so both apps draw the same creature — a mark somebody recognises by
 * colour and shape is not recognisable if the second app draws it differently, and
 * near-identical is worse than obviously different.
 */
export interface Icon {
  accent: string
  cells: ((string | null)[])[]
}

/**
 * Why a reference has no picture behind it: `expired` when the store held it and no
 * longer does, `unknown` when no store here ever held that id.
 */
export type ImageAbsence =
    "expired"
  | "unknown"

export const ImageAbsenceValues: readonly ImageAbsence[] = ["expired", "unknown"] as const

/**
 * One picture a transcript entry shows, in the Swift app's
 * `SessionImageArtifact.object` shape. A reference with `state` describes no bytes:
 * its size fields are 0 and `expires_at` is 1, which is the branch every renderer
 * already draws as gone.
 */
export interface ImageArtifact {
  byte_count: number

  /**
   * Unix seconds after which the picture is gone.
   */
  expires_at: number
  height: number

  /**
   * A lowercase UUID. The whole of what the bytes are fetched by.
   */
  id: string

  /**
   * Always image/png: every stored picture was drawn and written out again.
   */
  media_type: string
  state?: ImageAbsence
  width: number
}

export interface ImagePath {
  /**
   * One normalized absolute path to a regular local file. A link is refused.
   */
  path: string
}

/**
 * POST /v1/artifacts/images, with this machine's orchestrator token only: 1…6
 * local pictures a session wants to show in its own reply. Each is decoded, bounded
 * and stored as PNG before any is kept.
 */
export interface ImageStoreRequest {
  images: ImagePath[]
}

export interface ImageStoreResult {
  artifacts: StoredImage[]
  at: number
  ok: boolean
}

export interface Inventory {
  at: number
  scan: InventoryScan
  served_by: string
  sessions: InventorySession[]
}

export interface InventoryScan {
  complete: boolean
  notes: string[] | null
  provenance: string
}

/**
 * A raw row of the terminal reading, before the fleet list drops the rows that are
 * not assistants.
 */
export interface InventorySession {
  assistant?: Assistant
  backend: Backend
  conversation_id?: string
  cwd?: string
  evidence: Evidence
  id: string
  label?: string
  pid?: number
  state: SessionState
  tty?: string
}

/**
 * One key for a session's menu: a digit "1"…"9" answers the row with that number,
 * "tab" and "shift+tab" are the only other keys, and "submit" presses a
 * multi-select's button. Anything else is refused before the session is looked up.
 * Never a way to type text: words sent to a picker are thrown away and the Return
 * after them confirms whatever is highlighted.
 */
export interface KeyRequest {
  key: string
}

/**
 * What a current inventory says about the bound process. An incomplete reading
 * answers `unknown`, never `offline`: absence of evidence is not proof of death.
 */
export type Liveness =
    "online"
  | "offline"
  | "unknown"

export const LivenessValues: readonly Liveness[] = ["online", "offline", "unknown"] as const

export interface ModelUsage {
  cacheReadTokens: number
  cacheWriteTokens: number
  inputTokens: number

  /**
   * Empty where the record did not name one. Codex's cumulative total does not, and
   * it is left blank rather than guessed from the session's current configuration,
   * which can have changed partway through a thread.
   */
  model: string
  outputTokens: number
  thinkingTokens: number
}

export interface Mover {
  id: string
  kind: MoverKind
}

/**
 * Who can clear an obligation. Naming the mover is what turns a stuck list into an
 * actionable one.
 */
export type MoverKind =
    "this_session"
  | "other_session"
  | "person"
  | "task"
  | "broker"

export const MoverKindValues: readonly MoverKind[] = ["this_session", "other_session", "person", "task", "broker"] as const

export interface Obligation {
  age_seconds: number
  escalation: Escalation
  evidence: Evidence
  id: string
  kind: ObligationKind
  mover: Mover
  note: string
  opened_at: number
  subject: string
}

export type ObligationKind =
    "wait"
  | "landing"
  | "handoff"
  | "succession"
  | "assignment"
  | "deadletter"
  | "review"

export const ObligationKindValues: readonly ObligationKind[] = ["wait", "landing", "handoff", "succession", "assignment", "deadletter", "review"] as const

export interface ObligationList {
  at: number
  obligations: Obligation[]

  /**
   * How many rows are past their overdue threshold. A count, not a verdict.
   */
  stuck: number
}

/**
 * POST /v1/auth/pair/confirm. A wrong code is 403 wrong_code with tries_left. Five
 * wrong codes in a day, whichever pairings they were typed into, close pairing: the
 * fifth, and every confirmation after it, is 403 expired, as are a lapsed pairing
 * and a replaced one.
 */
export interface PairConfirm {
  code: string
  pairing_id: string
}

/**
 * POST /v1/auth/pair. Open without a token. Three in ten minutes, then 429
 * rate_limited; also 429 rate_limited while five wrong codes in the last day keep
 * pairing closed.
 */
export interface PairRequest {
  /**
   * What to call the device; trimmed, at most forty characters, `A browser` when
   * empty.
   */
  name?: string
}

/**
 * The answer to a pairing request. The six-digit code is never in it: it is shown
 * on this machine, to a local-token holder, and typed into the device.
 */
export interface PairStarted {
  /**
   * Unix seconds. Two minutes after the request.
   */
  expires: number
  pairing_id: string
}

export interface PairedDevice {
  /**
   * read, and send when this device may type into a session.
   */
  caps: string[]

  /**
   * Unix seconds.
   */
  created: number
  id: string

  /**
   * Unix seconds of the last request it made since the daemon started or last
   * saved; absent when never.
   */
  last_seen?: number
  name: string
}

/**
 * One `pairing` event on GET /v1/auth/pairings, the server-sent stream only this
 * machine's own token may open. It is the one place the code leaves the daemon. The
 * stream starts with the pairing open now, if any.
 */
export interface PairingNotice {
  code: string
  expires: number
  name: string
  pairing_id: string
}

/**
 * POST /v1/auth/password: a correct password mints a new read-only device. Ten
 * wrong passwords in a day, from everybody together, and the checks still under way
 * count toward the same ten; past it, 429 rate_limited before any hashing. `name`
 * is cut to forty characters before it is stored or audited.
 */
export interface PasswordRequest {
  name?: string
  password: string
}

/**
 * POST /v1/auth/devices/password. Empty clears it. Local token only.
 */
export interface PasswordSet {
  password: string
}

/**
 * One conversation an assistant has already recorded in a place. `id` is the only
 * part a client sends back.
 */
export interface PastSession {
  /**
   * When it was last written to, Unix seconds.
   */
  at: number

  /**
   * A lowercase UUID: the conversation's own id.
   */
  id: string

  /**
   * Something is writing to it right now; resuming it would put a second process on
   * the same record.
   */
  live: boolean
  title: string
}

/**
 * GET /v1/places/{id}/sessions[/{assistant}]: what that assistant has recorded in
 * the place, newest first, at most two hundred. Dispatched children and `-p` runs
 * are not conversations and are left out.
 */
export interface PastSessionList {
  assistant: string
  at: number

  /**
   * The list stopped at its cap and there were more.
   */
  more: boolean
  place: string
  sessions: PastSession[]
}

/**
 * A refusal from the start, resume and history routes: not_found, forbidden,
 * bad_request, invalid_launch, terminal_closed, terminal_unsupported,
 * terminal_io_failed, iterm_attention_required, capability_unavailable,
 * terminal_busy.
 */
export interface PlaceError {
  /**
   * The terminal the refusal is about, on terminal_closed and
   * iterm_attention_required, so a page can name it in its own language.
   */
  app?: string
  code: string
  message: string
  request_id: string
}

export interface PlaceRefusal {
  error: PlaceError
}

/**
 * POST /v1/places/{id}/resume/[{assistant}/]{session}: a conversation this machine
 * listed for that place, picked back up in a new terminal. The same gate and replay
 * as a start.
 */
export interface PlaceResumed {
  assistant: string
  at: number
  attach: string
  backend: Backend
  cwd: string
  id: string
  ok: boolean
  place: string

  /**
   * The conversation that was resumed.
   */
  session: string
}

/**
 * POST /v1/places/{id}/start[/{assistant}[/{model}]]: a terminal was opened and the
 * assistant typed into it. The body is not read. `id` is in the same space as every
 * id in /v1/sessions, but the session is not in that list yet. Needs a device that
 * may send and an Idempotency-Key; a retry within ten minutes is answered from the
 * first reply rather than opening a second tab.
 */
export interface PlaceStarted {
  /**
   * claude or codex, as the path named it (claude when it named none).
   */
  assistant: string
  at: number

  /**
   * What to type at the Mac to see the session, for the one start that puts it
   * where nobody is looking (a tmux server started detached); empty otherwise.
   */
  attach: string
  backend: Backend
  cwd: string

  /**
   * The new terminal: a tmux pane id or an iTerm2 session id.
   */
  id: string

  /**
   * The model the path named, or empty.
   */
  model: string
  ok: boolean
  place: string
}

export interface Project {
  displayPath: string
  id: string
  name: string

  /**
   * A reading, not a stored count, so it cannot drift from the thing it describes.
   */
  sessionCount: number
}

export interface ProjectCatalog {
  /**
   * False when the store could not be read at all; `readState.error` says why.
   */
  available: boolean

  /**
   * The store's own Board switch.
   */
  enabled: boolean
  mode: string
  projects: CatalogProject[]
  readState: CatalogReadState
  revision: number
  schemaVersion: number
  source: CatalogSource
}

/**
 * GET /v1/projects.
 */
export interface ProjectCatalogAnswer {
  at: number
  catalog: ProjectCatalog
}

/**
 * Which worktrees under one Project finished a Feature. With no accepted Feature
 * attribution on this daemon, `worktrees` is always empty; the read still resolves
 * the Project.
 */
export interface ProjectWorktrees {
  excluded: ProjectWorktreesExcluded
  generatedAt: string
  outcomeRule: string
  policy: string
  project: ProjectWorktreesProject
  range: AnalyticsRange
  read: ProjectWorktreesRead
  schemaVersion: number

  /**
   * available or partial.
   */
  status: string
  unattributed: ProjectWorktreesUnattributed

  /**
   * Per-worktree outcomes (open objects).
   */
  worktrees: AnalyticsCounts[]
}

/**
 * Worktrees left out for having no accepted Feature.
 */
export interface ProjectWorktreesExcluded {
  reason: string
  worktreesWithoutFeature: number
}

/**
 * The Project resolved.
 */
export interface ProjectWorktreesProject {
  id: string
  label: string
}

/**
 * What a project-worktrees read covered.
 */
export interface ProjectWorktreesRead {
  featureRows: number
  maxScannedRows: number
  projectRows: number
  rows: number
  truncated: boolean
  worktreeRows: number
}

/**
 * GET /v1/orchestrator/usage/project-worktrees.
 */
export interface ProjectWorktreesReply {
  projectWorktrees: ProjectWorktrees
}

/**
 * Managed worktrees whose rows name no Project.
 */
export interface ProjectWorktreesUnattributed {
  reasons: AnalyticsCounts
  worktrees: number
}

/**
 * Every refusal on this daemon has this shape. A caller reads `error` as the code
 * and never parses `detail`.
 */
export interface Refusal {
  detail: string
  error: string
  route?: string
  upstream?: string
}

/**
 * POST /v1/auth/devices/revoke-all: every paired device, the password and the open
 * pairing. This machine's own token stays.
 */
export interface RevokedAll {
  count: number
  ok: boolean
}

/**
 * A broker-proved independent Feature Root this session owns.
 */
export interface RootAssignmentRecord {
  explanation: string
  id: string
  label: string
  ownership: string
  state: string
}

/**
 * What the reading behind this snapshot knows about itself. Without it an empty
 * list cannot be told apart from a failed scan.
 */
export interface Scan {
  complete: boolean
  completed: ScanCompleted

  /**
   * An empty list is only authoritative when the reading was complete. This is what
   * stops a client reading a failed scan as `every session went away`.
   */
  emptyAuthoritative: boolean

  /**
   * Identifies the process. A client reconnecting to a restarted daemon uses it to
   * tell a reset generation from one that went backwards.
   */
  epoch: number
  generation: number
  provenance: string
}

export interface ScanCompleted {
  complete: boolean
  sequence: number
}

export interface ScheduleList {
  schedules: ScheduleRow[]
}

/**
 * The body POST /v1/schedules accepts. `claims` absent is refused rather than read
 * as none: a dispatch that declared nothing and a dispatch that declared an empty
 * set are different requests.
 */
export interface ScheduleRequest {
  assistant: Assistant
  brief: string
  claims?: string[]
  dir: string
  id: string
  name: string
  when: string
}

export interface ScheduleRow {
  assistant: Assistant
  dir: string
  enabled: boolean
  id: string

  /**
   * 0 means never run, rather than the Unix value of the zero time.
   */
  lastRun: number
  lastTask: string
  name: string

  /**
   * Present and true when this schedule's stored spelling did not parse. It is
   * switched off, and `when` carries the spelling as written rather than a parsed
   * value — otherwise an unreadable row renders as `every 0s`, which reads like a
   * setting somebody chose.
   */
  unreadable?: boolean
  when: string
}

export interface ScheduleSaved {
  id: string
  ok: boolean
  when: string
}

/**
 * What the clock says about its own last pass. A pass that fired nothing and a
 * scheduler that stopped are both silence from outside, so the clock reports itself
 * the way a scan does.
 */
export interface SchedulerPulse {
  /**
   * When the last pass ran. Absent means no pass has finished yet, which is the
   * ordinary state for the first tick after startup.
   */
  at?: number
  considered: number

  /**
   * How many came due on this pass. Separate from `fired` because a due schedule
   * whose dispatch was refused is not the same as nothing being due.
   */
  due: number
  fired: number

  /**
   * Why a pass did nothing, when the reason was not that nothing was due.
   */
  note?: string
  tickSeconds: number
}

/**
 * Text, pictures, or both; a send that is neither is refused. Each picture is a
 * base64 `data:` URL, at most six, inside the 20 MB body limit. Pictures that
 * cannot be decoded are left out, and a send none of whose pictures can be is
 * refused.
 */
export interface SendRequest {
  images?: string[]
  text?: string
}

/**
 * Who this session is parked on, and who is parked on it. Absent when neither.
 * `state` is `waiting_on_session` whenever `waitingOn` is not empty, otherwise
 * `has_waiters`.
 */
export interface SessionCoordination {
  state: string
  waitedOnBy: CoordinationWaitRow[]
  waitingOn: CoordinationWaitRow[]
}

/**
 * Present on exactly the row whose live process is the one
 * ~/.config/clawdline/coordinator.json registers — terminal, assistant, tty, pid,
 * start time and conversation all equal. `status` is always `online` here, because
 * the field is only attached to a matching live row.
 */
export interface SessionCoordinator {
  commands: SessionCoordinatorCommand[]
  label: string
  status: string
}

/**
 * One command in the Clawdfather panel. The list is the Swift app's fixed table
 * (Coordinator.swift `commands`), in its order. `reason` and `why` are present only
 * when `enabled` is false.
 */
export interface SessionCoordinatorCommand {
  enabled: boolean
  reason?: string
  token_effort: string
  token_effort_basis: string
  type: string
  why?: string
}

/**
 * The facts behind the status line under an open session. This daemon serves the
 * transcript-derived part the Swift app calls the summary, and the plan windows;
 * the working tree, context use, links, permission and fast mode are not read here
 * and their keys are absent.
 */
export interface SessionInfo {
  limits?: SessionLimits
  models: SessionModel[]
  session: SessionInfoSession
  usage?: SessionInfoUsage
}

/**
 * GET /v1/sessions/{id}/info. Kept off the session stream because answering reads
 * the session's record; the console holds an answer for a minute.
 */
export interface SessionInfoReply {
  info: SessionInfo
}

export interface SessionInfoSession {
  assistant?: Assistant
  cwd?: string
  id: string

  /**
   * The model the session is on, as its record last named it: the newest assistant
   * turn's model, or a `/model` switch made after it. Absent when the record says
   * nothing.
   */
  model?: string
  sessionId?: string

  /**
   * The same label the session list shows.
   */
  title?: string
}

/**
 * What the conversation has spent. For Claude it is the sum of every assistant turn
 * in the transcript and is absent when the transcript is larger than 8 MiB, because
 * a partial sum is not a total. For Codex it is Codex's own running total.
 */
export interface SessionInfoUsage {
  cacheRead: number
  cacheWrite: number

  /**
   * US dollars. Claude Code's own session total from its status-line cache when it
   * wrote one, otherwise these tokens at list price. Absent when neither is known,
   * which is always the case for Codex; also absent at exactly zero.
   */
  costUsd?: number
  input: number

  /**
   * The model the last counted turn named, as written.
   */
  model?: string
  output: number
  total: number
}

/**
 * One plan window, as the provider last described it.
 */
export interface SessionLimitWindow {
  /**
   * The window is spent: the provider refused a request on it, or reported 100% or
   * more.
   */
  hit: boolean

  /**
   * `5h`, `7d`, or the window's length for any other (`1d`, `90m`).
   */
  name: string

  /**
   * Unix seconds. Absent when the provider did not say.
   */
  resetsAt?: number

  /**
   * As the provider reported it, unrounded; it can exceed 100.
   */
  usedPercent: number
}

/**
 * The plan windows of the account this session's assistant runs on: an
 * account-level reading shared by every session of that assistant (the Swift app's
 * `AssistantQuota.machineLimits`), not this conversation's. An empty `windows` is
 * "nobody said", never 0%.
 */
export interface SessionLimits {
  /**
   * Unix seconds of the provider record the windows came from. Absent when nothing
   * has been read.
   */
  at?: number

  /**
   * Unix milliseconds when this daemon took the reading. A client holding readings
   * from several answers keeps the newest by this. Absent for a session with no
   * assistant.
   */
  readAtMs?: number
  windows: SessionLimitWindow[]
}

/**
 * The question on a waiting session's screen, as rows a finger can hit (the Swift
 * app's menuObject). Present only on a waiting session whose screen could be read
 * as a menu; a waiting row without it is a question drawn in a shape nothing
 * recognised. The row labels and details may be refilled from the session's own
 * transcript, but only once the screen proves which question it is showing; the
 * numbers, the caret, Submit and the steps are always the screen's.
 */
export interface SessionMenu {
  options: SessionMenuOption[]

  /**
   * The prose above the rows, or the question as the call asked it. Absent when it
   * could not be read.
   */
  question?: string

  /**
   * The number of the row the caret is on. Absent when it is on none of them — a
   * multi-select's button can hold it.
   */
  selected?: number

  /**
   * Where this question sits in a set of them, as the picker's tab bar draws it.
   * Absent for a lone question.
   */
  steps?: SessionMenuStep[]
  submit?: SessionMenuSubmit
}

/**
 * One row. `n` is the keystroke and not the position: the page sends that number to
 * `POST /v1/sessions/{id}/key`, and renumbering would make a button answer a
 * different question than its label says.
 */
export interface SessionMenuOption {
  /**
   * Whether a keystroke reaches this row (1…9). A row that cannot be answered is
   * drawn and not offered.
   */
  can: boolean

  /**
   * Only on a multi-select, where a row ticks rather than answers; present and
   * false is a real answer (the daemon writes it through its own wire type, since a
   * generated optional bool would drop false).
   */
  checked?: boolean

  /**
   * The prose under the label, joined.
   */
  detail?: string
  label: string
  n: number

  /**
   * The caret is on this row, so it is what a bare Return would confirm.
   */
  selected: boolean
}

/**
 * One question of a set, as the picker's tab bar names it.
 */
export interface SessionMenuStep {
  /**
   * What was chosen, once the picker's review screen names it.
   */
  answer?: string
  done: boolean
  label: string
}

/**
 * The button under a multi-select's rows. It has no number on screen; `POST /key`
 * takes the word `submit` for it.
 */
export interface SessionMenuSubmit {
  label: string
  selected: boolean
}

/**
 * One model this session's assistant can be switched to. A session's current model
 * is matched against `id` by prefix, so a dated id still finds its row; `name` is
 * what a reader is shown for it.
 */
export interface SessionModel {
  command: string
  id: string
  name: string
}

/**
 * One assistant session. Fields that cannot be supported are absent rather than
 * invented; a reader that handles absence handles this too.
 */
export interface SessionRow {
  assistant?: Assistant
  backend: Backend
  closeability: Closeability
  coordination?: SessionCoordination
  coordinator?: SessionCoordinator
  cwd?: string
  disposition?: WorkDisposition
  evidence: Evidence
  icon?: Icon
  id: string
  isClaude: boolean

  /**
   * What the session is called, by the Swift app's rungs (ITerm.swift
   * preferredDisplayLabel): a name typed in Clawdline (the Swift store's
   * config.json `session_titles`), the title of the task, handoff or Feature Root
   * Clawdline opened the tab for (orchestrator.json), the conversation's own title
   * (`/rename`, else `aiTitle`), Codex's thread name or an automatic title, Claude
   * Code's registry handle — the first that has something. Never a terminal
   * title. Absent when nothing names the session.
   */
  label?: string

  /**
   * What a working session says it is doing, read from its screen with the
   * assistant's own clock in it. Present while working; on a waiting session with a
   * menu it is instead that menu's revision (the Swift app's menuRevision), which
   * no row draws and which changes whenever the question does. The Swift app sends
   * it under this name and the row's height depends on it.
   */
  line?: string
  menu?: SessionMenu
  owed?: WorkOwed
  root_assignment?: RootAssignmentRecord

  /**
   * The assistant's own conversation id, when one was recovered from its command
   * line.
   */
  sessionId?: string

  /**
   * The commands this session left running in the background, newest first, at most
   * six. Absent rather than empty when there are none, as the Swift app sends it;
   * always absent for Codex, which keeps no record of them.
   */
  shells?: SessionShell[]
  state: SessionState
  tty?: string

  /**
   * Who the declaring session said will move it — a session id, or a person.
   */
  work_moved_by?: string

  /**
   * The session's own words for its state, present only when its declaration
   * decided `work_state` (then `work_provenance` is `self`).
   */
  work_note?: string

  /**
   * Whether that mover is a person. Absent unless the declaration decided the
   * state; present and false is a real answer.
   */
  work_person_needed?: boolean
  work_provenance?: WorkProvenance

  /**
   * Unix seconds: when that declaration was made.
   */
  work_since?: number
  work_state: WorkState
}

/**
 * One background command a session started and has not finished: its output file
 * has no ending written under it, and the session's transcript announced its id as
 * a background command. `at` is when it last printed something.
 */
export interface SessionShell {
  /**
   * Unix seconds.
   */
  at: number

  /**
   * The command line that started it, on one line. Absent when the two transcript
   * records it is joined from straddled a read.
   */
  command?: string

  /**
   * The last line it printed, clipped to 160 characters.
   */
  doing?: string

  /**
   * Claude Code's own id for it.
   */
  id: string

  /**
   * The description written beside the command, when there was one.
   */
  what?: string
}

/**
 * What the session appears to be doing. `unknown` is a real answer and is never
 * flattened into `idle`.
 */
export type SessionState =
    "working"
  | "waiting"
  | "idle"
  | "unknown"

export const SessionStateValues: readonly SessionState[] = ["working", "waiting", "idle", "unknown"] as const

export interface SessionsSnapshot {
  at: number
  scan: Scan
  sessions: SessionRow[]
}

/**
 * The keys to change. A null key is left as it is.
 */
export interface SettingsRequest {
  /**
   * A combination the shell can register (`cmd+shift+k`), or empty for none.
   */
  hotkey: string | null

  /**
   * Bundle identifiers separated by commas, or empty for every app.
   */
  scope_app: string | null
}

export interface SettingsSnapshot {
  /**
   * False before anything has been written. Every key then has the shell's default.
   */
  exists: boolean

  /**
   * The file's `hotkey`, or null when the file does not carry one as a string. Null
   * and empty both register nothing in this app: the Swift app is running and owns
   * option+space.
   */
  hotkey: string | null

  /**
   * Where the file is, whether or not it exists.
   */
  path: string

  /**
   * The file's `scope_app`, or null when absent — which the shell reads as
   * com.googlecode.iterm2. Empty is every app.
   */
  scope_app: string | null
}

/**
 * Whether the task has written a result yet. `settled` false is not a failure; it
 * means nothing has been written, which is the ordinary state of work still in
 * progress.
 */
export interface SettleResult {
  ok: boolean
  settled: boolean
  state?: TaskState
  task_id: string
}

/**
 * A new or adopted token, twice: here for a script, and in `Set-Cookie:
 * clawdline-next=…; Path=/; Max-Age=31536000; HttpOnly; SameSite=Strict` (plus `;
 * Secure` behind an HTTPS proxy) for a page.
 */
export interface SignedIn {
  ok: boolean
  token: string
}

export interface StartAssistant {
  availability: StartAvailability
  id: string
  label: string
}

/**
 * AssistantQuota.Availability. This daemon reads no quota, so it answers unknown.
 */
export type StartAvailability =
    "ok"
  | "low"
  | "exhausted"
  | "unknown"

export const StartAvailabilityValues: readonly StartAvailability[] = ["ok", "low", "exhausted", "unknown"] as const

/**
 * One directory a session can be started in. `id` is sixteen hex characters of the
 * path's SHA-256 and is the only part a client sends back; `path` is here so two
 * projects with one name can be told apart.
 */
export interface StartPlace {
  /**
   * When this place was last worked in, Unix seconds.
   */
  at: number
  icon?: Icon
  id: string
  label: string
  path: string
}

/**
 * GET /v1/places: recorded Claude Code folders, Codex rollouts and live sessions'
 * directories, deduplicated, still on disk, newest first, at most forty.
 */
export interface StartPlaceList {
  assistants: StartAssistant[]
  at: number
  places: StartPlace[]
}

/**
 * Whether the Swift app's store was read for this answer: `current`; `stale`, an
 * earlier reading carried because the newest one was half-written; or `unknown`,
 * nothing could be read. Unknown is never the same as empty.
 */
export type StoreReading =
    "current"
  | "stale"
  | "unknown"

export const StoreReadingValues: readonly StoreReading[] = ["current", "stale", "unknown"] as const

/**
 * One stored picture and the literal to paste into a reply to show it:
 * `<clawdline-image id="…">`.
 */
export interface StoredImage {
  byte_count: number
  expires_at: number
  height: number
  id: string
  marker: string
  media_type: string
  width: number
}

/**
 * The tab the task was opened in.
 */
export interface TaskChild {
  backend?: string
  sessionId?: string
  terminalId?: string
}

/**
 * `at` is when the answer was built. With `store` at `unknown` the list holds only
 * this daemon's own tasks, which is not the same as the machine having no others.
 */
export interface TaskList {
  at: number
  page: TaskPage
  store: StoreReading
  tasks: TaskRow[]
}

/**
 * Which finished tasks this answer carries. Unfinished ones ride on every page.
 */
export interface TaskPage {
  cursor: number
  fields: string
  finished: number
  limit: number

  /**
   * Where the next page starts. The Swift app sends null on the last page; here the
   * key is absent.
   */
  nextCursor?: number
  unfinished: number
}

/**
 * The session that asked for the task. `terminalId` is not stored: it is resolved
 * on every read against the sessions on screen — the parent task's child terminal
 * first, otherwise the one live session whose conversation is `sessionId` — and
 * is absent when that is not exactly one.
 */
export interface TaskRoot {
  assistant?: string
  label?: string
  sessionId?: string
  taskId?: string
  terminalId?: string
}

/**
 * One task. The camelCase keys are the Swift app's list projection, which the
 * copied console reads (`view/derive.js`: id, title, state, created, finishedAt,
 * child, root, usage). The four snake_case keys `task_id`, `project_dir`,
 * `created_at` and `claims` are this daemon's older names, kept beside them because
 * the Dashboard panel still reads them. The Swift app's `projectDir` is sent only
 * as `project_dir`: the generator gives both spellings one Go name, and the copied
 * console reads neither. `claims` is therefore always present here, where the Swift
 * app leaves it out when none were declared (`claims_declared` says which). Omitted
 * from the Swift projection because no page here reads them: worktree (its presence
 * is `isolation`), executor, completion_delivery, verification, landing,
 * landing_paths, terminal_intervention, released_claims, respawn_of, waiting_on.
 */
export interface TaskRow {
  artifacts?: string[]
  assistant: Assistant
  attachSession?: string
  attached?: boolean
  briefedAt?: number
  child?: TaskChild
  claims: string[]
  claims_declared: boolean

  /**
   * Unix seconds.
   */
  created: number

  /**
   * Unix seconds; the same instant as `created`.
   */
  created_at: number
  depth: number
  dir: string
  finishedAt?: number
  id: string
  isolation?: string
  kind: string
  model?: string
  permission: string
  project_dir: string
  reasoning_effort?: string
  resultVerifiedAt?: number
  root?: TaskRoot
  schedule_id?: string
  session_root?: boolean
  spawnedAt?: number
  state: TaskState
  task_id: string
  title: string
  untouched_claims?: string[]
  usage?: TaskUsage
  workItemId?: string
  workPhase?: string
}

export type TaskState =
    "queued"
  | "spawning"
  | "briefed"
  | "success"
  | "failure"
  | "timeout"
  | "cancelled"
  | "spawn_failed"

export const TaskStateValues: readonly TaskState[] = ["queued", "spawning", "briefed", "success", "failure", "timeout", "cancelled", "spawn_failed"] as const

/**
 * What the child spent. `costUsd` is absent where nothing priced it, which is
 * always the case for Codex.
 */
export interface TaskUsage {
  cacheRead: number
  cacheWrite: number
  costUsd?: number
  input: number
  model?: string
  output: number
  total: number
}

export interface TranscriptAction {
  command?: string

  /**
   * read or search.
   */
  kind: string
  name?: string
  path?: string
  query?: string
}

/**
 * What a Codex tool item recorded about itself: `called` for an MCP call with a
 * title, `explored` for a shell command Codex classified as reads and searches.
 */
export interface TranscriptActivity {
  actions: TranscriptAction[]

  /**
   * How long the item took. -1 when the record did not say, which the Swift app
   * sends as an absent key; 0 is a real, sub-millisecond duration and is drawn as
   * one.
   */
  durationMs: number
  kind: string

  /**
   * A called tool's result text, cut at 4,000 characters.
   */
  result?: string

  /**
   * inProgress, pending, completed or failed.
   */
  status?: string
  title?: string
}

/**
 * One thing in a conversation, in the shape the Swift app's `transcriptRows` writes
 * it. A tool call and what the tool returned both carry `role: tool`; only the call
 * names its tool. A call's `text` is the one line describing what it was asked to
 * do — a command, a path, a query — which is what a folded row shows as its
 * subject. An `AskUserQuestion` call carries its questions instead, after the
 * U+0001 `ask` U+0001 marker.
 */
export interface TranscriptEntry {
  activity?: TranscriptActivity

  /**
   * Pictures an assistant turn showed with a `<clawdline-image>` marker, or a
   * Clawdline session message carried. Resolved against this daemon's store and
   * then, read-only, the Swift app's.
   */
  artifacts?: ImageArtifact[]

  /**
   * Unix seconds. Absent when the record carried no timestamp this reader accepts.
   */
  at?: number

  /**
   * Exact edits: a Codex patch, or the whole file a Claude `Write` created. Absent
   * on every other entry.
   */
  fileChanges?: TranscriptFileChange[]

  /**
   * Images attached to a user turn. Absent when there were none: the Swift app
   * writes an explicit 0 on user rows, and a reader treats absence as that 0.
   */
  imageCount?: number
  notice?: TranscriptNotice

  /**
   * A complete Codex checklist update.
   */
  plan?: TranscriptPlanStep[]

  /**
   * user, assistant, peer (another Claude Code session), message (another session
   * through Clawdline), notice (Clawdline about a task) or tool.
   */
  role: string

  /**
   * The human-facing name of the session a peer or message row came from.
   */
  source?: string

  /**
   * Which assistant sent a Clawdline session message.
   */
  sourceAssistant?: string

  /**
   * How a peer or message row arrived: the peer's own mode, or `clawdline`.
   */
  sourceMode?: string
  text: string

  /**
   * The tool a call used. Absent on a tool's result and on prose.
   */
  tool?: string
}

export interface TranscriptFileChange {
  /**
   * The whole file, for an addition, a deletion or a Claude `Write`.
   */
  content?: string

  /**
   * add, delete, update or write, as the record spelled it; `change` when it did
   * not.
   */
  kind: string
  movePath?: string
  path: string
  unifiedDiff?: string
}

/**
 * A decoded Clawdline notice without its protocol, version and body — the Swift
 * app's `webObject`. Which fields are present depends on `kind`: task_finished,
 * workspace_overlap, file_wait_request, file_wait_release or handoff_receipt.
 */
export interface TranscriptNotice {
  ack_path?: string
  assistant?: string
  audience?: string

  /**
   * Present only when true.
   */
  child_may_still_write?: boolean

  /**
   * Present only when true.
   */
  claims_released?: boolean
  commit?: string
  handoff_id?: string
  kind: string
  note?: string
  notice_id?: string

  /**
   * task_finished only, where the decoder requires it, so absence there means 0.
   */
  outstanding?: number
  overlaps?: TranscriptNoticeOverlap[]
  paths?: string[]
  project_dir?: string
  reason?: string
  release_condition?: string
  repository?: string
  result_path?: string
  state?: string
  task?: TranscriptNoticeTask
  title?: string
  wait_id?: string
  waiter_session_id?: string
}

export interface TranscriptNoticeOverlap {
  path: string
  task: TranscriptNoticeTask
}

export interface TranscriptNoticeTask {
  id: string
  title: string
}

/**
 * `entries`, `signature` and `truncation` are the Swift app's transcript payload;
 * `evidence`, `path` and `note` say where the reading came from.
 */
export interface TranscriptPage {
  /**
   * Oldest first.
   */
  entries: TranscriptEntry[]
  evidence: Evidence
  id: string
  note?: string

  /**
   * Which file this was read from. A reading that cannot name its source is not
   * evidence.
   */
  path?: string

  /**
   * The record's size and modification time, `<bytes>-<unix seconds>`, and empty
   * when nothing was read. It changes whenever the entries could have.
   */
  signature: string
  truncation?: TranscriptTruncation
}

export interface TranscriptPlanStep {
  /**
   * pending, inProgress or completed — Codex app-server's spelling, not the
   * rollout's in_progress.
   */
  status: string
  step: string
}

/**
 * The newest entries were kept and older ones left out, because the whole page
 * would have passed its byte budget.
 */
export interface TranscriptTruncation {
  budgetBytes: number
  entriesOmittedCount: number

  /**
   * transcript_byte_budget.
   */
  reason: string
}

/**
 * The Swift app's `UsageQueryService` payload. The lossless `.json` export is this
 * object unwrapped, with every matched row, `truncated`, and no `pagination`.
 */
export interface UsageAnalytics {
  availability: AnalyticsAvailability
  breakdown: AnalyticsBreakdown[]
  bucket: string
  capabilities: AnalyticsCapabilities
  corrections: number
  coverage: AnalyticsCoverageSummary
  freshness: AnalyticsFreshness
  groupBy: string
  pagination?: AnalyticsPagination
  portfolio: AnalyticsPortfolio
  priceSnapshot: AnalyticsPriceSnapshot
  range: AnalyticsRange
  rangeFreshness: AnalyticsRangeFreshness
  rowCount: number
  rows: AnalyticsRow[]
  schemaVersion: number
  totals: AnalyticsSummary
  trend: AnalyticsTrendBucket[]

  /**
   * The `.json` export only.
   */
  truncated?: boolean
  unavailableDimensions: AnalyticsUnavailableDimensions

  /**
   * overview or agent_work; echoed only.
   */
  view: string
}

/**
 * A refused Usage read.
 */
export interface UsageAnalyticsRefusal {
  error: UsageAnalyticsRefusalBody
}

/**
 * The Swift app's refusal envelope, which the Usage page reads its code from.
 * Codes: bad_request, usage_analytics_busy (503, with Retry-After),
 * export_too_large (413), json_serialization_failed, ambiguous_project (409),
 * project_not_found (404).
 */
export interface UsageAnalyticsRefusalBody {
  code: string
  message: string
  request_id: string
}

/**
 * GET /v1/orchestrator/usage/analytics.
 */
export interface UsageAnalyticsReply {
  usage: UsageAnalytics
}

export interface UsageReport {
  at: number
  sessions: UsageRow[]

  /**
   * The sum of the rows that could be read. Rows carrying `evidence: none`
   * contribute nothing, so this can be smaller than the truth and never larger.
   */
  totalTokens: number
}

/**
 * One session's usage, as its own transcript records it. This is what the
 * transcript accounts for, which is a smaller claim than what the session spent:
 * one conversation's own turns cannot see work another model did on its behalf.
 */
export interface UsageRow {
  assistant?: Assistant
  evidence: Evidence
  id: string
  label?: string

  /**
   * How many assistant turns were counted. Absent for a source that reports a
   * cumulative total rather than per-turn figures.
   */
  messages?: number
  models: ModelUsage[]

  /**
   * Why a row could not be read. Present with `evidence: none`, and never alongside
   * a number.
   */
  note?: string
  totalTokens: number
}

/**
 * A refusal from this route. It is the ordinary refusal shape with one field added,
 * because `no_whisper` covers two different afternoons: `brew install whisper-cpp`
 * leaves a machine with the binary and no model, and a page told only "no whisper"
 * sends somebody to check the thing they already did.
 */
export interface VoiceRefusal {
  detail: string
  error: string

  /**
   * Only on `no_whisper`: `no_binary` or `no_model`.
   */
  reason?: string
}

/**
 * A recording, already in the one shape whisper.cpp takes. The resampling is done
 * in the browser because that is the one format question every browser can answer
 * about itself — what it just recorded — while this machine has no ffmpeg and
 * could not open an Opus file if it wanted to.
 */
export interface VoiceRequest {
  /**
   * Base64 of little-endian 16-bit mono PCM. A minute of it is about 2.6MB encoded.
   */
  audio: string

  /**
   * Must be 16000. Checked rather than resampled: a body that names 48000 has not
   * made a small mistake, it has sent something that would transcribe as a voice
   * three times too fast, and quietly resampling somebody's voice is a worse answer
   * than saying no.
   */
  rate: number
}

/**
 * What was said, and how long this machine took to read it. An empty `text` is an
 * answer and not a failure: whisper heard the recording and there were no words in
 * it, which happens to a pocket and to a room that went quiet.
 */
export interface VoiceResult {
  ms: number
  text: string
}

/**
 * What a finished row delivered, present only with `milestone_complete` or
 * `work_complete`. `scope` is `session` for a session's own delivery receipt and
 * `task` for the task that opened it; the landing fields are present only when a
 * broker-verified landing backs `work_complete`.
 */
export interface WorkDisposition {
  commit?: string
  evidence: string
  landedAt?: number
  receiptAt?: number
  scope: string
  target?: string
  targetCommit?: string
  taskId?: string
  title: string
}

/**
 * Something this session declared it is owed, beside whatever its work state is.
 */
export interface WorkOwed {
  moved_by?: string
  note: string
  person_needed: boolean
  provenance: string
  since: number
}

/**
 * Who decided a row's work state. `broker` means it was projected from what could
 * be read; `self` means the session's own declaration (the Swift store's
 * `session_self_states`) is what decided it.
 */
export type WorkProvenance =
    "broker"
  | "self"

export const WorkProvenanceValues: readonly WorkProvenance[] = ["broker", "self"] as const

/**
 * One projection of what this session needs, ranked so a reader can sort by it.
 * `unknown` outranks nothing and means the inputs were incomplete.
 */
export type WorkState =
    "ready"
  | "working"
  | "holding"
  | "waiting_you"
  | "waiting_session"
  | "unknown"
  | "milestone_complete"
  | "work_complete"

export const WorkStateValues: readonly WorkState[] = ["ready", "working", "holding", "waiting_you", "waiting_session", "unknown", "milestone_complete", "work_complete"] as const

export interface WorktreeCanonical {
  error: WorktreeIssue | null
  observedAt: string | null
  oid: string | null
  ref: string | null
  state: WorktreeObservationState
}

export type WorktreeClass =
    "active_in_use"
  | "landed_identical_residue"
  | "genuinely_unlanded"
  | "mixed_conflicted"
  | "task_owned_temporary"
  | "prunable_stale_metadata"
  | "unknown_incomplete_evidence"

export const WorktreeClassValues: readonly WorktreeClass[] = ["active_in_use", "landed_identical_residue", "genuinely_unlanded", "mixed_conflicted", "task_owned_temporary", "prunable_stale_metadata", "unknown_incomplete_evidence"] as const

/**
 * An assessment only. No route here acts on it.
 */
export interface WorktreeCleanup {
  blockers: WorktreeIssue[]
  eligible: boolean
  nextOwner: string | null
}

export interface WorktreeContext {
  createdAt: string | null
  currentStatus: string | null
  evidence: string
  finishedAt: string | null
  note: string | null
  originSession: WorktreeOrigin
  purpose: string | null
  startedAt: string | null
  state: string
}

/**
 * Each is null when any row it sums could not be read, or the observation failed or
 * was truncated. Null is never zero.
 */
export interface WorktreeCounts {
  active: number | null
  modified: number | null
  rows: number | null
  staged: number | null
  storageBytes: number | null
  unknown: number | null
  untracked: number | null
}

export interface WorktreeIssue {
  code: string
  message: string
}

/**
 * One Project's worktree lifecycle, as ProjectWorktreeLifecycleService.snapshotJSON
 * writes it. Before the first refresh it is `complete: false` with error
 * `not_observed`, which means nobody has looked yet, not that there is nothing.
 */
export interface WorktreeLifecycle {
  complete: boolean
  counts: WorktreeCounts
  error: WorktreeIssue | null
  observedAt: string | null
  project: WorktreeProjectRef
  repository: WorktreeRepository
  rows: WorktreeRow[]
  schemaVersion: number
  truncated: boolean
}

/**
 * GET /v1/projects/:id/worktrees and POST /v1/projects/:id/worktrees/refresh.
 */
export interface WorktreeLifecycleAnswer {
  projectWorktreeLifecycle: WorktreeLifecycle
}

export interface WorktreeLocal {
  error: WorktreeIssue | null
  head: string | null
  observedAt: string | null
  state: WorktreeObservationState
}

export type WorktreeObservationState =
    "current"
  | "stale"
  | "unknown"
  | "failed"

export const WorktreeObservationStateValues: readonly WorktreeObservationState[] = ["current", "stale", "unknown", "failed"] as const

export interface WorktreeOrigin {
  sessionId: string | null
  title: string | null
}

export interface WorktreeOwner {
  evidence: string
  sessionId: string | null
  taskId: string | null
  terminalId: string | null
  title: string | null
}

export interface WorktreeProjectRef {
  id: string
  label: string
}

export interface WorktreeRepository {
  canonicalPath: string
  id: string
  label: string
}

export interface WorktreeRow {
  active: boolean | null
  base: string | null
  branch: string | null
  canonicalTargetObservation: WorktreeCanonical
  classifications: WorktreeClass[]
  cleanup: WorktreeCleanup
  context: WorktreeContext
  head: string | null
  localObservation: WorktreeLocal
  owner: WorktreeOwner
  path: string
  status: WorktreeStatus
  storage: WorktreeStorage
  target: string | null
  worktreeId: string
}

export interface WorktreeStatus {
  complete: boolean
  modified: number | null
  staged: number | null
  untracked: number | null
}

export interface WorktreeStorage {
  bytes: number | null
  complete: boolean
  error: WorktreeIssue | null
  observedAt: string | null
}
