/*
 * Words this app says that the Swift app never did (design-decisions D35).
 *
 * The copied catalog, `public/strings/zh-Hant.json`, is the Swift app's and
 * stays byte for byte; a sentence it has no key for goes here instead, in the
 * two languages this machine's person reads, and nowhere else. Every one of
 * them is a place this app deliberately says more than the one it replicates:
 * the Swift app cut the same things and said nothing (docs/limits.md §3.2).
 *
 * Holes are `{name}`, as the copied catalog's are.
 */

const words = {
  en: {
    olderNotRead:
      "Earlier conversation was not loaded: this page reads only the last {window} of the record, and {bytes} before that were not read.",
    olderLeftOut: "Earlier conversation was not loaded: {count} older entries did not fit in one page ({budget}).",
    documentsListed: "{count} older documents are not in this list.",
    documentsWalked: "The search stopped after {entries} entries, so some folders were not looked through.",
    documentsTasks: "The folders of {count} older tasks were not searched.",
    stackStatusNotRun: "needs its status command",
    stackNothingDeclared: "declares no ports",
    stackUnknownTip:
      "Only this project's own status command can tell, and this app does not run a project's commands. Run it in a terminal in {root}.",
    stacksCommandsNotRun:
      "Only the ports in each .devstack.json are asked. Its commands (status, up, restart, down, logs) are not run from here: start, restart or read a stack in a terminal in its project.",
    stackNoAction: "Not run from here. Start or restart {name} in a terminal in its project.",
    stacksNone: "No project on this machine has a .devstack.json.",
    stacksFailed: "Could not read the server list.",
    stacksTruncated: "Some projects were not looked at; this list may be incomplete.",
    sessionGone: "The session in this address is no longer on this machine, so here is the list.",
    sessionNotStarted: "This session has not started a conversation yet. Send the first message and its contents will appear here.",
    sessionNotStartedShort: "Conversation not started yet",
    infoContext: "Context",
    infoContextUsed: "{used} of {window} tokens in the context",
    infoResetsInMinutes: "in {n} min",
    sessionLastActivity: "last activity {time}",
    sessionStateUnrecognizedList:
      "Clawdline read the screen but could not identify its state. Open this session to inspect it.",
    proposalNeedsYourDecision:
      "The system has no to-do it can reassess. Finishing work will not withdraw this proposal; answer it, or it will wait until expiry.",
    proposalNotNow: "Not now",
    proposalResolve: "Already done / no longer applies",
    proposalResolveSummary: "What was completed, or which premise no longer applies?",
    proposalResolveEvidence: "Source: file:line, command output, or daemon response",
    proposalResolveSubmit: "Record as resolved",
    imageMarkupTitle: "Mark what to change",
    imageMarkupHint: "Draw with one finger. Move or zoom with two.",
    imageMarkupCanvas: "Picture marking canvas",
    imageMarkupTools: "Picture tools",
    imageMarkupRedPen: "Red pen",
    imageMarkupMove: "Move",
    imageMarkupZoom: "Picture zoom",
    imageMarkupZoomOut: "Zoom out",
    imageMarkupZoomIn: "Zoom in",
    imageMarkupUndo: "Undo",
    imageMarkupCancel: "Cancel",
    imageMarkupDone: "Done",
    smartTitleButton: "Name with AI",
    smartTitleAction: "name this session with AI",
    smartTitleConfirmTitle: "Name this session with AI?",
    smartTitleConfirmSay:
      "Clawdline will send this session's requests and the assistant's latest reply to {assistant} for one small model turn, then save its answer as the session title. This uses that assistant's quota. Cancel to make no model call and edit the title yourself instead.",
    smartTitleWorking: "Naming…",
    smartTitleSaved: "Smart title saved.",
    smartTitleOutOfQuota:
      "{assistant} has no usage left on its account, so no title was changed. Wait for it to reset, or pick the other assistant under Settings → Auto-name new sessions and try again.",
    smartTitleFailed: "{assistant} did not return a usable title. No title was changed.",
    smartTitleNoNamer: "{assistant}, the naming assistant chosen in Settings, is not installed on this machine.",
    smartTitleConfirmSayAuto:
      "Clawdline will send this session's requests and the assistant's latest reply to Claude Code for one small model turn, and to Codex only if Claude Code has no usage left or is not installed. The answer is saved as the session title and uses the quota of whichever assistant answered. Cancel to make no model call and edit the title yourself instead.",
    smartTitleSavedBy: "Smart title saved, named by {assistant}.",
    smartTitleOutOfQuotaAll:
      "Claude Code and Codex both have no usage left on their accounts, so no title was changed. Try again once either one resets.",
    smartTitleNoNamerAll: "Neither Claude Code nor Codex is installed on this machine, so no title was changed.",
    sessionStop: "Stop current work (Esc)",
    sessionStopSent: "Esc sent. The session stops its current turn once it reads it.",
    sessionStateUnrecognizedDetail:
      "Clawdline read the screen but could not identify its state. Inspect the conversation below before deciding what to do.",
    sessionCountNotStarted: "{n} not started yet",
    transcriptTechnicalDetails: "Technical details",
    transcriptRetry: "Try again",
    transcriptRetrying: "Reading…",
    scheduleUnreadableJSON: "This schedule file is not a readable JSON object and was disabled.",
    scheduleInvalidSchema: "This schedule file has an invalid format and was disabled.",
    scheduleProjectUnavailable: "This schedule's project directory is currently unavailable, so it was disabled.",
    scheduleUnreadable: "This schedule file could not be read and was disabled.",
    schedulesHeading: "Schedules",
    schedulesListLabel: "Scheduled tasks",
    scheduleUntitled: "Untitled schedule",
    commandNoPlanner: "This machine has neither Claude Code nor Codex available to make a draft.",
    scheduleInvalid: "Invalid schedule",
    scheduleInvalidStatus: "Invalid",
    timelineSetPerProject: "Set per project",
    cloudChecking: "Checking this browser's Clawdline account…",
    cloudSignInLede: "Sign in to read your machines",
    cloudSignInFine:
      "Clawdline Cloud lists the machines paired with this browser and their sessions, and carries what you send them.",
    cloudConnecting: "Connecting to Clawdline Cloud…",
    cloudRetrying: "Clawdline Cloud did not answer ({code}). Trying again in {seconds} s.",
    cloudRetryingBrowserOffline: "This browser is offline. Trying again in {seconds} s.",
    cloudRetryingUnknown:
      "The connection between this browser and Clawdline Cloud was interrupted, but its cause could not be measured. Trying again in {seconds} s.",
    cloudFailed: "Could not reach Clawdline Cloud ({code}).",
    cloudRetry: "Try again",
    cloudRevoked: "This browser's device was revoked. Sign in again to read your machines.",
    cloudPairingLede: "Signed in, not paired yet",
    cloudPairingFine:
      "This browser holds no key for any machine on account {account} yet. Pair one from here: this page gives you a complete instruction to paste into an AI agent that can operate the target machine.",
    // Pairing from this page (`cloud/pair.ts`). The code is this browser's
    // offer; the machine is what hands the key over, so the person carries the
    // code there, and compares the two fingerprints both sides print.
    cloudPair: "Pair",
    cloudPairOne: "Pair {machine} with this browser",
    cloudPairStart: "Pair a machine",
    cloudPairTitle: "Pair {machine} with this browser",
    cloudPairTitleAny: "Pair a machine with this browser",
    cloudPairStatusUnpaired: "Status: this browser does not have this machine's key yet.",
    cloudPairWaysIntro: "Choose the direction that matches where you are now. Both finish with the same fingerprint check.",
    cloudPairFromMachineTitle: "Start on the machine",
    cloudPairRecommended: "Recommended after install",
    cloudPairFromMachineWhen: "Use this while you are at the machine or already connected to its terminal.",
    cloudPairFromMachineStep1: "Run the command below on that machine. It prints a one-time link.",
    cloudPairFromMachineStep2: "Open that link in this browser. The pairing screen appears here.",
    cloudPairFromMachineSuccess: "Done means both screens show the same machine fingerprint. If they differ, stop using that pairing.",
    cloudPairFromBrowserTitle: "Start in this browser",
    cloudPairFromBrowserWhen: "Use this when the machine is reachable only over SSH or another terminal.",
    cloudPairFromBrowserStep1: "Generate one complete agent instruction here, then paste it into an AI agent that can operate that machine.",
    cloudPairFromBrowserStep2: "Keep this page open while the machine answers.",
    cloudPairFromBrowserSuccess: "Done means the browser fingerprint printed by the machine and the machine fingerprint shown here both match.",
    cloudPairGenerate: "Generate the agent instruction",
    cloudPairWhy:
      "Signing in is not enough to read a machine: the machine hands its key over itself, to a code it was given on the machine. That is what keeps an account password from being a way into your terminals.",
    cloudPairAsking: "Asking Clawdline Cloud for a pairing code…",
    cloudPairRun: "Paste this whole instruction into an AI agent that can operate {machine}:",
    cloudPairRunAny: "Paste this whole instruction into an AI agent that can operate the machine to pair:",
    cloudPairTargetAny: "the machine to pair",
    cloudPairAgentPrompt:
      "Complete Clawdline Cloud pairing on the target machine {machine}. First verify that the machine you are operating is that exact target. If it is not, use existing authorized access to connect to it or hand this task to an agent running there; do not run the command on the current machine.\n\nOn the target machine, run this one-time command exactly once:\n{command}\n\nTreat the offer as a short-lived, one-use secret: do not decode, edit, store, or repeat it in your reply. When it succeeds, run `clawdline cloud devices` on that same machine, compare the printed browser and machine fingerprints with the browser, and report the result without the offer.",
    cloudPairSettings:
      "A machine with Clawdline's settings window can take the part after -offer in its field for the browser's pairing code instead.",
    cloudPairCopy: "Copy for AI agent",
    cloudPairCopied: "Agent instruction copied.",
    cloudPairCopyFailed: "This browser would not copy it. Select the complete instruction and copy it by hand.",
    cloudPairYourKey: "This browser's fingerprint: {fingerprint}",
    cloudPairYourKeyCheck:
      "When the machine finishes, it prints a fingerprint on its browser line. It must be this one.",
    cloudPairExpires: "The code works until {time}.",
    cloudPairWaiting: "Waiting for the machine to answer…",
    cloudPairStopped: "Stopped waiting. The code still works until {time}; nothing here can withdraw it.",
    cloudPairStoppedEarly: "Stopped waiting.",
    cloudPairDone: "Paired. This browser now holds {machine}'s key.",
    cloudPairMachineKey: "{machine}'s fingerprint: {fingerprint}",
    cloudPairMachineKeyCheck:
      "The machine printed its own on its machine line; the two must be the same. If they are not, the code reached another machine: do not use this pairing.",
    cloudPairOther: "The machine that answered is {other}, not {machine}. {other} is the one paired.",
    cloudPairReload: "Reload and read it",
    cloudPairExpired: "The code ran out before the machine answered. Nothing was paired.",
    cloudPairAgain: "New code",
    cloudPairRefused:
      "That was not this browser's to finish ({code}): the pairing belongs to another account or was already used. Nothing was paired.",
    cloudPairFailed: "Pairing did not finish ({code}). If the machine printed a reason, that one says more.",
    cloudPairLinkLede: "This page was opened from a machine's pairing link",
    cloudPairLinkFine:
      "Pairing hands that machine's key to this browser. Answer only a link you just took from a machine of your own.",
    cloudPairLinkGo: "Pair with it",
    cloudPairLinkWaiting: "Answered. Waiting for the machine to hand over its key…",
    cloudPairLinkExpired:
      "That link has run out: a machine's link lasts about three minutes. Pair from the machine list instead, whose code lasts longer and says until when.",
    cloudPairLinkBad: "That is not a pairing link this page can read ({code}).",
    cloudMachineSessionsUnread: "its sessions cannot be read here",
    cloudMachineSessionsUnknown: "sessions not known yet",
    cloudMachineActions: "Actions for {machine}",
    cloudMachineID: "ID {id}",
    cloudMachinePlatformMac: "macOS",
    cloudMachinePlatformLinux: "Linux",
    cloudMachinePlatformLinuxAWS: "Linux on AWS",
    cloudMachinePlatformUnknown: "platform not readable here",
    cloudMachineSeen: "last seen {time}",
    cloudMachineSeenAt: "last seen {time}",
    cloudMachineSeenUnknown: "last seen not known here",
    devicesPairHelp: "Press Pair: this page gives you a complete instruction to paste into an AI agent that can operate that machine.",
    cloudDeviceLimit:
      "Account {account} already has {limit} viewer devices ({tier}). Removing one from this page is not in this version.",
    cloudInstallLede: "Add Clawdline to the Home Screen first",
    cloudInstallFine:
      "On an iPhone or iPad, the keys a Safari page makes stay in Safari and cannot move into the Home Screen app. Add this page to the Home Screen, open it from there, and sign in there.",
    cloudMachinesLede: "Choose a machine",
    cloudMachinesFine: "Account {account} · this browser {device}",
    cloudMachinesWaiting: "Waiting for the machines on this account to report in…",
    cloudMachinesNone: "No machine on this account has reported in yet.",
    cloudMachinesRefusedSignIn: "Clawdline Cloud refused the machine list ({code}). Sign in again.",
    cloudMachinesRefusedPair:
      "This browser could not read the machine data in the list ({code}). Pair the machine with this browser again.",
    cloudMachinesRefusedRetry:
      "The machine list did not answer ({code}). Check this browser's connection and try again.",
    // Two different things had one sentence between them. The copied catalog's
    // `webEmptyWaitTitle` ("Waiting for the app") is the honest one for a page
    // with no line to anything; it was also being said to a page whose line is
    // up and whose machine simply has not stated its list yet, which is a
    // different fact and a different thing to do about it.
    sessionsListWaitTitle: "Waiting for this machine's list",
    sessionsListWaitHint: "The line is up. This machine has not said yet which sessions it has.",
    sessionsListIncompleteTitle: "This machine's list is incomplete",
    sessionsListUnansweredTitle: "The session list did not answer",
    screenSessionGone: "This session is gone. Close the screen and return to the session list.",
    screenForbidden: "This page may not read the screen. Open the local console on that machine.",
    screenUnanswered: "Clawdline did not answer the screen read. Check the connection and try again.",
    schedulePlacesUnanswered: "The place list did not answer. Check this browser's connection to Clawdline and try again.",
    scheduleMachineField: "Machine",
    schedulePermissionField: "Permission",
    schedulePermissionDefault: "This machine's default",
    schedulePermissionAsk: "Ask me at every step",
    schedulePermissionEdits: "May edit files directly",
    schedulePermissionFull: "Full permission (never asks)",
    schedulePermissionFullWarning:
      "With full permission, each run may run any command and change any file without asking, while nobody is watching.",
    scheduleMachineOffline: "{machine}: offline (last seen {time})",
    scheduleMachineUnread: "{machine}: offline or unreadable",
    scheduleMoving: "Moving to {machine}…",
    scheduleMoved: "Moved to {machine}.",
    scheduleMoveWebhookMoved: "Its webhook moved with it to {machine}, and its URL is unchanged.",
    scheduleMoveWebhookLeftDisabled:
      "Its webhook was disabled, so it did not move; generate a new one on {machine} if you need one.",
    scheduleMoveHookMoveFailed:
      "Clawdline Cloud did not move the webhook, so the schedule was not moved: it stays on {source} and its webhook is as it was. {why}",
    scheduleMoveHookBindFailed:
      "{machine} did not take the webhook, so the move was undone: the schedule stays on {source}. If Clawdline on {machine} is older than webhook binding, update it, then move again. {why}",
    scheduleMoveHookStranded:
      "The webhook of “{title}” is on {machine} and paused: calls to it run nothing. To fix it, open this schedule's webhook, disable it and generate a new one (its URL changes).",
    scheduleMoveCopyLeft: "The copy on {machine} could not be deleted: it is there, switched on. Delete it on {machine}.",
    scheduleMoveSourceLeftDisabled: "The schedule on {source} could not be switched back on: it is there, disabled. Switch it on.",
    scheduleMoveTargetOffline: "{machine} is offline, so the schedule was not moved. Move it once that machine is back.",
    scheduleMoveTargetOutdated:
      "Clawdline on {machine} is too old to say which repository each project clones, so the schedule was not moved. Update Clawdline on {machine}, then move it.",
    scheduleMoveSourceOutdated:
      "Clawdline on {machine} is too old to say which repository this project clones, so the schedule was not moved. Update Clawdline on {machine}, then move it.",
    scheduleMoveNoOrigin:
      "“{project}” has no origin remote, so there is nothing to find it by on another machine. Give it an origin, or make a new schedule on the other machine.",
    scheduleMoveSourceUnlisted:
      "“{project}” is no longer in {machine}'s project list, so this schedule cannot be switched off there to move it. Open the project on {machine} once, then move it.",
    scheduleMoveNoProject: "{machine} has no project cloned from {repo}. Clone it there and open it once, then move the schedule.",
    scheduleMoveWebhookUnknown:
      "Whether “{title}” has a webhook could not be read on {machine}, so it was not moved. Try again.",
    scheduleMoveSpent:
      "“{title}” ran once and is done; a copy would run it again. Make a new schedule on the other machine instead.",
    scheduleMoveTargetTooOld:
      "Clawdline on {machine} is too old to take the settings this schedule carries. Update Clawdline on {machine}, then move it.",
    scheduleMoveHookStale:
      "Clawdline Cloud found the webhook changed while it was being moved, so it was not switched on. Move the schedule again.",
    scheduleMovePathRewritten: "The path in the first message now reads {path}.",
    scheduleMoveNotStarted: "{source} did not switch the schedule off, so nothing was moved. {why}",
    scheduleMoveCreateFailed: "{machine} refused the copy, so the schedule stays on {source} as it was. {why}",
    scheduleMoveCreateFailedDisabled:
      "{machine} refused the copy, and the schedule on {source} could not be switched back on: it is there, disabled. {why}",
    scheduleMoveDeleteFailed:
      "The schedule now runs on {machine}. The old copy is still on {source}, disabled; delete it there. {why}",
    cloudMachineSessions: "{count} sessions",
    cloudAccessProblem:
      "Machine {machine}'s data could not be read in this browser ({code}). Pair that machine with this browser again; if it still cannot be read, sign in again.",
    cloudSwitch: "Other machines",
    cloudCurrentMachine: "Current machine",
    cloudManageMachines: "Manage machines",
    cloudConnRetry: "Try again",
    cloudForget: "Forget",
    cloudForgetOne: "Forget {machine}",
    cloudForgetTitle: "Forget {machine}?",
    cloudForgetAsk:
      "{machine} is removed from this account. This cannot be undone from here: the machine comes back only if you sign it in again on the machine itself, and it comes back as a new machine with a new id.",
    cloudForgetAskCurrent: "This machine reported in a moment ago. Forgetting it stops its connection now.",
    cloudForgetAskStale: "This machine has not reported in for a while.",
    cloudForgetAskUnknown: "This machine has never reported in where this browser could see it.",
    cloudForgetHonest:
      "Routing stops now. A device that already holds the master key can still open ciphertext it recorded earlier; key rotation happens lazily.",
    cloudForgetting: "Forgetting {machine}…",
    cloudForgotten: "{machine} was forgotten. It is no longer on this account.",
    cloudForgottenRow: "forgotten",
    cloudForgetSaid: "Clawdline Cloud said: {note}",
    cloudForgetHonestUnread:
      "Clawdline Cloud did not say what this does to keys already handed out, so this page does not say it either.",
    cloudForgetRefused:
      "Clawdline Cloud refused to forget {machine} ({code}). This browser is not signed in to that account any more. Nothing was changed.",
    cloudForgetAbsent: "This account has no machine {machine} ({code}). Nothing was changed.",
    cloudForgetUnreadable:
      "Clawdline Cloud's answer about forgetting {machine} could not be read ({code}), so it is not known whether it was forgotten. Reload this page before asking again.",
    // Renaming a machine. It is an account write like forgetting one and it is
    // asked the same way, but it is not destructive, so what it says after is
    // about where the new name has and has not arrived yet.
    cloudRename: "Rename",
    cloudRenameOne: "Rename {machine}",
    cloudRenameTitle: "Rename {machine}?",
    cloudRenameAsk:
      "This changes what {machine} is called on this account, for every browser signed in to it. It changes nothing on the machine itself.",
    cloudRenameLater:
      "This list is what the machines themselves last said about themselves, so it goes on showing the old name until this one reports in again.",
    cloudRenameField: "New name",
    cloudRenaming: "Renaming {machine}…",
    cloudRenamed: "{machine} is called {name} on this account now.",
    cloudRenameRefused:
      "Clawdline Cloud refused to rename {machine} ({code}). This browser is not signed in to that account any more. Nothing was changed.",
    cloudRenameAbsent: "This account has no machine {machine} ({code}). Nothing was changed.",
    cloudRenameUnreadable:
      "Clawdline Cloud's answer about renaming {machine} could not be read ({code}), so it is not known whether the name was changed. Reload this page and look at the list before asking again.",
    cloudRenameTooLong: "A machine's name is at most {max} characters on this account.",
    cloudBlocked: "This console was built for {origin} and is being served from {here}, so it does not connect.",
    // The Devices page's own sentence about the list under it. The copied
    // catalog has one (`webDevicesLede`) and it describes an account; only one
    // of the two consoles here has an account's list to show, so the other
    // says what it does have (`legacy/devices-bridge.ts`).
    devicesLedeAccount:
      "The machines on this account, their status, and whether this browser can read them.",
    devicesLedeThisMachine:
      "Only the machine serving this page. A console served by the daemon reaches no other machine; which machines are on your account is answered by the Clawdline Cloud console.",
    devicesThisMachine: "This machine",
    signedInTitle: "Signed in to this machine",
    signedInLede:
      "Browsers opened with clawdline open, devices paired with a code, and devices signed in with the password. Revoking one refuses its next request.",
    signedInThisWindow: "This window uses this machine's own key. It is not in this list and cannot be revoked here.",
    signedInNone: "Nothing but this machine itself is signed in.",
    signedInPassword: "A password is set: whoever knows it can sign in another device.",
    signedInCapsRead: "Read only",
    signedInCapsSend: "Read and send",
    signedInSince: "Signed in {time}",
    signedInLastSeen: "Last used {time}",
    signedInNeverSeen: "Not used since the daemon started",
    signedInRevoke: "Revoke",
    signedInRevokeOne: "Revoke {name}",
    signedInRevokeAsk:
      "Revoke {name} ({id})? Whatever is signed in with it is refused from its next request and has to be signed in again.",
    signedInRevokeConfirm: "Revoke it",
    signedInCancel: "Cancel",
    signedInRevoked: "Revoked {name}.",
    signedInFailed: "Could not read who is signed in: {why}",
    signedInRevokeFailed: "{name} was not revoked: {why}",
    signedInThisBrowser:
      "This browser is signed in as a device of its own. The full list is shown only in this machine's app window, or by clawdline devices in a terminal.",
    signedInSignOut: "Sign this browser out",
    signedInSignOutAsk:
      "Sign this browser out? Its key is revoked now; to come back, sign it in again with clawdline open or a pairing code.",
    signedInSignOutConfirm: "Sign out",
    signedInSignOutFailed: "This browser was not signed out: {why}",
    cloudMisdeclared: "This console's Clawdline Cloud declaration cannot be used: {reason}",
    cloudNotCarried: "This cannot be done over Clawdline Cloud yet. Do it on the machine itself.",
    todosReadFailed: "Could not load",
    todosRefreshFailed: "Refresh failed",
    todosRetrying: "Retrying…",
    todosRetryTip: "The last read of these to-dos failed: {reason}. Tap to try again.",
    cloudPastUnavailable:
      "This machine cannot list its earlier sessions over Clawdline Cloud yet (it does not answer past-sessions), so none can be picked up from here. Pick it up on the machine, or start a new session here.",
    sendUnknown: "Not known whether this reached the machine ({code}).",
    sendUnsubmitted:
      "This was typed into the session's input line on the machine, but Enter was not pressed ({code}). Press Enter there, or clear it; sending it again would type it twice.",
    sendLook: "Look",
    sendLookTip: "Read the conversation on the machine again: if this is there, the card goes.",
    sendLooking: "Looking…",
    sendAbsent: "Not in the conversation on the machine ({code}).",
    sendAgain: "Send again",
    sendAgainTip: "If the first attempt reached the machine after all, it is not typed a second time.",
    sendInterrupted: "This page was reloaded while this was being sent, so it is not known whether it reached the machine.",
    sendKeptWords:
      "This page kept the words when it was reloaded, but not the pictures, so this one cannot be sent again from here.",
    menuUnknown: "Not known whether that answer reached the machine. Waiting for the session to update.",
    menuChooseAgain: "Choose again",
    menuUnreadSay:
      "Claude Code is showing a menu on that machine, and Clawdline could not read its choices from the screen.",
    menuUnreadHow:
      "*Sending a message will not answer it.* Open the live screen to see what it asks, or cancel the menu (the same as pressing Esc there) and then say your answer in the message box.",
    menuCancel: "Cancel this menu (Esc)",
    menuCancelSent: "Esc sent. Once the menu has closed, say your answer in the message box.",
    menuTicked: "Ticked. Nothing is sent until you press Submit.",
    newBuild: "A newer Clawdline is being served. This page is still the older one.",
    newBuildReload: "Reload",
    menuMoved: "The question changed before the answer landed, so nothing was typed. Read the new question and choose again.",
    menuUnverified: "This machine cannot check which question an answer is for over Clawdline Cloud, so menus are answered on the machine itself.",
    // The Links sheet says which kind of nothing it found. The copied catalog
    // has one sentence for an empty list and one for a failed read, and no way
    // to say that the list is right and only the deploy could not be named —
    // which is the distinction between a project with no CI and a machine
    // whose git is wedged.
    linksNotRepository: "Not a git repository, so nothing here could name a workflow run. Everything else on this list was read.",
    linksNoRemote: "This repository has no origin remote, and a workflow run is named after one, so no deploy could be found. Everything else on this list was read.",
    linksRemoteNotGitHub: "This repository's origin is not on GitHub, and only a GitHub remote names a workflow run here, so no deploy could be found.",
    linksGitUnreadable: "git would not answer here ({reason}), so whether this project has a deploy is unknown — which is not the same as no.",
    linksGitMissing: "there is no git on this machine",
    linksGitTimeout: "it did not answer in time",
    linksGitFailed: "it refused",
    linksGitTooLarge: "it said more than this reads",
    // The fifth kind of nothing, and the one that had no sentence at all: the
    // repository *is* on GitHub, git answered, and the tool that polls the
    // workflow runs still produced no row. That tool writes down why; until
    // now nothing read the key, so a person was shown a blank cell beside a
    // file that had been explaining itself for days.
    linksDeployNoRun:
      "The status line's tool has no workflow run to show for this repository (it wrote `{state}`). {reason}",
    linksDeployNoPage:
      "The status line's tool says this repository's newest workflow run is `{state}` and gave no page to open it on, so it is not a row here. {reason}",
    linksDeployNoFile:
      "This repository is on GitHub and nothing has written a workflow reading for it on this machine — so there is no deploy row because nobody is looking, not because there is no run. It is the status line's command that writes these, not this app.",
    linksDeployUnreadable:
      "There is a workflow file for this repository on this machine and it could not be read as one small JSON object, so whether there is a deploy is unknown — which is not the same as no.",
    linksDeployRunningStale:
      "The status line's tool last said a deploy was running and has not written anything since, for longer than any deploy here is allowed to go quiet — so it is not drawn as running. The deploy most likely finished or was stopped without the tool recording how.",
    linksDeployBecause: "Its reason: {reason}.",
    linksDeployNoWhy: "It did not say why.",
    // That tool's own words for having nothing to show (`gh-run-status.py`).
    // The list is its to grow, so an unknown one is said as it was written
    // rather than swallowed — the whole shape this section exists to end.
    linksDeployWhyNoGh: "there is no `gh` command on this machine to ask GitHub with",
    linksDeployWhyNoBranch: "it could not get a branch name here, so there was nothing to look up",
    linksDeployWhyGhFailed: "`gh` did not answer — not signed in, timed out, or refused",
    linksDeployWhyNoRuns: "this branch has no workflow run at all",
    linksDeployWhyWorkflowDisabled:
      "that workflow is disabled, so its last failure will never be replaced and is not news",
    linksDeployWhyStaleFail:
      "the last run failed long enough ago that it stopped counting as the current state",
    linksDeployWhyUnknown: "That tool gave a reason this app does not know: `{why}`.",
    linksDeployWhen: "That tool last wrote this down: {when}.",
    linksTruncated: "More addresses were found than this list carries; the rest are not shown.",
    // The swipe. A confirmation reached from the list has to name what it
    // would act on: "this session" is enough beside the conversation and
    // nothing at all beside thirteen rows.
    endNamedTitle: "Close {session}?",
    endWorkChecking: "Checking this Session's unfinished Board items…",
    endWorkCompletedSummary: "Completed {work} Board items and {todos} TODOs",
    endWorkOpenHeading: "Still unfinished",
    endWorkBoardLabel: "Board",
    endWorkTodoLabel: "TODO",
    endWorkNoOpen: "No unfinished Board items or TODOs.",
    endWorkCloseUnknown: "Clawdline cannot confirm whether this Session is ready to close yet.",
    endWorkReadyToClose: "If nothing outside Clawdline remains to deliver, this Session is now safe to close.",
    endWorkSafeToClose: "Clawdline has verified that this Session is safe to close.",
    endWorkClose: "Close Session",
    endWorkConfirmClose: "Close safely",
    endWorkTruncated: "More Session work exists than this reminder could list.",
    endWorkUnreadable: "Clawdline could not read this Session's unfinished Board items. Review its Session to-dos before closing it.",
    swipeCloseAction: "Close Session",
    swipeEndLabel: "Close {session}",
    brokerWork: "Dispatched by Clawdline",
    providerWork: "Spawned by the assistant",
    brokerTasksUnknown: "dispatched work not known yet",
    agentsNoRecord: "not recorded yet",
    agentsUnknown: "not known yet",
    bgShellOne: "1 background shell",
    bgShellMany: "{n} background shells",
    bgAgentRunningOne: "1 subagent running",
    bgAgentRunningMany: "{n} subagents running",
    bgAgentListedOne: "1 subagent",
    bgAgentListedMany: "{n} subagents",
    bgAgentUnknown: "subagents ?",
    bgTitle: "Background work",
    bgOpen: "See the background shells and subagents",
    bgClose: "Close",
    bgShellsNone: "No background shell is running.",
    agentsUnreadable: "could not be read",
    agentsUnrecognized: "format not recognized",
    agentsTruncated: "{count} older items not shown",
    projectsTitle: "Projects",
    projectsLede: "Directories an assistant has actually been run in, and that are still there.",
    projectsBack: "‹ Projects",
    projectsRepositoryLifecycle: "Repository lifecycle",
    projectsWorktrees: "Worktrees",
    projectsRefreshObservation: "Refresh observation",
    projectsLifecycleBoundary:
      "Read-only overview. Refresh asks the owning machine for one bounded observation. Cleanup is intentionally unavailable in a browser.",
    projectsDeliveredNotLanded: "Delivered, not landed",
    projectsUnattributedWorktrees: "Unattributed worktrees",
    pushCloudReached: "Notifications are on: {machines} will notify this device.",
    pushCloudUnreached: "{machines} did not take it this time ({why}); this page tries again the next time it opens.",
    pushCloudNoMachine:
      "Notifications are on here, but no machine on this account has taken them yet; this page tries again the next time it opens.",
    pushCloudOffUntold: "This device no longer gets notifications, but {machines} could not be told: {why}",
    restoreCardTitle: "{n} sessions were open before the last restart",
    restoreCardTitleOne: "1 session was open before the last restart",
    restoreCardHint: "A restart or crash closed them. You can reopen them and carry on with the same conversations.",
    restoreCardOpen: "Review and restore",
    restoreSheetTitle: "Sessions open before the restart",
    restoreSheetSay: "Ticked sessions reopen in the same folder with the same assistant, continuing their conversation.",
    restoreLastSeen: "last seen {time}",
    restoreGo: "Restore {n} selected",
    restoreGoing: "Restoring…",
    restoreDismissAll: "Skip all",
    restoreDismissing: "Skipping…",
    restoreCancel: "Cancel",
    restoreDone: "Done",
    restoreOpened: "Opened.",
    restoreOpening: "Opening…",
    restoreFailedNotRestorable: "Not on offer any more: it is open now, or was already restored or skipped.",
    restoreFailedPlaceUnavailable: "Its folder is no longer one this machine can open.",
    restoreFailedNotFound: "The assistant no longer lists this conversation for its folder.",
    restoreFailedOpen: "The terminal could not open it.",
    restoreFailedBusy: "Other sessions were being opened. Try again.",
    restoreFailedUnknown: "Did not open.",
    restoreFailedSaid: "Did not open: {why}",
    restoreRefused: "The machine did not take this: {why}",
    restoreUnknownOutcome: "No answer came back, so whether these opened is not known. The list below is re-read.",
  },
  "zh-Hant": {
    olderNotRead: "更早的對話沒有載入：這一頁只讀對話記錄的最後 {window}，前面還有 {bytes} 沒有讀。",
    olderLeftOut: "更早的對話沒有載入：一頁最多 {budget}，比較舊的 {count} 則沒有放進來。",
    documentsListed: "還有 {count} 份比較舊的文件不在這份清單上。",
    documentsWalked: "搜尋在 {entries} 個項目後停下，有些資料夾沒有看完。",
    documentsTasks: "比較舊的 {count} 個工作的資料夾沒有搜尋。",
    stackStatusNotRun: "要跑它的 status 才知道",
    stackNothingDeclared: "沒有宣告 port",
    stackUnknownTip: "只有這個專案自己的 status 指令知道狀態，而這個 app 不執行專案的指令。請在 {root} 的終端機裡跑。",
    stacksCommandsNotRun:
      "這裡只探測 .devstack.json 宣告的 port，不會執行檔案裡的指令（status、up、restart、down、logs）：要啟動、重啟或看紀錄，請在那個專案的終端機裡自己跑。",
    stackNoAction: "這裡不會執行指令。請在 {name} 專案的終端機裡啟動或重啟。",
    stacksNone: "這台機器上的專案都沒有 .devstack.json。",
    stacksFailed: "讀不到伺服器清單。",
    stacksTruncated: "有些專案沒有看完，這份清單可能不完整。",
    sessionGone: "網址裡的那個 session 已經不在這台機器上了，先回到清單。",
    sessionNotStarted: "這個 session 還沒有開始對話。送出第一則訊息後，內容就會顯示在這裡。",
    sessionNotStartedShort: "對話還沒開始",
    infoContext: "Context",
    infoContextUsed: "context 裡有 {used} / {window} tokens",
    infoResetsInMinutes: "{n} 分鐘後",
    sessionLastActivity: "上次活動：{time}",
    sessionStateUnrecognizedList: "Clawdline 已讀到畫面，但無法辨認狀態。請開啟這個 session 查看。",
    sessionStateUnrecognizedDetail: "Clawdline 已讀到畫面，但無法辨認狀態。決定下一步前，請查看下方對話。",
    sessionCountNotStarted: "{n} 個還沒開始對話",
    transcriptTechnicalDetails: "技術細節",
    transcriptRetry: "再試一次",
    transcriptRetrying: "讀取中…",
    scheduleUnreadableJSON: "這個排程檔不是可讀取的 JSON 物件，已停用。",
    scheduleInvalidSchema: "這個排程檔的內容不符合格式，已停用。",
    scheduleProjectUnavailable: "這個排程指定的專案資料夾目前無法使用，已停用。",
    scheduleUnreadable: "無法讀取這個排程檔，已停用。",
    schedulesHeading: "排程",
    schedulesListLabel: "排定的工作",
    scheduleUntitled: "未命名排程",
    commandNoPlanner: "這台機器沒有可用的 Claude Code 或 Codex，無法產生草稿。",
    scheduleInvalid: "無效的排程",
    scheduleInvalidStatus: "無效",
    timelineSetPerProject: "依專案設定",
    cloudChecking: "正在確認這個瀏覽器的 Clawdline 帳號…",
    cloudSignInLede: "登入後就能讀取你的機器",
    cloudSignInFine: "Clawdline Cloud 會列出和這個瀏覽器配對過的機器與它們的 session，也會把你從這裡送出的東西帶過去。",
    cloudConnecting: "正在連上 Clawdline Cloud…",
    cloudRetrying: "Clawdline Cloud 沒有回應（{code}），{seconds} 秒後再試。",
    cloudRetryingBrowserOffline: "這個瀏覽器目前沒有網路連線，{seconds} 秒後再試。",
    cloudRetryingUnknown: "這個瀏覽器與 Clawdline Cloud 的連線中斷，但目前量不到原因，{seconds} 秒後再試。",
    cloudFailed: "連不上 Clawdline Cloud（{code}）。",
    cloudRetry: "再試一次",
    cloudRevoked: "這個瀏覽器的裝置已被撤銷，請重新登入。",
    cloudPairingLede: "已登入，但還沒配對",
    cloudPairingFine: "這個瀏覽器還沒有帳號 {account} 任何一台機器的金鑰。從這裡配對：這一頁會產生一段完整指示，讓你直接貼給能操作目標機器的 AI Agent。",
    cloudPair: "配對",
    cloudPairOne: "把 {machine} 和這個瀏覽器配對",
    cloudPairStart: "配對一台機器",
    cloudPairTitle: "把 {machine} 和這個瀏覽器配對",
    cloudPairTitleAny: "把一台機器和這個瀏覽器配對",
    cloudPairStatusUnpaired: "目前狀態：這個瀏覽器還沒有這台機器的金鑰。",
    cloudPairWaysIntro: "依你現在人在哪裡選一條路；兩條路最後都要核對同一組指紋。",
    cloudPairFromMachineTitle: "從機器開始",
    cloudPairRecommended: "安裝後建議走這條",
    cloudPairFromMachineWhen: "你正在機器前，或已經連進它的終端機時，走這條。",
    cloudPairFromMachineStep1: "在那台機器執行下面的指令；它會印出一個一次性連結。",
    cloudPairFromMachineStep2: "用這個瀏覽器打開連結，配對畫面會出現在這裡。",
    cloudPairFromMachineSuccess: "完成時，兩邊顯示的機器指紋必須相同；不同就不要使用這次配對。",
    cloudPairFromBrowserTitle: "從這個瀏覽器開始",
    cloudPairFromBrowserWhen: "那台機器只能透過 SSH 或其他終端機連進去時，走這條。",
    cloudPairFromBrowserStep1: "先在這裡產生完整的 Agent 指示，再貼給能操作那台機器的 AI Agent。",
    cloudPairFromBrowserStep2: "機器回應以前，保持這一頁開著。",
    cloudPairFromBrowserSuccess: "完成時，機器印出的瀏覽器指紋，以及這裡顯示的機器指紋，都必須吻合。",
    cloudPairGenerate: "產生給 Agent 的指示",
    cloudPairWhy:
      "只登入帳號還讀不到機器：金鑰是那台機器自己交出來的，而且只交給在那台機器上收到的代碼。這樣帳號密碼就不會變成進你終端機的門。",
    cloudPairAsking: "正在跟 Clawdline Cloud 要一組配對代碼…",
    cloudPairRun: "把下面整段貼給能操作 {machine} 的 AI Agent：",
    cloudPairRunAny: "把下面整段貼給能操作目標機器的 AI Agent：",
    cloudPairTargetAny: "要配對的那台機器",
    cloudPairAgentPrompt:
      "請在目標機器 {machine} 上完成 Clawdline Cloud 配對。先確認你目前操作的就是這個確切目標；如果不是，請用既有且已授權的方式連到它，或把工作交給正在那台機器上執行的 Agent。不要在目前這台機器代跑。\n\n在目標機器上，將以下一次性指令原樣執行一次：\n{command}\n\noffer 是短效、只能使用一次的秘密；不要解碼、修改、保存，也不要在回覆中重貼。成功後請在同一台機器執行 `clawdline cloud devices`，核對瀏覽器與機器指紋，並回報結果但不要附上 offer。",
    cloudPairSettings: "有 Clawdline 設定視窗的機器，也可以把 -offer 後面那一串貼進「瀏覽器顯示的配對碼」那一欄。",
    cloudPairCopy: "複製給 AI Agent",
    cloudPairCopied: "已複製 Agent 指示。",
    cloudPairCopyFailed: "這個瀏覽器不讓這一頁複製，請手動選取完整指示。",
    cloudPairYourKey: "這個瀏覽器的指紋：{fingerprint}",
    cloudPairYourKeyCheck: "那台機器配好時，會在 browser 那一行印出一組指紋，必須和這一組相同。",
    cloudPairExpires: "這組代碼到{time}為止有效。",
    cloudPairWaiting: "正在等那台機器回應…",
    cloudPairStopped: "已經不等了。這組代碼到{time}以前仍然有效，這裡沒有辦法把它作廢。",
    cloudPairStoppedEarly: "已經不等了。",
    cloudPairDone: "配對好了，這個瀏覽器現在有 {machine} 的金鑰。",
    cloudPairMachineKey: "{machine} 的指紋：{fingerprint}",
    cloudPairMachineKeyCheck: "那台機器在 machine 那一行印出了它自己的指紋，兩組必須相同。不一樣就表示代碼到了別台機器：不要用這次配對。",
    cloudPairOther: "回應的是 {other}，不是 {machine}；配對好的是 {other}。",
    cloudPairReload: "重新載入，開始讀取",
    cloudPairExpired: "那台機器回應之前，這組代碼就過期了，什麼都沒有配對。",
    cloudPairAgain: "產生新的代碼",
    cloudPairRefused: "這次配對不是這個瀏覽器能完成的（{code}）：它屬於別的帳號，或已經用過了。什麼都沒有配對。",
    cloudPairFailed: "配對沒有完成（{code}）。那台機器如果有印出原因，那一句說得比較完整。",
    cloudPairLinkLede: "這一頁是從一台機器的配對連結打開的",
    cloudPairLinkFine: "配對會把那台機器的金鑰交給這個瀏覽器。只回應你剛剛從自己機器上拿到的連結。",
    cloudPairLinkGo: "和它配對",
    cloudPairLinkWaiting: "已經回應，正在等那台機器交出金鑰…",
    cloudPairLinkExpired: "這個連結已經過期了：機器印出的連結只有大約三分鐘。改從機器清單配對，那裡的代碼有效得比較久，也會寫出到幾點。",
    cloudPairLinkBad: "這不是這一頁讀得懂的配對連結（{code}）。",
    cloudMachineSessionsUnread: "這裡讀不到它的 session",
    cloudMachineSessionsUnknown: "還不知道有幾個 session",
    cloudMachineActions: "{machine} 的操作",
    cloudMachineID: "ID {id}",
    cloudMachinePlatformMac: "macOS",
    cloudMachinePlatformLinux: "Linux",
    cloudMachinePlatformLinuxAWS: "AWS 上的 Linux",
    cloudMachinePlatformUnknown: "這裡讀不到平台",
    cloudMachineSeen: "上次看到：{time}",
    cloudMachineSeenAt: "上次看到：{time}",
    cloudMachineSeenUnknown: "這裡不知道上次看到的時間",
    devicesPairHelp: "按「配對」，這一頁會產生完整指示，讓你直接貼給能操作那台機器的 AI Agent。",
    cloudDeviceLimit: "帳號 {account} 的觀看裝置已經有 {limit} 台（{tier}）。這一版還不能在這裡移除舊裝置。",
    cloudInstallLede: "請先把 Clawdline 加到主畫面",
    cloudInstallFine: "在 iPhone 與 iPad 上，Safari 頁面產生的金鑰搬不進主畫面的 app。請把這一頁加到主畫面，從那裡打開，在那裡登入。",
    cloudMachinesLede: "選一台機器",
    cloudMachinesFine: "帳號 {account} · 這個瀏覽器 {device}",
    cloudMachinesWaiting: "正在等這個帳號的機器回報…",
    cloudMachinesNone: "這個帳號還沒有任何機器回報。",
    cloudMachinesRefusedSignIn: "Clawdline Cloud 拒絕讀取機器清單（{code}）。請重新登入。",
    cloudMachinesRefusedPair: "這個瀏覽器解不開清單裡的機器資料（{code}）。請把那台機器和這個瀏覽器重新配對。",
    cloudMachinesRefusedRetry: "機器清單這次沒有回應（{code}）。請檢查這個瀏覽器的網路，再試一次。",
    sessionsListWaitTitle: "在等這台機器的清單",
    sessionsListWaitHint: "線已經通了。這台機器還沒說它現在有哪些 session。",
    sessionsListIncompleteTitle: "這台機器的清單沒有讀完整",
    sessionsListUnansweredTitle: "session 清單沒有回答",
    screenSessionGone: "這個 session 已經不在了；請關閉畫面，回到 session 清單。",
    screenForbidden: "這個分頁沒有權限讀取畫面；請到那台機器的本機 console 查看。",
    screenUnanswered: "Clawdline 沒有回答畫面讀取；請檢查連線後再試。",
    schedulePlacesUnanswered: "地點清單沒有回答；請檢查這個瀏覽器到 Clawdline 的連線後再試。",
    scheduleMachineField: "機器",
    schedulePermissionField: "權限",
    schedulePermissionDefault: "這台機器的預設",
    schedulePermissionAsk: "每一步都問我",
    schedulePermissionEdits: "可以直接改檔案",
    schedulePermissionFull: "完全權限（不再詢問）",
    schedulePermissionFullWarning: "完全權限的排程每次執行時，會在沒有人看著的情況下，不經詢問就執行任何指令、修改任何檔案。",
    scheduleMachineOffline: "{machine}：離線（最後在線 {time}）",
    scheduleMachineUnread: "{machine}：離線／讀不到",
    scheduleMoving: "正在搬到 {machine}…",
    scheduleMoved: "已搬到 {machine}。",
    scheduleMoveWebhookMoved: "webhook 也一起搬到 {machine}，網址不變。",
    scheduleMoveWebhookLeftDisabled: "它原本綁的 webhook 已停用，所以沒有一起搬；需要的話請在 {machine} 上重新產生一個。",
    scheduleMoveHookMoveFailed: "Clawdline Cloud 沒有搬動 webhook，所以排程沒有搬：它仍在 {source}，webhook 維持原狀。{why}",
    scheduleMoveHookBindFailed:
      "{machine} 沒有接下 webhook，所以這次搬移已經復原：排程仍在 {source}。如果 {machine} 上的 Clawdline 比 webhook 綁定功能還舊，請先更新再搬。{why}",
    scheduleMoveHookStranded:
      "「{title}」的 webhook 現在在 {machine} 上，處於暫停：呼叫它不會執行任何排程。修正方式：打開這個排程的 webhook，停用後重新產生一個（網址會換）。",
    scheduleMoveCopyLeft: "{machine} 上的那份複本沒能刪掉：它還在那裡，而且是啟用的。請到 {machine} 刪掉它。",
    scheduleMoveSourceLeftDisabled: "{source} 上的原排程沒能重新啟用：它還在那裡，目前停用。請把它打開。",
    scheduleMoveTargetOffline: "{machine} 目前離線，排程沒有搬。等那台機器上線後再搬。",
    scheduleMoveTargetOutdated:
      "{machine} 上的 Clawdline 版本太舊，還不會說每個專案 clone 自哪個 repository，所以排程沒有搬。請先更新 {machine} 上的 Clawdline 再搬。",
    scheduleMoveSourceOutdated:
      "{machine} 上的 Clawdline 版本太舊，還不會說這個專案 clone 自哪個 repository，所以排程沒有搬。請先更新 {machine} 上的 Clawdline 再搬。",
    scheduleMoveNoOrigin:
      "「{project}」沒有 origin remote，在別台機器上找不到同一個專案，所以沒辦法搬。請替它設定 origin，或直接在另一台機器上新增排程。",
    scheduleMoveSourceUnlisted:
      "「{project}」已經不在 {machine} 的專案清單裡，沒辦法先在那裡停用這個排程再搬。請在 {machine} 上開過一次這個專案再搬。",
    scheduleMoveNoProject: "{machine} 上沒有 clone 自 {repo} 的專案。請先在那台機器 clone 並開過一次，再搬這個排程。",
    scheduleMoveWebhookUnknown: "讀不到「{title}」在 {machine} 上有沒有綁 webhook，所以沒有搬。請再試一次。",
    scheduleMoveSpent: "「{title}」是只跑一次的排程，而且已經跑過了；搬過去會再跑一次。請直接在另一台機器新增一個。",
    scheduleMoveTargetTooOld: "{machine} 上的 Clawdline 版本太舊，收不下這個排程帶著的設定。請先更新 {machine} 上的 Clawdline 再搬。",
    scheduleMoveHookStale: "Clawdline Cloud 發現 webhook 在搬移途中被改過，所以沒有啟用它。請再搬一次。",
    scheduleMovePathRewritten: "第一則訊息裡的路徑已換成 {path}。",
    scheduleMoveNotStarted: "{source} 沒有停用這個排程，所以什麼都沒搬。{why}",
    scheduleMoveCreateFailed: "{machine} 拒絕建立這份排程，排程仍在 {source}，維持原狀。{why}",
    scheduleMoveCreateFailedDisabled: "{machine} 拒絕建立這份排程，而 {source} 上的原排程沒能重新啟用：它還在那裡，目前停用。{why}",
    scheduleMoveDeleteFailed: "排程已經在 {machine} 上執行。舊的那份還在 {source}，目前停用；請到那台機器刪掉它。{why}",
    cloudMachineSessions: "{count} 個 session",
    cloudAccessProblem: "機器 {machine} 的資料在這個瀏覽器讀不出來（{code}）。請重新配對這台機器；若仍然讀不到，請重新登入。",
    cloudSwitch: "換一台機器",
    cloudCurrentMachine: "目前機器",
    cloudManageMachines: "管理機器",
    cloudConnRetry: "再試一次",
    cloudForget: "忘記",
    cloudForgetOne: "忘記 {machine}",
    cloudForgetTitle: "要忘記 {machine} 嗎？",
    cloudForgetAsk:
      "{machine} 會從這個帳號移除。這件事在這裡沒有回頭路：它只有在那台機器上重新登入才會回來，而且回來的時候是一台新的機器、新的 id。",
    cloudForgetAskCurrent: "這台機器剛剛還在回報。忘記它會立刻停掉它現在的連線。",
    cloudForgetAskStale: "這台機器已經有一陣子沒有回報了。",
    cloudForgetAskUnknown: "這個瀏覽器沒有看過這台機器回報。",
    cloudForgetHonest: "routing 會立刻停止。但已經握有主金鑰的裝置，仍然解得開它先前錄下的密文；金鑰輪替是延遲的。",
    cloudForgetting: "正在忘記 {machine}…",
    cloudForgotten: "{machine} 已經忘記了，它不在這個帳號上了。",
    cloudForgottenRow: "已忘記",
    cloudForgetSaid: "Clawdline Cloud 說：{note}",
    cloudForgetHonestUnread: "Clawdline Cloud 沒有說這對已經發出去的金鑰有什麼影響，所以這一頁也不替它說。",
    cloudForgetRefused: "Clawdline Cloud 拒絕忘記 {machine}（{code}）：這個瀏覽器已經不是那個帳號的登入狀態。什麼都沒有改變。",
    cloudForgetAbsent: "這個帳號上沒有 {machine} 這台機器（{code}）。什麼都沒有改變。",
    cloudForgetUnreadable:
      "Clawdline Cloud 對「忘記 {machine}」的回應讀不到（{code}），所以不知道它到底有沒有被忘記。請重新整理這一頁再看一次，不要直接再按一次。",
    cloudRename: "改名",
    cloudRenameOne: "把 {machine} 改名",
    cloudRenameTitle: "要把 {machine} 改名嗎？",
    cloudRenameAsk: "這會改掉 {machine} 在這個帳號上的名字，每一個登入這個帳號的瀏覽器都會看到新的。機器本身不會有任何改變。",
    cloudRenameLater: "這份清單是各台機器自己上次說的，所以在這一台重新回報之前，它還是會顯示舊的名字。",
    cloudRenameField: "新的名字",
    cloudRenaming: "正在把 {machine} 改名…",
    cloudRenamed: "{machine} 在這個帳號上現在叫做 {name}。",
    cloudRenameRefused: "Clawdline Cloud 拒絕把 {machine} 改名（{code}）：這個瀏覽器已經不是那個帳號的登入狀態。什麼都沒有改變。",
    cloudRenameAbsent: "這個帳號上沒有 {machine} 這台機器（{code}）。什麼都沒有改變。",
    cloudRenameUnreadable:
      "Clawdline Cloud 對「把 {machine} 改名」的回應讀不到（{code}），所以不知道名字到底有沒有改成功。請重新整理這一頁、看過清單之後再決定要不要再改一次。",
    cloudRenameTooLong: "在這個帳號上，一台機器的名字最多 {max} 個字元。",
    cloudBlocked: "這個 console 是給 {origin} 用的，現在卻從 {here} 打開，所以不會連線。",
    devicesLedeAccount: "這個帳號上的機器、目前狀態，以及這個瀏覽器能不能讀取它們。",
    devicesLedeThisMachine:
      "只有服務這一頁的那一台機器。daemon 服務的 console 連不到別台；帳號上有哪些機器，要問 Clawdline Cloud 的 console。",
    devicesThisMachine: "這台機器",
    signedInTitle: "登入這台機器的裝置",
    signedInLede: "用 clawdline open 開的瀏覽器、用配對碼配對的裝置，以及用密碼登入的裝置。撤銷之後，它的下一個請求就會被拒絕。",
    signedInThisWindow: "這個視窗用的是這台機器自己的金鑰，不在清單裡，也不能在這裡撤銷。",
    signedInNone: "除了這台機器自己，沒有其他裝置登入。",
    signedInPassword: "已經設定密碼：知道密碼的人都能再登入一台裝置。",
    signedInCapsRead: "只能讀",
    signedInCapsSend: "可讀、可傳送",
    signedInSince: "{time} 登入",
    signedInLastSeen: "最後使用：{time}",
    signedInNeverSeen: "daemon 啟動後還沒用過",
    signedInRevoke: "撤銷",
    signedInRevokeOne: "撤銷 {name}",
    signedInRevokeAsk: "要撤銷 {name}（{id}）嗎？用它登入的瀏覽器或裝置，下一個請求就會被拒絕，必須重新登入。",
    signedInRevokeConfirm: "確定撤銷",
    signedInCancel: "取消",
    signedInRevoked: "已撤銷 {name}。",
    signedInFailed: "讀不到登入的裝置：{why}",
    signedInRevokeFailed: "{name} 沒有撤銷：{why}",
    signedInThisBrowser: "這個瀏覽器是以自己的裝置身分登入的。完整清單只會顯示在這台機器的 App 視窗，或在終端機執行 clawdline devices。",
    signedInSignOut: "登出這個瀏覽器",
    signedInSignOutAsk: "要登出這個瀏覽器嗎？它的金鑰會立刻撤銷；要回來，得再用 clawdline open 或配對碼登入。",
    signedInSignOutConfirm: "確定登出",
    signedInSignOutFailed: "這個瀏覽器沒有登出：{why}",
    cloudMisdeclared: "這個 console 的 Clawdline Cloud 宣告不能用：{reason}",
    cloudNotCarried: "這件事還不能經由 Clawdline Cloud 做，請直接在那台機器上操作。",
    todosReadFailed: "讀取失敗",
    todosRefreshFailed: "更新失敗",
    todosRetrying: "重試中…",
    todosRetryTip: "最近一次讀取待辦失敗：{reason}。點一下重試。",
    cloudPastUnavailable:
      "這台機器還不能經由 Clawdline Cloud 列出以前的 session（它不回答 past-sessions），所以這裡沒辦法接續。請到那台機器上接續，或在這裡開一個新的 session。",
    sendUnknown: "不知道有沒有送到那台機器（{code}）。",
    sendUnsubmitted: "字已經打進那台機器這個 session 的輸入列，但沒有按下 Enter（{code}）。請到那台機器上按 Enter，或把它清掉；再送一次會打成兩份。",
    sendLook: "去看看",
    sendLookTip: "重新讀一次那台機器上的對話：如果已經在裡面，這張卡就會消失。",
    sendLooking: "正在看…",
    sendAbsent: "那台機器上的對話裡沒有這則（{code}）。",
    sendAgain: "再送一次",
    sendAgainTip: "如果第一次其實有送到，這次不會重打。",
    sendInterrupted: "送出到一半這一頁被重新載入了，不知道有沒有送到那台機器。",
    sendKeptWords: "重新載入時這一頁留住了文字，但沒有留住圖片，所以這一則不能從這裡再送一次。",
    menuUnknown: "不知道剛才的選擇有沒有送到那台機器，等畫面更新。",
    menuChooseAgain: "重新選擇",
    menuUnreadSay: "Claude Code 正在那台機器上顯示一個選單，Clawdline 沒能從畫面讀出它的選項。",
    menuUnreadHow:
      "*直接送訊息不會回答它。*打開即時畫面看它在問什麼，或取消這個選單（等於在那台機器上按 Esc），再用下面的輸入框說你的答案。",
    menuCancel: "取消這個選單（Esc）",
    menuCancelSent: "已送出 Esc。選單關掉後，用輸入框說你的答案。",
    menuTicked: "已打勾。要按 Submit 才會送出。",
    newBuild: "已經有新版的 Clawdline，這個頁面還是舊的那一份。",
    newBuildReload: "重新載入",
    menuMoved: "送到之前題目已經換了，所以什麼都沒打。請看清楚新的題目再選。",
    menuUnverified: "這台機器經由 Clawdline Cloud 還無法確認答案對應哪一題，請直接到那台機器上作答。",
    linksNotRepository: "這裡不是 git repository，所以沒有東西可以對應到一次 workflow 執行。這份清單上其他項目都讀到了。",
    linksNoRemote: "這個 repository 沒有 origin remote，而 workflow 執行是用 remote 命名的，所以找不到 deploy。這份清單上其他項目都讀到了。",
    linksRemoteNotGitHub: "這個 repository 的 origin 不在 GitHub 上，而這裡只有 GitHub 的 remote 對得到 workflow 執行，所以找不到 deploy。",
    linksGitUnreadable: "git 在這裡沒有回答（{reason}），所以這個專案有沒有 deploy 是不知道，不是沒有。",
    linksGitMissing: "這台機器上沒有 git",
    linksGitTimeout: "它沒有在時限內回答",
    linksGitFailed: "它拒絕了",
    linksGitTooLarge: "它回的東西超過這裡讀得下的量",
    linksDeployNoRun:
      "狀態列的工具沒有可以報的 workflow 執行紀錄（它寫下的是「{state}」）。{reason}",
    linksDeployNoPage:
      "狀態列的工具說這個 repository 最新的 workflow 執行是「{state}」，但沒有給可以打開的頁面，所以這份清單上沒有這一列。{reason}",
    linksDeployNoFile:
      "這個 repository 在 GitHub 上，而這台機器上還沒有人替它寫下 workflow 的讀數——所以沒有 deploy 這一列是因為沒有人在看，不是因為沒有執行紀錄。寫這些檔案的是狀態列的指令，不是這個 app。",
    linksDeployUnreadable:
      "這台機器上有這個 repository 的 workflow 檔案，但它讀不成一個小小的 JSON 物件，所以有沒有 deploy 是不知道，不是沒有。",
    linksDeployRunningStale:
      "狀態列的工具最後說有一次部署正在跑，之後就再也沒寫過任何東西，而且已經超過這裡允許部署沉默的時間——所以不再畫成進行中。那次部署多半已經結束或被中斷，只是工具沒有記下結果。",
    linksDeployBecause: "它給的理由是：{reason}。",
    linksDeployNoWhy: "它沒有說為什麼。",
    linksDeployWhyNoGh: "這台機器上沒有 `gh` 指令可以去問 GitHub",
    linksDeployWhyNoBranch: "它在這裡取不到分支名稱，所以沒有東西可以查",
    linksDeployWhyGhFailed: "`gh` 沒有回答——沒登入、逾時，或是被拒絕",
    linksDeployWhyNoRuns: "這個分支上一次 workflow 都還沒有跑過",
    linksDeployWhyWorkflowDisabled:
      "那個 workflow 已經停用，所以最後一次失敗永遠不會被取代，也就不算現況",
    linksDeployWhyStaleFail:
      "上一次執行是失敗的，而那已經久到不再算是現在的狀態",
    linksDeployWhyUnknown: "這個工具說了一個我不認得的理由：「{why}」。",
    linksDeployWhen: "那個工具最後一次寫下這件事：{when}。",
    linksTruncated: "找到的位址比這份清單裝得下的多，其餘沒有列出。",
    endNamedTitle: "要關閉 {session} 嗎？",
    endWorkChecking: "正在確認這個 Session 尚未完成的看板項目…",
    endWorkCompletedSummary: "已完成 {work} 個看板項目、{todos} 個 TODO",
    endWorkOpenHeading: "還有未完成項目",
    endWorkBoardLabel: "看板",
    endWorkTodoLabel: "TODO",
    endWorkNoOpen: "沒有未完成的看板項目或 TODO。",
    endWorkCloseUnknown: "Clawdline 還不能確認這個 Session 是否適合關閉。",
    endWorkReadyToClose: "若沒有 Clawdline 以外尚未交付的工作，現在可以安全關閉這個 Session。",
    endWorkSafeToClose: "Clawdline 已確認這個 Session 可以安全關閉。",
    endWorkClose: "關閉 Session",
    endWorkConfirmClose: "安全關閉",
    endWorkTruncated: "尚有其他 Session 工作未列在這份提醒中。",
    endWorkUnreadable: "Clawdline 無法讀取這個 Session 尚未完成的看板項目；關閉前請先查看 Session 待辦。",
    swipeCloseAction: "關閉 Session",
    swipeEndLabel: "關閉 {session}",
    brokerWork: "由 Clawdline 派出",
    providerWork: "由助理派出",
    brokerTasksUnknown: "還不知道派出的工作",
    agentsNoRecord: "還沒有紀錄",
    agentsUnknown: "還不知道",
    bgShellOne: "1 個背景 shell",
    bgShellMany: "{n} 個背景 shell",
    bgAgentRunningOne: "1 個 subagent 在跑",
    bgAgentRunningMany: "{n} 個 subagent 在跑",
    bgAgentListedOne: "1 個 subagent",
    bgAgentListedMany: "{n} 個 subagent",
    bgAgentUnknown: "subagent ?",
    bgTitle: "背景工作",
    bgOpen: "看背景 shell 和 subagent",
    bgClose: "關閉",
    bgShellsNone: "沒有正在跑的背景 shell。",
    agentsUnreadable: "讀不到",
    agentsUnrecognized: "不認得這個格式",
    agentsTruncated: "還有 {count} 件較舊工作未列出",
    projectsTitle: "專案",
    projectsLede: "助理實際執行過、而且仍存在的目錄。",
    projectsBack: "‹ 專案",
    projectsRepositoryLifecycle: "版本庫生命週期",
    projectsWorktrees: "工作樹",
    projectsRefreshObservation: "重新觀測",
    projectsLifecycleBoundary: "唯讀總覽。重新整理只會向擁有這個版本庫的機器取得一次有界觀測；瀏覽器刻意不提供清理操作。",
    projectsDeliveredNotLanded: "做完了，沒有落地",
    projectsUnattributedWorktrees: "歸不到專案的工作樹",
    proposalNeedsYourDecision:
      "系統沒有待辦可重新判定；工作完成不會撤回這筆提議，請自行回答，否則它會等到過期。",
    proposalNotNow: "現在不要",
    proposalResolve: "已完成／已不存在",
    proposalResolveSummary: "哪件事已完成，或哪個前提已不存在？",
    proposalResolveEvidence: "出處：檔案:行號、指令輸出或 daemon 回應",
    proposalResolveSubmit: "記成已解決",
    imageMarkupTitle: "標記要修改的地方",
    imageMarkupHint: "單指用紅筆圈選，雙指移動或縮放。",
    imageMarkupCanvas: "圖片標記畫布",
    imageMarkupTools: "圖片工具",
    imageMarkupRedPen: "紅筆",
    imageMarkupMove: "移動",
    imageMarkupZoom: "圖片縮放",
    imageMarkupZoomOut: "縮小",
    imageMarkupZoomIn: "放大",
    imageMarkupUndo: "復原",
    imageMarkupCancel: "取消",
    imageMarkupDone: "完成",
    smartTitleButton: "智能命名",
    smartTitleAction: "智能命名這個 session",
    smartTitleConfirmTitle: "要智能命名這個 session 嗎？",
    smartTitleConfirmSay:
      "Clawdline 會把這個 session 的需求與助理最新的回覆交給 {assistant} 跑一次小型模型 turn，再把答案存成 session 標題；這會使用該助理的額度。取消就不會呼叫模型，也可以改用手動編輯標題。",
    smartTitleWorking: "命名中…",
    smartTitleSaved: "智能標題已儲存。",
    smartTitleOutOfQuota:
      "{assistant} 的額度已用完，標題沒有變更。等額度恢復，或到「設定 → 自動命名新的 session」改用另一個助理再試。",
    smartTitleFailed: "{assistant} 沒有回傳可用的標題，標題沒有變更。",
    smartTitleNoNamer: "設定裡選的命名助理 {assistant} 沒有安裝在這台機器上。",
    smartTitleConfirmSayAuto:
      "Clawdline 會把這個 session 的需求與助理最新的回覆交給 Claude Code 跑一次小型模型 turn；只有在 Claude Code 額度用完或沒安裝時，才改交給 Codex。答案會存成 session 標題，並使用實際回答的那個助理的額度。取消就不會呼叫模型，也可以改用手動編輯標題。",
    smartTitleSavedBy: "智能標題已儲存（由 {assistant} 命名）。",
    smartTitleOutOfQuotaAll: "Claude Code 和 Codex 的額度都已用完，標題沒有變更。等其中一個額度恢復再試。",
    smartTitleNoNamerAll: "這台機器上沒有安裝 Claude Code，也沒有 Codex，標題沒有變更。",
    sessionStop: "停止目前的工作（Esc）",
    sessionStopSent: "已送出 Esc，session 讀到後會停下目前這一輪。",
    pushCloudReached: "通知已開啟：{machines} 會通知這台裝置。",
    pushCloudUnreached: "{machines} 這次沒收到（{why}），下次打開這一頁會再送。",
    pushCloudNoMachine: "這台裝置的通知已開啟，但帳號上還沒有機器收下；下次打開這一頁會再送。",
    pushCloudOffUntold: "這台裝置已經不會收到通知，但沒能通知 {machines}：{why}",
    restoreCardTitle: "上次重新開機前開著 {n} 個 session",
    restoreCardTitleOne: "上次重新開機前開著 1 個 session",
    restoreCardHint: "重新開機或當機把它們關掉了，可以接著原本的對話重新打開。",
    restoreCardOpen: "查看並恢復",
    restoreSheetTitle: "重新開機前開著的 session",
    restoreSheetSay: "勾選的 session 會在原本的資料夾、用原本的助手重新打開，接著原本的對話。",
    restoreLastSeen: "最後看到：{time}",
    restoreGo: "恢復選取的 {n} 個",
    restoreGoing: "恢復中…",
    restoreDismissAll: "全部略過",
    restoreDismissing: "略過中…",
    restoreCancel: "取消",
    restoreDone: "完成",
    restoreOpened: "已打開。",
    restoreOpening: "打開中…",
    restoreFailedNotRestorable: "已經不在可恢復的清單上：它現在開著，或已經恢復、略過了。",
    restoreFailedPlaceUnavailable: "它的資料夾已經不是這台機器能打開的地方。",
    restoreFailedNotFound: "助手在這個資料夾下已經找不到這段對話。",
    restoreFailedOpen: "終端機沒能打開它。",
    restoreFailedBusy: "其他 session 正在打開，請再試一次。",
    restoreFailedUnknown: "沒有打開。",
    restoreFailedSaid: "沒有打開：{why}",
    restoreRefused: "機器沒有接受：{why}",
    restoreUnknownOutcome: "沒有收到回覆，不確定有沒有打開。下方清單已重新讀取。",
  },
} as const

export type NextWord = keyof (typeof words)["en"]

/** The page's language as the copied catalog set it, or the browser's. */
function language(): "en" | "zh-Hant" {
  const lang = (typeof document !== "undefined" && document.documentElement.lang) ||
    (typeof navigator !== "undefined" && navigator.language) || "en"
  return lang.toLowerCase().startsWith("zh") ? "zh-Hant" : "en"
}

/** One sentence, its holes filled. */
export function nextWord(key: NextWord, holes: Record<string, string | number> = {}): string {
  return words[language()][key].replace(/\{(\w+)\}/g, (all, name: string) =>
    name in holes ? String(holes[name]) : all,
  )
}

/** A byte count as a person reads it: 8 MB, 412.3 MB, 150 KB. */
export function byteWords(n: number): string {
  const units = ["B", "KB", "MB", "GB", "TB"]
  let value = n
  let unit = 0
  while (value >= 1024 && unit < units.length - 1) {
    value /= 1024
    unit++
  }
  const shown = unit === 0 || Number.isInteger(value) ? String(Math.round(value)) : value.toFixed(1)
  return shown + " " + units[unit]
}
